import {AsyncLocalStorage} from 'node:async_hooks';
import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {worldGenerationCandidateSaveSchema,worldGenerationCandidateSchema,worldGenerationPublishSchema,worldGenerationStartSchema,type FrozenWorldGenerationReference,type WorldGenerationCandidate,type WorldGenerationCapability,type WorldGenerationReceipt,type WorldGenerationSession} from '../../../common/worldGeneration';
import {PUBLIC_WORLD_SPACE_ID,type PublishedWorldPackage} from '../../../common/worldPackages';
import {assertFound,NewDesignError} from '../../domain/errors';
import {stableHash} from '../aiContracts';
import {getNewDesignPool} from '../runtime';
import {createCardInTransaction,DEFAULT_SPACE_ID} from '../store';
import {worldPackageCapability,requireWorldPackageCapability} from '../worldPackages/capability';
import {freezeWorldPackage} from '../worldPackages/freeze';
import {publishWorldPackageInTransaction} from '../worldPackages/publication';
import {createPackageRelation} from '../worldPackages/relations';

const pools=new AsyncLocalStorage<Pool>();
export const withWorldGenerationPool=<T>(pool:Pool,work:()=>Promise<T>)=>pools.run(pool,work);
export const getWorldGenerationPool=async()=>pools.getStore()??getNewDesignPool();
const iso=(value:unknown)=>value instanceof Date?value.toISOString():new Date(String(value)).toISOString();

export async function getWorldGenerationCapability():Promise<WorldGenerationCapability>{const pool=await getWorldGenerationPool(),row=(await pool.query("SELECT to_regclass('new_design.world_generation_sessions') IS NOT NULL sessions,to_regclass('new_design.world_generation_candidates') IS NOT NULL candidates,to_regclass('new_design.world_generation_publications') IS NOT NULL publications,EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('new_design.world_generation_candidates') AND tgname='world_generation_candidates_immutable' AND tgenabled='O') candidate_guard,EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('new_design.world_generation_sessions') AND tgname='world_generation_session_identity' AND tgenabled='O') session_guard,EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('new_design.model_route_snapshots') AND conname='model_route_snapshots_managed_scope_check' AND pg_get_constraintdef(oid) LIKE '%world_generation%') model_scope,EXISTS(SELECT 1 FROM new_design.relation_types WHERE relation_key='world_sample_relation' AND status='published') world_relation")).rows[0]??{},installed=Boolean(row.sessions&&row.candidates&&row.publications),operational=installed&&Boolean(row.candidate_guard&&row.session_guard&&row.model_scope&&row.world_relation);let publishOperational=false;if(operational)publishOperational=(await worldPackageCapability(pool)).operational;return{installed,operational,publishOperational,reason:!installed?'世界生成手动迁移 116 尚未启用。':!operational?'世界生成来源保护、关系规则或独立模型任务范围不完整，写入已停用。':!publishOperational?'候选生成可用，但公共世界包门禁未启用，发布已停用。':'世界候选生成、版本保护与明确发布可用。'};}
async function requireCapability(publish=false){const value=await getWorldGenerationCapability();if(!value.operational||publish&&!value.publishOperational)throw new NewDesignError(value.reason,503);}

function candidate(row:Record<string,unknown>,publishedId:string|null):WorldGenerationCandidate{return{id:String(row.id),sessionId:String(row.session_id),version:Number(row.version),requestKey:String(row.request_key),source:row.source as 'manual'|'ai',basedOnCandidateId:row.based_on_candidate_id?String(row.based_on_candidate_id):null,content:worldGenerationCandidateSchema.parse(row.candidate),status:row.id===publishedId?'published':'candidate',promptSnapshot:row.prompt_snapshot as Record<string,unknown>|null,modelSnapshot:row.model_snapshot as Record<string,unknown>|null,usedTokens:row.used_tokens===null?null:Number(row.used_tokens),createdAt:iso(row.created_at)};}
async function readSession(db:Pick<PoolClient,'query'>,id:string,lock=false):Promise<WorldGenerationSession>{const row=assertFound((await db.query(`SELECT * FROM new_design.world_generation_sessions WHERE id=$1 ${lock?'FOR UPDATE':''}`,[id])).rows[0],'世界生成会话不存在。'),rows=(await db.query('SELECT * FROM new_design.world_generation_candidates WHERE session_id=$1 ORDER BY version,id',[id])).rows,published=row.published_candidate_id?String(row.published_candidate_id):null;return{id:String(row.id),requestKey:String(row.create_request_key),name:String(row.name),blueprint:row.blueprint,frozenReferences:row.frozen_references,sourceHash:String(row.source_hash),status:row.status,revision:Number(row.revision),failure:row.failure===null?null:String(row.failure),publicRootCardId:row.public_root_card_id?String(row.public_root_card_id):null,publishedPackageId:row.published_package_id?String(row.published_package_id):null,publishedCandidateId:published,candidates:rows.map(item=>candidate(item,published)),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)};}
async function freezeReferences(db:Pick<PoolClient,'query'>,references:Array<{cardId:string;versionId:string}>):Promise<FrozenWorldGenerationReference[]>{const result=[];for(const item of references){const row=assertFound((await db.query("SELECT card.id card_id,card.current_version_id,card.status,version.id version_id,version.title,version.values,type.type_key FROM new_design.cards card JOIN new_design.card_versions version ON version.card_id=card.id JOIN new_design.card_types type ON type.id=card.card_type_id WHERE card.id=$1 AND version.id=$2 AND card.space_id=$3 AND card.status='active' AND type.status='published'",[item.cardId,item.versionId,PUBLIC_WORLD_SPACE_ID])).rows[0],'所选世界参考版本不存在或不属于公共资源。');const value={cardId:String(row.card_id),versionId:String(row.version_id),title:String(row.title),typeKey:String(row.type_key),values:row.values as Record<string,unknown>};result.push({...value,hash:stableHash(value)});}return result;}
async function referencesCurrent(db:Pick<PoolClient,'query'>,items:FrozenWorldGenerationReference[]){for(const item of items)if(!(await db.query("SELECT 1 FROM new_design.cards WHERE id=$1 AND current_version_id=$2 AND status='active'",[item.cardId,item.versionId])).rowCount)throw new NewDesignError('世界参考来源已变化，原候选保留；请重新生成或明确更新参考版本。',409);}

export async function listWorldGenerationSessions():Promise<WorldGenerationSession[]>{await requireCapability();const db=await getWorldGenerationPool(),ids=(await db.query('SELECT id FROM new_design.world_generation_sessions ORDER BY updated_at DESC,id DESC LIMIT 100')).rows,result=[];for(const row of ids)result.push(await readSession(db,String(row.id)));return result;}
export async function getWorldGenerationSession(id:string):Promise<WorldGenerationSession>{await requireCapability();return readSession(await getWorldGenerationPool(),id);}
export async function readWorldGenerationOriginal(requestKey:string):Promise<WorldGenerationSession|null>{await requireCapability();const db=await getWorldGenerationPool(),row=(await db.query('SELECT id FROM new_design.world_generation_sessions WHERE create_request_key=$1',[requestKey])).rows[0];return row?readSession(db,String(row.id)):null;}
export async function createWorldGenerationSession(raw:unknown):Promise<{session:WorldGenerationSession;repeated:boolean}>{const input=worldGenerationStartSchema.parse(raw);await requireCapability();const fingerprint=stableHash(input),pool=await getWorldGenerationPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`world_generation:create:${input.requestKey}`]);const prior=(await db.query('SELECT id,request_hash FROM new_design.world_generation_sessions WHERE create_request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.request_hash!==fingerprint)throw new NewDesignError('原世界生成凭证已用于不同输入，请保留原凭证。',409);const session=await readSession(db,String(prior.id));await db.query('COMMIT');return{session,repeated:true};}const references=await freezeReferences(db,input.blueprint.references),sourceHash=stableHash({blueprint:input.blueprint,references}),id=randomUUID();await db.query('INSERT INTO new_design.world_generation_sessions(id,create_request_key,request_hash,name,blueprint,frozen_references,source_hash) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7)',[id,input.requestKey,fingerprint,input.name,JSON.stringify(input.blueprint),JSON.stringify(references),sourceHash]);const session=await readSession(db,id);await db.query('COMMIT');return{session,repeated:false};}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function saveWorldGenerationCandidate(sessionId:string,raw:unknown,execution?:{promptSnapshot:Record<string,unknown>;modelSnapshot:Record<string,unknown>;usedTokens:number}):Promise<{session:WorldGenerationSession;candidate:WorldGenerationCandidate;repeated:boolean}>{const input=worldGenerationCandidateSaveSchema.parse(raw);if(input.source==='ai'&&!execution)throw new NewDesignError('AI 世界候选缺少原提示词与模型回执。',422);if(input.source==='manual'&&execution)throw new NewDesignError('人工修订不能附冒充的模型回执。',422);await requireCapability();const fingerprint=stableHash({sessionId,input}),pool=await getWorldGenerationPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`world_generation:candidate:${input.requestKey}`]);const prior=(await db.query('SELECT * FROM new_design.world_generation_candidates WHERE request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.request_hash!==fingerprint||prior.session_id!==sessionId)throw new NewDesignError('原候选凭证已用于不同世界输入。',409);const session=await readSession(db,sessionId);await db.query('COMMIT');return{session,candidate:candidate(prior,session.publishedCandidateId),repeated:true};}const session=await readSession(db,sessionId,true);if(session.revision!==input.expectedSessionRevision)throw new NewDesignError('世界会话已有新候选，请读取最新版本后再保存。',409);if(input.basedOnCandidateId&&!session.candidates.some(item=>item.id===input.basedOnCandidateId))throw new NewDesignError('修订基础候选不属于当前世界会话。',422);const id=randomUUID(),version=(session.candidates.at(-1)?.version??0)+1,row=(await db.query('INSERT INTO new_design.world_generation_candidates(id,session_id,version,request_key,request_hash,source,based_on_candidate_id,candidate,prompt_snapshot,model_snapshot,used_tokens) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11) RETURNING *',[id,sessionId,version,input.requestKey,fingerprint,input.source,input.basedOnCandidateId??null,JSON.stringify(input.candidate),execution?JSON.stringify(execution.promptSnapshot):null,execution?JSON.stringify(execution.modelSnapshot):null,execution?.usedTokens??null])).rows[0];await db.query("UPDATE new_design.world_generation_sessions SET revision=revision+1,status=CASE WHEN status IN ('failed','result_unknown') THEN 'active' ELSE status END,failure=NULL,updated_at=now() WHERE id=$1",[sessionId]);const next=await readSession(db,sessionId);await db.query('COMMIT');return{session:next,candidate:candidate(row,next.publishedCandidateId),repeated:false};}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function failWorldGenerationSession(id:string,message:string,unknown=false){await requireCapability();await(await getWorldGenerationPool()).query("UPDATE new_design.world_generation_sessions SET status=$2,failure=$3,updated_at=now() WHERE id=$1 AND status<>'published'",[id,unknown?'result_unknown':'failed',message]);return getWorldGenerationSession(id);}

async function typeId(db:PoolClient,key:string){return String(assertFound((await db.query("SELECT id FROM new_design.card_types WHERE type_key=$1 AND status='published' AND space_id IN ($2,$3) ORDER BY CASE WHEN space_id=$3 THEN 0 ELSE 1 END LIMIT 1",[key,DEFAULT_SPACE_ID,PUBLIC_WORLD_SPACE_ID])).rows[0],`公共世界缺少已发布内容类型：${key}`).id);}
async function savedVersion(db:PoolClient,id:string){return String(assertFound((await db.query('SELECT current_version_id FROM new_design.cards WHERE id=$1',[id])).rows[0],'公共世界资料未保存完整。').current_version_id);}
async function createPublicWorld(db:PoolClient,_name:string,content:ReturnType<typeof worldGenerationCandidateSchema.parse>,requestKey:string):Promise<PublishedWorldPackage>{
  await requireWorldPackageCapability(db);const cards:Array<{cardId:string;versionId:string;section:'profile'|'rules'|'factions'|'locations'}>=[],objects=new Map<string,string>();
  const overview=await createCardInTransaction(db,{spaceId:PUBLIC_WORLD_SPACE_ID,cardTypeId:await typeId(db,'world_overview'),title:content.title,values:{name:content.title,elevator_pitch:content.elevatorPitch,era:content.era,spatial_structure:content.spatialStructure,core_order:content.coreOrder,ordinary_life:content.ordinaryLife,major_tension:content.tensions.join('\n')},formResolutionKind:'type_schema'});cards.push({cardId:overview.id,versionId:await savedVersion(db,overview.id),section:'profile'});objects.set(content.title,overview.id);
  const rule=await createCardInTransaction(db,{spaceId:PUBLIC_WORLD_SPACE_ID,cardTypeId:await typeId(db,'world_rule'),title:`${content.title}：世界规则`,values:{era:content.era,world_summary:content.sixLayers.rules,geography:content.spatialStructure,society:[content.sixLayers.factions,content.sixLayers.relations].join('\n'),culture:content.ordinaryLife,power_rules:content.rules.map(item=>`${item.name}：${item.summary}；代价：${item.cost}`).join('\n'),hard_rules:content.rules.map(item=>`${item.name}：${item.boundary}；执行：${item.enforcement}`).join('\n')},formResolutionKind:'type_schema'});cards.push({cardId:rule.id,versionId:await savedVersion(db,rule.id),section:'rules'});
  for(const item of content.factions){const card=await createCardInTransaction(db,{spaceId:PUBLIC_WORLD_SPACE_ID,cardTypeId:await typeId(db,'organization'),title:item.name,values:{name:item.name,faction_type:'organization',purpose:item.goals.join('；'),leader:item.doctrine,resources:item.methods.join('；'),internal_conflict:item.position,external_stance:content.relations.filter(link=>link.source===item.name||link.target===item.name).map(link=>`${link.source}—${link.target}：${link.relation}，${link.tension}`).join('\n')},formResolutionKind:'type_schema'});cards.push({cardId:card.id,versionId:await savedVersion(db,card.id),section:'factions'});objects.set(item.name,card.id);}
  for(const item of content.locations){const card=await createCardInTransaction(db,{spaceId:PUBLIC_WORLD_SPACE_ID,cardTypeId:await typeId(db,'location'),title:item.name,values:{name:item.name,location_type:'world',appearance:item.summary,atmosphere:content.sixLayers.locations,story_function:content.sixLayers.tensions,risk:item.risk,access_rule:item.entryConstraint},formResolutionKind:'type_schema'});cards.push({cardId:card.id,versionId:await savedVersion(db,card.id),section:'locations'});objects.set(item.name,card.id);}
  const relationType=assertFound((await db.query("SELECT id FROM new_design.relation_types WHERE relation_key='world_sample_relation' AND status='published'")).rows[0],'公共世界缺少已发布关系规则。'),relationVersionIds:string[]=[];
  for(const item of content.relations){const source=objects.get(item.source),target=objects.get(item.target);if(!source||!target)throw new NewDesignError(`世界关系“${item.source}—${item.target}”缺少已发布对象，请先补齐候选。`,422);relationVersionIds.push((await createPackageRelation(db,PUBLIC_WORLD_SPACE_ID,String(relationType.id),source,target,{relation:item.relation,tension:item.tension})).versionId);}
  const raw={requestKey,rootCardId:overview.id,rootVersionId:cards[0].versionId,cards,relationVersionIds},preview=await freezeWorldPackage(db,raw,true);return(await publishWorldPackageInTransaction(db,{...raw,previewHash:preview.previewHash})).package;
}
export async function publishWorldCandidate(sessionId:string,raw:unknown):Promise<WorldGenerationReceipt>{const input=worldGenerationPublishSchema.parse(raw);await requireCapability(true);const fingerprint=stableHash({sessionId,input}),pool=await getWorldGenerationPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`world_generation:publish:${input.requestKey}`]);const prior=(await db.query('SELECT input_hash,receipt FROM new_design.world_generation_publications WHERE request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.input_hash!==fingerprint||prior.receipt.session.id!==sessionId)throw new NewDesignError('原发布凭证已用于不同世界候选。',409);await db.query('COMMIT');return{...prior.receipt,repeated:true};}const session=await readSession(db,sessionId,true);if(session.revision!==input.expectedSessionRevision)throw new NewDesignError('世界候选或发布状态已变化，请重新读取后确认。',409);if(session.publishedPackageId)throw new NewDesignError('该生成会话已有正式世界；原版本保留，请从世界工作区创建后续版本。',409);const selected=assertFound(session.candidates.find(item=>item.id===input.candidateId),'所选世界候选不属于当前会话。');await referencesCurrent(db,session.frozenReferences);const published=await createPublicWorld(db,session.name,selected.content,input.requestKey);await db.query("UPDATE new_design.world_generation_sessions SET status='published',revision=revision+1,failure=NULL,published_candidate_id=$2,public_root_card_id=$3,published_package_id=$4,updated_at=now() WHERE id=$1",[sessionId,selected.id,published.rootCardId,published.id]);const next=await readSession(db,sessionId),publishedCandidate=assertFound(next.candidates.find(item=>item.id===selected.id),'正式候选未读取。'),receipt:WorldGenerationReceipt={session:next,candidate:publishedCandidate,package:published,requestKey:input.requestKey,inputHash:fingerprint,repeated:false};await db.query('INSERT INTO new_design.world_generation_publications(id,session_id,candidate_id,request_key,input_hash,input,receipt) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb)',[randomUUID(),sessionId,selected.id,input.requestKey,fingerprint,JSON.stringify(input),JSON.stringify(receipt)]);await db.query('COMMIT');return receipt;}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
