import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {ExperienceWorkspace,ExperienceSnapshot,ExperienceActorSource,ExperienceRequest} from '../../../common/characterExperiences';
import {assertFound,NewDesignError} from '../../domain/errors';
import {getNewDesignPool} from '../runtime';
import {freezeFormContext} from '../formAssist';
import {resolveBookFormVersion} from '../referenceParity';
import {formAiFieldVisible} from '../../../common/formAssist';
async function bookSource(db:PoolClient,bookId:string){return assertFound((await db.query("SELECT id,space_id,name FROM new_design.books WHERE id=$1 AND status='active'",[bookId])).rows[0],'本书不存在或已归档。');}
export async function actorSource(db:PoolClient,bookId:string,characterId:string,fieldKey?:string):Promise<ExperienceActorSource>{
 const book=await bookSource(db,bookId),card=assertFound((await db.query("SELECT card.*,type.current_version_id type_version_id FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='character' AND type.status='published' WHERE card.id=$1 AND card.space_id=$2 AND card.status='active' AND card.current_version_id IS NOT NULL",[characterId,book.space_id])).rows[0],'人物不属于本书正式档案。');
 const resolution=await resolveBookFormVersion(db,book.space_id,'character'),locals=(await db.query("SELECT definition.field_key,local.value FROM new_design.card_version_local_values local JOIN new_design.field_definitions definition ON definition.id=local.field_definition_id WHERE local.card_version_id=$1 AND definition.scope='card' AND definition.status='active'",[card.current_version_id])).rows,values={...card.values,...Object.fromEntries(locals.map(row=>[row.field_key,row.value]))};
 const form=await freezeFormContext(db,{bookId,cardTypeId:card.card_type_id,cardId:characterId,typeVersionId:card.type_version_id,cardRevision:Number(card.revision),formVersionId:resolution?.id??null,title:String(card.title)},values,[]),field=fieldKey?form.fields.find(field=>field.key===fieldKey&&!field.hidden&&['short_text','long_text'].includes(field.type)&&formAiFieldVisible(field,values)):null;
 if(fieldKey&&(!field||typeof values[fieldKey]!=='string'||!String(values[fieldKey]).trim()))throw new NewDesignError('选择的小传字段不是本书可见的已填写文本；原填写保留，未发送模型请求。',422);
 return{id:characterId,title:String(card.title),versionId:String(card.current_version_id),revision:Number(card.revision),fieldKey:field?.key??'',fieldLabel:field?.name??'',text:field?String(values[field.key]):'',form,slotIds:[]};
}
async function events(db:PoolClient,spaceId:string){return(await db.query("SELECT card.id,card.current_version_id version_id,card.title FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='event' AND type.status='published' WHERE card.space_id=$1 AND card.status='active' AND card.current_version_id IS NOT NULL ORDER BY card.id LIMIT 301",[spaceId])).rows.map(row=>({id:String(row.id),versionId:String(row.version_id),title:String(row.title)}));}
export async function freezeExperienceSources(db:PoolClient,bookId:string,request:ExperienceRequest):Promise<ExperienceSnapshot>{
 const book=await bookSource(db,bookId),eventChoices=await events(db,book.space_id);if(eventChoices.length>300)throw new NewDesignError('事件资料超出单次经历准备范围，请先缩小本书资料范围；未发送模型请求。',422);
 const actors=[];for(const source of request.sources){const actor=await actorSource(db,bookId,source.characterId,source.fieldKey);actor.slotIds=[randomUUID(),randomUUID(),randomUUID()];actors.push(actor);}return{bookId,bookName:String(book.name),instruction:request.instruction,actors,events:eventChoices};
}
export async function getExperienceWorkspace(bookId:string,characterId:string):Promise<ExperienceWorkspace>{const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const book=await bookSource(db,bookId),actor=await actorSource(db,bookId,characterId),choices=(await db.query("SELECT card.id,card.title FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='character' AND type.status='published' WHERE card.space_id=$1 AND card.status='active' AND card.current_version_id IS NOT NULL ORDER BY card.id LIMIT 301",[book.space_id])).rows,eventChoices=await events(db,book.space_id),eventType=(await db.query("SELECT id FROM new_design.card_types WHERE space_id=$1 AND type_key='event' AND status='published' AND current_version_id IS NOT NULL",[book.space_id])).rows[0];const result={bookId,characterId,characterName:actor.title,sourceFields:actor.form.fields.filter(field=>!field.hidden&&['short_text','long_text'].includes(field.type)&&formAiFieldVisible(field,actor.form.values)&&typeof actor.form.values[field.key]==='string'&&String(actor.form.values[field.key]).trim()).map(field=>({key:field.key,label:field.name,text:String(actor.form.values[field.key])})),characters:choices.slice(0,300).map(row=>({id:String(row.id),title:String(row.title)})),events:eventChoices.slice(0,300),eventTypeId:eventType?String(eventType.id):null,truncated:choices.length>300||eventChoices.length>300};await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
