import {randomUUID,createHash} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {RecentBodyExperienceCandidateSource,RecentBodyExperienceDraft} from '../../../../common/characterExperiences/recentBodies';
import type {AuthorTimelineCommand,AuthorTimelineReceipt} from '../../../../common/bookComposition/timeline';
import {formHash} from '../../formAssist';
import {getNewDesignPool} from '../../runtime';
import {assertFound,NewDesignError} from '../../../domain/errors';
import {proposeStoryTime} from '../../storyTimeline';
import {freezeRecentBodyExperienceSources} from './sources';
import {readRecentBodyExperienceRow,recentBodyExperienceRecord,recentBodyExperienceContract} from '.';
async function original(db:PoolClient,bookId:string,batchId:string,candidateId:string){const saved=recentBodyExperienceRecord(assertFound(await readRecentBodyExperienceRow(db,bookId,batchId),'原正文经历不属于本书。'));if(saved.status!=='review'||!saved.output)throw new NewDesignError('原正文经历尚无完整结果，请只读核对。',409);const candidate=assertFound(saved.output.candidates.find(item=>item.id===candidateId),'原正文经历候选不存在。'),actor=assertFound(saved.snapshot.actors.find(actor=>actor.id===candidate.characterId),'原人物来源不存在。'),body=assertFound(saved.snapshot.bodies.find(body=>body.documentId===candidate.chapterDocumentId&&body.bodyVersionId===candidate.bodyVersionId),'原采用正文来源不存在。');const fresh=await freezeRecentBodyExperienceSources(db,bookId,{characterIds:saved.request.characterIds,chapterDocumentIds:saved.request.chapterDocumentIds});const frozen={...saved.snapshot,actors:saved.snapshot.actors.map(actor=>({...actor,slotIds:[]}))};if(fresh.sourceHash!==saved.request.expectedSourceHash||formHash(frozen)!==saved.request.expectedSourceHash)throw new NewDesignError('人物、采用正文、冻结计划、事件或原时间来源已变化；原候选和证据保留，未保存。',409);const source:RecentBodyExperienceCandidateSource={contract:'character_recent_body_candidate_v1',batchId,candidateId,characterId:actor.id,sourceHash:formHash({contract:recentBodyExperienceContract,bookId,batchId,candidate,sourceHash:saved.request.expectedSourceHash})};return{saved,candidate,actor,body,source};}
export async function getRecentBodyExperienceDraft(bookId:string,batchId:string,candidateId:string,eventId:string):Promise<RecentBodyExperienceDraft>{const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const data=await original(db,bookId,batchId,candidateId);const event=assertFound((await db.query("SELECT card.id FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='event' AND type.status='published' JOIN new_design.books book ON book.space_id=card.space_id WHERE book.id=$1 AND card.id=$2 AND card.status='active' AND card.current_version_id IS NOT NULL",[bookId,eventId])).rows[0],'请明确选择本书真实事件，未按名称合并。');await db.query('COMMIT');return{source:data.source,command:{operation:'time_create',eventCardId:String(event.id),value:{...data.candidate.time,evidenceKind:'manual',chapterDocumentId:null,bodyVersionId:null,textAnchorId:null,factId:null,planVersionId:null,stateProposalId:null}},title:data.candidate.title,summary:data.candidate.summary,evidence:data.candidate.evidenceLabel,sourceRoute:`/new-design/books/${bookId}/story-setting?tab=characters&selected=${data.actor.id}&detail=timeline&recentExperienceBatch=${batchId}`,bodySourceRoute:data.body.sourceRoute};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function validateRecentBodyExperienceCommandInTransaction(db:PoolClient,bookId:string,source:RecentBodyExperienceCandidateSource,command:AuthorTimelineCommand){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`recent-body-experience-candidate:${source.batchId}:${source.candidateId}`]);const data=await original(db,bookId,source.batchId,source.candidateId);if(formHash(source)!==formHash(data.source)||command.operation!=='time_create'||!['planned','occurred'].includes(command.value.lifecycle)||command.value.evidenceKind!=='manual')throw new NewDesignError('原正文经历来源或可核对时间提案不匹配，未保存。',409);if((await db.query("SELECT id FROM new_design.form_ai_draft_decisions WHERE batch_id=$1 AND candidate_id=$2 AND decision='adopt'",[source.batchId,source.candidateId])).rowCount)throw new NewDesignError('此原正文经历已有时间提案，请核对原保存结果，不重复创建。',409);return data;}
/** Only the explicit normal save creates body evidence, in the same physical transaction as its proposal and receipt. */
export async function saveRecentBodyExperienceTimeInTransaction(db:PoolClient,bookId:string,source:RecentBodyExperienceCandidateSource,command:AuthorTimelineCommand){const data=await validateRecentBodyExperienceCommandInTransaction(db,bookId,source,command);if(command.operation!=='time_create')throw new NewDesignError('请载入正文时间提案后再保存。',422);const anchorId=randomUUID(),excerpt=data.candidate.evidenceLabel;await db.query("INSERT INTO new_design.chapter_text_anchors(id,book_id,chapter_document_id,body_version_id,subject_card_id,role,label,start_offset,end_offset,excerpt,fragment_hash) VALUES($1,$2,$3,$4,$5,'reference',$6,$7,$8,$9,$10)",[anchorId,bookId,data.body.documentId,data.body.bodyVersionId,data.actor.id,data.candidate.title,data.candidate.evidenceStart,data.candidate.evidenceEnd,excerpt,createHash('sha256').update(excerpt,'utf8').digest('hex')]);return proposeStoryTime({...command.value,bookId,eventCardId:command.eventCardId,proposalSource:'ai',evidenceKind:'body',chapterDocumentId:data.body.documentId,bodyVersionId:data.body.bodyVersionId,textAnchorId:anchorId,editor:`user:recent-body-experience:${source.batchId}:${source.candidateId}`},db);}
export async function recordRecentBodyExperienceAdoptionInTransaction(db:PoolClient,bookId:string,source:RecentBodyExperienceCandidateSource,receipt:AuthorTimelineReceipt,inputHash:string){await db.query("INSERT INTO new_design.form_ai_draft_decisions(id,batch_id,candidate_id,decision,selected_field_keys,draft_snapshot,request_hash,source_hash,idempotency_key) VALUES($1,$2,$3,'adopt',ARRAY['time'],$4::jsonb,$5,$6,$7)",[randomUUID(),source.batchId,source.candidateId,JSON.stringify({contract:'character_recent_body_experience_adoption_v1',bookId,source,receipt}),inputHash,source.sourceHash,`recent-body-experience-time:${receipt.requestKey}`]);}
