import type {PoolClient} from 'pg';
import {randomUUID,createHash} from 'node:crypto';
import type {RecentBodySelection,RecentBodySource,RecentBodyExperiencePreview,RecentBodyExperienceSnapshot,RecentBodyExperienceWorkspace,RecentBodySeriesPreview} from '../../../../common/characterExperiences/recentBodies';
import {recentBodySelectionSchema,recentBodySeriesSelectionSchema} from '../../../../common/characterExperiences/recentBodies';
import {actorSource} from '../sources';
import {formHash} from '../../formAssist';
import {assertFound,NewDesignError} from '../../../domain/errors';
import {getNewDesignPool} from '../../runtime';
import {listAuthorStoryOccurrencesInTransaction,readAuthorFormalStoryTimelineInTransaction} from '../../storyTimeline';
async function book(db:PoolClient,id:string){return assertFound((await db.query("SELECT id,space_id,name FROM new_design.books WHERE id=$1 AND status='active'",[id])).rows[0],'本书不存在或已归档。');}
async function recent(db:PoolClient,bookId:string){return(await db.query("SELECT document.*,body.id body_version_id,body.content,body.content_hash,body.planning_version_id FROM new_design.chapter_documents document JOIN new_design.chapter_body_versions body ON body.id=document.adopted_version_id AND body.chapter_document_id=document.id AND body.archived_at IS NULL WHERE document.book_id=$1 AND document.status='active' ORDER BY document.logical_order DESC,document.id DESC LIMIT 5",[bookId])).rows;}
async function events(db:PoolClient,spaceId:string){return(await db.query("SELECT card.id,card.current_version_id,card.title FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='event' AND type.status='published' WHERE card.space_id=$1 AND card.status='active' AND card.current_version_id IS NOT NULL ORDER BY card.id LIMIT 301",[spaceId])).rows.map(row=>({id:String(row.id),versionId:String(row.current_version_id),title:String(row.title)}));}
async function body(db:PoolClient,row:Record<string,any>):Promise<RecentBodySource>{const content=String(row.content);if(createHash('sha256').update(content,'utf8').digest('hex')!==String(row.content_hash))throw new NewDesignError('原采用正文全文与来源哈希不匹配，保留来源，未准备候选。',409);const planningVersion=row.planning_version_id?assertFound((await db.query('SELECT * FROM new_design.planning_versions WHERE id=$1 AND book_id=$2',[row.planning_version_id,row.book_id])).rows[0],'原正文的冻结计划不存在。'):null;return{documentId:String(row.id),chapterCardId:String(row.chapter_card_id),revision:Number(row.revision),title:String(row.title),logicalOrder:Number(row.logical_order),bodyVersionId:String(row.body_version_id),contentHash:String(row.content_hash),content,planningVersion:planningVersion?JSON.parse(JSON.stringify(planningVersion)):null,sourceRoute:`/new-design/books/${row.book_id}/writing?chapterDocument=${row.id}`};}
async function freezeRecentBodyScope(db:PoolClient,bookId:string,parsed:RecentBodySelection):Promise<RecentBodyExperiencePreview>{const sourceBook=await book(db,bookId),recentRows=await recent(db,bookId),eventChoices=await events(db,sourceBook.space_id);if(eventChoices.length>300)throw new NewDesignError('事件清单超出完整最近正文同步范围，未调用模型。',422);const actors=[];for(const id of parsed.characterIds)actors.push(await actorSource(db,bookId,id));const bodies=[];for(const id of parsed.chapterDocumentIds)bodies.push(await body(db,assertFound(recentRows.find(row=>String(row.id)===id),'选择的正文不在本书最近五章采用范围，请重新核对。')));if(bodies.reduce((sum,item)=>sum+item.content.length,0)>120000)throw new NewDesignError('所选采用正文超过单次完整读取范围，请减少章节；未截断或发送模型请求。',422);const snapshot:RecentBodyExperienceSnapshot={contract:'character_recent_body_experiences_v1',bookId,bookName:String(sourceBook.name),actors,bodies,events:eventChoices,timeline:{...await readAuthorFormalStoryTimelineInTransaction(db,bookId),occurrences:await listAuthorStoryOccurrencesInTransaction(db,bookId)}};if(Object.values(snapshot.timeline).some(value=>!Array.isArray(value)||value.length>2000))throw new NewDesignError('原时间或叙述记录超过单次完整核对范围，未截断或调用模型。',422);const sourceHash=formHash(snapshot);return{snapshot,sourceHash};}
/** Random candidate slots are not part of the source identity. */
export function freezeRecentBodyExperienceSources(db:PoolClient,bookId:string,input:RecentBodySelection){return freezeRecentBodyScope(db,bookId,recentBodySelectionSchema.parse(input));}
export async function previewRecentBodyExperienceSeries(bookId:string,input:RecentBodySelection):Promise<RecentBodySeriesPreview>{const selection=recentBodySeriesSelectionSchema.parse(input),db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const full=await freezeRecentBodyScope(db,bookId,selection),parts=[];for(let offset=0;offset<full.snapshot.actors.length;offset+=20){const actors=full.snapshot.actors.slice(offset,offset+20);parts.push({characterIds:actors.map(actor=>actor.id),expectedSourceHash:formHash({...full.snapshot,actors})});}await db.query('COMMIT');return{bookId,selection,...full,parts};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export function assignRecentBodySlots(snapshot:RecentBodyExperienceSnapshot){return{...snapshot,actors:snapshot.actors.map(actor=>({...actor,slotIds:[randomUUID(),randomUUID(),randomUUID()]}))};}
export async function previewRecentBodyExperiences(bookId:string,input:RecentBodySelection){const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const result=await freezeRecentBodyExperienceSources(db,bookId,input);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function getRecentBodyExperienceWorkspace(bookId:string,characterId:string):Promise<RecentBodyExperienceWorkspace>{const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const sourceBook=await book(db,bookId);await actorSource(db,bookId,characterId);const rows=(await db.query("SELECT card.id,card.title FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key='character' AND type.status='published' WHERE card.space_id=$1 AND card.status='active' AND card.current_version_id IS NOT NULL ORDER BY card.id LIMIT 301",[sourceBook.space_id])).rows,eventChoices=await events(db,sourceBook.space_id),eventType=(await db.query("SELECT id FROM new_design.card_types WHERE space_id=$1 AND type_key='event' AND status='published' AND current_version_id IS NOT NULL",[sourceBook.space_id])).rows[0],chapters=[];for(const row of await recent(db,bookId)){const {content,planningVersion,...choice}=await body(db,row);chapters.push(choice);}await db.query('COMMIT');return{bookId,characterId,characters:rows.slice(0,300).map(row=>({id:String(row.id),title:String(row.title)})),chapters,events:eventChoices.slice(0,300),eventTypeId:eventType?String(eventType.id):null,truncated:rows.length>300||eventChoices.length>300};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
