import {createHash} from "node:crypto";
import {constants} from "node:fs";
import {mkdir,lstat,open,realpath} from "node:fs/promises";
import path from "node:path";
import {TextDecoder} from "node:util";
import {KNOWLEDGE_MAX_BYTES,type PreparedKnowledgeFile} from "../../../common/knowledgeReference";
import {NewDesignError} from "../../domain/errors";
const root=path.resolve(__dirname,"../../../../data/assets");
function sha(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
export function decodeKnowledgeBytes(bytes:Uint8Array):string {if(!bytes.length||bytes.length>KNOWLEDGE_MAX_BYTES)throw new NewDesignError("文件必须非空且不超过 2 MiB。",422,{filename:"请选择大小合适的文本文件。"});let text:string;try{text=new TextDecoder("utf-8",{fatal:true}).decode(bytes);}catch{throw new NewDesignError("文件不是有效 UTF-8，请在编辑器另存为 UTF-8 后上传。",422,{filename:"请转换文件编码。"});}if(/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(text)||!text.trim())throw new NewDesignError("文件包含二进制控制字符或没有正文。",422,{filename:"只支持有效文本或 Markdown 正文。"});return text;}
async function controlledDirectory(){const base=path.resolve(root,"../..");let current=base;const components=path.relative(base,root).split(path.sep);const baseInfo=await lstat(base);if(!baseInfo.isDirectory()||baseInfo.isSymbolicLink())throw new NewDesignError("知识文件根目录不是受控目录。",503);for(const part of components){current=path.join(current,part);try{await mkdir(current);}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;}const info=await lstat(current);if(!info.isDirectory()||info.isSymbolicLink())throw new NewDesignError("知识文件目录不能使用符号链接。",503);}const resolved=await realpath(root);if(resolved.toLowerCase()!==root.toLowerCase())throw new NewDesignError("知识文件目录解析到了非受控路径。",503);}
export async function persistKnowledgeBytes(bytes:Uint8Array,mimeType:string):Promise<PreparedKnowledgeFile>{const text=decodeKnowledgeBytes(bytes),checksum=sha(bytes),locator=`knowledge-${checksum}.utf8`;await controlledDirectory();const target=path.join(root,locator);let handle;try{handle=await open(target,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW,0o600);await handle.writeFile(bytes);await handle.sync();}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;const info=await lstat(target);if(!info.isFile()||info.isSymbolicLink()||info.size!==bytes.length)throw new NewDesignError("同哈希文件不是受控普通文件，不能覆盖。",503);const old=await open(target,constants.O_RDONLY|constants.O_NOFOLLOW);try{const observed=await old.readFile();if(sha(observed)!==checksum)throw new NewDesignError("已保存文件校验失败，原文件未覆盖。",503);}finally{await old.close();}}finally{await handle?.close();}return{checksum,byteSize:bytes.length,locator,text,mimeType};}
export async function readKnowledgeBytes(locator:string,checksum:string,size:number):Promise<Buffer>{if(!/^knowledge-[a-f0-9]{64}\.utf8$/.test(locator))throw new NewDesignError("知识文件引用不是本模块受控相对路径。",422);await controlledDirectory();const target=path.join(root,locator),info=await lstat(target);if(!info.isFile()||info.isSymbolicLink()||info.size!==size||size>KNOWLEDGE_MAX_BYTES)throw new NewDesignError("知识原文件缺失、大小异常或不是普通文件，请保留原资料并重新上传。",503);const handle=await open(target,constants.O_RDONLY|constants.O_NOFOLLOW);try{const bytes=await handle.readFile();if(sha(bytes)!==checksum)throw new NewDesignError("原文件校验和不一致，禁止从已损坏文件解析。",503);decodeKnowledgeBytes(bytes);return bytes;}finally{await handle.close();}}
