import {createHash,randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {comicEpisodeAdoptionSchema,comicEpisodeProposalSchema,type ComicEpisode,type ComicEpisodeAdoptionInput,type ComicEpisodeAdoptionReceipt,type ComicEpisodeProposalInput,type ComicEpisodeProposalReceipt,type ComicEpisodeVersion,type ComicEpisodeWorkspace,type ComicEpisodeOutlinePrompt} from '../../../common/comicEpisodes';
import type {ComicGenerationReceipt} from '../../../common/comicPanels';
import {NewDesignError} from '../../domain/errors';
import {getNewDesignPool} from '../runtime';

const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value),'utf8').digest('hex');
type Db=Pick<PoolClient,'query'>|Pick<Pool,'query'>;
function version(row:Record<string,unknown>):ComicEpisodeVersion{return {id:String(row.id),episodeId:String(row.episode_id),version:Number(row.version),sourceKind:row.source_kind as ComicEpisodeVersion['sourceKind'],sourceVersionId:String(row.source_version_id),content:row.content as ComicEpisodeVersion['content'],createdAt:new Date(String(row.created_at)).toISOString()};}
function episode(row:Record<string,unknown>,versions:ComicEpisodeVersion[]):ComicEpisode{return {id:String(row.id),projectId:String(row.project_id),order:Number(row.episode_order),revision:Number(row.revision),adoptedVersionId:row.adopted_version_id?String(row.adopted_version_id):null,versions};}
async function capability(write=false){const pool=await getNewDesignPool();const row=(await pool.query("SELECT to_regclass('new_design.comic_episodes') IS NOT NULL episodes,to_regclass('new_design.comic_episode_versions') IS NOT NULL versions,to_regclass('new_design.comic_episode_adoptions') IS NOT NULL adoptions,(SELECT count(*) FROM pg_trigger WHERE tgname IN ('comic_episode_versions_immutable','comic_episode_adoptions_immutable') AND tgenabled='O') guards")).rows[0];if(!row.episodes||!row.versions||!row.adoptions||write&&Number(row.guards)!==2)throw new NewDesignError(!row.episodes?'漫画分集手动迁移 110 尚未启用。':'漫画分集保护未就绪，写入已停用。',503);}
async function readEpisode(db:Db,projectId:string,id:string):Promise<ComicEpisode>{const row=(await db.query('SELECT * FROM new_design.comic_episodes WHERE project_id=$1 AND id=$2',[projectId,id])).rows[0];if(!row)throw new NewDesignError('指定漫画分集不存在。',404);const versions=(await db.query('SELECT * FROM new_design.comic_episode_versions WHERE episode_id=$1 ORDER BY version DESC,id DESC',[id])).rows.map(version);return episode(row,versions);}
async function sourceVersion(db:Db,projectId:string){const row=(await db.query('SELECT adopted_source_version_id FROM new_design.comic_projects WHERE id=$1',[projectId])).rows[0];if(!row)throw new NewDesignError('漫画项目不存在。',404);if(!row.adopted_source_version_id)throw new NewDesignError('漫画项目缺少已采用来源。',409);return String(row.adopted_source_version_id);}
export async function getComicEpisodeWorkspace(projectId:string):Promise<ComicEpisodeWorkspace>{await capability();const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');const sourceVersionId=await sourceVersion(db,projectId),rows=(await db.query('SELECT * FROM new_design.comic_episodes WHERE project_id=$1 ORDER BY episode_order,id',[projectId])).rows,ids=rows.map(row=>row.id),versions=ids.length?(await db.query('SELECT * FROM new_design.comic_episode_versions WHERE episode_id=ANY($1::uuid[]) ORDER BY episode_id,version DESC,id DESC',[ids])).rows.map(version):[];await db.query('COMMIT');return {projectId,sourceVersionId,episodes:rows.map(row=>episode(row,versions.filter(item=>item.episodeId===row.id)))};}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function readComicEpisodeOriginal(projectId:string,requestKey:string):Promise<ComicEpisodeProposalReceipt|null>{await capability();const db=await getNewDesignPool(),row=(await db.query('SELECT episode_id,id FROM new_design.comic_episode_versions WHERE project_id=$1 AND request_key=$2',[projectId,requestKey])).rows[0];if(!row)return null;const current=await readEpisode(db,projectId,String(row.episode_id));return {episode:current,version:current.versions.find(item=>item.id===row.id)!,requestKey,repeated:true};}
export async function readComicEpisodeAdoptionOriginal(projectId:string,requestKey:string):Promise<ComicEpisodeAdoptionReceipt|null>{await capability();const db=await getNewDesignPool(),row=(await db.query('SELECT episode_id,version_id,revision FROM new_design.comic_episode_adoptions WHERE project_id=$1 AND request_key=$2',[projectId,requestKey])).rows[0];return row?{episode:await readEpisode(db,projectId,String(row.episode_id)),adoptedVersionId:String(row.version_id),adoptionRevision:Number(row.revision),requestKey,repeated:true}:null;}
export async function getComicEpisodeOutlinePrompt(projectId:string,order:number,instruction:string):Promise<ComicEpisodeOutlinePrompt>{await capability();const row=(await(await getNewDesignPool()).query('SELECT project.adopted_source_version_id,state.adopted_version_id bundle_version_id,bundle.content FROM new_design.comic_projects project JOIN new_design.comic_source_bundle_state state ON state.project_id=project.id JOIN new_design.comic_source_bundle_versions bundle ON bundle.project_id=project.id AND bundle.id=state.adopted_version_id WHERE project.id=$1',[projectId])).rows[0];if(!row)throw new NewDesignError('请先采用来源整理版本，再生成分话大纲。',409);return{operation:'episode_outline',projectId,sourceVersionId:String(row.adopted_source_version_id),sourceBundleVersionId:String(row.bundle_version_id),sourceBundle:row.content,order,instruction};}
export async function readComicEpisodeGenerationOriginal(projectId:string,requestKey:string):Promise<ComicGenerationReceipt|null>{const result=await readComicEpisodeOriginal(projectId,requestKey);if(!result||result.version.sourceKind!=='ai_candidate')return null;const currentSource=await sourceVersion(await getNewDesignPool(),projectId);return{requestKey,operation:'episode_outline',sourceVersionIds:[result.version.sourceVersionId],candidateVersionId:result.version.id,status:'succeeded',repeated:true,readiness:result.version.sourceVersionId===currentSource?'current':'stale_source',adopted:result.episode.adoptedVersionId===result.version.id};}

export async function proposeComicEpisode(projectId:string,raw:ComicEpisodeProposalInput,options:{sourceKind?:'manual'|'ai_candidate';expectedSourceVersionId?:string;expectedSourceBundleVersionId?:string}={}):Promise<ComicEpisodeProposalReceipt>{const input=comicEpisodeProposalSchema.parse(raw),sourceKind=options.sourceKind??'manual',fingerprint=digest(sourceKind==='manual'?{projectId,...input}:{projectId,...input,sourceKind,expectedSourceVersionId:options.expectedSourceVersionId??null,expectedSourceBundleVersionId:options.expectedSourceBundleVersionId??null});await capability(true);const pool=await getNewDesignPool(),db=await pool.connect();let committing=false;try{
 await db.query('BEGIN');const previous=(await db.query('SELECT episode_id,id,input_hash FROM new_design.comic_episode_versions WHERE request_key=$1',[input.requestKey])).rows[0];if(previous){if(previous.input_hash!==fingerprint)throw new NewDesignError('原分集候选请求已用于不同内容。',409);const current=await readEpisode(db,projectId,String(previous.episode_id));await db.query('COMMIT');return {episode:current,version:current.versions.find(item=>item.id===previous.id)!,requestKey:input.requestKey,repeated:true};}
 const sourceVersionId=await sourceVersion(db,projectId);if(options.expectedSourceVersionId&&sourceVersionId!==options.expectedSourceVersionId)throw new NewDesignError('漫画原文来源已变化，大纲候选未保存。',409);if(options.expectedSourceBundleVersionId){const bundle=(await db.query('SELECT adopted_version_id FROM new_design.comic_source_bundle_state WHERE project_id=$1',[projectId])).rows[0];if(bundle?.adopted_version_id!==options.expectedSourceBundleVersionId)throw new NewDesignError('来源整理版本已变化，大纲候选未保存。',409);}await db.query('SELECT id FROM new_design.comic_projects WHERE id=$1 FOR UPDATE',[projectId]);
 let row=(await db.query('SELECT * FROM new_design.comic_episodes WHERE project_id=$1 AND episode_order=$2 FOR UPDATE',[projectId,input.order])).rows[0];
 if(!row){if(input.expectedRevision!==0)throw new NewDesignError('新分集尚不存在，请按当前序号重新核对。',409);const id=randomUUID();row=(await db.query('INSERT INTO new_design.comic_episodes(id,project_id,episode_order) VALUES($1,$2,$3) RETURNING *',[id,projectId,input.order])).rows[0];}
 if(Number(row.revision)!==input.expectedRevision)throw new NewDesignError('分集已采用其他版本，请读取最新版本后再修改。',409);
 const next=Number((await db.query('SELECT coalesce(max(version),0)+1 value FROM new_design.comic_episode_versions WHERE episode_id=$1',[row.id])).rows[0].value),versionId=randomUUID();
 await db.query('INSERT INTO new_design.comic_episode_versions(id,project_id,episode_id,version,source_kind,source_version_id,content,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[versionId,projectId,row.id,next,sourceKind,sourceVersionId,input.content,input.requestKey,fingerprint]);
 const current=await readEpisode(db,projectId,String(row.id));committing=true;await db.query('COMMIT');return {episode:current,version:current.versions.find(item=>item.id===versionId)!,requestKey:input.requestKey,repeated:false};
 }catch(error){await db.query('ROLLBACK').catch(()=>undefined);if(committing)throw new NewDesignError('分集候选结果未知，请只读核对原请求。',503);if((error as {code?:string}).code==='23505'){const receipt=await readComicEpisodeOriginal(projectId,input.requestKey);if(receipt){const row=(await pool.query('SELECT input_hash FROM new_design.comic_episode_versions WHERE id=$1',[receipt.version.id])).rows[0];if(row?.input_hash===fingerprint)return receipt;}throw new NewDesignError('分集序号或原请求键已被占用，请读取当前分集。',409);}throw error;}finally{db.release();}}

export async function adoptComicEpisode(projectId:string,episodeId:string,raw:ComicEpisodeAdoptionInput):Promise<ComicEpisodeAdoptionReceipt>{const input=comicEpisodeAdoptionSchema.parse(raw),fingerprint=digest({projectId,episodeId,...input});await capability(true);const pool=await getNewDesignPool(),db=await pool.connect();let committing=false;try{
 await db.query('BEGIN');const previous=(await db.query('SELECT episode_id,version_id,revision,input_hash FROM new_design.comic_episode_adoptions WHERE request_key=$1',[input.requestKey])).rows[0];if(previous){if(previous.input_hash!==fingerprint||previous.episode_id!==episodeId)throw new NewDesignError('原采用请求已用于其他分集。',409);const current=await readEpisode(db,projectId,episodeId);await db.query('COMMIT');return {episode:current,adoptedVersionId:String(previous.version_id),adoptionRevision:Number(previous.revision),requestKey:input.requestKey,repeated:true};}
 const sourceVersionId=await sourceVersion(db,projectId),row=(await db.query('SELECT * FROM new_design.comic_episodes WHERE id=$1 AND project_id=$2 FOR UPDATE',[episodeId,projectId])).rows[0];if(!row)throw new NewDesignError('指定漫画分集不存在。',404);
 if(Number(row.revision)!==input.expectedRevision)throw new NewDesignError('分集采用状态已变化，请先核对当前正式版本。',409);
 const target=(await db.query('SELECT id,source_version_id FROM new_design.comic_episode_versions WHERE id=$1 AND episode_id=$2',[input.versionId,episodeId])).rows[0];if(!target)throw new NewDesignError('候选版本不存在或属于其他分集。',404);if(target.source_version_id!==sourceVersionId)throw new NewDesignError('候选基于旧来源，请重新核对后再采用。',409);
 await db.query('UPDATE new_design.comic_episodes SET adopted_version_id=$2,revision=revision+1,updated_at=now() WHERE id=$1',[episodeId,input.versionId]);
 await db.query('INSERT INTO new_design.comic_episode_adoptions(id,project_id,episode_id,version_id,revision,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),projectId,episodeId,input.versionId,input.expectedRevision+1,input.requestKey,fingerprint]);
 const current=await readEpisode(db,projectId,episodeId);committing=true;await db.query('COMMIT');return {episode:current,adoptedVersionId:input.versionId,adoptionRevision:input.expectedRevision+1,requestKey:input.requestKey,repeated:false};
 }catch(error){await db.query('ROLLBACK').catch(()=>undefined);if(committing)throw new NewDesignError('分集采用结果未知，请只读核对原请求。',503);if((error as {code?:string}).code==='23505'){const receipt=await readComicEpisodeAdoptionOriginal(projectId,input.requestKey);if(receipt){const row=(await pool.query('SELECT input_hash FROM new_design.comic_episode_adoptions WHERE request_key=$1',[input.requestKey])).rows[0];if(row?.input_hash===fingerprint)return receipt;}}throw error;}finally{db.release();}}
