import type { ContextScopeKind, ContextSelectorKind, ContextSourceType } from "./contracts";
export interface ContextAuthorChoice {id:string;label:string;kind?:string;parentId?:string|null;}
export interface ContextAuthorSource {kind:ContextSourceType;stableId:string;versionId:string;revision:number;label:string;current:boolean;checkpoint?:Record<string,unknown>;}
export interface ContextAuthorCatalog {bookId:string;types:ContextAuthorChoice[];scopes:ContextAuthorChoice[];sources:ContextAuthorSource[];tags:ContextAuthorChoice[];views:ContextAuthorChoice[];relations:ContextAuthorChoice[];packs:ContextAuthorChoice[];retrievals:ContextAuthorChoice[];spaces:ContextAuthorChoice[];tasks:ContextAuthorChoice[];groups:ContextAuthorChoice[];slots:ContextAuthorChoice[];routeOverrides:ContextAuthorChoice[];truncated:boolean;}
export const contextSourceLabels:Record<ContextSourceType,string>={card_version:"本书资料",card_relation:"资料关系",body_version:"章节正文",text_anchor:"正文证据位置",planning_version:"故事规划",canonical_fact:"已确认事实",knowledge_state_change:"认知变化",state_change:"状态变化",story_time:"故事时间",story_event_relation:"事件关系",research_document_version:"参考文本",research_version:"研究记录",research_pack_version:"研究参考包",prompt_component:"指令组件",retrieval_chunk:"检索片段"};
export const contextSelectorLabels:Record<ContextSelectorKind,string>={explicit_source:"明确资料版本",card_type:"内容类型",tag:"标签",smart_view:"智能视图",relation:"资料关系",story_range:"故事范围",research_pack:"研究资料包",prompt_component:"提示词组件",retrieval_trace:"既有检索轨迹"};
export function contextSelectorChoices(c:ContextAuthorCatalog,kind:ContextSelectorKind):ContextAuthorChoice[]{return kind==="card_type"?c.types:kind==="tag"?c.tags:kind==="smart_view"?c.views:kind==="relation"?c.relations:kind==="research_pack"?c.packs:kind==="retrieval_trace"?c.retrievals:[];}
export function contextScopeChoices(c:ContextAuthorCatalog,kind:ContextScopeKind):ContextAuthorChoice[]{if(kind==="task_group")return c.groups;if(kind==="task_node"||kind==="one_time")return c.tasks;return c.scopes.filter(choice=>choice.kind===kind);}
export function contextChoiceLabel(choices:ContextAuthorChoice[],id:string,fallback="已保存的选项（需复核）"):string{return choices.find(choice=>choice.id===id)?.label??fallback;}
