import {createHash,randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {comicPanelAdoptionSchema,comicPanelProposalSchema,type ComicPanel,type ComicPanelAdoptionInput,type ComicPanelAdoptionReceipt,type ComicPanelProposalInput,type ComicPanelProposalReceipt,type ComicPanelSet,type ComicPanelWorkspace} from '../../../common/comicPanels';
import {NewDesignError} from '../../domain/errors';
import {getNewDesignPool} from '../runtime';

type Db=Pick<PoolClient,'query'>|Pick<Pool,'query'>;
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value),'utf8').digest('hex');
async function capable(write=false){const row=(await(await getNewDesignPool()).query("SELECT to_regclass('new_design.comic_panel_sets') IS NOT NULL sets,to_regclass('new_design.comic_panels') IS NOT NULL panels,to_regclass('new_design.comic_panel_set_adoptions') IS NOT NULL adoptions,(SELECT count(*) FROM pg_trigger WHERE tgname IN ('comic_panel_sets_immutable','comic_panels_immutable','comic_panel_set_adoptions_immutable') AND tgenabled='O') guards")).rows[0];if(!row.sets||!row.panels||!row.adoptions||write&&Number(row.guards)!==3)throw new NewDesignError(!row.sets?'漫画分格手动迁移 111 尚未启用。':'漫画分格保护未就绪，写入已停用。',503);}
function panel(row:Record<string,unknown>):ComicPanel{return {id:String(row.id),order:Number(row.panel_order),panelType:String(row.panel_type),action:String(row.action),dialogues:row.dialogues as ComicPanel['dialogues'],characterRefs:row.character_refs as string[],sceneRef:row.scene_ref?String(row.scene_ref):null,visualPrompt:String(row.visual_prompt),densityLevel:row.density_level as ComicPanel['densityLevel'],focus:row.focus?String(row.focus):null,layoutData:row.layout_data as ComicPanel['layoutData']};}
async function readSet(db:Db,id:string):Promise<ComicPanelSet>{const row=(await db.query('SELECT * FROM new_design.comic_panel_sets WHERE id=$1',[id])).rows[0];if(!row)throw new NewDesignError('分格脚本版本不存在。',404);const panels=(await db.query('SELECT * FROM new_design.comic_panels WHERE panel_set_id=$1 ORDER BY panel_order',[id])).rows.map(panel);return {id:String(row.id),episodeId:String(row.episode_id),version:Number(row.version),episodeVersionId:String(row.episode_version_id),densityMode:row.density_mode as ComicPanelSet['densityMode'],sourceKind:row.source_kind as ComicPanelSet['sourceKind'],panels,createdAt:new Date(String(row.created_at)).toISOString()};}
async function episode(db:Db,projectId:string,episodeId:string,lock=false){const row=(await db.query(`SELECT episode.*,version.content->>'title' episode_title FROM new_design.comic_episodes episode LEFT JOIN new_design.comic_episode_versions version ON version.id=episode.adopted_version_id WHERE episode.project_id=$1 AND episode.id=$2${lock?' FOR UPDATE OF episode':''}`,[projectId,episodeId])).rows[0];if(!row)throw new NewDesignError('漫画分集不存在或不属于该项目。',404);if(!row.adopted_version_id)throw new NewDesignError('请先采用分集大纲，再制作分格脚本。',409);return row;}
export async function getComicPanelWorkspace(projectId:string,episodeId:string):Promise<ComicPanelWorkspace>{await capable();const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');const row=await episode(db,projectId,episodeId),sets=(await db.query('SELECT id FROM new_design.comic_panel_sets WHERE episode_id=$1 ORDER BY version DESC,id DESC',[episodeId])).rows,items=[];for(const item of sets)items.push(await readSet(db,String(item.id)));await db.query('COMMIT');const adopted=items.find(item=>item.id===row.adopted_panel_set_id);return {projectId,episodeId,episodeOrder:Number(row.episode_order),episodeTitle:String(row.episode_title),episodeVersionId:String(row.adopted_version_id),adoptedSetId:row.adopted_panel_set_id?String(row.adopted_panel_set_id):null,adoptedReady:Boolean(adopted&&adopted.episodeVersionId===row.adopted_version_id),scriptRevision:Number(row.script_revision),sets:items};}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function readComicPanelProposalOriginal(projectId:string,requestKey:string):Promise<ComicPanelProposalReceipt|null>{await capable();const db=await getNewDesignPool(),row=(await db.query('SELECT id FROM new_design.comic_panel_sets WHERE project_id=$1 AND request_key=$2',[projectId,requestKey])).rows[0];return row?{set:await readSet(db,String(row.id)),requestKey,repeated:true}:null;}
export async function readComicPanelAdoptionOriginal(projectId:string,requestKey:string):Promise<ComicPanelAdoptionReceipt|null>{await capable();const db=await getNewDesignPool(),row=(await db.query('SELECT episode_id,set_id,revision FROM new_design.comic_panel_set_adoptions WHERE project_id=$1 AND request_key=$2',[projectId,requestKey])).rows[0];return row?{workspace:await getComicPanelWorkspace(projectId,String(row.episode_id)),adoptedSetId:String(row.set_id),adoptionRevision:Number(row.revision),requestKey,repeated:true}:null;}
export async function proposeComicPanelSet(projectId:string,episodeId:string,raw:ComicPanelProposalInput):Promise<ComicPanelProposalReceipt>{const input=comicPanelProposalSchema.parse(raw),hash=fingerprint({projectId,episodeId,...input});await capable(true);const pool=await getNewDesignPool(),db=await pool.connect();let committing=false;try{
 await db.query('BEGIN');const existing=(await db.query('SELECT id,input_hash FROM new_design.comic_panel_sets WHERE request_key=$1',[input.requestKey])).rows[0];if(existing){if(existing.input_hash!==hash)throw new NewDesignError('原分格候选请求已用于不同内容。',409);const set=await readSet(db,String(existing.id));await db.query('COMMIT');return {set,requestKey:input.requestKey,repeated:true};}
 const row=await episode(db,projectId,episodeId,true);if(row.adopted_version_id!==input.episodeVersionId||Number(row.script_revision)!==input.expectedScriptRevision)throw new NewDesignError('分集大纲或已采用脚本发生变化，请先读取最新版本。',409);
 const next=Number((await db.query('SELECT coalesce(max(version),0)+1 value FROM new_design.comic_panel_sets WHERE episode_id=$1',[episodeId])).rows[0].value),setId=randomUUID();await db.query('INSERT INTO new_design.comic_panel_sets(id,project_id,episode_id,version,episode_version_id,density_mode,source_kind,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[setId,projectId,episodeId,next,input.episodeVersionId,input.densityMode,'manual',input.requestKey,hash]);
 for(const item of input.panels)await db.query('INSERT INTO new_design.comic_panels(id,panel_set_id,panel_order,panel_type,action,dialogues,character_refs,scene_ref,visual_prompt,density_level,focus,layout_data) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,$10,$11,$12::jsonb)',[randomUUID(),setId,item.order,item.panelType,item.action,JSON.stringify(item.dialogues),JSON.stringify(item.characterRefs),item.sceneRef,item.visualPrompt,item.densityLevel,item.focus,item.layoutData?JSON.stringify(item.layoutData):null]);
 const set=await readSet(db,setId);committing=true;await db.query('COMMIT');return {set,requestKey:input.requestKey,repeated:false};
 }catch(error){await db.query('ROLLBACK').catch(()=>undefined);if(committing)throw new NewDesignError('分格候选结果未知，请按原请求只读核对。',503);if((error as {code?:string}).code==='23505'){const receipt=await readComicPanelProposalOriginal(projectId,input.requestKey);if(receipt){const row=(await pool.query('SELECT input_hash FROM new_design.comic_panel_sets WHERE id=$1',[receipt.set.id])).rows[0];if(row?.input_hash===hash)return receipt;}throw new NewDesignError('原分格请求键已被使用。',409);}throw error;}finally{db.release();}}
export async function adoptComicPanelSet(projectId:string,episodeId:string,raw:ComicPanelAdoptionInput):Promise<ComicPanelAdoptionReceipt>{const input=comicPanelAdoptionSchema.parse(raw),hash=fingerprint({projectId,episodeId,...input});await capable(true);const pool=await getNewDesignPool(),db=await pool.connect();let committing=false;try{
 await db.query('BEGIN');const existing=(await db.query('SELECT episode_id,set_id,revision,input_hash FROM new_design.comic_panel_set_adoptions WHERE request_key=$1',[input.requestKey])).rows[0];if(existing){if(existing.input_hash!==hash||existing.episode_id!==episodeId)throw new NewDesignError('原分格采用请求已用于其他内容。',409);await db.query('COMMIT');return {workspace:await getComicPanelWorkspace(projectId,episodeId),adoptedSetId:String(existing.set_id),adoptionRevision:Number(existing.revision),requestKey:input.requestKey,repeated:true};}
 const row=await episode(db,projectId,episodeId,true);if(Number(row.script_revision)!==input.expectedScriptRevision)throw new NewDesignError('分格采用状态已变化，请先核对当前脚本。',409);const set=(await db.query('SELECT id,episode_version_id FROM new_design.comic_panel_sets WHERE id=$1 AND project_id=$2 AND episode_id=$3',[input.setId,projectId,episodeId])).rows[0];if(!set)throw new NewDesignError('分格候选不存在或属于其他分集。',404);if(set.episode_version_id!==row.adopted_version_id)throw new NewDesignError('分格候选依据旧分集大纲，请重新制作候选。',409);
 await db.query('UPDATE new_design.comic_episodes SET adopted_panel_set_id=$2,script_revision=script_revision+1,updated_at=now() WHERE id=$1',[episodeId,input.setId]);await db.query('INSERT INTO new_design.comic_panel_set_adoptions(id,project_id,episode_id,set_id,revision,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),projectId,episodeId,input.setId,input.expectedScriptRevision+1,input.requestKey,hash]);committing=true;await db.query('COMMIT');return {workspace:await getComicPanelWorkspace(projectId,episodeId),adoptedSetId:input.setId,adoptionRevision:input.expectedScriptRevision+1,requestKey:input.requestKey,repeated:false};
 }catch(error){await db.query('ROLLBACK').catch(()=>undefined);if(committing)throw new NewDesignError('分格采用结果未知，请按原请求只读核对。',503);if((error as {code?:string}).code==='23505'){const receipt=await readComicPanelAdoptionOriginal(projectId,input.requestKey);if(receipt){const row=(await pool.query('SELECT input_hash FROM new_design.comic_panel_set_adoptions WHERE request_key=$1',[input.requestKey])).rows[0];if(row?.input_hash===hash)return receipt;}}throw error;}finally{db.release();}}
