packages:
  - client
  - desktop
  - new-design
  - server
  - site
  - shared
injectWorkspacePackages: true
allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@prisma/engines': true
  better-sqlite3: true
  electron: false
  electron-winstaller: false
  esbuild: true
  prisma: true
