const {test}=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
require('../node_modules/tsx/dist/cjs/index.cjs');
const {selectShelf,shelfProgress,shelfAction}=require('../src/common/bookshelf/presentation.ts');
const {changeBookLifecycle,getBookReading,getBookshelfSnapshot,SHELF_COVERS_QUERY,READING_CHAPTERS_QUERY}=require('../src/server/database/bookshelf/index.ts');
const {bookshelfMutationFence,bookshelfWritableGuard}=require('../src/server/http/bookshelf/index.ts');
const bookId='41000000-0000-4000-8000-000000000002',chapterId='42000000-0000-4000-8000-000000000002';
const {getShelfTextExport,SAVED_CHAPTERS_QUERY,ADOPTED_EXPORT_QUERY}=require('../src/server/database/bookshelf/index.ts');
const {shelfTextFile}=require('../src/common/bookshelf/text.ts');
function readingFixture(){const sql=[],saved={id:chapterId,chapter_card_id:bookId,title:'雨夜',logical_order:1,version_id:'43000000-0000-4000-8000-000000000002',version:3,source:'ai',content:'最新待审稿',content_hash:'saved-hash',word_count:5,adopted:false,stable:false},adopted={...saved,version_id:chapterId,version:2,content:'人工已采用稿',content_hash:'adopted-hash',source:'manual',stable:true};const client={release(){},async query(q){sql.push(q);if(q.includes("to_regclass('new_design.chapter_quality_requests')"))return {rows:[{present:false}]};if(q.includes('SELECT id,name FROM'))return {rows:[{id:bookId,name:'山河/作品'}]};if(q===SAVED_CHAPTERS_QUERY)return {rows:[saved]};if(q===READING_CHAPTERS_QUERY||q===ADOPTED_EXPORT_QUERY)return {rows:[adopted]};if(q.startsWith('SELECT v.content,v.content_hash'))return {rows:[adopted]};if(q==='SELECT CURRENT_TIMESTAMP read_at')return {rows:[{read_at:new Date('2026-09-17T00:00:00Z')}]};return {rows:[]};}};return {pool:{connect:async()=>client},sql};}
test('saved reading and TXT keep the latest unadopted version distinct from formal adoption',async()=>{const f=readingFixture(),saved=await getBookReading(bookId,chapterId,f.pool,'saved'),adopted=await getBookReading(bookId,chapterId,f.pool,'adopted');assert.equal(saved.selected.version,3);assert.equal(saved.selected.adopted,false);assert.equal(saved.selected.content,'最新待审稿');assert.equal(adopted.selected.version,2);assert.equal(adopted.selected.adopted,true);assert.equal(adopted.selected.content,'人工已采用稿');const exported=await getShelfTextExport(bookId,'saved',chapterId,f.pool);assert.equal(exported.chapters[0].versionId,saved.selected.versionId);assert.equal(exported.chapters[0].contentHash,saved.selected.contentHash);assert.equal(exported.chapters[0].content,saved.selected.content);assert.ok(f.sql.every(q=>! /^(UPDATE|INSERT|DELETE|ALTER)/.test(q)));assert.ok(f.sql.includes('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY'));});
test('TXT export rejects foreign chapters and empty manuscripts without fallback or writes',async()=>{const f=readingFixture();await assert.rejects(()=>getShelfTextExport(bookId,'saved',bookId,f.pool),error=>error.status===404);const client={release(){},async query(q){return {rows:q.includes('SELECT id,name FROM')?[{id:bookId,name:'空书'}]:[]};}};await assert.rejects(()=>getShelfTextExport(bookId,'saved',undefined,{connect:async()=>client}),error=>error.status===422);assert.ok(f.sql.includes('ROLLBACK'));});
test('download labels draft scope and exact versions without claiming publication or completion',async()=>{const f=readingFixture(),value=await getShelfTextExport(bookId,'saved',chapterId,f.pool),file=shelfTextFile(value);assert.ok(file.text.startsWith('\uFEFF'));assert.match(file.text,/含未采用候选/);assert.match(file.text,/未采用候选 · 保存版本 3/);assert.match(file.text,/saved-hash/);assert.doesNotMatch(file.filename,/[\\/:*?"<>|]/);const adopted=shelfTextFile(await getShelfTextExport(bookId,'adopted',chapterId,f.pool));assert.match(adopted.text,/正式采用正文（未声明完本）/);assert.match(adopted.text,/adopted-hash/);});
function book(i=0){return {id:bookId+i,name:'作品'+i,description:'世界与人物',createdAt:'2026-09-16T00:00:00Z',updatedAt:'2026-09-17T00:00:00Z',characterCount:1,worldCount:1,writtenChapterCount:0,stableChapterCount:0,adoptedChapterPlanCount:3,writableChapterPlanCount:0,runningTasks:0,queuedTasks:0,waitingTasks:0,pendingFacts:0,pendingChanges:0,latestTask:null,latestDirector:null,lastChapterCardId:null,revision:1};}
test('archived books reject new scoped HTTP writes without preventing explicit restoration',async()=>{const checked=[];const guard=bookshelfWritableGuard(async id=>{checked.push(id);return {bookId:id,status:'archived',revision:2};});const run=req=>new Promise(resolve=>guard(req,{},resolve));assert.equal((await run({method:'POST',path:'/books/'+bookId+'/story-ai-batches'})).status,409);assert.equal((await run({method:'POST',path:'/visual-assets',body:{bookId}})).status,409);assert.equal(await run({method:'PATCH',path:'/books/'+bookId+'/lifecycle'}),undefined);assert.equal(checked.length,2);});
test('shelf filtering and 24-book pagination cover all books with stable ordering',()=>{const books=Array.from({length:53},(_,i)=>book(i));assert.equal(selectShelf(books,'','all','updated',1).items.length,24);assert.equal(selectShelf(books,'','all','updated',99).items.length,5);assert.equal(selectShelf(books,'世界','all','created',1).total,53);assert.equal(selectShelf(books,'作品52','all','updated',1).total,1);assert.equal(selectShelf(books,'','readable','updated',1).total,0);});
test('task completion and saved candidates never become adopted chapter progress',()=>{const b=book();b.latestDirector={id:'original',status:'completed',savedCandidateCount:10,leaseExpired:false};assert.equal(shelfProgress(b),0);b.adoptedChapterPlanCount=0;assert.equal(shelfProgress(b),null);b.latestDirector.status='waiting_recovery';assert.match(shelfAction(b).href,/director\?run=original$/);b.latestDirector=null;b.latestTask={status:'failed',sourceRoute:'/new-design/books/foreign/writing'};assert.doesNotMatch(shelfAction(b).href,/foreign/);});
function lifecyclePool({blocker=false,native=false,commitLost=false}={}){let current={id:bookId,status:'active',revision:1},changes=0;const sql=[];const client={release(){},async query(q,p){sql.push(q);if(q.includes('FOR UPDATE'))return {rows:[{...current}]};if(q.startsWith('WITH sources'))return {rows:blocker?[{title:'原导演暂停',route:'/new-design/books/'+bookId+'/director?run=original'}]:[]};if(q.includes('information_schema.columns'))return {rows:[{table_name:'image_generation_requests'}]};if(q.startsWith('SELECT 1 FROM new_design.'))return {rows:[],rowCount:native?1:0};if(q.startsWith('UPDATE new_design.books')){changes++;current={...current,status:p[1],revision:current.revision+1};}if(q==='COMMIT'&&commitLost)throw Error('ack lost');return {rows:[],rowCount:0};}};return {pool:{connect:async()=>client},state:()=>current,changes:()=>changes,sql};}
test('archive replay has one effect, restore keeps the original identity without touching creative data',async()=>{const f=lifecyclePool(),input={action:'archive',expectedRevision:1};const first=await changeBookLifecycle(bookId,input,f.pool),replay=await changeBookLifecycle(bookId,input,f.pool);assert.deepEqual(replay,first);assert.equal(f.changes(),1);const restored=await changeBookLifecycle(bookId,{action:'restore',expectedRevision:2},f.pool);assert.deepEqual(restored,{bookId,status:'active',revision:3});await assert.rejects(()=>changeBookLifecycle(bookId,input,f.pool),/状态已变化/);assert.equal(f.changes(),2);assert.ok(f.sql.filter(q=>/^(UPDATE|INSERT|DELETE|TRUNCATE|ALTER)/.test(q)).every(q=>q.startsWith('UPDATE new_design.books SET status=')));});
test('paused source tasks and native requests outside running records block archive',async()=>{for(const options of [{blocker:true},{native:true}]){const f=lifecyclePool(options);await assert.rejects(()=>changeBookLifecycle(bookId,{action:'archive',expectedRevision:1},f.pool),error=>error.status===409&&/原来源/.test(error.message));assert.equal(f.changes(),0);}});
test('lost commit acknowledgment preserves unknown rather than confirming a second transition',async()=>{const f=lifecyclePool({commitLost:true});await assert.rejects(()=>changeBookLifecycle(bookId,{action:'archive',expectedRevision:1},f.pool),/结果待核对/);assert.equal(f.changes(),1);});
test('HTTP archive fence refuses live mutations and releases exactly once on close or finish',()=>{const fence=bookshelfMutationFence(),response=()=>{const r=new EventEmitter();r.status=function(code){this.code=code;return this};r.json=function(body){this.body=body;return this};return r;};let entered=0;const live=response();fence({method:'POST',path:'/books/'+bookId+'/story-ai-batches'},live,()=>entered++);const blocked=response();fence({method:'PATCH',path:'/books/'+bookId+'/lifecycle'},blocked,()=>entered++);assert.equal(blocked.code,409);live.emit('finish');live.emit('close');const archive=response();fence({method:'PATCH',path:'/books/'+bookId+'/lifecycle'},archive,()=>entered++);const concurrent=response();fence({method:'POST',path:'/books/new'},concurrent,()=>entered++);assert.equal(concurrent.code,409);archive.emit('finish');fence({method:'POST',path:'/books/new'},response(),()=>entered++);assert.equal(entered,3);});
test('reader uses original adopted version and rejects foreign or missing selected chapters',async()=>{const sql=[];const row={id:chapterId,chapter_card_id:bookId,title:'第一章',logical_order:1,version_id:chapterId,version:2,word_count:3,stable:false};const client={release(){},async query(q){sql.push(q);if(q.includes("to_regclass('new_design.chapter_quality_requests')"))return {rows:[{present:false}]};if(q.includes('SELECT id,name FROM'))return {rows:[{id:bookId,name:'测试'}]};if(q===READING_CHAPTERS_QUERY)return {rows:[row]};if(q.startsWith('SELECT v.content,v.content_hash'))return {rows:[{content:'已采用正文',content_hash:'original'}]};if(q==='SELECT CURRENT_TIMESTAMP read_at')return {rows:[{read_at:new Date()}]};return {rows:[]};}},pool={connect:async()=>client};const result=await getBookReading(bookId,chapterId,pool);assert.equal(result.selected.content,'已采用正文');assert.equal(result.selected.version,2);assert.equal(result.selected.stable,false);await assert.rejects(()=>getBookReading(bookId,bookId,pool),/未自动改选/);assert.ok(sql.every(q=>! /^(UPDATE|INSERT|DELETE|ALTER)/.test(q)));assert.match(READING_CHAPTERS_QUERY,/v.id=d.adopted_version_id/);assert.match(READING_CHAPTERS_QUERY,/d.book_id=\$1/);assert.match(SHELF_COVERS_QUERY,/m.owner_stable_id=m.book_id/);assert.match(SHELF_COVERS_QUERY,/v.id=m.asset_version_id/);});
test('shelf snapshot includes all unfinished drafts and keeps recycle bin outside active statistics',async()=>{const sql=[];const client={release(){},async query(q){sql.push(q);if(q==='SELECT CURRENT_TIMESTAMP read_at')return {rows:[{read_at:new Date()}]};if(q.includes("SELECT id,name,description,revision,updated_at FROM"))return {rows:[{id:bookId,name:'归档作品',description:'',revision:2,updated_at:new Date()}]};if(q.startsWith('SELECT id,book_name'))return {rows:[1,2].map(i=>({id:chapterId+i,book_name:'草稿'+i,status:'review',stage:'review',progress:10,updated_at:new Date()}))};return {rows:[]};}};const result=await getBookshelfSnapshot({connect:async()=>client});assert.equal(result.books.length,0);assert.equal(result.recycled.length,1);assert.equal(result.drafts.length,2);assert.ok(sql.some(q=>q.startsWith('SELECT id,book_name')&&!q.includes('LIMIT 1')));assert.ok(sql.every(q=>! /^(UPDATE|INSERT|DELETE|ALTER)/.test(q)));});
test('shelf snapshot shows the latest cover request state from the new-design task ledger',async()=>{
 const doneId='33333333-3333-4333-8333-333333333333',rows=[{id:bookId,name:'封面生成中',description:'',created_at:new Date(),updated_at:new Date()},{id:chapterId,name:'封面待核对',description:'',created_at:new Date(),updated_at:new Date()},{id:doneId,name:'已有封面',description:'',created_at:new Date(),updated_at:new Date()}],sql=[];
 const {HOME_BOOKS_QUERY}=require('../src/server/database/home/index.ts');
 const client={release(){},async query(q){sql.push(q);if(q==='SELECT CURRENT_TIMESTAMP read_at')return{rows:[{read_at:new Date()}]};if(q===HOME_BOOKS_QUERY)return{rows};if(q.includes("source_kind='image_generation'")&&q.includes("->>'kind'='cover'"))return{rows:[{book_id:bookId,status:'running'},{book_id:chapterId,status:'failed'},{book_id:doneId,status:'succeeded'}]};if(q.includes('SELECT id,revision FROM new_design.books'))return{rows:rows.map(row=>({id:row.id,revision:1}))};return{rows:[]};}};
 const result=await getBookshelfSnapshot({connect:async()=>client});
 assert.equal(result.books.find(item=>item.id===bookId).coverGenerationStatus,'running');
 assert.equal(result.books.find(item=>item.id===chapterId).coverGenerationStatus,'attention');
 assert.equal(result.books.find(item=>item.id===doneId).coverGenerationStatus,null);
 assert.ok(sql.some(q=>q.includes('DISTINCT ON (task.book_id)')));
 assert.ok(sql.every(q=>! /^(UPDATE|INSERT|DELETE|ALTER)/.test(q)));
});
