const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{compiled}=require('./support/isolatedDatabase.cjs'),{resourceSupplementFixture}=require('./support/resourceSupplementFixture.cjs'),{resourceSupplementHttp}=require('./support/resourceSupplementHttp.cjs');
const key=()=>randomUUID(),cleanup=[];
(async()=>{const t={after:fn=>cleanup.push(fn),diagnostic:message=>process.stdout.write(message+'\n')},f=await resourceSupplementFixture(t),{pool,book,actor}=f,first=await f.chapter(1,1,false,undefined,'资源人物在翌晨抵达渡口😀。数量为1。'),second=await f.chapter(2,2,false,undefined,'资源人物回忆三年前学习剑术😀。数量为2。');for(let i=1;i<Number(process.env.ND_RECENT_BODY_BROWSER_ACTORS??1);i++)await f.create('character',`正文人物${i}`,{name:`正文人物${i}`,story_role:'supporting'});const types=await f.cards.listCardTypes(book.spaceId),eventType=types.find(type=>type.key==='event'),event=await f.cards.createCard({cardTypeId:eventType.id,spaceId:book.spaceId,title:'抵达渡口',values:Object.fromEntries(eventType.draftFields.filter(field=>field.required).map(field=>[field.key,'抵达渡口']))}),models=compiled('server/database/modelManagement'),route={primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'isolated-recent-body-browser-stub',credentialId:null},fallbacks:[],policy:{maxOutputTokens:20000,maxTotalTokens:1000000,timeoutMs:30000,maxRetries:0,retryDelayMs:0}};for(const [scope,taskType]of [['system_default',null],['task','form_assist']]){const current=(await models.getModelRouteCenterCatalog()).routes.find(item=>item.scope===scope&&item.taskType===taskType);await models.saveManagedModelRoute({...route,scope,taskType,expectedConfigId:current?.id??null,expectedRevision:current?.revision??null,replaceUnsupported:true,idempotencyKey:key()});}
 const tables=['cards','card_versions','chapter_documents','chapter_body_versions','chapter_stable_checkpoints','chapter_settlements','state_changes','current_state_projections','current_knowledge_state_projections'],frame=async()=>Object.fromEntries(await Promise.all(tables.map(async table=>[table,(await pool.query(`SELECT row.* FROM new_design.${table} row ORDER BY to_jsonb(row)::text`)).rows]))),before=await frame();let calls=0,loseAi=true,loseTime=true;
 const time={lifecycle:'occurred',timeMode:'unknown',startCertainty:'unknown',endCertainty:'unknown',startInstant:null,endInstant:null,timezoneName:null,calendarKey:null,startLabel:null,endLabel:null,normalizedStart:null,normalizedEnd:null,durationValue:null,durationUnit:null,relativeToEventCardId:null,relativeRelation:null,relativeOffset:null,replacesTimingId:null,reason:'采用正文支持抵达经历，日期未知，需作者审核'},gateway=compiled('server/ai').createIndependentAiGateway({fetcher:async(_url,init)=>{calls++;const input=JSON.parse(JSON.parse(init.body).messages.at(-1).content).taskData.snapshot,body=input.bodies.find(item=>item.documentId===first.document.id),subject=input.actors.find(item=>item.id===actor.id),output={candidates:subject?[{id:subject.slotIds[0],characterId:actor.id,chapterDocumentId:body.documentId,bodyVersionId:body.bodyVersionId,title:'抵达渡口',summary:'原采用正文的抵达经历，故事时间仍待作者核对',evidenceStart:0,evidenceEnd:body.content.length,evidenceLabel:body.content,suggestedEventId:event.id,narrativeRole:'scene',time}]:[],notes:['章序不表示发生日期。']};return new Response(JSON.stringify({message:{content:JSON.stringify(output)},prompt_eval_count:80,eval_count:100}),{status:200});}});
 const base=`/books/${book.id}/character-experiences/recent-bodies`,http=await resourceSupplementHttp(t,{ai:gateway,beforeRouter:app=>{
  app.get('/fixture/verify',(_req,res,next)=>{void(async()=>{assert.deepEqual(await frame(),before);const proposals=(await pool.query('SELECT * FROM new_design.story_time_proposals WHERE book_id=$1 ORDER BY id',[book.id])).rows,timings=(await pool.query('SELECT * FROM new_design.story_event_timings WHERE book_id=$1 ORDER BY id',[book.id])).rows,records=(await pool.query('SELECT id,status,stage,prompt_id FROM new_design.ai_generation_batches WHERE book_id=$1 ORDER BY id',[book.id])).rows,anchors=(await pool.query("SELECT anchor.* FROM new_design.chapter_text_anchors anchor JOIN new_design.story_time_proposal_versions version ON version.text_anchor_id=anchor.id WHERE anchor.book_id=$1 ORDER BY anchor.id",[book.id])).rows;assert.ok(anchors.every(anchor=>anchor.body_version_id===first.version.id&&anchor.excerpt===first.version.content));return{success:true,database:f.database,providerCalls:calls,formalSourcesUnchanged:true,records,proposals:proposals.map(item=>({id:item.id,status:item.status})),timings:timings.map(item=>({id:item.id,lifecycle:item.lifecycle,evidenceKind:item.evidence_kind,bodyVersionId:item.body_version_id})),boundProofs:anchors.length};})().then(result=>res.json(result)).catch(next);});
  app.post('/fixture/finish',(_req,res)=>{res.json({success:true});setImmediate(async()=>{for(const finish of cleanup.reverse())await finish();});});
  app.use('/api/new-design',(req,res,next)=>{if(req.method==='POST'){const json=res.json.bind(res);res.json=value=>{if(req.path===base&&loseAi&&value.success&&value.data?.status==='review'){loseAi=false;res.destroy();return res;}if(req.path.endsWith('/composition-timeline/commands')&&loseTime&&value.success&&value.data?.operation==='time_create'){loseTime=false;res.destroy();return res;}return json(value);};}next();});
 }});process.stdout.write(JSON.stringify({database:f.database,origin:http.origin,bookId:book.id,characterId:actor.id,eventId:event.id,chapterDocumentIds:[first.document.id,second.document.id]})+'\n');
})().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
