const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{randomUUID}=require('node:crypto');
const {isolatedDatabase,compiled}=require('./support/isolatedDatabase.cjs'),key=()=>randomUUID();
const analysis={situation:['谨慎核对来信'],concerns:['信息尚不充分'],misreadings:[],pressureReactions:[],emotions:[],decisionTriggers:[],beliefs:[],inferenceBasis:['本人冻结档案'],uncertainties:['未确认信件真伪']};
const output=input=>({bookId:input.bookId,cardId:input.cardId,sourceHash:input.sourceHash,utterance:input.kind==='conversation'?'我会先核对来信。':'',analysis,sourceVersionIds:[]});
const install=async pool=>{await pool.query(fs.readFileSync(path.join(__dirname,'../migrations/099_dependency_creation_record_guards.sql'),'utf8'));await pool.query(fs.readFileSync(path.join(__dirname,'../migrations/101_character_author_trials.sql'),'utf8'));};
async function route(pool){const models=compiled('server/database/modelManagement'),current=(await pool.query("SELECT id,revision FROM new_design.model_route_configs WHERE scope='system_default' AND task_key IS NULL AND task_group IS NULL AND book_id IS NULL AND status='active'")).rows[0];await models.saveManagedModelRoute({scope:'system_default',taskType:null,replaceUnsupported:true,expectedConfigId:current?.id??null,expectedRevision:current?Number(current.revision):null,idempotencyKey:key(),primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'isolated-author-fixture',credentialId:null},fallbacks:[],policy:{maxOutputTokens:8192,maxTotalTokens:65536,timeoutMs:10000,maxRetries:0,retryDelayMs:0}});}
async function observe(pool,t){const watch=client=>{if(client.__authorObserved)return;client.__authorObserved=true;const query=client.query;client.query=function(...args){const value=query.apply(this,args);return value?.catch?value.catch(error=>{t.diagnostic(JSON.stringify({isolatedQueryFailure:{code:error.code,message:error.message,context:error.where,statement:String(args[0]).slice(0,180)}}));throw error;}):value;};};pool.on('connect',watch);const client=await pool.connect();watch(client);client.release();}
async function fixture(t){const {pool,database}=await isolatedDatabase(t);await observe(pool,t);const templates=compiled('server/database/templateStore'),store=compiled('server/database/store'),author=compiled('server/database/authorMaterials');let template=await templates.saveTemplate({key:`author_${key().replaceAll('-','')}`,name:'人物作者谈话隔离模板',description:'',draftConfig:{},requestKey:key()});template=await templates.publishTemplate(template.id,template.revision,key());const book=await templates.createBook({key:`author_${key().replaceAll('-','')}`,name:'隔离作者谈话',description:'虚构来信',templateVersionId:template.currentVersionId});const type=(await store.listCardTypes(book.spaceId)).find(item=>item.key==='character');const actor=(await author.createAuthorMaterial(book.id,{requestKey:key(),cardTypeId:type.id,title:'林舟',values:{name:'林舟',story_role:'supporting',age:0,personality:'谨慎'}})).card;return{pool,database,book,actor};}
test('single book character supports real author turns and scene analysis with immutable original execution, saved-only recovery and no formal changes',{timeout:150000},async t=>{
 if(!process.env.ND_REFERENCE_TEST_BUILD){t.skip('Final isolated work build required; author runtime is not used.');return;}
 const {pool,book,actor}=await fixture(t),db=compiled('server/database/characterAuthor'),app=compiled('server/application/characterAuthor'),spool=compiled('server/ai/imageGeneration/receipts');
 const workspace=()=>db.getCharacterAuthorWorkspace(book.id,actor.id,null),source=(await workspace()).source;assert.ok(source);assert.equal(source.data.chapters.length,0);assert.equal(source.data.profile.values.age,0);assert.equal(source.cardId,actor.id);
 let calls=0;const seen=[],dependencies={fetcher:async(_url,options)=>{calls++;const payload=JSON.parse(JSON.parse(options.body).messages[1].content).taskData;seen.push(payload);return new Response(JSON.stringify({message:{content:JSON.stringify({...output(payload.input),sourceVersionIds:[payload.source.data.profile.versionId]})},prompt_eval_count:13,eval_count:8}),{status:200,headers:{'Content-Type':'application/json'}});}};
 const input={requestKey:key(),bookId:book.id,cardId:actor.id,cutoffBodyVersionId:null,sourceHash:source.hash,kind:'conversation',message:'你如何看待这封来信？',historyKeys:[]},run=value=>app.runCharacterAuthor(value,dependencies);
 assert.deepEqual((await workspace()).capability,{installed:false,operational:false});await assert.rejects(run(input),error=>error.recovery.mutationOutcome==='not_written');assert.equal(calls,0);
 await install(pool);assert.deepEqual((await workspace()).capability,{installed:true,operational:false});await assert.rejects(run(input));assert.equal(calls,0);await pool.query("UPDATE new_design.character_author_capability SET operational=true");await route(pool);
 const tables=['cards','card_versions','books','card_relations','card_relation_versions','canonical_facts','state_changes','entity_initial_states','knowledge_state_changes','chapter_documents','chapter_body_versions','chapter_stable_checkpoints'],formal=async()=>Object.fromEntries(await Promise.all(tables.map(async table=>[table,(await pool.query(`SELECT coalesce(jsonb_agg(to_jsonb(row) ORDER BY to_jsonb(row)::text),'[]'::jsonb) data FROM new_design.${table} row`)).rows[0].data]))),before=await formal();
 await assert.rejects(run({...input,requestKey:key(),sourceHash:'f'.repeat(64)}),error=>error.status===409);assert.equal(calls,0);
 const [first,duplicate]=await Promise.all([run(input),run(input)]);assert.equal(first.id,duplicate.id);assert.ok([first,duplicate].some(value=>value.status==='succeeded'));assert.equal(calls,1);assert.equal((await run(input)).status,'succeeded');assert.equal(calls,1);assert.equal(seen[0].history.length,0);
 await assert.rejects(run({...input,message:'改动同一键'}),error=>error.status===409);assert.equal(calls,1);
 const secondInput={...input,requestKey:key(),message:'接下来会怎么做？',historyKeys:[input.requestKey]},second=await run(secondInput);assert.equal(second.status,'succeeded');assert.equal(seen[1].history[0].output.utterance,first.output?.utterance??'我会先核对来信。');assert.equal(calls,2);
 await assert.rejects(run({...input,requestKey:key(),historyKeys:[secondInput.requestKey]}),error=>error.status===409);assert.equal(calls,2);
 const sceneInput={...input,requestKey:key(),kind:'scene_analysis',message:'整理并说明未确认之处。',historyKeys:[input.requestKey,secondInput.requestKey]},scene=await run(sceneInput);assert.equal(scene.status,'succeeded');assert.equal(scene.output.analysis.uncertainties[0],analysis.uncertainties[0]);assert.equal(seen[2].history.length,2);assert.equal(calls,3);
 await assert.rejects(db.getCharacterAuthorWorkspace(key(),actor.id,null));await assert.rejects(run({...input,requestKey:key(),bookId:key()}));assert.equal(calls,3);
 const recoveryInput={...input,requestKey:key(),historyKeys:[input.requestKey,secondInput.requestKey,sceneInput.requestKey]},pending=await db.claimCharacterAuthor(recoveryInput);assert.equal(pending.claimed,true);await assert.rejects(run({...recoveryInput,requestKey:key()}),error=>error.status===409);assert.equal(calls,3);
 const refs={scopeKind:'character_author',bookId:book.id,cardId:actor.id,requestId:pending.result.id,attemptId:pending.attemptId,inputHash:pending.plan.inputHash},execution={provider:pending.plan.route.primary.provider,model:pending.plan.route.primary.model,routeSnapshotId:pending.plan.snapshotId,routeSnapshotHash:pending.plan.snapshotHash,attempts:[{status:'succeeded',requestSent:true,responseReceived:true}],inputTokens:13,outputTokens:8};
 await spool.writeCharacterAuthorReply(refs,{output:output(recoveryInput),execution});assert.equal(await spool.readCharacterAuthorReply({...refs,cardId:key()}),null);await assert.rejects(spool.readCharacterAuthorReply({...refs,inputHash:'f'.repeat(64)}));assert.equal((await db.readCharacterAuthorByKey(recoveryInput.requestKey)).canCompleteSaved,true);await assert.rejects(db.endExpiredCharacterAuthor(pending.result.id));const recovery=compiled('server/database/savedRecovery'),target={kind:'character_author',id:pending.result.id,bookId:book.id},checked=await recovery.inspectSavedRecovery(target);assert.equal(checked.canRecover,true);assert.ok((await recovery.getSavedRecoveryWorkspace(book.id)).items.some(item=>item.target.id===pending.result.id));const restoreInput={requestKey:key(),items:[{target,fingerprint:checked.fingerprint}]};assert.equal((await recovery.recoverSavedSources(restoreInput)).outcomes[0].completed,true);assert.equal((await recovery.recoverSavedSources(restoreInput)).outcomes[0].completed,false);assert.equal((await db.readCharacterAuthorByKey(recoveryInput.requestKey)).status,'succeeded');assert.equal(calls,3);
 await assert.rejects(pool.query("UPDATE new_design.character_author_trials SET input_payload=jsonb_set(input_payload,'{message}','\"forged\"') WHERE id=$1",[scene.id]),error=>error.code==='23514');await assert.rejects(pool.query('DELETE FROM new_design.character_author_trials WHERE id=$1',[scene.id]),error=>error.code==='23514');assert.deepEqual(await formal(),before);
 const ledger=(await pool.query('SELECT task.book_id,attempt.context_manifest_id,usage.input_tokens,usage.output_tokens FROM new_design.ai_tasks task JOIN new_design.ai_task_attempts attempt ON attempt.task_id=task.id JOIN new_design.ai_attempt_usage usage ON usage.attempt_id=attempt.id WHERE task.id=$1',[scene.id])).rows[0];assert.equal(ledger.book_id,book.id);assert.equal(Number(ledger.input_tokens),13);assert.equal(Number(ledger.output_tokens),8);assert.ok(ledger.context_manifest_id);
 // Original HTTP read and completion are real handlers; repeated read never starts generation.
 const express=require('express'),serverApp=express();serverApp.use(express.json());serverApp.use('/author',compiled('server/http/characterAuthor').characterAuthorRouter(dependencies));serverApp.use((error,req,res,next)=>res.status(error.status??500).json({success:false,error:error.message,recovery:error.recovery}));const server=serverApp.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const get=url=>new Promise((resolve,reject)=>http.get({host:'127.0.0.1',port:server.address().port,path:url},res=>{let raw='';res.on('data',chunk=>raw+=chunk);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw)}));}).on('error',reject));
 assert.equal((await get(`/author/by-key/${sceneInput.requestKey}`)).body.data.id,scene.id);assert.equal((await get(`/author/workspace?bookId=${book.id}&cardId=${actor.id}`)).body.data.results.length,4);assert.equal((await get(`/author/workspace?bookId=${book.id}&cardId=${key()}`)).status,404);assert.equal(calls,3);
 let invalidCalls=0;const invalidInput={...input,requestKey:key(),historyKeys:[input.requestKey,secondInput.requestKey,sceneInput.requestKey,recoveryInput.requestKey]},failed=await app.runCharacterAuthor(invalidInput,{fetcher:async()=>{invalidCalls++;return new Response(JSON.stringify({message:{content:'{}'},prompt_eval_count:5,eval_count:2}),{status:200,headers:{'Content-Type':'application/json'}});}});assert.equal(failed.status,'failed');assert.equal(failed.output,null);assert.equal(invalidCalls,1);assert.equal(Number((await pool.query('SELECT input_tokens FROM new_design.ai_attempt_usage WHERE task_id=$1',[failed.id])).rows[0].input_tokens),5);
 let unknownCalls=0;const unknownInput={...input,requestKey:key(),historyKeys:[input.requestKey,secondInput.requestKey,sceneInput.requestKey,recoveryInput.requestKey]},unknown=await app.runCharacterAuthor(unknownInput,{fetcher:async()=>{unknownCalls++;throw Error('isolated response lost after send');}});assert.equal(unknown.status,'running');assert.equal(unknown.canCompleteSaved,false);assert.equal((await app.runCharacterAuthor(unknownInput,{fetcher:async()=>{unknownCalls++;throw Error('must not resend');}})).id,unknown.id);assert.equal(unknownCalls,1);await assert.rejects(db.endExpiredCharacterAuthor(unknown.id));const unknownStep=(await pool.query('SELECT step_id FROM new_design.character_author_trials WHERE id=$1',[unknown.id])).rows[0].step_id;await pool.query("UPDATE new_design.ai_task_steps SET lease_expires_at=now()-interval '1 second',revision=revision+1 WHERE id=$1",[unknownStep]);assert.equal((await db.readCharacterAuthorByKey(unknownInput.requestKey)).canEndExpired,true);assert.equal((await db.endExpiredCharacterAuthor(unknown.id)).status,'ended_unknown');assert.equal(unknownCalls,1);assert.equal(Number((await pool.query("SELECT count(*) FROM new_design.ai_attempt_usage WHERE task_id=$1 AND input_tokens IS NULL AND output_tokens IS NULL AND budget_decision='unknown'",[unknown.id])).rows[0].count),1);assert.deepEqual(await formal(),before);
 await pool.query('UPDATE new_design.character_author_capability SET operational=false');assert.equal((await run(input)).id,first.id);await assert.rejects(run({...input,requestKey:key()}));assert.equal(calls,3);assert.deepEqual(await formal(),before);
 t.diagnostic('One character and no chapter/checkpoint are sufficient. Only fixture text responses are used; original formal book content remains unchanged.');
});
test('author scene sources include original current relations while confirmed state is bounded by exact adopted cutoff; late reply is retained as stale',{timeout:150000},async t=>{
 if(!process.env.ND_REFERENCE_TEST_BUILD){t.skip('Final isolated work build required.');return;}
 const {resourceSupplementFixture}=require('./support/resourceSupplementFixture.cjs'),f=await resourceSupplementFixture(t),{pool,book,actor,settlement}=f;await observe(pool,t);await install(pool);await route(pool);await pool.query('UPDATE new_design.character_author_capability SET operational=true');
 const other=await f.create('character','关联人物',{name:'关联人物',story_role:'supporting'}),definition={name:'隔离作者关系',description:'当前关系设定不冒充过去发生事实',direction:'directed',sourceTypeKeys:['character'],targetTypeKeys:['character'],sourceMax:null,targetMax:null,fields:[{key:'trust',name:'信任',type:'number',description:'',required:false,defaultValue:null,options:[],group:'关系',order:1,aiSuggestible:true}],capability:'optional',mode:'relation_state',dimensions:[{fieldKey:'trust',label:'信任',direction:'forward',policy:'tracked',mode:'absolute'}]};
 const draft=await settlement.saveSettlementRelationConfigurationDraft(book.id,{requestKey:key(),expectedRelationTypeRevision:null,definition});await settlement.publishSettlementRelationConfigurationDraft(book.id,{requestKey:key(),draftId:draft.draftId,expectedRevision:1,confirmPublish:true,confirmInstanceRebind:false,rebindRelations:[],createRelations:[{sourceCardId:actor.id,targetCardId:other.id}]});
 const relation=(await pool.query('SELECT * FROM new_design.card_relations WHERE source_card_id=$1 AND target_card_id=$2',[actor.id,other.id])).rows[0];await f.state.saveInitialState({bookId:book.id,subjectKind:'relation',subjectId:relation.id,stateKey:'trust',value:0,requestKey:key(),actor:'isolated_test',note:''});
 const first=await f.chapter(1,1),second=await f.chapter(2,2),db=compiled('server/database/characterAuthor'),workspace=await db.getCharacterAuthorWorkspace(book.id,actor.id,first.version.id),source=workspace.source;
 assert.equal(source.data.chapters.length,1);assert.equal(source.data.chapters[0].bodyVersionId,first.version.id);assert.equal(source.data.relations.length,1);assert.equal(source.data.relations[0].targetId,other.id);assert.equal(source.data.relations[0].targetVersionId,(await pool.query('SELECT current_version_id FROM new_design.cards WHERE id=$1',[other.id])).rows[0].current_version_id);assert.ok(source.data.states.some(item=>item.subjectKind==='relation'&&item.value===0));assert.ok(source.data.states.some(item=>item.kind==='change'&&item.value===1));assert.ok(!source.data.states.some(item=>item.kind==='change'&&item.value===2));assert.ok(!source.versionIds.includes(second.version.id));
 assert.equal((await db.getCharacterAuthorWorkspace(book.id,actor.id,null)).source,null);
 const input={requestKey:key(),bookId:book.id,cardId:actor.id,cutoffBodyVersionId:first.version.id,sourceHash:source.hash,kind:'scene_analysis',message:'只用截至第一章的发生内容。',historyKeys:[]},pending=await db.claimCharacterAuthor(input),refs={scopeKind:'character_author',bookId:book.id,cardId:actor.id,requestId:pending.result.id,attemptId:pending.attemptId,inputHash:pending.plan.inputHash};
 const execution={provider:pending.plan.route.primary.provider,model:pending.plan.route.primary.model,routeSnapshotId:pending.plan.snapshotId,routeSnapshotHash:pending.plan.snapshotHash,attempts:[{status:'succeeded',requestSent:true,responseReceived:true}]};await compiled('server/ai/imageGeneration/receipts').writeCharacterAuthorReply(refs,{output:{...output(input),sourceVersionIds:[relation.current_version_id,first.version.id]},execution});
 await pool.query("UPDATE new_design.ai_task_steps SET lease_expires_at=now()-interval '1 second',revision=revision+1 WHERE id=$1",[(await pool.query('SELECT step_id FROM new_design.character_author_trials WHERE id=$1',[pending.result.id])).rows[0].step_id]);
 assert.equal((await db.completeCharacterAuthor(pending.result.id)).status,'stale');assert.equal((await db.readCharacterAuthorByKey(input.requestKey)).output.sourceHash,source.hash);assert.equal(Number((await pool.query('SELECT count(*) FROM new_design.ai_attempt_usage WHERE task_id=$1 AND input_tokens IS NULL AND output_tokens IS NULL AND budget_decision=\'unknown\'',[pending.result.id])).rows[0].count),1);
});
