const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {compiled}=require('./support/isolatedDatabase.cjs'),key=()=>randomUUID();
test('character author contract rejects missing explicit source and unbounded or malformed history',()=>{
 const {characterAuthorInputSchema:schema}=compiled('common/characterAuthor'),input={requestKey:key(),bookId:key(),cardId:key(),cutoffBodyVersionId:null,sourceHash:'a'.repeat(64),kind:'conversation',message:'保留作者消息',historyKeys:[]};
 assert.equal(schema.parse(input).cutoffBodyVersionId,null);for(const wrong of [{...input,sourceHash:undefined},{...input,cutoffBodyVersionId:'foreign'},{...input,message:' '},{...input,historyKeys:Array.from({length:101},key)},{...input,participantCardIds:[key()]}])assert.equal(schema.safeParse(wrong).success,false);
});
test('independent author prompt requires the exact one character, frozen source, bounded citations and actual response',()=>{
 const {preparePrompt}=compiled('server/ai/prompts'),{stableHash}=compiled('server/database/aiContracts'),bookId=key(),cardId=key(),versionId=key(),data={book:{id:bookId},profile:{id:cardId,versionId,values:{age:0}},relations:[],chapters:[],states:[],knowledge:[]},source={bookId,cardId,cutoffBodyVersionId:null,data,versionIds:[versionId],hash:stableHash({bookId,cardId,cutoffBodyVersionId:null,data})},input={requestKey:key(),bookId,cardId,cutoffBodyVersionId:null,sourceHash:source.hash,kind:'conversation',message:'原作者话语',historyKeys:[]},payload={contract:'character_author_v1',input,source,history:[]},analysis={situation:[],concerns:[],misreadings:[],pressureReactions:[],emotions:[],decisionTriggers:[],beliefs:[],inferenceBasis:['原档案'],uncertainties:[]},output={bookId,cardId,sourceHash:source.hash,utterance:'先核对情况。',analysis,sourceVersionIds:[versionId]},prompt=preparePrompt('character_author',payload);
 assert.equal(prompt.assetId,'new_design.character.author_conversation');assert.deepEqual(prompt.parseOutput(output),output);assert.equal(JSON.parse(prompt.messages[1].content).taskData.source.data.profile.values.age,0);
 for(const wrong of [{...output,bookId:key()},{...output,cardId:key()},{...output,sourceHash:'b'.repeat(64)},{...output,sourceVersionIds:[key()]},{...output,utterance:' '},{...output,analysis:{...analysis,fakeFact:true}}])assert.throws(()=>prompt.parseOutput(wrong));
 const scene=preparePrompt('character_author',{...payload,input:{...input,kind:'scene_analysis'}});assert.equal(scene.parseOutput({...output,utterance:''}).analysis.inferenceBasis[0],'原档案');assert.throws(()=>scene.parseOutput({...output,utterance:'',analysis:{...analysis,inferenceBasis:[]}}));assert.throws(()=>preparePrompt('character_author',{...payload,source:{...source,cardId:key()}}));
});
