const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const {compiled}=require('./support/isolatedDatabase.cjs'),contracts=compiled('common/characterImport'),moduleValue={exports:{}};
new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/client/characterImport/draft.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>name==='zod'?require('zod'):contracts,moduleValue,moduleValue.exports);
const draft=moduleValue.exports,key=()=>randomUUID();
function fixture(){const bookId=key(),input={requestKey:key(),resourceId:key(),resourceVersionId:key(),title:'书内人物',mapping:[{sourceKey:'publicAge',targetKey:'privateAge',value:0},{sourceKey:'publicFlag',targetKey:'privateFlag',value:false}],additionalValues:{name:'人物',story_role:'supporting'},previewHash:'a'.repeat(64)},card={id:key(),cardTypeId:key()},receipt={bookId,requestKey:input.requestKey,input,mappedFields:input.mapping.map(item=>({sourceKey:item.sourceKey,sourceLabel:'来源',targetKey:item.targetKey,targetLabel:'本书'})),resourceId:input.resourceId,resourceVersionId:input.resourceVersionId,receipt:{bookId,requestKey:input.requestKey,operation:'create',cardVersionId:key(),card},sourceRoute:`/new-design/books/${bookId}/story-setting?tab=characters&selected=${card.id}&type=${card.cardTypeId}&detail=basic`};return{bookId,input,receipt};}
test('draft and complete original command retain distinct mapping keys, zero and false across refresh',()=>{
 const f=fixture(),saved=draft.importDraftSchema.parse(JSON.parse(JSON.stringify(draft.draftOf(f.bookId,f.input))));assert.equal(saved.mapping.publicAge.targetKey,'privateAge');assert.equal(saved.mapping.publicAge.value,0);assert.equal(saved.mapping.publicFlag.value,false);assert.equal(contracts.characterImportCommitSchema.safeParse(f.input).success,true);assert.equal(contracts.characterImportCommitSchema.safeParse({...f.input,mapping:[{sourceKey:'publicFlag',targetKey:'privateFlag'}]}).success,false);
 assert.equal(draft.importDraftSchema.safeParse({...saved,bookId:'other'}).success,false);assert.equal(draft.importDraftSchema.safeParse({...saved,mapping:{lost:{targetKey:'missing-value'}}}).success,false);assert.deepEqual([null,'',[],{},0,false,'内容'].map(contracts.importValuePresent),[false,false,false,false,true,true,true]);
});
test('receipt accepts JSON object-key reordering and rejects different book, source version or field mapping',()=>{
 const f=fixture();assert.equal(draft.validImportReceipt(f.receipt,f.bookId,f.input),true);const reordered={...f.input,mapping:f.input.mapping.map(item=>({value:item.value,targetKey:item.targetKey,sourceKey:item.sourceKey}))};assert.equal(draft.validImportReceipt(f.receipt,f.bookId,reordered),true);assert.equal(draft.validImportReceipt(f.receipt,key(),f.input),false);for(const changed of [{...f.input,resourceVersionId:key()},{...f.input,mapping:f.input.mapping.map(item=>({...item,value:1}))},{...f.input,title:'另一份'}])assert.equal(draft.validImportReceipt(f.receipt,f.bookId,changed),false);
 assert.equal(draft.validImportReceipt({...f.receipt,sourceRoute:'https://foreign.example'},f.bookId,f.input),false);assert.equal(draft.validImportReceipt({...f.receipt,mappedFields:[]},f.bookId,f.input),false);assert.equal(draft.validImportReceipt({...f.receipt,receipt:{...f.receipt.receipt,operation:'update'}},f.bookId,f.input),false);
});
