const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {isolatedDatabase,compiled}=require('./support/isolatedDatabase.cjs');const key=()=>randomUUID();
const time={lifecycle:'planned',timeMode:'unknown',startCertainty:'unknown',endCertainty:'unknown',startInstant:null,endInstant:null,timezoneName:null,calendarKey:null,startLabel:null,endLabel:null,normalizedStart:null,normalizedEnd:null,durationValue:null,durationUnit:null,relativeToEventCardId:null,relativeRelation:null,relativeOffset:null,replacesTimingId:null,reason:'人物小传明确记载，时间未知，等待人工核对。'};
test('biography candidates retain original sources and use actual editable time, review, relation and occurrence contracts',async t=>{
 const {pool,database}=await isolatedDatabase(t);t.diagnostic(`Isolated database retained: ${database}`);
 const templates=compiled('server/database/templateStore'),cards=compiled('server/database/store'),fields=compiled('server/database/fieldExtensions'),experiences=compiled('server/database/characterExperiences'),timeline=compiled('server/database/bookComposition'),ai=compiled('server/ai'),models=compiled('server/database/modelManagement'),author=compiled('server/database/authorMaterials'),prompts=compiled('server/ai/prompts'),schema=compiled('common/characterExperiences/schema');
 let template=await templates.saveTemplate({key:`e_${key().replaceAll('-','')}`,name:'经历隔离模板',description:'',draftConfig:{},requestKey:key()});template=await templates.publishTemplate(template.id,template.revision,key());const book=await templates.createBook({key:`e_${key().replaceAll('-','')}`,name:'经历隔离书',description:'',templateVersionId:template.currentVersionId}),types=await cards.listCardTypes(book.spaceId),characterType=types.find(type=>type.key==='character'),extension=await fields.createBookFieldExtension(book.id,{cardTypeId:characterType.id,expectedTypeRevision:characterType.revision,field:{name:'人物小传',description:'明确来源文本',type:'long_text',required:false,defaultValue:null,options:[],group:'档案',aiSuggestible:true,stateSettlement:'none'},backfillStrategy:'none',idempotencyKey:key(),createdBy:'isolated_test'}),bio=extension.fieldKey,text='隔离人物年少时取得一把短刀，之后离开故乡。';
 const actor=await cards.createCard({cardTypeId:characterType.id,spaceId:book.spaceId,title:'隔离人物',values:{name:'隔离人物',story_role:'protagonist',[bio]:text}}),other=await cards.createCard({cardTypeId:characterType.id,spaceId:book.spaceId,title:'第二人物',values:{name:'第二人物',story_role:'supporting',[bio]:'第二人物在故乡学习医术。'}});
 async function material(typeKey,title){const type=types.find(type=>type.key===typeKey),values=Object.fromEntries(type.draftFields.filter(field=>field.required).map(field=>[field.key,title]));return cards.createCard({cardTypeId:type.id,spaceId:book.spaceId,title,values});}
 const event=await material('event','取得短刀'),secondEvent=await material('event','离开故乡'),chapter=await material('chapter','离乡');
 const workspace=await experiences.getExperienceWorkspace(book.id,actor.id);assert.equal(workspace.sourceFields.find(field=>field.key===bio).text,text);assert.equal(workspace.events.length,2);
 const route={primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'isolated-stub-never-real-model',credentialId:null},fallbacks:[],policy:{maxOutputTokens:16000,maxTotalTokens:1000000,timeoutMs:30000,maxRetries:0,retryDelayMs:0}};for(const [scope,taskType]of [['system_default',null],['task','form_assist']]){const current=(await models.getModelRouteCenterCatalog()).routes.find(item=>item.scope===scope&&item.taskType===taskType);await models.saveManagedModelRoute({...route,scope,taskType,expectedConfigId:current?.id??null,expectedRevision:current?.revision??null,replaceUnsupported:true,idempotencyKey:key()});}
 let calls=0;const gateway=ai.createIndependentAiGateway({fetcher:async(url,init)=>{calls++;const input=JSON.parse(JSON.parse(init.body).messages.at(-1).content).taskData,candidates=input.actors.map(actor=>({id:actor.slotIds[0],characterId:actor.id,fieldKey:actor.fieldKey,title:'小传经历',summary:'人工核对人物小传中的经历。',evidenceStart:0,evidenceEnd:actor.text.length,evidenceLabel:actor.text,suggestedEventId:null,time}));return new Response(JSON.stringify({message:{content:JSON.stringify({candidates,notes:['未猜测日期。']})},prompt_eval_count:100,eval_count:120}),{status:200});}});
 const input={requestKey:key(),instruction:'只核对已有小传',sources:[{characterId:actor.id,fieldKey:bio},{characterId:other.id,fieldKey:bio}]},record=await experiences.generateExperiences(book.id,input,gateway);assert.equal(record.status,'review');assert.equal(record.output.candidates.length,2);assert.equal(calls,1);assert.equal(schema.validExperienceRecord(record),true);assert.equal((await experiences.generateExperiences(book.id,input,gateway)).id,record.id);assert.equal(calls,1);assert.equal((await experiences.readExperienceOriginal(book.id,input)).id,record.id);await assert.rejects(experiences.readExperienceOriginal(book.id,{...input,instruction:'改变原范围'}),error=>error.mutationOutcome==='unknown');
 const proposalCounts=()=>pool.query('SELECT (SELECT count(*) FROM new_design.story_time_proposals)::integer proposals,(SELECT count(*) FROM new_design.story_event_timings)::integer timings,(SELECT count(*) FROM new_design.state_changes)::integer states,(SELECT count(*) FROM new_design.current_knowledge_state_projections)::integer knowledge');assert.deepEqual((await proposalCounts()).rows[0],{proposals:0,timings:0,states:0,knowledge:0});
 const first=record.output.candidates.find(candidate=>candidate.characterId===actor.id),draft=await experiences.getExperienceDraft(book.id,record.id,first.id,event.id),source=await timeline.getBookCompositionTimelineWorkspace(book.id),preview=await timeline.previewBookCompositionTimeline(book.id,{requestKey:key(),expectedSourceHash:source.sourceHash,command:draft.command,candidateSource:draft.source});assert.equal(preview.input.candidateSource.sourceHash,draft.source.sourceHash);
 const save={...preview.input,previewHash:preview.previewHash},results=await Promise.all([timeline.saveBookCompositionTimeline(book.id,save),timeline.saveBookCompositionTimeline(book.id,save)]);assert.equal(new Set(results.map(result=>result.result.id)).size,1);assert.equal(results.filter(result=>result.repeated).length,1);let proposal=results[0].result;assert.equal(proposal.status,'proposed');assert.equal(proposal.proposalSource,'manual');assert.equal(proposal.currentVersion.lifecycle,'planned');assert.equal(proposal.currentVersion.evidenceKind,'manual');assert.equal((await timeline.readBookCompositionTimelineOriginalReceipt(book.id,save)).result.id,proposal.id);await assert.rejects(timeline.readBookCompositionTimelineOriginalReceipt(book.id,{...save,command:{...save.command,value:{...save.command.value,reason:'different'}}}),error=>error.mutationOutcome==='unknown');assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.form_ai_draft_decisions WHERE batch_id=$1 AND candidate_id=$2',[record.id,first.id])).rows[0].n,1);
 const after=await timeline.getBookCompositionTimelineWorkspace(book.id);await assert.rejects(timeline.previewBookCompositionTimeline(book.id,{...preview.input,requestKey:key(),expectedSourceHash:after.sourceHash}),error=>error.status===409);await assert.rejects(timeline.previewBookCompositionTimeline(book.id,{...preview.input,requestKey:key(),expectedSourceHash:after.sourceHash,candidateSource:{...draft.source,sourceHash:'a'.repeat(64)}}),error=>error.status===409);
 async function execute(command){const ws=await timeline.getBookCompositionTimelineWorkspace(book.id),p=await timeline.previewBookCompositionTimeline(book.id,{requestKey:key(),expectedSourceHash:ws.sourceHash,command});return timeline.saveBookCompositionTimeline(book.id,{...p.input,previewHash:p.previewHash});}
 proposal=(await execute({operation:'time_edit',proposalId:proposal.id,expectedRevision:proposal.revision,value:{...draft.command.value,timeMode:'partial',startCertainty:'partial',startLabel:'年少时期',reason:'人工核对小传，保持计划安排'}})).result;assert.equal(proposal.versions.length,2);proposal=(await execute({operation:'time_review',proposalId:proposal.id,expectedRevision:proposal.revision,action:'confirm',note:'明确确认计划安排，未声称正文已发生。'})).result;assert.equal(proposal.status,'confirmed');assert.equal((await timeline.getBookCompositionTimelineWorkspace(book.id)).timings[0].lifecycle,'planned');
 const evidence={evidenceKind:'manual',chapterDocumentId:null,bodyVersionId:null,textAnchorId:null,factId:null,planVersionId:null,stateProposalId:null},relation=(await execute({operation:'relation_create',value:{...evidence,relationFamily:'temporal',relationType:'before',sourceEventCardId:event.id,targetEventCardId:secondEvent.id,confidence:null,reason:'作者明确核对事件安排。'}})).result;const changedRelation=(await execute({operation:'relation_edit',proposalId:relation.id,expectedRevision:relation.revision,value:{...evidence,relationFamily:'temporal',relationType:'before',sourceEventCardId:event.id,targetEventCardId:secondEvent.id,confidence:.8,reason:'人工修订原关系说明。'}})).result;assert.equal((await execute({operation:'relation_review',proposalId:relation.id,expectedRevision:changedRelation.revision,action:'confirm',note:'明确审核关系'})).result.status,'confirmed');
 const occurrence=(await execute({operation:'occurrence_create',value:{eventCardId:event.id,chapterCardId:chapter.id,sceneCardId:null,chapterDocumentId:null,bodyVersionId:null,textAnchorId:null,role:'flashback',narrativeOrder:0,sourceKind:'manual',note:'明确叙述引用，正文保持。'}})).result;assert.equal(occurrence.narrativeOrder,0);assert.equal((await execute({operation:'occurrence_edit',occurrenceId:occurrence.id,expectedRevision:occurrence.revision,value:{eventCardId:event.id,chapterCardId:chapter.id,sceneCardId:null,chapterDocumentId:null,bodyVersionId:null,textAnchorId:null,role:'retell',narrativeOrder:1,sourceKind:'manual',note:'人工修改叙述位置'}})).result.revision,2);
 const second=record.output.candidates.find(candidate=>candidate.characterId===other.id),secondDraft=await experiences.getExperienceDraft(book.id,record.id,second.id,secondEvent.id),secondSource=await timeline.getBookCompositionTimelineWorkspace(book.id),secondPreview=await timeline.previewBookCompositionTimeline(book.id,{requestKey:key(),expectedSourceHash:secondSource.sourceHash,command:secondDraft.command,candidateSource:secondDraft.source}),secondSave={...secondPreview.input,previewHash:secondPreview.previewHash};
 const realConnect=pool.connect.bind(pool);let lost=false;pool.connect=function(callback){if(callback)return realConnect(callback);return realConnect().then(client=>{if(!client.experienceLostAck){client.experienceLostAck=true;const query=client.query.bind(client);client.query=async(...args)=>{const result=await query(...args);if(args[0]==='COMMIT'&&!lost){lost=true;throw new Error('isolated lost acknowledgement');}return result;};}return client;});};await assert.rejects(timeline.saveBookCompositionTimeline(book.id,secondSave),error=>error.mutationOutcome==='unknown');pool.connect=realConnect;const recovered=await timeline.readBookCompositionTimelineOriginalReceipt(book.id,secondSave);assert.ok(recovered);assert.equal(recovered.candidateSource.candidateId,second.id);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.story_time_proposals WHERE event_card_id=$1',[secondEvent.id])).rows[0].n,1);
 const thirdInput={requestKey:key(),instruction:'新的明确准备',sources:[{characterId:actor.id,fieldKey:bio}]},third=await experiences.generateExperiences(book.id,thirdInput,gateway);const actorCurrent=(await pool.query('SELECT * FROM new_design.cards WHERE id=$1',[actor.id])).rows[0];await author.updateAuthorMaterial(book.id,actor.id,{requestKey:key(),cardTypeId:characterType.id,title:actorCurrent.title,values:{...actorCurrent.values,[bio]:text+'人工补充。'},revision:actorCurrent.revision});await assert.rejects(experiences.getExperienceDraft(book.id,third.id,third.output.candidates[0].id,event.id),error=>error.status===409);
 const tasks=await compiled('server/database/authorTasks').listAuthorTasks({bookId:book.id,limit:100});const task=tasks.items.find(item=>item.id===`story_batch:${record.id}`);assert.ok(task);assert.match(task.source.route,new RegExp(`experienceBatch=${record.id}`));assert.match(task.source.route,new RegExp(`selected=${actor.id}`));assert.equal(task.title,'人物经历时间候选');
 const unknownInput={requestKey:key(),instruction:'原未知准备',sources:[{characterId:actor.id,fieldKey:bio}]};let unknownCalls=0;const unknownGateway={...gateway,generateCharacterExperiences:async()=>{unknownCalls++;const error=new ai.AiExecutionError('等待原经历回复','原调用未知');error.executionSnapshot={attempts:[{requestSent:true,responseReceived:false}],usageStatus:'unknown'};throw error;}};await assert.rejects(experiences.generateExperiences(book.id,unknownInput,unknownGateway),error=>error.mutationOutcome==='unknown');const unknownRecord=await experiences.readExperienceOriginal(book.id,unknownInput);assert.equal(unknownRecord.stage,'result_unknown');assert.equal((await experiences.generateExperiences(book.id,unknownInput,unknownGateway)).status,'running');assert.equal(unknownCalls,1);const unknownLock=await pool.connect();try{await unknownLock.query('SELECT pg_advisory_lock(hashtextextended($1,0))',[`experience-execution:${unknownInput.requestKey}`]);await assert.rejects(experiences.endUnknownExperiences(book.id,unknownInput),error=>error.status===409);}finally{await unknownLock.query('SELECT pg_advisory_unlock(hashtextextended($1,0))',[`experience-execution:${unknownInput.requestKey}`]);unknownLock.release();}const ended=await experiences.endUnknownExperiences(book.id,unknownInput);assert.equal(ended.stage,'ended_unknown');assert.equal(ended.output,null);assert.equal(unknownCalls,1);assert.equal((await experiences.readExperienceOriginal(book.id,unknownInput)).status,'discarded');
 assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.state_changes')).rows[0].n,0);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.current_knowledge_state_projections')).rows[0].n,0);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.chapter_body_versions')).rows[0].n,0);assert.equal(calls,2);
});
