const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const common=require('../dist/common/creativeExtraction');
const {creativeExtractionAsset,creativeTaskInputSchema}=require('../dist/server/ai/prompts/creativeExtraction');
const {creativeTransaction,withCreativeExtractionPool}=require('../dist/server/database/creativeExtraction/repository');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,hash='a'.repeat(64);
const prepare={requestKey:id(1),bookId:id(2),mode:'title_groups',instruction:'三组仙侠中文书名',source:null,typeId:null,typeVersionId:null,documentId:null,bodyVersionId:null,expectedDocumentRevision:null,groupCount:3,candidatesPerGroup:2};
const task={book:{id:id(2),name:'守脉者',description:'少年寻找记忆',revision:1},mode:'title_groups',instruction:'三组中文标题',source:null,fields:[],typeId:null,typeVersionId:null,body:null,groupCount:3,candidatesPerGroup:2};
const candidate=(group,title)=>({group,title,values:{},content:null,reason:'明确读者体验',risks:['撞名需人工核对']});
function recovery(){const source=fs.readFileSync(path.join(__dirname,'../src/client/creativeExtraction/recovery.ts'),'utf8'),module={exports:{}};new Function('module','exports','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(module,module.exports,request=>request==='zod'?require('zod'):common);return module.exports;}
test('creative source and preparation are strict exact scoped contracts, not user supplied catalog overrides',()=>{assert.deepEqual(common.prepareCreativeSchema.parse(prepare),prepare);assert.throws(()=>common.prepareCreativeSchema.parse({...prepare,fields:[]}));assert.throws(()=>common.prepareCreativeSchema.parse({...prepare,mode:'writing_resource'}));assert.throws(()=>common.prepareCreativeSchema.parse({...prepare,source:{kind:'research',documentId:id(3),versionId:id(4),checksum:hash,start:10,end:9}}));assert.throws(()=>common.creativeSourceSchema.parse({kind:'text',title:'参考',text:'  '}));});
test('creative title dynamic output preserves exact group and count and does not provide adoption permissions',()=>{const {schema}=creativeExtractionAsset.prepare(task),good={candidates:[candidate('悬疑','断脉山'),candidate('悬疑','失忆仙途'),candidate('成长','守山少年'),candidate('成长','灵脉归途'),candidate('诗意','山河记'),candidate('诗意','云外旧梦')],notes:[]};assert.deepEqual(schema.parse(good),good);assert.throws(()=>schema.parse({...good,candidates:good.candidates.slice(1)}));assert.throws(()=>schema.parse({...good,adopt:true}));assert.throws(()=>schema.parse({...good,candidates:[{...good.candidates[0],id:id(9)},...good.candidates.slice(1)]}));});
test('creative writing fields obey actual schema and dictionary values, not guessed field names',()=>{const fields=[{key:'unexpected_stable_key',name:'句式策略',description:'正式内容字段',type:'select',required:true,options:[{value:id(11),label:'长短交错'}]}],prepared=creativeExtractionAsset.prepare({...task,mode:'writing_resource',fields,typeId:id(12),typeVersionId:id(13)}),good={candidates:[{...candidate('写法','节奏策略'),values:{unexpected_stable_key:id(11)}}],notes:[]};assert.deepEqual(prepared.schema.parse(good),good);assert.throws(()=>prepared.schema.parse({...good,candidates:[{...good.candidates[0],values:{unexpected_stable_key:'长短交错'}}]}));assert.throws(()=>prepared.schema.parse({...good,candidates:[{...good.candidates[0],values:{unexpected_stable_key:id(11),pace:'私加字段'}}]}));assert.throws(()=>creativeExtractionAsset.prepare({...task,mode:'writing_resource',fields:[]}));});
test('creative cleaning freezes original body and exact adopted planning version, rejects empty candidate',()=>{const body={documentId:id(21),versionId:id(22),hash,content:'本章完整原正文',revision:3,planningObjectId:id(23),planningVersionId:id(24),planningHash:hash},input={...task,mode:'style_cleaning',body};assert.deepEqual(creativeTaskInputSchema.parse(input).body,body);assert.throws(()=>creativeTaskInputSchema.parse({...input,body:{...body,planningVersionId:null}}));const {schema}=creativeExtractionAsset.prepare(input);assert.throws(()=>schema.parse({candidates:[{...candidate('清洗','本章候选'),content:'   '}],notes:[]}));assert.equal(schema.parse({candidates:[{...candidate('清洗','本章候选'),content:'独立表达的完整本章候选'}],notes:[]}).candidates[0].content,'独立表达的完整本章候选');});
test('creative prepare receipt compares original full input and cannot acknowledge another reference',()=>{const policy=recovery(),pending={phase:'prepare',bookId:id(2),input:prepare},preview={id:id(30),bookId:id(2),requestKey:id(1),mode:'title_groups',input:task,originalInput:prepare,status:'ready'};assert.equal(policy.creativePreviewMatches(preview,pending),true);assert.equal(policy.creativePreviewMatches({...preview,originalInput:{...prepare,instruction:'另一要求'}},pending),false);assert.equal(policy.creativePreviewMatches({...preview,bookId:id(31)},pending),false);});
test('creative running original receipt remains pending, terminal receipt requires exact original run input and task refs',()=>{const policy=recovery(),input={requestKey:id(40),expectedRevision:1},pending={phase:'run',bookId:id(2),previewId:id(30),input},preview={id:id(30),bookId:id(2),input:task,runInput:input,status:'running',taskId:id(41),attemptId:id(42)};assert.equal(policy.creativePreviewMatches(preview,pending),true);assert.equal(policy.creativeRunSettled(preview,pending),false);assert.equal(policy.creativeRunSettled({...preview,status:'succeeded'},pending),true);assert.equal(policy.creativeRunSettled({...preview,status:'succeeded',runInput:{...input,expectedRevision:2}},pending),false);assert.equal(policy.creativeRunSettled({...preview,status:'succeeded',attemptId:null},pending),false);});
test('creative title write receipt requires full exact command and actual newer book revision',()=>{const policy=recovery(),command={operation:'adopt_title',requestKey:id(50),previewId:id(30),candidateId:null,expectedPreviewRevision:1,title:'新书名',expectedBookRevision:1,confirm:true},pending={phase:'save',bookId:id(2),previewId:id(30),input:command},receipt={requestKey:id(50),previewId:id(30),operation:'adopt_title',bookId:id(2),command,resourceId:null,versionId:null,bodyVersionId:null,bookRevision:2};assert.equal(policy.creativeReceiptMatches(receipt,pending),true);assert.equal(policy.creativeReceiptMatches({...receipt,command:{...command,title:'另一书名'}},pending),false);assert.equal(policy.creativeReceiptMatches({...receipt,bookRevision:1},pending),false);assert.equal(policy.creativeReceiptMatches({...receipt,bodyVersionId:id(51)},pending),false);});
test('creative acknowledged local rollback and ambiguous COMMIT have distinct outcomes; no real database is used',async()=>{for(const committing of [false,true]){const client={query:async sql=>{if(committing&&sql==='COMMIT')throw new Error('fixture disconnected');return{rows:[]};},release(){}};await withCreativeExtractionPool({connect:async()=>client},async()=>assert.rejects(creativeTransaction('保存专项候选',id(2),async()=>{if(!committing)throw new Error('fixture sql error');return{};}),error=>error.recovery.mutationOutcome===(committing?'unknown':'not_written')&&!error.message.includes('fixture')));}});
test('creative original key collision stays unknown despite current rollback',async()=>{const client={query:async()=>({rows:[]}),release(){}};await withCreativeExtractionPool({connect:async()=>client},async()=>assert.rejects(creativeTransaction('保存专项候选',id(2),async(_,conflict)=>{conflict();throw new Error('fixture conflict');}),error=>error.recovery.mutationOutcome==='unknown'));});
test('creative original fact consumers and recovery have no second adopted body or title fact',()=>{const read=file=>fs.readFileSync(path.join(__dirname,'../',file),'utf8'),commands=read('src/server/database/creativeExtraction/commands.ts'),application=read('src/server/application/creativeExtraction/index.ts'),ui=read('src/client/creativeExtraction/index.tsx'),sql=read('migrations/078_creative_extraction.sql');assert.match(commands,/INSERT INTO new_design.chapter_body_versions/);assert.match(commands,/UPDATE new_design.books SET name=\$2,revision=revision\+1/);assert.ok(!commands.includes('SET adopted_version_id'));assert.ok(!sql.includes('CREATE TABLE titles'));assert.match(sql,/BEFORE UPDATE OR DELETE/);assert.match(sql,/NEW.original_input/);assert.match(sql,/NEW.run_input/);assert.match(application,/if\(!claim.claimed\)return readCreativeExtractionPreview/);const complete=application.slice(application.indexOf('export async function completeSavedCreativeExtraction'));assert.ok(!complete.includes('executeManagedPrompt'));assert.match(ui,/creativeRunSettled\(result,original\)/);assert.match(ui,/不证明原操作未提交/);assert.match(ui,/manual:z.array\(creativeSavedOutputSchema.shape.candidates.element\).max\(25\)/);});
