const test=require("node:test"),assert=require("node:assert/strict");
const {preparePrompt,listPromptAssets}=require("../dist/server/ai/prompts");
const {isBlankCreationReviewValue}=require("../dist/common/creationReviewAi");
const {creationReviewAiInputSchema,adoptCreationPreparationInputSchema}=require("../dist/server/application/creationReviewAi");
const {directorControlSchema}=require("../dist/server/application/creationDirector");
const {executeManagedPrompt}=require("../dist/server/ai/runtime/managedExecution");
const {DEFAULT_MODEL_POLICY}=require("../dist/common/modelRouting");
const sessionId="74000000-0000-4000-8000-000000000001",reviewId="74000000-0000-4000-8000-000000000002",templateId="74000000-0000-4000-8000-000000000003",hash="a".repeat(64);
const field={key:"health",name:"体力",description:"人物体力",type:"number",required:true,options:[],defaultValue:null,group:"状态",order:0};
function input(){return{contract:"creation_preparation_v1",sessionId,sessionRevision:1,specificationHash:hash,stage:null,mode:"required",method:"blank",bookName:"",sourceReference:"",sourceText:"",direction:null,schemaTypes:[{key:"character",name:"人物",description:"人物设定",fields:[structuredClone(field)]}],targets:[{reviewCardId:reviewId,typeKey:"character",isNew:false,title:"",values:{},allowTitle:true,fieldKeys:["health"]}],contextCards:[{id:reviewId,typeKey:"character",title:"",values:{}}],catalog:{templateVersionId:templateId,reviewCardsHash:hash,dictionaries:[],relationSpecs:[],planningLevels:[{key:"story",label:"故事总纲",parentLevel:null,cardTypeKey:null},{key:"volume",label:"卷规划",parentLevel:"story",cardTypeKey:"volume"},{key:"chapter",label:"章节规划",parentLevel:"volume",cardTypeKey:"chapter"},{key:"scene",label:"场景规划",parentLevel:"chapter",cardTypeKey:"scene"}]}};}
function output(){return{candidates:[{reviewCardId:reviewId,typeKey:"character",isNew:false,titleSuggestion:"沈青",values:{health:10}}],directions:[],relations:[],plans:[],notes:[]};}

test('wire schema exposes the same stage boundaries as local validation',()=>{
 for(const stage of [null,'direction','project','world','characters','skeleton']){
  const i=input();i.stage=stage;
  const p=preparePrompt(stage==='direction'?'directions':'initial_content',i);
  assert.equal(p.outputSchema.properties.candidates.minItems,i.targets.length);
  assert.equal(p.outputSchema.properties.candidates.maxItems,i.targets.length);
  assert.equal(p.outputSchema.properties.plans.maxItems,stage==='skeleton'?300:0);
  assert.equal(p.outputSchema.properties.directions.maxItems,stage==='direction'?5:0);
  assert.equal(p.outputSchema.properties.relations.maxItems,stage===null?0:300);
 }
});
test("preparation preserves registered tasks without expanding six composition tasks",()=>{const assets=listPromptAssets();assert.equal(assets.length,require("../dist/server/ai/prompts").PROMPT_TASK_TYPES.length);assert.ok(assets.some(asset=>asset.taskType==="chapter_generation"));const compositionKeys=require("../dist/common/promptComposition").COMPOSITION_TASK_KEYS;assert.equal(compositionKeys.length,6);assert.equal(compositionKeys.includes("chapter_generation"),false);assert.deepEqual(preparePrompt("form_assist",input()).parseOutput(output()),output());});
test("empty names and values are valid preparation input, while numeric zero and false are protected",()=>{for(const value of [null,undefined,"","  ",[]])assert.equal(isBlankCreationReviewValue(value),true);for(const value of [0,false,"人工",[0]])assert.equal(isBlankCreationReviewValue(value),false);for(const value of [0,false,"人工"]){const i=input();i.targets[0].values.health=value;assert.throws(()=>preparePrompt("form_assist",i));}});
test("exact UUID type field whitelist and field value types cannot be expanded by model output",()=>{for(const patch of [{reviewCardId:templateId},{typeKey:"organization"},{isNew:true},{values:{health:"十"}},{values:{health:10,unregistered:"私密模型回复"}}]){const o=output();Object.assign(o.candidates[0],patch);assert.throws(()=>preparePrompt("form_assist",input()).parseOutput(o));}});
test("conditional invisible and forbidden AI fields are not permitted preparation targets",()=>{for(const patch of [{hidden:true},{aiSuggestible:false},{visibleWhen:{fieldKey:"enabled",operator:"equals",value:true}}]){const i=input();Object.assign(i.schemaTypes[0].fields[0],patch);assert.throws(()=>preparePrompt("form_assist",i));}const i=input();i.schemaTypes[0].fields[0].visibleWhen={fieldKey:"enabled",operator:"equals",value:true};i.targets[0].values.enabled=true;assert.doesNotThrow(()=>preparePrompt("form_assist",i));});
test("candidate failure gives Chinese actual content type and field without raw model text or chapter labels",()=>{const o=output();o.candidates[0].values.health="provider-private-response";assert.throws(()=>preparePrompt("form_assist",input()).parseOutput(o),error=>{assert.match(error.message,/人物.*体力/);assert.doesNotMatch(error.message,/provider-private-response|章节变化|health/);assert.ok(error.issues[`${reviewId}.health`]);return true;});});
test("source APIs are strict and never accept execution overrides or duplicated adoption selections",()=>{const valid={expectedSessionRevision:1,requestKey:"prepare-contract-1",mode:"required",reviewCardId:reviewId};assert.ok(creationReviewAiInputSchema.safeParse(valid).success);assert.equal(creationReviewAiInputSchema.safeParse({...valid,environment:{}}).success,false);const adopt={expectedSessionRevision:1,requestKey:"adopt-contract-1",selections:[{reviewCardId:reviewId,title:true,fieldKeys:["health","health"]}],relationIds:[],planIds:[]};assert.equal(adoptCreationPreparationInputSchema.safeParse(adopt).success,false);assert.equal(directorControlSchema.safeParse({expectedRevision:1,mode:"manual"}).success,false);assert.ok(directorControlSchema.safeParse({expectedRevision:1,idempotencyKey:"control-contract-1",mode:"manual"}).success);});
test("dictionary output is restricted to precise allowed branch and leaf nodes, with actual selection bounds",()=>{const root="74000000-0000-4000-8000-000000000004",leaf="74000000-0000-4000-8000-000000000005",other="74000000-0000-4000-8000-000000000006",dictionaryId="74000000-0000-4000-8000-000000000007";const i=input();i.catalog.dictionaries=[{id:dictionaryId,label:"境界",nodes:[{id:root,parentId:null,label:"修行",path:["修行"]},{id:leaf,parentId:root,label:"筑基",path:["修行","筑基"]},{id:other,parentId:null,label:"旁支",path:["旁支"]}]}];Object.assign(i.schemaTypes[0].fields[0],{type:"multi_select",options:[{value:leaf,label:"筑基"},{value:root,label:"修行"},{value:other,label:"旁支"}],optionSource:{kind:"dictionary_tree",dictionaryId,rule:{mode:"multiple",rootNodeId:root,depthMode:"descendants",relativeDepth:null,leafOnly:true,allowParentSelection:false,showFullPath:true,allowInlineCreate:false,aiSuggestible:true,minSelections:1,maxSelections:1}}});const prompt=preparePrompt("form_assist",i),o=output();o.candidates[0].values.health=[leaf];assert.doesNotThrow(()=>prompt.parseOutput(o));for(const value of [[root],[other],[leaf,leaf],[]]){o.candidates[0].values.health=value;assert.throws(()=>prompt.parseOutput(o));}});
test("registered legacy direction and initial-content schemas remain independent from governed review preparation",()=>{const direction={id:"方向甲",title:"守脉者",premise:"少年维护祖脉",protagonist:"守山少年",centralConflict:"飞升会失忆",readerPromise:"发现隐藏真相",styleKeywords:["仙侠"]};const legacy=preparePrompt("initial_content",{direction,sourceText:"",schemaTypes:input().schemaTypes});assert.deepEqual(legacy.parseOutput({cards:[{typeKey:"character",title:"沈青",values:{health:10}}]}).cards[0].title,"沈青");assert.equal(legacy.outputSchema.properties.candidates,undefined);});
test("received invalid model reply retains real response and token evidence, without technical content fallback",async()=>{let requests=0;const i=input(),p=preparePrompt("form_assist",i),route={primary:{provider:"openai-compatible",endpoint:"http://127.0.0.1:9999/v1",model:"contract-fixture",credentialId:null},fallbacks:[],policy:{...DEFAULT_MODEL_POLICY,maxTotalTokens:200000},sourceLayers:[]};const bad=output();bad.candidates[0].values.health="invalid-private-value";await assert.rejects(()=>executeManagedPrompt("form_assist",p,{routeResolver:async()=>route,snapshotWriter:async()=>({id:templateId,snapshotHash:hash,taskType:"form_assist",route}),fetcher:async()=>{requests++;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(bad)}}],usage:{prompt_tokens:20,completion_tokens:30,total_tokens:50}}),{status:200,headers:{"Content-Type":"application/json"}});}}),error=>{assert.equal(error.executionSnapshot.attempts[0].requestSent,true);assert.equal(error.executionSnapshot.attempts[0].responseReceived,true);assert.equal(error.executionSnapshot.knownTokens,50);assert.match(error.message,/人物.*体力/);return true;});assert.equal(requests,1);});
test("invalid JSON is a received reply with known provider usage rather than a fabricated unknown send",async()=>{const p=preparePrompt("form_assist",input()),route={primary:{provider:"openai-compatible",endpoint:"http://127.0.0.1:9999/v1",model:"contract-fixture",credentialId:null},fallbacks:[],policy:{...DEFAULT_MODEL_POLICY,maxTotalTokens:200000},sourceLayers:[]};await assert.rejects(()=>executeManagedPrompt("form_assist",p,{routeResolver:async()=>route,snapshotWriter:async()=>({id:templateId,snapshotHash:hash,taskType:"form_assist",route}),fetcher:async()=>new Response(JSON.stringify({choices:[{message:{content:"not-json-private-text"}}],usage:{prompt_tokens:8,completion_tokens:12,total_tokens:20}}),{status:200,headers:{"Content-Type":"application/json"}})}),error=>{assert.equal(error.executionSnapshot.attempts[0].responseReceived,true);assert.equal(error.executionSnapshot.knownTokens,20);assert.doesNotMatch(error.message,/private-text/);return true;});});
test("acknowledged adoption-only rollback preserves saved model semantics, while unknown commit or rollback stays unknown",async()=>{
 const {directorTransaction}=require("../dist/server/database/creationDirector/transaction"),{withBookCreationProductionPool}=require("../dist/server/database/bookCreationStore");
 for(const scenario of ["rollback_ack","commit_unknown","rollback_unknown"]){const queries=[],client={query:async sql=>{queries.push(sql);if(scenario==="commit_unknown"&&sql==="COMMIT"||scenario==="rollback_unknown"&&sql==="ROLLBACK")throw new Error("SQL-private-failure");return{rows:[]};},release(){}};const pool={connect:async()=>client};await assert.rejects(()=>withBookCreationProductionPool(pool,()=>directorTransaction(sessionId,async()=>{if(scenario!=="commit_unknown")throw new Error("SQL-private-failure");return{};},false,"adopt-contract-key",true)),error=>{assert.equal(error.failure.mutationOutcome,scenario==="rollback_ack"?"not_written":"unknown");assert.equal(error.failure.modelRequestState,"completed");assert.match(error.recovery.failedStep,/采用勾选候选/);assert.match(error.recovery.savedResult,/已经保存/);assert.doesNotMatch(error.message,/SQL-private/);return true;});assert.ok(queries.includes("ROLLBACK"));}
});
test("preparation rollback proof is not applied to external model output saving transactions",async()=>{const {directorTransaction}=require("../dist/server/database/creationDirector/transaction"),{withBookCreationProductionPool}=require("../dist/server/database/bookCreationStore");const original=new Error("infrastructure-output-failure"),client={query:async()=>({rows:[]}),release(){}},pool={connect:async()=>client};await assert.rejects(()=>withBookCreationProductionPool(pool,()=>directorTransaction(sessionId,async()=>{throw original;})),error=>error===original);await assert.rejects(()=>withBookCreationProductionPool(pool,()=>directorTransaction(sessionId,async()=>{throw new Error("SQL-private-failure");},true)),error=>error.failure.mutationOutcome==="not_written"&&error.failure.modelRequestState==="not_sent"&&!error.message.includes("SQL-private"));});
