const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),express=require('express');
const production=require('../dist/server/database/bookCreationProduction'),director=require('../dist/server/application/creationDirector'),models=require('../dist/server/database/modelManagement');
const {mountCreationDirector}=require('../dist/server/http/creationDirector');
const {creationFixture,seedCreationTemplate}=require('./creationProduction/postgresFixture.cjs');

test('governed creation director preserves pending candidates, original receipts, manual drafts and late-result fencing',
 {skip:process.env.AI_NOVEL_NEW_DESIGN_DEV_RUNTIME!=='1',timeout:180000},async t=>{
 const fixture=await creationFixture(t),{db,scopedPool}=fixture,config=await seedCreationTemplate(db),scope=action=>production.withBookCreationProductionPool(scopedPool,action);
 // Only empty fixture facts, no author's template/model copied or replaced.
 const payload=structuredClone(config.payload),systemSpace='00000000-0000-4000-8000-000000000001';
 for(const [key,name] of [['plotline','故事线'],['world_rule','世界规则']]){
  const type={sourceId:randomUUID(),sourceVersionId:randomUUID(),key,name,description:'导演隔离规格',capabilities:[],sortOrder:0,
   fields:[{key:'name',name:'必填内容',type:'short_text',description:'',required:true,defaultValue:null,options:[],group:'准备',order:0},{key:'notes',name:'人工补充',type:'short_text',description:'',required:false,defaultValue:null,options:[],group:'准备',order:1}]};
  payload.cardTypes.push(type);await db.query("INSERT INTO new_design.card_types(id,space_id,type_key,name,status) VALUES($1,$2,$3,$4,'published')",[type.sourceId,systemSpace,key,name]);
  await db.query('INSERT INTO new_design.card_type_versions(id,card_type_id,version,fields) VALUES($1,$2,1,$3::jsonb)',[type.sourceVersionId,type.sourceId,JSON.stringify(type.fields)]);
  await db.query('UPDATE new_design.card_types SET current_version_id=$2 WHERE id=$1',[type.sourceId,type.sourceVersionId]);
 }
 const versionId=randomUUID();await db.query('INSERT INTO new_design.template_group_versions(id,template_id,version,payload) VALUES($1,$2,2,$3::jsonb)',[versionId,config.template,JSON.stringify(payload)]);await db.query('UPDATE new_design.template_groups SET current_version_id=$2 WHERE id=$1',[config.template,versionId]);
 await models.saveManagedModelRoute({scope:'system_default',taskType:null,expectedConfigId:null,expectedRevision:null,idempotencyKey:randomUUID(),primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'director-fixture-stub-not-real-model',credentialId:null},fallbacks:[],policy:{maxOutputTokens:8000,maxTotalTokens:1000000,timeoutMs:30000,maxRetries:0,retryDelayMs:0}},{client:db});
 let calls=0,failWorld=false,invalidWorld=false,holdCharacters=false,releaseCharacters,enterCharacters;
 const fetcher=async(_url,options)=>{
  calls++;const input=JSON.parse(JSON.parse(options.body).messages.at(-1).content).taskData;assert.equal(input.contract,'creation_preparation_v1');
  if(input.stage==='world'&&failWorld){failWorld=false;throw new Error('secret-runtime-detail');}
  if(input.stage==='characters'&&holdCharacters){enterCharacters();await new Promise(resolve=>{releaseCharacters=resolve;});holdCharacters=false;}
  const candidates=input.targets.map(target=>({reviewCardId:target.reviewCardId,typeKey:target.typeKey,isNew:target.isNew,titleSuggestion:target.allowTitle?`${input.schemaTypes.find(type=>type.key===target.typeKey).name}准备`:null,values:Object.fromEntries(target.fieldKeys.map(key=>[key,key==='name'?'必填已准备':'AI 可选内容']))}));
  if(input.stage==='world'&&invalidWorld){invalidWorld=false;candidates[0].values.name=123;}
  const plans=[];if(input.stage==='skeleton'){let parentDraftId=null;for(const level of input.catalog.planningLevels){const id=randomUUID(),candidate=level.cardTypeKey?candidates.find(candidate=>candidate.typeKey===level.cardTypeKey):null;
   plans.push({id,parentDraftId,reviewCardId:candidate?.reviewCardId??null,level:level.key,title:`${level.label}准备`,sortOrder:0,content:{goal:'守阵并寻找旧案真相',storyTime:'',mustHappen:[],mustPreserve:[],forbiddenBoundaries:[],expectedChanges:[],characterArc:'',notes:''},executionMode:'ai_assisted',references:[],decision:'pending'});parentDraftId=id;}}
   return new Response(JSON.stringify({message:{content:JSON.stringify({candidates,directions:input.stage==='direction'?[{id:'fixture-first',title:'AI 推荐开书',premise:'守阵少年寻找旧案',protagonist:'守阵少年',centralConflict:'救人与守阵的代价',readerPromise:'仙侠探索与成长',styleKeywords:['仙侠','悬疑']}]:[],relations:[],plans,notes:[]})},prompt_eval_count:100,eval_count:50}),{status:200,headers:{'content-type':'application/json'}});
 };
 const app=express(),router=express.Router();app.use(express.json());app.use((_req,_res,next)=>scope(async()=>next()));
 // Real HTTP/store/executor; only provider transport is a declared stub.
 mountCreationDirector(router,undefined,{executeCreationDirector:(id,input)=>director.executeCreationDirector(id,input,undefined,{fetcher})});app.use('/api',router);app.use((error,_req,res,_next)=>res.status(error.status||500).json({success:false,error:error.message,issues:error.issues,recovery:error.recovery}));
 const server=await new Promise(resolve=>{const instance=app.listen(0,'127.0.0.1',()=>resolve(instance));});t.after(async()=>{releaseCharacters?.();await new Promise(resolve=>server.close(resolve));});
 const base=`http://127.0.0.1:${server.address().port}/api`,api=async(path,input,method='POST')=>{const response=await fetch(base+path,{method,headers:{'content-type':'application/json'},...(input===undefined?{}:{body:JSON.stringify(input)})});return{status:response.status,...await response.json()};},path=id=>`/book-creation/sessions/${id}`,read=id=>api(path(id),undefined,'GET');
 const create=async()=>{const requestKey=randomUUID(),result=await api('/book-creation/sessions',{method:'blank',templateVersionId:versionId,bookName:'',description:'',sourceReference:'',inputPayload:{creationDirector:{mode:'automatic',cursor:5}},requestKey});assert.equal(result.status,201,JSON.stringify(result));assert.equal(result.data.inputPayload.creationDirector,undefined);assert.equal((await api(`/book-creation/sessions/by-request/${requestKey}`,undefined,'GET')).data.id,result.data.id);return result.data;};
 const control=async(session,mode,extra={})=>{const idempotencyKey=randomUUID(),result=await api(path(session.id)+'/director',{expectedRevision:session.revision,idempotencyKey,mode,...extra},'PATCH');assert.equal(result.status,200,JSON.stringify(result));assert.equal((await api(path(session.id)+`/director/commands/by-key/${idempotencyKey}`,undefined,'GET')).data.session.revision,result.data.revision);return result.data;};
 const prepare=(session,idempotencyKey=randomUUID())=>api(path(session.id)+'/director/prepare',{expectedRevision:session.revision,idempotencyKey});
 let automatic=await control(await create(),'automatic');const autoKey=randomUUID(),autoRevision=automatic.revision;
 let result=await prepare(automatic,autoKey);assert.equal(result.status,200,JSON.stringify(result));let prepared=result.data;automatic=prepared.session;
 assert.equal(prepared.status,'review',JSON.stringify(prepared));assert.equal(automatic.inputPayload.creationDirector.cursor,5);assert.equal(automatic.reviewCards.length,0,'AI never adopts pending output');assert.equal(calls,5);assert.equal(prepared.receipts.length,5);assert.equal(prepared.receipts.at(-1).output.candidates.length,7);
 assert.equal((await api(path(automatic.id)+'/director/prepare',{expectedRevision:autoRevision,idempotencyKey:autoKey})).data.receipts.length,5);assert.equal(calls,5);assert.equal((await api(path(automatic.id)+'/director/prepare',{expectedRevision:autoRevision+1,idempotencyKey:autoKey})).status,409);
 let stepwise=await control(await create(),'stepwise');result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data.session;assert.equal(stepwise.inputPayload.creationDirector.cursor,1);assert.equal(stepwise.reviewCards.length,0);
 const directionBatch=result.data.receipts.at(-1);result=await api(`/book-creation/creation-preparation-batches/${directionBatch.batchId}/adopt`,{expectedSessionRevision:stepwise.revision,requestKey:randomUUID(),selections:[],relationIds:[],planIds:[],directionId:'fixture-first'});assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data.session;assert.equal(stepwise.selectedDirectionId,'fixture-first');
 const manualCard={id:randomUUID(),typeKey:'world_rule',title:'世界准备',values:{name:'',notes:'作者填写，必须保留'},sourceKind:'manual',sourceId:null,sourceVersionId:null,originalTitle:'世界准备',originalValues:{name:'',notes:'作者填写，必须保留'}},reviewKey=randomUUID();
 result=await api(path(stepwise.id)+'/review',{bookName:'作者确定的书名',description:'',reviewCards:[manualCard],revision:stepwise.revision,requestKey:reviewKey},'PATCH');assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data;assert.equal((await api(path(stepwise.id)+`/write-receipts?requestKey=${reviewKey}`,undefined,'GET')).data.session.revision,stepwise.revision);
 const manualBaseline=structuredClone(stepwise.reviewCards);
 assert.equal((await api(path(stepwise.id)+'/complete',{expectedRevision:stepwise.revision,requestKey:randomUUID()})).status,422);
 result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data.session;assert.equal(stepwise.inputPayload.creationDirector.cursor,2);
 failWorld=true;const failedKey=randomUUID(),failedRevision=stepwise.revision;result=await prepare(stepwise,failedKey);assert.equal(result.status,200,JSON.stringify(result));assert.equal(result.data.status,'failed');stepwise=result.data.session;assert.equal(stepwise.status,'failed');assert.equal(stepwise.lastFailedStage,'director_world');assert.equal(stepwise.reviewCards.length,1);assert.doesNotMatch(stepwise.errorMessage,/secret-runtime-detail/);
 const modelFailure=result.data.receipts.at(-1);assert.equal(modelFailure.modelResultSaved,false);assert.equal(modelFailure.failure.modelRequestState,'sent_unknown');assert.match(modelFailure.failure.failedStep,/[\u4e00-\u9fff]/);assert.equal(modelFailure.failure.recovery.source.route,`/new-design/books/new?session=${stepwise.id}`);assert.match(modelFailure.failure.recovery.savedResult,/尚未确认/);assert.deepEqual(stepwise.reviewCards,manualBaseline);
 const afterFailure=calls;assert.equal((await api(path(stepwise.id)+'/director/prepare',{expectedRevision:failedRevision,idempotencyKey:failedKey})).data.status,'failed');assert.equal(calls,afterFailure);
 invalidWorld=true;result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));assert.equal(result.data.status,'failed');stepwise=result.data.session;assert.match(stepwise.errorMessage,/世界规则.*必填内容/);assert.deepEqual(stepwise.reviewCards,manualBaseline);assert.ok(result.data.receipts.at(-1).failure.issues[`${manualCard.id}.name`]);
 result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));assert.equal(result.data.status,'review');stepwise=result.data.session;assert.deepEqual(stepwise.reviewCards,manualBaseline,'saved candidates remain unapplied');
 holdCharacters=true;const entered=new Promise(resolve=>{enterCharacters=resolve;}),pending=prepare(stepwise);await Promise.race([entered,pending.then(value=>{throw new Error(`Characters provider never entered: ${JSON.stringify(value)}`);})]);
 const running=(await read(stepwise.id)).data;assert.equal(running.status,'generating');const activeBatch=running.inputPayload.creationDirector.activeBatchId;
 assert.equal((await api(path(stepwise.id)+'/review',{bookName:running.bookName,description:'',reviewCards:running.reviewCards,revision:running.revision,requestKey:randomUUID()},'PATCH')).status,409);
 stepwise=await control(running,'manual',{takeOver:true});releaseCharacters();const late=await pending;assert.equal(late.status,503,JSON.stringify(late));assert.equal(late.recovery.failedStep,'核对模型结果保存');assert.equal(late.recovery.mutationOutcome,'unknown');assert.equal(late.recovery.sourceRoute,`/new-design/books/new?session=${stepwise.id}`);assert.match(late.recovery.savedResult,/模型已返回/);
 const afterLate=(await read(stepwise.id)).data;assert.equal(afterLate.revision,stepwise.revision);assert.equal(afterLate.reviewCards.some(card=>card.typeKey==='character'),false);const ended=await api(`/book-creation/creation-preparation-batches/${activeBatch}`,undefined,'GET');assert.equal(ended.data.status,'ended_unknown');assert.equal(ended.data.canAdoptSavedResult,false);
 stepwise=await control(afterLate,'stepwise');result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data.session;stepwise=await control(stepwise,'automatic');result=await prepare(stepwise);assert.equal(result.status,200,JSON.stringify(result));prepared=result.data;stepwise=prepared.session;assert.equal(stepwise.inputPayload.creationDirector.cursor,5);assert.equal(stepwise.bookName,'作者确定的书名');
 const final=prepared.receipts.at(-1),adoptKey=randomUUID(),adoption={expectedSessionRevision:stepwise.revision,requestKey:adoptKey,selections:final.output.candidates.map(candidate=>({reviewCardId:candidate.reviewCardId,title:candidate.titleSuggestion!==null,fieldKeys:Object.keys(candidate.values)})),relationIds:[],planIds:[]};
 result=await api(`/book-creation/creation-preparation-batches/${final.batchId}/adopt`,adoption);assert.equal(result.status,200,JSON.stringify(result));stepwise=result.data.session;assert.equal((await api(`/book-creation/creation-preparation-batches/${final.batchId}/adoptions/by-key/${adoptKey}`,undefined,'GET')).data.session.revision,stepwise.revision);
 const world=stepwise.reviewCards.find(card=>card.typeKey==='world_rule');assert.equal(world.values.notes,'作者填写，必须保留');assert.ok(world.values.name);assert.ok(world.aiFieldBatchIds.name);assert.equal(world.aiFieldBatchIds.notes,undefined);
 const completeKey=randomUUID(),completeInput={expectedRevision:stepwise.revision,requestKey:completeKey};result=await api(path(stepwise.id)+'/complete',completeInput);assert.equal(result.status,200,JSON.stringify(result));const completed=result.data;assert.equal(completed.status,'completed');assert.equal((await api(path(stepwise.id)+'/complete',completeInput)).data.bookId,completed.bookId);assert.equal((await api(path(stepwise.id)+`/write-receipts?requestKey=${completeKey}`,undefined,'GET')).data.session.bookId,completed.bookId);assert.equal((await read(stepwise.id)).data.bookId,completed.bookId);
 const savedWorld=(await db.query("SELECT card.id,card.values FROM new_design.cards card JOIN new_design.books book ON book.space_id=card.space_id JOIN new_design.card_types type ON type.id=card.card_type_id WHERE book.id=$1 AND type.type_key='world_rule'",[completed.bookId])).rows[0];assert.equal(savedWorld.values.notes,'作者填写，必须保留');assert.equal((await db.query("SELECT source_kind FROM new_design.card_field_origins WHERE card_id=$1 AND field_key='notes'",[savedWorld.id])).rows[0].source_kind,'user');
 await fixture.authorUnchanged();console.log('director_fixture_retained',fixture.schema,'governed_stub_calls',calls);
});
