const test=require("node:test");
const assert=require("node:assert/strict");
const {randomUUID}=require("node:crypto");
const express=require("express");
const enabled=process.env.AI_NOVEL_NEW_DESIGN_DEV_RUNTIME==="1";
const runtime=require("../dist/server/database/runtime");
const store=require("../dist/server/database/store");
const templates=require("../dist/server/database/templateStore");
const composition=require("../dist/server/database/compositionStore");
const trees=require("../dist/server/database/treeResources");
const material=require("../dist/server/database/materialManagement");
const {businessFormAiRouter}=require("../dist/server/http/formAssist");

test("real PostgreSQL/API form AI freezes scope, protects drafts and saves one official version",{skip:!enabled,timeout:60000},async t=>{
 const pool=await runtime.getNewDesignPool();let verifiedBookId=null,apiServer=null;
 t.after(async()=>{if(apiServer)await new Promise(resolve=>apiServer.close(resolve));if(verifiedBookId)await pool.query("UPDATE new_design.books SET status='archived' WHERE id=$1",[verifiedBookId]);await pool.end();});
 const registered=(await pool.query("SELECT id FROM new_design.schema_migrations ORDER BY id")).rows.map(row=>row.id);
 for(const number of [46,47,48,49,50])assert.ok(registered.some(id=>id.startsWith(String(number).padStart(3,"0")+"_")));
 const extensions=(await pool.query("SELECT extname,extversion FROM pg_extension WHERE extname=ANY($1::text[])",[["age","vector","pg_trgm"]])).rows;
 assert.equal(extensions.length,3);console.log("extensions",extensions);
 const template=(await pool.query("SELECT id FROM new_design.template_group_versions ORDER BY created_at LIMIT 1")).rows[0];assert.ok(template);
 const token=randomUUID().replaceAll("-","").slice(0,12),book=await templates.createBook({key:`ai_verify_${token}`,name:`表单AI验证-${token}`,description:"自动化运行验收专用，非作者正式作品",templateVersionId:template.id});
 verifiedBookId=book.id;
 const root=randomUUID(),branch=randomUUID(),allowed=randomUUID(),outside=randomUUID(),archived=randomUUID();
 const dictionary=await composition.saveDictionary({key:`verify_${token}`,name:"验证人物定位",description:"分支范围验证",scope:"book",ownerSpaceId:book.spaceId,items:[{id:root,label:"世界",parentId:null,sortOrder:10,status:"active"},{id:branch,label:"本宗",parentId:root,sortOrder:20,status:"active"},{id:allowed,label:"内门",parentId:branch,sortOrder:30,status:"active"},{id:outside,label:"外宗",parentId:root,sortOrder:40,status:"active"},{id:archived,label:"旧制",parentId:branch,sortOrder:50,status:"archived"}]});
 const rule={mode:"single",rootNodeId:branch,depthMode:"direct_children",relativeDepth:null,leafOnly:true,allowParentSelection:false,showFullPath:true,allowInlineCreate:true,aiSuggestible:true,minSelections:0,maxSelections:1};
 const field=(key,name,type,extra={})=>({key,name,type,description:"",required:false,defaultValue:null,options:[],group:"验证",order:1,aiSuggestible:true,...extra});
 let type=await store.createCardType({key:`verify_${token}`,name:"通用表单验证",description:"测试规格",semanticCapabilities:[],fields:[field("name","人物姓名","short_text",{required:true}),field("age","年龄","number"),field("role","宗门定位","select",{optionSource:{kind:"dictionary_tree",dictionaryId:dictionary.id,rule}})]},book.spaceId);
 type=await store.publishCardType(type.id,type.revision);
 const dimension=await trees.saveTagDimension({name:`验证职责-${token}`,description:"",scope:"book",ownerSpaceId:book.spaceId});
 const tag=await material.createMaterialTag({bookId:book.id},{key:`verify_${token}`,name:"成长",aliases:[],metadata:{},dimensionId:dimension.id,parentId:null,sortOrder:10,idempotencyKey:`tag-${token}`});
 await trees.saveCardTypeTagBinding({cardTypeId:type.id,dimensionId:dimension.id,rule:{...rule,rootNodeId:null,depthMode:"whole_tree"},required:false,displayArea:"sidebar",includeInFilters:true,includeInAiContext:true});
 const card=await store.createCard({cardTypeId:type.id,title:"验证人物",spaceId:book.spaceId,values:{name:"正式原稿"}});
 let calls=0;
 const ai={assistForm:async input=>{calls++;if(input.instruction==="越界")return {role:outside};if(input.instruction==="新增")return {__new_role:"外门"};if(input.instruction==="推荐")return {[`__tags_${dimension.key}`]:[tag.id]};if(input.instruction==="矛盾")return {__observations:"暂未发现矛盾，关联证据不足。"};return {age:18};}};
 const app=express();app.use(express.json());app.use(businessFormAiRouter(ai));app.post("/cards/:id/save",(req,res,next)=>void store.updateCard(req.params.id,req.body).then(data=>res.json({success:true,data})).catch(next));app.use((error,req,res,next)=>res.status(error.status??500).json({success:false,error:error.message}));
 const server=app.listen(0,"127.0.0.1");apiServer=server;await new Promise(resolve=>server.once("listening",resolve));
 const base=`http://127.0.0.1:${server.address().port}`;
 const post=async(path,body,status=200)=>{const response=await fetch(base+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data.data;};
 const target={bookId:book.id,cardTypeId:type.id,cardId:card.id,typeVersionId:type.currentVersionId,cardRevision:card.revision,formVersionId:null,title:card.title},path=`/books/${book.id}/form-ai`;
 const draft={name:"未保存的人工姓名",age:null,role:allowed};
 const request={target,action:"fill_empty",instruction:"填空",values:draft,tagIds:[],fieldKeys:["age"],idempotencyKey:`generate-${token}`};
 const run=await post(path,request);assert.equal(run.status,"review");assert.equal(calls,1);
 assert.deepEqual((await post(path,request)).id,run.id);assert.equal(calls,1);
 await post(path,{...request,values:{...draft,age:20}},409);
 assert.equal((await store.getCard(card.id)).revision,1);assert.equal((await store.listCardVersions(card.id)).length,1);
 const adopt={candidateId:run.candidates[0].id,fieldKeys:["age"],treeKeys:[],values:{...draft,name:"生成后继续改的人名"},tagIds:[],idempotencyKey:`adopt-${token}`};
 await post(`${path}/${run.id}/adopt`,{...adopt,values:{...adopt.values,age:22}},409);
 const applied=await post(`${path}/${run.id}/adopt`,adopt);assert.equal(applied.values.name,"生成后继续改的人名");assert.equal(applied.values.age,18);
 assert.equal((await post(`${path}/${run.id}/adopt`,adopt)).decisionId,applied.decisionId);
 await post(`${path}/${run.id}/discard`,{idempotencyKey:adopt.idempotencyKey},409);
 const recommended=await post(path,{...request,action:"recommend",instruction:"推荐",values:applied.values,fieldKeys:[],idempotencyKey:`recommend-${token}`});assert.equal(recommended.status,"review");
 const tags=await post(`${path}/${recommended.id}/adopt`,{candidateId:recommended.candidates[0].id,fieldKeys:[],treeKeys:[dimension.key],values:applied.values,tagIds:[],idempotencyKey:`adopt-tags-${token}`});assert.deepEqual(tags.tagIds,[tag.id]);
 const invalid=await post(path,{...request,action:"recommend",instruction:"越界",fieldKeys:[],idempotencyKey:`outside-${token}`});assert.equal(invalid.status,"failed");
 const observations=await post(path,{...request,action:"check",instruction:"矛盾",fieldKeys:[],idempotencyKey:`check-${token}`});assert.equal(observations.candidates.length,0);assert.equal(observations.observations.length,1);
 const save={title:card.title,values:tags.values,revision:1,formVersionId:null,formResolutionKind:"type_schema",aiDraftDecisionIds:[applied.decisionId,tags.decisionId],tagIds:tags.tagIds};
 const saved=await post(`/cards/${card.id}/save`,save);assert.equal(saved.revision,2);assert.equal(saved.values.name,"生成后继续改的人名");assert.equal((await store.listCardVersions(card.id)).length,2);
 assert.equal(Number((await pool.query("SELECT count(*) value FROM new_design.card_version_ai_draft_sources source JOIN new_design.card_versions version ON version.id=source.card_version_id WHERE version.card_id=$1",[card.id])).rows[0].value),2);
 assert.equal((await pool.query("SELECT status FROM new_design.material_tag_memberships WHERE card_id=$1 AND tag_id=$2",[card.id,tag.id])).rows[0].status,"active");
 await post(`/cards/${card.id}/save`,{...save,revision:2},409);
 await post(`${path}/${run.id}/adopt`,{...adopt,idempotencyKey:`stale-${token}`},409);
 const nextTarget={...target,cardRevision:2};
 const options=await post(path,{...request,target:nextTarget,action:"recommend",instruction:"新增",values:saved.values,tagIds:[tag.id],fieldKeys:[],idempotencyKey:`new-option-${token}`});assert.equal(options.newNodes.length,1);
 const confirmation={suggestionId:options.newNodes[0].id,name:"外门",idempotencyKey:`confirm-option-${token}`};
 const created=await post(`${path}/${options.id}/new-node`,confirmation);assert.equal(created.requiresBinding,false);
 assert.equal((await post(`${path}/${options.id}/new-node`,confirmation)).nodeId,created.nodeId);
 assert.equal((await composition.getDictionary(dictionary.id)).items.filter(item=>item.label==="外门").length,1);
 const alternatives=await post(path,{...request,target:nextTarget,action:"alternatives",instruction:"三个方案",values:saved.values,tagIds:[tag.id],fieldKeys:["age"],idempotencyKey:`alternatives-${token}`});assert.equal(alternatives.candidates.length,3);
 await post(`${path}/${alternatives.id}/discard`,{idempotencyKey:`discard-${token}`});
 console.log("verified_book",book.id,"registered_migrations",registered.length,"model_stub_calls",calls);
});
