const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),ts=require("typescript");
const root=path.join(__dirname,"../src"),read=file=>fs.readFileSync(path.join(root,file),"utf8");
function load(file,bindings={}){const exports={};new Function("exports","require",ts.transpileModule(read(file),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,name=>bindings[name]);return exports;}
const policy=load("common/multiviewAuthor/index.ts"),selection=load("client/multiview/selection.ts",{"../../common/contracts":{BOOK_VIEW_KEYS:["characters","events","rules"]}});
test("actual multiview mounts unified author editor and retains specialist workspaces",()=>{const page=read("client/BookViewsPage.tsx"),editor=read("client/businessForms/BusinessFormWorkspace.tsx");assert.match(page,/<MultiviewAuthorPanel/);assert.match(page,/<BusinessFormWorkspace key=\{book\.id\} book=\{book\}/);assert.match(page,/embedded initialCardId=\{selected\.id\}/);assert.doesNotMatch(page,/SharedInspector|newDesignApi\.updateCard/);for(const component of ["ChapterPanel","StateWorkspace","QualityWorkspace","ComparisonWorkspace"])assert.match(page,new RegExp(`<${component}`));assert.match(editor,/workspace\.bookId!==book\.id\|\|workspace\.spaceId!==book\.spaceId/);assert.match(editor,/item\.id===requestedCardId&&item\.status==="active"/);assert.match(editor,/initialCardId\?\?new URLSearchParams\(location\.search\)\.get\("selected"\)/);assert.match(editor,/getAuthorMaterialWriteReceipt\(book\.id,requestKey\)/);assert.match(editor,/原请求回执未找到，不能断言未执行/);assert.match(editor,/requestKey&&notWritten&&receiptChecked&&<button/);assert.match(editor,/if\(committed\)/);assert.match(editor,/原请求保存成功/);assert.doesNotMatch(editor,/newDesignApi\.(updateCard|createCard)\(/);});
test("author draft storage preserves exact original key and rejects cross-book or malformed data",()=>{const recovery=load("client/businessForms/draftRecovery.ts"),book="130ad21c-fc6e-486a-bc20-383eb019d05b",card="230ad21c-fc6e-486a-bc20-383eb019d05b",key="330ad21c-fc6e-486a-bc20-383eb019d05b",draft={version:1,bookId:book,cardId:card,cardTypeId:key,revision:2,title:"人工",values:{active:false,count:0},localValues:{},tagIds:[],aiDecisionIds:[],unknownWrite:true,requestKey:key,notWritten:false,creating:false};assert.equal(recovery.parseBusinessDraft(JSON.stringify(draft),book,card).requestKey,key);assert.equal(recovery.parseBusinessDraft(JSON.stringify(draft),key,card),null);assert.equal(recovery.parseBusinessDraft(JSON.stringify({...draft,requestKey:"wrong"}),book,card),null);assert.equal(recovery.parseBusinessDraft(JSON.stringify({...draft,values:{constructor:{secret:"bad"}}}),book,card),null);});
const ids=["130ad21c-fc6e-486a-bc20-383eb019d05b","230ad21c-fc6e-486a-bc20-383eb019d05b","330ad21c-fc6e-486a-bc20-383eb019d05b"],nodes=ids.map((id,index)=>({id,parentId:index?ids[index-1]:null,label:["宗门","仙门","青云宗"][index],path:["宗门","仙门","青云宗"].slice(0,index+1),sortOrder:index}));
const cards=[{id:"a",cardTypeId:"type",typeVersionId:"v1",typeKey:"character",title:"林青",cardTypeName:"人物",values:{clan:ids[0]}},{id:"b",cardTypeId:"type",typeVersionId:"v1",typeKey:"character",title:"白云",cardTypeName:"人物",values:{clan:ids[2]}},{id:"c",cardTypeId:"type",typeVersionId:"v2",typeKey:"character",title:"旧规格",cardTypeName:"人物",values:{clan:ids[2]}}],workspace={bookId:ids[0],spaceId:ids[1],cards,facets:[{id:"dictionary",kind:"dictionary",label:"宗门",cardTypeId:"type",typeVersionId:"v1",fieldKey:"clan",nodes,unavailableReason:null},{id:"tag",kind:"tag",label:"身份",nodes,unavailableReason:null}],assignments:[{cardId:"b",nodeIds:[ids[1],ids[2]]}]};
const state=(mode)=>({...selection.emptyMultiviewSelection(),conditions:[{facetId:"dictionary",nodeIds:[ids[0]],mode}]});
test("node, whole branch, and descendant-only filtering use exact formal versions",()=>{assert.deepEqual(policy.filterMultiviewCards(workspace,state("exact"),["character"]).map(c=>c.id),["a"]);assert.deepEqual(policy.filterMultiviewCards(workspace,state("subtree"),["character"]).map(c=>c.id),["a","b"]);assert.deepEqual(policy.filterMultiviewCards(workspace,state("descendants"),["character"]).map(c=>c.id),["b"]);});
test("conditions intersect across dimensions and retained empty mode does not filter",()=>{const input={...state("subtree"),conditions:[...state("subtree").conditions,{facetId:"tag",nodeIds:[ids[1]],mode:"subtree"}]};assert.deepEqual(policy.filterMultiviewCards(workspace,input,["character"]).map(c=>c.id),["b"]);assert.equal(policy.filterMultiviewCards(workspace,{...input,search:"林"},["character"]).length,0);assert.equal(policy.filterMultiviewCards(workspace,{...selection.emptyMultiviewSelection(),conditions:[{facetId:"unknown",nodeIds:[],mode:"descendants"}]},[]).length,3);});
test("multivalue grouping projects one canonical card into multiple groups",()=>{const groups=policy.groupMultiviewCards(workspace,cards,"tag");assert.equal(groups.filter(g=>g.cards.some(c=>c.id==="b")).length,2);assert.equal(groups.find(g=>g.id===ids[2]).cards[0],cards[1]);assert.equal(groups.find(g=>g.id==="unclassified").cards.length,2);assert.deepEqual([...policy.multiviewDescendants([...nodes,{...nodes[0],parentId:ids[2]}],ids[0])],[ids[1],ids[2]]);});
test("view state parse rejects malformed storage and preserves each view selection",()=>{const input={...state("descendants"),search:"林",selectedByView:{characters:ids[1],events:ids[2]},groupFacetId:"tag"};assert.deepEqual(selection.parseMultiviewSelection(JSON.stringify({version:1,selection:input})),input);assert.equal(selection.parseMultiviewSelection(JSON.stringify({version:2,selection:input})),null);assert.equal(selection.parseMultiviewSelection(JSON.stringify({version:1,selection:{...input,selectedByView:{other:ids[1]}}})),null);assert.equal(selection.parseMultiviewSelection(JSON.stringify({version:1,selection:{...input,conditions:[{facetId:"tag",nodeIds:["bad"],mode:"exact"}]}})),null);});
test("all editor entry selections restore retained original requests and lock tag/provenance changes",()=>{const ui=read("client/businessForms/BusinessFormWorkspace.tsx");assert.match(ui,/const first = cards\[0\];\s*if \(first\) \{\s*selectCard\(first\)/);assert.match(ui,/CardTagFields[^\n]+disabled=\{[^}\n]*\bbusy\|\|unknownWrite\|\|requestKey!==null\|\|!sourcesReady\b[^}\n]*\}/);assert.match(ui,/hasUnsavedChanges=\{dirty\|\|unknownWrite\|\|requestKey!==null\|\|busy\}/);assert.match(ui,/disabled=\{[^}\n]*\bbusy\|\|unknownWrite\|\|requestKey!==null\|\|!sourcesReady\b[^}\n]*\} onClick=\{\(\)=>\{setAiDraftDecisionIds\(\[\]\)/);});
test("author panel retains drafts, has real recovery sources and no business writes",()=>{const ui=read("client/multiview/MultiviewAuthorPanel.tsx");assert.match(ui,/dirty&&\(!onPreserveDraft\|\|!onPreserveDraft\(\)\)/);assert.match(ui,/beforeunload/);assert.match(ui,/allowInlineCreate:false/);assert.match(ui,/同一份本书表单/);assert.match(ui,/structure\/maintenance/);assert.match(ui,/返回原页只读刷新来源，不重发保存请求/);assert.doesNotMatch(ui,/newDesignApi|updateCard|createCard|applyBookChange/);const db=read("server/database/multiviewAuthor/index.ts");assert.match(db,/getBookViewWorkspace/);assert.match(db,/getMaterialManagementWorkspace/);assert.match(db,/typeVersionId:card\.typeVersionId/);assert.doesNotMatch(db,/INSERT|UPDATE|DELETE|CREATE TABLE/);const css=read("client/multiview/multiview.css");assert.match(css,/font-size:16px;min-height:44px/);assert.match(css,/color:var\(--nd-ink\);background:var\(--nd-canvas\)/);});
