const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {isolatedDatabase,compiled}=require('./support/isolatedDatabase.cjs'),key=()=>randomUUID();
test('real empty book creation installs original project rule separately from frozen template and preserves exact format sources',{timeout:120000},async t=>{
 if(!process.env.ND_REFERENCE_TEST_BUILD){t.skip('Requires the final isolated work build.');return;}
 const {pool}=await isolatedDatabase(t),templates=compiled('server/database/templateStore'),cards=compiled('server/database/store'),classification=compiled('server/database/bookshelf/classification'),initialization=compiled('server/database/bookshelf/initialize'),shelf=compiled('server/database/bookshelf');
 const sourceBefore=(await pool.query("SELECT to_jsonb(type) value FROM new_design.card_types type WHERE id='10000000-0000-4000-8000-000000000001'")).rows[0].value;
 let template=await templates.saveTemplate({key:`empty_${key()}`,name:'空书实际接续',description:'',draftConfig:{},requestKey:key()});template=await templates.publishTemplate(template.id,template.revision,key());
 const payload=(await templates.listTemplateVersions(template.id))[0].payload;assert.equal(payload.cardTypes.some(type=>type.key==='project_rule'),false);
 const format={form:'long_novel',targetWordCount:200000},book=await templates.createBook({key:`empty_${key()}`,name:'空书接续',description:'',templateVersionId:template.currentVersionId},{includeTemplateSeed:false,origin:{method:'blank',sourceReference:'作者明确选择',sourcePayload:{storyFormat:format}}});
 const type=(await cards.listCardTypes(book.spaceId)).find(type=>type.key==='project_rule');assert.ok(type?.currentVersionId);
 const workspace=await classification.readBookClassification(book.id);assert.ok(workspace.cardId);assert.equal(workspace.canInitialize,false);assert.equal(workspace.revision,1);
 const original=(await pool.query('SELECT installed_payload FROM new_design.books WHERE id=$1',[book.id])).rows[0].installed_payload;assert.deepEqual(original,payload);
 const receipt=(await pool.query('SELECT author_write_receipt FROM new_design.card_versions WHERE card_id=$1',[workspace.cardId])).rows[0].author_write_receipt;assert.equal(receipt.operation,'create');assert.equal(receipt.bookId,book.id);
 const count=async()=>Number((await pool.query('SELECT count(*) n FROM new_design.cards WHERE space_id=$1',[book.spaceId])).rows[0].n),before=await count();
 const [a,b]=await Promise.all([initialization.initializeProjectRule(book.id,{requestKey:key()}),initialization.initializeProjectRule(book.id,{requestKey:key()})]);assert.equal(a.cardId,workspace.cardId);assert.equal(b.cardId,a.cardId);assert.equal(await count(),before);
 const input={requestKey:key(),cardId:workspace.cardId,expectedRevision:workspace.revision,classification:{publicationStatus:'draft',writingMode:'original',platform:'qidian_male',creationExperience:'simple'}};
 const saved=await classification.saveBookClassification(book.id,input);assert.equal(saved.card.id,workspace.cardId);assert.equal((await classification.saveBookClassification(book.id,input)).card.revision,saved.card.revision);
 const bookOnShelf=(await shelf.getBookshelfSnapshot(pool)).books.find(item=>item.id===book.id);assert.equal(bookOnShelf.storyFormat,null);assert.deepEqual(bookOnShelf.creationStoryFormat.format,format);assert.ok(bookOnShelf.creationStoryFormat.sourceId);assert.deepEqual(bookOnShelf.classification,input.classification);
 const planning=compiled('server/database/planning'),selection=(await planning.getPlanningCenterWorkspace(book.id)).creationStoryFormat;assert.deepEqual(selection,bookOnShelf.creationStoryFormat);
 const content={goal:'\u96e8\u591c\u8ffd\u67e5\u6765\u4fe1',storyFormat:{...selection.format},storyFormatSourceId:selection.sourceId},createPlan={bookId:book.id,level:'story',parentObjectId:null,cardId:null,title:'\u6545\u4e8b\u603b\u7eb2',sortOrder:0,content,source:'manual',executionMode:'manual',references:[],idempotencyKey:key()};
 await assert.rejects(planning.createPlanningObject({...createPlan,content:{...content,storyFormat:{form:'long_novel',targetWordCount:5000}},idempotencyKey:key()}),error=>error.status===422);
 await assert.rejects(planning.createPlanningObject({...createPlan,content:{...content,storyFormatSourceId:key()},idempotencyKey:key()}),error=>error.status===409);
 let plan=await planning.createPlanningObject(createPlan);assert.equal((await shelf.getBookshelfSnapshot(pool)).books.find(item=>item.id===book.id).storyFormat,null);
 plan=await planning.adoptPlanningVersion(plan.id,{versionId:plan.currentVersionId,expectedRevision:plan.revision,idempotencyKey:key()});assert.deepEqual((await shelf.getBookshelfSnapshot(pool)).books.find(item=>item.id===book.id).storyFormat,format);
 const edited={form:'short_story',targetWordCount:5000};plan=await planning.addPlanningVersion(plan.id,{content:{goal:content.goal,storyFormat:edited},source:'manual',executionMode:'manual',references:[],baseVersionId:plan.currentVersionId,expectedRevision:plan.revision,idempotencyKey:key()});assert.deepEqual((await shelf.getBookshelfSnapshot(pool)).books.find(item=>item.id===book.id).storyFormat,format);
 plan=await planning.adoptPlanningVersion(plan.id,{versionId:plan.currentVersionId,expectedRevision:plan.revision,idempotencyKey:key()});const shortBook=(await shelf.getBookshelfSnapshot(pool)).books.find(item=>item.id===book.id);assert.deepEqual(shortBook.storyFormat,edited);assert.deepEqual(shortBook.creationStoryFormat.format,format);
 assert.deepEqual((await pool.query("SELECT to_jsonb(type) value FROM new_design.card_types type WHERE id='10000000-0000-4000-8000-000000000001'")).rows[0].value,sourceBefore);
 // Existing empty books use the explicit command; archived/user-authored definitions are never overwritten.
 const spaceId=key(),oldBookId=key();await pool.query('INSERT INTO new_design.card_spaces(id,space_key,name) VALUES($1,$2,$3)',[spaceId,`book_${key()}`,'原空书']);await pool.query('INSERT INTO new_design.books(id,space_id,book_key,name,template_id,template_version_id,installed_payload) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[oldBookId,spaceId,`old_${key()}`,'原空书',template.id,template.currentVersionId,JSON.stringify(payload)]);
 assert.equal((await classification.readBookClassification(oldBookId)).canInitialize,true);const created=await initialization.initializeProjectRule(oldBookId,{requestKey:key()});assert.equal((await classification.readBookClassification(oldBookId)).cardId,created.cardId);assert.equal((await initialization.initializeProjectRule(oldBookId,{requestKey:key()})).cardId,created.cardId);
 await assert.rejects(initialization.initializeProjectRule(key(),{requestKey:key()}),error=>error.recovery.mutationOutcome==='not_written');
});
