const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {isolatedDatabase,compiled}=require('./support/isolatedDatabase.cjs');
const key=()=>randomUUID();
test('visible batches freeze actual published fields and save selected origins through the standard author form',async t=>{
 const {pool,database}=await isolatedDatabase(t);t.diagnostic(`Isolated database retained: ${database}`);
 const templates=compiled('server/database/templateStore'),cards=compiled('server/database/store'),fields=compiled('server/database/fieldExtensions'),refs=compiled('server/database/referenceParity'),batch=compiled('server/database/storyWorkspace'),author=compiled('server/database/authorMaterials'),prompts=compiled('server/ai/prompts');
 let template=await templates.saveTemplate({key:`t_${key().replaceAll('-','')}`,name:'外显隔离模板',description:'',draftConfig:{},requestKey:key()});template=await templates.publishTemplate(template.id,template.revision,key());
 const book=await templates.createBook({key:`b_${key().replaceAll('-','')}`,name:'外显隔离书',description:'',templateVersionId:template.currentVersionId});
 const p=await refs.previewReferenceAssociations(template.currentVersionId,['character']);template=await refs.publishReferenceAssociations({sourceTemplateVersionId:template.currentVersionId,templateRevision:template.revision,primaryTypeKeys:['character'],previewHash:p.inputHash,requestKey:key()});
 const visiblePreview=await refs.previewReferenceSpecification(template.currentVersionId,'visible');assert.equal(visiblePreview.canPublish,true,visiblePreview.conflicts.join(';'));assert.equal(visiblePreview.additions.length,5);const visiblePublication={kind:'visible',sourceTemplateVersionId:template.currentVersionId,templateRevision:template.revision,previewHash:visiblePreview.inputHash,requestKey:key()};template=await refs.publishReferenceSpecification(visiblePublication);assert.deepEqual(await refs.readReferenceSpecificationReceipt(visiblePublication),template);const sync=await templates.previewBookSync(book.id,template.currentVersionId);await templates.applyBookSync(sync.id);
 const source=(await templates.listTemplateVersions(template.id))[0].payload.forms.find(form=>form.key==='reference_character_associations'),selection={sourceTemplateVersionId:template.currentVersionId,sourceFormVersionId:source.sourceVersionId,setActive:true},fp=await refs.previewReferenceForm(book.id,selection),v1=await refs.installReferenceForm(book.id,{...selection,previewHash:fp.inputHash,requestKey:key()});
 const type=(await pool.query("SELECT * FROM new_design.card_types WHERE space_id=$1 AND type_key='character'",[book.spaceId])).rows[0],created=[];
 for(const [index,fieldType] of ['long_text','number','boolean'].entries()){
  const current=(await pool.query('SELECT revision FROM new_design.card_types WHERE id=$1',[type.id])).rows[0];
  created.push(await fields.createBookFieldExtension(book.id,{cardTypeId:type.id,expectedTypeRevision:current.revision,field:{name:`外显隔离字段${index}`,description:'',type:fieldType,required:false,defaultValue:null,options:[],group:'外显',aiSuggestible:true,stateSettlement:'none'},backfillStrategy:'none',idempotencyKey:key(),createdBy:'isolated_test'}));
 }
 const [appearance,count,flag]=created.map(field=>field.fieldKey),initial={name:'外显人物甲',story_role:'supporting',[appearance]:'人工填写的外貌',[count]:0,[flag]:false};
 const a=await cards.createCard({cardTypeId:type.id,spaceId:book.spaceId,title:'外显人物甲',values:initial,formVersionId:v1.currentVersionId,formResolutionKind:'installed_form'}),b=await cards.createCard({cardTypeId:type.id,spaceId:book.spaceId,title:'外显人物乙',values:{name:'外显人物乙',story_role:'supporting'},formVersionId:v1.currentVersionId,formResolutionKind:'installed_form'});
 const secondPreview=await refs.previewReferenceForm(book.id,{...selection,setActive:false,targetFormId:v1.id}),v2=await refs.installReferenceForm(book.id,{...selection,setActive:false,targetFormId:v1.id,previewHash:secondPreview.inputHash,requestKey:key()});assert.notEqual(v1.currentVersionId,v2.currentVersionId);
 let calls=0,received;const ai={generateStoryWorkspaceBatch:async input=>{calls++;received=structuredClone(input);return{output:{candidates:Object.fromEntries(input.slots.map(slot=>[slot.id,{[appearance]:`候选外貌：${slot.title}`,[count]:2,[flag]:true}]))},promptSnapshot:{assetId:'isolated_structured_stub'},modelSnapshot:{provider:'isolated_fixture'},usedTokens:10};}};
 const request={mode:'visible_prepare',requestKey:key(),instruction:'准备两个人物外显',cardIds:[a.id,b.id]},run=await batch.generateStoryBatch(book.id,request,ai);assert.equal(run.status,'review');assert.equal(calls,1);assert.equal(run.snapshot.slots.length,2);assert.ok(run.snapshot.slots.every(slot=>slot.target.formVersionId===v1.currentVersionId));
 assert.ok(received.slots.every(slot=>slot.fields.every(field=>field.group==='外显'||field.group==='外在表现')));assert.ok(received.slots.every(slot=>!slot.fields.some(field=>field.key==='name')));assert.equal(received.slots.find(slot=>slot.id===a.id).values[appearance],initial[appearance]);assert.equal(received.slots.find(slot=>slot.id===a.id).values[count],0);assert.equal(received.slots.find(slot=>slot.id===a.id).values[flag],false);
 assert.equal((await pool.query('SELECT values FROM new_design.cards WHERE id=$1',[a.id])).rows[0].values[appearance],initial[appearance]);assert.deepEqual(await batch.generateStoryBatch(book.id,request,ai),run);assert.equal(calls,1);
 await assert.rejects(batch.generateStoryBatch(book.id,{...request,instruction:'不同完整输入'},ai),e=>e.mutationOutcome==='unknown');assert.equal(calls,1);
 const prompt=prompts.preparePrompt('visible_prepare',run.snapshot);assert.equal(prompt.assetId,'new_design.character.visible_prepare');assert.throws(()=>prompt.parseOutput({candidates:{[a.id]:{name:'不能改名'},[b.id]:{[appearance]:'乙'}}}));assert.throws(()=>prompt.parseOutput({candidates:{[a.id]:{[appearance]:'缺少乙'}}}));
 const slot=run.snapshot.slots.find(slot=>slot.id===a.id),input={slotId:a.id,fieldKeys:[appearance],sourceHash:slot.sourceHash,requestKey:key()},draft=await batch.adoptVisibleFields(book.id,request.requestKey,input);assert.ok(draft.decisionId);assert.deepEqual(Object.keys(draft.values),[appearance]);assert.equal((await pool.query('SELECT revision FROM new_design.cards WHERE id=$1',[a.id])).rows[0].revision,a.revision);
 assert.deepEqual(await batch.adoptVisibleFields(book.id,request.requestKey,input),draft);assert.deepEqual(await batch.readVisibleAdoption(book.id,request.requestKey,input),draft);await assert.rejects(batch.readVisibleAdoption(book.id,request.requestKey,{...input,fieldKeys:[count]}),e=>e.mutationOutcome==='unknown');
 const write={requestKey:key(),cardTypeId:type.id,revision:a.revision,title:a.title,values:{...initial,...draft.values},formVersionId:v1.currentVersionId,formResolutionKind:'installed_form',aiDraftDecisionIds:[draft.decisionId]},saved=await author.updateAuthorMaterial(book.id,a.id,write);assert.equal(saved.card.values[appearance],draft.values[appearance]);assert.equal(saved.card.values[count],0);assert.equal(saved.card.values[flag],false);assert.equal(saved.card.values.name,initial.name);assert.deepEqual(saved.aiDraftDecisionIds,[draft.decisionId]);assert.deepEqual(await author.updateAuthorMaterial(book.id,a.id,write),{...saved,repeated:true});
 const origin=(await pool.query('SELECT * FROM new_design.card_field_origins WHERE card_id=$1 AND field_key=$2',[a.id,appearance])).rows[0];assert.equal(origin.generation_batch_id,request.requestKey);assert.equal(origin.confirmation_status,'confirmed');assert.equal((await pool.query('SELECT count(*)::int n FROM new_design.card_version_ai_draft_sources WHERE decision_id=$1',[draft.decisionId])).rows[0].n,1);
 assert.deepEqual(await batch.readVisibleAdoption(book.id,request.requestKey,input),draft);assert.equal((await batch.checkStoryBatchSlot(book.id,request.requestKey,b.id)).slot.id,b.id);
 const adjusted=await batch.generateStoryBatch(book.id,{mode:'visible_adjust',requestKey:key(),instruction:'调整指定人物的外显',cardIds:[a.id]},ai);assert.equal(adjusted.status,'review');assert.equal(adjusted.snapshot.slots.length,1);assert.equal(prompts.preparePrompt('visible_adjust',adjusted.snapshot).assetId,'new_design.character.visible_adjust');
 await cards.updateCard(a.id,{title:a.title,values:{...saved.card.values,[appearance]:'准备后又有人工填写'},revision:saved.card.revision});await assert.rejects(batch.adoptVisibleFields(book.id,adjusted.requestKey,{slotId:a.id,fieldKeys:[appearance],sourceHash:adjusted.snapshot.slots[0].sourceHash,requestKey:key()}),e=>e.mutationOutcome==='not_written');
 // Explicit batch saving uses exactly the same author-card writer in one atomic transaction.
 const freshRun=await batch.generateStoryBatch(book.id,{mode:'visible_prepare',requestKey:key(),instruction:'批量原子保存',cardIds:[a.id,b.id]},ai),batchInput={requestKey:key(),items:freshRun.snapshot.slots.map(slot=>({slotId:slot.id,fieldKeys:[appearance],sourceHash:slot.sourceHash,requestKey:key(),saveRequestKey:key()}))};
 const before=(await pool.query('SELECT id,revision,current_version_id,values FROM new_design.cards WHERE id=ANY($1::uuid[]) ORDER BY id',[[a.id,b.id]])).rows;
 await pool.query(`CREATE FUNCTION new_design.reject_visible_fixture() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id='${b.id}'::uuid THEN RAISE EXCEPTION 'isolated injected second actor failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER reject_visible_fixture BEFORE UPDATE ON new_design.cards FOR EACH ROW EXECUTE FUNCTION new_design.reject_visible_fixture()`);
 await assert.rejects(batch.writeVisibleBatch(book.id,freshRun.requestKey,batchInput),e=>e.mutationOutcome==='not_written');assert.deepEqual((await pool.query('SELECT id,revision,current_version_id,values FROM new_design.cards WHERE id=ANY($1::uuid[]) ORDER BY id',[[a.id,b.id]])).rows,before);assert.equal((await pool.query('SELECT count(*)::int n FROM new_design.form_ai_draft_decisions WHERE batch_id=$1',[freshRun.requestKey])).rows[0].n,0);assert.equal((await batch.readStoryBatch(book.id,freshRun.requestKey)).status,'review');assert.equal(await batch.readVisibleBatchWrite(book.id,freshRun.requestKey,batchInput),null);
 await pool.query('DROP TRIGGER reject_visible_fixture ON new_design.cards; DROP FUNCTION new_design.reject_visible_fixture()');
 const [batchSaved,batchRepeat]=await Promise.all([batch.writeVisibleBatch(book.id,freshRun.requestKey,batchInput),batch.writeVisibleBatch(book.id,freshRun.requestKey,batchInput)]);assert.deepEqual(batchSaved,batchRepeat);assert.equal(batchSaved.items.length,2);assert.deepEqual(await batch.readVisibleBatchWrite(book.id,freshRun.requestKey,batchInput),batchSaved);for(const saved of batchSaved.items){assert.equal(saved.card.values[appearance],freshRun.output.candidates[saved.card.id][appearance]);assert.equal(saved.card.values[count],before.find(row=>row.id===saved.card.id).values[count]);assert.equal(saved.card.values[flag],before.find(row=>row.id===saved.card.id).values[flag]);assert.equal(saved.aiDraftDecisionIds.length,1);assert.deepEqual(await author.readAuthorMaterialWriteReceipt(book.id,saved.requestKey),saved);}assert.equal((await pool.query('SELECT count(*)::int n FROM new_design.form_ai_draft_decisions WHERE batch_id=$1',[freshRun.requestKey])).rows[0].n,3);
 await assert.rejects(batch.readVisibleBatchWrite(book.id,freshRun.requestKey,{...batchInput,items:batchInput.items.slice(0,1)}),e=>e.mutationOutcome==='unknown');assert.equal(await batch.readVisibleBatchWrite(key(),freshRun.requestKey,batchInput),null);
 const lostRun=await batch.generateStoryBatch(book.id,{mode:'visible_adjust',requestKey:key(),instruction:'丢失保存确认',cardIds:[a.id,b.id]},ai),lostInput={requestKey:key(),items:lostRun.snapshot.slots.map(slot=>({slotId:slot.id,fieldKeys:[appearance],sourceHash:slot.sourceHash,requestKey:key(),saveRequestKey:key()}))};
 const originalConnect=pool.connect.bind(pool);pool.connect=async()=>{const client=await originalConnect(),query=client.query.bind(client);client.query=async(...args)=>{const result=await query(...args);if(args[0]==='COMMIT'){client.query=query;throw new Error('isolated lost commit acknowledgment');}return result;};return client;};
 try{await assert.rejects(batch.writeVisibleBatch(book.id,lostRun.requestKey,lostInput),e=>e.mutationOutcome==='unknown');}finally{pool.connect=originalConnect;}
 const recovered=await batch.readVisibleBatchWrite(book.id,lostRun.requestKey,lostInput);assert.ok(recovered);assert.equal(recovered.items.length,2);assert.deepEqual(await batch.writeVisibleBatch(book.id,lostRun.requestKey,lostInput),recovered);
 assert.equal((await pool.query('SELECT count(*)::int n FROM new_design.card_relations WHERE space_id=$1',[book.spaceId])).rows[0].n,0);
});
