const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {compiled}=require('./support/isolatedDatabase.cjs'),{resourceSupplementFixture}=require('./support/resourceSupplementFixture.cjs'),{resourceSupplementHttp}=require('./support/resourceSupplementHttp.cjs'),{resourceBackfillClient:client}=require('./support/resourceBackfillClient.cjs');
const {ResourceBackfillSeriesController}=client('controller'),{prepareResourceBackfillSeries,prepareResourceBackfillAi}=client('preflight'),{createResourceSupplementApi}=client('api'),key=()=>randomUUID();
test('real retained PostgreSQL / HTTP recent chapter range with two lost acknowledgements preserves all stable originals',async t=>{
 const migrations=[['087','stable_resource_supplements'],['085','character_resource_backfill'],['088','stable_resource_supplement_candidates'],['089','resource_supplement_impact_reviews'],['090','resource_supplement_integrity'],['091','resource_supplement_correction_origins'],['092','resource_supplement_formal_commits'],['093','resource_supplement_correction_candidates'],['094','resource_supplement_correction_commits']].map(([n,name])=>({id:`${n}_${name}`,fileName:`${n}_${name}.sql`}));
 const f=await resourceSupplementFixture(t,migrations),{book,pool,actor,settlement}=f,prop=await f.create('prop','批量资源',{name:'批量资源'}),field=(key,name,type)=>({key,name,type,description:'资源',required:false,defaultValue:null,options:[],group:'资源',order:1,aiSuggestible:true});
 const definition={name:'批量人物持有',description:'隔离范围',direction:'directed',sourceTypeKeys:['character'],targetTypeKeys:['prop'],sourceMax:null,targetMax:null,fields:[field('holding','持有','boolean'),field('quantity','数量','number')],capability:'optional',mode:'relation_state',dimensions:[{fieldKey:'holding',label:'持有',direction:'forward',policy:'tracked',mode:'absolute'},{fieldKey:'quantity',label:'数量',direction:'forward',policy:'tracked',mode:'delta'}]};
 const draft=await settlement.saveSettlementRelationConfigurationDraft(book.id,{requestKey:key(),expectedRelationTypeRevision:null,definition});
 await settlement.publishSettlementRelationConfigurationDraft(book.id,{requestKey:key(),draftId:draft.draftId,expectedRevision:1,confirmPublish:true,confirmInstanceRebind:false,rebindRelations:[],createRelations:[{sourceCardId:actor.id,targetCardId:prop.id}]});
 const resources=compiled('server/database/characterResources'),ledger=await resources.getCharacterResources(book.id,actor.id),choice=ledger.choices.find(c=>c.holdingDimensionKey==='holding'),selection={relationTypeId:choice.relationTypeId,holdingDimensionKey:choice.holdingDimensionKey,specificationHash:choice.specificationHash},selected=await resources.getCharacterResources(book.id,actor.id,selection),relation=selected.items[0].relationId;
 for(const [stateKey,value]of [['holding',false],['quantity',0]])await f.state.saveInitialState({bookId:book.id,subjectKind:'relation',subjectId:relation,stateKey,value,requestKey:key(),actor:'isolated_batch_author',note:''});
 const chapters=[];for(const order of [1,2,3])chapters.push(await f.chapter(order,order,order===1));
 const scope={...selection,characterId:actor.id,characterVersionId:selected.characterVersionId,characterRevision:selected.characterRevision,resourceIds:[prop.id],relationIds:[relation]},input={resourceScope:scope,documentIds:chapters.map(c=>c.document.id).reverse()};
 const originals=async()=>({sessions:(await pool.query('SELECT to_jsonb(s) value FROM new_design.chapter_adoption_sessions s WHERE id=ANY($1::uuid[]) ORDER BY id',[chapters.map(c=>c.workspace.session.id)])).rows,documents:(await pool.query('SELECT to_jsonb(d) value FROM new_design.chapter_documents d WHERE id=ANY($1::uuid[]) ORDER BY id',[chapters.map(c=>c.document.id)])).rows,checkpoints:(await pool.query('SELECT to_jsonb(c) value FROM new_design.chapter_stable_checkpoints c ORDER BY id')).rows,states:(await pool.query('SELECT to_jsonb(s) value FROM new_design.state_changes s ORDER BY id')).rows});
 const before=await originals(),counts=async()=>(await pool.query(`SELECT (SELECT count(*)::int FROM new_design.chapter_resource_supplements) creations,(SELECT count(*)::int FROM new_design.chapter_proposal_extraction_requests) extractions,(SELECT count(*)::int FROM new_design.resource_supplement_formal_commits) formals,(SELECT count(*)::int FROM new_design.resource_supplement_integrity_issues) issues`)).rows[0];
 const models=compiled('server/database/modelManagement'),route={primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'isolated-range-provider-stub',credentialId:null},fallbacks:[],policy:{maxOutputTokens:8000,maxTotalTokens:1000000,timeoutMs:30000,maxRetries:0,retryDelayMs:0}};
 for(const [scope,taskType]of [['system_default',null],['task','chapter_settlement']]){const current=(await models.getModelRouteCenterCatalog()).routes.find(r=>r.scope===scope&&r.taskType===taskType);await models.saveManagedModelRoute({...route,scope,taskType,expectedConfigId:current?.id??null,expectedRevision:current?.revision??null,replaceUnsupported:true,idempotencyKey:key()});}
 let providerCalls=0,lostStart=false,lostAi=false;
 const http=await resourceSupplementHttp(t,{runExtraction:async(session,value)=>{
  const workspace=await settlement.getChapterSettlementEditingWorkspace(session),source=await f.supplements.getResourceSupplementSource(book.id,session),dimension=workspace.catalog.subjects.find(s=>s.id===relation).fields.find(field=>field.key==='quantity'),after=source.basis.chapterOrder;
  const candidate={category:'relationship',title:`第${after}章资源`,subjectKind:'relation',subjectId:relation,stateKey:'quantity',specificationHash:dimension.specificationHash,baselineHash:dimension.baseline.hash,beforeValue:dimension.baseline.value,afterValue:after,changeValue:after-Number(dimension.baseline.value),riskLevel:'medium',confidence:0.8,confidenceNote:'隔离范围',planAlignment:'not_applicable',planExpectation:'',evidenceStart:0,evidenceEnd:source.basis.bodyContent.length,evidenceLabel:source.basis.bodyContent,reason:'仅保存人工核对候选'};
  return compiled('server/ai/chapterSettlement').runChapterSettlementAiExtraction(session,value,{fetcher:async()=>{providerCalls++;return new Response(JSON.stringify({message:{content:JSON.stringify({items:[candidate],notes:[]})},prompt_eval_count:100,eval_count:50}),{status:200,headers:{'content-type':'application/json'}});}});
 }});
 const rootJson=require('express').response.json;http.app.response.json=function(envelope){const isStart=this.req.method==='POST'&&this.req.path.endsWith('/resource-supplements'),isAi=this.req.method==='POST'&&this.req.path.endsWith('/editing/ai-extractions');if(envelope?.success&&(isStart&&!lostStart||isAi&&providerCalls===2&&!lostAi)){if(isStart)lostStart=true;else lostAi=true;this.socket.destroy();return this;}return rootJson.call(this,envelope);};
 const api={...createResourceSupplementApi((path,init)=>init?.method==='POST'?http.post(path,JSON.parse(init.body)):http.get(path)),getCharacterResources:(book,actor,selection)=>http.get(`/books/${book}/characters/${actor}/resource-ledger?${new URLSearchParams(selection)}`),getChapterSettlementEditingWorkspace:session=>http.get(`/chapter-adoption-sessions/${session}/editing-workspace`)},values=new Map(),storageKey=`batch:${book.id}:${actor.id}`;
 const ports={bookId:book.id,characterId:actor.id,key:storageKey,storage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},uuid:key,changed:()=>{},lock:run=>run(),prepare:input=>prepareResourceBackfillSeries(api,book.id,input,key),prepareAi:(part,input)=>prepareResourceBackfillAi(api,book.id,part,input.resourceScope),start:command=>api.startResourceSupplement(book.id,command),readStart:command=>api.readResourceSupplementStartOriginal(book.id,command),ai:command=>http.post(`/chapter-adoption-sessions/${command.sessionId}/editing/ai-extractions`,command.input),readAi:command=>http.post(`/chapter-adoption-sessions/${command.sessionId}/editing/ai-extraction-receipt`,command.input),notWritten:error=>error.recovery?.mutationOutcome==='not_written'};
 await t.test('whole valid preflight sorts actual recent adopted bodies and performs zero writes',async()=>{const parts=await ports.prepare(input);assert.deepEqual(parts.map(p=>p.chapter.logicalOrder),[1,2,3]);assert.deepEqual(await counts(),{creations:0,extractions:0,formals:0,issues:0});assert.equal(providerCalls,0);assert.deepEqual(await originals(),before);});
 await t.test('last missing chapter, foreign actor and stale declared scope reject before any creation or model',async()=>{for(const value of [{...input,documentIds:[...input.documentIds.slice(0,2),key()]},{...input,resourceScope:{...scope,characterId:key()}},{...input,resourceScope:{...scope,characterRevision:scope.characterRevision+1}}])await assert.rejects(ports.prepare(value));assert.deepEqual(await counts(),{creations:0,extractions:0,formals:0,issues:0});assert.equal(providerCalls,0);});
 let controller=new ResourceBackfillSeriesController(ports);controller.restore();
 await t.test('actual first independent COMMIT response loss retains full pending command and zero models',async()=>{await controller.start(input);assert.equal(controller.plan.stage,'pending_start',controller.message);assert.equal(lostStart,true);assert.equal(providerCalls,0);assert.deepEqual(await counts(),{creations:1,extractions:0,formals:0,issues:0});controller.cancel();controller=new ResourceBackfillSeriesController(ports);controller.restore();await controller.verify();assert.equal(controller.plan.stage,'ready',controller.message);assert.equal(providerCalls,0);assert.deepEqual(await counts(),{creations:1,extractions:0,formals:0,issues:0});});
 await t.test('actual second governed model response loss keeps prior results and stops the third chapter',async()=>{await controller.resume();assert.equal(controller.plan.stage,'pending_ai',controller.message);assert.equal(controller.plan.next,1);assert.equal(providerCalls,2);assert.equal(lostAi,true);assert.deepEqual(await counts(),{creations:2,extractions:2,formals:0,issues:0});controller.cancel();controller=new ResourceBackfillSeriesController(ports);controller.restore();await controller.verify();assert.equal(controller.plan.stage,'ready',controller.message);assert.equal(controller.plan.next,2);assert.equal(providerCalls,2);assert.deepEqual(await counts(),{creations:2,extractions:2,formals:0,issues:0});});
 await t.test('explicit remaining range prepares only the third model, retaining all stable original rows',async()=>{await controller.resume();assert.equal(controller.plan.stage,'complete',controller.message);assert.equal(providerCalls,3);assert.deepEqual(await counts(),{creations:3,extractions:3,formals:0,issues:0});assert.deepEqual(await originals(),before);const proposed=(await pool.query('SELECT decision,count(*)::int n FROM new_design.chapter_settlement_items WHERE session_id=ANY($1::uuid[]) GROUP BY decision',[controller.plan.parts.map(p=>p.ai.sessionId)])).rows;assert.deepEqual(proposed,[{decision:'pending',n:3}]);});
});
