const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const {normalizeFormLocalField}=require('../dist/common/formLocalFieldNormalization');
const runtime=require('../dist/server/database/runtime');
const {executeStructureWrite,readStructureWriteReceipt,structureWriteHash,strictFormInputSchema,parseStructureWriteInput}=require('../dist/server/database/structureWrites');
const key='00000000-0000-4000-8000-000000000101';
const summary={id:'00000000-0000-4000-8000-000000000102',key:'template_fixture',name:'测试模板',description:'隔离假客户端',status:'draft',revision:1,currentVersion:null,currentVersionId:null,draftConfig:{},createdAt:'2026-09-17T00:00:00Z',updatedAt:'2026-09-17T00:00:00Z'};
async function scoped(query,action){const previous=runtime.getNewDesignPool,client={query,release(){}};runtime.getNewDesignPool=async()=>({connect:async()=>client});try{return await action();}finally{runtime.getNewDesignPool=previous;}}
test('structure receipt mock: result and acknowledgement precede COMMIT, no post-COMMIT read',async()=>{const calls=[];await scoped(async(sql)=>{calls.push(sql);return{rows:[]};},async()=>{const saved=await executeStructureWrite('template','save',key,{name:'测试模板'},async(client)=>{await client.query('MOCK original-template-write');return summary;});assert.equal(saved,summary);});assert.ok(calls.findIndex(sql=>sql.startsWith('INSERT INTO new_design.structure_write_receipts'))<calls.indexOf('COMMIT'));assert.equal(calls.at(-1),'COMMIT');});
test('structure receipt mock: same complete input reuses immutable original summary',async()=>{const input={id:summary.id,revision:1},hash=structureWriteHash({kind:'template',operation:'publish',input});let written=0;await scoped(async(sql)=>({rows:sql.startsWith('SELECT * FROM new_design.structure_write_receipts')?[{kind:'template',operation:'publish',request_key:key,input_hash:hash,result_summary:summary}]:[]}),async()=>{assert.deepEqual(await executeStructureWrite('template','publish',key,input,async()=>{written++;return summary;}),summary);});assert.equal(written,0);assert.equal(structureWriteHash({a:1,b:{x:false,y:0}}),structureWriteHash({b:{y:0,x:false},a:1}));});
test('structure receipt mock: another payload at original key remains unknown despite local rollback',async()=>{await scoped(async(sql)=>({rows:sql.startsWith('SELECT * FROM new_design.structure_write_receipts')?[{operation:'save',input_hash:'different'}]:[]}),async()=>{await assert.rejects(executeStructureWrite('template','save',key,{name:'新输入'},async()=>summary),error=>error.status===409&&error.recovery.mutationOutcome==='unknown');});});
test('structure receipt mock: only acknowledged rollback before COMMIT permits not_written',async()=>{for(const committing of [false,true])await scoped(async(sql)=>{if(committing&&sql==='COMMIT')throw new Error('mock disconnected');return{rows:[]};},async()=>{await assert.rejects(executeStructureWrite('template','save',key,{name:'测试模板'},async()=>{if(!committing)throw new Error('mock SQL failure');return summary;}),error=>error.recovery.mutationOutcome===(committing?'unknown':'not_written')&&!error.message.includes('mock'));});});
test('structure receipt mock: readonly missing original acknowledgement is null, not a write proof',async()=>{const calls=[];await scoped(async(sql)=>{calls.push(sql);return{rows:[]};},async()=>assert.equal(await readStructureWriteReceipt('template',key),null));assert.equal(calls[0],'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');assert.ok(!calls.some(sql=>/^(INSERT|UPDATE|DELETE)/.test(sql)));});
test('strict form schema preserves real options, defaults and exact dictionary contract without stripping',()=>{const field={key:'stance',name:'立场',description:'正式来源',type:'select',required:false,defaultValue:'ally',options:[{value:'ally',label:'盟友'}],group:'本事件补充',order:10,aiSuggestible:true,stateSettlement:'tracked'};const parsed=strictFormInputSchema.parse({key:'form_fixture',name:'表单',description:'',requestKey:key,definition:{primaryTypeKey:'event',groups:[{key:'main',name:'主要资料',order:10,sections:[{key:'core',name:'核心信息',order:10,slots:[{key:'participants',name:'参与人物',kind:'card_reference',relationTypeKey:'participants',allowedTypeKeys:['character'],min:0,max:10,localFields:[field]}]}]}]}});assert.deepEqual(parsed.definition.groups[0].sections[0].slots[0].localFields[0],field);assert.equal(parsed.requestKey,key);});
test('structure page recovery is original-key GET only and source generations preserve drafts',()=>{const read=name=>fs.readFileSync(path.join(__dirname,'../src/client',name),'utf8'),recovery=read('structureWrites/useRecovery.ts'),template=read('TemplateGroupsPage.tsx'),form=read('FormDesignerPage.tsx'),sync=read('structureWrites/useSyncRecovery.ts');assert.match(recovery,/getStructureWriteReceipt\(kind,original.key\)/);assert.match(recovery,/空查询不证明未写入/);assert.match(recovery,/workingRef.current/);assert.match(recovery,/if\(clear\(\)\)/);assert.match(recovery,/storageBlockedRef.current=true/);assert.match(template,/selected===selection.current/);assert.match(template,/request!==catalogGeneration.current/);assert.match(template,/templateConflictLabel/);assert.match(form,/window.confirm/);assert.match(form,/if\(!draftRef.current&&selectedGeneration===generation.current/);assert.match(sync,/getBookTemplateSync\(frozen.sync.id\)/);assert.match(sync,/saved.status==='previewed'/);assert.match(sync,/不能证明请求已终止/);});
test('technical receipt migration is append-only and does not copy original definitions',()=>{const sql=fs.readFileSync(path.join(__dirname,'../migrations/071_structure_write_receipts.sql'),'utf8');assert.match(sql,/PRIMARY KEY\(kind,request_key\)/);assert.match(sql,/BEFORE UPDATE OR DELETE/);assert.match(sql,/RAISE EXCEPTION/);assert.ok(!/INSERT INTO (template_groups|card_group_forms)/.test(sql));});
test('entry validation before business write has distinct not-written proof and Chinese exact paths',()=>{assert.throws(()=>parseStructureWriteInput('form','save',strictFormInputSchema,{key:'form_fixture',name:'表单',definition:{primaryTypeKey:'event',groups:[]}}),error=>error.status===422&&error.recovery.mutationOutcome==='not_written'&&error.recovery.savedResult.includes('尚未进入写入')&&!error.recovery.savedResult.includes('回滚')&&Object.keys(error.issues).includes('definition.groups'));});
test('public local field contract preserves full formal defaults while historical core remains optional',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/common/contracts.ts'),'utf8');assert.match(source,/FormLocalFieldDefinition extends\s+Pick<FieldDefinition/);assert.match(source,/Partial<Omit<FieldDefinition/);});
function draftPolicy(){const source=fs.readFileSync(path.join(__dirname,'../src/client/structureDraftRecovery.ts'),'utf8'),module={exports:{}};new Function('module','exports','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(module,module.exports,request=>{assert.equal(request,'../common/formLocalFieldNormalization');return {normalizeFormLocalField};});return module.exports;}
function formInput(field){return{key:'form_fixture',name:'表单',description:'',definition:{primaryTypeKey:'event',groups:[{key:'main',name:'主要资料',order:10,sections:[{key:'core',name:'核心信息',order:10,slots:[{key:'participants',name:'参与人物',kind:'card_reference',relationTypeKey:'participants',allowedTypeKeys:['character'],min:0,max:10,localFields:[field]}]}]}]}};}
test('declared optional defaults and whitespace produce exact strict form output without changing raw draft',()=>{const policy=draftPolicy(),field={key:' count ',name:' 次数 ',type:'number',required:false,order:1},input=formInput(field),draft={...summary,isSystem:false,key:input.key,name:' 表单 ',description:' ',draftDefinition:input.definition};delete draft.draftConfig;const raw=JSON.stringify(draft),normalized=policy.normalizedStructureDraft(draft),server=strictFormInputSchema.parse({...formInput(field),name:' 表单 ',description:' '});assert.deepEqual(normalized.draftDefinition,server.definition);assert.equal(normalized.name,server.name);assert.equal(normalized.description,server.description);assert.equal(JSON.stringify(draft),raw);assert.deepEqual(normalized.draftDefinition.groups[0].sections[0].slots[0].localFields[0],{key:'count',name:'次数',type:'number',required:false,order:1,description:'',group:'基本信息',defaultValue:null,options:[]});});
test('field options and dictionary rule defaults match strict schema but required rule fields are never invented',()=>{const tree={key:'stance',name:'立场',type:'select',required:false,order:1,optionSource:{kind:'dictionary_tree',dictionaryId:key,rule:{mode:'single',depthMode:'whole_tree'}}},normalized=normalizeFormLocalField(tree),server=strictFormInputSchema.parse(formInput(tree));assert.deepEqual(normalized,server.definition.groups[0].sections[0].slots[0].localFields[0]);const inline={key:'stance',name:' 立场 ',type:'select',required:false,order:1,defaultValue:0,options:[{value:' ally ',label:' 盟友 '}]};assert.deepEqual(normalizeFormLocalField(inline),strictFormInputSchema.parse(formInput(inline)).definition.groups[0].sections[0].slots[0].localFields[0]);assert.equal(normalizeFormLocalField({...inline,defaultValue:false}).defaultValue,false);for(const field of [{key:'count',name:'次数',type:'number',required:false},{...tree,optionSource:{...tree.optionSource,rule:{}}},{...tree,optionSource:{kind:'dictionary_tree',dictionaryId:key}}]){const value=normalizeFormLocalField(field);assert.equal(strictFormInputSchema.safeParse(formInput(value)).success,false);}const missingRule=normalizeFormLocalField({...tree,optionSource:{...tree.optionSource,rule:{}}}).optionSource.rule;assert.ok(!Object.hasOwn(missingRule,'mode'));assert.ok(!Object.hasOwn(missingRule,'depthMode'));});
test('normalizer preserves unknown extensions for strict rejection, never strips or fabricates order',()=>{const field={key:'count',name:'次数',type:'number',required:false,order:1,extra:{original:'原扩展'}},raw=JSON.stringify(field),normalized=normalizeFormLocalField(field);assert.deepEqual(normalized.extra,field.extra);assert.equal(JSON.stringify(field),raw);assert.equal(strictFormInputSchema.safeParse(formInput(normalized)).success,false);assert.ok(!Object.hasOwn(normalizeFormLocalField({key:'count',name:'次数',type:'number',required:false}),'order'));});
test('old pending comparison normalizes only readonly copies and raw restoration retains original key/input',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/client/structureWrites/useRecovery.ts'),'utf8'),page=fs.readFileSync(path.join(__dirname,'../src/client/FormDesignerPage.tsx'),'utf8');assert.match(source,/actual=normalizedStructureDraft\(saved\),expected=normalizedStructureDraft\(original.draft\)/);assert.match(source,/draft:value.draft/);assert.match(source,/key:value.key/);assert.match(source,/callback.current\(restored.rawDraft\?\?restored.draft,false\)/);assert.match(source,/rawDraft.id!==value.draft.id/);assert.match(source,/rawDraft.revision!==value.draft.revision/);assert.match(page,/createCardGroupForm\(\{\.\.\.input,requestKey\}\),draft\)/);});
