const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {creationFixture,seedCreationTemplate}=require('./creationProduction/postgresFixture.cjs');
const world=require('../dist/server/application/worldConsistency'),dbWorld=require('../dist/server/database/worldConsistency'),templates=require('../dist/server/database/templateStore'),models=require('../dist/server/database/modelManagement');
function candidate(input){const subject=input.catalog.subjects.find(s=>s.kind==='card'),field=subject.fields.find(f=>f.key==='notes');return{summary:'隔离模型回复：地域约束有歧义',findings:[{stableKey:'region_constraint',title:'地域约束未明确',description:'仅检查原资料的正式约束字段',severity:'medium',evidence:[{kind:subject.kind,id:subject.id,versionId:subject.versionId,fieldKey:field.key,specVersionId:field.specVersionId,specHash:field.specHash,valueHash:field.valueHash,note:'原正式资料为不可飞行'}],fixes:[{cardId:subject.id,cardVersionId:subject.versionId,fieldKey:field.key,specVersionId:field.specVersionId,specHash:field.specHash,beforeHash:field.valueHash,after:'禁海范围内不可飞行',reason:'明确范围，候选无正式保存权'}]}],recheckOutcome:'not_requested'};}
test('world consistency uses real isolated quality/task ledgers and explicit saved reply recovery without a second model call',
 {skip:process.env.AI_NOVEL_NEW_DESIGN_DEV_RUNTIME!=='1',timeout:180000},async t=>{
 const fixture=await creationFixture(t),{db,scopedPool}=fixture,configuration=await seedCreationTemplate(db);
 await db.query('BEGIN');let book;
 try{({book}=await templates.createBookInTransaction(db,{key:`world_${randomUUID().replaceAll('-','')}`,name:'隔离世界检查',description:'不复制作者数据',templateVersionId:configuration.version},{includeTemplateSeed:false,reviewCards:[{id:randomUUID(),typeKey:'character',title:'禁海城设定',values:{name:'禁海城',notes:'不可飞行'},sourceKind:'manual',sourceId:null,sourceVersionId:null,originalTitle:'禁海城设定',originalValues:{name:'禁海城',notes:'不可飞行'}}]}));await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}
 await models.saveManagedModelRoute({scope:'system_default',taskType:null,expectedConfigId:null,expectedRevision:null,idempotencyKey:randomUUID(),primary:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'world-fixture-stub-not-real-model',credentialId:null},fallbacks:[],policy:{maxOutputTokens:8000,maxTotalTokens:1000000,timeoutMs:30000,maxRetries:0,retryDelayMs:0}},{client:db});
 const scope=work=>dbWorld.withWorldConsistencyPool(scopedPool,work);let calls=0,input,result;
 const fetcher=async(_url,options)=>{calls++;const taskData=JSON.parse(JSON.parse(options.body).messages.at(-1).content).taskData;assert.equal(taskData.contract,'world_consistency_v1');return new Response(JSON.stringify({message:{content:JSON.stringify(candidate(taskData))},prompt_eval_count:25,eval_count:17}),{status:200,headers:{'content-type':'application/json'}});};
 await scope(async()=>{
  const workspace=await world.getWorldConsistencyWorkspace(book.id);input={requestKey:randomUUID(),catalogHash:workspace.catalog.hash,cardIds:workspace.catalog.subjects.filter(s=>s.kind==='card').map(s=>s.id),relationIds:[]};
  let fault=false;const faultDb=new Proxy(db,{get(target,key){if(key==='query')return(sql,values)=>{if(!fault&&typeof sql==='string'&&sql.includes('INSERT INTO new_design.quality_audit_reports')){fault=true;return db.query('SELECT 1/0');}return db.query(sql,values);};return Reflect.get(target,key);}});
  await t.test('raw reply commits separately; candidate import failure preserves original reply and actual usage',async()=>{
   await dbWorld.withWorldConsistencyPool({query:faultDb.query,connect:async()=>faultDb},()=>assert.rejects(world.runWorldConsistency(book.id,input,{fetcher})));assert.equal(fault,true);assert.equal(calls,1);result=await world.getWorldConsistencyByKey(book.id,input.requestKey);assert.equal(result.status,'running');assert.equal(result.modelResultSaved,true);assert.equal(result.canImportSavedResult,true);assert.equal(result.modelRequestState,'completed');assert.deepEqual(result.input,input);
   assert.equal((await world.runWorldConsistency(book.id,input,{fetcher})).id,result.id);assert.equal(calls,1);
   await assert.rejects(world.runWorldConsistency(book.id,{...input,cardIds:[]},{fetcher}));assert.equal(calls,1);
  });
  await t.test('explicit import uses same attempt and original problem ledger, with local quality debt only',async()=>{
   result=await world.importSavedWorldConsistency(book.id,result.id);assert.equal(result.status,'succeeded');assert.equal(calls,1);const updated=await world.getWorldConsistencyWorkspace(book.id);assert.equal(updated.issues.length,1);assert.equal(updated.issues[0].currentVersion.evidence[0].evidenceKind,'card_field');assert.equal(updated.issues[0].fixCandidates[0].versions[0].targetCardId,input.cardIds[0]);
   const executionResult=(await db.query('SELECT attempt.result_stable_id,attempt.result_version_id FROM new_design.ai_task_attempts attempt JOIN new_design.world_consistency_requests request ON request.attempt_id=attempt.id WHERE request.id=$1',[result.id])).rows[0];assert.equal(executionResult.result_stable_id,result.reportId);assert.equal(executionResult.result_version_id,result.reportId);
   for(const replacement of ['invented_field',null])await assert.rejects(db.query(`INSERT INTO new_design.quality_issue_evidence(id,issue_version_id,evidence_kind,material_kind,material_id,card_version_id,relation_version_id,field_key,field_spec_version_id,field_spec_hash,observed_value_hash,note,is_unverified_observation)
    SELECT $1,issue_version_id,evidence_kind,material_kind,material_id,card_version_id,relation_version_id,$2,field_spec_version_id,field_spec_hash,observed_value_hash,note,false FROM new_design.quality_issue_evidence WHERE issue_version_id=$3 LIMIT 1`,[randomUUID(),replacement,updated.issues[0].currentVersion.id]),error=>error.code==='23514');
   const report=(await db.query('SELECT policy_decision,execution_effect FROM new_design.quality_audit_reports WHERE id=$1',[result.reportId])).rows[0];assert.deepEqual(report,{policy_decision:'record_quality_debt',execution_effect:'quality_debt'});const usage=(await db.query('SELECT input_tokens,output_tokens FROM new_design.ai_attempt_usage WHERE task_id=(SELECT ai_task_id FROM new_design.world_consistency_requests WHERE id=$1)',[result.id])).rows[0];assert.equal(Number(usage.input_tokens),25);assert.equal(Number(usage.output_tokens),17);
   assert.equal((await world.importSavedWorldConsistency(book.id,result.id)).id,result.id);assert.equal(calls,1);const issue=updated.issues[0];await assert.rejects(world.runWorldConsistency(book.id,{...input,requestKey:randomUUID(),catalogHash:updated.catalog.hash,recheckIssueId:issue.id},{fetcher}));assert.equal(calls,1);
  });
  await t.test('wrong book or missing normal save does not manufacture a repair proof',async()=>{const issue=(await world.getWorldConsistencyWorkspace(book.id)).issues[0],id=issue.fixCandidates[0].id;await assert.rejects(world.getWorldConsistencyRepairDraft(randomUUID(),id));assert.equal(await world.getWorldRepairNormalSaveReceipt(book.id,id),null);await assert.rejects(world.recordWorldRepairSaved(book.id,id,{requestKey:randomUUID(),authorWriteRequestKey:randomUUID()}));assert.equal(calls,1);});
  await t.test('no-op source updates preserve report history; formal specification change marks the original report stale',async()=>{
   await db.query('UPDATE new_design.cards SET status=status WHERE id=$1',[input.cardIds[0]]);assert.equal((await world.getWorldConsistencyResult(book.id,result.id)).status,'succeeded');
   const field=(await db.query("SELECT id FROM new_design.field_definitions WHERE space_id=$1 AND card_type_id=(SELECT card_type_id FROM new_design.cards WHERE id=$2) AND field_key='notes' AND status='active' LIMIT 1",[book.spaceId,input.cardIds[0]])).rows[0];assert.ok(field);await db.query("UPDATE new_design.field_definitions SET status='archived',revision=revision+1 WHERE id=$1",[field.id]);assert.equal((await world.getWorldConsistencyResult(book.id,result.id)).status,'stale');assert.equal(calls,1);
  });
 });await fixture.authorUnchanged();t.diagnostic(`retained isolated schema ${fixture.schema}; real model not called; provider reply is a controlled fetch stub`);
 });
