const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {isolatedDatabase,compiled}=require('./support/isolatedDatabase.cjs');const key=()=>randomUUID();
test('manual frozen world packages and normal independent installations preserve canonical ownership, history and unknown commits',async t=>{
 const {pool,database}=await isolatedDatabase(t,[{id:'084_world_packages',fileName:'084_world_packages.sql'}]);t.diagnostic(`World package database retained: ${database}`);
 const worlds=compiled('server/database/worldPackages'),store=compiled('server/database/store'),templates=compiled('server/database/templateStore'),contract=compiled('common/worldPackages');
 assert.deepEqual(await worlds.getWorldPackageCapability(),{installed:true,operational:false});
 let sourceType=(await store.listCardTypes()).find(type=>type.key==='world_rule');assert.ok(sourceType);
 const dictionaryId=(await pool.query("SELECT id FROM new_design.dictionary_definitions WHERE scope='system' AND status='published' ORDER BY id LIMIT 1")).rows[0].id;
 sourceType=await store.updateCardType(sourceType.id,{name:sourceType.name,description:sourceType.description,semanticCapabilities:sourceType.semanticCapabilities,revision:sourceType.revision,fields:[...sourceType.draftFields,...[['wp_count','number'],['wp_flag','boolean']].map(([fieldKey,type],index)=>({key:fieldKey,name:fieldKey,description:'',type,required:false,defaultValue:null,options:[],group:'档案',order:900+index,aiSuggestible:false,stateSettlement:'none'})),{key:'wp_tree',name:'世界包字典',description:'',type:'multi_select',required:false,defaultValue:null,options:[],group:'档案',order:902,aiSuggestible:false,stateSettlement:'none',optionSource:{kind:'dictionary_tree',dictionaryId,settleOnChapter:false,rule:{mode:'multiple',rootNodeId:null,depthMode:'whole_tree',relativeDepth:null,leafOnly:false,allowParentSelection:true,showFullPath:true,allowInlineCreate:false,aiSuggestible:false,minSelections:0,maxSelections:null}}}]});sourceType=await store.publishCardType(sourceType.id,sourceType.revision);
 let template=await templates.saveTemplate({key:`wp_${key().replaceAll('-','')}`,name:'世界包隔离模板',description:'',draftConfig:{},requestKey:key()});template=await templates.publishTemplate(template.id,template.revision,key());
 const books=await Promise.all([1,2].map(number=>templates.createBook({key:`wp_${key().replaceAll('-','')}`,name:`世界隔离书${number}`,description:'',templateVersionId:template.currentVersionId})));
 const source=await store.createCard({cardTypeId:sourceType.id,spaceId:contract.PUBLIC_WORLD_SPACE_ID,title:'公共固定世界',values:{era:'隔离测试时代',world_summary:'公共固定世界',wp_count:0,wp_flag:false}}),sourceVersion=(await store.listCardVersions(source.id))[0];
 const input={requestKey:key(),rootCardId:source.id,rootVersionId:sourceVersion.id,cards:[{cardId:source.id,versionId:sourceVersion.id,section:'profile'}],relationVersionIds:[]};
 await assert.rejects(worlds.previewWorldPackage(input),error=>error.status===503);await pool.query("UPDATE new_design.world_package_capability SET operational=true WHERE contract='public_world_package_v1'");
 const foundation=async()=>Object.fromEntries(await Promise.all(['entity_initial_states','state_changes','canonical_facts','knowledge_state_proposals','current_knowledge_state_projections','card_relations','chapter_body_versions','chapter_settlements','ai_generation_batches','ai_tasks'].map(async table=>[table,(await pool.query(`SELECT coalesce(jsonb_agg(to_jsonb(row) ORDER BY to_jsonb(row)::text),'[]'::jsonb) data FROM new_design.${table} row`)).rows[0].data]))),before=await foundation();
 const preview=await worlds.previewWorldPackage(input);assert.equal(preview.frame.cards[0].versionId,sourceVersion.id);assert.deepEqual(preview.frame.cards[0].values,source.values);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.world_package_versions')).rows[0].n,0);
 assert.equal(preview.frame.dictionaries[0].id,dictionaryId);assert.ok(preview.frame.dictionaries[0].nodes.length);
 await assert.rejects(worlds.previewWorldPackage({...input,rootVersionId:key()}),error=>error.status===422);
 const commit={...input,previewHash:preview.previewHash},published=await worlds.publishWorldPackage(commit),again=await worlds.publishWorldPackage(commit);assert.equal(again.package.id,published.package.id);assert.equal(again.repeated,true);assert.deepEqual((await worlds.readPublishedWorldPackage(published.package.id)).frame,preview.frame);
 await assert.rejects(worlds.readWorldPackageOriginal({...commit,cards:[{...commit.cards[0],section:'rules'}]}),error=>error.mutationOutcome==='unknown');
 // Database enforcement rejects an absent/null snapshot and a valid frame missing refs.
 const hash=compiled('server/database/formAssist').formHash;
 for(const corrupt of [true,false]){const db=await pool.connect();try{await db.query('BEGIN');const requestKey=key(),id=key(),raw={...commit,requestKey},frame=structuredClone(preview.frame);if(corrupt)frame.cards[0].title=null;const frameHash=hash(frame),inputHash=hash({scope:'public',input:raw}),receipt={requestKey,inputHash,input:raw,package:{...published.package,id,version:2,frame,frameHash},repeated:false};const insert=()=>db.query('INSERT INTO new_design.world_package_versions(id,root_card_id,root_version_id,version,frame,frame_hash,request_key,input_hash,input,receipt) VALUES($1,$2,$3,2,$4::jsonb,$5,$6,$7,$8::jsonb,$9::jsonb)',[id,source.id,sourceVersion.id,JSON.stringify(frame),frameHash,requestKey,inputHash,JSON.stringify(raw),JSON.stringify(receipt)]);if(corrupt)await assert.rejects(insert(),error=>error.code==='23514');else{await insert();await assert.rejects(db.query('COMMIT'),error=>error.code==='23514');}}finally{await db.query('ROLLBACK');db.release();}}
 // Frozen references protect exact history; ordinary editing still creates a new version.
 await assert.rejects(pool.query("UPDATE new_design.card_versions SET title='篡改固定版本' WHERE id=$1",[sourceVersion.id]),error=>error.code==='23514');
 await assert.rejects(pool.query("UPDATE new_design.card_type_versions SET fields='[]'::jsonb WHERE id=$1",[sourceVersion.typeVersionId]),error=>error.code==='23514');
 await assert.rejects(pool.query("UPDATE new_design.dictionary_item_versions SET label='篡改字典历史' WHERE id=$1",[preview.frame.dictionaries[0].nodes[0].versionId]),error=>error.code==='23514');
 await assert.rejects(pool.query("UPDATE new_design.world_package_versions SET frame_hash=repeat('a',64) WHERE id=$1",[published.package.id]),error=>error.code==='23514');
 const newSource=await store.updateCard(source.id,{title:'公共后来版本',values:{...source.values,world_summary:'公共后来版本'},revision:source.revision});assert.equal(newSource.revision,2);assert.equal((await worlds.readPublishedWorldPackage(published.package.id)).frame.cards[0].title,'公共固定世界');
 const installations=[];
 for(const book of books){
  const target=(await store.listCardTypes(book.spaceId)).find(type=>type.key==='world_rule'),item={sourceCardId:source.id,requestKey:key(),targetTypeId:target.id,title:'同名私有世界',mapping:Object.entries(source.values).map(([sourceKey,value])=>({sourceKey,targetKey:sourceKey,value})),additionalValues:{}},installInput={requestKey:key(),packageId:published.package.id,cards:[item],relations:[],syncEnabled:true};
  const localSame=await store.createCard({cardTypeId:target.id,spaceId:book.spaceId,title:'同名私有世界',values:{era:'独立时代',world_summary:'人工独立资料'}}),localBefore=await store.getCard(localSame.id);
  if(item.mapping.length)await assert.rejects(worlds.previewWorldInstallation(book.id,{...installInput,cards:[{...item,mapping:item.mapping.slice(1)}]}),error=>error.status===422);
  const installPreview=await worlds.previewWorldInstallation(book.id,installInput),installCommit={input:installInput,previewHash:installPreview.previewHash},installed=await worlds.installWorldPackage(book.id,installCommit);installations.push(installed);
  assert.notEqual(installed.cards[0].targetCardId,source.id);assert.notEqual(installed.cards[0].targetCardId,localSame.id);assert.deepEqual(await store.getCard(localSame.id),localBefore);assert.equal((await store.getCard(installed.cards[0].targetCardId)).values.world_summary,'公共固定世界');assert.equal((await worlds.installWorldPackage(book.id,installCommit)).installationId,installed.installationId);assert.equal((await worlds.readWorldInstallationOriginal(book.id,installCommit)).installationId,installed.installationId);
  const normal=await store.getCard(installed.cards[0].targetCardId);assert.equal(normal.values.wp_count,0);assert.equal(normal.values.wp_flag,false);
  await assert.rejects(worlds.readWorldInstallationOriginal(book.id,{...installCommit,input:{...installCommit.input,syncEnabled:false}}),error=>error.mutationOutcome==='unknown');
 }
 assert.notEqual(installations[0].cards[0].targetCardId,installations[1].cards[0].targetCardId);assert.deepEqual(await foundation(),before);
 // Canonical whole original-query loss is unknown, even with a definite rollback.
 const originalConnect=pool.connect.bind(pool);pool.connect=async(...args)=>{if(args.length)return originalConnect(...args);const db=await originalConnect(),query=db.query.bind(db),release=db.release.bind(db);db.query=(...params)=>String(params[0]).startsWith('SELECT input_hash,receipt FROM new_design.world_package_versions')?Promise.reject(new Error('isolated original lookup unavailable')):query(...params);db.release=(...args)=>{db.query=query;release(...args);};return db;};try{await assert.rejects(worlds.publishWorldPackage(commit),error=>error.mutationOutcome==='unknown');}finally{pool.connect=originalConnect;}
 assert.equal((await worlds.readWorldPackageOriginal(commit)).package.id,published.package.id);
 // A real successful COMMIT with a lost acknowledgement retains one complete package.
 const lostInput={...input,requestKey:key()},lostPreview=await worlds.previewWorldPackage(lostInput),lostCommit={...lostInput,previewHash:lostPreview.previewHash},connect=pool.connect.bind(pool);let lost=true;
 pool.connect=async(...args)=>{if(args.length)return connect(...args);const db=await connect(),query=db.query.bind(db),release=db.release.bind(db);db.query=async(...params)=>{const result=await query(...params);if(params[0]==='COMMIT'&&lost){lost=false;throw new Error('lost world COMMIT reply');}return result;};db.release=(...args)=>{db.query=query;release(...args);};return db;};
 try{await assert.rejects(worlds.publishWorldPackage(lostCommit),error=>error.mutationOutcome==='unknown');}finally{pool.connect=connect;}
 const recovered=await worlds.readWorldPackageOriginal(lostCommit);assert.ok(recovered);assert.equal((await worlds.publishWorldPackage(lostCommit)).package.id,recovered.package.id);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.world_package_versions WHERE request_key=$1',[lostInput.requestKey])).rows[0].n,1);
 const lostInstallInput={...installations[1].input.input,requestKey:key(),cards:installations[1].input.input.cards.map(item=>({...item,requestKey:key()}))},lostInstallPreview=await worlds.previewWorldInstallation(books[1].id,lostInstallInput),lostInstallCommit={input:lostInstallInput,previewHash:lostInstallPreview.previewHash};lost=true;
 pool.connect=async(...args)=>{if(args.length)return connect(...args);const db=await connect(),query=db.query.bind(db),release=db.release.bind(db);db.query=async(...params)=>{const result=await query(...params);if(params[0]==='COMMIT'&&lost){lost=false;throw new Error('lost installation COMMIT reply');}return result;};db.release=(...args)=>{db.query=query;release(...args);};return db;};try{await assert.rejects(worlds.installWorldPackage(books[1].id,lostInstallCommit),error=>error.mutationOutcome==='unknown');}finally{pool.connect=connect;}
 const recoveredInstall=await worlds.readWorldInstallationOriginal(books[1].id,lostInstallCommit);assert.ok(recoveredInstall);assert.equal((await worlds.installWorldPackage(books[1].id,lostInstallCommit)).installationId,recoveredInstall.installationId);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.world_package_installations WHERE book_id=$1 AND request_key=$2',[books[1].id,lostInstallInput.requestKey])).rows[0].n,1);
 // Failure after normal creation but before complete mapping rolls back both.
 const target=(await store.listCardTypes(books[0].spaceId)).find(type=>type.key==='world_rule'),rollbackInput={requestKey:key(),packageId:published.package.id,cards:[{sourceCardId:source.id,requestKey:key(),targetTypeId:target.id,title:'失败前资料',mapping:Object.entries(source.values).map(([sourceKey,value])=>({sourceKey,targetKey:sourceKey,value})),additionalValues:{}}],relations:[],syncEnabled:false},rollbackPreview=await worlds.previewWorldInstallation(books[0].id,rollbackInput),rollbackCommit={input:rollbackInput,previewHash:rollbackPreview.previewHash};
 pool.connect=async(...args)=>{if(args.length)return connect(...args);const db=await connect(),query=db.query.bind(db),release=db.release.bind(db);db.query=(...params)=>String(params[0]).startsWith('INSERT INTO new_design.world_package_install_card_refs')?Promise.reject(new Error('isolated mapping failure')):query(...params);db.release=(...args)=>{db.query=query;release(...args);};return db;};try{await assert.rejects(worlds.installWorldPackage(books[0].id,rollbackCommit),error=>error.mutationOutcome==='not_written');}finally{pool.connect=connect;}
 assert.equal(await worlds.readWorldInstallationOriginal(books[0].id,rollbackCommit),null);assert.equal((await pool.query('SELECT count(*)::integer n FROM new_design.card_versions WHERE author_book_id=$1 AND author_request_key=$2',[books[0].id,rollbackInput.cards[0].requestKey])).rows[0].n,0);
 // Disabled source protection cannot be treated as a usable installation.
 await pool.query('ALTER TABLE new_design.card_versions DISABLE TRIGGER world_package_card_history_guard');assert.equal((await worlds.getWorldPackageCapability()).operational,false);await assert.rejects(worlds.previewWorldPackage({...input,requestKey:key()}),error=>error.status===503);await pool.query('ALTER TABLE new_design.card_versions ENABLE TRIGGER world_package_card_history_guard');
 // An actual private type revision change invalidates the full reviewed install.
 const staleInput={...rollbackInput,requestKey:key(),cards:rollbackInput.cards.map(item=>({...item,requestKey:key()}))},stalePreview=await worlds.previewWorldInstallation(books[0].id,staleInput);let privateType=await store.getCardType(target.id);privateType=await store.updateCardType(privateType.id,{name:privateType.name,description:privateType.description,semanticCapabilities:privateType.semanticCapabilities,revision:privateType.revision,fields:[...privateType.draftFields,{key:'wp_extra',name:'本书额外背景',description:'',type:'long_text',required:false,defaultValue:null,options:[],group:'档案',order:999,aiSuggestible:false,stateSettlement:'none'}]});await store.publishCardType(privateType.id,privateType.revision);await assert.rejects(worlds.installWorldPackage(books[0].id,{input:staleInput,previewHash:stalePreview.previewHash}),error=>error.mutationOutcome==='not_written'&&error.status===409);
 // The full HTTP router keeps original reads separate from archived-book writes.
 const express=require('express'),app=express();app.use(express.json());app.use('/api/new-design',compiled('server/http/router').createNewDesignRouter());const http=app.listen(0,'127.0.0.1');await new Promise(resolve=>http.once('listening',resolve));t.after(()=>new Promise(resolve=>http.close(resolve)));const base=`http://127.0.0.1:${http.address().port}/api/new-design`,send=(route,input)=>fetch(base+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}),metadata=async()=>Object.fromEntries(await Promise.all(['world_package_versions','world_package_card_refs','world_package_installations','world_package_install_card_refs','cards','card_versions'].map(async table=>[table,(await pool.query(`SELECT count(*)::integer n FROM new_design.${table}`)).rows[0].n]))),readBefore=await metadata();
 assert.equal((await fetch(base+'/world-packages/capability')).status,200);assert.equal((await fetch(base+`/world-packages/${published.package.id}`)).status,200);assert.equal((await send('/world-packages/preview',input)).status,200);assert.equal((await send('/world-packages/original-receipt',commit)).status,200);assert.equal((await send(`/books/${books[0].id}/world-packages/original-receipt`,installations[0].input)).status,200);const mismatch=await send('/world-packages/original-receipt',{...commit,rootVersionId:key()});assert.equal(mismatch.status,409);assert.equal((await mismatch.json()).recovery.mutationOutcome,'unknown');assert.deepEqual(await metadata(),readBefore);
 await compiled('server/database/bookshelf').changeBookLifecycle(books[0].id,{action:'archive',expectedRevision:(await pool.query('SELECT revision FROM new_design.books WHERE id=$1',[books[0].id])).rows[0].revision});assert.equal((await send(`/books/${books[0].id}/world-packages/original-receipt`,installations[0].input)).status,200);assert.equal((await send(`/books/${books[0].id}/world-packages/install`,installations[0].input)).status,409);assert.deepEqual(await metadata(),readBefore);
 await pool.query("UPDATE new_design.world_package_capability SET operational=false WHERE contract='public_world_package_v1'");assert.equal((await worlds.readWorldPackageOriginal(commit)).package.id,published.package.id);assert.equal((await worlds.readWorldInstallationOriginal(books[0].id,installations[0].input)).installationId,installations[0].installationId);assert.deepEqual(await foundation(),before);
 const backup=await require('./support/worldPackageBackup.cjs').verifyWorldPackageBackup(t,pool,database);assert.equal(backup.outcome,'restored_and_verified');
});
