const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {compiled}=require('./support/isolatedDatabase.cjs'),contract=compiled('common/worldPackages');
test('three-way world fields retain absent, null, empty, zero and false, with structural equality',()=>{
 const fields=contract.worldThreeWayFields({zero:0,flag:false,n:null,empty:'',same:{z:1,a:2},conflict:'base',local:'old',upstream:'old',both:'base',removed:'yes'},{zero:0,flag:false,n:null,empty:'',same:{a:2,z:1},conflict:'local',local:'new',upstream:'old',both:'new'},{zero:0,flag:false,n:null,empty:'',same:{z:1,a:2},conflict:'public',local:'old',upstream:'new',both:'new',removed:null});
 const by=Object.fromEntries(fields.map(field=>[field.key,field]));for(const key of ['zero','flag','n','empty','same'])assert.equal(by[key].status,'unchanged');assert.equal(by.conflict.status,'conflict');assert.equal(by.local.status,'local_only');assert.equal(by.upstream.status,'upstream_only');assert.equal(by.both.status,'converged');assert.equal(by.removed.status,'conflict');assert.deepEqual(by.removed.local,{present:false});assert.deepEqual(by.removed.upstream,{present:true,value:null});
});
test('package and install requests reject unknown scope, duplicate identities and reused normal save keys',()=>{
 const id=randomUUID(),version=randomUUID(),requestKey=randomUUID(),input={requestKey,rootCardId:id,rootVersionId:version,cards:[{cardId:id,versionId:version,section:'profile'}],relationVersionIds:[]};assert.ok(contract.worldPackageInputSchema.safeParse(input).success);for(const altered of [{...input,bookId:randomUUID()},{...input,cards:[...input.cards,input.cards[0]]},{...input,cards:[{...input.cards[0],section:'猜测概要'}]}])assert.equal(contract.worldPackageInputSchema.safeParse(altered).success,false);
 const item={sourceCardId:id,requestKey:randomUUID(),targetTypeId:randomUUID(),title:'独立世界',mapping:[{sourceKey:'a',targetKey:'b',value:false}],additionalValues:{}},install={requestKey,packageId:randomUUID(),cards:[item],relations:[],syncEnabled:true};assert.ok(contract.worldInstallInputSchema.safeParse(install).success);for(const altered of [{...install,cards:[item,item]},{...install,cards:[{...item,requestKey}]},{...install,cards:[{...item,mapping:[{sourceKey:'a',targetKey:'b'}]}]}])assert.equal(contract.worldInstallInputSchema.safeParse(altered).success,false);
});
