import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {constants} from 'node:fs';
import {mkdir,lstat,realpath,open,link,unlink} from 'node:fs/promises';
import {z} from 'zod';
import {creativeSavedOutputSchema} from '../../../common/creativeExtraction';
import {stableHash} from '../../database/aiContracts';
import {CreativeExtractionError} from '../../database/creativeExtraction';
import {sanitizeChapterProductionExecutionReceipt} from '../../ai/chapterProductionReceipts';
const appRoot=path.resolve(__dirname,'../../../..'),root=path.join(appRoot,'data','ai-receipts','creative-extraction'),limit=16*1024*1024;
const uuid=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/),references=z.object({bookId:uuid,previewId:uuid,attemptId:uuid,planHash:hash}).strict();
const evidenceSchema=references.extend({output:creativeSavedOutputSchema,execution:z.record(z.string(),z.unknown()),outputHash:hash,executionHash:hash,evidenceHash:hash}).strict();
export type CreativeEvidence=z.infer<typeof evidenceSchema>;
const samePath=(left:string,right:string)=>process.platform==='win32'?left.toLowerCase()===right.toLowerCase():left===right;
async function directory(bookId:string,create:boolean){references.shape.bookId.parse(bookId);let current=appRoot;for(const component of ['',...path.relative(appRoot,root).split(path.sep),bookId]){if(component)current=path.join(current,component);if(create&&component)try{await mkdir(current,0o700);}catch(error){if(!(error&&typeof error==='object'&&'code' in error&&error.code==='EEXIST'))throw error;}let info;try{info=await lstat(current);}catch(error){if(!create&&error&&typeof error==='object'&&'code' in error&&error.code==='ENOENT')return null;throw error;}if(!info.isDirectory()||info.isSymbolicLink()||!samePath(await realpath(current),current))throw new Error('Invalid evidence directory');}return current;}
function validate(value:unknown,expected:z.infer<typeof references>){const record=evidenceSchema.parse(value),{evidenceHash,...payload}=record,execution=sanitizeChapterProductionExecutionReceipt(record.execution);if(stableHash(execution)!==record.executionHash||stableHash(payload)!==evidenceHash||stableHash(record.output)!==record.outputHash||stableHash(record.execution)!==record.executionHash||Object.entries(expected).some(([key,value])=>record[key as keyof typeof expected]!==value))throw new Error('Evidence identity differs');return record;}
export async function readCreativeEvidence(raw:z.infer<typeof references>):Promise<CreativeEvidence|null>{const expected=references.parse(raw);try{const dir=await directory(expected.bookId,false);if(!dir)return null;const target=path.join(dir,`${expected.previewId}-${expected.attemptId}.json`);let info;try{info=await lstat(target);}catch(error){if(error&&typeof error==='object'&&'code' in error&&error.code==='ENOENT')return null;throw error;}if(!info.isFile()||info.isSymbolicLink()||info.nlink!==1||info.size<1||info.size>limit)throw new Error('Invalid evidence file');const file=await open(target,constants.O_RDONLY|constants.O_NOFOLLOW);try{const current=await file.stat();if(current.dev!==info.dev||current.ino!==info.ino||current.size!==info.size||current.nlink!==1)throw new Error('Evidence changed');const bytes=Buffer.alloc(current.size);let offset=0;while(offset<bytes.length){const next=await file.read(bytes,offset,bytes.length-offset,offset);if(!next.bytesRead)throw new Error('Incomplete evidence');offset+=next.bytesRead;}const after=await file.stat();if(after.size!==current.size||after.mtimeMs!==current.mtimeMs)throw new Error('Evidence changed');return validate(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)),expected);}finally{await file.close();}}catch{throw new CreativeExtractionError('原回复本地凭证暂未读取，原输入和领取保留；只读核对，不重新调用模型。',503,'读取原创作提炼回复凭证','unknown',expected.bookId);}}
async function syncDirectory(dir:string){if(process.platform==='win32')return;const handle=await open(dir,constants.O_RDONLY|constants.O_NOFOLLOW);try{await handle.sync();}finally{await handle.close();}}
export async function writeCreativeEvidence(raw:z.infer<typeof references>,output:z.infer<typeof creativeSavedOutputSchema>,execution:Record<string,unknown>){const expected=references.parse(raw),payload={...expected,output:creativeSavedOutputSchema.parse(output),execution,outputHash:stableHash(output),executionHash:stableHash(execution)},record=validate({...payload,evidenceHash:stableHash(payload)},expected),bytes=Buffer.from(JSON.stringify(record),'utf8');if(bytes.length>limit)throw new CreativeExtractionError('完整回复凭证超过保存范围；原领取保留，不能截断回复冒充成功。',422,'保留原创作提炼回复','unknown',expected.bookId);let temporary:string|null=null;try{const prior=await readCreativeEvidence(expected);if(prior){if(prior.evidenceHash!==record.evidenceHash)throw new Error('Original evidence differs');return prior;}const dir=await directory(expected.bookId,true);if(!dir)throw new Error('Evidence directory missing');const target=path.join(dir,`${expected.previewId}-${expected.attemptId}.json`),pending=path.join(dir,`pending-${randomUUID()}.tmp`);temporary=pending;const file=await open(pending,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{await file.writeFile(bytes);await file.sync();}finally{await file.close();}await directory(expected.bookId,false);try{await link(pending,target);}catch(error){if(!(error&&typeof error==='object'&&'code' in error&&error.code==='EEXIST'))throw error;}await unlink(pending);temporary=null;await syncDirectory(dir);const saved=await readCreativeEvidence(expected);if(!saved||saved.evidenceHash!==record.evidenceHash)throw new Error('Evidence not acknowledged');return saved;}catch(error){if(error instanceof CreativeExtractionError)throw error;throw new CreativeExtractionError('原模型已返回，但回复凭证保存尚未确认；保留原请求核对，不重新调用模型。',503,'保留原创作提炼回复','unknown',expected.bookId);}finally{if(temporary)await unlink(temporary).catch(()=>{/* Only the exclusive temporary file, never original evidence. */});}}
