import {insertContractRecord} from "../aiContracts/records";
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {CharacterAuthorPromptInput} from '../../../common/characterAuthor';
import {preparePrompt} from '../../ai/prompts';
import {configurationForConnection} from '../../ai';
import {resolveManagedTaskRoute,captureManagedModelSnapshot,getManagedCredentialEnvironment} from '../modelManagement';
import {stableHash} from '../aiContracts';
import {NewDesignError} from '../../domain/errors';
export async function freezeCharacterAuthor(client:PoolClient,id:string,input:CharacterAuthorPromptInput){
 const prompt=preparePrompt('character_author',input),route=await resolveManagedTaskRoute('character_dialogue',{client});
 if(route.policy.maxRetries!==0||route.fallbacks.length)throw new NewDesignError('人物谈话需要单次原请求，请关闭人物对话路线的自动重试和备用连接。',422);
 await configurationForConnection(route.primary,route.policy,{credentialResolver:(id,provider)=>getManagedCredentialEnvironment(id,provider,{client})});
 const recipeId=randomUUID(),recipeVersionId=randomUUID(),contractId=randomUUID(),contractVersionId=randomUUID(),manifestId=randomUUID(),key=`character_author_${id}`,schema={type:'object',const:input},variables={...schema,'x-character-author':{contract:'character_author_v1',requestId:id,sourceHash:input.source.hash}};
 await client.query("INSERT INTO new_design.prompt_recipes(id,recipe_key,name,description) VALUES($1,$2,'人物谈话与场景分析','单个人物对作者；仅推断候选')",[recipeId,key]);
 await client.query("INSERT INTO new_design.prompt_recipe_versions(id,recipe_id,version,source,status,variables_schema,content_hash,created_by) VALUES($1,$2,1,'system','draft',$3::jsonb,$4,'character_author')",[recipeVersionId,recipeId,JSON.stringify(variables),stableHash({variables,messages:prompt.messages})]);
 await client.query("UPDATE new_design.prompt_recipe_versions SET status='published' WHERE id=$1",[recipeVersionId]);await client.query('UPDATE new_design.prompt_recipes SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1',[recipeId,recipeVersionId]);
 await client.query("INSERT INTO new_design.task_contracts(id,task_key,name,description) VALUES($1,$2,'人物谈话与场景分析','不改变正式认知、状态或正文')",[contractId,key]);
 await client.query(`INSERT INTO new_design.task_contract_versions(id,contract_id,version,source,status,task_group,input_schema,input_schema_version,output_schema,output_schema_version,context_policy_version,prompt_recipe_version_id,required_capabilities,budget_policy,timeout_ms,retry_policy,confirmation_policy,content_hash,created_by) VALUES($1,$2,1,'system','draft','character_dialogue',$3::jsonb,$4,$5::jsonb,$6,$7,$8,ARRAY['structured_output'],$9::jsonb,600000,'{"maxAttempts":1,"automaticRetry":false}'::jsonb,'before_adopt',$10,'character_author')`,[contractVersionId,contractId,JSON.stringify(schema),stableHash(schema),JSON.stringify(prompt.outputSchema),stableHash(prompt.outputSchema),prompt.contextPolicy,recipeVersionId,JSON.stringify({assetId:prompt.assetId,assetVersion:prompt.version,maxOutputTokens:prompt.maxTokens,temperature:prompt.temperature}),stableHash({schema,outputSchema:prompt.outputSchema,recipeVersionId})]);
 await client.query("UPDATE new_design.task_contract_versions SET status='published' WHERE id=$1",[contractVersionId]);await client.query('UPDATE new_design.task_contracts SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1',[contractId,contractVersionId]);
 for(const[kind,entity,version]of [['prompt_recipe',recipeId,recipeVersionId],['task_contract',contractId,contractVersionId]])await insertContractRecord(client,"ai_contract_publication",{id:randomUUID(),entity_kind:kind,entity_id:entity,to_version_id:version,entity_revision:2,action:"publish",actor:"character_author",idempotency_key:`${key}_${kind}`,from_version_id:null});
 const snapshot=await captureManagedModelSnapshot('character_dialogue',route,{client},{bookId:input.input.bookId,taskContractVersionId:contractVersionId});
 await client.query("INSERT INTO new_design.context_manifests(id,book_id,task_contract_version_id,prompt_recipe_version_id,node_key,status,manifest_hash,created_by,task_group,model_route_snapshot_id,source_set_hash,decision_summary) VALUES($1,$2,$3,$4,'character_author','complete',$5,'character_author','character_dialogue',$6,$7,$8::jsonb)",[manifestId,input.input.bookId,contractVersionId,recipeVersionId,stableHash(input),snapshot.id,input.source.hash,JSON.stringify({contract:'character_author_v1',cardId:input.input.cardId,cutoffBodyVersionId:input.input.cutoffBodyVersionId,kind:input.input.kind,historyKeys:input.input.historyKeys})]);
 const slotId=randomUUID();await insertContractRecord(client,"context_manifest_slot",{id:slotId,manifest_id:manifestId,slot_key:"character_author_sources",sort_order:0,required:true,token_budget:null});
 const primaryRefs=[{kind:'card_version',stableId:input.input.cardId,versionId:String(input.source.data.profile.versionId),sourceType:'card_version'},...input.source.data.relations.flatMap(item=>[{kind:'card_relation',stableId:String(item.id),versionId:String(item.versionId),sourceType:'card_relation'},{kind:'card_version',stableId:String(item.sourceId),versionId:String(item.sourceVersionId),sourceType:'card_version'},{kind:'card_version',stableId:String(item.targetId),versionId:String(item.targetVersionId),sourceType:'card_version'}]),...input.source.data.chapters.map(item=>({kind:'chapter_body_version',stableId:String(item.documentId),versionId:String(item.bodyVersionId),sourceType:'body_version'})),...input.source.data.states.map(item=>({kind:item.kind==='initial'?'entity_initial_state':'state_change',stableId:String(item.stableId),versionId:String(item.versionId),sourceType:item.kind==='initial'?'entity_initial_state':'state_change'})),...input.source.data.knowledge.map(item=>({kind:'knowledge_state_change',stableId:String(item.stableId),versionId:String(item.versionId),sourceType:'knowledge_state_change'}))];
 const refs=[...new Map(primaryRefs.map(ref=>[`${ref.kind}:${ref.stableId}:${ref.versionId}`,ref])).values()];
 for(const[order,ref]of refs.entries()){const resolved=(await client.query('SELECT resolved_hash FROM new_design.resolve_dependency_resource($1,$2,$3) WHERE resolved_book_id=$4',[ref.kind,ref.stableId,ref.versionId,input.input.bookId])).rows[0];if(!resolved)throw new NewDesignError('人物谈话原版本未能精确解析，停止生成，不用当前或他书来源代替。',409);await client.query("INSERT INTO new_design.context_manifest_items(id,manifest_id,slot_id,source_type,stable_object_id,exact_version_id,content_hash,inclusion_reason,priority,token_estimate,transform_status,sort_order,content_role,layer_label) VALUES($1,$2,$3,$4,$5,$6,$7,'本人当前档案及明确截至正文／确认来源',0,$9,'full',$8,'required','人物谈话来源')",[randomUUID(),manifestId,slotId,ref.sourceType,ref.stableId,ref.versionId,resolved.resolved_hash,order,Math.ceil(JSON.stringify(input.source.data).length/3/refs.length)]);}
 return{promptInput:input,route,contractVersionId,recipeVersionId,manifestId,snapshotId:snapshot.id,snapshotHash:snapshot.snapshotHash,inputHash:stableHash(input),outputSchemaVersion:stableHash(prompt.outputSchema),timeoutMs:route.policy.timeoutMs};
}
