import {z} from 'zod';
import type {PoolClient} from 'pg';
import type {CharacterResourceLedger,ResourceLedgerSelection,ResourceBackfillChapter} from '../../../common/characterResources';
import {stableHash} from '../aiContracts';
import {assertFound,NewDesignError} from '../../domain/errors';
import {getNewDesignPool} from '../runtime';
import {readSettlementRelationConfigurationInTransaction} from '../chapterSettlement';
import {readProfessionalObjectsInTransaction,readProfessionalState,professionalFields,professionalDisplay} from '../worldCharacterMaintenance';

export const resourceLedgerQuerySchema=z.object({relationTypeId:z.string().uuid().optional(),holdingDimensionKey:z.string().min(1).max(100).optional(),specificationHash:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict().refine(input=>[input.relationTypeId,input.holdingDimensionKey,input.specificationHash].filter(value=>value!==undefined).length%3===0,'请选择完整的持有关系和状态维度。');
type Query=z.infer<typeof resourceLedgerQuerySchema>;
export async function readCharacterResourcesInTransaction(db:PoolClient,bookId:string,characterId:string,input:Query={}):Promise<CharacterResourceLedger>{
 const config=await readSettlementRelationConfigurationInTransaction(db,bookId);
 const character=assertFound((await db.query("SELECT card.* FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id WHERE card.id=$1 AND card.space_id=$2 AND card.status='active' AND card.current_version_id IS NOT NULL AND type.type_key='character' AND type.status='published'",[characterId,config.spaceId])).rows[0],'人物不属于本书当前可用档案。');
 const choices=config.published.filter(type=>!type.unavailableReason&&type.definition.direction==='directed'&&type.definition.sourceTypeKeys.includes('character')&&type.definition.targetTypeKeys.includes('prop')&&type.definition.capability!=='disabled'&&type.definition.mode!=='none').flatMap(type=>type.definition.dimensions.filter(dimension=>dimension.policy!=='derived'&&dimension.mode!=='derived'&&type.definition.fields.some(field=>field.key===dimension.fieldKey&&!field.hidden)).map(dimension=>({relationTypeId:type.id,holdingDimensionKey:dimension.fieldKey,specificationHash:stableHash({bookId,relationTypeId:type.id,relationTypeRevision:type.revision,definition:type.definition,dimension}),name:type.name,holdingLabel:dimension.label,relationTypeRevision:type.revision,fields:type.definition.fields})));
 const choice=input.relationTypeId?choices.find(choice=>choice.relationTypeId===input.relationTypeId&&choice.holdingDimensionKey===input.holdingDimensionKey):null;
 if(input.relationTypeId&&(!choice||choice.specificationHash!==input.specificationHash))throw new NewDesignError('所选持有关系、状态维度或规格已变化，请保留原选择并重新核对；未自动改选其他关系。',409);
 const selection:ResourceLedgerSelection|null=choice?{relationTypeId:choice.relationTypeId,holdingDimensionKey:choice.holdingDimensionKey,specificationHash:choice.specificationHash}:null;
 const rows=choice?(await db.query(`SELECT relation.*,type.name type_label,type.status type_status,type.properties_schema,source.title source_label,target.title target_label,
 version.id exact_version_id,target.current_version_id resource_version_id,
 (version.revision=relation.revision AND version.status=relation.status AND version.properties=relation.properties AND source_snapshot.id IS NOT NULL AND target_snapshot.id IS NOT NULL) version_valid
 FROM new_design.card_relations relation JOIN new_design.relation_types type ON type.id=relation.relation_type_id
 JOIN new_design.cards source ON source.id=relation.source_card_id AND source.space_id=relation.space_id AND source.status='active'
 JOIN new_design.cards target ON target.id=relation.target_card_id AND target.space_id=relation.space_id AND target.status='active' AND target.current_version_id IS NOT NULL
 JOIN new_design.card_types target_type ON target_type.id=target.card_type_id AND target_type.type_key='prop' AND target_type.status='published'
 LEFT JOIN new_design.card_relation_versions version ON version.id=relation.current_version_id AND version.card_relation_id=relation.id
 LEFT JOIN new_design.card_versions source_snapshot ON source_snapshot.id=version.source_card_version_id AND source_snapshot.card_id=source.id
 LEFT JOIN new_design.card_versions target_snapshot ON target_snapshot.id=version.target_card_version_id AND target_snapshot.card_id=target.id
 WHERE relation.space_id=$1 AND relation.source_card_id=$2 AND relation.relation_type_id=$3 AND relation.status='active'
 ORDER BY target.title,relation.id LIMIT 201`,[config.spaceId,characterId,choice.relationTypeId])).rows:[];
 const visible=rows.slice(0,200),subjectIds=[characterId,...visible.flatMap(row=>[String(row.id),String(row.target_card_id)])],read=await readProfessionalObjectsInTransaction(db,config.spaceId,characterId,[characterId,...visible.map(row=>String(row.target_card_id))]);
 const objectLabels=new Map(read.objects.map(object=>[object.id,object.title]));
 const nodes=(await db.query(`SELECT item.dictionary_id,item.id,version.label FROM new_design.dictionary_items item JOIN new_design.dictionary_definitions definition ON definition.id=item.dictionary_id JOIN new_design.dictionary_item_versions version ON version.id=item.current_version_id AND version.item_id=item.id WHERE item.status='active' AND version.status='active' AND definition.status='published' AND (definition.owner_space_id IS NULL OR definition.owner_space_id=$1)`,[config.spaceId])).rows;
 const dictionaryLabels=new Map<string,string>(nodes.map(row=>[`${row.dictionary_id}:${row.id}`,String(row.label)])),states=await readProfessionalState(db,bookId,read.objects,visible,objectLabels,dictionaryLabels,subjectIds);
 const items=visible.map(row=>({relationId:String(row.id),relationVersionId:row.exact_version_id?String(row.exact_version_id):null,revision:Number(row.revision),resourceId:String(row.target_card_id),resourceVersionId:String(row.resource_version_id),name:String(row.target_label),holderName:String(character.title),available:row.version_valid===true&&row.type_status==='published',reason:row.version_valid===true&&row.type_status==='published'?null:'持有关系的正式版本或规格无效，请在原关系中核对。',holding:states.items.find(state=>state.id===`relation:${row.id}:${choice!.holdingDimensionKey}`)??null,properties:professionalFields(row.properties_schema).map(field=>({key:field.key,label:field.name,display:professionalDisplay(row.properties?.[field.key],field,objectLabels,dictionaryLabels)})),states:states.items.filter(state=>state.subjectId===row.id||state.subjectId===row.target_card_id),sourceRoute:`/new-design/books/${bookId}/story-setting?tab=characters&selected=${characterId}&detail=relations&relation=${row.id}`}));
 const pending=(await db.query(`SELECT count(*)::integer n FROM new_design.chapter_settlement_items item JOIN new_design.chapter_adoption_sessions session ON session.id=item.session_id JOIN new_design.chapter_documents document ON document.id=session.chapter_document_id AND document.adopted_version_id=session.body_version_id AND document.status='active' JOIN new_design.state_change_proposals proposal ON proposal.id=item.state_proposal_id AND proposal.book_id=session.book_id AND proposal.chapter_document_id=document.id AND proposal.body_version_id=session.body_version_id WHERE session.book_id=$1 AND item.decision IN('pending','defer') AND proposal.subject_id=ANY($2::uuid[]) AND session.status IN('adopted_pending_proposals','pending_review','partially_confirmed','failed')`,[bookId,visible.flatMap(row=>[row.id,row.target_card_id])])).rows[0];
 const chapters=(await db.query(`SELECT document.*,body.id body_version_id,body.content_hash,session.id session_id,session.revision session_revision,session.status session_status
 FROM new_design.chapter_documents document JOIN new_design.chapter_body_versions body ON body.id=document.adopted_version_id AND body.chapter_document_id=document.id AND body.archived_at IS NULL
 LEFT JOIN LATERAL(SELECT session.* FROM new_design.chapter_adoption_sessions session WHERE session.chapter_document_id=document.id AND session.book_id=document.book_id AND session.body_version_id=body.id AND session.status<>'cancelled' ORDER BY session.created_at DESC,session.id DESC LIMIT 1) session ON true
 WHERE document.book_id=$1 AND document.status='active' ORDER BY document.logical_order DESC,document.id DESC LIMIT 5`,[bookId])).rows;
 const anchors=(await db.query("SELECT * FROM new_design.chapter_text_anchors WHERE book_id=$1 AND body_version_id=ANY($2::uuid[]) AND status='active' AND subject_card_id=ANY($3::uuid[]) ORDER BY chapter_document_id,start_offset,id",[bookId,chapters.map(chapter=>chapter.body_version_id),[characterId,...visible.map(row=>row.target_card_id)]])).rows;
 const recentChapters:ResourceBackfillChapter[]=chapters.map(chapter=>({documentId:String(chapter.id),chapterCardId:String(chapter.chapter_card_id),title:String(chapter.title),logicalOrder:Number(chapter.logical_order),bodyVersionId:String(chapter.body_version_id),bodyContentHash:String(chapter.content_hash),sessionId:chapter.session_id?String(chapter.session_id):null,sessionRevision:chapter.session_revision?Number(chapter.session_revision):null,sessionStatus:chapter.session_status??null,sourceRoute:`/new-design/books/${bookId}/writing?chapterDocument=${chapter.id}${chapter.session_id?`&session=${chapter.session_id}`:''}`,anchors:anchors.filter(anchor=>anchor.body_version_id===chapter.body_version_id&&anchor.chapter_document_id===chapter.id).map(anchor=>({id:String(anchor.id),subjectCardId:anchor.subject_card_id?String(anchor.subject_card_id):null,start:Number(anchor.start_offset),end:Number(anchor.end_offset),excerpt:String(anchor.excerpt)})),unavailableReason:!chapter.session_id?'尚无对应的结果确认会话，请在原章节准备采用确认。':['adopted_pending_proposals','pending_review','partially_confirmed','failed'].includes(chapter.session_status)?null:chapter.session_status==='stable'?'本章已稳定结算；补充变化需先核对下游影响，不能直接重开或改写历史。':'原结算会话当前不可编辑，请返回原章节核对。'}));
 return{bookId,characterId,characterVersionId:String(character.current_version_id),characterRevision:Number(character.revision),characterName:String(character.title),choices,selection,items,pendingCount:Number(pending?.n??0),recentChapters,truncated:rows.length>200||read.truncated||states.truncated};
}
export async function getCharacterResources(bookId:string,characterId:string,input:Query={}):Promise<CharacterResourceLedger>{
 z.string().uuid().parse(bookId);z.string().uuid().parse(characterId);const parsed=resourceLedgerQuerySchema.parse(input),db=await(await getNewDesignPool()).connect();
 try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const result=await readCharacterResourcesInTransaction(db,bookId,characterId,parsed);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}
}

export {freezeResourceBackfillScope,verifyFrozenResourceBackfillScope} from "./backfillScope";
