import type {SettlementRelationDefinition,SettlementPublishedRelation,SettlementRelationConfigurationWorkspace,SettlementRelationDraft} from "../../common/chapterSettlementEditing";
export interface RelationEditorDraft {draftId:string|null;revision:number|null;versionId:string|null;relationTypeId:string|null;sourceRelationTypeId:string|null;sourceRevision:number|null;definition:SettlementRelationDefinition;}
export function emptyRelationDefinition():SettlementRelationDefinition{return {name:"",description:"",direction:"directed",sourceTypeKeys:[],targetTypeKeys:[],sourceMax:null,targetMax:null,fields:[],capability:"optional",mode:"relation_state",dimensions:[]};}
export function copyRelationDefinition(value:SettlementRelationDefinition):SettlementRelationDefinition{return {...value,sourceTypeKeys:[...value.sourceTypeKeys],targetTypeKeys:[...value.targetTypeKeys],fields:value.fields.map(field=>({...field,options:field.options.map(option=>({...option})),defaultValue:Array.isArray(field.defaultValue)?[...field.defaultValue]:field.defaultValue,visibleWhen:field.visibleWhen?{...field.visibleWhen}:undefined,optionSource:field.optionSource?.kind==="dictionary_tree"?{...field.optionSource,rule:{...field.optionSource.rule}}:field.optionSource?{...field.optionSource}:undefined})),dimensions:value.dimensions.map(item=>({...item}))};}
export function emptyRelationEditor():RelationEditorDraft{return {draftId:null,revision:null,versionId:null,relationTypeId:null,sourceRelationTypeId:null,sourceRevision:null,definition:emptyRelationDefinition()};}
export function fromPublished(value:SettlementPublishedRelation,workspace:SettlementRelationConfigurationWorkspace):RelationEditorDraft{return {...emptyRelationEditor(),relationTypeId:value.ownerSpaceId===workspace.spaceId&&value.editable?value.id:null,sourceRelationTypeId:value.ownerSpaceId===workspace.spaceId&&value.editable?null:value.id,sourceRevision:value.revision,definition:copyRelationDefinition(value.definition)};}
export function fromSaved(value:SettlementRelationDraft):RelationEditorDraft{return {draftId:value.id,revision:value.revision,versionId:value.versionId,relationTypeId:value.relationTypeId,sourceRelationTypeId:value.sourceRelationTypeId,sourceRevision:value.expectedRelationTypeRevision,definition:copyRelationDefinition(value.definition)};}
export function sameRelationDefinition(left:SettlementRelationDefinition,right:SettlementRelationDefinition):boolean{return JSON.stringify(left)===JSON.stringify(right);}
export function relationDefinitionIssues(value:SettlementRelationDefinition):Record<string,string>{const issues:Record<string,string>={};if(!value.name.trim())issues.name="请填写关系名称。";if(!value.sourceTypeKeys.length)issues.sourceTypeKeys="请选择来源类型。";if(!value.targetTypeKeys.length)issues.targetTypeKeys="请选择目标类型。";const seen=new Set<string>();value.fields.forEach((field,index)=>{if(!field.name.trim())issues[`fields.${index}.name`]="请填写中文属性名称。";if(seen.has(field.key))issues[`fields.${index}.key`]="属性标识重复，请重新添加属性。";seen.add(field.key);});const dimensions=new Set<string>();value.dimensions.forEach((item,index)=>{const field=value.fields.find(field=>field.key===item.fieldKey);if(!field)issues[`dimensions.${index}.fieldKey`]="请选择对应属性。";if(!item.label.trim())issues[`dimensions.${index}.label`]="请填写中文维度名称。";if(dimensions.has(item.fieldKey))issues[`dimensions.${index}.fieldKey`]="同一属性只配置一次结算维度。";dimensions.add(item.fieldKey);if(item.mode==="delta"&&field?.type!=="number")issues[`dimensions.${index}.mode`]="变化量只支持数字属性。";});return issues;}
export function relationIssueLabel(key:string):string {const labels:Record<string,string>={name:"关系名称",sourceTypeKeys:"来源类型",targetTypeKeys:"目标类型",fields:"关系属性",dimensions:"结算维度",definition:"关系规格",draftId:"已保存草稿",expectedRevision:"草稿修订",expectedRelationTypeRevision:"正式来源修订",confirmPublish:"发布确认",confirmInstanceRebind:"本书实例切换确认",rebindRelations:"影响关系范围",createRelations:"新建关系范围"};const parts=key.split(".").filter(part=>part!=="definition");return labels[parts[0]]??"关系配置";}
export function relationSource(params:URLSearchParams):{bookId:string;returnRoute:string|null;invalid:boolean}{const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,bookId=params.get("book")??"",documentId=params.get("chapterDocument"),sessionId=params.get("session");if(bookId&&!uuid.test(bookId)||documentId&&!uuid.test(documentId)||sessionId&&!uuid.test(sessionId))return {bookId:"",returnRoute:null,invalid:true};if(documentId||sessionId){if(!bookId||!documentId||!sessionId)return {bookId,returnRoute:null,invalid:true};return {bookId,returnRoute:`/new-design/books/${bookId}/writing?chapterDocument=${documentId}&session=${sessionId}`,invalid:false};}return {bookId,returnRoute:null,invalid:false};}
