import type {RelationEditorDraft} from "./editing";
export interface RelationPendingRecovery {kind:"save"|"publish";key:string;notWritten:boolean;}
export interface RelationStoredRecovery {version:1;bookId:string;draft:RelationEditorDraft;baseline:string;pending:RelationPendingRecovery|null;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==="object"&&!Array.isArray(value);
const text=(value:unknown)=>typeof value==="string"&&value.length<=10000;
const integer=(value:unknown)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>=0;
const nullableId=(value:unknown)=>value===null||typeof value==="string"&&uuid.test(value);
const nullablePositive=(value:unknown)=>value===null||integer(value)&&Number(value)>0;
const scalar=(value:unknown)=>value===null||typeof value==="string"||typeof value==="boolean"||typeof value==="number"&&Number.isFinite(value);
function rule(value:unknown):boolean {if(!object(value))return false;return ["single","multiple","cascade_single","cascade_multiple"].includes(String(value.mode))&&["whole_tree","branch","direct_children","descendants","relative_depth"].includes(String(value.depthMode))&&nullableId(value.rootNodeId)&&nullablePositive(value.relativeDepth)&&["leafOnly","allowParentSelection","showFullPath","allowInlineCreate","aiSuggestible"].every(key=>typeof value[key]==="boolean")&&integer(value.minSelections)&&(value.maxSelections===null||integer(value.maxSelections));}
function field(value:unknown):boolean {if(!object(value))return false;if(!["key","name","description","group"].every(key=>text(value[key]))||!integer(value.order)||typeof value.required!=="boolean"||!["short_text","long_text","number","boolean","date","select","multi_select"].includes(String(value.type))||!Array.isArray(value.options)||value.options.length>100||!value.options.every(option=>object(option)&&text(option.value)&&text(option.label)&&(option.id===undefined||typeof option.id==="string"))||!(scalar(value.defaultValue)||Array.isArray(value.defaultValue)&&value.defaultValue.length<=100&&value.defaultValue.every(scalar)))return false;
  if(value.stateSettlement!==undefined&&!["none","tracked","lifecycle"].includes(String(value.stateSettlement)))return false;
  if(!["hidden","aiSuggestible"].every(key=>value[key]===undefined||typeof value[key]==="boolean")||value.standardFieldId!==undefined&&!nullableId(value.standardFieldId))return false;
  if(value.visibleWhen!==undefined&&(!object(value.visibleWhen)||!text(value.visibleWhen.fieldKey)||!["equals","not_equals","is_empty","is_not_empty","includes"].includes(String(value.visibleWhen.operator))||value.visibleWhen.value!==undefined&&!scalar(value.visibleWhen.value)))return false;
  if(value.optionSource!==undefined){const source=value.optionSource;if(!object(source))return false;if(source.kind!=="inline"&&(source.kind!=="dictionary_tree"||typeof source.dictionaryId!=="string"||!uuid.test(source.dictionaryId)||!rule(source.rule)||typeof source.settleOnChapter!=="boolean"))return false;}return true;
}
function definition(value:unknown):boolean {return object(value)&&text(value.name)&&text(value.description)&&["directed","undirected"].includes(String(value.direction))&&["disabled","optional","required"].includes(String(value.capability))&&["none","relation_state","lifecycle"].includes(String(value.mode))&&nullablePositive(value.sourceMax)&&nullablePositive(value.targetMax)&&[value.sourceTypeKeys,value.targetTypeKeys].every(items=>Array.isArray(items)&&items.length<=100&&items.every(text))&&Array.isArray(value.fields)&&value.fields.length<=50&&value.fields.every(field)&&Array.isArray(value.dimensions)&&value.dimensions.length<=50&&value.dimensions.every(item=>object(item)&&text(item.fieldKey)&&text(item.label)&&["forward","inverse","bidirectional"].includes(String(item.direction))&&["tracked","derived","lifecycle_only"].includes(String(item.policy))&&["absolute","delta","derived","lifecycle"].includes(String(item.mode)));}
export function readRelationRecovery(bookId:string):RelationStoredRecovery|null {try{if(!uuid.test(bookId))return null;const raw=sessionStorage.getItem(`new-design:relation-configuration:v1:${bookId}`);if(!raw||raw.length>500000)return null;const value=JSON.parse(raw);if(!object(value)||value.version!==1||value.bookId!==bookId||!object(value.draft)||typeof value.baseline!=="string"||!definition(JSON.parse(value.baseline))||!definition(value.draft.definition))return null;const draft=value.draft;if(![draft.draftId,draft.versionId,draft.relationTypeId,draft.sourceRelationTypeId].every(nullableId)||![draft.revision,draft.sourceRevision].every(nullablePositive))return null;const pending=value.pending;if(pending!==null&&(!object(pending)||!["save","publish"].includes(String(pending.kind))||typeof pending.key!=="string"||!uuid.test(pending.key)||typeof pending.notWritten!=="boolean"))return null;return value as unknown as RelationStoredRecovery;}catch{return null;}}
export function writeRelationRecovery(value:RelationStoredRecovery|null,bookId:string):boolean {try{if(!uuid.test(bookId)||value&&value.bookId!==bookId)return false;const key=`new-design:relation-configuration:v1:${bookId}`;if(value)sessionStorage.setItem(key,JSON.stringify(value));else sessionStorage.removeItem(key);return true;}catch{return false;}}
