import {randomUUID} from "node:crypto";
import type {CreateKnowledgeProfileInput,KnowledgeProfileReceipt} from "../../../common/knowledgeIndex";
import type {PoolClient} from "pg";
import {readManagedEmbeddingConnectionVersion} from "../modelManagement";
import {stableHash} from "../aiContracts";
import {NewDesignError} from "../../domain/errors";
import {indexTransaction,indexOriginalRead,OriginalKnowledgeRequestConflict} from "./repository";
import {createKnowledgeProfileSchema} from "./policy";
async function receipt(client:PoolClient,bookId:string,key:string,repeated=true):Promise<KnowledgeProfileReceipt|null>{const rows=(await client.query("SELECT * FROM new_design.embedding_profile_versions WHERE knowledge_profile_key=$1 AND knowledge_profile_book_id=$2",[key,bookId])).rows;if(rows.length>1)throw new NewDesignError("原嵌入规格请求出现重复来源，请保留原标识核对。",409);const row=rows[0];return row?{requestKey:key,inputHash:String(row.knowledge_profile_hash),profileId:String(row.profile_id),profileVersionId:String(row.id),connectionVersionId:String(row.connection_version_id),repeated,mutationOutcome:"committed"}:null;}
export async function getKnowledgeProfileByKey(bookId:string,key:string){return indexOriginalRead(bookId,key,async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`knowledge_profile:${key}`]);return receipt(client,bookId,key);});}
export async function createKnowledgeProfile(bookId:string,value:CreateKnowledgeProfileInput){const input=createKnowledgeProfileSchema.parse(value),hash=stableHash({contract:"knowledge_profile_v1",bookId,input});return indexTransaction(bookId,input.requestKey,"保存知识嵌入规格","not_sent",async(client,markAbsent)=>{await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`knowledge_profile:${input.requestKey}`]);const prior=await receipt(client,bookId,input.requestKey);if(prior){if(prior.inputHash!==hash)throw new OriginalKnowledgeRequestConflict(bookId,"同一原请求不能保存不同嵌入规格或用于另一部书。");return prior;}if((await client.query("SELECT id FROM new_design.embedding_profile_versions WHERE knowledge_profile_key=$1",[input.requestKey])).rowCount)throw new OriginalKnowledgeRequestConflict(bookId,"原规格请求属于另一部书，请核对原来源。");markAbsent();if(!(await client.query("SELECT id FROM new_design.books WHERE id=$1 AND status='active'",[bookId])).rowCount)throw new NewDesignError("此书不存在或已归档。",409);const connection=await readManagedEmbeddingConnectionVersion(input.connectionVersionId,{client});if(connection.maxRetries!==0)throw new NewDesignError("首次知识嵌入仅支持单次请求，请在原向量配置明确设为不自动重试。",422);if(connection.model.length>160)throw new NewDesignError("模型标识超过原嵌入规格支持的长度，请明确配置兼容模型版本。",422);const id=randomUUID(),versionId=randomUUID();await client.query("INSERT INTO new_design.embedding_profiles(id,profile_key,name,purpose,created_by) VALUES($1,$2,$3,'semantic_retrieval','knowledge-index-user')",[id,`knowledge.${id}`,input.name]);await client.query("INSERT INTO new_design.embedding_profile_versions(id,profile_id,version,provider_key,model_key,dimensions,distance_metric,normalize,chunker_key,chunker_version,max_chunk_chars,overlap_chars,allowed_source_kinds,content_hash,created_by,connection_version_id,knowledge_profile_key,knowledge_profile_hash,knowledge_profile_book_id) VALUES($1,$2,1,$3,$4,$5,$6,$7,'knowledge.characters','v1',$8,$9,ARRAY['asset_parsed_text'],$10,'knowledge-index-user',$11,$12,$13,$14)",[versionId,id,connection.provider,connection.model,input.dimensions,input.distanceMetric,input.normalize,input.maxChunkChars,input.overlapChars,stableHash({...input,provider:connection.provider,model:connection.model,connectionHash:connection.connectionHash}),connection.id,input.requestKey,hash,bookId]);await client.query("UPDATE new_design.embedding_profiles SET current_version_id=$2 WHERE id=$1",[id,versionId]);return{requestKey:input.requestKey,inputHash:hash,profileId:id,profileVersionId:versionId,connectionVersionId:connection.id,repeated:false,mutationOutcome:"committed" as const};});}
