import type {PoolClient} from "pg";
import {knowledgePool} from "../knowledgeReference";
import {NewDesignError} from "../../domain/errors";
export class KnowledgeEmbeddingError extends NewDesignError {
 readonly recovery:{failedStep:string;summary:string;savedResult:string;actionLabel:string;sourceRoute:string;mutationOutcome:"not_written"|"unknown";modelRequestState:"not_sent"|"sent_unknown"|"completed"};
 constructor(bookId:string,step:string,message:string,outcome:"not_written"|"unknown",state:"not_sent"|"sent_unknown"|"completed",status=503){super(message,status);this.recovery={failedStep:step,summary:message,savedResult:state==="completed"?"原模型回复已经收到；已保留的回复与原索引事实不会被替代。":state==="sent_unknown"?"原请求与冻结版本保留；是否收到模型回复尚未确认，不能当作零用量或再次调用。":"尚未发送模型请求；原文件、规格与既有索引保留。",actionLabel:"返回知识参考",sourceRoute:`/new-design/knowledge?bookId=${bookId}`,mutationOutcome:outcome,modelRequestState:state};}
}
export class OriginalKnowledgeRequestConflict extends KnowledgeEmbeddingError {constructor(bookId:string,message:string){super(bookId,"核对已经存在的原请求",message,"unknown","not_sent",409);this.recovery.savedResult="本次未发送新的模型请求；已经存在的原请求与回执保留，不能据本次回滚认定原操作未写入或原模型未调用。";}}
export class KnowledgePreparationError extends KnowledgeEmbeddingError {readonly preparationNotWritten=true;constructor(bookId:string,step:string,message:string,status:number){super(bookId,step,message,"not_written","not_sent",status);this.recovery.savedResult="初始领取事务在提交前已确认回滚，尚未发送本次模型请求；原输入和已存在的资料保留，可明确重新准备。";}}
export async function lockIndex(client:PoolClient,bookId:string,key?:string){if(key)await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`knowledge_embedding_key:${bookId}:${key}`]);await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`knowledge_book:${bookId}`]);}
/** Only this pure DB transaction can prove an acknowledged rollback; never infer external send state from SQL errors. */
export async function indexTransaction<T>(bookId:string,key:string|undefined,step:string,state:"not_sent"|"sent_unknown"|"completed",action:(client:PoolClient,markOriginalPreparationAbsent:()=>void)=>Promise<T>,initialPreparation=false):Promise<T>{
 let client:PoolClient|undefined,committing=false,originalAbsentVerified=false;try{client=await(await knowledgePool()).connect();await client.query("BEGIN");await lockIndex(client,bookId,key);const result=await action(client,()=>{originalAbsentVerified=true;});committing=true;await client.query("COMMIT");return result;}catch(error){let rolledBack=false;if(client)try{await client.query("ROLLBACK");rolledBack=true;}catch{}const safe=Boolean(client)&&!committing&&rolledBack,wholeOperationNotWritten=safe&&originalAbsentVerified;if(error instanceof KnowledgeEmbeddingError)throw error;if(initialPreparation&&wholeOperationNotWritten)throw new KnowledgePreparationError(bookId,step,error instanceof NewDesignError?error.message:"初始模型领取已回滚，尚未发送请求。",error instanceof NewDesignError?error.status:503);
  throw new KnowledgeEmbeddingError(bookId,step,error instanceof NewDesignError?error.message:safe?"本次数据库事务已回滚；原操作是否此前已保存仍需核对，请保留原凭证。":"保存回执尚未确认；请只读核对原请求，不能自动重发模型。",wholeOperationNotWritten?"not_written":"unknown",state,error instanceof NewDesignError?error.status:503);
 }finally{client?.release();}
}
export async function indexRead<T>(action:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await(await knowledgePool()).connect();try{return await action(client);}finally{client.release();}}
/** The ACK of this read transaction says nothing about any earlier write/model request. */
export async function indexOriginalRead<T>(bookId:string,key:string,action:(client:PoolClient)=>Promise<T>):Promise<T>{return indexRead(async client=>{try{await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");await lockIndex(client,bookId,key);const value=await action(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK").catch(()=>undefined);const failure=new KnowledgeEmbeddingError(bookId,"只读核对原请求",error instanceof NewDesignError?error.message:"原请求查询暂不可用；这不证明原操作未写入，请保留原标识继续核对。","unknown","not_sent",error instanceof NewDesignError?error.status:503);failure.recovery.savedResult="此次只是读取原请求，没有发起新模型调用；查询失败或空结果不证明原操作未写入、未调用或已成功。";throw failure;}});}
