import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {DialoguePromptInput} from '../../../common/characterDialogue';
import type {ManagedTaskRoute} from '../../../common/modelRouting';
import {preparePrompt} from '../../ai/prompts';
import {configurationForConnection} from '../../ai/runtime/managedExecution';
import {resolveManagedTaskRoute,captureManagedModelSnapshot,getManagedCredentialEnvironment} from '../modelManagement';
import {stableHash} from '../aiContracts';
import {NewDesignError} from '../../domain/errors';
export interface DialogueFrozenPlan {input:DialoguePromptInput;inputHash:string;outputSchemaVersion:string;route:ManagedTaskRoute;contractVersionId:string;recipeVersionId:string;manifestId:string;snapshotId:string;snapshotHash:string;sourceHash:string;}
export async function freezeDialogue(client:PoolClient,bookId:string,roundId:string,sourceHash:string,input:DialoguePromptInput):Promise<DialogueFrozenPlan>{
 const original=(await client.query("SELECT resolved_hash AS content_hash FROM new_design.resolve_dependency_resource('card_version',$1,$2) WHERE resolved_book_id=$3",[input.actor.cardId,input.actor.cardVersionId,bookId])).rows[0];
 if(!original||typeof original.content_hash!=='string')throw new NewDesignError('原人物版本依赖凭证不存在，不用模拟表单的哈希冒充原档案。',409);
 const prompt=preparePrompt('character_dialogue',input),inputHash=stableHash(input),recipeId=randomUUID(),recipeVersionId=randomUUID(),contractId=randomUUID(),contractVersionId=randomUUID(),manifestId=randomUUID(),key=`character_dialogue_${roundId}`,schema={type:'object',const:input},variables={...schema,'x-character-dialogue':{bookId,roundId,sessionId:input.sessionId,checkpointId:input.checkpoint.id,sourceHash}};
 await client.query("INSERT INTO new_design.prompt_recipes(id,recipe_key,name,description) VALUES($1,$2,'人物对话模拟','一人一轮，仅本人私有历史来源与沙盘公开发言')",[recipeId,key]);await client.query("INSERT INTO new_design.prompt_recipe_versions(id,recipe_id,version,source,status,variables_schema,content_hash,created_by) VALUES($1,$2,1,'system','draft',$3::jsonb,$4,'character_dialogue')",[recipeVersionId,recipeId,JSON.stringify(variables),stableHash({variables,messages:prompt.messages})]);await client.query("UPDATE new_design.prompt_recipe_versions SET status='published' WHERE id=$1",[recipeVersionId]);await client.query('UPDATE new_design.prompt_recipes SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1',[recipeId,recipeVersionId]);
 await client.query("INSERT INTO new_design.ai_contract_publications(id,entity_kind,entity_id,to_version_id,entity_revision,action,actor,idempotency_key) VALUES($1,'prompt_recipe',$2,$3,2,'publish','character_dialogue',$4)",[randomUUID(),recipeId,recipeVersionId,`${key}_recipe`]);
 await client.query("INSERT INTO new_design.task_contracts(id,task_key,name,description) VALUES($1,$2,'人物对话模拟','非事实沙盘，动作明确选择后仅进原规划草稿')",[contractId,key]);await client.query(`INSERT INTO new_design.task_contract_versions(id,contract_id,version,source,status,task_group,input_schema,input_schema_version,output_schema,output_schema_version,context_policy_version,prompt_recipe_version_id,required_capabilities,budget_policy,timeout_ms,retry_policy,confirmation_policy,content_hash,created_by)
 VALUES($1,$2,1,'system','draft','character_dialogue',$3::jsonb,$4,$5::jsonb,$6,$7,$8,ARRAY['structured_output'],$9::jsonb,600000,'{"maxAttempts":1,"automaticRetry":false}'::jsonb,'before_adopt',$10,'character_dialogue')`,[contractVersionId,contractId,JSON.stringify(schema),stableHash(schema),JSON.stringify(prompt.outputSchema),stableHash(prompt.outputSchema),prompt.contextPolicy,recipeVersionId,JSON.stringify({assetId:prompt.assetId,assetVersion:prompt.version,maxOutputTokens:prompt.maxTokens,temperature:prompt.temperature}),stableHash({schema,outputSchema:prompt.outputSchema,recipeVersionId})]);await client.query("UPDATE new_design.task_contract_versions SET status='published' WHERE id=$1",[contractVersionId]);await client.query('UPDATE new_design.task_contracts SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1',[contractId,contractVersionId]);await client.query("INSERT INTO new_design.ai_contract_publications(id,entity_kind,entity_id,to_version_id,entity_revision,action,actor,idempotency_key) VALUES($1,'task_contract',$2,$3,2,'publish','character_dialogue',$4)",[randomUUID(),contractId,contractVersionId,`${key}_contract`]);
 const route=await resolveManagedTaskRoute('character_dialogue',{client});if(route.policy.maxRetries!==0||route.fallbacks.length)throw new NewDesignError('人物模拟仅支持单次原请求，请明确配置无自动重试／备用路线。',422);await configurationForConnection(route.primary,route.policy,{credentialResolver:(id,provider)=>getManagedCredentialEnvironment(id,provider,{client})});const snapshot=await captureManagedModelSnapshot('character_dialogue',route,{client},{bookId,taskContractVersionId:contractVersionId});
 await client.query("INSERT INTO new_design.context_manifests(id,book_id,task_contract_version_id,prompt_recipe_version_id,node_key,status,manifest_hash,created_by,task_group,model_route_snapshot_id,source_set_hash,decision_summary) VALUES($1,$2,$3,$4,'character_dialogue','complete',$5,'character_dialogue','character_dialogue',$6,$7,$8::jsonb)",[manifestId,bookId,contractVersionId,recipeVersionId,inputHash,snapshot.id,sourceHash,JSON.stringify({checkpointId:input.checkpoint.id,actorCardId:input.actor.cardId,privateKnowledge:'actor_only',publicRounds:input.publicRounds.map(r=>r.id)})]);const slotId=randomUUID();await client.query("INSERT INTO new_design.context_manifest_slots(id,manifest_id,slot_key,sort_order,required,token_budget) VALUES($1,$2,'actor_at_chapter',0,true,NULL)",[slotId,manifestId]);await client.query("INSERT INTO new_design.context_manifest_entries(id,manifest_id,slot_id,source_type,stable_object_id,exact_version_id,content_hash,inclusion_reason,priority,token_estimate,transform_status,sort_order,content_role,layer_label) VALUES($1,$2,$3,'card_version',$4,$5,$6,'本人截至章实际档案，不含未来当前替代',0,$7,'full',0,'required','人物本人历史档案')",[randomUUID(),manifestId,slotId,input.actor.cardId,input.actor.cardVersionId,original.content_hash,Math.ceil(JSON.stringify(input.actor).length/4)]);
 const references:Array<{sourceType:string;kind:string;stableId:string;versionId:string;label:string}>=[{sourceType:'body_version',kind:'chapter_body_version',stableId:input.checkpoint.chapterDocumentId,versionId:input.checkpoint.bodyVersionId,label:'截至章原正文'}];
 for(const state of input.states)references.push({sourceType:state.kind==='initial'?'entity_initial_state':'state_change',kind:state.kind==='initial'?'entity_initial_state':'state_change',stableId:state.stableObjectId,versionId:state.sourceVersionId,label:state.fieldLabel});
 for(const knowledge of input.knowledge)references.push({sourceType:'knowledge_state_change',kind:'knowledge_state_change',stableId:knowledge.proposalId,versionId:knowledge.id,label:knowledge.label});
 for(const [order,ref]of references.entries()){const source=(await client.query('SELECT resolved_hash FROM new_design.resolve_dependency_resource($1,$2,$3) WHERE resolved_book_id=$4',[ref.kind,ref.stableId,ref.versionId,bookId])).rows[0];if(!source)throw new NewDesignError('本人历史状态／认知／截至章原依赖无法精确解析，不冒充完整模型来源。',409);await client.query("INSERT INTO new_design.context_manifest_entries(id,manifest_id,slot_id,source_type,stable_object_id,exact_version_id,content_hash,inclusion_reason,priority,token_estimate,transform_status,sort_order,content_role,layer_label) VALUES($1,$2,$3,$4,$5,$6,$7,'本人当时精确原来源',0,0,'full',$8,'required',$9)",[randomUUID(),manifestId,slotId,ref.sourceType,ref.stableId,ref.versionId,String(source.resolved_hash),order+1,ref.label]);}
 await client.query("SELECT new_design.add_registered_dependency('chapter_settlement',$1,$2,'context_manifest',$3,$3,'context_included','hard','context_build',$3)",[input.checkpoint.chapterDocumentId,input.checkpoint.settlementId,manifestId]);
 return{input,inputHash,outputSchemaVersion:stableHash(prompt.outputSchema),route,contractVersionId,recipeVersionId,manifestId,snapshotId:snapshot.id,snapshotHash:snapshot.snapshotHash,sourceHash};
}
