import { randomUUID } from "node:crypto";
import type { BookResearchAdoptionBatch, BookResearchAdoptionItem } from "../../../common/contracts";
import { NewDesignError, assertFound } from "../../domain/errors";
import { stableHash } from "../aiContracts/integrity";
import { getNewDesignPool } from "../runtime";

type Row=Record<string,unknown>;
const iso=(value:unknown)=>value instanceof Date?value.toISOString():new Date(String(value)).toISOString();
const asObject=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
function mapItem(row:Row):BookResearchAdoptionItem{return{id:String(row.id),sourceCandidateId:String(row.source_candidate_id),targetTypeKey:String(row.target_type_key),title:String(row.title),values:asObject(row.values),evidenceIds:Array.isArray(row.evidence_ids)?row.evidence_ids.map(String):[],decision:row.decision as BookResearchAdoptionItem["decision"],targetCardId:row.target_card_id?String(row.target_card_id):null,revision:Number(row.revision),sortOrder:Number(row.sort_order)};}

async function sourceState(row:Row):Promise<{label:string;update:boolean}>{const pool=await getNewDesignPool();if(row.source_kind==="research_version"){const source=assertFound((await pool.query("SELECT record.title,record.current_version_id FROM new_design.research_record_versions version JOIN new_design.research_records record ON record.id=version.record_id WHERE version.id=$1",[row.source_id])).rows[0],"研究版本不存在。");return{label:String(source.title),update:String(source.current_version_id)!==String(row.source_id)};}const source=assertFound((await pool.query("SELECT pack.name,pack.current_version_id FROM new_design.research_reference_pack_versions version JOIN new_design.research_reference_packs pack ON pack.id=version.pack_id WHERE version.id=$1",[row.source_id])).rows[0],"参考包版本不存在。");return{label:String(source.name),update:String(source.current_version_id)!==String(row.source_id)};}
async function mapBatch(row:Row):Promise<BookResearchAdoptionBatch>{const pool=await getNewDesignPool(),items=(await pool.query("SELECT * FROM new_design.book_research_adoption_items WHERE batch_id=$1 ORDER BY sort_order,id",[row.id])).rows.map(mapItem),source=await sourceState(row);return{id:String(row.id),bookId:String(row.book_id),sourceKind:row.source_kind as BookResearchAdoptionBatch["sourceKind"],sourceId:String(row.source_id),sourceLabel:source.label,sourceSnapshot:asObject(row.source_snapshot),sourceUpdateAvailable:source.update,status:row.status as BookResearchAdoptionBatch["status"],revision:Number(row.revision),items,createdBy:String(row.created_by),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)};}

async function sourceCandidates(sourceKind:BookResearchAdoptionBatch["sourceKind"],sourceId:string,candidateIds?:string[]):Promise<{rows:Row[];snapshot:Record<string,unknown>}>{const pool=await getNewDesignPool();let rows:Row[],snapshot:Record<string,unknown>;if(sourceKind==="research_version"){const source=assertFound((await pool.query("SELECT version.id,version.version,version.run_hash,record.id record_id,record.title FROM new_design.research_record_versions version JOIN new_design.research_records record ON record.id=version.record_id WHERE version.id=$1 AND version.run_status IN ('completed','partial')",[sourceId])).rows[0],"只能采用已完成或部分完成的研究版本。");rows=(await pool.query("SELECT candidate.*,batch.research_version_id FROM new_design.research_candidates candidate JOIN new_design.research_candidate_batches batch ON batch.id=candidate.batch_id WHERE batch.research_version_id=$1 ORDER BY candidate.created_at,candidate.id",[sourceId])).rows;snapshot={kind:sourceKind,sourceId,recordId:String(source.record_id),label:String(source.title),version:Number(source.version),runHash:String(source.run_hash)};}else{const source=assertFound((await pool.query("SELECT version.id,version.version,version.note,pack.id pack_id,pack.name FROM new_design.research_reference_pack_versions version JOIN new_design.research_reference_packs pack ON pack.id=version.pack_id WHERE version.id=$1",[sourceId])).rows[0],"参考包版本不存在。"),rawRows=(await pool.query(`SELECT candidate.*,batch.research_version_id FROM new_design.research_reference_pack_items item JOIN new_design.research_candidate_batches batch ON batch.research_version_id=item.research_version_id JOIN new_design.research_candidates candidate ON candidate.batch_id=batch.id WHERE item.pack_version_id=$1 ORDER BY item.sort_order,candidate.created_at,candidate.id`,[sourceId])).rows;rows=[...new Map(rawRows.map(row=>[String(row.id),row])).values()];snapshot={kind:sourceKind,sourceId,packId:String(source.pack_id),label:String(source.name),version:Number(source.version),note:String(source.note??"")};}if(candidateIds?.length){const requested=new Set(candidateIds);rows=rows.filter(row=>requested.has(String(row.id)));if(rows.length!==requested.size)throw new NewDesignError("部分候选不属于所选研究版本。",422);}snapshot={...snapshot,candidateIds:rows.map(row=>String(row.id)),candidateHash:stableHash(rows.map(row=>({id:row.id,revision:row.revision,values:row.values})))};return{rows,snapshot};}

export async function createBookResearchAdoptionPreview(input:{bookId:string;sourceKind:BookResearchAdoptionBatch["sourceKind"];sourceId:string;candidateIds?:string[];idempotencyKey:string;createdBy?:string}):Promise<BookResearchAdoptionBatch>{const pool=await getNewDesignPool(),requestHash=stableHash({bookId:input.bookId,sourceKind:input.sourceKind,sourceId:input.sourceId,candidateIds:[...(input.candidateIds??[])].sort()}),existing=(await pool.query("SELECT * FROM new_design.book_research_adoption_batches WHERE book_id=$1 AND idempotency_key=$2",[input.bookId,input.idempotencyKey])).rows[0];if(existing){if(String(existing.request_hash)!==requestHash)throw new NewDesignError("幂等键对应另一份研究采用请求。",409);return mapBatch(existing);}const book=assertFound((await pool.query("SELECT id FROM new_design.books WHERE id=$1 AND status='active'",[input.bookId])).rows[0],"书籍不存在或已归档。"),source=await sourceCandidates(input.sourceKind,input.sourceId,input.candidateIds);if(!source.rows.length)throw new NewDesignError("该研究版本没有可采用的资料提案。",422);const client=await pool.connect(),id=randomUUID();try{await client.query("BEGIN");const row=(await client.query("INSERT INTO new_design.book_research_adoption_batches(id,book_id,source_kind,source_id,source_snapshot,idempotency_key,request_hash,created_by) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8) RETURNING *",[id,book.id,input.sourceKind,input.sourceId,JSON.stringify(source.snapshot),input.idempotencyKey,requestHash,input.createdBy??"user"])).rows[0];for(const [index,candidate] of source.rows.entries())await client.query("INSERT INTO new_design.book_research_adoption_items(id,batch_id,source_candidate_id,target_type_key,title,values,evidence_ids,sort_order,updated_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)",[randomUUID(),id,candidate.id,candidate.target_type_key,candidate.title,JSON.stringify(candidate.values??{}),candidate.evidence_ids??[],index,input.createdBy??"user"]);await client.query("INSERT INTO new_design.book_research_adoption_events(id,batch_id,action,detail,idempotency_key,actor) VALUES($1,$2,'preview',$3::jsonb,$4,$5)",[randomUUID(),id,JSON.stringify({sourceKind:input.sourceKind,sourceId:input.sourceId,candidateCount:source.rows.length}),input.idempotencyKey,input.createdBy??"user"]);await client.query("COMMIT");return mapBatch(row);}catch(error){await client.query("ROLLBACK");if((error as {code?:string}).code==="23505"){const repeated=(await pool.query("SELECT * FROM new_design.book_research_adoption_batches WHERE book_id=$1 AND idempotency_key=$2",[input.bookId,input.idempotencyKey])).rows[0];if(repeated&&String(repeated.request_hash)===requestHash)return mapBatch(repeated);}throw error;}finally{client.release();}}

export async function getBookResearchAdoptionBatch(id:string,bookId?:string):Promise<BookResearchAdoptionBatch>{const row=assertFound((await(await getNewDesignPool()).query("SELECT * FROM new_design.book_research_adoption_batches WHERE id=$1 AND ($2::uuid IS NULL OR book_id=$2)",[id,bookId??null])).rows[0],"研究采用预览不存在。");return mapBatch(row);}
export async function listBookResearchAdoptionBatches(bookId:string):Promise<BookResearchAdoptionBatch[]>{const rows=(await(await getNewDesignPool()).query("SELECT * FROM new_design.book_research_adoption_batches WHERE book_id=$1 ORDER BY updated_at DESC,id DESC LIMIT 50",[bookId])).rows,result:BookResearchAdoptionBatch[]=[];for(const row of rows)result.push(await mapBatch(row));return result;}

export async function reviseBookResearchAdoptionItem(id:string,input:{bookId:string;title:string;values:Record<string,unknown>;decision:BookResearchAdoptionItem["decision"];expectedRevision:number;actor?:string}):Promise<BookResearchAdoptionBatch>{const pool=await getNewDesignPool(),client=await pool.connect();try{await client.query("BEGIN");const item=assertFound((await client.query("SELECT item.*,batch.book_id,batch.status FROM new_design.book_research_adoption_items item JOIN new_design.book_research_adoption_batches batch ON batch.id=item.batch_id WHERE item.id=$1 FOR UPDATE OF item",[id])).rows[0],"研究提案不存在。");if(String(item.book_id)!==input.bookId)throw new NewDesignError("研究提案不属于当前书籍。",404);if(item.status!=="draft"||Number(item.revision)!==input.expectedRevision)throw new NewDesignError("研究提案已变化或不可编辑，请刷新。",409);await client.query("UPDATE new_design.book_research_adoption_items SET title=$2,values=$3::jsonb,decision=$4,revision=revision+1,updated_by=$5,updated_at=now() WHERE id=$1",[id,input.title,JSON.stringify(input.values),input.decision,input.actor??"user"]);await client.query("UPDATE new_design.book_research_adoption_batches SET revision=revision+1,updated_at=now() WHERE id=$1",[item.batch_id]);await client.query("INSERT INTO new_design.book_research_adoption_events(id,batch_id,action,detail,idempotency_key,actor) VALUES($1,$2,$3,$4::jsonb,$5,$6)",[randomUUID(),item.batch_id,input.decision==="pending"?"edit":"decide",JSON.stringify({itemId:id,decision:input.decision}),`item:${id}:${input.expectedRevision}`,input.actor??"user"]);await client.query("COMMIT");return getBookResearchAdoptionBatch(String(item.batch_id),input.bookId);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
