import {useCallback,useEffect,useRef,useState} from "react";
import {VISUAL_MAX_BYTES,VISUAL_MIME_TYPES,visualRoute,visualUploadSchema,visualCommandSchema,visualPreviewSchema,readVisualSelection,type VisualAssetsApi,type VisualWorkspace,type VisualAsset,type VisualVersion,type VisualUploadInput,type VisualCommand,type VisualPreviewInput,type VisualReceipt,type VisualImpactPreview} from "../../common/visualAssets";
import "./visual-assets.css";
import type {ImageGenerationApi} from "../../common/imageGeneration";
import {ImageGenerationPanel} from "../imageGeneration";

type Pending={kind:"upload";input:VisualUploadInput}|{kind:"command";input:VisualCommand}|{kind:"preview";input:VisualPreviewInput}|{kind:"read_only";bookId:string;requestKey:string;isPreview:boolean};
const STORAGE="new-design:visual-source-request:v1",UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const identity=(pending:Pending)=>pending.kind==="read_only"?pending:pending.input;
function restore():Pending|null{try{const value=JSON.parse(sessionStorage.getItem(STORAGE)??"null");if(!value||typeof value!=="object")return null;if(value.kind==="read_only"&&UUID.test(value.bookId)&&typeof value.requestKey==="string"&&value.requestKey.length>=8&&value.requestKey.length<=160&&typeof value.isPreview==="boolean")return value;for(const [kind,schema] of [["upload",visualUploadSchema],["command",visualCommandSchema],["preview",visualPreviewSchema]] as const){if(value.kind!==kind)continue;const parsed=schema.safeParse(value.input);if(parsed.success){if(kind==="upload")return{kind,input:visualUploadSchema.parse(parsed.data)};if(kind==="command")return{kind,input:visualCommandSchema.parse(parsed.data)};return{kind,input:visualPreviewSchema.parse(parsed.data)};}}const ref=value.input;if(ref&&typeof ref==="object"&&typeof ref.bookId==="string"&&UUID.test(ref.bookId)&&typeof ref.requestKey==="string"&&ref.requestKey.length>=8&&ref.requestKey.length<=160&&["upload","command","preview"].includes(value.kind))return{kind:"read_only",bookId:ref.bookId,requestKey:ref.requestKey,isPreview:value.kind==="preview"};return null;}catch{return null;}}
function unreadableMarker(){try{return Boolean(sessionStorage.getItem(STORAGE))&&!restore();}catch{return true;}}
function notWritten(error:unknown){return Boolean(error&&typeof error==="object"&&"recovery" in error&&error.recovery&&typeof error.recovery==="object"&&"mutationOutcome" in error.recovery&&error.recovery.mutationOutcome==="not_written");}
function sourceMessage(error:unknown){const names:Record<string,string>={bookId:"原书籍",assetId:"原图片",expectedRevision:"原图片修订",kind:"图片用途",title:"图片名称",description:"画面说明",filename:"本地文件名",mimeType:"图像格式",base64:"原图文件内容与大小",requestKey:"原请求凭证",versionId:"所选精确图片版本",previewId:"原影响预览",reason:"归档原因",ownerKind:"绑定目标类型",ownerStableId:"原绑定内容",ownerVersionId:"绑定内容精确版本",label:"绑定说明"};let locations:string[]=[];if(error&&typeof error==="object"&&"issues" in error){const issues=error.issues;if(Array.isArray(issues))locations=issues.flatMap(issue=>issue&&typeof issue==="object"&&"path" in issue&&Array.isArray(issue.path)&&names[String(issue.path[0])]?names[String(issue.path[0])]:[]);else if(issues&&typeof issues==="object")locations=Object.keys(issues).flatMap(key=>names[key]?[names[key]]:[]);}const message=error instanceof Error&&error.name==="ZodError"?"本地图片输入未符合规格，尚未提交原保存请求。":error instanceof Error&&error.message.length<=1000?error.message:"本次图片结果未确认；原文件、版本、填写及原凭证保留。";return message+(locations.length?` 需要修正位置：${[...new Set(locations)].join("、")}。`:"");}
const ownerKey=(owner:VisualWorkspace["owners"][number])=>`${owner.kind}:${owner.stableId}:${owner.versionId}`;
const stepOf=(pending:Pending)=>pending.kind==="preview"?"保存原图片影响预览":pending.kind==="upload"?"保存本地图像候选版本":pending.kind==="read_only"?"只读核对原图片凭证":pending.input.operation==="description"?"保存图片说明候选":pending.input.operation==="adopt"?"明确采用图片精确版本":pending.input.operation==="archive"?"归档原图片并保留引用":"绑定图片到精确正式版本";
const snapshot=(title:string,description:string)=>JSON.stringify({title,description});
function readFile(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("本地文件尚未完整读取，原文件保留，请重新选择。"));reader.onload=()=>{const result=reader.result;if(typeof result!=="string"||!result.includes(",")){reject(new Error("本地图片编码未完整读取。"));return;}resolve(result.slice(result.indexOf(",")+1));};reader.readAsDataURL(file);});}

export default function VisualAssetsPage({bookId,api,imageApi,selectionSearch,coverWorkbench=false,bookContext,onCloseGuardChange}:{bookId:string;api:VisualAssetsApi;imageApi?:ImageGenerationApi;selectionSearch?:string;coverWorkbench?:boolean;bookContext?:{name:string;description:string};onCloseGuardChange?:(state:{blocked:boolean;dirty:boolean})=>void}){
 const [imageGuard,setImageGuard]=useState({blocked:false,dirty:false}),[coverView,setCoverView]=useState<'gallery'|'generate'>('gallery');
 const scope=useRef(bookId),mounted=useRef(true),generation=useRef(0),initialized=useRef(false),selection=useRef(readVisualSelection(selectionSearch??window.location.search)),dirtyRef=useRef(false);
 const [workspace,setWorkspace]=useState<VisualWorkspace|null>(null),[assetId,setAssetId]=useState<string|null>(null),[versionId,setVersionId]=useState<string|null>(null),[creating,setCreating]=useState(false),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[baseline,setBaseline]=useState(snapshot("","")),[kind,setKind]=useState<"cover"|"illustration">("cover"),[file,setFile]=useState<File|null>(null),[search,setSearch]=useState(""),[archived,setArchived]=useState(false);
 const [pending,setPending]=useState<Pending|null>(restore),[storageIssue]=useState(unreadableMarker),[busy,setBusy]=useState(false),[error,setError]=useState(""),[step,setStep]=useState(""),[notice,setNotice]=useState(""),[lastReceipt,setLastReceipt]=useState<VisualReceipt|null>(null),[impact,setImpact]=useState<VisualImpactPreview|null>(null),[reason,setReason]=useState(""),[owner,setOwner]=useState(""),[label,setLabel]=useState(""),[imageFailed,setImageFailed]=useState(false),[imageRefresh,setImageRefresh]=useState(0),[switchTo,setSwitchTo]=useState<{assetId:string|null;versionId:string|null}|null>(null);
 const asset=workspace?.assets.find(item=>item.id===assetId)??null,version=asset?.versions.find(item=>item.id===versionId)??null,dirty=snapshot(title,description)!==baseline||Boolean(file)||Boolean(reason)||Boolean(label),scopeChanged=bookId!==scope.current;
 dirtyRef.current=dirty;
 const locked=busy||Boolean(pending)||scopeChanged||storageIssue,editable=creating||asset?.status==="active",pendingScope=pending?identity(pending):null;
 useEffect(()=>{onCloseGuardChange?.({blocked:locked||imageGuard.blocked,dirty:dirty||imageGuard.dirty});},[locked,dirty,imageGuard,onCloseGuardChange]);
 useEffect(()=>{if(!coverWorkbench)return;if(pending)setCoverView('gallery');else if(imageGuard.blocked)setCoverView('generate');},[coverWorkbench,pending,imageGuard.blocked]);
 const remember=(value:Pending|null)=>{setPending(value);try{value?sessionStorage.setItem(STORAGE,JSON.stringify(value)):sessionStorage.removeItem(STORAGE);}catch{if(value){const id=identity(value);try{sessionStorage.setItem(STORAGE,JSON.stringify({kind:"read_only",bookId:id.bookId,requestKey:id.requestKey,isPreview:value.kind==="preview"||value.kind==="read_only"&&value.isPreview}));}catch{/* The visible original key and in-memory full input remain. */}setNotice("浏览器容量不足，完整图片仅保留在当前页面；请记下原凭证，刷新后只读核对，不用重选文件替代原请求。");}}};
 const load=useCallback(async()=>{const token=++generation.current,next=await api.workspace(scope.current);if(!mounted.current||token!==generation.current)return null;if(next.bookId!==scope.current)throw new Error("返回图片目录不属于原书籍，未替换当前填写。");setWorkspace(next);return next;},[api]);
 const open=(item:VisualAsset|null,target:VisualVersion|null)=>{setAssetId(item?.id??null);setVersionId(target?.id??null);setCreating(!item);setKind(item?.kind??"cover");setTitle(target?.title??item?.title??"");setDescription(target?.description??"");setBaseline(snapshot(target?.title??item?.title??"",target?.description??""));setFile(null);setImpact(null);setReason("");setOwner("");setLabel("");setImageFailed(false);setError("");};
 useEffect(()=>{mounted.current=true;void load().then(next=>{if(!next||initialized.current)return;initialized.current=true;const selected=selection.current;if(!selected.valid){setStep("定位原图片版本");setError("原图片或版本凭证格式不正确，没有选择其他图片代替。");return;}if(!selected.assetId)return;const item=next.assets.find(candidate=>candidate.id===selected.assetId);if(!item){setStep("定位原图片");setError("指定图片不存在于本书已加载原资产列表，未选择其他图片代替。");return;}const target=selected.versionId?item.versions.find(candidate=>candidate.id===selected.versionId):item.versions.find(candidate=>candidate.id===item.currentVersionId)??item.versions[0];if(!target){setStep("定位原图片精确版本");setError("指定原版本没有读取到，不使用当前或其他版本替代。");return;}open(item,target);}).catch(error=>{setStep("读取本书原视觉资产");setError(sourceMessage(error));});return()=>{mounted.current=false;generation.current++;};},[load]);
 useEffect(()=>{const handle=(event:BeforeUnloadEvent)=>{if(dirty||pending){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handle);return()=>window.removeEventListener("beforeunload",handle);},[dirty,pending]);
 const choose=(nextAssetId:string|null,nextVersionId:string|null)=>{if(locked)return;if(dirtyRef.current){setSwitchTo({assetId:nextAssetId,versionId:nextVersionId});return;}if(!nextAssetId){open(null,null);return;}const item=workspace?.assets.find(candidate=>candidate.id===nextAssetId),target=item?.versions.find(candidate=>candidate.id===(nextVersionId??item?.currentVersionId))??(!nextVersionId?item?.versions[0]:undefined);if(!item||!target){setStep("选择原图片版本");setError("原选择不存在于当前目录，填写保留，不用其他版本代替。");return;}open(item,target);};
 const refresh=async()=>{if(busy)return;setBusy(true);try{await load();setNotice("原目录已只读刷新，当前名称、说明、本地文件与原请求保留；不会换成新当前版本。");}catch(error){setStep("只读刷新本书图片目录");setError(sourceMessage(error));}finally{setBusy(false);}};
 const acceptReceipt=async(result:VisualReceipt,original:Pending)=>{if(result.bookId!==identity(original).bookId||result.requestKey!==identity(original).requestKey)throw new Error("回执不属于同一原图片操作，保留原请求继续核对。");setLastReceipt(result);remember(null);setError("");setNotice(result.retainedResult);setImpact(null);try{const next=await load();if((original.kind==="upload"||original.kind==="command"&&original.input.operation==="description")&&result.bookId===scope.current){const item=next?.assets.find(candidate=>candidate.id===result.assetId),target=item?.versions.find(candidate=>candidate.id===result.versionId);if(item&&target)open(item,target);}else if(original.kind==="command"&&original.input.operation==="archive")setReason("");else if(original.kind==="command"&&original.input.operation==="mount")setLabel("");}catch(error){setStep("读取已保存回执后的原目录");setError(`原操作已保存，回执保留，不重复原操作。${sourceMessage(error)}`);}};
 const send=async(original:Exclude<Pending,{kind:"read_only"}>)=>original.kind==="upload"?api.upload(original.input):original.kind==="command"?api.command(original.input):api.preview(original.input);
 const resolve=async(original:Pending,result:VisualReceipt|VisualImpactPreview)=>{if("retainedResult" in result){await acceptReceipt(result,original);return;}if(result.bookId!==identity(original).bookId||original.kind==="preview"&&(result.assetId!==original.input.assetId||result.toVersionId!==original.input.toVersionId||result.revision!==original.input.expectedRevision))throw new Error("预览回执不属于同一原版本，原请求保持，未确认采用或归档。");setImpact(result);remember(null);setError("");setNotice("影响预览已保存，还没有采用或归档；核对下游引用后明确确认。");};
 const submit=async(original:Exclude<Pending,{kind:"read_only"}>)=>{if(locked)return;remember(original);setBusy(true);setStep(stepOf(original));setError("");try{await resolve(original,await send(original));}catch(error){setError(sourceMessage(error));if(notWritten(error)){remember(null);setNotice("本次数据库写入已确认回滚；原文件、当前填写与历史版本保留，可修正后明确重新提交。");}else setNotice("写入回执未确认，原输入和原凭证保持；只读核对，不换新凭证重复上传或绑定。");}finally{setBusy(false);}};
 const check=async()=>{if(!pending||busy)return;const original=pending,id=identity(original);setBusy(true);setStep("只读核对原图片操作凭证");try{const isPreview=original.kind==="preview"||original.kind==="read_only"&&original.isPreview,result=isPreview?await api.previewByKey(id.bookId,id.requestKey):await api.receipt(id.bookId,id.requestKey);if(result)await resolve(original,result);else setError("没有读取到原回执，不证明请求未提交；保留原凭证继续核对，未重新提交或生成。");}catch(error){setError(sourceMessage(error));}finally{setBusy(false);}};
 const completeOriginal=async()=>{if(!pending||pending.kind==="read_only"||busy)return;const original=pending,id=identity(original);let writeAttempted=false;setBusy(true);setStep("按原凭证核对并完成原图片数据库操作");try{const result=original.kind==="preview"?await api.previewByKey(id.bookId,id.requestKey):await api.receipt(id.bookId,id.requestKey);if(result){await resolve(original,result);return;}writeAttempted=true;await resolve(original,await send(original));}catch(error){setError(sourceMessage(error));if(writeAttempted&&notWritten(error)){remember(null);setNotice("同一原操作已确认回滚；当前原填写与文件保留，需核对版本和规格后明确重新准备。");}else setNotice("原凭证核对或同一原操作仍未确认，完整原输入与原凭证保持；只读失败不证明原写入未提交，不换新文件或凭证，不调用模型。");}finally{setBusy(false);}};
 const upload=async()=>{if(!file||locked)return;setBusy(true);setStep("读取并检查本地图像文件");try{if(file.size<=0||file.size>VISUAL_MAX_BYTES||!(VISUAL_MIME_TYPES as readonly string[]).includes(file.type))throw new Error("请选择非空且不超过10MiB的 PNG、JPEG、WebP 或 GIF 本地图片；不支持网页和SVG。");const base64=await readFile(file),input=visualUploadSchema.parse({bookId:scope.current,assetId:creating?null:asset?.id??null,expectedRevision:creating?null:asset?.revision??null,kind,title,description,filename:file.name,mimeType:file.type,base64,requestKey:crypto.randomUUID()});setBusy(false);await submit({kind:"upload",input});}catch(error){setError(sourceMessage(error));setNotice("尚未提交图片保存请求；原文件与说明保留，修正后可重新读取。");}finally{setBusy(false);}};
 const prepareImpact=(archive:boolean)=>{if(!asset||locked||dirty||!archive&&!version)return;void submit({kind:"preview",input:{bookId:scope.current,assetId:asset.id,expectedRevision:asset.revision,toVersionId:archive?null:version!.id,requestKey:crypto.randomUUID()}});};
 const confirmImpact=()=>{if(!impact||locked||!asset||impact.assetId!==asset.id||impact.revision!==asset.revision)return;if(impact.toVersionId)void submit({kind:"command",input:{operation:"adopt",bookId:scope.current,assetId:asset.id,expectedRevision:impact.revision,versionId:impact.toVersionId,previewId:impact.id,requestKey:crypto.randomUUID()}});else if(reason.trim())void submit({kind:"command",input:{operation:"archive",bookId:scope.current,assetId:asset.id,expectedRevision:impact.revision,previewId:impact.id,reason,requestKey:crypto.randomUUID()}});};
 const mount=()=>{const target=workspace?.owners.find(item=>ownerKey(item)===owner);if(!asset||!version||!target||locked)return;void submit({kind:"command",input:{operation:"mount",bookId:scope.current,assetId:asset.id,expectedRevision:asset.revision,versionId:version.id,ownerKind:target.kind,ownerStableId:target.stableId,ownerVersionId:target.versionId,label,requestKey:crypto.randomUUID()}});};
 const sourceHref=(item:VisualAsset,target:VisualVersion)=>`${visualRoute(scope.current)}?asset=${item.id}&version=${target.id}`;
 const visible=workspace?.assets.filter(item=>(archived||item.status==="active")&&(!search.trim()||item.title.includes(search.trim())))??[];
 return <div className="nd-shell nd-visual-page"><header className="nd-page-header"><div><p className="nd-eyebrow">新设计／本书视觉资产</p><h1>{workspace?.bookName??"本书"} · 视觉资产</h1><p>封面与插图按原图版本保存，明确采用或绑定后再用于本书。</p></div><a href={`/new-design/books/${scope.current}/overview`}>返回本书概览</a></header>
 {scopeChanged&&<div role="alert" className="nd-message is-error"><p>书籍来源已切换，原书未保存填写与原请求保留，禁止写到新书。</p><a href={visualRoute(scope.current)}>返回原书视觉资产继续处理</a></div>}
 {storageIssue&&<div className="nd-message is-error" role="alert"><p>未完成步骤：读取浏览器原图片操作凭证。</p><p>原凭证标记损坏或无法读取，保留标记并锁定新写入，不能当作“没有旧请求”。请从已保存的原凭证或本书原版本历史核对；不会用新图片代替原请求。</p><a href="/new-design/structure/maintenance">打开运行维护核对原资产账本</a><button type="button" disabled={busy} onClick={()=>void refresh()}>只读刷新本书版本历史</button></div>}
 <div className="nd-action-row"><button type="button" disabled={busy} onClick={()=>void refresh()}>只读刷新原目录</button><a href="/new-design/operations/records">查看原运行记录</a></div>
 {error&&<div className="nd-message is-error" role="alert"><p>未完成步骤：{step||"核对原图片来源"}</p><p>{error}</p><p>保留内容：原图片文件、不可变历史版本、既有精确引用、当前名称与说明。</p><a href="/new-design/structure/maintenance">检查运行维护（不重新提交）</a></div>}{notice&&<p role="status">{notice}</p>}
 {pending&&pendingScope&&<section className="nd-message" role="alert"><h2>原图片操作回执待核对</h2><p>{stepOf(pending)}</p><details><summary>原请求系统信息（只读）</summary><p>原请求凭证：{pendingScope.requestKey}</p></details><p>只读核对不会上传、绑定或生成。完成原操作只使用当前页面保存的完整原文件／输入与同一凭证，不使用新选择代替。</p><a href={visualRoute(pendingScope.bookId)}>返回原书图片来源页</a><button type="button" disabled={busy} onClick={()=>void check()}>只读核对原凭证</button>{pending.kind!=="read_only"&&<button type="button" disabled={busy} onClick={()=>void completeOriginal()}>按原凭证核对并完成原图片操作</button>}{pending.kind==="read_only"&&<p>完整原输入没有保留，只允许核对；不把重新选择的文件当作原请求提交。</p>}</section>}
 {switchTo&&<section className="nd-message" role="alert"><p>当前图片说明、文件或绑定说明未保存。切换只放弃这些本页草稿，不删除原版本和引用。</p><button type="button" disabled={locked} onClick={()=>setSwitchTo(null)}>保留填写，暂不切换</button><button type="button" disabled={locked} onClick={()=>{const target=switchTo;setSwitchTo(null);if(!target.assetId){open(null,null);return;}const item=workspace?.assets.find(candidate=>candidate.id===target.assetId),targetVersion=item?.versions.find(candidate=>candidate.id===(target.versionId??item?.currentVersionId))??(!target.versionId?item?.versions[0]:undefined);if(item&&targetVersion)open(item,targetVersion);else setError("原目标没有读取到，当前填写仍保留，未切换到其他图片。");}}>放弃本页未保存填写并切换</button></section>}
 {coverWorkbench&&<nav className="nd-shelf-cover-tabs" aria-label="封面管理视图"><button className="nd-button" aria-pressed={coverView==='gallery'} disabled={locked||imageGuard.blocked} onClick={()=>setCoverView('gallery')}>封面图库与管理</button><button className="nd-button" aria-pressed={coverView==='generate'} disabled={locked||imageGuard.blocked} onClick={()=>setCoverView('generate')}>AI 生成封面</button></nav>}
 <div hidden={coverWorkbench&&coverView!=='generate'}>{imageApi?<ImageGenerationPanel bookContext={bookContext} onCloseGuardChange={setImageGuard} key={bookId} bookId={bookId} api={imageApi} disabled={locked} onSaved={()=>{void load().catch(failure=>{setError(sourceMessage(failure));setNotice('新图片已保存，刷新原图片目录失败；保存回执保留，请只读刷新，不重新生成。');});}}/>:<section className="nd-visual-capability"><h2>图片生成</h2><p>专属图片操作入口尚未加载。已有图片保留；请打开运行维护后只读刷新本页，不使用文字模型替代。</p><a className="nd-button" href="/new-design/structure/maintenance">打开运行维护</a></section>}</div>
 <div hidden={coverWorkbench&&coverView!=='gallery'}><div className="nd-visual-workspace"><aside className="nd-visual-catalog"><header><h2>本书图片</h2><button type="button" disabled={locked} onClick={()=>choose(null,null)}>＋ 新增本地图片</button></header><label className="nd-control">搜索图片名称<input value={search} onChange={event=>setSearch(event.target.value)}/></label><label><input type="checkbox" checked={archived} onChange={event=>setArchived(event.target.checked)}/>显示归档历史</label>{(["cover","illustration"] as const).map(category=><details open key={category}><summary>{category==="cover"?"封面":"插图"} · {visible.filter(item=>item.kind===category).length}</summary>{visible.filter(item=>item.kind===category).map(item=><button type="button" key={item.id} disabled={locked} className={item.id===assetId?"is-selected":""} onClick={()=>choose(item.id,null)}><span>{item.title}</span><small>{item.status==="archived"?"已归档，只读":item.currentVersionId?"已有采用版本":"候选尚未采用"} · {item.versions.length} 个版本</small></button>)}</details>)}{!visible.length&&<p>没有匹配原图片。选择真实本地文件保存，不创建空图片占位。</p>}</aside>
 <main className="nd-visual-editor">{asset||creating?<><header><h2>{creating?"新增本地图片":asset?.title}</h2>{asset&&<p>修订 {asset.revision} · {asset.status==="active"?"可维护":"已归档，保留版本和引用"}</p>}</header>{asset&&<label className="nd-control">查看精确图片版本<select disabled={locked} value={versionId??""} onChange={event=>choose(asset.id,event.target.value)}>{asset.versions.map(item=><option key={item.id} value={item.id}>版本 {item.version} · {item.title}{item.id===asset.currentVersionId?"（当前采用）":"（历史或待采用）"}</option>)}</select></label>}
 {version&&<section className="nd-visual-image">{version.readable&&!imageFailed?<img key={imageRefresh} src={api.imageUrl(scope.current,asset!.id,version.id)} alt={version.title||"本书图片精确版本"} onError={()=>{setImageFailed(true);setStep("读取所选图片精确版本内容");setError("原图片文件未读取到或校验失败，未展示其他图片代替。原版本、说明和引用保留，可核对后只读重新读取。");}}/>:<div role="status">{imageFailed?"所选原图暂未读取，未使用替代图片。":"本版本不是本模块已验证受控图片；不会读取任意路径或外部网址。"}</div>}<p>版本 {version.version} · {Math.ceil(version.byteSize/1024)} KiB · {version.integrity==="verified"?"登记完整性已核对，展示仍校验实际文件":"完整性尚未通过"}</p><details><summary>原版本来源凭证（只读）</summary><p>原版本：{version.id}</p><p>内容校验：{version.checksum}</p><p>保存时间：{version.createdAt}</p><p>原文件名：{version.filename}</p></details>{version.readable&&imageFailed&&<button type="button" disabled={busy} onClick={()=>{setImageFailed(false);setImageRefresh(value=>value+1);}}>只读重新读取同一原图版本</button>}<a href={sourceHref(asset!,version)}>打开所选精确版本来源页</a></section>}
 <fieldset disabled={locked||!editable} className="nd-visual-fields"><label className="nd-control">图片用途<select disabled={!creating} value={kind} onChange={event=>setKind(event.target.value==="cover"?"cover":"illustration")}><option value="cover">封面</option><option value="illustration">插图</option></select></label><label className="nd-control">图片名称<input value={title} maxLength={240} onChange={event=>setTitle(event.target.value)}/></label><label className="nd-control">画面说明<textarea maxLength={4000} value={description} onChange={event=>setDescription(event.target.value)}/></label><label className="nd-control">{creating?"选择真实本地图片":"选择替换文件（仅保存新候选，不覆盖原图）"}<input type="file" accept={VISUAL_MIME_TYPES.join(",")} onChange={event=>setFile(event.target.files?.[0]??null)}/></label>{file&&<p>已选本地文件：{file.name} · {Math.ceil(file.size/1024)} KiB</p>}<div className="nd-action-row"><button type="button" disabled={!file||!title.trim()} onClick={()=>void upload()}>保存本地图片为新候选版本</button>{asset&&version&&<button type="button" disabled={Boolean(file)||!title.trim()||!version.readable||snapshot(title,description)===baseline} onClick={()=>void submit({kind:"command",input:{operation:"description",bookId:scope.current,assetId:asset.id,expectedRevision:asset.revision,versionId:version.id,title,description,requestKey:crypto.randomUUID()}})}>只保存说明为新候选版本</button>}</div></fieldset><p role="status">{dirty?"当前填写尚未保存；刷新目录不会覆盖本页填写。":"当前名称与说明和原版本一致。"}</p>
 {asset?.status==="active"&&version&&<><section><h3>明确采用与归档</h3><p>采用改变本图片的当前版本，既有资料引用仍固定旧版本；归档保留原图与引用并停止新增引用。两者先预览实际下游影响。</p><div className="nd-action-row"><button type="button" disabled={locked||dirty||!version.readable} onClick={()=>prepareImpact(false)}>预览采用所选版本的影响</button><button type="button" disabled={locked||dirty} onClick={()=>prepareImpact(true)}>预览归档原图片的影响</button></div>{impact&&<div className="nd-message"><h4>{impact.toVersionId?"待明确采用原版本":"待明确归档原图片"}</h4><p>{impact.impacts.length} 项下游精确引用受影响；强依赖需复核，弱依赖只提醒，不替换正文。</p><ul>{impact.impacts.map(item=><li key={item.id}>{item.label} · {item.strength==="hard"?"强依赖，需复核":"弱依赖，提醒"}<details><summary>影响来源凭证（只读）</summary><p>{item.id}</p></details></li>)}</ul>{!impact.toVersionId&&<label className="nd-control">归档原因<textarea disabled={locked} value={reason} maxLength={2000} onChange={event=>setReason(event.target.value)}/></label>}<p>预览后版本或引用若已变化，请保留当前结果并重新预览，再明确确认采用或归档。</p><button type="button" disabled={locked||impact.assetId!==asset.id||impact.revision!==asset.revision||!impact.toVersionId&&!reason.trim()} onClick={confirmImpact}>{impact.toVersionId?"明确采用此原图片版本":"确认归档，保留原图与引用"}</button><button type="button" disabled={locked} onClick={()=>setImpact(null)}>暂不采用或归档，保留原版本</button></div>}</section>
 <section><h3>绑定到本书正式内容</h3><p>仅选择本书真实正式对象及精确版本；以后新图片不会自动替换已有绑定。</p><fieldset className="nd-visual-fields" disabled={locked||!version.readable}><label className="nd-control">真实绑定目标<select value={owner} onChange={event=>setOwner(event.target.value)}><option value="">请选择已加载正式目标</option>{workspace?.owners.map(item=><option key={ownerKey(item)} value={ownerKey(item)}>{item.kind==="book"?"本书":item.kind==="card_version"?"本书资料":"已采用章节正文"} · {item.title}</option>)}</select></label><label className="nd-control">绑定说明<input value={label} maxLength={240} onChange={event=>setLabel(event.target.value)}/></label><button type="button" disabled={!owner||workspace?.mounts.some(item=>item.status==="active"&&item.assetId===asset.id&&item.versionId===version.id&&`${item.ownerKind}:${item.ownerStableId}:${item.ownerVersionId}`===owner)} onClick={mount}>明确绑定所选图片精确版本</button></fieldset></section></>}
 <section><h3>已保存的精确版本引用</h3>{workspace?.mounts.filter(item=>item.assetId===assetId).map(item=>{const targetVersion=asset?.versions.find(candidate=>candidate.id===item.versionId),targetOwner=workspace?.owners.find(candidate=>candidate.stableId===item.ownerStableId&&candidate.versionId===item.ownerVersionId&&candidate.kind===item.ownerKind);return <article key={item.id}><p>{targetOwner?.title??"原正式内容的历史精确版本"} · {item.label||"未写说明"} · {item.status==="active"?"引用保留":"引用已结束"}</p><details><summary>原正式内容版本凭证（只读）</summary><p>{item.ownerVersionId}</p></details>{asset&&targetVersion?<a href={sourceHref(asset,targetVersion)}>查看此绑定使用的原图片版本 {targetVersion.version}</a>:<p>绑定原版本未读取到，不显示其他版本代替。</p>}</article>})}{!workspace?.mounts.some(item=>item.assetId===assetId)&&<p>此图片还没有已保存绑定，候选和收藏不等于正式引用。</p>}</section>
 </>:<p>从左侧选择已有图片，或新增本地图片，再填写名称与画面说明。</p>}{lastReceipt&&<section className="nd-message" role="status"><h3>原操作已保存</h3><p>{lastReceipt.retainedResult}</p><details><summary>原请求凭证（只读）</summary><p>{lastReceipt.requestKey}</p></details>{lastReceipt.versionId&&<a href={`${visualRoute(lastReceipt.bookId)}?asset=${lastReceipt.assetId}&version=${lastReceipt.versionId}`}>查看已保存精确版本来源页</a>}</section>}</main></div></div></div>;
}
