import {useCallback,useEffect,useRef,useState} from 'react';
import type {CreativeHubBinding,CreativeHubCapability,CreativeHubState,CreativeHubThread,CreativeHubTurn} from '../../common/creativeHub';
import type {BookshelfSnapshot} from '../../common/bookshelf';
import type {CreativeHubApi} from './api';
import {CreativeHubConversation} from './CreativeHubConversation';
import {CreativeHubThreadList} from './CreativeHubThreadList';
import {creativeHubHref,readCreativeHubLocation} from './location';
import './creative-hub.css';

interface PendingQuestion {threadId:string;requestKey:string;question:string;expectedThreadRevision:number;}
const PENDING_KEY='new-design:creative-hub:pending-question:';
const message=(error:unknown,fallback:string)=>error instanceof Error&&error.message?error.message:fallback;
function readPending(threadId:string):PendingQuestion|null{try{const value=JSON.parse(sessionStorage.getItem(PENDING_KEY+threadId)??'null') as PendingQuestion|null;return value?.threadId===threadId?value:null;}catch{return null;}}
function savePending(threadId:string,value:PendingQuestion|null){try{if(value)sessionStorage.setItem(PENDING_KEY+threadId,JSON.stringify(value));else sessionStorage.removeItem(PENDING_KEY+threadId);}catch{/* Session recovery is optional; database receipts remain canonical. */}}
function replaceThread(items:CreativeHubThread[],next:CreativeHubThread){return items.map(item=>item.id===next.id?next:item).sort((left,right)=>right.updatedAt.localeCompare(left.updatedAt));}

export default function CreativeHubPage({api,getBookshelf}:{api:CreativeHubApi;getBookshelf():Promise<BookshelfSnapshot>}){
  const initial=typeof window==='undefined'?{threadId:null,explicit:false,error:null}:readCreativeHubLocation(window.location.search);
  const [location,setLocation]=useState(initial),[capability,setCapability]=useState<CreativeHubCapability|null>(null),[threads,setThreads]=useState<CreativeHubThread[]>([]),[selected,setSelected]=useState<CreativeHubThread|null>(null),[state,setState]=useState<CreativeHubState|null>(null),[turns,setTurns]=useState<CreativeHubTurn[]>([]),[bookshelf,setBookshelf]=useState<BookshelfSnapshot|null>(null);
  const [busy,setBusy]=useState(true),[detailBusy,setDetailBusy]=useState(false),[mutating,setMutating]=useState(false),[failure,setFailure]=useState(initial.error??''),[detailFailure,setDetailFailure]=useState('');
  const [creating,setCreating]=useState(false),[createTitle,setCreateTitle]=useState('新的创作诊断'),[createBookId,setCreateBookId]=useState(''),[title,setTitle]=useState(''),[bindingBookId,setBindingBookId]=useState(''),[question,setQuestion]=useState('');
  const loadGeneration=useRef(0);

  const navigate=useCallback((threadId:string|null,replace=false)=>{const next={threadId,explicit:Boolean(threadId),error:null};setLocation(next);if(typeof window!=='undefined')window.history[replace?'replaceState':'pushState']({},'',creativeHubHref(threadId));},[]);
  useEffect(()=>{const pop=()=>setLocation(readCreativeHubLocation(window.location.search));window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);

  const loadIndex=useCallback(async()=>{setBusy(true);setFailure(location.error??'');try{const gate=await api.capability();setCapability(gate);const shelfPromise=getBookshelf().then(setBookshelf).catch(()=>setBookshelf(null));if(!gate.installed){setThreads([]);setSelected(null);await shelfPromise;return;}const items=await api.list();setThreads(items);if(location.error){setSelected(null);return;}if(location.threadId){const exact=items.find(item=>item.id===location.threadId);if(!exact){setSelected(null);setFailure('指定会话不存在或已归档；未自动切换到其他会话。');}else setSelected(exact);}else if(items[0]){setSelected(items[0]);navigate(items[0].id,true);}else setSelected(null);await shelfPromise;}catch(error){setFailure(message(error,'创作中枢目录读取失败；原会话不会被重建或覆盖。'));}finally{setBusy(false);}},[api,getBookshelf,location.error,location.threadId,navigate]);
  useEffect(()=>{void loadIndex();},[loadIndex]);

  const loadDetail=useCallback(async(thread:CreativeHubThread)=>{const generation=++loadGeneration.current;setDetailBusy(true);setDetailFailure('');try{const [nextState,nextTurns]=await Promise.all([api.state(thread.id),api.history(thread.id)]);if(generation!==loadGeneration.current)return;setState(nextState);setTurns(nextTurns);setTitle(thread.title);setBindingBookId(thread.binding.bookId??'');setQuestion(readPending(thread.id)?.question??'');}catch(error){if(generation===loadGeneration.current)setDetailFailure(message(error,'原会话状态未读取；已显示的历史保留，不会自动改选其他会话。'));}finally{if(generation===loadGeneration.current)setDetailBusy(false);}},[api]);
  useEffect(()=>{if(selected)void loadDetail(selected);else{loadGeneration.current++;setState(null);setTurns([]);setTitle('');setBindingBookId('');setQuestion('');}},[selected,loadDetail]);

  const selectThread=(thread:CreativeHubThread)=>{setFailure('');setSelected(thread);navigate(thread.id);};
  const create=async()=>{if(!capability?.operational||!createTitle.trim())return;setMutating(true);setFailure('');try{const binding:CreativeHubBinding=createBookId?{bookId:createBookId}:{};const created=await api.create({title:createTitle.trim(),binding});setThreads(current=>[created,...current]);setSelected(created);setCreating(false);setCreateTitle('新的创作诊断');setCreateBookId('');navigate(created.id);}catch(error){setFailure(message(error,'新会话未创建；请核对能力门禁后重试。'));}finally{setMutating(false);}};
  const saveBinding=async()=>{if(!selected||!capability?.operational)return;setMutating(true);setDetailFailure('');try{const binding:CreativeHubBinding=bindingBookId===(selected.binding.bookId??'')?selected.binding:bindingBookId?{bookId:bindingBookId}:{};const next=await api.update(selected.id,{title:title.trim()||selected.title,binding,expectedRevision:selected.revision});setSelected(next);setThreads(current=>replaceThread(current,next));setState(await api.state(next.id));}catch(error){setDetailFailure(message(error,'会话绑定未保存；原绑定和历史仍保留。'));}finally{setMutating(false);}};
  const archive=async()=>{if(!selected||!capability?.operational||!window.confirm(`归档会话“${selected.title}”？历史会保留，但不会继续出现在当前列表。`))return;setMutating(true);try{await api.archive(selected.id,selected.revision);const remaining=threads.filter(item=>item.id!==selected.id);setThreads(remaining);setSelected(remaining[0]??null);navigate(remaining[0]?.id??null,true);}catch(error){setDetailFailure(message(error,'会话未归档；请读取最新版本后再决定。'));}finally{setMutating(false);}};
  const submit=async()=>{if(!selected||!capability?.operational||!question.trim())return;const previous=readPending(selected.id),pending=previous&&previous.question===question.trim()&&previous.expectedThreadRevision===selected.revision?previous:{threadId:selected.id,requestKey:crypto.randomUUID(),question:question.trim(),expectedThreadRevision:selected.revision};savePending(selected.id,pending);setMutating(true);setDetailFailure('');try{await api.start(selected.id,{requestKey:pending.requestKey,question:pending.question,expectedThreadRevision:pending.expectedThreadRevision});savePending(selected.id,null);setQuestion('');await loadDetail(selected);}catch(error){setDetailFailure(`${message(error,'诊断回执尚未确认。')} 原问题与请求凭证已在本次会话保留；再次发送会使用同一凭证。`);await api.history(selected.id).then(setTurns).catch(()=>undefined);}finally{setMutating(false);}};
  const resume=async(turn:CreativeHubTurn)=>{if(!selected||turn.threadId!==selected.id||!capability?.operational)return;setMutating(true);setDetailFailure('');try{await api.resume(selected.id,turn.id);await loadDetail(selected);}catch(error){setDetailFailure(message(error,'原诊断不能安全重试；未知结果不会重新发送。'));await api.history(selected.id).then(setTurns).catch(()=>undefined);}finally{setMutating(false);}};

  const gateDisabled=!capability?.operational;
  return <div className="nd-shell nd-creative-hub"><header className="nd-page-header"><div><p className="nd-eyebrow">新设计／只读创作诊断</p><h1>创作中枢</h1><p>持续询问作品进度、失败原因和修改影响，并回到正式来源页面处理。中枢不直接改写正文、规划或任务状态。</p></div><button type="button" className="nd-button" disabled={busy} onClick={()=>void loadIndex()}>只读刷新</button></header>
    {capability&&!capability.operational&&<section className="nd-message is-warning" role="alert"><strong>创作中枢写入门禁未就绪</strong><p>{capability.reason}</p><p>当前源码不会自动安装迁移，也不会借用旧版会话或数据库。</p><a href="/new-design/structure/maintenance">打开运行维护</a></section>}
    {failure&&<p className="nd-message is-error" role="alert">{failure}</p>}
    {creating&&<section className="nd-hub-create"><h2>新建持续会话</h2><label>会话名称<input maxLength={120} value={createTitle} onChange={event=>setCreateTitle(event.target.value)}/></label><label>绑定作品（可选）<select value={createBookId} onChange={event=>setCreateBookId(event.target.value)}><option value="">暂不绑定</option>{bookshelf?.books.map(book=><option key={book.id} value={book.id}>{book.name}</option>)}</select></label><div><button className="nd-button nd-button-primary" type="button" disabled={gateDisabled||mutating||!createTitle.trim()} onClick={()=>void create()}>创建会话</button><button className="nd-button" type="button" onClick={()=>setCreating(false)}>取消</button></div></section>}
    <main className="nd-hub-layout"><CreativeHubThreadList threads={threads} selectedId={selected?.id??null} busy={busy||gateDisabled} onSelect={selectThread} onCreate={()=>setCreating(true)}/><section className="nd-hub-main" aria-busy={detailBusy}>
      {selected?<><header className="nd-hub-binding"><div><p className="nd-eyebrow">当前上下文</p><h2>{selected.title}</h2><p>{state?.book?`已绑定《${state.book.name}》`:'未绑定作品'}{selected.binding.chapterDocumentId?' · 已绑定章节':''}{selected.binding.taskId?' · 已绑定原任务':''}</p></div><div className="nd-hub-binding-actions"><label>会话名称<input maxLength={120} value={title} onChange={event=>setTitle(event.target.value)}/></label><label>作品范围<select value={bindingBookId} onChange={event=>setBindingBookId(event.target.value)}><option value="">不绑定作品</option>{bookshelf?.books.map(book=><option key={book.id} value={book.id}>{book.name}</option>)}</select></label><button type="button" className="nd-button" disabled={gateDisabled||mutating||!title.trim()} onClick={()=>void saveBinding()}>保存名称与绑定</button><button type="button" className="nd-button nd-button-danger" disabled={gateDisabled||mutating} onClick={()=>void archive()}>归档会话</button></div></header>
        {detailFailure&&<p className="nd-message is-error" role="alert">{detailFailure}</p>}{state&&<details className="nd-hub-state"><summary>本次诊断可读取的正式状态</summary>{state.blockers.length?<ul>{state.blockers.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>当前投影没有列出阻塞；这不等于所有创作步骤均已完成。</p>}<div>{state.sourceLinks.map(link=><a key={link.href} href={link.href}>{link.label}</a>)}</div></details>}
        <CreativeHubConversation turns={turns} busy={mutating||detailBusy} disabled={gateDisabled} question={question} onQuestionChange={setQuestion} onSubmit={()=>void submit()} onResume={turn=>void resume(turn)}/></>:<div className="nd-empty-state"><h2>选择或新建一个会话</h2><p>会话会保留绑定范围和每次诊断的冻结状态；明确无效的深链不会自动切换到其他会话。</p></div>}
    </section></main>
  </div>;
}
