import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {characterImportInputSchema,characterImportCommitSchema,importValuePresent,type CharacterImportInput,type CharacterImportCommit,type CharacterImportPreview,type CharacterImportReceipt,type CharacterImportWorkspace} from '../../../common/characterImport';
import {assertFound,NewDesignError} from '../../domain/errors';
import {getNewDesignPool} from '../runtime';
import {formHash} from '../formAssist';
import {validateCardValues} from '../../domain/validation';
import {validateDictionaryTreeValues} from '../treeResources';
import {createAuthorMaterialInTransaction} from '../authorMaterials';
import {characterImportSources} from './sources';
export {getCharacterImportCatalog} from './sources';
const contract='public_character_import_v1';
export class CharacterImportError extends NewDesignError{constructor(message:string,status:number,public readonly mutationOutcome:'not_written'|'unknown',issues?:Record<string,string>){super(message,status,issues);}}
function mappedValues(workspace:CharacterImportWorkspace,input:CharacterImportInput){
 const keys=Object.keys(workspace.source.values).filter(key=>importValuePresent(workspace.source.values[key])),seen=new Set<string>(),targets=new Set<string>(),fields=workspace.target.importFields;
 for(const item of input.mapping){if(!Object.hasOwn(workspace.source.values,item.sourceKey)||!keys.includes(item.sourceKey)||seen.has(item.sourceKey)||targets.has(item.targetKey)||Object.hasOwn(input.additionalValues,item.targetKey)||!fields.some(field=>field.key===item.targetKey))throw new NewDesignError('来源字段、目标字段或映射值不完整；没有静默丢弃或覆盖字段。',422);seen.add(item.sourceKey);targets.add(item.targetKey);}
 const missing=keys.filter(key=>!seen.has(key));if(missing.length)throw new NewDesignError('公共角色的已填写字段缺少映射，原来源保留，请先明确每个目标字段。',422,Object.fromEntries(missing.map(key=>[key,'请选择本书实际字段，必要时先新增字段再读取。'])));
 if(Object.keys(input.additionalValues).some(key=>!fields.some(field=>field.key===key)))throw new NewDesignError('本次填写包含不可导入的字段，不复制正式状态、认知或持有。',422);
 const valid=validateCardValues(workspace.target.fields,{...input.additionalValues,...Object.fromEntries(input.mapping.map(item=>[item.targetKey,item.value]))});if(Object.keys(valid.issues).length)throw new NewDesignError('请完善本书人物必填信息与映射值。',422,valid.issues);return valid.values;
}
async function preview(db:PoolClient,bookId:string,input:CharacterImportInput,lock=false):Promise<CharacterImportPreview>{const workspace=await characterImportSources(db,bookId,input.resourceId,input.resourceVersionId,lock),values=mappedValues(workspace,input),issues=await validateDictionaryTreeValues(db,workspace.target.fields,values);if(Object.keys(issues).length)throw new NewDesignError('公共选项不能直接当成本书选项，请明确核对映射后的值。',422,issues);return{bookId,input,workspace,values,previewHash:formHash({contract,bookId,input,workspace,values})};}
export async function getCharacterImportWorkspace(bookId:string,resourceId:string,resourceVersionId:string){const db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const workspace=await characterImportSources(db,bookId,resourceId,resourceVersionId);await db.query('COMMIT');return workspace;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function previewCharacterImport(bookId:string,input:CharacterImportInput){const parsed=characterImportInputSchema.parse(input),db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const result=await preview(db,bookId,parsed);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
async function original(db:PoolClient,bookId:string,input:CharacterImportCommit):Promise<CharacterImportReceipt|null>{const row=(await db.query("SELECT snapshot FROM new_design.resource_adoptions WHERE book_id=$1 AND snapshot->>'contract'=$2 AND snapshot->>'requestKey'=$3",[bookId,contract,input.requestKey])).rows[0];if(!row)return null;if(row.snapshot.inputHash!==formHash({bookId,input}))throw new CharacterImportError('原导入请求与公共版本、字段映射或书内填写不同，原凭证保留。',409,'unknown');return{...row.snapshot.receipt,repeated:true};}
export async function readCharacterImportOriginal(bookId:string,input:CharacterImportCommit){const parsed=characterImportCommitSchema.parse(input),db=await(await getNewDesignPool()).connect();try{await db.query('BEGIN READ ONLY');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`character-import:${bookId}:${parsed.requestKey}`]);const saved=await original(db,bookId,parsed);await db.query('COMMIT');return saved;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function importPublicCharacter(bookId:string,input:CharacterImportCommit):Promise<CharacterImportReceipt>{
 const parsed=characterImportCommitSchema.parse(input),pool=await getNewDesignPool(),db=await pool.connect().catch(()=>{throw new CharacterImportError('导入连接未建立，原填写保留，尚未提交。',503,'not_written');});let committing=false,requestConflict=false;
 try{
  await db.query('SELECT pg_advisory_lock(hashtextextended($1,0))',[`character-import:${bookId}:${parsed.requestKey}`]);await db.query('BEGIN ISOLATION LEVEL SERIALIZABLE');let saved:CharacterImportReceipt|null;try{saved=await original(db,bookId,parsed);}catch(error){requestConflict=true;throw error;}if(saved){await db.query('ROLLBACK');return saved;}
  const {previewHash,...raw}=parsed,current=await preview(db,bookId,raw,true);if(current.previewHash!==previewHash)throw new NewDesignError('公共版本、本书规格或映射来源已变化，请保留填写重新预览；尚未导入。',409);
  if((await db.query("SELECT id FROM new_design.card_versions WHERE author_book_id=$1 AND author_request_key=$2",[bookId,parsed.requestKey])).rowCount)throw new NewDesignError("原键已用于其他人物保存，请保留原填写核对，未将旧人物当作新导入。",409);
  const created=await createAuthorMaterialInTransaction(db,bookId,{requestKey:parsed.requestKey,cardTypeId:current.workspace.target.cardTypeId,title:parsed.title,values:current.values,formVersionId:current.workspace.target.formVersionId,formResolutionKind:current.workspace.target.formResolutionKind});
  const adoptionId=randomUUID(),inputHash=formHash({bookId,input:parsed}),receipt:CharacterImportReceipt={bookId,requestKey:parsed.requestKey,inputHash,input:parsed,mappedFields:parsed.mapping.map(item=>({sourceKey:item.sourceKey,sourceLabel:current.workspace.source.fields.find(field=>field.key===item.sourceKey)?.name??item.sourceKey,targetKey:item.targetKey,targetLabel:current.workspace.target.fields.find(field=>field.key===item.targetKey)?.name??item.targetKey})),adoptionId,resourceId:parsed.resourceId,resourceVersionId:parsed.resourceVersionId,receipt:created,sourceRoute:`/new-design/books/${bookId}/story-setting?tab=characters&selected=${created.card.id}&type=${created.card.cardTypeId}&detail=basic`,repeated:false};
  for(const item of parsed.mapping)await db.query("INSERT INTO new_design.card_field_origins(id,card_id,field_key,source_kind,source_id,confirmation_status,original_value,current_value) VALUES($1,$2,$3,'resource',$4,'confirmed',$5::jsonb,$6::jsonb)",[randomUUID(),created.card.id,item.targetKey,parsed.resourceId,JSON.stringify(current.workspace.source.values[item.sourceKey]),JSON.stringify(current.values[item.targetKey]??null)]);
  await db.query("INSERT INTO new_design.resource_adoptions(id,resource_card_id,resource_version_id,book_id,target_card_id,action,snapshot) VALUES($1,$2,$3,$4,$5,'install_snapshot',$6::jsonb)",[adoptionId,parsed.resourceId,parsed.resourceVersionId,bookId,created.card.id,JSON.stringify({contract,requestKey:parsed.requestKey,inputHash,input:parsed,workspace:current.workspace,values:current.values,receipt})]);committing=true;await db.query('COMMIT');return receipt;
 }catch(error){let rollback=false;try{await db.query('ROLLBACK');rollback=true;}catch{}if(requestConflict)throw error instanceof CharacterImportError?error:new CharacterImportError('原导入回执未完整读取，保留原键只读核对，不能证明此前未保存。',503,'unknown');throw new CharacterImportError(error instanceof NewDesignError?error.message:'原导入结果未确认，保留完整原请求只读核对。',error instanceof NewDesignError?error.status:503,!committing&&rollback?'not_written':'unknown',error instanceof NewDesignError?error.issues:undefined);}
 finally{let released=false;try{await db.query('SELECT pg_advisory_unlock(hashtextextended($1,0))',[`character-import:${bookId}:${parsed.requestKey}`]);}catch{db.release(true);released=true;}if(!released)db.release();}
}
