export const settlementRecordDefaults:Record<string,Record<string,unknown>>={
  "settlement_relation_configuration_receipt": {
    "id": null,
    "book_id": null,
    "request_key": null,
    "input_hash": null,
    "receipt": null,
    "created_at": "__now"
  },
  "settlement_relation_configuration_draft": {
    "id": null,
    "book_id": null,
    "revision": null,
    "current_version_id": null,
    "relation_type_id": null,
    "source_relation_type_id": null,
    "expected_relation_type_revision": null,
    "status": null,
    "created_at": "__now",
    "updated_at": "__now"
  },
  "settlement_relation_configuration_version": {
    "id": null,
    "draft_id": null,
    "version": null,
    "definition": null,
    "relation_type_id": null,
    "source_relation_type_id": null,
    "expected_relation_type_revision": null,
    "created_at": "__now"
  },
  "chapter_proposal_extraction_request": {
    "id": null,
    "session_id": null,
    "book_id": null,
    "body_version_id": null,
    "task_contract_version_id": null,
    "prompt_recipe_version_id": null,
    "context_manifest_id": null,
    "model_route_snapshot_id": null,
    "ai_task_id": null,
    "status": "preparing",
    "request_hash": null,
    "idempotency_key": null,
    "created_by": "",
    "error_summary": "",
    "created_at": "__now",
    "updated_at": "__now",
    "frozen_plan": null,
    "frozen_input_hash": null,
    "expected_session_revision": null,
    "generated_output": null,
    "generated_execution": null,
    "failure": null
  },
  "chapter_settlement_event": {
    "id": null,
    "session_id": null,
    "event_kind": null,
    "from_status": null,
    "to_status": null,
    "item_id": null,
    "idempotency_key": null,
    "actor": "",
    "detail": {},
    "created_at": "__now",
    "editing_request_key": null,
    "editing_input_hash": null,
    "editing_receipt": null
  },
  "chapter_adoption_session": {
    "id": null,
    "book_id": null,
    "chapter_document_id": null,
    "body_version_id": null,
    "preparation_id": null,
    "prior_body_version_id": null,
    "adoption_id": null,
    "settlement_id": null,
    "policy_version_id": null,
    "planning_object_id": null,
    "planning_version_id": null,
    "context_manifest_id": null,
    "dependency_hash": null,
    "adoption_kind": null,
    "status": null,
    "revision": 1,
    "idempotency_key": null,
    "created_by": "",
    "error_summary": "",
    "created_at": "__now",
    "updated_at": "__now",
    "supplement_base_checkpoint_id": null
  },
  "chapter_stable_checkpoint": {
    "id": null,
    "book_id": null,
    "chapter_document_id": null,
    "body_version_id": null,
    "session_id": null,
    "settlement_id": null,
    "previous_checkpoint_id": null,
    "chapter_order": null,
    "summary": {},
    "dependency_hash": null,
    "status": "stable",
    "created_at": "__now"
  },
  "settlement_policy_version": {
    "id": null,
    "book_id": null,
    "version": null,
    "auto_confirm_low_risk": false,
    "allowed_auto_categories": [],
    "major_fact_categories": [
      "death",
      "identity_reveal",
      "faction_change",
      "core_relationship",
      "key_prop",
      "timeline_causality",
      "world_rule",
      "foreshadow_payoff"
    ],
    "confidence_floor": 0.95,
    "created_by": "",
    "note": "",
    "created_at": "__now"
  },
  "book_settlement_policy": {
    "book_id": null,
    "current_version_id": null,
    "revision": 1,
    "updated_at": "__now"
  },
  "chapter_adoption_preparation": {
    "id": null,
    "book_id": null,
    "chapter_document_id": null,
    "body_version_id": null,
    "expected_document_revision": null,
    "planning_object_id": null,
    "planning_version_id": null,
    "planning_content_hash": null,
    "context_manifest_id": null,
    "dependency_snapshot": {},
    "dependency_hash": null,
    "status": "prepared",
    "idempotency_key": null,
    "created_by": "",
    "created_at": "__now",
    "supplement_base_checkpoint_id": null
  },
  "chapter_settlement_item_version": {
    "id": null,
    "item_id": null,
    "version": null,
    "snapshot": null,
    "editor": null,
    "note": "",
    "created_at": "__now"
  },
  "embedding_source_snapshot": {
    "id": null,
    "space_id": null,
    "book_id": null,
    "profile_version_id": null,
    "dependency_source_resource_id": null,
    "source_kind": null,
    "source_stable_id": null,
    "source_version_id": null,
    "source_revision": null,
    "source_hash": null,
    "title": "",
    "content_text": null,
    "chunk_recipe_hash": null,
    "status": "current",
    "created_by": "",
    "created_at": "__now",
    "stale_at": null
  },
  "chunking_request": {
    "id": null,
    "book_id": null,
    "source_snapshot_id": null,
    "profile_version_id": null,
    "expected_source_hash": null,
    "status": "pending",
    "attempt_count": 0,
    "idempotency_key": null,
    "last_error": "",
    "created_at": "__now",
    "started_at": null,
    "completed_at": null
  },
  "ai_contract_publication": {
    "id": null,
    "entity_kind": null,
    "entity_id": null,
    "from_version_id": null,
    "to_version_id": null,
    "entity_revision": null,
    "action": null,
    "actor": null,
    "idempotency_key": null,
    "created_at": "__now"
  },
  "context_manifest_slot": {
    "id": null,
    "manifest_id": null,
    "slot_key": null,
    "sort_order": null,
    "required": null,
    "token_budget": null
  }
};
export const settlementRecordChecks:Record<string,string>={
 settlement_relation_configuration_receipt:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (request_key IS NOT NULL) AND (input_hash IS NOT NULL) AND ($1::jsonb ? 'receipt') AND (created_at IS NOT NULL) AND ((length(request_key) BETWEEN 8 AND 160) IS NOT FALSE) AND ((input_hash ~ '^[0-9a-f]{64}$') IS NOT FALSE) AND ((jsonb_typeof(receipt)='object') IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,request_key text,input_hash text,receipt jsonb,created_at timestamptz)`,
 settlement_relation_configuration_draft:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (revision IS NOT NULL) AND (status IS NOT NULL) AND (created_at IS NOT NULL) AND (updated_at IS NOT NULL) AND ((revision>0) IS NOT FALSE) AND ((expected_relation_type_revision>0) IS NOT FALSE) AND ((status IN ('draft','published')) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,revision integer,current_version_id uuid,relation_type_id uuid,source_relation_type_id uuid,expected_relation_type_revision integer,status text,created_at timestamptz,updated_at timestamptz)`,
 settlement_relation_configuration_version:`SELECT (id IS NOT NULL) AND (draft_id IS NOT NULL) AND (version IS NOT NULL) AND ($1::jsonb ? 'definition') AND (created_at IS NOT NULL) AND ((version>0) IS NOT FALSE) AND ((jsonb_typeof(definition)='object') IS NOT FALSE) AND ((expected_relation_type_revision>0) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,draft_id uuid,version integer,definition jsonb,relation_type_id uuid,source_relation_type_id uuid,expected_relation_type_revision integer,created_at timestamptz)`,
 chapter_proposal_extraction_request:`SELECT (id IS NOT NULL) AND (session_id IS NOT NULL) AND (book_id IS NOT NULL) AND (body_version_id IS NOT NULL) AND (task_contract_version_id IS NOT NULL) AND (prompt_recipe_version_id IS NOT NULL) AND (context_manifest_id IS NOT NULL) AND (model_route_snapshot_id IS NOT NULL) AND (status IS NOT NULL) AND (request_hash IS NOT NULL) AND (idempotency_key IS NOT NULL) AND (created_by IS NOT NULL) AND (error_summary IS NOT NULL) AND (created_at IS NOT NULL) AND (updated_at IS NOT NULL) AND ((status IN ('preparing','queued','running','succeeded','failed','cancelled','unavailable','stale')) IS NOT FALSE) AND ((request_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((length(idempotency_key) BETWEEN 8 AND 160) IS NOT FALSE) AND ((length(error_summary)<=2000) IS NOT FALSE) AND ((frozen_plan IS NULL OR jsonb_typeof(frozen_plan)='object') IS NOT FALSE) AND ((frozen_input_hash IS NULL OR frozen_input_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((expected_session_revision IS NULL OR expected_session_revision>0) IS NOT FALSE) AND ((generated_output IS NULL OR jsonb_typeof(generated_output)='object') IS NOT FALSE) AND ((generated_execution IS NULL OR jsonb_typeof(generated_execution)='object') IS NOT FALSE) AND ((failure IS NULL OR jsonb_typeof(failure)='object') IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,session_id uuid,book_id uuid,body_version_id uuid,task_contract_version_id uuid,prompt_recipe_version_id uuid,context_manifest_id uuid,model_route_snapshot_id uuid,ai_task_id uuid,status text,request_hash char(64),idempotency_key text,created_by text,error_summary text,created_at timestamptz,updated_at timestamptz,frozen_plan jsonb,frozen_input_hash text,expected_session_revision integer,generated_output jsonb,generated_execution jsonb,failure jsonb)`,
 chapter_settlement_event:`SELECT (id IS NOT NULL) AND (session_id IS NOT NULL) AND (event_kind IS NOT NULL) AND (to_status IS NOT NULL) AND (actor IS NOT NULL) AND ($1::jsonb ? 'detail') AND (created_at IS NOT NULL) AND ((event_kind IN ('session_started','body_adopted','impact_review_required','proposal_added','proposal_edited','decision_recorded','settlement_started','settlement_committed','settlement_failed')) IS NOT FALSE) AND ((jsonb_typeof(detail)='object') IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,session_id uuid,event_kind text,from_status text,to_status text,item_id uuid,idempotency_key text,actor text,detail jsonb,created_at timestamptz,editing_request_key text,editing_input_hash char(64),editing_receipt jsonb)`,
 chapter_adoption_session:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (chapter_document_id IS NOT NULL) AND (body_version_id IS NOT NULL) AND (preparation_id IS NOT NULL) AND (policy_version_id IS NOT NULL) AND (planning_object_id IS NOT NULL) AND (planning_version_id IS NOT NULL) AND (dependency_hash IS NOT NULL) AND (adoption_kind IS NOT NULL) AND (status IS NOT NULL) AND (revision IS NOT NULL) AND (idempotency_key IS NOT NULL) AND (created_by IS NOT NULL) AND (error_summary IS NOT NULL) AND (created_at IS NOT NULL) AND (updated_at IS NOT NULL) AND ((dependency_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((adoption_kind IN ('first_adoption','body_switch','resource_supplement')) IS NOT FALSE) AND ((status IN ('reviewing','adopted_pending_proposals','pending_review','partially_confirmed','settling','stable','failed','impact_review_required','cancelled')) IS NOT FALSE) AND ((revision>0) IS NOT FALSE) AND ((length(idempotency_key) BETWEEN 8 AND 160) IS NOT FALSE) AND ((length(error_summary)<=2000) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,chapter_document_id uuid,body_version_id uuid,preparation_id uuid,prior_body_version_id uuid,adoption_id uuid,settlement_id uuid,policy_version_id uuid,planning_object_id uuid,planning_version_id uuid,context_manifest_id uuid,dependency_hash char(64),adoption_kind text,status text,revision integer,idempotency_key text,created_by text,error_summary text,created_at timestamptz,updated_at timestamptz,supplement_base_checkpoint_id uuid)`,
 chapter_stable_checkpoint:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (chapter_document_id IS NOT NULL) AND (body_version_id IS NOT NULL) AND (session_id IS NOT NULL) AND (settlement_id IS NOT NULL) AND (chapter_order IS NOT NULL) AND ($1::jsonb ? 'summary') AND (dependency_hash IS NOT NULL) AND (status IS NOT NULL) AND (created_at IS NOT NULL) AND ((chapter_order>0) IS NOT FALSE) AND ((jsonb_typeof(summary)='object') IS NOT FALSE) AND ((dependency_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((status IN ('stable','stale','superseded')) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,chapter_document_id uuid,body_version_id uuid,session_id uuid,settlement_id uuid,previous_checkpoint_id uuid,chapter_order integer,summary jsonb,dependency_hash char(64),status text,created_at timestamptz)`,
 settlement_policy_version:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (version IS NOT NULL) AND (auto_confirm_low_risk IS NOT NULL) AND (allowed_auto_categories IS NOT NULL) AND (major_fact_categories IS NOT NULL) AND (confidence_floor IS NOT NULL) AND (created_by IS NOT NULL) AND (note IS NOT NULL) AND (created_at IS NOT NULL) AND ((version>0) IS NOT FALSE) AND ((allowed_auto_categories <@ ARRAY['fact','knowledge','character_state','relationship','prop','event','foreshadow']::text[]) IS NOT FALSE) AND ((confidence_floor BETWEEN 0 AND 1) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,version integer,auto_confirm_low_risk boolean,allowed_auto_categories text[],major_fact_categories text[],confidence_floor numeric(5,4),created_by text,note text,created_at timestamptz)`,
 book_settlement_policy:`SELECT (book_id IS NOT NULL) AND (current_version_id IS NOT NULL) AND (revision IS NOT NULL) AND (updated_at IS NOT NULL) AND ((revision>0) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(book_id uuid,current_version_id uuid,revision integer,updated_at timestamptz)`,
 chapter_adoption_preparation:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (chapter_document_id IS NOT NULL) AND (body_version_id IS NOT NULL) AND (expected_document_revision IS NOT NULL) AND (planning_object_id IS NOT NULL) AND (planning_version_id IS NOT NULL) AND (planning_content_hash IS NOT NULL) AND ($1::jsonb ? 'dependency_snapshot') AND (dependency_hash IS NOT NULL) AND (status IS NOT NULL) AND (idempotency_key IS NOT NULL) AND (created_by IS NOT NULL) AND (created_at IS NOT NULL) AND ((expected_document_revision>0) IS NOT FALSE) AND ((planning_content_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((jsonb_typeof(dependency_snapshot)='object') IS NOT FALSE) AND ((dependency_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((status IN ('prepared','consumed','stale','cancelled')) IS NOT FALSE) AND ((length(idempotency_key) BETWEEN 8 AND 160) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,chapter_document_id uuid,body_version_id uuid,expected_document_revision integer,planning_object_id uuid,planning_version_id uuid,planning_content_hash char(64),context_manifest_id uuid,dependency_snapshot jsonb,dependency_hash char(64),status text,idempotency_key text,created_by text,created_at timestamptz,supplement_base_checkpoint_id uuid)`,
 chapter_settlement_item_version:`SELECT (id IS NOT NULL) AND (item_id IS NOT NULL) AND (version IS NOT NULL) AND ($1::jsonb ? 'snapshot') AND (editor IS NOT NULL) AND (note IS NOT NULL) AND (created_at IS NOT NULL) AND ((version>0) IS NOT FALSE) AND ((jsonb_typeof(snapshot)='object') IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,item_id uuid,version integer,snapshot jsonb,editor text,note text,created_at timestamptz)`,
 embedding_source_snapshot:`SELECT (id IS NOT NULL) AND (space_id IS NOT NULL) AND (book_id IS NOT NULL) AND (profile_version_id IS NOT NULL) AND (dependency_source_resource_id IS NOT NULL) AND (source_kind IS NOT NULL) AND (source_stable_id IS NOT NULL) AND (source_version_id IS NOT NULL) AND (source_revision IS NOT NULL) AND (source_hash IS NOT NULL) AND (title IS NOT NULL) AND (content_text IS NOT NULL) AND (chunk_recipe_hash IS NOT NULL) AND (status IS NOT NULL) AND (created_by IS NOT NULL) AND (created_at IS NOT NULL) AND ((source_kind IN (
    'card_version','chapter_body_version','canonical_fact','knowledge_state_change','state_change',
    'story_event_timing','story_event_relation','planning_version','research_document_version',
    'research_record_version','research_reference_pack_version','prompt_component','ai_task_attempt',
    'quality_issue_evidence','asset_parsed_text'
  )) IS NOT FALSE) AND ((source_revision>0) IS NOT FALSE) AND ((source_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((length(content_text)>0) IS NOT FALSE) AND ((chunk_recipe_hash ~ '^[a-f0-9]{64}$') IS NOT FALSE) AND ((status IN ('current','stale','archived')) IS NOT FALSE) AND (((status='current' AND stale_at IS NULL) OR (status<>'current' AND stale_at IS NOT NULL)) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,space_id uuid,book_id uuid,profile_version_id uuid,dependency_source_resource_id uuid,source_kind text,source_stable_id uuid,source_version_id uuid,source_revision integer,source_hash char(64),title text,content_text text,chunk_recipe_hash char(64),status text,created_by text,created_at timestamptz,stale_at timestamptz)`,
 chunking_request:`SELECT (id IS NOT NULL) AND (book_id IS NOT NULL) AND (source_snapshot_id IS NOT NULL) AND (profile_version_id IS NOT NULL) AND (expected_source_hash IS NOT NULL) AND (status IS NOT NULL) AND (attempt_count IS NOT NULL) AND (idempotency_key IS NOT NULL) AND (last_error IS NOT NULL) AND (created_at IS NOT NULL) AND ((status IN ('pending','running','succeeded','failed','stale','cancelled')) IS NOT FALSE) AND ((attempt_count>=0) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,book_id uuid,source_snapshot_id uuid,profile_version_id uuid,expected_source_hash char(64),status text,attempt_count integer,idempotency_key text,last_error text,created_at timestamptz,started_at timestamptz,completed_at timestamptz)`,
 ai_contract_publication:`SELECT (id IS NOT NULL) AND (entity_kind IS NOT NULL) AND (entity_id IS NOT NULL) AND (to_version_id IS NOT NULL) AND (entity_revision IS NOT NULL) AND (action IS NOT NULL) AND (actor IS NOT NULL) AND (idempotency_key IS NOT NULL) AND (created_at IS NOT NULL) AND ((entity_kind IN ('prompt_recipe','task_contract','model_route')) IS NOT FALSE) AND ((entity_revision>0) IS NOT FALSE) AND ((action IN ('publish','rollback','republish')) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,entity_kind text,entity_id uuid,from_version_id uuid,to_version_id uuid,entity_revision integer,action text,actor text,idempotency_key text,created_at timestamptz)`,
 context_manifest_slot:`SELECT (id IS NOT NULL) AND (manifest_id IS NOT NULL) AND (slot_key IS NOT NULL) AND (sort_order IS NOT NULL) AND (required IS NOT NULL) AND ((sort_order>=0) IS NOT FALSE) AND ((token_budget IS NULL OR token_budget>=0) IS NOT FALSE) AS valid FROM jsonb_to_record($1::jsonb) AS row(id uuid,manifest_id uuid,slot_key text,sort_order integer,required boolean,token_budget integer)`,
};
