import BookClassificationPanel from '../bookClassification';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {BookCompositionWorkspace} from '../../common/bookComposition';
import type {BookReading,ReadingScope} from '../../common/bookshelf';
import type {CompositionEditorState} from '../bookComposition/draftRecovery';
import {readStoryFormat,storyFormatDescription} from '../../common/storyFormat';
import {newDesignApi} from '../api';
import {ChapterWritingPage} from '../chapterWriting';
import ProductionDirectorPage from '../productionDirector';
import Help from '../storyWorkspace/Help';
import './simple.css';

export default function SimpleCreationPage({bookId,short=false}:{bookId:string;short?:boolean}) {
 const [workspace,setWorkspace]=useState<BookCompositionWorkspace|null>(null),[selected,setSelected]=useState(()=>new URLSearchParams(location.search).get('chapter')??''),[tab,setTab]=useState<'read'|'edit'|'director'>('read'),[scope,setScope]=useState<ReadingScope>('adopted'),[reading,setReading]=useState<BookReading|null>(null),[error,setError]=useState(''),[readError,setReadError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[blocked,setBlocked]=useState(false);
 const [classificationGuard,setClassificationGuard]=useState({blocked:false,dirty:false});
 const sequence=useRef(0),readSequence=useRef(0),editor=useRef<CompositionEditorState>({dirty:false,locked:false,preserveDraft:()=>true}),director=useRef({blocked:false,dirty:false});
 const root=`/new-design/books/${bookId}`,format=readStoryFormat(workspace?.planning.objects.find(object=>object.level==='story'&&object.status==='active')?.adoptedVersion?.content.storyFormat),chapters=workspace?.writing.chapters??[],chapter=chapters.find(chapter=>chapter.chapterCardId===selected)??null;
 const readable=reading?.bookId===bookId&&reading.scope===scope&&reading.selected?.cardId===chapter?.chapterCardId;
 const shapeIssue=short&&(format?.form!=='short_story'||chapters.length!==1);
 const receiveEditor=useCallback((state:CompositionEditorState)=>{editor.current=state;setBlocked(state.locked);},[]);
 const receiveDirector=useCallback((state:{blocked:boolean;dirty:boolean})=>{director.current=state;setBlocked(state.blocked);},[]);
 const preserve=()=>{if(editor.current.locked||director.current.blocked||classificationGuard.blocked){setError('原请求待核对或确认未完成，请留在原面板核对；填写和原凭证保留。');return false;}if(classificationGuard.dirty&&!window.confirm('作品分类填写尚未保存；保留本地填写并切换？'))return false;if(editor.current.dirty&&!editor.current.preserveDraft()){setError('本地正文稿件未能保留，请先核对网站存储再切换。');return false;}return true;};
 useEffect(()=>{const token=++sequence.current;setBusy(true);void newDesignApi.getBookCompositionWorkspace(bookId).then(value=>{if(token!==sequence.current)return;if(value.bookId!==bookId||value.book.id!==bookId||value.planning.bookId!==bookId||value.writing.bookId!==bookId)throw new Error('作品与规划正文来源不一致，原选择保留。');setWorkspace(value);setSelected(prior=>prior||value.writing.chapters[0]?.chapterCardId||'');setError('');}).catch(error=>{if(token===sequence.current)setError(error instanceof Error?error.message:'作品目录未读取。');}).finally(()=>{if(token===sequence.current)setBusy(false);});return()=>{sequence.current++;};},[bookId,revision]);
 useEffect(()=>{const token=++readSequence.current;setReading(null);setReadError('');setLoading(false);if(!chapter?.documentId||tab!=='read'||shapeIssue)return;setLoading(true);void newDesignApi.getBookReading(bookId,chapter.documentId,scope).then(value=>{if(token!==readSequence.current)return;if(value.bookId!==bookId||value.scope!==scope||value.selected?.cardId!==chapter.chapterCardId||short&&value.chapters.length!==1)throw new Error('所选原稿件未找到或来源已变化，不换用另一版本。');setReading(value);}).catch(error=>{if(token===readSequence.current)setReadError(error instanceof Error?error.message:'原稿件未读取。');}).finally(()=>{if(token===readSequence.current)setLoading(false);});return()=>{readSequence.current++;};},[bookId,chapter?.documentId,chapter?.chapterCardId,tab,scope,short,shapeIssue,revision]);
 const navigate=(next:typeof tab)=>{if(!preserve())return;editor.current={dirty:false,locked:false,preserveDraft:()=>true};director.current={blocked:false,dirty:false};setBlocked(false);setTab(next);};
 const choose=(id:string)=>{if(!preserve())return;setSelected(id);const url=new URL(location.href);url.searchParams.set('chapter',id);history.replaceState(null,'',url);};
 return <main className="nd-shell nd-simple"><header className="nd-page-header"><div><a href="/new-design/books" onClick={event=>{if(!preserve())event.preventDefault();}}>我的书架</a><h1>{workspace?.book.name??(short?'短篇创作':'简易创作')} <Help label={short?'短篇创作':'简易创作'}>阅读只读取原正文版本，已保存稿可以包含未采用候选；编辑、诊断、采用和变化确认仍使用原章节流程。导演只准备候选，采用及稳定结算需分别确认。切换面板会保留本地稿件，未知原请求先核对。</Help></h1><p>{format?storyFormatDescription(format):'从原章节计划、候选和采用正文继续创作。'}</p></div><div className="nd-row-actions"><button className="nd-button" disabled={busy||blocked} onClick={()=>{if(preserve())setRevision(value=>value+1);}}>只读刷新作品</button><a className="nd-button" href={root+'/overview'} onClick={event=>{if(!preserve())event.preventDefault();}}>专业工作台</a><a className="nd-button" href={root+'/completion'} onClick={event=>{if(!preserve())event.preventDefault();}}>导出作品</a></div></header>
  {busy&&<p role="status">读取原作品目录…</p>}{error&&<p role="alert" className="nd-message is-error">{error}</p>}
  {workspace&&<><details><summary>作品分类与默认创作体验</summary><BookClassificationPanel key={bookId} bookId={bookId} onGuardChange={setClassificationGuard}/></details>{!short&&format?.form==='short_story'&&<a className="nd-button" href={root+'/short-story'} onClick={event=>{if(!preserve())event.preventDefault();}}>打开本书整篇短篇工作区</a>}<section className="nd-simple-stats"><span>章节计划 {chapters.filter(chapter=>chapter.hasAdoptedPlan).length} / {chapters.length} 已采用</span><span>正文候选 {chapters.reduce((sum,chapter)=>sum+chapter.candidateCount,0)} 个</span><span>正式正文 {chapters.filter(chapter=>chapter.adoptedBodyVersionId).length} 章</span><span>稳定结算 {chapters.filter(chapter=>chapter.state==='stable').length} 章</span><span>待处理问题 {chapters.reduce((sum,chapter)=>sum+chapter.openIssueCount,0)} 项</span></section><nav className="nd-row-actions" aria-label="创作面板">{([['read',short?'阅读整篇':'阅读章节'],['edit',short?'编辑与完善整篇':'编辑与完善章节'],['director','AI 创作进度']] as const).map(([key,label])=><button className="nd-button" type="button" aria-pressed={tab===key} disabled={blocked||shapeIssue} key={key} onClick={()=>navigate(key)}>{label}</button>)}<a className="nd-button" href={root+'/story-setting'} onClick={event=>{if(!preserve())event.preventDefault();}}>创作资料</a><a className="nd-button" href={root+'/knowledge'} onClick={event=>{if(!preserve())event.preventDefault();}}>知识参考</a><a className="nd-button" href={root+'/planning?stage=structured'} onClick={event=>{if(!preserve())event.preventDefault();}}>故事与章节计划</a></nav>
   {shapeIssue?<section role="alert"><h2>短篇来源需要核对</h2><p>正式故事总纲须明确为短篇，并有唯一整篇正文计划。当前来源不满足此约定，请回原规划核对；原正文和候选保持。</p><a href={root+'/planning?stage=structured'}>核对原故事规划</a></section>:tab==='director'?<ProductionDirectorPage key={bookId} bookId={bookId} embedded onCloseGuardChange={receiveDirector}/>:<div className="nd-simple-workspace">{!short&&<aside aria-label="原章节目录">{chapters.map(item=><button type="button" className="nd-button" aria-pressed={item.chapterCardId===selected} disabled={blocked||busy} key={item.chapterCardId} onClick={()=>choose(item.chapterCardId)}><small>{item.volumeTitle}</small><strong>{item.logicalOrder} · {item.title}</strong><span>{item.state==='stable'?'已稳定':item.adoptedBodyVersionId?'已有采用正文':`${item.candidateCount} 个候选`}{item.openIssueCount?` · ${item.openIssueCount} 项问题`:''}</span></button>)}</aside>}<section>{!chapter?<><h2>尚无所选章节</h2><p>先准备并采用章节计划；指定原章节未找到时不会换用其他章节。</p><a href={root+'/planning?stage=structured'}>准备章节计划</a></>:tab==='edit'?<ChapterWritingPage key={`${bookId}:${chapter.chapterCardId}`} bookId={bookId} embedded initialChapterCardId={chapter.chapterCardId} onEditorStateChange={receiveEditor} onSaved={async()=>{setRevision(value=>value+1);}}/>:<><div className="nd-row-actions"><h2>{short?'整篇正文':chapter.title}</h2><label>阅读版本<select value={scope} disabled={loading} onChange={event=>setScope(event.target.value as ReadingScope)}><option value="adopted">正式采用正文</option><option value="saved">已保存稿（含未采用候选）</option></select></label><button className="nd-button" type="button" onClick={()=>navigate('edit')}>编辑、诊断与采用</button></div>{loading&&<p role="status">读取所选原稿件…</p>}{readError&&<p role="alert">{readError}</p>}{readable&&reading?.selected?<><p>原正文版本 v{reading.selected.version} · {reading.selected.wordCount.toLocaleString('zh-CN')} 字 · {reading.selected.adopted?reading.selected.stable?'已采用，已稳定':'已采用，待稳定':'未采用候选'}</p>{reading.review&&<section aria-label="此版本审校状态"><p>审校状态：{{unreviewed:'尚未审校',reviewing:'审校结果待核对',quality_debt:'已保存，待优化',replan_required:'等待重规划',attention:'等待原来源处理',reviewed:'已有有效审校报告',stale:'原审校依据已变化'}[reading.review.status]}{reading.review.issueCount!==null?` · ${reading.review.issueCount} 项待处理问题`:''}</p><p>{reading.review.summary}</p>{reading.review.reportId&&<a href={root+'/views/quality?report='+reading.review.reportId} onClick={event=>{if(!preserve())event.preventDefault();}}>查看原审校报告与后续修复</a>}</section>}<article className="nd-simple-reading">{reading.selected.content}</article>{short&&reading.selected.adopted&&<a className="nd-button" href={`/new-design/books/new?method=reference&mode=automatic&form=long_novel&sourceBook=${bookId}&sourceDocument=${reading.selected.id}&sourceBody=${reading.selected.versionId}`}>以此采用短篇发展长篇</a>}</>:!loading&&!readError&&<p>此稿件尚无正文。可先生成或保存候选，再明确采用；保存稿与正式稿可分别阅读。</p>}</>}</section></div>}</>}
 </main>;
}
