import type {ChapterSettlementCategory,ChapterSettlementRisk,KnowledgeAcquisitionMethod,KnowledgeStance} from "../../../common/contracts";

export interface SettlementEditorDraft {category:ChapterSettlementCategory;title:string;subjectId:string;fieldId:string;selectedSpecificationHash:string;selectedBaselineHash:string;selectedBaselineValue:unknown;selectedBaselineDisplay:string;itemRevision:number|null;initialValue:unknown;afterValue:unknown;riskLevel:ChapterSettlementRisk;evidence:string;evidenceStart:number|null;reason:string;holderId:string;stance:KnowledgeStance;acquisitionMethod:KnowledgeAcquisitionMethod;}
export const categoryLabels:Record<ChapterSettlementCategory,string>={fact:"确定事实",knowledge:"角色所知",character_state:"人物状态",relationship:"资料关系状态",prop:"道具状态",event:"事件对象状态",foreshadow:"伏笔进度"};
export const riskLabels:Record<ChapterSettlementRisk,string>={low:"低风险",medium:"需留意",high:"重要变化",critical:"核心变化"};
export const stanceLabels:Record<KnowledgeStance,string>={knows:"知道",believes:"相信",suspects:"怀疑",misunderstands:"误解",unknown:"不知道"};
export const acquisitionLabels:Record<KnowledgeAcquisitionMethod,string>={witnessed:"亲眼见到",told:"听人告知",inferred:"推断得出",read:"阅读得知",narration:"叙述告知读者",assumed:"自行假定",forgotten:"已经忘记",manual:"作者明确记录"};
export function emptySettlementDraft():SettlementEditorDraft{return {category:"character_state",title:"",subjectId:"",fieldId:"",selectedSpecificationHash:"",selectedBaselineHash:"",selectedBaselineValue:null,selectedBaselineDisplay:"尚未选择",itemRevision:null,initialValue:null,afterValue:null,riskLevel:"medium",evidence:"",evidenceStart:null,reason:"",holderId:"",stance:"knows",acquisitionMethod:"manual"};}
export function copySettlementDraft(draft:SettlementEditorDraft):SettlementEditorDraft{return {...draft,selectedBaselineValue:Array.isArray(draft.selectedBaselineValue)?[...draft.selectedBaselineValue]:draft.selectedBaselineValue,initialValue:Array.isArray(draft.initialValue)?[...draft.initialValue]:draft.initialValue,afterValue:Array.isArray(draft.afterValue)?[...draft.afterValue]:draft.afterValue};}
export function settlementDraftDirty(draft:SettlementEditorDraft,editingId:string|null):boolean{return editingId!==null||draft.title!==""||draft.subjectId!==""||draft.evidence!==""||draft.reason!=="";}
export function needsSettlementBaseline(category:ChapterSettlementCategory):boolean{return category!=="fact"&&category!=="knowledge";}
export function settlementControlKey(key:string):string|null {if(key.startsWith("decisions."))return null;const leaf=key.split(".").at(-1)??key;const mapped:Record<string,string>={value:"initialValue",beforeValue:"afterValue",baselineHash:"afterValue",specificationHash:"stateKey",holderCardId:"holderKey",subjectCardId:"subjectId",evidenceEnd:"evidenceStart",changeValue:"afterValue"};const target=mapped[leaf]??leaf;return ["subjectId","stateKey","afterValue","title","reason","evidenceStart","holderKey","initialValue"].includes(target)?target:null;}
export function evidencePositions(content:string,excerpt:string):number[]{if(!excerpt.trim())return [];const positions:number[]=[];let offset=0;while(offset<=content.length){const found=content.indexOf(excerpt,offset);if(found<0)break;positions.push(found);offset=found+1;}return positions;}
export function settlementFieldLabel(key:string):string {const labels:Record<string,string>={subjectId:"变化对象",subjectCardId:"变化对象",fieldId:"记录字段",fieldChoiceId:"记录字段",stateKey:"记录字段",specificationHash:"正式字段规格",baselineHash:"变化前基线",initialValue:"初始状态",value:"初始状态",afterValue:"变化后",beforeValue:"变化前基线",title:"变化标题",reason:"变化原因",evidenceStart:"正文证据位置",evidenceEnd:"正文证据位置",holderCardId:"知情人物",holderKey:"知情对象",stance:"所知态度",acquisitionMethod:"获知方式",expectedRevision:"章节修订",expectedProjectionRevision:"前值基线",idempotencyKey:"提交凭证"};return labels[key.split(".").at(-1)??key]??"结算资料";}
