import type {PoolClient} from "pg";
import type {AdoptCreationPreparationInput,CreationPreparationOutput,CreationPreparationAdoptionReceipt,CreationPreparationTarget} from "../../../common/creationReviewAi";
import {isBlankCreationReviewValue} from "../../../common/creationReviewAi";
import {NewDesignError} from "../../domain/errors";
import {validateBookCreationReviewCards} from "../../domain/bookCreation";
import {stableHash} from "../aiContracts/integrity";
import {readBookCreationSessionInTransaction} from "../bookCreationStore";
import {getCreationPreparationContext} from "./commands";
import {creationCardsHash,validateFormalReview} from "./policy";
import {appendCreationReceipt,priorCreationReceipt,lockCreationRequest,lockCreationSession,updateCreationSession} from "./repository";
import {findRecordCard} from '../recordCards';

export type PreparationAdoptionCommand=AdoptCreationPreparationInput&{batchId:string;frozenSessionRevision:number;templateVersionId:string;specificationHash:string;output:CreationPreparationOutput};
type FrozenPreparationPlan={input:{catalog:{reviewCardsHash:string};targets:CreationPreparationTarget[];specificationHash:string;sessionRevision:number};inputHash:string;sourceBatches?:Array<{id:string;outputHash:string;inputHash:string}>};
type CandidateOrigin={batchId:string;target:CreationPreparationTarget;candidate:CreationPreparationOutput["candidates"][number]};
async function readCandidateOrigins(client:PoolClient,sessionId:string,batch:Record<string,any>,plan:FrozenPreparationPlan):Promise<{cards:Map<string,CandidateOrigin>;outputs:CreationPreparationOutput[]}>{
 const sources=plan.sourceBatches??[],ids=new Set<string>(),rows:Array<Record<string,any>>=[];
 for(const source of sources){if(ids.has(source.id)||source.id===String(batch.id))throw new NewDesignError("累计候选的来源批次重复，原结果保留，请核对准备记录。",409);ids.add(source.id);const previous=await findRecordCard(client,source.id,'ai_generation_batch',{lock:true});if(!previous||previous.session_id!==sessionId||previous.status!=="review"||previous.preparation_terminal||previous.frozen_plan?.inputHash!==source.inputHash||stableHash(previous.output_payload)!==source.outputHash)throw new NewDesignError("前阶段候选来源已变化，不能将其冒充本次生成结果。",409);rows.push(previous);}
 rows.push(batch);const cards=new Map<string,CandidateOrigin>(),outputs:CreationPreparationOutput[]=[];
 for(const source of rows){const frozen=source.frozen_plan as FrozenPreparationPlan,raw=source.preparation_generated_output as CreationPreparationOutput|undefined;if(!frozen?.input||frozen.inputHash!==stableHash(frozen.input)||frozen.input.catalog.reviewCardsHash!==plan.input.catalog.reviewCardsHash||!raw||stableHash(raw)!==source.preparation_execution?.providerOutputHash)throw new NewDesignError("模型原始输出或冻结资料来源无法核对；原结果保留，请返回准备记录。",409);outputs.push(raw);
  for(const candidate of raw.candidates){const target=frozen.input.targets.find(t=>t.reviewCardId===candidate.reviewCardId);if(!target||target.typeKey!==candidate.typeKey||target.isNew!==candidate.isNew||cards.has(candidate.reviewCardId))throw new NewDesignError("累计资料候选不属于唯一真实生成位置。",409);cards.set(candidate.reviewCardId,{batchId:String(source.id),target,candidate});}
 }
 return{cards,outputs};
}
/** Caller owns COMMIT; model execution is never performed by this function. */
export async function adoptCreationPreparationInTransaction(client:PoolClient,id:string,input:PreparationAdoptionCommand):Promise<CreationPreparationAdoptionReceipt>{
 await lockCreationRequest(client,id,input.requestKey);const hash=stableHash(JSON.parse(JSON.stringify({operation:"adopt_preparation",sessionId:id,input}))),prior=await priorCreationReceipt<CreationPreparationAdoptionReceipt>(client,id,input.requestKey);if(prior){if(prior.inputHash!==hash)throw new NewDesignError("原采用请求已用于不同候选，请核对原回执。",409);return{...prior.receipt,repeated:true};}
 const row=await lockCreationSession(client,id);if(Number(row.revision)!==input.expectedSessionRevision||row.director_active_command_key||["creating","completed","generating"].includes(String(row.status)))throw new NewDesignError("开书资料或阶段已更新，或自动准备仍在继续；请核对原候选，必要时明确接管后再采用。",409);
 const batch=await findRecordCard(client,input.batchId,'ai_generation_batch',{lock:true});if(!batch||batch.session_id!==id||batch.status!=="review"||!batch.frozen_plan||stableHash(batch.output_payload)!==stableHash(input.output))throw new NewDesignError("候选缺少当前开书的真实已保存模型输出，不能采用。",409);
 const plan=batch.frozen_plan as FrozenPreparationPlan;
 const context=await getCreationPreparationContext(id,client),session=context.session;if(input.templateVersionId!==session.templateVersionId||plan.input.specificationHash!==input.specificationHash||plan.input.sessionRevision!==input.frozenSessionRevision||plan.input.catalog.reviewCardsHash!==context.catalog.reviewCardsHash)throw new NewDesignError("候选模板、对象或资料基线已变化；原模型结果保留，请明确重新核对来源。",409);
 const origins=await readCandidateOrigins(client,id,batch,plan),cards=structuredClone(session.reviewCards),selectedIds=new Set<string>();
 for(const selection of input.selections){if(selectedIds.has(selection.reviewCardId))throw new NewDesignError("采用资料位置不能重复。",422);selectedIds.add(selection.reviewCardId);const candidate=input.output.candidates.find(c=>c.reviewCardId===selection.reviewCardId),origin=origins.cards.get(selection.reviewCardId),target=origin?.target;if(!candidate||!origin||!target||stableHash(candidate)!==stableHash(origin.candidate))throw new NewDesignError("采用对象不属于冻结候选位置。",422);
  let card=cards.find(c=>c.id===selection.reviewCardId);if(!card){if(!target.isNew||!selection.title||!candidate.titleSuggestion?.trim())throw new NewDesignError("新增资料必须明确采用有效中文名称。",422,{[`${selection.reviewCardId}.$title`]:"请明确采用有效中文名称。"});card={id:target.reviewCardId,typeKey:target.typeKey,title:"",values:{},sourceKind:"ai",sourceId:null,sourceVersionId:null,originalTitle:candidate.titleSuggestion,originalValues:structuredClone(candidate.values),aiFieldBatchIds:{}};cards.push(card);}else if(target.isNew||card.typeKey!==target.typeKey)throw new NewDesignError("冻结候选对象与现有资料不一致。",409);
  if(selection.title){if(!target.allowTitle||card.title.trim()||!candidate.titleSuggestion?.trim())throw new NewDesignError("已有资料名称不允许被 AI 候选覆盖；请取消该名称选择。",409,{[`${selection.reviewCardId}.$title`]:"请保留原名称，取消该名称选择。"});card.title=candidate.titleSuggestion;card.aiFieldBatchIds={...card.aiFieldBatchIds,$title:origin.batchId};}
  if(new Set(selection.fieldKeys).size!==selection.fieldKeys.length)throw new NewDesignError("采用字段不能重复。",422);
  const fields=context.schemaTypes.find(t=>t.key===card!.typeKey)?.fields??[];
  for(const key of selection.fieldKeys){if(!target.fieldKeys.includes(key)||!fields.some(f=>f.key===key)||!Object.hasOwn(candidate.values,key))throw new NewDesignError("采用字段不属于本模板冻结白名单。",422,{[`${selection.reviewCardId}.${key}`]:"请取消未知字段选择。"});if(!isBlankCreationReviewValue(card.values[key]))throw new NewDesignError("已有人工或已保存字段不能被 AI 直接覆盖，请保留原值。",409,{[`${selection.reviewCardId}.${key}`]:"请取消该字段选择。"});card.values[key]=structuredClone(candidate.values[key]);card.aiFieldBatchIds={...card.aiFieldBatchIds,[key]:origin.batchId};}
 }
 const validated=validateBookCreationReviewCards(cards,context.templateSnapshot.cardTypes,context.templateSnapshot.dictionaries,false);if(Object.keys(validated.issues).length)throw new NewDesignError("采用资料的字段或字典选择无效；模型结果保留。",422,validated.issues);
 const relationSet=new Set(input.relationIds),planSet=new Set(input.planIds);if(relationSet.size!==input.relationIds.length||planSet.size!==input.planIds.length)throw new NewDesignError("采用关系或规划位置不能重复。",422);for(const key of relationSet){const draft=input.output.relations.find(d=>d.id===key);if(!draft||!origins.outputs.some(output=>output.relations.some(value=>stableHash(value)===stableHash(draft))))throw new NewDesignError("关系候选不是原模型结果。",422);}for(const key of planSet){const draft=input.output.plans.find(d=>d.id===key);if(!draft||!origins.outputs.some(output=>output.plans.some(value=>stableHash(value)===stableHash(draft))))throw new NewDesignError("规划候选不是原模型结果。",422);}
 let formal=session.formalReview??null;
 if(relationSet.size||planSet.size){const changed=creationCardsHash(validated.cards)!==context.catalog.reviewCardsHash;if(formal&&((formal.relations.length||formal.plans.length)&&changed||formal.reviewCardsHash!==context.catalog.reviewCardsHash))throw new NewDesignError("原关系与规划来源需重新核对；保留旧草稿，不能随采用字段自动重定基线。",409);const relations=[...(formal?.relations??[])],plans=[...(formal?.plans??[])];for(const draft of input.output.relations.filter(d=>relationSet.has(d.id))){if(relations.some(d=>d.id===draft.id))throw new NewDesignError("关系草稿已存在，不能覆盖人工审阅。",409);relations.push({...structuredClone(draft),decision:"pending"});}for(const draft of input.output.plans.filter(d=>planSet.has(d.id))){if(plans.some(d=>d.id===draft.id))throw new NewDesignError("规划草稿已存在，不能覆盖人工审阅。",409);plans.push({...structuredClone(draft),decision:"pending"});}
  const catalog={...context.catalog,reviewCardsHash:creationCardsHash(validated.cards)};validateFormalReview({expectedSessionRevision:session.revision,expectedFormalRevision:formal?.revision??null,requestKey:input.requestKey,templateVersionId:session.templateVersionId,reviewCardsHash:catalog.reviewCardsHash,relations,plans},catalog,validated.cards);formal={revision:(formal?.revision??0)+1,templateVersionId:session.templateVersionId,reviewCardsHash:catalog.reviewCardsHash,relations,plans};
 }
 let bookName=session.bookName,description=session.description;const direction=input.directionId?input.output.directions.find(d=>d.id===input.directionId):null;if(input.directionId&&(!direction||!origins.outputs.some(output=>output.directions.some(value=>stableHash(value)===stableHash(direction)))))throw new NewDesignError("方向选择不是原模型结果。",422);const directions=[...session.directionCandidates];if(direction){const existing=directions.find(value=>value.id===direction.id);if(existing&&stableHash(existing)!==stableHash(direction))throw new NewDesignError("同一方向位置已有不同保存结果，请保留原方向并核对来源。",409);if(!existing)directions.push(structuredClone(direction));if(!bookName.trim())bookName=direction.title;if(!description.trim())description=direction.premise;}
 await updateCreationSession(client,row,{review_cards:validated.cards,formal_review:formal,book_name:bookName,description,direction_candidates:directions,selected_direction_id:direction?.id??session.selectedDirectionId,status:'review'});
 const saved=await readBookCreationSessionInTransaction(client,id),receipt:CreationPreparationAdoptionReceipt={sessionId:id,batchId:input.batchId,requestKey:input.requestKey,repeated:false,session:saved,adopted:{reviewCardIds:[...selectedIds],relationIds:[...relationSet],planIds:[...planSet],directionId:input.directionId??null}};await appendCreationReceipt(client,id,hash,receipt);return receipt;
}
