import type {PoolClient} from "pg";
import type {BookCreationSession,BookCreationReviewCard} from "../../../common/contracts";
import type {BookCreationProductionReceipt,SaveBookCreationFormalReviewInput} from "../../../common/bookCreationProduction";
import {NewDesignError} from "../../domain/errors";
import {normalizeBookCreationReview,validateBookCreationReviewCards} from "../../domain/bookCreation";
import {stableHash} from "../aiContracts/integrity";
import {readBookCreationSessionInTransaction} from "../bookCreationStore";
import {createBookInTransaction,type TemplatePayload} from "../templateStore";
import {creationDirectorState,CREATION_DIRECTOR_STAGES} from "../../../common/creationDirector";
import {getCreationPool,lockCreationRequest,lockCreationSession,priorCreationReceipt,appendCreationReceipt,reportCreationFailure} from "./repository";
import {saveFormalReviewInputSchema,creationCatalog,validateFormalReview,creationAiFields} from "./policy";
import {installBookCreationProduction} from "./install";

async function readTemplate(client:PoolClient,id:string):Promise<TemplatePayload>{const row=(await client.query("SELECT payload FROM new_design.template_group_versions WHERE id=$1",[id])).rows[0];if(!row)throw new NewDesignError("本次开书的精确模板版本不可用。",404);return row.payload as TemplatePayload;}
export async function getCreationPreparationContext(id:string,supplied?:PoolClient,lock=false){
 const client=supplied??await(await getCreationPool()).connect();try{if(!supplied)await client.query(lock?"BEGIN ISOLATION LEVEL REPEATABLE READ":"BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");if(lock)await lockCreationSession(client,id);const session=await readBookCreationSessionInTransaction(client,id),payload=await readTemplate(client,session.templateVersionId),catalog=creationCatalog(session.templateVersionId,payload,session.reviewCards);const sourceText=[session.bookName,session.description,session.sourceReference,...Object.values(session.inputPayload).filter((v):v is string=>typeof v==="string"),session.researchPreview?JSON.stringify(session.researchPreview.compiledSnapshot):""].filter(Boolean).join("\n");const result={session,sourceText,templateSnapshot:payload,catalog,schemaTypes:payload.cardTypes.map(type=>({key:type.key,name:type.name,description:type.description,fields:creationAiFields(type.fields,catalog)}))};if(!supplied)await client.query("COMMIT");return result;}catch(error){if(!supplied)await client.query("ROLLBACK");throw error;}finally{if(!supplied)client.release();}
}
export async function getBookCreationProductionWorkspace(id:string){const {session,catalog}=await getCreationPreparationContext(id);return{session,catalog};}
type MutationResult={installed?:BookCreationProductionReceipt["installed"]};
async function mutate(id:string,key:string,expectedRevision:number,operation:BookCreationProductionReceipt["operation"],input:unknown,action:(client:PoolClient,row:Record<string,unknown>)=>Promise<MutationResult>):Promise<BookCreationProductionReceipt>{
 const client=await(await getCreationPool()).connect();let committing=false;try{await client.query("BEGIN");await lockCreationRequest(client,id,key);const hash=stableHash(JSON.parse(JSON.stringify({sessionId:id,operation,input}))),prior=await priorCreationReceipt(client,id,key);if(prior){if(prior.inputHash!==hash)throw new NewDesignError("原保存请求已用于不同内容，请核对原回执。",409);committing=true;await client.query("COMMIT");return{...prior.receipt,repeated:true};}
  const row=await lockCreationSession(client,id);if(Number(row.revision)!==expectedRevision)throw new NewDesignError("开书资料已更新，请核对最新来源后明确重新准备。",409);if(row.director_active_command_key||["generating","creating","completed"].includes(String(row.status)))throw new NewDesignError("当前开书阶段不可修改；自动准备仍在继续时，请先核对结果或明确接管，再保存或开书。",409);
  const result=await action(client,row),session=await readBookCreationSessionInTransaction(client,id),receipt:BookCreationProductionReceipt={sessionId:id,requestKey:key,operation,repeated:false,session,...result};await appendCreationReceipt(client,id,hash,receipt);committing=true;await client.query("COMMIT");return receipt;
 }catch(error){let rollback=false;try{await client.query("ROLLBACK");rollback=true;}catch{}const step=operation==="save_review"?"保存开书资料表单":operation==="save_formal_review"?"保存关系与规划审阅":operation==="complete"?"确认开书并安装正式关系与规划":"创建开书准备";reportCreationFailure(id,error,rollback,committing,step);}finally{client.release();}
}
export async function saveBookCreationFormalReview(id:string,raw:SaveBookCreationFormalReviewInput):Promise<BookCreationProductionReceipt>{
 const input=saveFormalReviewInputSchema.parse(raw);return mutate(id,input.requestKey,input.expectedSessionRevision,"save_formal_review",input,async(client,row)=>{
  const session=await readBookCreationSessionInTransaction(client,id),payload=await readTemplate(client,session.templateVersionId),catalog=creationCatalog(session.templateVersionId,payload,session.reviewCards),current=session.formalReview?.revision??null;if(input.expectedFormalRevision!==current)throw new NewDesignError("关系与规划草稿版本已变化，请核对原回执。",409);validateFormalReview(input,catalog,session.reviewCards);
  const formalReview={revision:(current??0)+1,templateVersionId:session.templateVersionId,reviewCardsHash:catalog.reviewCardsHash,relations:input.relations,plans:input.plans};await client.query("UPDATE new_design.book_creation_sessions SET formal_review=$2::jsonb,revision=revision+1,updated_at=now() WHERE id=$1",[id,JSON.stringify(formalReview)]);return{};
 });
}
export async function saveBookCreationReviewCommand(id:string,input:{bookName:string;description:string;reviewCards:BookCreationReviewCard[];revision:number;requireComplete?:boolean;requestKey:string}):Promise<BookCreationSession>{
 return(await mutate(id,input.requestKey,input.revision,"save_review",input,async(client,row)=>{
  const payload=await readTemplate(client,String(row.template_version_id)),validated=validateBookCreationReviewCards(normalizeBookCreationReview(input.reviewCards,(row.review_cards??[]) as BookCreationReviewCard[]),payload.cardTypes,payload.dictionaries,input.requireComplete??false);if(Object.keys(validated.issues).length)throw new NewDesignError("开书表单中仍有内容需要修改。",422,validated.issues);const inputPayload=row.input_payload;if(!inputPayload||typeof inputPayload!=="object"||Array.isArray(inputPayload))throw new NewDesignError("开书会话的阶段数据格式异常，请保留草稿并核对原会话。",422,{inputPayload:"阶段数据必须为受控对象。"});const director=creationDirectorState(inputPayload as Record<string,unknown>),stage=director&&director.cursor<CREATION_DIRECTOR_STAGES.length?`director_${CREATION_DIRECTOR_STAGES[director.cursor].key}`:"review_initial_content";
  await client.query("UPDATE new_design.book_creation_sessions SET book_name=$2,description=$3,review_cards=$4::jsonb,status='review',stage=$5,error_message=NULL,revision=revision+1,updated_at=now() WHERE id=$1",[id,input.bookName,input.description,JSON.stringify(validated.cards),stage]);return{};
 })).session;
}
export async function completeBookCreationCommand(id:string,input:{keepCurrentResult?:boolean;expectedRevision:number;requestKey:string}):Promise<BookCreationSession>{
 return(await mutate(id,input.requestKey,input.expectedRevision,"complete",input,async(client,row)=>{
  const session=await readBookCreationSessionInTransaction(client,id);if(session.status!=="review")throw new NewDesignError("请先审阅开书内容。",422);if(!session.bookName.trim())throw new NewDesignError("请填写书名。",422,{bookName:"请填写书名。"});const director=creationDirectorState(session.inputPayload);if(director?.activeBatchId)throw new NewDesignError("当前阶段仍在准备，请先核对其结果。",409);if(director&&director.mode!=="manual"&&!CREATION_DIRECTOR_STAGES.every(stage=>director.completedStages.includes(stage.key)))throw new NewDesignError("请完成各阶段准备，或明确选择人工接管。",422);
  const payload=await readTemplate(client,session.templateVersionId),validated=validateBookCreationReviewCards(session.reviewCards,payload.cardTypes,payload.dictionaries,true);if(Object.keys(validated.issues).length)throw new NewDesignError("请补齐开书资料后再创建。",422,validated.issues);const catalog=creationCatalog(session.templateVersionId,payload,validated.cards),review=session.formalReview??{revision:1,templateVersionId:session.templateVersionId,reviewCardsHash:catalog.reviewCardsHash,relations:[],plans:[]};validateFormalReview({...review,expectedSessionRevision:session.revision,expectedFormalRevision:review.revision,requestKey:input.requestKey},catalog,validated.cards,true);
  const research=(await client.query("SELECT * FROM new_design.book_creation_research_selections WHERE session_id=$1 ORDER BY sort_order",[id])).rows.map(r=>({researchVersionId:r.research_version_id?String(r.research_version_id):null,packVersionId:r.pack_version_id?String(r.pack_version_id):null,purpose:String(r.purpose),compiledSnapshot:r.compiled_snapshot as Record<string,unknown>}));const latestBatch=(await client.query("SELECT id FROM new_design.ai_generation_batches WHERE session_id=$1 AND operation='initial_content' AND status='review' ORDER BY created_at DESC LIMIT 1",[id])).rows[0];
  await client.query("UPDATE new_design.book_creation_sessions SET status='creating',stage='install_template',progress=88 WHERE id=$1",[id]);const created=await createBookInTransaction(client,{key:`book_${id.replace(/-/g,"")}`,name:session.bookName.trim(),description:session.description.trim(),templateVersionId:session.templateVersionId},{includeTemplateSeed:false,reviewCards:validated.cards,researchReferences:research,origin:{sessionId:id,method:session.method,sourceReference:session.sourceReference,sourcePayload:session.inputPayload,generationBatchId:latestBatch?.id?String(latestBatch.id):undefined}});
  const installed=await installBookCreationProduction(client,created.book.id,created.book.spaceId,review,created.installed,input.requestKey);await client.query("UPDATE new_design.book_creation_sessions SET status='completed',stage='ready',progress=100,book_id=$2,error_message=NULL,revision=revision+1,updated_at=now() WHERE id=$1",[id,created.book.id]);const used=[...new Set(validated.cards.flatMap(card=>Object.values(card.aiFieldBatchIds??{})))];if(used.length)await client.query("UPDATE new_design.ai_generation_batches SET status='applied',updated_at=now() WHERE session_id=$1 AND id=ANY($2::uuid[]) AND status='review'",[id,used]);return{installed};
 })).session;
}
export async function readBookCreationProductionReceipt(id:string,key:string):Promise<BookCreationProductionReceipt|null>{const client=await(await getCreationPool()).connect();try{await client.query("BEGIN");await lockCreationRequest(client,id,key);await lockCreationSession(client,id);const prior=await priorCreationReceipt(client,id,key);await client.query("COMMIT");return prior?{...prior.receipt,repeated:true}:null;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
export async function getBookCreationSessionByRequest(key:string):Promise<BookCreationSession|null>{if(!key||key.length<8||key.length>160)throw new NewDesignError("原开书请求标识无效。",422);const client=await(await getCreationPool()).connect();try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`book_creation_create:${key}`]);const row=(await client.query("SELECT id FROM new_design.book_creation_sessions WHERE creation_request_key=$1",[key])).rows[0],session=row?await readBookCreationSessionInTransaction(client,String(row.id)):null;await client.query("COMMIT");return session;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
