import {useEffect,useRef,useState} from 'react';
import type {ShelfBook,ShelfBookDetail} from '../../common/bookshelf';
import type {AuthorTaskRecord} from '../../common/authorTasks';
import type {DirectorFollowupDetail} from '../../common/directorFollowup';
import {newDesignApi} from '../api';
export default function BookDetails({book,compact=false}:{book:ShelfBook;compact?:boolean}){
 const [data,setData]=useState<ShelfBookDetail|null>(null),[detail,setDetail]=useState<DirectorFollowupDetail|null>(null),[selected,setSelected]=useState<AuthorTaskRecord|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),sequence=useRef(0),flight=useRef(false);
 useEffect(()=>{const token=++sequence.current;setBusy(true);void newDesignApi.getShelfBookDetail(book.id).then(value=>{if(token!==sequence.current)return;if(value.bookId!==book.id||value.records.items.some(item=>item.bookId!==book.id))throw Error('作品信息与原书籍不一致，未替换为其他书。');setData(value);setError('');}).catch(reason=>{if(token===sequence.current)setError(reason instanceof Error?reason.message:'本书任务与用量未读取。');}).finally(()=>{if(token===sequence.current)setBusy(false);});return()=>{sequence.current++;};},[book.id,book.updatedAt,refresh]);
 async function inspect(record:AuthorTaskRecord){if(flight.current)return;flight.current=true;setBusy(true);setError('');setSelected(record);setDetail(null);try{const value=await newDesignApi.directorFollowup.detail(record.kind,record.id);if(value.record.id!==record.id||value.record.kind!==record.kind||value.record.bookId!==book.id)throw Error('原任务详情来源不匹配。');setDetail(value);}catch(reason){setError(reason instanceof Error?reason.message:'原任务详情未读取。');}finally{flight.current=false;setBusy(false);}}
 async function more(){if(!data?.records.nextCursor||flight.current)return;flight.current=true;setBusy(true);try{const next=await newDesignApi.listAuthorTasks({bookId:book.id,cursor:data.records.nextCursor,limit:40});if(next.items.some(item=>item.bookId!==book.id))throw Error('更多任务不属于本书。');setData(current=>current?{...current,records:{...next,items:[...current.records.items,...next.items.filter(item=>!current.records.items.some(old=>old.id===item.id&&old.kind===item.kind))]}}:current);}catch(reason){setError(reason instanceof Error?reason.message:'更多任务未读取。');}finally{flight.current=false;setBusy(false);}}
 const usage=data?.usage;
 return <div className="nd-shelf-details"><div className="nd-shelf-project-facts"><span>人物 {book.characterCount}</span><span>世界 {data?.worlds.map(item=>item.name).join('、')||`${book.worldCount} 份设定`}</span><span>章计划 {book.adoptedChapterPlanCount} / {book.chapterPlanCount} 已采用</span><span>待处理质量 {book.openQualityIssues}</span></div>{usage&&<p className="nd-shelf-facts">AI 调用记录 {usage.totalAttemptCount} 次 · 输入 {usage.inputTokens===null?'未知':usage.inputTokens.toLocaleString()} / 输出 {usage.outputTokens===null?'未知':usage.outputTokens.toLocaleString()} Tokens{usage.unrecordedAttemptCount+usage.unknownUsageCount>0?` · ${usage.unrecordedAttemptCount+usage.unknownUsageCount} 次用量待核对`:''}</p>}
 {compact&&data?.records.items[0]&&<p className="nd-shelf-facts" title={data.records.items[0].recoveryGuidance}>{data.records.items[0].title} · {data.records.items[0].statusLabel}{data.records.items[0].progress!==null?` · 本次任务 ${Math.round(data.records.items[0].progress*100)}%`:''}{data.records.items[0].failedStep?' · 停在：'+data.records.items[0].failedStep:''}</p>}{data&&!compact&&<details><summary>本书推进详情 · {data.records.total} 条</summary><div className="nd-shelf-task-list">{data.records.items.map(record=><article key={record.kind+record.id}><div><strong>{record.title}</strong><p>{record.statusLabel}{record.progress!==null?` · 本次任务 ${Math.round(record.progress*100)}%`:''}</p>{record.failedStep&&<p>停在：{record.failedStep}</p>}<p>{record.retainedResult}</p></div><button className="nd-button" disabled={busy} onClick={()=>void inspect(record)}>查看执行详情</button></article>)}{!data.records.items.length&&<p>尚无本书推进记录。</p>}{data.records.nextCursor&&<button className="nd-button" disabled={busy} onClick={()=>void more()}>继续读取本书记录</button>}</div></details>}
 {selected&&!compact&&<section className="nd-shelf-execution" aria-label="原任务执行详情"><h3>{selected.title}</h3>{detail?<><p>{detail.record.statusLabel} · {detail.record.recoveryGuidance}</p><p>{detail.record.consequence}</p>{detail.steps.map(step=><p key={step.id}>{step.label}：{step.statusLabel}{step.attemptStatusLabel?' · '+step.attemptStatusLabel:''}{step.failureCategoryLabel?' · '+step.failureCategoryLabel:''}{step.leaseExpired?' · 原领取过期':''}</p>)}{detail.stepsTruncated&&<p>步骤超过当前范围，请在原来源查看全部。</p>}<details><summary>本次正式来源与精确版本</summary>{detail.anchors.map((anchor,index)=><p key={index}>{anchor.label} · {anchor.stateLabel}</p>)}{detail.anchorsTruncated&&<p>来源超过当前范围，请回原来源核对全部。</p>}</details>{detail.notes.map((note,index)=><p key={index}>{note}</p>)}{detail.navigation.available&&<a className="nd-button" href={detail.navigation.route}>{detail.navigation.label}</a>}</>:busy?<p role="status">正在读取原任务步骤与来源…</p>:<button className="nd-button" onClick={()=>void inspect(selected)}>重新读取此原任务</button>}</section>}
 {error&&<p role="alert">{error}<button className="nd-button" disabled={busy} onClick={()=>setRefresh(value=>value+1)}>重新读取本书信息</button></p>}</div>;
}
