import {useEffect,useRef,useState} from 'react';
import type {ShelfBook} from '../../common/bookshelf';
import type {DirectorRun,DirectorReceipt,DirectorCommand} from '../../common/productionDirector';
import {directorPendingKey,parseDirectorPending,retainDirectorPending,type DirectorPending} from '../productionDirector';
import {ApiError,newDesignApi} from '../api';
function continuation(run:DirectorRun):DirectorCommand['action']|null{
 if(run.status==='ready')return 'run';
 if(run.status==='paused')return 'resume';
 if(run.status==='failed'&&!run.chapters.some(item=>item.status==='unknown'||item.status==='running'||item.ledgerPending||item.boundaryPending||item.decision==='stop_for_replan')&&run.chapters.some(item=>item.status==='pending'||item.status==='failed'))return 'retry_failed';
 if((run.status==='waiting_recovery'||run.status==='running'&&run.leaseExpired)&&run.chapters.filter(item=>item.status==='running'||item.status==='unknown'||item.ledgerPending||item.boundaryPending).every(item=>item.modelResultSaved))return 'resume';
 return null;
}
export default function DirectorQuickAction({book,onInspect,onChanged}:{book:ShelfBook;onInspect:()=>void;onChanged:()=>void}){
 const [run,setRun]=useState<DirectorRun|null>(null),[pending,setPending]=useState<DirectorPending|null>(null),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[notWritten,setNotWritten]=useState(false),[checked,setChecked]=useState(false),flight=useRef(false),sequence=useRef(0);
 useEffect(()=>{const token=++sequence.current;try{const raw=sessionStorage.getItem(directorPendingKey(book.id));if(raw)setPending(parseDirectorPending(raw,book.id));}catch{setBlocked(true);setMessage('原导演凭证未读取，请打开驾驶舱核对。');}if(book.latestDirector)void newDesignApi.getDirectorRun(book.id,book.latestDirector.id).then(value=>{if(token!==sequence.current)return;if(value.bookId!==book.id||value.id!==book.latestDirector?.id)throw Error('原导演范围不匹配。');setRun(value);}).catch(reason=>{if(token===sequence.current)setMessage(reason instanceof Error?reason.message:'导演状态未读取。');});return()=>{sequence.current++;};},[book.id,book.latestDirector?.id,book.updatedAt]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(pending||busy||blocked){event.preventDefault();event.returnValue='';}};addEventListener('beforeunload',leave);return()=>removeEventListener('beforeunload',leave);},[pending,busy,blocked]);
 function accept(receipt:DirectorReceipt,original:DirectorPending){if(original.kind!=='command'||receipt.requestKey!==original.input.requestKey||receipt.action!==original.input.action||receipt.run.bookId!==book.id||receipt.run.id!==original.runId)throw Error('原导演命令回执不一致，请保留完整凭证。');sessionStorage.removeItem(directorPendingKey(book.id));setPending(null);setNotWritten(false);setChecked(false);setRun(receipt.run);setMessage('原导演命令已确认；已有候选和人工正文保留。');onChanged();}
 async function execute(){if(!run||busy||pending||blocked||flight.current)return;const action=continuation(run);if(!action)return;if(!window.confirm('明确继续本书所选章节范围？原候选和人工正文保留，后续生成可能产生模型用量。'))return;const original:DirectorPending={bookId:book.id,kind:'command',runId:run.id,input:{requestKey:crypto.randomUUID(),expectedRevision:run.revision,action}};try{retainDirectorPending(original);}catch{setBlocked(true);setMessage('原命令无法保留，尚未提交，请打开驾驶舱核对存储。');return;}flight.current=true;setPending(original);setNotWritten(false);setChecked(false);setBusy(true);try{accept(await newDesignApi.controlDirectorRun(book.id,run.id,original.input),original);}catch(reason){setNotWritten(reason instanceof ApiError&&reason.recovery?.mutationOutcome==='not_written');setMessage(reason instanceof Error?reason.message:'原继续命令结果待核对，不重新执行。');}finally{flight.current=false;setBusy(false);}}
 async function check(){if(!pending||flight.current)return;flight.current=true;setBusy(true);try{const receipt=await newDesignApi.getDirectorReceipt(book.id,pending.input.requestKey);setChecked(true);if(receipt)accept(receipt,pending);else setMessage('未找到原回执不证明未执行，保留原输入，不重发命令；请打开驾驶舱核对原结果。');}catch(reason){setMessage(reason instanceof Error?reason.message:'原回执未读取。');}finally{flight.current=false;setBusy(false);}}
 const action=run?continuation(run):null;
 return <div className="nd-shelf-quick-director">{pending?<button className="nd-button" disabled={busy} onClick={()=>void check()}>{busy?'正在核对…':'核对原继续命令'}</button>:action?<button className="nd-button nd-button-primary" disabled={busy||blocked} onClick={()=>void execute()}>{action==='retry_failed'?'明确继续失败或未执行章':action==='run'?'开始所选章节范围':'继续自动执行原范围'}</button>:null}{pending&&notWritten&&checked&&<button className="nd-button" disabled={busy} onClick={()=>{try{sessionStorage.removeItem(directorPendingKey(book.id));setPending(null);setChecked(false);setNotWritten(false);setMessage('原命令已确认未写入，请打开驾驶舱重新读取并核对范围。');setRun(null);}catch{setBlocked(true);}}}>保留范围并重新准备</button>}<button className="nd-button" onClick={onInspect}>查看原导演范围</button>{message&&<p role="status">{message}</p>}</div>;
}
