import {useEffect,useRef,useState} from 'react';
import type {BookshelfSnapshot,ShelfBook,ShelfFilter,ShelfSort,RecycledBook,BookLifecycleInput} from '../../common/bookshelf';
import {selectShelf,shelfAction,shelfProgress,shelfAttention} from '../../common/bookshelf/presentation';
import {hasLiveWork} from '../../common/home/presentation';
import {ApiError,newDesignApi} from '../api';
import Help from '../storyWorkspace/Help';
import './bookshelf.css';
type Pending={bookId:string;input:BookLifecycleInput};
const STORAGE='new-design:bookshelf:lifecycle';
const filters:[ShelfFilter,string][]=[['all','全部作品'],['running','正在推进'],['attention','需要核对'],['readable','已有正文'],['preparing','准备故事']];
const sorts:[ShelfSort,string][]=[['updated','最近更新'],['created','最近创建'],['progress','采用正文进度']];
function retained():Pending|null {const raw=sessionStorage.getItem(STORAGE);if(!raw)return null;const value=JSON.parse(raw) as Pending;if(!value||!/^([a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12})$/i.test(value.bookId)||!['archive','restore'].includes(value.input?.action)||!Number.isSafeInteger(value.input.expectedRevision)||value.input.expectedRevision<1)throw Error('原归档凭证无法读取，请保留此页。');return value;}
function date(value:string){return new Date(value).toLocaleDateString('zh-CN');}
function Cover({book}:{book:ShelfBook}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[book.cover?.versionId]);return <div className="nd-shelf-cover">{book.cover?.integrity==='verified'&&!failed?<img src={newDesignApi.visualImageUrl(book.id,book.cover.assetId,book.cover.versionId)} alt={`《${book.name}》封面`} loading="lazy" onError={()=>setFailed(true)}/>:<><span>我的作品</span><strong>{book.name}</strong><small>{book.cover?'封面文件待核对':'未设置封面'}</small></>}</div>;}
export default function BookshelfPage(){
 const query=new URLSearchParams(location.search),[snapshot,setSnapshot]=useState<BookshelfSnapshot|null>(null),[view,setView]=useState<'shelf'|'workbench'|'trash'>(query.get('view')==='trash'?'trash':query.get('view')==='workbench'?'workbench':'shelf'),[search,setSearch]=useState(query.get('q')??''),[filter,setFilter]=useState<ShelfFilter>(filters.some(([key])=>key===query.get('status'))?query.get('status') as ShelfFilter:'all'),[sort,setSort]=useState<ShelfSort>(sorts.some(([key])=>key===query.get('sort'))?query.get('sort') as ShelfSort:'updated'),[page,setPage]=useState(Math.max(1,Number(query.get('page'))||1));
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<Pending|null>(null),[storageBroken,setStorageBroken]=useState(false),[confirm,setConfirm]=useState<{book:ShelfBook|RecycledBook;action:'archive'|'restore'}|null>(null);
 const generation=useRef(0),inFlight=useRef(false),dialog=useRef<HTMLDialogElement>(null),mounted=useRef(true);
 const [sources,setSources]=useState<Array<{label:string;href:string}>>([]);
 const load=async()=>{const seq=++generation.current;setLoading(true);try{const data=await newDesignApi.getBookshelf();if(seq!==generation.current||!mounted.current)return;setSnapshot(data);setError('');}catch(reason){if(seq===generation.current&&mounted.current)setError(reason instanceof Error?reason.message:'书架未读取完整；已有作品与草稿保留。');}finally{if(seq===generation.current&&mounted.current)setLoading(false);}};
 useEffect(()=>{mounted.current=true;try{setPending(retained());}catch(reason){setStorageBroken(true);setError(reason instanceof Error?reason.message:'原请求未读取。');}void load();return()=>{mounted.current=false;generation.current++;};},[]);
 useEffect(()=>{const next=new URLSearchParams();if(view!=='shelf')next.set('view',view);if(search)next.set('q',search);if(filter!=='all')next.set('status',filter);if(sort!=='updated')next.set('sort',sort);if(page>1)next.set('page',String(page));history.replaceState(history.state,'',location.pathname+(next.size?'?'+next.toString():''));},[view,search,filter,sort,page]);
 useEffect(()=>{if(!confirm)return;const focus=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>{dialog.current?.close();focus?.focus();};},[confirm]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(pending||busy||storageBroken){event.preventDefault();event.returnValue='';}};addEventListener('beforeunload',leave);return()=>removeEventListener('beforeunload',leave);},[pending,busy,storageBroken]);
 const change=async()=>{if(!confirm||inFlight.current||pending||storageBroken)return;const original:Pending={bookId:confirm.book.id,input:{action:confirm.action,expectedRevision:confirm.book.revision}};try{sessionStorage.setItem(STORAGE,JSON.stringify(original));}catch{setError('未能保留原请求，尚未提交，请检查浏览器存储权限。');return;}inFlight.current=true;setBusy(true);setPending(original);setConfirm(null);setError('');setNotice('');setSources([]);try{const result=await newDesignApi.changeBookLifecycle(original.bookId,original.input);if(result.bookId!==original.bookId||result.status!==(original.input.action==='archive'?'archived':'active')||result.revision!==original.input.expectedRevision+1)throw Error('原书籍状态回执不匹配，请核对原请求。');sessionStorage.removeItem(STORAGE);setPending(null);await load();setNotice(original.input.action==='archive'?'作品已移入回收站；原正文、资料及身份保留，可恢复。':'作品已恢复；原正文、资料及身份保留，未自动恢复 AI。');}catch(reason){if(reason instanceof ApiError&&[400,404,409,422].includes(reason.status)){sessionStorage.removeItem(STORAGE);setPending(null);const root='/new-design/books/'+original.bookId;const links=Object.values(reason.issues??{}).flatMap(value=>{const split=value.indexOf('：/new-design/'),href=split>=0?value.slice(split+1):'';try{const url=new URL(href,'http://shelf.invalid');return href.startsWith(root+'/')&&url.pathname.startsWith(root+'/')&&url.origin==='http://shelf.invalid'?[{label:value.slice(0,split),href}]:[];}catch{return [];}});setSources(links.length?links:[{label:'打开原作品工作区',href:root+'/overview'}]);}setError(reason instanceof Error?reason.message:'原状态变更结果待核对。');}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 const check=async()=>{if(!pending||inFlight.current)return;inFlight.current=true;setBusy(true);try{const result=await newDesignApi.readBookLifecycle(pending.bookId);if(result.bookId!==pending.bookId||result.status!==(pending.input.action==='archive'?'archived':'active')||result.revision!==pending.input.expectedRevision+1){setError('原状态转移未确认；保留原凭证，不根据当前列表推断成功或重复提交。');return;}sessionStorage.removeItem(STORAGE);setPending(null);await load();setNotice('原书籍状态转移已确认；未新增书籍或恢复 AI。');}catch(reason){setError(reason instanceof Error?reason.message:'原状态未读取。');}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 const books=snapshot?.books??[],selection=selectShelf(books,search,filter,sort,page),recycled=(snapshot?.recycled??[]).filter(book=>`${book.name}\n${book.description}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())),locked=busy||!!pending||storageBroken;
 return <main className="nd-shell nd-bookshelf" aria-busy={loading||busy}>
 <header className="nd-page-header"><div><p className="nd-kicker">我的创作</p><h1>{view==='trash'?'回收站':'我的书架'} <Help label="书架">浏览作品、阅读正式采用正文，回到本书继续设定、规划和写作。采用正文进度不表示全书完稿；候选、稳定章节和任务完成分别显示。回收站保留原资料，恢复不会自动启动 AI。</Help></h1></div><div className="nd-row-actions"><button className="nd-button" disabled={loading||busy} onClick={()=>void load()}>刷新书架</button><a className="nd-button nd-button-primary" href="/new-design/books/new">＋ 开始新故事</a></div></header>
 <nav className="nd-shelf-switch" aria-label="书架视图">{([['shelf','书架'],['workbench','工作台'],['trash','回收站']] as const).map(([key,label])=><button className="nd-button" aria-pressed={view===key} key={key} onClick={()=>{setView(key);setPage(1);}}>{label}{key==='trash'&&snapshot?`（${snapshot.recycled.length}）`:''}</button>)}</nav>
 <div className="nd-shelf-controls"><label>搜索作品<input type="search" value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="书名或作品说明"/></label>{view!=='trash'&&<><label>创作状态<select value={filter} onChange={event=>{setFilter(event.target.value as ShelfFilter);setPage(1);}}>{filters.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>排序<select value={sort} onChange={event=>{setSort(event.target.value as ShelfSort);setPage(1);}}>{sorts.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></>}</div>
 {loading&&<p role="status">正在读取作品与正式正文…{snapshot?'保留上次读取结果。':''}</p>}{busy&&<p role="status">正在核对原书籍状态…</p>}{error&&<section className="nd-message is-error" role="alert"><p>{error}</p>{sources.map(source=><a className="nd-button" key={source.href} href={source.href}>{source.label}</a>)}<button className="nd-button" disabled={loading||busy} onClick={()=>void load()}>重新读取书架</button></section>}{storageBroken&&<p role="alert">原归档凭证无法读取，归档和恢复操作保留禁用。</p>}{pending&&<p role="alert">原归档或恢复结果待核对，不重复提交。<button className="nd-button" disabled={busy} onClick={()=>void check()}>核对原请求状态</button></p>}{notice&&<p role="status">{notice}</p>}
 {snapshot&&view!=='trash'&&<><div className="nd-shelf-totals" aria-label="全部作品状态"><span>{books.length} 部作品</span><span>正在推进 {books.filter(hasLiveWork).length}</span><span>需要核对 {books.filter(shelfAttention).length}</span><span>已采用 {books.reduce((sum,book)=>sum+book.writtenChapterCount,0)} 章</span></div>{snapshot.drafts.length>0&&<section className="nd-shelf-drafts"><h2>开书草稿 <Help label="开书草稿">这些故事尚未建立正式书籍。继续原草稿完成审阅和开书；与书架作品分别计数。</Help></h2>{snapshot.drafts.map(draft=><article key={draft.id}><div><strong>{draft.name||'待命名故事'}</strong><p>{draft.status==='failed'?'准备未完成':['running','generating'].includes(draft.status)?'正在准备':'等待审阅'} · 已保存阶段 {draft.completedStages.length} 项 · {date(draft.updatedAt)}</p></div><a className="nd-button" href={`/new-design/books/new?session=${encodeURIComponent(draft.id)}`}>继续原开书草稿</a></article>)}</section>}
 <section className={`nd-shelf-books ${view==='workbench'?'is-workbench':''}`} aria-label="作品列表">{selection.items.map(book=>{const root=`/new-design/books/${book.id}`,action=shelfAction(book),progress=shelfProgress(book),reading=root+'/reading'+(book.firstChapterId?'?chapter='+book.firstChapterId:'');return <article className="nd-shelf-book" key={book.id}><a href={book.firstChapterId?reading:action.href} aria-label={`打开《${book.name}》`}><Cover book={book}/></a><div className="nd-shelf-book-detail"><h2><a href={action.href}>{book.name}</a></h2><p className="nd-shelf-description">{book.description||'尚未填写作品说明。'}</p><p className="nd-shelf-status">{hasLiveWork(book)?'正在推进':shelfAttention(book)?'需要核对':book.writtenChapterCount?'已有正式正文':'准备故事'} · 更新于 {date(book.updatedAt)}</p><dl><div><dt>采用正文</dt><dd>{book.writtenChapterCount} 章 · {book.wordCount.toLocaleString('zh-CN')} 字</dd></div><div><dt>稳定章节</dt><dd>{book.stableChapterCount} 章</dd></div><div><dt>保留候选</dt><dd>{book.candidateCount} 版</dd></div></dl><p className="nd-shelf-progress">{progress===null?'尚无采用章节计划':`采用正文进度 ${progress}% · ${book.writtenChapterCount} / ${book.adoptedChapterPlanCount} 章计划`}</p>{progress!==null&&<progress max={100} value={progress} aria-label="采用正文相对于采用章节计划的进度"/>}{view==='workbench'&&<><p>{action.reason}</p>{book.latestDirector&&<p>原导演：{book.latestDirector.status==='completed'?'本次范围执行完成':book.latestDirector.status==='running'?'范围执行中':book.latestDirector.status==='paused'?'范围暂停':'范围待核对'} · 已保存 {book.latestDirector.savedCandidateCount} 章候选（未代表采用）</p>}<nav aria-label={`《${book.name}》创作步骤`}>{[['setting','① 项目设定'],['story-setting','② 故事设定'],['planning','③ 故事规划'],['writing','④ 正文创作']].map(([path,label])=><a key={path} href={`${root}/${path}`}>{label}</a>)}</nav></>}
 <div className="nd-row-actions"><a className="nd-button nd-button-primary" href={action.href}>{action.label}</a>{book.firstChapterId&&<a className="nd-button" href={reading}>阅读正文</a>}<a className="nd-button" href={root+'/overview'}>进入工作区</a></div><div className="nd-shelf-management"><a href={root+'/visual-assets'}>{book.cover?'管理封面':'设置封面'}</a><a href={root+'/completion'}>导出正文</a><button disabled={locked||loading} onClick={()=>setConfirm({book,action:'archive'})}>移入回收站</button></div></div></article>;})}</section>
 {!selection.total&&<section className="nd-empty"><strong>{books.length?'没有符合条件的作品':'书架还没有作品'}</strong><p>{books.length?'调整搜索或创作状态，再查看作品。':'完成开书草稿，或开始一个新故事。'}</p></section>}{selection.total>0&&<nav className="nd-shelf-pagination" aria-label="书架分页"><button className="nd-button" disabled={selection.page<=1} onClick={()=>setPage(selection.page-1)}>上一页</button><span>第 {selection.page} / {selection.totalPages} 页 · {selection.total} 部</span><button className="nd-button" disabled={selection.page>=selection.totalPages} onClick={()=>setPage(selection.page+1)}>下一页</button></nav>}</>}
 {snapshot&&view==='trash'&&<section className="nd-shelf-recycled"><p>作品正文、资料、快照与原书籍身份保留。恢复后从原位置继续；AI 任务不会自动启动。</p>{recycled.map(book=><article key={book.id}><div><h2>{book.name}</h2><p>{book.description||'未填写作品说明。'}</p><small>归档于 {date(book.updatedAt)}</small></div><button className="nd-button" disabled={locked||loading} onClick={()=>setConfirm({book,action:'restore'})}>恢复到书架</button></article>)}{!recycled.length&&<p>{search?'没有符合搜索的归档作品。':'回收站没有作品。'}</p>}</section>}
 {confirm&&<dialog ref={dialog} aria-labelledby="nd-shelf-confirm-title" className="nd-shelf-dialog" onCancel={event=>{event.preventDefault();if(!busy)setConfirm(null);}}><h2 id="nd-shelf-confirm-title">{confirm.action==='archive'?'移入回收站':'恢复到书架'}</h2><p>《{confirm.book.name}》{confirm.action==='archive'?'将从书架和正常作品统计中移除。正文、资料及快照保留，可从回收站恢复；运行、暂停或待核对的任务需先处理。':'将以原书籍身份恢复，原正文、资料及快照保留；不会恢复 AI 执行。'}</p><div className="nd-row-actions"><button className="nd-button" onClick={()=>setConfirm(null)}>取消</button><button className="nd-button nd-button-primary" disabled={locked} onClick={()=>void change()}>{confirm.action==='archive'?'确认移入回收站':'确认恢复'}</button></div></dialog>}
 </main>;
}
