import {useEffect,useRef,useState} from 'react';
import type {BookReading,ReadingScope} from '../../common/bookshelf';
import {newDesignApi} from '../api';
import {downloadBookText,saveShelfText} from './download';
import Help from '../storyWorkspace/Help';
import './bookshelf.css';
export default function ReadingPage({bookId}:{bookId:string}){
 const query=new URLSearchParams(location.search),[chapter,setChapter]=useState(query.get('chapter')??''),[scope,setScope]=useState<ReadingScope>(query.get('scope')==='adopted'?'adopted':'saved'),[data,setData]=useState<BookReading|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[directory,setDirectory]=useState(false),[downloading,setDownloading]=useState(false),[notice,setNotice]=useState(''),sequence=useRef(0),downloadFlight=useRef(false);
 const ambiguous=query.getAll('chapter').length>1||query.getAll('scope').length>1||query.has('scope')&&!['saved','adopted'].includes(query.get('scope')??'');
 useEffect(()=>{const seq=++sequence.current;setLoading(true);setError('');if(ambiguous){setError('稿件或章节来源无效，请从本书目录明确选择。');setLoading(false);return;}void newDesignApi.getBookReading(bookId,chapter||undefined,scope).then(next=>{if(seq!==sequence.current)return;if(next.bookId!==bookId||next.scope!==scope||chapter&&next.selected?.id!==chapter)throw Error('正文来源不匹配，未改选其他章节。');setData(next);}).catch(reason=>{if(seq===sequence.current)setError(reason instanceof Error?reason.message:'正文未读取。');}).finally(()=>{if(seq===sequence.current)setLoading(false);});return()=>{sequence.current++;};},[bookId,chapter,scope,revision,ambiguous]);
 function navigate(id:string,nextScope=scope){setChapter(id);setScope(nextScope);setDirectory(false);setNotice('');const next=new URLSearchParams({scope:nextScope});if(id)next.set('chapter',id);history.replaceState(history.state,'',location.pathname+'?'+next.toString());}
 const ready=!!data&&!error&&!loading&&data.scope===scope,index=data?.chapters.findIndex(item=>item.id===data.selected?.id)??-1,root='/new-design/books/'+bookId;
 async function copy(){if(!ready||!data?.selected)return;try{await navigator.clipboard.writeText(data.selected.content);setNotice('本章正文已复制。');}catch{setNotice('复制未完成，请选择正文手动复制。');}}
 function downloadChapter(){if(!ready||!data?.selected)return;saveShelfText({bookId,name:data.name,scope,chapters:[data.selected],readAt:data.readAt});setNotice('已开始下载当前显示的本章版本。');}
 async function downloadFull(){if(downloadFlight.current||!ready)return;downloadFlight.current=true;setDownloading(true);setNotice('');try{await downloadBookText(bookId,scope);setNotice('已开始下载本书所选稿件，版本清单随正文保存。');}catch(reason){setNotice(reason instanceof Error?reason.message:'下载未完成。');}finally{downloadFlight.current=false;setDownloading(false);}}
 return <main className="nd-shell nd-book-reader" aria-busy={loading}><header className="nd-page-header"><div><p className="nd-kicker"><a href="/new-design/books">我的书架</a></p><h1>{data?.name??'阅读正文'} <Help label="阅读正文">已保存稿读取各章最新非归档版本，可以包含尚未采用候选；正式采用正文只读取明确采用的版本。阅读、复制和下载不改变正文采用及章节变化。</Help></h1></div><div className="nd-reader-actions"><button className="nd-button" onClick={()=>setDirectory(value=>!value)} aria-expanded={directory}>章节目录</button><button className="nd-button" disabled={!ready||!data?.selected} onClick={()=>void copy()}>复制本章</button><button className="nd-button" disabled={!ready||!data?.selected} onClick={downloadChapter}>下载本章</button><button className="nd-button" disabled={!ready||!data?.chapters.length||downloading} onClick={()=>void downloadFull()}>{downloading?'正在读取整本…':'下载整本 TXT'}</button><a className="nd-button" href={root+'/overview'}>进入工作区</a><a className="nd-button" href={root+'/completion'}>出版导出</a></div></header>
 <div className="nd-reader-scope"><label>阅读稿件 <select disabled={loading||downloading} value={scope} onChange={event=>navigate('',event.target.value as ReadingScope)}><option value="saved">已保存稿（含未采用候选）</option><option value="adopted">正式采用正文</option></select></label><button className="nd-button" disabled={loading} onClick={()=>setRevision(value=>value+1)}>刷新所选稿件</button></div>
 {scope==='saved'&&<p className="nd-message">已保存稿可包含未采用候选，不代表正式正文或全书完稿。</p>}{loading&&<p role="status">正在读取本书所选稿件…</p>}{error&&<p className="nd-message is-error" role="alert">{error}<button className="nd-button" disabled={loading} onClick={()=>setRevision(value=>value+1)}>核对原稿件与章节</button></p>}{notice&&<p role="status">{notice}</p>}
 {directory&&<button className="nd-reader-backdrop" aria-label="关闭目录" onClick={()=>setDirectory(false)}/>}
 <div className={'nd-reader-layout '+(directory?'is-directory-open':'')}><aside aria-label="本书正文目录"><header><h2>章节目录</h2><button className="nd-button" onClick={()=>setDirectory(false)}>关闭目录</button></header><p>{data?.chapters.length??0} 章 · {(data?.chapters.reduce((sum,item)=>sum+item.wordCount,0)??0).toLocaleString('zh-CN')} 字</p>{data?.chapters.map(item=><button type="button" key={item.id} disabled={loading} aria-pressed={data.selected?.id===item.id} onClick={()=>navigate(item.id)}><strong>{item.order} · {item.title}</strong><small>{item.wordCount.toLocaleString('zh-CN')} 字 · {item.adopted?item.stable?'已采用 · 稳定':'已采用 · 待稳定':'未采用候选'} · v{item.version}</small></button>)}</aside><section>{ready&&data?.selected?<><h2>{data.selected.title}</h2><p>保存版本 {data.selected.version} · {data.selected.wordCount.toLocaleString('zh-CN')} 字 · {data.selected.adopted?data.selected.stable?'已采用 · 已稳定':'已采用 · 待稳定':'未采用候选'}</p><article className="nd-reader-content">{data.selected.content}</article><nav className="nd-reader-actions" aria-label="阅读翻章"><button className="nd-button" disabled={loading||index<=0} onClick={()=>navigate(data.chapters[index-1].id)}>上一章</button><button className="nd-button" disabled={loading||index<0||index>=data.chapters.length-1} onClick={()=>navigate(data.chapters[index+1].id)}>下一章</button><a className="nd-button" href={root+'/chapters/'+data.selected.cardId+'/write'}>编辑本章</a></nav></>:!loading&&!error?<div className="nd-empty"><strong>本书所选稿件尚无正文</strong><p>到正文工作台查看保存的候选或明确采用正文，再选择对应稿件阅读。</p><a className="nd-button" href={root+'/writing'}>进入正文创作</a></div>:<p>原目录和书籍身份保留，请核对指定稿件与章节。</p>}</section></div></main>;
}
