import {useEffect,useRef,useState} from 'react';
import type {BookReading} from '../../common/bookshelf';
import {newDesignApi} from '../api';
import Help from '../storyWorkspace/Help';
import './bookshelf.css';
export default function ReadingPage({bookId}:{bookId:string}){
 const query=new URLSearchParams(location.search),[chapter,setChapter]=useState(query.get('chapter')??''),[data,setData]=useState<BookReading|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),sequence=useRef(0);
 const ambiguous=query.getAll('chapter').length>1;
 useEffect(()=>{const seq=++sequence.current;setLoading(true);setError('');if(ambiguous){setError('章节来源重复，请从本书目录明确选择。');setLoading(false);return;}void newDesignApi.getBookReading(bookId,chapter||undefined).then(next=>{if(seq!==sequence.current)return;if(next.bookId!==bookId||chapter&&next.selected?.id!==chapter)throw Error('正式正文来源不匹配，未改选其他章节。');setData(next);}).catch(reason=>{if(seq===sequence.current)setError(reason instanceof Error?reason.message:'正式正文未读取。');}).finally(()=>{if(seq===sequence.current)setLoading(false);});return()=>{sequence.current++;};},[bookId,chapter,revision,ambiguous]);
 const select=(id:string)=>{setChapter(id);const next=new URLSearchParams();next.set('chapter',id);history.replaceState(history.state,'',location.pathname+'?'+next.toString());};
 const index=data?.chapters.findIndex(item=>item.id===data.selected?.id)??-1,root=`/new-design/books/${bookId}`;
 return <main className="nd-shell nd-book-reader" aria-busy={loading}><header className="nd-page-header"><div><p className="nd-kicker"><a href="/new-design/books">我的书架</a></p><h1>{data?.name??'阅读正文'} <Help label="阅读正文">阅读本书明确采用的完整章节版本。候选正文不进入阅读目录；稳定章节单独标记。重新读取可能展示新采用的版本。</Help></h1></div><div className="nd-row-actions"><a className="nd-button" href={root+'/overview'}>进入工作区</a><a className="nd-button" href={root+'/completion'}>导出正文</a></div></header>{loading&&<p role="status">正在读取正式采用正文…</p>}{error&&<p className="nd-message is-error" role="alert">{error}<button className="nd-button" disabled={loading} onClick={()=>setRevision(value=>value+1)}>核对原正式版本</button></p>}
 <div className="nd-reader-layout"><aside aria-label="正式正文目录"><h2>章节目录</h2>{data?.chapters.map(item=><button type="button" key={item.id} disabled={loading} aria-pressed={data.selected?.id===item.id} onClick={()=>select(item.id)}><strong>{item.order} · {item.title}</strong><small>{item.wordCount.toLocaleString('zh-CN')} 字 · {item.stable?'已稳定':'已采用，待稳定'}</small></button>)}</aside><section>{data?.selected&&!error?<><h2>{data.selected.title}</h2><p>采用版本 {data.selected.version} · {data.selected.wordCount.toLocaleString('zh-CN')} 字 · {data.selected.stable?'已稳定':'待稳定'}</p><article className="nd-reader-content">{data.selected.content}</article><nav className="nd-row-actions" aria-label="阅读翻章"><button className="nd-button" disabled={loading||index<=0} onClick={()=>select(data.chapters[index-1].id)}>上一章</button><button className="nd-button" disabled={loading||index<0||index>=data.chapters.length-1} onClick={()=>select(data.chapters[index+1].id)}>下一章</button><a className="nd-button" href={`${root}/chapters/${data.selected.cardId}/write`}>编辑本章</a></nav></>:!loading&&!error?<div className="nd-empty"><strong>本书尚无正式采用正文</strong><p>在正文工作台检查并明确采用章节后，可在这里阅读。</p><a className="nd-button" href={root+'/writing'}>进入正文创作</a></div>:<p>原目录和书籍身份保留，请核对指定章节。</p>}</section></div></main>;
}
