import {useEffect,useRef,useState} from "react";
import type {ManagedEmbeddingCatalog,ManagedEmbeddingSaveResult,SaveManagedEmbeddingConnectionInput} from "../../common/modelRouting";
import {ApiError,newDesignApi} from "../api";
import {blankEmbeddingDraft,copyEmbeddingConnection,embeddingDifferences,parseEmbeddingEditor,normalizedEmbeddingInput,matchesEmbeddingSave,type EmbeddingDraft,type EmbeddingPending} from "./embeddingEditing";
const storageKey="new-design:embedding-model-editor:v1";
const labels:Record<string,string>={provider:"模型服务",endpoint:"连接地址",model:"向量模型",credentialId:"凭据引用",timeoutMs:"单次等待",maxRetries:"技术重试次数",retryDelayMs:"重试间隔",expectedRevision:"配置修订",expectedConfigId:"原配置来源"};
export default function EmbeddingConnectionPanel({disabled,onLock}:{disabled:boolean;onLock:(locked:boolean)=>void}){
 const [catalog,setCatalog]=useState<ManagedEmbeddingCatalog|null>(null),[draft,setDraft]=useState<EmbeddingDraft>(blankEmbeddingDraft),[base,setBase]=useState<{id:string;revision:number}|null>(null),[pending,setPending]=useState<EmbeddingPending|null>(null),[proof,setProof]=useState<ManagedEmbeddingSaveResult|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(""),[step,setStep]=useState(""),[retained,setRetained]=useState(""),[issues,setIssues]=useState<Record<string,string>>({}),[models,setModels]=useState<string[]>([]),[notice,setNotice]=useState("");
 const pendingRef=useRef<EmbeddingPending|null>(null),generation=useRef(0),currentDraft=useRef(draft),form=useRef<HTMLElement|null>(null);currentDraft.current=draft;pendingRef.current=pending;
 const [storageIssue,setStorageIssue]=useState("");const storageBlocked=useRef(false);
 const locked=disabled||busy||Boolean(pending)||Boolean(storageIssue),newest=catalog?.connections.find(connection=>connection.configId===base?.id)??null;
 const report=(reason:unknown,fallback:string)=>{setStep(reason instanceof ApiError?reason.recovery?.failedStep??fallback:fallback);setRetained(reason instanceof ApiError?reason.recovery?.savedResult??"当前填写、原请求和已保存向量模型版本保留。":"当前填写、原请求和已保存向量模型版本保留。");setIssues(reason instanceof ApiError?reason.issues:{});setError(reason instanceof Error?reason.message:"服务器回执尚未确认，请只读核对原请求。");};
 const blockStorage=(message:string)=>{storageBlocked.current=true;setStorageIssue(message);};
 const retain=(value:EmbeddingDraft,nextBase=base,nextPending=pendingRef.current)=>{if(storageBlocked.current)return false;try{const serialized=JSON.stringify({version:1,draft:value,base:nextBase,pending:nextPending});if(serialized.length>30000){blockStorage("填写与原请求凭证超过本机恢复容量，未覆盖原凭证且不会发送新请求。当前填写与服务器版本保留，请保留输入并检查网站存储后返回原页核对。");return false;}sessionStorage.setItem(storageKey,serialized);return true;}catch{blockStorage("输入或原请求未能保留，已锁定提交。当前填写与服务器记录保留，请检查网站存储后重新打开原页面核对。");return false;}};
 const read=async()=>{const token=++generation.current;setBusy(true);try{const value=await newDesignApi.getManagedEmbeddingCatalog();if(token!==generation.current)return;setCatalog(value);setError("");}catch(reason){if(token===generation.current)report(reason,"读取知识语义索引模型目录");}finally{if(token===generation.current)setBusy(false);}};
 useEffect(()=>{try{const raw=sessionStorage.getItem(storageKey),saved=parseEmbeddingEditor(raw);if(raw!==null&&!saved){blockStorage("保留的草稿或原请求凭证无法完整读取，已锁定提交且不会覆盖原凭证。服务器版本仍保留，请到运行维护核对网站存储后返回原页。");}else if(saved){setDraft(saved.draft);setBase(saved.base);setPending(saved.pending);pendingRef.current=saved.pending;}}catch{blockStorage("网站存储暂不可用，原请求状态未确认，已锁定提交；服务器版本保留，请到运行维护核对后返回原页。");}setReady(true);void read();return()=>{generation.current++;onLock(false);};},[]);
 useEffect(()=>{onLock(busy||Boolean(pending)||Boolean(storageIssue));},[busy,pending,storageIssue,onLock]);
 useEffect(()=>{if(ready&&!storageBlocked.current)retain(draft);},[ready,draft,base,pending]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(pendingRef.current||currentDraft.current.endpoint||currentDraft.current.model){retain(currentDraft.current);event.preventDefault();event.returnValue="";}};addEventListener("beforeunload",leave);return()=>removeEventListener("beforeunload",leave);},[base]);
 const change=(next:EmbeddingDraft)=>{if(locked)return;setDraft(next);setModels([]);setNotice("");};
 const accept=async(result:ManagedEmbeddingSaveResult,input:SaveManagedEmbeddingConnectionInput)=>{if(!await matchesEmbeddingSave(result,input))throw new Error("原保存回执与完整输入凭证不一致，保留原请求只读核对。");setProof(result);setBase({id:result.connection.configId,revision:result.configRevision});setNotice(`专属向量模型第 ${result.savedVersion} 版已保存${result.active?"并启用":"；后续已有更新，请核对"}。需要在知识中心明确绑定此版本后才能建立索引。`);};
 const save=async()=>{if(locked||pendingRef.current||!ready)return;const input=normalizedEmbeddingInput({...draft,expectedConfigId:base?.id??null,expectedRevision:base?.revision??null,idempotencyKey:crypto.randomUUID()}),next={input,notWritten:false,checked:false};if(!retain(draft,base,next))return;generation.current++;pendingRef.current=next;setPending(next);setBusy(true);let acknowledged=false;try{const result=await newDesignApi.saveManagedEmbeddingConnection(input);await accept(result,input);acknowledged=true;const value=await newDesignApi.getManagedEmbeddingCatalog();setCatalog(value);pendingRef.current=null;setPending(null);setError("");}catch(reason){report(reason,acknowledged?"只读刷新已保存向量模型目录":"保存并启用知识语义索引模型");if(!acknowledged&&reason instanceof ApiError&&reason.recovery?.mutationOutcome==="not_written"){const confirmed={...next,notWritten:true};pendingRef.current=confirmed;setPending(confirmed);}}finally{setBusy(false);}};
 const check=async()=>{const original=pendingRef.current;if(!original||busy)return;setBusy(true);let found=false;try{const result=await newDesignApi.getManagedEmbeddingSaveReceipt(original.input.idempotencyKey);if(result){await accept(result,original.input);found=true;pendingRef.current=null;setPending(null);}else{const checked={...original,checked:true};pendingRef.current=checked;setPending(checked);setStep("只读核对原向量模型保存");setError("原回执尚未找到，不能断言未写入；输入和原标识保留，不重复提交。");}try{setCatalog(await newDesignApi.getManagedEmbeddingCatalog());}catch(reason){report(reason,found?"已保存成功后的目录读取":"核对原模型目录");}}catch(reason){report(reason,"只读核对原向量模型请求");}finally{setBusy(false);}};
 const reprepare=()=>{const original=pendingRef.current;if(!original?.notWritten||!original.checked||busy||!catalog)return;const actual=catalog.connections[0]??null;if(!confirm("原请求已确认未写入。保留输入，明确核对并使用读取到的专属配置修订；之后仍需点击保存，不自动发请求。是否继续？"))return;setBase(actual?{id:actual.configId,revision:actual.configRevision}:null);pendingRef.current=null;setPending(null);setError("");setNotice("填写保留，已明确核对最新专属配置修订；请核对后点击保存并启用。");};
 const chooseVersion=(id:string)=>{if(locked||!catalog)return;const value=catalog.connections.find(connection=>connection.id===id);if(!value)return;if((draft.endpoint||draft.model)&&!confirm("用所选原版本的连接设置替换未保存填写，再编辑新版本。是否继续？"))return;if(!retain(draft))return;setDraft(copyEmbeddingConnection(value));setBase({id:value.configId,revision:value.configRevision});setModels([]);setError("");};
 const probe=async()=>{if(locked||!draft.endpoint)return;const token=++generation.current;setBusy(true);try{const result=await newDesignApi.probeManagedModelConnection({provider:draft.provider,endpoint:draft.endpoint,model:draft.model,credentialId:draft.credentialId});if(token!==generation.current)return;setModels(result.models);setNotice("模型列表已读取，请明确选择向量模型。列入列表不证明它能生成所需维度，实际向量调用将在索引任务中核对。");}catch(reason){if(token===generation.current)report(reason,"读取向量服务模型列表");}finally{if(token===generation.current)setBusy(false);}};
 return <section ref={form} id="knowledge-embedding-model" className="nd-model-route-editor" aria-label="知识语义索引模型"><header><h2>知识语义索引模型</h2><p>单独配置用于查找相近内容的向量模型，不能使用文字默认模型或备用路线。已有索引绑定原版本，修改设置不会换掉已有索引。</p></header>{storageIssue&&<section role="alert"><h3>未完成步骤：恢复原草稿与请求凭证</h3><p>{storageIssue}</p><a className="nd-button" href="/new-design/structure/maintenance">打开运行维护</a><p>此入口只导航，不重发请求、不清除或覆盖原凭证。</p></section>}{proof&&<p role="status">已保存第 {proof.savedVersion} 版；{proof.active?"此连接已启用":"此连接已有后续版本"}。成功凭证保留，不因后续读取失败变成保存失败。</p>}{notice&&<p role="status">{notice}</p>}{catalog?.configurationIssue&&<p role="alert">{catalog.configurationIssue}</p>}
 <label className="nd-control">选择明确的连接版本<select disabled={locked} value="" onChange={event=>chooseVersion(event.target.value)}><option value="">请选择原版本，不自动使用文字默认设置</option>{catalog?.connections.map(value=><option value={value.id} key={value.id}>{value.label} · 第 {value.version} 版 · {value.model}</option>)}</select></label><fieldset disabled={locked} className="nd-model-form-grid"><label className="nd-control">模型服务<select data-embedding-field="provider" value={draft.provider} onChange={event=>change({...draft,provider:event.target.value as EmbeddingDraft["provider"],credentialId:null})}><option value="ollama">本机 Ollama</option><option value="openai-compatible">兼容 OpenAI 接口</option></select></label><label className="nd-control">连接地址<input data-embedding-field="endpoint" type="url" value={draft.endpoint} onChange={event=>change({...draft,endpoint:event.target.value})}/></label><label className="nd-control">向量模型<input data-embedding-field="model" value={draft.model} onChange={event=>change({...draft,model:event.target.value})}/></label><label className="nd-control">凭据引用<select data-embedding-field="credentialId" value={draft.credentialId??""} onChange={event=>change({...draft,credentialId:event.target.value||null})}><option value="">无需凭据／尚未选择</option>{catalog?.credentials.filter(value=>value.provider===draft.provider||value.id===draft.credentialId).map(value=><option key={value.id} value={value.id} disabled={value.status!=="active"}>{value.label}{value.available?"":"（凭据未就绪）"}</option>)}</select></label>{([['timeoutMs','单次等待（秒）',1000],['maxRetries','技术重试次数',1],['retryDelayMs','重试间隔（秒）',1000]] as const).map(([key,label,divisor])=><label className="nd-control" key={key}>{label}<input data-embedding-field={key} type="number" min={key==="timeoutMs"?1:0} max={key==="timeoutMs"?600:key==="maxRetries"?3:10} step={1} value={draft[key]/divisor} onChange={event=>change({...draft,[key]:Number(event.target.value)*divisor})}/></label>)}</fieldset><p>凭据从新版数据库读取，密钥可在上方“数据库模型凭据”中加密保存；连接版本只保留凭据引用，不回显密钥。</p><button className="nd-button" disabled={locked||!draft.endpoint} onClick={()=>void probe()}>读取连接与模型列表</button>{models.length>0&&<label className="nd-control">服务返回的模型<select disabled={locked} value="" onChange={event=>change({...draft,model:event.target.value||draft.model})}><option value="">请选择向量模型，不自动选择第一项</option>{models.map(model=><option key={model} value={model}>{model}</option>)}</select></label>}
 {newest&&base&&newest.configRevision!==base.revision&&<p role="alert">配置修订已变化，输入保留。请选择原版本核对，或经明确确认后重新准备；不会自动替换填写。</p>}{error&&<section className="nd-message is-error" role="alert"><h3>未完成步骤：{step}</h3><p>{error}</p><p>{retained}</p>{Object.keys(issues).map(key=><button className="nd-button" key={key} onClick={()=>{const field=key.split('.').at(-1)??key;form.current?.querySelector<HTMLElement>(`[data-embedding-field="${Object.hasOwn(labels,field)?field:'model'}"]`)?.focus();}}>定位：{labels[key.split('.').at(-1)??key]??"原配置来源"}</button>)}</section>}{pending&&<section role="alert"><p>原保存请求待核对，输入与原标识保留；结果未知禁止重复保存。</p><button className="nd-button" disabled={busy} onClick={()=>void check()}>只读核对原保存回执</button>{pending.notWritten&&pending.checked&&<button className="nd-button" disabled={busy} onClick={reprepare}>已确认未写入，保留填写重新准备</button>}</section>}
 <div className="nd-action-row"><button className="nd-button nd-button-primary" disabled={locked||!ready} onClick={()=>void save()}>保存并启用专属向量模型</button><button className="nd-button" disabled={busy} onClick={()=>void read()}>只读重新读取目录</button><a className="nd-button" href="/new-design/knowledge" onClick={event=>{if(pendingRef.current||!retain(draft))event.preventDefault();}}>到知识中心选择索引连接版本</a><a className="nd-button" href="/new-design/structure/maintenance" onClick={event=>{if(!retain(draft))event.preventDefault();}}>打开运行维护</a></div><p>差异：{embeddingDifferences(newest,draft).join('、')||"与所选原配置一致"}。</p>{base&&<details><summary>原配置版本凭证</summary><p>{base.id} · 修订 {base.revision}</p></details>}
 </section>;
}
