import {useEffect,useMemo,useRef,useState} from 'react';
import {type WorldUsageSelection,type WorldUsageCandidate,type WorldUsageWorkspace,type WorldUsagePrepareInput,type WorldUsageAdoptInput} from '../../common/worldUsage';
import type {createWorldUsageApi} from './api';
import {ApiError} from '../api';
import type {WorkspaceEditor} from '../storyWorkspace/useGuard';
import {emptyWorldUsageSelection,readWorldUsageFrame,writeWorldUsageFrame,type WorldUsagePending} from './storage';

type Api=ReturnType<typeof createWorldUsageApi>;

export default function WorldUsagePanel({bookId,rootCardId,api,onState}:{bookId:string;rootCardId:string;api:Api;onState?:(state:WorkspaceEditor)=>void}){
 const key=`new-design:world-usage:v1:${bookId}:${rootCardId}`,initial=useMemo(()=>readWorldUsageFrame(key),[key]);
 const [workspace,setWorkspace]=useState<WorldUsageWorkspace|null>(null),[draft,setDraft]=useState(initial.selection),[pending,setPending]=useState<WorldUsagePending|null>(initial.pending),[broken,setBroken]=useState(initial.broken),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[instruction,setInstruction]=useState(initial.instruction);
 const mounted=useRef(true),working=useRef(false);
 useEffect(()=>{onState?.({dirty:JSON.stringify(draft)!==JSON.stringify(workspace?.adopted?.selection??emptyWorldUsageSelection)||Boolean(instruction.trim()),locked:busy||broken||Boolean(pending)});},[draft,instruction,workspace?.adopted?.selection,busy,broken,pending,onState]);
 useEffect(()=>()=>onState?.({dirty:false,locked:false}),[onState]);
 useEffect(()=>{mounted.current=true;void api.workspace(bookId,rootCardId).then(data=>{if(mounted.current){setWorkspace(data);if(!initial.hasFrame&&data.adopted)setDraft(data.adopted.selection);}}).catch(reason=>{if(mounted.current)setError(reason instanceof Error?reason.message:'本书世界来源未读取。');});return()=>{mounted.current=false;};},[bookId,rootCardId,api,initial.hasFrame]);
 const retain=(selection:WorldUsageSelection,next:WorldUsagePending|null,nextInstruction=instruction)=>{try{writeWorldUsageFrame(key,selection,next,nextInstruction);setDraft(selection);setPending(next);setInstruction(nextInstruction);return true;}catch{setBroken(true);setError('原填写或请求凭证未能保留，已停止新操作；请核对浏览器存储。');return false;}};
 const refresh=async()=>{const data=await api.workspace(bookId,rootCardId);if(data.bookId!==bookId||data.rootCardId!==rootCardId)throw Error('本书世界来源不匹配。');if(mounted.current)setWorkspace(data);return data;};
 const exclusive=async(work:()=>Promise<void>)=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{await work();}catch(reason){if(mounted.current)setError(reason instanceof Error?reason.message:'原操作结果待核对。');}finally{working.current=false;if(mounted.current)setBusy(false);}};
 const check=()=>exclusive(async()=>{if(!pending)return;const result=pending.kind==='prepare'?await api.candidateByKey(bookId,rootCardId,pending.input.requestKey):await api.adoptionByKey(bookId,rootCardId,pending.input.requestKey);if(!result){setMessage('原键暂未查到不证明请求没有执行；原填写与原键仍保留。');return;}if(result.bookId!==bookId||result.rootCardId!==rootCardId||result.requestKey!==pending.input.requestKey)throw Error('原回执来源不匹配，保留原键。');if(pending.kind==='prepare'&&'status' in result&&result.status==='running'){await refresh();setMessage('原模型请求仍在处理中或结果未知；保留原键，未发起新请求。');return;}if(!retain(pending.kind==='adopt'&&'version' in result?result.selection:draft,null,pending.kind==='prepare'&&'status' in result&&result.status==='review'&&pending.input.mode==='ai'?'':instruction))return;await refresh();setMessage(pending.kind==='prepare'?'原候选已读取，须作者核对后再采用。':'原采用版本已确认，后续章节会重新核对来源。');});
 const prepare=(mode:'manual'|'ai')=>exclusive(async()=>{if(!workspace?.capability.operational||!workspace.sources||pending||broken)return;const input:WorldUsagePrepareInput={requestKey:crypto.randomUUID(),mode,expectedSourceHash:workspace.sources.sourceHash,instruction:instruction.trim(),...(mode==='manual'?{selection:draft}:{})};if(!retain(draft,{kind:'prepare',input}))return;try{const result=await api.prepare(bookId,rootCardId,input);if(result.requestKey!==input.requestKey||result.sources.sourceHash!==input.expectedSourceHash)throw Error('世界候选回执与原冻结来源不符。');if(result.status==='running'){await refresh();setMessage('原建议正在生成，只读核对原键，不再次发起。');return;}if(!retain(draft,null,mode==='ai'&&result.status==='review'?'':instruction))return;await refresh();setMessage(result.status==='review'?'候选已保存；请检查全部选择并明确采用。':'原建议已结束；请核对回执。');}catch(reason){if(reason instanceof ApiError&&reason.recovery?.mutationOutcome==='not_written'){retain(draft,null);}throw reason;}});
 const adopt=(candidate:WorldUsageCandidate)=>exclusive(async()=>{if(!workspace?.capability.operational||!workspace.sources||pending||broken||candidate.status!=='review'||!candidate.selection)return;if(candidate.sources.sourceHash!==workspace.sources.sourceHash){setError('候选来源已变化，请先重新准备。');return;}const input:WorldUsageAdoptInput={requestKey:crypto.randomUUID(),candidateId:candidate.id,expectedSourceHash:candidate.sources.sourceHash,expectedCurrentVersion:workspace.adopted?.version??0};if(!retain(draft,{kind:'adopt',input}))return;try{const receipt=await api.adopt(bookId,rootCardId,input);if(receipt.requestKey!==input.requestKey||receipt.candidateId!==candidate.id||receipt.sources.sourceHash!==input.expectedSourceHash)throw Error('正式采用回执与候选不一致。');if(!retain(receipt.selection,null))return;await refresh();setMessage('世界使用范围已明确采用；章节生成会核对精确来源。');}catch(reason){if(reason instanceof ApiError&&reason.recovery?.mutationOutcome==='not_written'){retain(draft,null);}throw reason;}});
 const sources=workspace?.sources?.cards??[],locked=busy||broken||Boolean(pending)||!workspace?.capability.operational||!workspace.sources;
 const group=(slot:'factions'|'locations'|'rules',label:string,ids:string[],field:'factionIds'|'locationIds'|'ruleIds')=><fieldset><legend>{label}</legend>{sources.filter(source=>source.slotKey===slot).map(source=><label key={source.cardId}><input type="checkbox" disabled={locked} checked={ids.includes(source.cardId)} onChange={event=>{const next={...draft,[field]:event.target.checked?[...ids,source.cardId]:ids.filter(id=>id!==source.cardId)};retain(field==='locationIds'&&!next.locationIds.includes(next.primaryLocationId??'')?{...next,primaryLocationId:null}:next,pending);}}/>{source.title}<small> · 正式版本 {source.versionId.slice(0,8)}{source.mountId?' · 本书已关联':''}</small></label>)}{!sources.some(source=>source.slotKey===slot)&&<p>本书尚无可选的正式{label}资料。</p>}</fieldset>;
 return <section className="nd-world-usage" aria-label="本书世界使用范围"><header><h3>章节生成使用范围</h3><p>从本书正式世界资料明确保留主舞台、势力、地点和规则。关联资料只是来源；只有下方明确采用的版本会作为生成范围。</p></header>
 {!workspace&&!error&&<p role="status">正在核对本书世界来源…</p>}{workspace&&!workspace.capability.operational&&<p role="status">本书世界使用范围能力尚未启用；原世界档案和关联资料仍可查看。</p>}
 {workspace?.adopted&&<section><h4>当前采用 · 第 {workspace.adopted.version} 版</h4><p>{workspace.stale?'来源已变化，生成会暂停并要求重新采用。':'正式来源仍匹配；生成前还会再次核对。'}</p><p>主舞台：{sources.find(source=>source.cardId===workspace.adopted?.selection.primaryLocationId)?.title??'未指定'}</p><p>势力 {workspace.adopted.selection.factionIds.length} · 地点 {workspace.adopted.selection.locationIds.length} · 规则 {workspace.adopted.selection.ruleIds.length}</p><p>{workspace.adopted.selection.boundary}</p></section>}
 <div className="nd-world-usage-options">{group('factions','核心势力',draft.factionIds,'factionIds')}{group('locations','故事地点',draft.locationIds,'locationIds')}{group('rules','必须保留的规则',draft.ruleIds,'ruleIds')}</div>
 <label>主舞台<select disabled={locked} value={draft.primaryLocationId??''} onChange={event=>retain({...draft,primaryLocationId:event.target.value||null},pending)}><option value="">暂不指定</option>{sources.filter(source=>draft.locationIds.includes(source.cardId)).map(source=><option key={source.cardId} value={source.cardId}>{source.title}</option>)}</select></label>
 <label>本书使用边界<textarea rows={3} maxLength={4000} disabled={locked} value={draft.boundary} onChange={event=>retain({...draft,boundary:event.target.value},pending)}/></label>
 <div className="nd-row-actions"><button type="button" className="nd-button nd-button-primary" disabled={locked||!(draft.factionIds.length||draft.locationIds.length||draft.ruleIds.length)} onClick={()=>void prepare('manual')}>保存人工范围候选</button><label>建议要求<input maxLength={2000} disabled={locked} value={instruction} onChange={event=>retain(draft,pending,event.target.value)}/></label><button type="button" className="nd-button" disabled={locked} onClick={()=>void prepare('ai')}>AI 整理使用范围建议</button><button type="button" className="nd-button" disabled={busy} onClick={()=>void exclusive(async()=>{await refresh();setMessage('只读来源已更新，填写与原请求未清除。');})}>只读刷新来源</button></div>
 {workspace?.candidates.map(item=><article key={item.id}><h4>{item.mode==='ai'?'AI 建议':'人工候选'} · {item.status==='review'?'待作者核对':item.status==='running'?'原请求待核对':item.status==='failed'?'原建议失败':'原结果未知'}</h4><p>来源哈希 {item.sources.sourceHash.slice(0,12)} · {new Date(item.createdAt).toLocaleString()}</p>{item.selection&&<><p>主舞台 {sources.find(source=>source.cardId===item.selection?.primaryLocationId)?.title??'未指定'} · 势力 {item.selection.factionIds.length} · 地点 {item.selection.locationIds.length} · 规则 {item.selection.ruleIds.length}</p><p>{item.selection.boundary}</p><button type="button" disabled={locked} onClick={()=>retain(item.selection!,pending)}>载入候选到人工填写</button><button type="button" disabled={locked||item.sources.sourceHash!==workspace?.sources?.sourceHash} onClick={()=>void adopt(item)}>明确采用此版本</button></>}{item.status==='running'&&<button type="button" disabled={busy} onClick={()=>void exclusive(async()=>{await refresh();setMessage('只读核对原建议；未重复调用模型。');})}>只读核对原建议</button>}</article>)}
 {pending&&<section role="alert"><p>原{pending.kind==='prepare'?'候选':'采用'}请求待核对，已保留请求键；不会换键重试。</p><button type="button" disabled={busy} onClick={()=>void check()}>只读核对原请求</button></section>}{broken&&<p role="alert">浏览器原记录无法完整读取，写入已锁定；原服务端版本保持。</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}
 </section>;
}
