import {Router,type Request,type Response} from 'express';
import {z} from 'zod';
import * as application from '../../application/characterDialogue';
import {NewDesignError} from '../../domain/errors';
const uuid=z.string().uuid(),empty=z.object({}).strict();
class DialogueInputError extends NewDesignError{readonly issues:Record<string,string>;constructor(paths:Array<Array<PropertyKey>>){super('本次人物沙盘来源或填写格式不合格；此操作尚未执行，原凭证和填写保留。',422);const labels:Record<string,string>={requestKey:'原请求凭证',checkpointId:'截至章',participantCardIds:'参与资料',sourceHash:'历史来源凭证',situation:'试演情境',expectedSessionRevision:'会话版本',actorCardId:'发言人物',instruction:'本轮要求',roundId:'原回合',actionKeys:'勾选动作',planningObjectId:'规划目标',planningVersionId:'规划版本',expectedPlanningRevision:'规划修订凭证'};this.issues=Object.fromEntries(paths.map((path,n)=>[`输入${n+1}`,`${labels[String(path[0])]??'来源或额外填写项'}${typeof path[1]==='number'?`第${path[1]+1}项`:''}格式不合格，请核对完整来源。`]));}}
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new DialogueInputError(result.error.issues.map(issue=>issue.path));return result.data;}
export function characterDialogueRouter(){const router=Router(),base='/books/:bookId/character-dialogue',book=(r:Request)=>parse(uuid,r.params.bookId),session=(r:Request)=>parse(uuid,r.params.sessionId),id=(r:Request)=>parse(uuid,r.params.id),key=(r:Request)=>parse(uuid,r.params.key);function invoke(req:Request,res:Response,work:()=>Promise<unknown>){void Promise.resolve().then(work).then(data=>res.json({success:true,data})).catch(error=>{const validBook=uuid.safeParse(req.params.bookId),safeMessage=error instanceof NewDesignError?error.message:'人物沙盘回执尚未确认，原来源、已保存回复和填写保留。',recovery=error instanceof application.DialogueError?{...error.recovery}:error instanceof DialogueInputError&&validBook.success?{...new application.DialogueError(validBook.data,'检查人物模拟输入',error.message,'not_written',422,'此请求在入口格式检查时被拒绝，领域操作未执行；旧回执、原沙盘与填写保留，不据此判断旧请求结果。').recovery}:validBook.success?{...new application.DialogueError(validBook.data,req.method==='GET'?'读取指定人物历史来源与原回执':'核对人物沙盘原操作',safeMessage,'unknown',error instanceof NewDesignError?error.status:503).recovery}:undefined;if(recovery&&req.method==='GET')delete(recovery as Partial<typeof recovery>).mutationOutcome;res.status(error instanceof NewDesignError?error.status:503).json({success:false,error:safeMessage,...(error instanceof DialogueInputError?{issues:error.issues}:{}),...(recovery?{recovery}:{})});});}
 router.get(`${base}/workspace`,(r,s)=>invoke(r,s,()=>{const query=z.object({checkpointId:uuid.optional(),participantCardIds:z.string().optional()}).strict();const value=parse(query,r.query);return application.getCharacterDialogueWorkspace(book(r),parse(application.dialogueWorkspaceQuerySchema,{...value,participantCardIds:value.participantCardIds?.split(',')}));}));
 router.post(`${base}/sessions`,(r,s)=>invoke(r,s,()=>application.createCharacterDialogueSession(book(r),parse(application.dialogueCreateSchema,r.body))));
 router.get(`${base}/sessions/by-key/:key`,(r,s)=>invoke(r,s,()=>application.getCharacterDialogueSessionByKey(book(r),key(r))));router.get(`${base}/sessions/:sessionId`,(r,s)=>invoke(r,s,()=>application.getCharacterDialogueSession(book(r),session(r))));
 router.post(`${base}/sessions/:sessionId/rounds`,(r,s)=>invoke(r,s,()=>application.runCharacterDialogueRound(book(r),session(r),parse(application.dialogueRoundSchema,r.body))));router.get(`${base}/sessions/:sessionId/rounds/by-key/:key`,(r,s)=>invoke(r,s,()=>application.getCharacterDialogueRoundByKey(book(r),session(r),key(r))));router.get(`${base}/sessions/:sessionId/rounds/:id`,(r,s)=>invoke(r,s,()=>application.getCharacterDialogueRound(book(r),session(r),id(r))));
 for(const [path,method]of [['complete-saved',application.completeSavedCharacterDialogueRound],['release-saved',application.releaseSavedCharacterDialogueRound],['end-expired-unknown',application.endExpiredCharacterDialogueRound]]as const)router.post(`${base}/sessions/:sessionId/rounds/:id/${path}`,(r,s)=>invoke(r,s,()=>{parse(empty,r.body);return method(book(r),session(r),id(r));}));
 router.post(`${base}/sessions/:sessionId/selections`,(r,s)=>invoke(r,s,()=>application.selectCharacterDialogueActions(book(r),session(r),parse(application.dialogueSelectionSchema,r.body))));router.get(`${base}/sessions/:sessionId/selections/by-key/:key`,(r,s)=>invoke(r,s,()=>application.getCharacterDialogueSelectionByKey(book(r),session(r),key(r))));return router;
}
