import {useEffect,useRef,useState} from 'react';
import {directorPendingKey,directorDraftKey,parseDirectorDraft,parseDirectorPending,retainDirectorPending,type DirectorPending} from './pending';
import {directorCreateSchema,type DirectorWorkspace,type DirectorReceipt,type DirectorCommand,type ChapterKnowledgeSelection} from '../../common/productionDirector';
import type {KnowledgeReferenceCandidate} from '../../common/knowledgeReference';
import {ApiError,newDesignApi} from '../api';
import BookShell from '../BookShell';
import './director.css';
import {z} from 'zod';
const statusLabels={ready:'等待明确开始',running:'逐章生成中',paused:'停在章边界',waiting_recovery:'原结果待核对',failed:'需要处理来源',completed:'候选准备完成',cancelled:'范围已结束'};
const chapterLabels={pending:'待生成',running:'原生成结果待核对',candidate_saved:'候选已保存',failed:'本章待处理',unknown:'原调用及用量未知'};
export default function ProductionDirectorPage({bookId}:{bookId:string}){
  const query=new URLSearchParams(window.location.search),runParams=query.getAll('run'),requested=runParams.length===1&&z.string().uuid().safeParse(runParams[0]).success?runParams[0]:null,invalidRun=runParams.length>0&&!requested;
  const [workspace,setWorkspace]=useState<DirectorWorkspace|null>(null),[selected,setSelected]=useState<string|null>(requested),[chapters,setChapters]=useState<string[]>([]),[instruction,setInstruction]=useState(''),[policy,setPolicy]=useState<'completion_first'|'quality_first'>('completion_first');
  const [pending,setPending]=useState<DirectorPending|null>(null),[storageBlocked,setStorageBlocked]=useState(false),[error,setError]=useState<Error|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[notWritten,setNotWritten]=useState(false),[checked,setChecked]=useState(false),[saved,setSaved]=useState<DirectorReceipt|null>(null);
  const [draftLoaded,setDraftLoaded]=useState(false);
  const [knowledgeSources,setKnowledgeSources]=useState<ChapterKnowledgeSelection[]>([]),[knowledgeChoices,setKnowledgeChoices]=useState<KnowledgeReferenceCandidate[]>([]),[knowledgeError,setKnowledgeError]=useState(''),[knowledgeTruncated,setKnowledgeTruncated]=useState(false),[knowledgeReading,setKnowledgeReading]=useState(false);
  const knowledgeSequence=useRef(0);
  async function readKnowledge(){const token=++knowledgeSequence.current;setKnowledgeReading(true);try{const next=await newDesignApi.getKnowledgeReferenceCandidates(bookId);if(token!==knowledgeSequence.current)return;setKnowledgeChoices(next.items);setKnowledgeTruncated(next.truncated);setKnowledgeError('');}catch(error){if(token===knowledgeSequence.current)setKnowledgeError(error instanceof Error?error.message:'知识参考未读取，已选原版本保留。');}finally{if(token===knowledgeSequence.current)setKnowledgeReading(false);}}
  useEffect(()=>{void readKnowledge();return()=>{knowledgeSequence.current++;};},[bookId]);
  const flight=useRef(false),sequence=useRef(0),run=workspace?.runs.find(item=>item.id===selected)??null;
  const capture=(value:unknown)=>setError(value instanceof Error?value:new Error('结果未确认，请保留原请求。'));
  const locked=busy||Boolean(pending)||storageBlocked||!draftLoaded||invalidRun;
  async function refresh(){const token=++sequence.current;try{const value=await newDesignApi.getDirectorWorkspace(bookId);if(value.bookId!==bookId||value.book.id!==bookId)throw new Error('导演目录来源与本书不一致，禁止替代。');if(requested&&!value.runs.some(item=>item.id===requested)){const exact=await newDesignApi.getDirectorRun(bookId,requested);if(exact.bookId!==bookId||exact.id!==requested)throw new Error('原导演记录来源不匹配，不选择其他记录代替。');value.runs=[exact,...value.runs];}if(token===sequence.current){setWorkspace(value);setNotice('已读取原记录；读取不继续任务、不生成正文。');}}catch(value){if(token===sequence.current)capture(value);}}
  useEffect(()=>{try{const raw=sessionStorage.getItem(directorPendingKey(bookId));if(raw)setPending(parseDirectorPending(raw,bookId));const draft=sessionStorage.getItem(directorDraftKey(bookId));if(draft){const value=parseDirectorDraft(draft,bookId);setChapters(value.chapters);setInstruction(value.instruction);setPolicy(value.policy);setKnowledgeSources(value.knowledgeSources??[]);}}catch{setStorageBlocked(true);}setDraftLoaded(true);void refresh();return()=>{sequence.current++;};},[bookId]);
  useEffect(()=>{if(!draftLoaded||storageBlocked)return;try{const raw=JSON.stringify({bookId,chapters,instruction,policy,knowledgeSources}),key=directorDraftKey(bookId);sessionStorage.setItem(key,raw);if(sessionStorage.getItem(key)!==raw)throw new Error('范围草稿未保存');}catch{setStorageBlocked(true);setNotice('本机未能保留未提交范围，当前填写仍在页面，禁止发出任务；请先复制要求保存。');}},[bookId,chapters,instruction,policy,knowledgeSources,storageBlocked,draftLoaded]);
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(pending||instruction||chapters.length||busy){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[pending,instruction,chapters,busy]);
  useEffect(()=>{if(busy||pending||!workspace?.runs.some(item=>item.status==='running'))return;const timer=window.setTimeout(()=>void refresh(),5000);return()=>window.clearTimeout(timer);},[workspace,busy,pending]);
  async function accept(value:DirectorReceipt,original:DirectorPending){if(value.run.bookId!==bookId||value.requestKey!==original.input.requestKey||value.action!==(original.kind==='create'?'create':original.input.action)||original.kind==='command'&&value.run.id!==original.runId)throw new Error('回执与本书原操作不一致，写入保持锁定。');
    setSaved(value);setSelected(value.run.id);setWorkspace(current=>current?{...current,runs:[value.run,...current.runs.filter(item=>item.id!==value.run.id)]}:current);setPending(null);setNotWritten(false);setChecked(false);setError(null);
    try{sessionStorage.removeItem(directorPendingKey(bookId));}catch{setStorageBlocked(true);setNotice('原操作回执已确认，本机标记未清除；重新打开时核对同一原回执。');}
    if(original.kind==='create'){setInstruction('');setChapters([]);}await refresh();
  }
  async function submit(value:DirectorPending){if(flight.current||locked)return;try{retainDirectorPending(value);}catch(error){capture(error);return;}setPending(value);setNotWritten(false);setChecked(false);flight.current=true;setBusy(true);setError(null);
    try{const result=value.kind==='create'?await newDesignApi.createDirectorRun(bookId,value.input):await newDesignApi.controlDirectorRun(bookId,value.runId,value.input);await accept(result,value);}catch(error){capture(error);setNotWritten(error instanceof ApiError&&error.recovery?.mutationOutcome==='not_written');}finally{flight.current=false;setBusy(false);}
  }
  async function check(){if(!pending||flight.current)return;flight.current=true;setBusy(true);try{const value=await newDesignApi.getDirectorReceipt(bookId,pending.input.requestKey);setChecked(true);if(value)await accept(value,pending);else setNotice('未读到原回执，不代表操作没有写入；继续按原凭证核对，不再调用模型。');}catch(value){capture(value);}finally{flight.current=false;setBusy(false);}}
  function prepareRange(){if(!workspace||locked)return;try{const chosen=workspace.writing.chapters.filter(item=>chapters.includes(item.chapterCardId));if(chosen.length!==chapters.length)throw new Error('所选章节未完整读取，请核对原范围；没有以其他章节代替。');const targets=chosen.map(item=>{const plan=workspace.planning.objects.find(plan=>plan.id===item.planningObjectId);if(!plan?.adoptedVersionId||plan.cardId!==item.chapterCardId||plan.adoptedVersionId!==item.planningVersionId)throw new Error(`“${item.title}”的已采用计划不一致，请重新读取并核对本章规划。`);return {planningObjectId:plan.id,planningVersionId:plan.adoptedVersionId,expectedPlanningRevision:plan.revision,chapterCardId:item.chapterCardId};});const input=directorCreateSchema.parse({requestKey:crypto.randomUUID(),chapters:targets,instruction,issuePolicy:policy,knowledgeSources});void submit({bookId,kind:'create',input});}catch(value){capture(value);}}
  function action(value:DirectorCommand['action']){if(!run||locked)return;if(['retry_failed','end_expired','cancel'].includes(value)&&!window.confirm(value==='end_expired'?'结束原过期领取会保留未知调用与用量记录，拒绝迟到覆盖；不会重新生成。是否确认？':value==='retry_failed'?'仅明确重试失败章，原候选和成功章保留，新调用可能产生用量。是否确认？':'结束此导演范围，已保存候选和正式正文保留。是否确认？'))return;void submit({bookId,kind:'command',runId:run.id,input:{requestKey:crypto.randomUUID(),expectedRevision:run.revision,action:value}});}
  const content=<main className='nd-director-page'>
    <header><h1>全书导演</h1><p>按已采用章计划逐章准备正文候选；在章节创作审阅、明确采用并确认变化。已有人工正文不会被批量覆盖。</p><a href={`/new-design/books/${bookId}/composition`}>查看全书编排</a></header>
    <button className='nd-button' disabled={busy} onClick={()=>void refresh()}>读取原运行记录</button>
    {invalidRun&&<section className='nd-message is-error' role='alert'><h2>运行来源不完整</h2><p>地址只允许一个真实运行凭证，不用另一项代替。当前填写保留，请返回本书导演目录核对来源。</p><a href={`/new-design/books/${bookId}/director`}>返回本书导演目录</a></section>}
    {error&&<section className='nd-message is-error' role='alert'><h2>{error instanceof ApiError?error.recovery?.failedStep??'处理导演操作':'核对导演结果'}</h2><p>{error.message}</p><p>{error instanceof ApiError?error.recovery?.savedResult:'已保存候选、正式正文和当前填写保留。'}</p><button className='nd-button' disabled={busy} onClick={()=>pending?void check():void refresh()}>{pending?'只读核对原操作':'读取来源状态'}</button><a href='/new-design/structure/models'>打开模型设置</a><a href='/new-design/structure/maintenance'>打开运行维护</a></section>}
    {notice&&<p role='status'>{notice}</p>}{saved&&<p>原操作回执已确认：{statusLabels[saved.run.status]}。后续读取失败不会撤销此回执。</p>}
    {storageBlocked&&<p role='alert'>本机原凭证不能确认，写入锁定；请保留浏览器存储，到运行记录核对来源，不新发任务。</p>}
    {pending&&<section className='nd-message'><h2>原操作结果待核对</h2><p>核对只读原凭证，不重新生成、不重复采用。</p><button className='nd-button' disabled={busy} onClick={()=>void check()}>核对原操作回执</button>{notWritten&&checked&&<button className='nd-button' disabled={busy} onClick={()=>{try{sessionStorage.removeItem(directorPendingKey(bookId));setPending(null);setNotWritten(false);setChecked(false);setNotice('服务器确认未写入；当前选择保留，请核对后明确重新准备。');}catch{setStorageBlocked(true);}}}>保留选择并重新准备</button>}</section>}
    {workspace&&<div className='nd-director-workspace'><aside aria-label='导演范围'><h2>运行范围</h2>{workspace.runs.map(item=><button className={selected===item.id?'is-selected':''} disabled={locked} key={item.id} onClick={()=>setSelected(item.id)}>{new Date(item.createdAt).toLocaleString('zh-CN')}<span>{statusLabels[item.status]} · {item.chapters.filter(chapter=>chapter.status==='candidate_saved').length}/{item.chapters.length} 章</span></button>)}{requested&&!run&&<p role='alert'>指定运行记录不属于本书或未读取，不以另一条记录代替。</p>}</aside>
      <section>{run?<><h2>{statusLabels[run.status]}</h2><p>{run.issuePolicy==='completion_first'?'完成优先：局部质量欠账记录为提醒，继续后续章。':'质量优先：明确需要人工审阅时停在已保存章边界。'}</p>{run.failure&&<section role='alert' className='nd-message is-error'><h3>{run.failure.failedStep}</h3><p>{run.failure.summary}</p><p>{run.failure.savedResult}</p><button className='nd-button' disabled={busy} onClick={()=>void refresh()}>读取本次章边界</button><a href={`/new-design/books/${bookId}/planning`}>回故事规划处理</a></section>}
        <div className='nd-row-actions'>
          {run.status==='ready'&&<button className='nd-button' disabled={locked} onClick={()=>action('run')}>明确开始逐章生成</button>}
          {run.status==='running'&&<button className='nd-button' disabled={locked||run.pauseRequested} onClick={()=>action('pause')}>{run.pauseRequested?'等待当前章完成后暂停':'请求章边界暂停'}</button>}
          {run.status==='paused'&&<button className='nd-button' disabled={locked} onClick={()=>action('resume')}>明确继续后续章</button>}
          {(run.status==='waiting_recovery'||run.status==='running'&&run.leaseExpired)&&run.chapters.filter(item=>item.status==='running'||item.status==='unknown'||item.ledgerPending||item.boundaryPending).every(item=>item.modelResultSaved)&&<><button className='nd-button' disabled={locked} onClick={()=>action('resume')}>核对原回复后明确继续范围</button><p>原回复只补入库与章边界，不再调用模型；后续未执行章继续生成，可能产生新用量。</p></>}
          {run.status==='failed'&&!run.chapters.some(item=>item.status==='candidate_saved'&&!item.boundaryPending&&item.decision==='stop_for_replan')&&run.chapters.some(item=>item.status==='failed'||item.status==='pending')&&<button className='nd-button' disabled={locked} onClick={()=>action('retry_failed')}>明确处理失败或未执行章</button>}
          {run.leaseExpired&&['running','waiting_recovery'].includes(run.status)&&!run.chapters.some(item=>item.ledgerPending||item.boundaryPending||(item.status==='running'||item.status==='unknown')&&(item.modelResultSaved||!item.unclaimed&&!item.leaseExpired))&&<button className='nd-button' disabled={locked} onClick={()=>action('end_expired')}>明确结束过期原范围</button>}
          {!['running','completed','cancelled'].includes(run.status)&&<button className='nd-button' disabled={locked} onClick={()=>action('cancel')}>结束此范围</button>}
        </div>
        <ol>{run.chapters.map(item=><li key={item.chapterCardId}><h3>{item.title}</h3><p>{chapterLabels[item.status]}</p>{item.warnings.map((warning,index)=><p className='nd-message' key={index}>{warning}</p>)}{item.failure&&<p role='alert'>{item.failure.failedStep}：{item.failure.summary}</p>}<a href={`/new-design/books/${bookId}/writing?chapter=${item.chapterCardId}`}>到本章核对候选、采用与结算</a><a href={`/new-design/books/${bookId}/planning?plan=${item.planningObjectId}`}>核对本章规划</a></li>)}</ol>
      </>:<p>从左侧选择运行范围，或在下方准备新的范围。</p>}
      <section><h2>准备章节范围</h2><p>按全书叙述顺序选择已采用计划的章节。保存范围不会调用模型，开始生成需再明确点击。</p>
        {workspace.writing.chapters.map(chapter=><label className='nd-director-choice' key={chapter.chapterCardId}><input type='checkbox' disabled={locked||!chapter.planningVersionId} checked={chapters.includes(chapter.chapterCardId)} onChange={event=>setChapters(current=>event.target.checked?[...current,chapter.chapterCardId]:current.filter(id=>id!==chapter.chapterCardId))}/>{chapter.volumeTitle}／{chapter.title}{!chapter.planningVersionId?'（请先采用计划）':''}</label>)}
        <label>本次要求<textarea value={instruction} maxLength={4000} disabled={locked} onChange={event=>setInstruction(event.target.value)}/></label>
        <section aria-label='本次知识参考'><h3>本次知识参考</h3><p>明确选择已解析参考；生成每章前核对原件、解析版本和完整正文，参考不是已发生的故事事实。</p><button className='nd-button' type='button' disabled={knowledgeReading} onClick={()=>void readKnowledge()}>只读刷新可用参考</button><a href={`/new-design/books/${bookId}/knowledge`}>上传、解析或查看知识参考</a>
          {knowledgeChoices.map(item=>{const selected=knowledgeSources.some(source=>source.parsedVersionId===item.parsedVersionId);return <label className='nd-director-choice' key={item.parsedVersionId}><input type='checkbox' checked={selected} disabled={locked||!selected&&knowledgeSources.length>=20} onChange={event=>setKnowledgeSources(current=>event.target.checked?[...current,{assetId:item.assetId,sourceVersionId:item.sourceVersionId,parsedVersionId:item.parsedVersionId,checksum:item.checksum}]:current.filter(source=>source.parsedVersionId!==item.parsedVersionId))}/><span>{item.title}</span></label>;})}
          {!knowledgeReading&&!knowledgeChoices.length&&<p>尚未读取到可用解析参考；可继续不使用知识参考，或先上传并解析。</p>}{knowledgeTruncated&&<p>可选列表超过显示范围，请到知识参考查找需要的来源，不假定已显示全部。</p>}
          {knowledgeSources.some(source=>!knowledgeChoices.some(item=>item.parsedVersionId===source.parsedVersionId&&item.assetId===source.assetId&&item.sourceVersionId===source.sourceVersionId&&item.checksum===source.checksum))&&<section role='alert'><p>已选原参考未在可用列表匹配；原版本保留，不自动换成另一版。核对来源后可明确移除本次选择。</p><button className='nd-button' disabled={locked} onClick={()=>setKnowledgeSources([])}>移除本次全部参考选择</button></section>}
          {knowledgeError&&<p role='alert'>未完成步骤：读取知识参考。{knowledgeError} 已选原版本保留；刷新只读取，不生成。</p>}
        </section>
        <label>问题处理方式<select disabled={locked} value={policy} onChange={event=>setPolicy(event.target.value as typeof policy)}><option value='completion_first'>完成优先，局部欠账后续处理</option><option value='quality_first'>质量优先，必要时人工审阅</option></select></label>
        <button className='nd-button nd-button-primary' disabled={locked||!chapters.length} onClick={prepareRange}>保存所选范围（{chapters.length} 章）</button>
      </section>
      </section></div>}
  </main>;
  return workspace?<BookShell book={workspace.book} active='director'>{content}</BookShell>:<div className='nd-shell'>{content}</div>;
}
