import {useState} from 'react';
import type {DirectorWorkspace} from '../../common/productionDirector';
import Help from '../storyWorkspace/Help';
export default function DirectorRangeSelector({workspace,selected,onChange,disabled}:{workspace:DirectorWorkspace;selected:string[];onChange:(ids:string[])=>void;disabled:boolean}) {
 const [volume,setVolume]=useState('all'),[query,setQuery]=useState(''),[first,setFirst]=useState(''),[last,setLast]=useState(''),[message,setMessage]=useState('');
 const rows=workspace.writing.chapters,volumes=workspace.planning.objects.filter(object=>object.level==='volume'&&object.status==='active').sort((a,b)=>a.sortOrder-b.sortOrder);
 const eligible=(id:string)=>{const chapter=rows.find(item=>item.chapterCardId===id),plan=workspace.planning.objects.find(item=>item.id===chapter?.planningObjectId&&item.status==='active');return Boolean(chapter?.planningVersionId&&plan?.adoptedVersionId===chapter.planningVersionId);};
 const visible=rows.filter(chapter=>(volume==='all'||chapter.volumePlanningObjectId===volume)&&(!query||`${chapter.volumeTitle} ${chapter.title}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
 const change=(next:string[])=>{if(disabled)return;if(next.length>500){setMessage('一次范围最多 500 章，请缩小范围；当前选择保留。');return;}setMessage('');onChange(next);};
 const include=(ids:string[])=>change([...new Set([...selected,...ids.filter(eligible)])]);
 const interval=()=>{const start=rows.findIndex(chapter=>chapter.chapterCardId===first),end=rows.findIndex(chapter=>chapter.chapterCardId===last);if(start<0||end<start){setMessage('请按叙述顺序选择起止章节；当前选择保留。');return;}const target=rows.slice(start,end+1);if(target.some(chapter=>!eligible(chapter.chapterCardId))){setMessage('起止范围包含未采用或已变化的计划，未加入任何章节。请先核对本章规划。');return;}include(target.map(chapter=>chapter.chapterCardId));};
 return <section className="nd-director-range"><h3>卷章范围 <Help label="卷章范围">批量选择只调整本次范围。保存范围不调用模型，明确开始才逐章生成候选；表内采用与稳定结算读取原章节状态，候选保存不等于正式作品完成。</Help></h3>
  <div className="nd-row-actions"><label>卷<select value={volume} onChange={event=>setVolume(event.target.value)}><option value="all">全书</option>{volumes.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>查找章节<input value={query} onChange={event=>setQuery(event.target.value)}/></label><button type="button" className="nd-button" disabled={disabled} onClick={()=>include(visible.map(chapter=>chapter.chapterCardId))}>加入筛选内已采用计划</button><button type="button" className="nd-button" disabled={disabled} onClick={()=>change(selected.filter(id=>!visible.some(chapter=>chapter.chapterCardId===id)))}>移除筛选内选择</button><button type="button" className="nd-button" disabled={disabled||!selected.length} onClick={()=>change([])}>清空本次选择</button></div>
  <div className="nd-row-actions"><label>起章<select value={first} disabled={disabled} onChange={event=>setFirst(event.target.value)}><option value="">选择起章</option>{rows.map((chapter,index)=><option key={chapter.chapterCardId} value={chapter.chapterCardId}>{index+1} · {chapter.title}</option>)}</select></label><label>止章<select value={last} disabled={disabled} onChange={event=>setLast(event.target.value)}><option value="">选择止章</option>{rows.map((chapter,index)=><option key={chapter.chapterCardId} value={chapter.chapterCardId}>{index+1} · {chapter.title}</option>)}</select></label><button type="button" className="nd-button" disabled={disabled||!first||!last} onClick={interval}>加入完整起止范围</button></div>
  <p>本次选择 {selected.length} 章 · 当前显示 {visible.length} / {rows.length} 章</p>{message&&<p role="alert">{message}</p>}
  <div className="nd-table-scroll"><table><caption>选择按原全书叙述顺序执行，不按勾选顺序重排</caption><thead><tr><th scope="col">选择</th><th scope="col">卷／章</th><th scope="col">采用计划</th><th scope="col">正文候选</th><th scope="col">正式进度</th></tr></thead><tbody>{visible.map(chapter=><tr key={chapter.chapterCardId}><td><input type="checkbox" aria-label={`选择 ${chapter.title}`} disabled={disabled||!eligible(chapter.chapterCardId)} checked={selected.includes(chapter.chapterCardId)} onChange={event=>change(event.target.checked?[...selected,chapter.chapterCardId]:selected.filter(id=>id!==chapter.chapterCardId))}/></td><th scope="row"><small>{chapter.volumeTitle}</small><br/>{chapter.title}</th><td>{chapter.planningVersionNumber?`v${chapter.planningVersionNumber}`:'待采用'}</td><td>{chapter.candidateCount} 个{chapter.pendingRequestCount?` · ${chapter.pendingRequestCount} 个原请求待核对`:''}</td><td>{chapter.state==='stable'?'当前正文已稳定结算':chapter.adoptedBodyVersionId?'已有采用正文，需核对结算':'尚无采用正文'}</td></tr>)}</tbody></table></div>{!visible.length&&<p>暂无匹配章节，请调整筛选或先建立章节计划。</p>}
 </section>;
}
