import {insertContractRecord} from "../aiContracts/records";
import {assertImagePreparationSelection} from '../imagePreparation';
import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import {IMAGE_CONTRACT,IMAGE_CAPABILITIES,type ImageGenerationInput,type PublicImageProtocolInput,type ImageConnectionVersion} from "../../../common/imageGeneration";
import {stableHash} from "../aiContracts";
import {prepareImageContract} from "../../ai/imageGeneration/contract";
export async function freezeImageRequest(client:PoolClient,id:string,input:ImageGenerationInput|PublicImageProtocolInput,connection:ImageConnectionVersion){
 const publicSource='portraitSource' in input?input.portraitSource:null,bookId='bookId' in input?input.bookId:null;
 await assertImagePreparationSelection(client,publicSource?{kind:'public_character',resourceId:publicSource.id,resourceVersionId:publicSource.versionId}:{kind:'book',bookId:bookId!},input.prompt,input.preparation);
 const recipeId=randomUUID(),recipeVersionId=randomUUID(),contractId=randomUUID(),contractVersionId=randomUUID(),snapshotId=randomUUID(),manifestId=randomUUID(),key=`image_generation_${id}`,contract=prepareImageContract(input);
 const variables={type:"object",const:input,"x-image-generation":{requestId:id,assetId:contract.assetId,assetVersion:contract.assetVersion,protocol:contract.protocol,connectionVersionId:connection.id},...(publicSource?{"x-public-character":{contract:"public_character_trial_v1",resourceId:publicSource.id}}:{})},inputSchema={type:"object",const:input};
 await client.query("INSERT INTO new_design.prompt_recipes(id,recipe_key,name,description) VALUES($1,$2,'单图生成要求','本次明确填写的画面要求；不读取全书资料')",[recipeId,key]);
 await client.query("INSERT INTO new_design.prompt_recipe_versions(id,recipe_id,version,source,status,variables_schema,content_hash,created_by) VALUES($1,$2,1,'system','draft',$3::jsonb,$4,'image_generation')",[recipeVersionId,recipeId,JSON.stringify(variables),stableHash({variables,contract})]);await client.query("UPDATE new_design.prompt_recipe_versions SET status='published' WHERE id=$1",[recipeVersionId]);await client.query("UPDATE new_design.prompt_recipes SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1",[recipeId,recipeVersionId]);await insertContractRecord(client,"ai_contract_publication",{id:randomUUID(),entity_kind:"prompt_recipe",entity_id:recipeId,to_version_id:recipeVersionId,entity_revision:2,action:"publish",actor:"image_generation",idempotency_key:`image_recipe_${id}`,from_version_id:null});
 await client.query("INSERT INTO new_design.task_contracts(id,task_key,name,description) VALUES($1,$2,'生成图片候选','单张图片候选；采用和绑定由作者分别确认')",[contractId,key]);await client.query("INSERT INTO new_design.task_contract_versions(id,contract_id,version,source,status,task_group,input_schema,input_schema_version,output_schema,output_schema_version,context_policy_version,prompt_recipe_version_id,required_capabilities,budget_policy,timeout_ms,retry_policy,confirmation_policy,content_hash,created_by) VALUES($1,$2,1,'system','draft','image_generation',$3::jsonb,$4,$5::jsonb,$6,'image-explicit-input-v1',$7,$8,$9::jsonb,$10,'{\"maxAttempts\":1,\"automaticRetry\":false}','before_adopt',$11,'image_generation')",[contractVersionId,contractId,JSON.stringify(inputSchema),stableHash(inputSchema),JSON.stringify(contract.outputSchema),stableHash(contract.outputSchema),recipeVersionId,[...IMAGE_CAPABILITIES],JSON.stringify({assetId:contract.assetId,assetVersion:contract.assetVersion,maxImages:1}),connection.timeoutMs,stableHash({inputSchema,contract,connectionHash:connection.connectionHash})]);await client.query("UPDATE new_design.task_contract_versions SET status='published' WHERE id=$1",[contractVersionId]);await client.query("UPDATE new_design.task_contracts SET current_version_id=$2,published_version_id=$2,revision=2 WHERE id=$1",[contractId,contractVersionId]);await insertContractRecord(client,"ai_contract_publication",{id:randomUUID(),entity_kind:"task_contract",entity_id:contractId,to_version_id:contractVersionId,entity_revision:2,action:"publish",actor:"image_generation",idempotency_key:`image_contract_${id}`,from_version_id:null});
 const parameters={baseUrl:connection.endpoint,imageProtocol:connection.protocol,imageSizes:connection.sizes},sourceLayers=[{scope:"task_group",configId:connection.configId,versionId:connection.id}],snapshotHash=stableHash({connection,input,contractVersionId});
 await client.query("INSERT INTO new_design.model_route_snapshots(id,book_id,task_contract_version_id,node_key,provider,model,parameters,required_capabilities,credential_ref_id,budget_policy,timeout_ms,retry_policy,source_layers,policy_version,snapshot_hash,managed_task_key) VALUES($1,$2,$3,'image_generation',$4,$5,$6::jsonb,$7,$8,'{\"maxImages\":1}',$9,'{\"maxRetries\":0,\"retryDelayMs\":0}',$10::jsonb,'image-explicit-version-v1',$11,$12)",[snapshotId,bookId,publicSource?null:contractVersionId,connection.provider,connection.model,JSON.stringify(parameters),[...IMAGE_CAPABILITIES],connection.credentialId,connection.timeoutMs,JSON.stringify(sourceLayers),snapshotHash,publicSource?"image_generation":null]);
 if(publicSource)await client.query("INSERT INTO new_design.context_manifests(id,book_id,public_character_scope,task_contract_version_id,prompt_recipe_version_id,node_key,status,manifest_hash,created_by,task_group,model_route_snapshot_id,source_set_hash,decision_summary) VALUES($1,NULL,$2,$3,$4,'image_generation','complete',$5,'public_characters','image_generation',$6,$7,$8::jsonb)",[manifestId,publicSource.id,contractVersionId,recipeVersionId,stableHash(input),snapshotId,publicSource.hash,JSON.stringify({contract:'public_character_trial_v1',requestId:id,selection:'exact_public_character_version'})]);
 else await client.query("INSERT INTO new_design.context_manifests(id,book_id,task_contract_version_id,prompt_recipe_version_id,node_key,status,manifest_hash,created_by,task_group,model_route_snapshot_id,source_set_hash,decision_summary) VALUES($1,$2,$3,$4,'image_generation','complete',$5,'image_generation','image_generation',$6,$7,$8::jsonb)",[manifestId,bookId,contractVersionId,recipeVersionId,stableHash(input),snapshotId,stableHash([]),JSON.stringify({selection:"explicit_image_input_only",requestId:id})]);
 return{contractVersionId,recipeVersionId,snapshotId,snapshotHash,manifestId,input,connection,protocol:IMAGE_CONTRACT.protocol,connectionVersionId:connection.id,connectionHash:connection.connectionHash,contract};
}
