import { useEffect, useRef, useState } from "react";
import type { CardTypeTagBinding, MaterialManagementWorkspace, TagDimension } from "../../common/contracts";
import { newDesignApi, type MaterialApiScope } from "../api";
import TreeSelector from "./TreeSelector";

interface Props{scope:MaterialApiScope;spaceId:string;cardTypeId:string;cardId:string;selectedTagIds?:string[];onDraftChange?:(ids:string[])=>void;onInitialTags?:(ids:string[])=>void;disabled?:boolean;}

export default function CardTagFields({scope,spaceId,cardTypeId,cardId,selectedTagIds,onDraftChange,onInitialTags,disabled}:Props){
  const [bindings,setBindings]=useState<CardTypeTagBinding[]>([]),[dimensions,setDimensions]=useState<TagDimension[]>([]),[workspace,setWorkspace]=useState<MaterialManagementWorkspace|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const loadGeneration=useRef(0);
  const load=async()=>{const generation=++loadGeneration.current;const [nextBindings,nextDimensions,nextWorkspace]=await Promise.all([newDesignApi.listCardTypeTagBindings(cardTypeId),newDesignApi.listTagDimensions(spaceId),newDesignApi.getMaterialWorkspace(scope)]);if(generation!==loadGeneration.current)return;setBindings(nextBindings);setDimensions(nextDimensions);setWorkspace(nextWorkspace);onInitialTags?.(nextWorkspace.memberships.find(item=>item.cardId===cardId)?.tagIds??[]);};
  useEffect(()=>{void load().catch(error=>setMessage(error instanceof Error?error.message:"标签维度加载失败。"));return()=>{loadGeneration.current++;};},[cardTypeId,cardId,spaceId]);
  const membership=workspace?.memberships.find(item=>item.cardId===cardId),selected=new Set(selectedTagIds??membership?.tagIds??[]);
  const change=async(binding:CardTypeTagBinding,nextIds:string[])=>{const dimension=dimensions.find(item=>item.id===binding.dimensionId);if(!dimension)return;const previous=dimension.nodes.filter(node=>selected.has(node.id)).map(node=>node.id);if(onDraftChange){const own=new Set(dimension.nodes.map(node=>node.id));onDraftChange([...selected].filter(id=>!own.has(id)).concat(nextIds));setMessage("标签已填入草稿，保存资料后生效。");return;}const add=nextIds.filter(id=>!previous.includes(id)),remove=previous.filter(id=>!nextIds.includes(id));setBusy(true);setMessage("");try{for(const id of add)await newDesignApi.changeTagMemberships(scope,id,{cardIds:[cardId],action:"add",idempotencyKey:crypto.randomUUID()});for(const id of remove)await newDesignApi.changeTagMemberships(scope,id,{cardIds:[cardId],action:"remove",idempotencyKey:crypto.randomUUID()});await load();setMessage("分类标签已保存。");}catch(error){setMessage(error instanceof Error?error.message:"标签保存失败。");}finally{setBusy(false);}};
  if(!bindings.length)return null;
  return <section className="nd-card-tag-fields"><div><p className="nd-kicker">分类与检索</p><h3>多维标签</h3><p className="nd-help-text">标签用于分类筛选与 AI 参考。{onDraftChange?"检查后随资料一起保存。":""}</p></div>{bindings.map(binding=>{const dimension=dimensions.find(item=>item.id===binding.dimensionId);if(!dimension)return <p className="nd-help-text" key={binding.id}>{binding.dimensionName}尚未安装到当前空间。</p>;return <TreeSelector key={binding.id} label={binding.dimensionName} nodes={dimension.nodes.map(node=>({id:node.id,parentId:node.parentId,name:node.name,description:String(node.metadata.description??""),status:node.status,path:node.path.map(part=>part.name)}))} rule={binding.rule} selectedIds={dimension.nodes.filter(node=>selected.has(node.id)).map(node=>node.id)} disabled={busy||disabled} onChange={ids=>void change(binding,ids)}/>;})}{message&&<p className="nd-message" aria-live="polite">{message}</p>}</section>;
}
