import {z} from 'zod';
import {experienceTimeSchema} from '../schema';
import type {RecentBodyExperienceSnapshot,RecentBodyExperienceRecord} from '.';
const uuid=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/);
const scope={characterIds:z.array(uuid).min(1).max(20),chapterDocumentIds:z.array(uuid).min(1).max(5)};
const unique=(input:{characterIds:string[];chapterDocumentIds:string[]})=>new Set(input.characterIds).size===input.characterIds.length&&new Set(input.chapterDocumentIds).size===input.chapterDocumentIds.length;
export const recentBodySelectionSchema=z.object(scope).strict().refine(unique,'人物与采用正文范围不能重复。');
export const recentBodyExperienceRequestSchema=z.object({...scope,requestKey:uuid,instruction:z.string().trim().max(2000),expectedSourceHash:hash}).strict().refine(unique,'人物与采用正文范围不能重复。');
export const recentBodyExperienceCandidateSourceSchema=z.object({contract:z.literal('character_recent_body_candidate_v1'),batchId:uuid,candidateId:uuid,characterId:uuid,sourceHash:hash}).strict();
export function recentBodyExperienceSchemaFor(input:RecentBodyExperienceSnapshot){
 if(input?.contract!=='character_recent_body_experiences_v1'||!uuid.safeParse(input.bookId).success||!Array.isArray(input.actors)||!Array.isArray(input.bodies)||!recentBodySelectionSchema.safeParse({characterIds:input.actors.map(actor=>actor.id),chapterDocumentIds:input.bodies.map(body=>body.documentId)}).success||!Array.isArray(input.events)||input.events.length>300||new Set(input.events.map(event=>event.id)).size!==input.events.length)throw new Error('最近采用正文经历来源不完整。');
 const slots=input.actors.flatMap(actor=>actor.slotIds);if(slots.length!==input.actors.length*3||new Set(slots).size!==slots.length||slots.some(id=>!uuid.safeParse(id).success)||input.bodies.some(body=>!uuid.safeParse(body.bodyVersionId).success||!hash.safeParse(body.contentHash).success||typeof body.content!=='string'))throw new Error('原人物候选位置或正文身份不完整。');
 const variants=input.actors.map(actor=>z.object({id:z.enum(actor.slotIds as [string,...string[]]),characterId:z.literal(actor.id),chapterDocumentId:z.enum(input.bodies.map(body=>body.documentId) as [string,...string[]]),bodyVersionId:uuid,title:z.string().trim().min(1).max(300),summary:z.string().min(1).max(10000),evidenceStart:z.number().int().nonnegative(),evidenceEnd:z.number().int().positive(),evidenceLabel:z.string().min(1).max(10000),suggestedEventId:input.events.length?z.enum(input.events.map(event=>event.id) as [string,...string[]]).nullable():z.null(),narrativeRole:z.enum(['mention','scene','reveal','retell','flashback','flashforward']),time:experienceTimeSchema.extend({lifecycle:z.enum(['planned','occurred'])}).strict()}).strict());
 const candidate=variants.length===1?variants[0]!:z.union([variants[0]!,variants[1]!,...variants.slice(2)]);
 return z.object({candidates:z.array(candidate).max(input.actors.length*3),notes:z.array(z.string().max(4000)).max(30)}).strict().superRefine((out,ctx)=>{const seen=new Set<string>();for(const [index,item]of out.candidates.entries()){const body=input.bodies.find(body=>body.documentId===item.chapterDocumentId);if(seen.has(item.id)||!body||body.bodyVersionId!==item.bodyVersionId||item.evidenceStart>=item.evidenceEnd||item.evidenceEnd>body.content.length||body.content.slice(item.evidenceStart,item.evidenceEnd)!==item.evidenceLabel||item.time.relativeToEventCardId&&!input.events.some(event=>event.id===item.time.relativeToEventCardId))ctx.addIssue({code:'custom',path:['candidates',index],message:'原人物、采用正文版本、时间参照或UTF-16证据不匹配。'});seen.add(item.id);}});
}
export function validRecentBodyExperienceRecord(value:unknown):value is RecentBodyExperienceRecord{try{const record=value as RecentBodyExperienceRecord;if(!record||!uuid.safeParse(record.id).success||!uuid.safeParse(record.bookId).success||!recentBodyExperienceRequestSchema.safeParse(record.request).success||record.id!==record.request.requestKey||record.bookId!==record.snapshot?.bookId||!['running','review','failed','discarded'].includes(record.status)||typeof record.stage!=='string'||typeof record.error!=='string'||record.request.characterIds.length!==record.snapshot.actors.length||record.request.chapterDocumentIds.length!==record.snapshot.bodies.length||record.snapshot.actors.some((actor,index)=>actor.id!==record.request.characterIds[index])||record.snapshot.bodies.some((body,index)=>body.documentId!==record.request.chapterDocumentIds[index]))return false;const schema=recentBodyExperienceSchemaFor(record.snapshot);return record.status==='review'?record.output!==null&&schema.safeParse(record.output).success:record.output===null||schema.safeParse(record.output).success;}catch{return false;}}
