SET search_path TO new_design,public;
-- A non-factual sandbox and immutable original-command evidence, never knowledge/state/body facts.
CREATE TABLE character_dialogue_sessions(
 id uuid PRIMARY KEY,book_id uuid NOT NULL REFERENCES books(id),request_key uuid NOT NULL,request_hash char(64) NOT NULL CHECK(request_hash ~ '^[0-9a-f]{64}$'),input_payload jsonb NOT NULL CHECK(jsonb_typeof(input_payload)='object'),frozen_sources jsonb NOT NULL CHECK(jsonb_typeof(frozen_sources)='object'),revision integer NOT NULL DEFAULT 1 CHECK(revision>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(book_id,request_key),UNIQUE(id,book_id));
CREATE TABLE character_dialogue_rounds(
 id uuid PRIMARY KEY,session_id uuid NOT NULL,book_id uuid NOT NULL,round_number integer NOT NULL CHECK(round_number BETWEEN 1 AND 50),request_key uuid NOT NULL,request_hash char(64) NOT NULL CHECK(request_hash ~ '^[0-9a-f]{64}$'),input_payload jsonb NOT NULL CHECK(jsonb_typeof(input_payload)='object'),input_hash char(64) NOT NULL CHECK(input_hash ~ '^[0-9a-f]{64}$'),frozen_plan jsonb NOT NULL CHECK(jsonb_typeof(frozen_plan)='object'),ai_task_id uuid NOT NULL UNIQUE REFERENCES ai_tasks(id),step_id uuid NOT NULL UNIQUE REFERENCES ai_task_steps(id),attempt_id uuid NOT NULL UNIQUE REFERENCES ai_task_attempts(id),status text NOT NULL DEFAULT 'running' CHECK(status IN('running','succeeded','failed','stale','ended_unknown')),model_request_state text NOT NULL DEFAULT 'not_sent' CHECK(model_request_state IN('not_sent','sent_unknown','completed')),generated_output jsonb,generated_execution jsonb,failure jsonb,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(session_id,book_id) REFERENCES character_dialogue_sessions(id,book_id),UNIQUE(book_id,request_key),UNIQUE(session_id,round_number),UNIQUE(id,session_id,book_id));
CREATE TABLE character_dialogue_selections(
 id uuid PRIMARY KEY,session_id uuid NOT NULL,book_id uuid NOT NULL,request_key uuid NOT NULL,request_hash char(64) NOT NULL CHECK(request_hash ~ '^[0-9a-f]{64}$'),input_payload jsonb NOT NULL CHECK(jsonb_typeof(input_payload)='object'),round_id uuid NOT NULL,planning_object_id uuid NOT NULL,planning_version_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(session_id,book_id) REFERENCES character_dialogue_sessions(id,book_id),FOREIGN KEY(round_id,session_id,book_id) REFERENCES character_dialogue_rounds(id,session_id,book_id),FOREIGN KEY(planning_version_id,planning_object_id) REFERENCES planning_versions(id,object_id),UNIQUE(book_id,request_key));
CREATE FUNCTION guard_character_dialogue_session() RETURNS trigger LANGUAGE plpgsql SET search_path TO new_design,public AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'dialogue sandbox history cannot be deleted' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' AND ((to_jsonb(OLD)-'revision') IS DISTINCT FROM (to_jsonb(NEW)-'revision') OR NEW.revision<>OLD.revision+1) THEN RAISE EXCEPTION 'dialogue sources and original input immutable' USING ERRCODE='23514'; END IF;
 IF NEW.frozen_sources->>'bookId' IS DISTINCT FROM NEW.book_id::text OR NEW.input_payload->>'requestKey' IS DISTINCT FROM NEW.request_key::text OR NEW.frozen_sources->>'hash' IS DISTINCT FROM NEW.input_payload->>'sourceHash' OR NOT EXISTS(SELECT 1 FROM chapter_stable_checkpoints checkpoint JOIN chapter_documents document ON document.id=checkpoint.chapter_document_id AND document.book_id=checkpoint.book_id WHERE checkpoint.id::text=NEW.input_payload->>'checkpointId' AND checkpoint.book_id=NEW.book_id AND checkpoint.body_version_id::text=NEW.frozen_sources->'checkpoint'->>'bodyVersionId') THEN RAISE EXCEPTION 'dialogue cutoff source identity mismatch' USING ERRCODE='23514'; END IF;RETURN NEW;
END $$;
CREATE TRIGGER character_dialogue_session_guard BEFORE INSERT OR UPDATE OR DELETE ON character_dialogue_sessions FOR EACH ROW EXECUTE FUNCTION guard_character_dialogue_session();
CREATE FUNCTION guard_character_dialogue_round() RETURNS trigger LANGUAGE plpgsql SET search_path TO new_design,public AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'dialogue original reply cannot be deleted' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' THEN
  IF (to_jsonb(OLD)-ARRAY['status','model_request_state','generated_output','generated_execution','failure']::text[]) IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['status','model_request_state','generated_output','generated_execution','failure']::text[]) THEN RAISE EXCEPTION 'dialogue original freeze immutable' USING ERRCODE='23514'; END IF;
  IF OLD.generated_output IS NOT NULL AND (OLD.generated_output,OLD.generated_execution) IS DISTINCT FROM(NEW.generated_output,NEW.generated_execution) THEN RAISE EXCEPTION 'dialogue original saved reply immutable' USING ERRCODE='23514'; END IF;
  IF OLD.status<>'running' AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'dialogue terminal round immutable' USING ERRCODE='23514'; END IF;
 END IF;
 IF NOT EXISTS(SELECT 1 FROM ai_tasks task JOIN ai_task_steps step ON step.task_id=task.id JOIN ai_task_attempts attempt ON attempt.task_id=task.id AND attempt.step_id=step.id JOIN task_contract_versions contract ON contract.id=attempt.task_contract_version_id JOIN character_dialogue_sessions session ON session.id=NEW.session_id AND session.book_id=NEW.book_id WHERE task.id=NEW.ai_task_id AND task.book_id=NEW.book_id AND task.source_kind='character_dialogue' AND task.source_id=NEW.id AND step.id=NEW.step_id AND step.max_attempts=1 AND step.current_attempt_id=attempt.id AND attempt.id=NEW.attempt_id AND attempt.attempt_number=1 AND attempt.input_hash=NEW.input_hash AND attempt.output_schema_version=contract.output_schema_version AND NEW.frozen_plan->>'sourceHash'=session.frozen_sources->>'hash' AND NEW.input_payload->>'requestKey'=NEW.request_key::text AND NEW.input_payload->>'sourceHash'=session.frozen_sources->>'hash' AND NEW.frozen_plan->'input'->'actor'->>'cardId'=NEW.input_payload->>'actorCardId' AND NEW.frozen_plan->'input'->>'sessionId'=session.id::text AND NEW.frozen_plan->'input'->>'roundId'=NEW.id::text) THEN RAISE EXCEPTION 'dialogue true original attempt and source mismatch' USING ERRCODE='23514'; END IF;
 IF NEW.generated_output IS NOT NULL AND (NEW.generated_execution IS NULL OR jsonb_typeof(NEW.generated_output)<>'object' OR jsonb_typeof(NEW.generated_execution)<>'object' OR NEW.model_request_state<>'completed' OR NEW.generated_execution->>'routeSnapshotId' IS DISTINCT FROM NEW.frozen_plan->>'snapshotId' OR NEW.generated_execution->>'routeSnapshotHash' IS DISTINCT FROM NEW.frozen_plan->>'snapshotHash' OR NEW.generated_execution->>'provider' IS DISTINCT FROM NEW.frozen_plan->'route'->'primary'->>'provider' OR NEW.generated_execution->>'model' IS DISTINCT FROM NEW.frozen_plan->'route'->'primary'->>'model' OR NEW.generated_output->>'actorCardId' IS DISTINCT FROM NEW.input_payload->>'actorCardId' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(COALESCE(NEW.generated_execution->'attempts','[]'::jsonb)) execution WHERE execution->>'status'='succeeded' AND execution->>'requestSent'='true' AND execution->>'responseReceived'='true')) THEN RAISE EXCEPTION 'dialogue saved reply requires true received execution' USING ERRCODE='23514'; END IF;
 IF NEW.status='succeeded' AND (NEW.generated_output IS NULL OR NOT EXISTS(SELECT 1 FROM ai_task_attempts WHERE id=NEW.attempt_id AND status='succeeded')) THEN RAISE EXCEPTION 'dialogue success requires original saved reply and completed attempt' USING ERRCODE='23514'; END IF;
 IF NEW.status='ended_unknown' AND NEW.generated_output IS NOT NULL THEN RAISE EXCEPTION 'saved dialogue reply cannot be unknown' USING ERRCODE='23514'; END IF;RETURN NEW;
END $$;
CREATE TRIGGER character_dialogue_round_guard BEFORE INSERT OR UPDATE OR DELETE ON character_dialogue_rounds FOR EACH ROW EXECUTE FUNCTION guard_character_dialogue_round();
CREATE TRIGGER character_dialogue_selection_append_only BEFORE UPDATE OR DELETE ON character_dialogue_selections FOR EACH ROW EXECUTE FUNCTION guard_quality_append_only();
CREATE FUNCTION guard_character_dialogue_selection() RETURNS trigger LANGUAGE plpgsql SET search_path TO new_design,public AS $$ DECLARE original_round character_dialogue_rounds; original_version planning_versions; saved_version planning_versions; appended jsonb; selected_count integer; BEGIN
 IF NEW.input_payload->>'requestKey' IS DISTINCT FROM NEW.request_key::text OR NEW.input_payload->>'planningObjectId' IS DISTINCT FROM NEW.planning_object_id::text OR jsonb_typeof(NEW.input_payload->'actionKeys') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'dialogue original action input required' USING ERRCODE='23514'; END IF;
 IF NOT EXISTS(SELECT 1 FROM character_dialogue_rounds round JOIN character_dialogue_sessions session ON session.id=round.session_id AND session.book_id=round.book_id JOIN planning_versions version ON version.id=NEW.planning_version_id AND version.object_id=NEW.planning_object_id AND version.book_id=NEW.book_id JOIN planning_operation_events event ON event.version_id=version.id AND event.object_id=version.object_id AND event.book_id=version.book_id WHERE round.id=NEW.round_id AND round.session_id=NEW.session_id AND round.book_id=NEW.book_id AND round.status='succeeded' AND round.generated_output IS NOT NULL AND version.source='user' AND version.status IN('draft','proposed') AND event.action='revise' AND event.idempotency_key=NEW.request_key::text AND event.expected_revision::text=NEW.input_payload->>'expectedPlanningRevision' AND NEW.input_payload->>'roundId'=round.id::text AND NEW.input_payload->>'sourceHash'=session.frozen_sources->>'hash') THEN RAISE EXCEPTION 'dialogue selected actions require original successful round and real planning candidate' USING ERRCODE='23514'; END IF;
 SELECT * INTO original_round FROM character_dialogue_rounds WHERE id=NEW.round_id;
 SELECT * INTO saved_version FROM planning_versions WHERE id=NEW.planning_version_id;
 SELECT * INTO original_version FROM planning_versions WHERE id=saved_version.base_version_id AND id::text=NEW.input_payload->>'planningVersionId' AND object_id=NEW.planning_object_id AND book_id=NEW.book_id;
 selected_count:=jsonb_array_length(NEW.input_payload->'actionKeys');
 IF original_version.id IS NULL OR selected_count NOT BETWEEN 1 AND 20 OR (SELECT count(DISTINCT value) FROM jsonb_array_elements(NEW.input_payload->'actionKeys'))<>selected_count THEN RAISE EXCEPTION 'dialogue original planning basis or selected keys invalid' USING ERRCODE='23514'; END IF;
 SELECT jsonb_agg(action->'constraint' ORDER BY selected.ordinality) INTO appended FROM jsonb_array_elements_text(NEW.input_payload->'actionKeys') WITH ORDINALITY selected(key,ordinality) JOIN LATERAL jsonb_array_elements(original_round.generated_output->'actions') action ON action->>'key'=selected.key;
 IF appended IS NULL OR jsonb_array_length(appended)<>selected_count OR jsonb_typeof(original_version.content->'constraints') IS DISTINCT FROM 'array' OR (saved_version.content-'constraints') IS DISTINCT FROM (original_version.content-'constraints') OR saved_version.content->'constraints' IS DISTINCT FROM ((original_version.content->'constraints')||appended) OR saved_version.execution_mode IS DISTINCT FROM original_version.execution_mode OR saved_version.based_on_parent_version_id IS DISTINCT FROM original_version.based_on_parent_version_id OR saved_version.source_body_version_id IS NOT NULL THEN RAISE EXCEPTION 'dialogue may only append exact selected constraints to original planning draft' USING ERRCODE='23514'; END IF;
 IF jsonb_array_length(saved_version.content->'constraints')>100 OR (SELECT count(DISTINCT value) FROM jsonb_array_elements(appended))<>selected_count OR EXISTS(SELECT 1 FROM jsonb_array_elements(appended) chosen JOIN jsonb_array_elements(original_version.content->'constraints') prior ON chosen.value=prior.value) THEN RAISE EXCEPTION 'dialogue duplicate or excessive new constraints prohibited' USING ERRCODE='23514'; END IF;
 IF (SELECT COALESCE(jsonb_agg(jsonb_build_array(reference_role,card_id,card_version_id,action_key,note,sort_order) ORDER BY reference_role,card_id,action_key),'[]'::jsonb) FROM planning_version_references WHERE planning_version_id=saved_version.id) IS DISTINCT FROM (SELECT COALESCE(jsonb_agg(jsonb_build_array(reference_role,card_id,card_version_id,action_key,note,sort_order) ORDER BY reference_role,card_id,action_key),'[]'::jsonb) FROM planning_version_references WHERE planning_version_id=original_version.id) THEN RAISE EXCEPTION 'dialogue selected constraints cannot replace original planning references' USING ERRCODE='23514'; END IF;RETURN NEW;
END $$;
CREATE TRIGGER character_dialogue_selection_guard BEFORE INSERT ON character_dialogue_selections FOR EACH ROW EXECUTE FUNCTION guard_character_dialogue_selection();
