-- Manual only. Requires 097; never install through ordinary startup.
SET search_path TO new_design,public;
CREATE TABLE image_preparation_capability(contract text PRIMARY KEY CHECK(contract='image_prompt_preparation_v1'),operational boolean NOT NULL DEFAULT false);
INSERT INTO image_preparation_capability(contract) VALUES('image_prompt_preparation_v1');
-- Preserve the installed public-manifest function OID and all original guards.
DO $$ DECLARE definition text; old_clause text:='contract.task_group IN (''character_dialogue'',''image_generation'')'; BEGIN
 definition:=pg_get_functiondef('new_design.guard_public_character_manifest()'::regprocedure);
 IF strpos(definition,old_clause)=0 THEN RAISE EXCEPTION 'unexpected public manifest guard'; END IF;
 EXECUTE replace(definition,old_clause,'(contract.task_group IN (''character_dialogue'',''image_generation'') OR (contract.task_group=''form_assist'' AND recipe.variables_schema->''x-image-preparation''->>''contract''=''image_prompt_preparation_v1'' AND contract.budget_policy->>''assetId''=''new_design.image.prompt_preparation'' AND EXISTS(SELECT 1 FROM image_preparation_capability WHERE contract=''image_prompt_preparation_v1'' AND operational)))');
END $$;
CREATE TABLE image_prompt_preparations(
 id uuid PRIMARY KEY REFERENCES ai_tasks(id),request_key uuid NOT NULL UNIQUE,request_hash char(64) NOT NULL,
 scope_id uuid NOT NULL,input_payload jsonb NOT NULL,source_snapshot jsonb NOT NULL,frozen_plan jsonb NOT NULL,
 step_id uuid NOT NULL UNIQUE REFERENCES ai_task_steps(id),attempt_id uuid NOT NULL UNIQUE REFERENCES ai_task_attempts(id),
 status text NOT NULL DEFAULT 'running' CHECK(status IN ('running','succeeded','failed','ended_unknown')),
 reply jsonb,output jsonb,summary text NOT NULL DEFAULT '原优化结果待核对',created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX image_preparation_one_running ON image_prompt_preparations(scope_id) WHERE status='running';
CREATE FUNCTION guard_image_preparation() RETURNS trigger LANGUAGE plpgsql SET search_path TO new_design,public AS $$
DECLARE task ai_tasks%ROWTYPE; step ai_task_steps%ROWTYPE; attempt ai_task_attempts%ROWTYPE; contract task_contract_versions%ROWTYPE; recipe prompt_recipe_versions%ROWTYPE; manifest context_manifests%ROWTYPE; snapshot model_route_snapshots%ROWTYPE; source jsonb; item jsonb; actual jsonb; target_book books%ROWTYPE; profile jsonb; card_count integer;
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'image preparation immutable' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' THEN
  IF (to_jsonb(NEW)-ARRAY['status','reply','output','summary']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['status','reply','output','summary']) OR OLD.status<>'running' AND NEW IS DISTINCT FROM OLD OR OLD.reply IS NOT NULL AND NEW.reply IS DISTINCT FROM OLD.reply OR NEW.status='running' AND (NEW.output IS NOT NULL OR NEW.summary IS DISTINCT FROM OLD.summary) THEN RAISE EXCEPTION 'image preparation original input and reply immutable' USING ERRCODE='23514'; END IF;
 ELSE
  IF NOT EXISTS(SELECT 1 FROM image_preparation_capability capability WHERE capability.contract='image_prompt_preparation_v1' AND capability.operational) OR NEW.status<>'running' OR NEW.reply IS NOT NULL OR NEW.output IS NOT NULL THEN RAISE EXCEPTION 'image preparation not enabled' USING ERRCODE='23514'; END IF;
 END IF;
 SELECT * INTO STRICT task FROM ai_tasks WHERE id=NEW.id;
 SELECT * INTO STRICT step FROM ai_task_steps WHERE id=NEW.step_id AND task_id=NEW.id AND current_attempt_id=NEW.attempt_id;
 SELECT * INTO STRICT attempt FROM ai_task_attempts WHERE id=NEW.attempt_id AND task_id=NEW.id AND step_id=NEW.step_id;
 SELECT * INTO STRICT contract FROM task_contract_versions WHERE id=attempt.task_contract_version_id;
 SELECT * INTO STRICT recipe FROM prompt_recipe_versions WHERE id=attempt.prompt_recipe_version_id;
 SELECT * INTO STRICT manifest FROM context_manifests WHERE id=attempt.context_manifest_id;
 SELECT * INTO STRICT snapshot FROM model_route_snapshots WHERE id=attempt.model_route_snapshot_id;
 source:=NEW.source_snapshot;
 IF jsonb_typeof(source)<>'object' OR source-ARRAY['scope','hash','data']<>'{}'::jsonb OR NEW.input_payload-ARRAY['requestKey','scope','sourceHash','original']<>'{}'::jsonb OR source->>'hash' !~ '^[a-f0-9]{64}$' OR NEW.request_hash !~ '^[a-f0-9]{64}$' OR jsonb_typeof(NEW.input_payload->'original')<>'string' OR length(btrim(NEW.input_payload->>'original')) NOT BETWEEN 1 AND 1000000 OR NEW.frozen_plan->>'contractVersionId' IS DISTINCT FROM contract.id::text OR NEW.frozen_plan->>'recipeVersionId' IS DISTINCT FROM recipe.id::text OR NEW.frozen_plan->>'manifestId' IS DISTINCT FROM manifest.id::text OR NEW.frozen_plan->>'snapshotId' IS DISTINCT FROM snapshot.id::text THEN RAISE EXCEPTION 'image preparation input shape mismatch' USING ERRCODE='23514'; END IF;
 IF NOT COALESCE(task.source_kind='image_prompt_preparation' AND task.source_id=NEW.id AND task.request_idempotency_key=NEW.request_key::text AND task.request_hash=NEW.request_hash AND task.task_contract_version_id=contract.id AND step.step_key='image_prompt_preparation' AND step.max_attempts=1 AND attempt.attempt_number=1 AND attempt.input_hash=NEW.frozen_plan->>'inputHash' AND attempt.output_schema_version=NEW.frozen_plan->>'outputSchemaVersion' AND contract.task_group='form_assist' AND contract.status='published' AND contract.budget_policy->>'assetId'='new_design.image.prompt_preparation' AND contract.budget_policy->>'assetVersion'='v1' AND contract.retry_policy='{"maxAttempts":1,"automaticRetry":false}'::jsonb AND recipe.id=contract.prompt_recipe_version_id AND recipe.status='published' AND recipe.variables_schema->'const'=contract.input_schema->'const' AND contract.input_schema->'const'=NEW.frozen_plan->'promptInput' AND NEW.frozen_plan->'promptInput'->'source'=source AND NEW.frozen_plan->'promptInput'->>'original'=NEW.input_payload->>'original' AND source->'scope'=NEW.input_payload->'scope' AND source->>'hash'=NEW.input_payload->>'sourceHash' AND manifest.task_contract_version_id=contract.id AND manifest.prompt_recipe_version_id=recipe.id AND manifest.model_route_snapshot_id=snapshot.id AND manifest.source_set_hash=source->>'hash' AND snapshot.snapshot_hash=NEW.frozen_plan->>'snapshotHash' AND snapshot.provider=NEW.frozen_plan->'route'->'primary'->>'provider' AND snapshot.model=NEW.frozen_plan->'route'->'primary'->>'model' AND snapshot.retry_policy->>'maxRetries'='0' AND NEW.frozen_plan->'route'->'fallbacks'='[]'::jsonb,false) THEN RAISE EXCEPTION 'image preparation frozen contract mismatch' USING ERRCODE='23514'; END IF;
 IF TG_OP='INSERT' THEN
  IF task.status<>'running' OR step.status<>'running' OR attempt.status<>'running' OR NEW.input_payload->>'requestKey'<>NEW.request_key::text THEN RAISE EXCEPTION 'image preparation claim mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.input_payload->'scope'->>'kind'='book' THEN
   IF (NEW.input_payload->'scope')-ARRAY['kind','bookId']<>'{}'::jsonb OR (source->'data')-ARRAY['book','cards','plans']<>'{}'::jsonb THEN RAISE EXCEPTION 'image preparation book source shape mismatch' USING ERRCODE='23514'; END IF;
   SELECT * INTO STRICT target_book FROM books WHERE id=NEW.scope_id AND status='active';
   IF task.book_id IS DISTINCT FROM target_book.id OR manifest.book_id IS DISTINCT FROM target_book.id OR NEW.input_payload->'scope'->>'bookId'<>target_book.id::text OR source->'data'->'book' IS DISTINCT FROM jsonb_build_object('id',target_book.id,'name',target_book.name,'description',target_book.description,'revision',target_book.revision) THEN RAISE EXCEPTION 'image preparation book mismatch' USING ERRCODE='23514'; END IF;
   SELECT count(*) INTO card_count FROM cards WHERE space_id=target_book.space_id AND status='active';
   IF jsonb_array_length(source->'data'->'cards')<>card_count OR (SELECT count(DISTINCT value->>'id') FROM jsonb_array_elements(source->'data'->'cards'))<>card_count THEN RAISE EXCEPTION 'image preparation incomplete card set' USING ERRCODE='23514'; END IF;
   FOR item IN SELECT value FROM jsonb_array_elements(source->'data'->'cards') LOOP
    SELECT jsonb_build_object('id',card.id,'versionId',version.id,'title',version.title,'typeVersionId',version.type_version_id,'values',version.values,'fields',spec.fields,'localFields',COALESCE((SELECT jsonb_agg(jsonb_build_object('definitionId',definition.id,'versionId',local_spec.id,'field',local_spec.field_schema,'value',local.value) ORDER BY definition.field_key) FROM card_version_local_values local JOIN field_definitions definition ON definition.id=local.field_definition_id JOIN field_definition_versions local_spec ON local_spec.id=local.field_definition_version_id AND local_spec.field_definition_id=definition.id WHERE local.card_version_id=version.id),'[]'::jsonb)) INTO actual FROM cards card JOIN card_versions version ON version.id=card.current_version_id AND version.card_id=card.id JOIN card_type_versions spec ON spec.id=version.type_version_id WHERE card.id=(item->>'id')::uuid AND card.space_id=target_book.space_id AND card.status='active';
    IF actual IS DISTINCT FROM item THEN RAISE EXCEPTION 'image preparation actual card mismatch' USING ERRCODE='23514'; END IF;
   END LOOP;
   SELECT COALESCE(jsonb_agg(jsonb_build_object('id',object.id,'versionId',version.id,'level',object.level,'title',object.title,'content',version.content,'contentHash',version.content_hash) ORDER BY object.id),'[]'::jsonb) INTO actual FROM planning_objects object JOIN planning_versions version ON version.id=object.adopted_version_id AND version.object_id=object.id WHERE object.book_id=target_book.id AND object.status='active' AND object.level='story' AND version.status='adopted' AND version.stale_at IS NULL;
   IF actual IS DISTINCT FROM source->'data'->'plans' THEN RAISE EXCEPTION 'image preparation story source mismatch' USING ERRCODE='23514'; END IF;
  ELSIF NEW.input_payload->'scope'->>'kind'='public_character' THEN
   profile:=source->'data'->'profile';
   IF (NEW.input_payload->'scope')-ARRAY['kind','resourceId','resourceVersionId']<>'{}'::jsonb OR (source->'data')-ARRAY['profile']<>'{}'::jsonb OR profile-ARRAY['id','versionId','revision','typeVersionId','title','values','fields','localFields','hash']<>'{}'::jsonb OR profile->>'hash' !~ '^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'image preparation public source shape mismatch' USING ERRCODE='23514'; END IF;
   IF task.book_id IS NOT NULL OR manifest.book_id IS NOT NULL OR manifest.public_character_scope IS DISTINCT FROM NEW.scope_id OR NEW.input_payload->'scope'->>'resourceId'<>NEW.scope_id::text OR profile->>'id'<>NEW.scope_id::text OR profile->>'versionId'<>NEW.input_payload->'scope'->>'resourceVersionId' OR NOT EXISTS(SELECT 1 FROM cards card JOIN card_types type ON type.id=card.card_type_id JOIN card_versions version ON version.card_id=card.id JOIN card_type_versions spec ON spec.id=version.type_version_id WHERE card.id=NEW.scope_id AND card.space_id='60000000-0000-4000-8000-000000000001' AND card.status='active' AND type.type_key='character' AND type.status='published' AND version.id=(profile->>'versionId')::uuid AND version.title=profile->>'title' AND version.revision=(profile->>'revision')::integer AND version.type_version_id=(profile->>'typeVersionId')::uuid AND profile->'values'=version.values||COALESCE((SELECT jsonb_object_agg(definition.field_key,local.value) FROM card_version_local_values local JOIN field_definitions definition ON definition.id=local.field_definition_id WHERE local.card_version_id=version.id),'{}'::jsonb) AND profile->'fields'=spec.fields||COALESCE((SELECT jsonb_agg(field.field_schema ORDER BY definition.field_key) FROM card_version_local_values local JOIN field_definitions definition ON definition.id=local.field_definition_id JOIN field_definition_versions field ON field.id=local.field_definition_version_id AND field.field_definition_id=definition.id WHERE local.card_version_id=version.id),'[]'::jsonb) AND profile->'localFields'=COALESCE((SELECT jsonb_agg(jsonb_build_object('definitionId',definition.id,'versionId',field.id,'field',field.field_schema,'value',local.value) ORDER BY definition.field_key) FROM card_version_local_values local JOIN field_definitions definition ON definition.id=local.field_definition_id JOIN field_definition_versions field ON field.id=local.field_definition_version_id AND field.field_definition_id=definition.id WHERE local.card_version_id=version.id),'[]'::jsonb)) THEN RAISE EXCEPTION 'image preparation public source mismatch' USING ERRCODE='23514'; END IF;
  ELSE RAISE EXCEPTION 'image preparation unknown scope' USING ERRCODE='23514'; END IF;
 END IF;
 IF TG_OP='INSERT' THEN
  IF (SELECT count(*) FROM context_manifest_entries WHERE manifest_id=manifest.id)<>(CASE WHEN task.book_id IS NULL THEN 1 ELSE jsonb_array_length(source->'data'->'cards')+jsonb_array_length(source->'data'->'plans') END) OR EXISTS(
   SELECT 1 FROM context_manifest_entries entry WHERE entry.manifest_id=manifest.id AND NOT COALESCE(
    entry.transform_status='full' AND entry.content_role='required' AND entry.token_estimate>=0 AND (
     task.book_id IS NULL AND entry.source_type='card_version' AND entry.stable_object_id=NEW.scope_id AND entry.exact_version_id=(NEW.input_payload->'scope'->>'resourceVersionId')::uuid OR
     task.book_id IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(source->'data'->'cards') card WHERE entry.source_type='card_version' AND entry.stable_object_id=(card->>'id')::uuid AND entry.exact_version_id=(card->>'versionId')::uuid) OR
     task.book_id IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(source->'data'->'plans') plan WHERE entry.source_type='planning_version' AND entry.stable_object_id=(plan->>'id')::uuid AND entry.exact_version_id=(plan->>'versionId')::uuid)
    ),false)) OR (SELECT count(DISTINCT (source_type,stable_object_id,exact_version_id)) FROM context_manifest_entries WHERE manifest_id=manifest.id)<>(SELECT count(*) FROM context_manifest_entries WHERE manifest_id=manifest.id) THEN
   RAISE EXCEPTION 'image preparation manifest sources mismatch' USING ERRCODE='23514';
  END IF;
 END IF;
 IF NEW.reply IS NOT NULL AND NOT COALESCE(NEW.reply->'output'->>'sourceHash'=source->>'hash' AND jsonb_typeof(NEW.reply->'output'->'chinese')='string' AND length(btrim(NEW.reply->'output'->>'chinese')) BETWEEN 1 AND 4000 AND jsonb_typeof(NEW.reply->'output'->'english')='string' AND length(btrim(NEW.reply->'output'->>'english')) BETWEEN 1 AND 4000 AND NEW.reply->'execution'->>'routeSnapshotId'=snapshot.id::text AND NEW.reply->'execution'->>'routeSnapshotHash'=snapshot.snapshot_hash AND NEW.reply->'execution'->>'provider'=snapshot.provider AND NEW.reply->'execution'->>'model'=snapshot.model AND EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.reply->'execution'->'attempts') trace WHERE trace->>'status'='succeeded' AND trace->>'requestSent'='true' AND trace->>'responseReceived'='true'),false) THEN RAISE EXCEPTION 'image preparation actual reply mismatch' USING ERRCODE='23514'; END IF;
 IF NEW.reply IS NOT NULL AND (NEW.reply-ARRAY['output','execution']<>'{}'::jsonb OR (NEW.reply->'output')-ARRAY['sourceHash','chinese','english','missingInformation']<>'{}'::jsonb OR jsonb_typeof(NEW.reply->'output'->'missingInformation')<>'array' OR jsonb_array_length(NEW.reply->'output'->'missingInformation')>20 OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.reply->'output'->'missingInformation') value WHERE jsonb_typeof(value)<>'string' OR length(value#>>'{}')>500)) THEN RAISE EXCEPTION 'image preparation reply shape mismatch' USING ERRCODE='23514'; END IF;
 IF NEW.status='failed' AND (task.status<>'failed' OR step.status<>'failed' OR attempt.status<>'failed') OR NEW.status='ended_unknown' AND (NEW.reply IS NOT NULL OR task.status<>'cancelled' OR step.status<>'cancelled' OR attempt.status<>'discarded') THEN RAISE EXCEPTION 'image preparation terminal ledger mismatch' USING ERRCODE='23514'; END IF;
 IF NEW.status='succeeded' AND (NEW.reply IS NULL OR NEW.output IS DISTINCT FROM NEW.reply->'output' OR task.status<>'succeeded' OR step.status<>'succeeded' OR attempt.status<>'succeeded') OR NEW.status IN ('failed','ended_unknown') AND NEW.output IS NOT NULL THEN RAISE EXCEPTION 'image preparation terminal mismatch' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER image_preparation_guard BEFORE INSERT OR UPDATE OR DELETE ON image_prompt_preparations FOR EACH ROW EXECUTE FUNCTION guard_image_preparation();
