-- Drama scripts and quality reports. Manual after 119.
SET search_path TO new_design, public;
CREATE TABLE drama_script_entities(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES drama_projects(id),episode_entity_id uuid NOT NULL REFERENCES drama_stage_entities(id),revision integer NOT NULL DEFAULT 0,adopted_version_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,episode_entity_id),UNIQUE(project_id,id));
CREATE TABLE drama_script_versions(id uuid PRIMARY KEY,project_id uuid NOT NULL,entity_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),episode_version_id uuid NOT NULL REFERENCES drama_stage_versions(id),content jsonb NOT NULL CHECK(jsonb_typeof(content)='object'),source_kind text NOT NULL CHECK(source_kind IN('manual','ai_candidate','repair_candidate')),request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(entity_id,version),UNIQUE(entity_id,id),FOREIGN KEY(project_id,entity_id) REFERENCES drama_script_entities(project_id,id));
ALTER TABLE drama_script_entities ADD CONSTRAINT drama_script_adopted_fk FOREIGN KEY(id,adopted_version_id) REFERENCES drama_script_versions(entity_id,id);
CREATE TABLE drama_script_adoptions(id uuid PRIMARY KEY,project_id uuid NOT NULL,entity_id uuid NOT NULL,version_id uuid NOT NULL,revision integer NOT NULL,request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(entity_id,revision),FOREIGN KEY(entity_id,version_id) REFERENCES drama_script_versions(entity_id,id));
CREATE TABLE drama_quality_reports(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES drama_projects(id),script_version_id uuid NOT NULL REFERENCES drama_script_versions(id),rule_version text NOT NULL,issues jsonb NOT NULL CHECK(jsonb_typeof(issues)='array'),passed boolean NOT NULL,request_key uuid NOT NULL UNIQUE,source_hash char(64) NOT NULL CHECK(source_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now());
CREATE TRIGGER drama_script_versions_immutable BEFORE UPDATE OR DELETE ON drama_script_versions FOR EACH ROW EXECUTE FUNCTION guard_drama_history();
CREATE TRIGGER drama_script_adoptions_immutable BEFORE UPDATE OR DELETE ON drama_script_adoptions FOR EACH ROW EXECUTE FUNCTION guard_drama_history();
CREATE TRIGGER drama_quality_reports_immutable BEFORE UPDATE OR DELETE ON drama_quality_reports FOR EACH ROW EXECUTE FUNCTION guard_drama_history();
