-- Drama storyboards, prompts and explicit media task ledger. Manual after 120.
SET search_path TO new_design, public;
CREATE TABLE drama_storyboard_entities(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES drama_projects(id),script_entity_id uuid NOT NULL REFERENCES drama_script_entities(id),revision integer NOT NULL DEFAULT 0,adopted_version_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,script_entity_id),UNIQUE(project_id,id));
CREATE TABLE drama_storyboard_versions(id uuid PRIMARY KEY,project_id uuid NOT NULL,entity_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),script_version_id uuid NOT NULL REFERENCES drama_script_versions(id),content jsonb NOT NULL CHECK(jsonb_typeof(content)='object'),source_kind text NOT NULL CHECK(source_kind IN('manual','ai_candidate')),request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(entity_id,version),UNIQUE(entity_id,id),FOREIGN KEY(project_id,entity_id) REFERENCES drama_storyboard_entities(project_id,id));
ALTER TABLE drama_storyboard_entities ADD CONSTRAINT drama_storyboard_adopted_fk FOREIGN KEY(id,adopted_version_id) REFERENCES drama_storyboard_versions(entity_id,id);
CREATE TABLE drama_storyboard_adoptions(id uuid PRIMARY KEY,project_id uuid NOT NULL,entity_id uuid NOT NULL,version_id uuid NOT NULL,revision integer NOT NULL,request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(entity_id,revision),FOREIGN KEY(entity_id,version_id) REFERENCES drama_storyboard_versions(entity_id,id));
CREATE TABLE drama_media_prompt_versions(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES drama_projects(id),storyboard_version_id uuid NOT NULL REFERENCES drama_storyboard_versions(id),shot_key text NOT NULL,media_kind text NOT NULL CHECK(media_kind IN('character_design','keyframe','dialogue_audio','video_prompt')),version integer NOT NULL CHECK(version>0),content jsonb NOT NULL CHECK(jsonb_typeof(content)='object'),request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(storyboard_version_id,shot_key,media_kind,version));
CREATE TABLE drama_media_tasks(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES drama_projects(id),prompt_version_id uuid NOT NULL REFERENCES drama_media_prompt_versions(id),provider_key text,status text NOT NULL CHECK(status IN('unavailable','queued','running','succeeded','failed','result_unknown')),stop_position integer,last_error text NOT NULL DEFAULT '',request_key uuid NOT NULL UNIQUE,input_hash char(64) NOT NULL CHECK(input_hash ~ '^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TRIGGER drama_storyboard_versions_immutable BEFORE UPDATE OR DELETE ON drama_storyboard_versions FOR EACH ROW EXECUTE FUNCTION guard_drama_history();CREATE TRIGGER drama_storyboard_adoptions_immutable BEFORE UPDATE OR DELETE ON drama_storyboard_adoptions FOR EACH ROW EXECUTE FUNCTION guard_drama_history();CREATE TRIGGER drama_media_prompt_versions_immutable BEFORE UPDATE OR DELETE ON drama_media_prompt_versions FOR EACH ROW EXECUTE FUNCTION guard_drama_history();
