import {useEffect,useState} from 'react';
import type {BookSummary,CardTypeSummary,FieldDefinition,RelationTypeSummary} from '../../common/contracts';
import {WORLD_SECTIONS,WORLD_SECTION_LABELS,type PublishedWorldPackage,type WorldInstallInput,type WorldInstallPreview} from '../../common/worldPackages';
import {WORLD_PROFESSIONAL_TYPE_KEYS} from '../../common/worldCharacterMaintenance';
import {fieldDisplay} from '../../common/formPresentation';
import {newDesignApi} from '../api';
import DynamicForm from '../DynamicForm';
import type {WorldCommand} from './command';
import {worldImportDraftSchema} from './draft';
import RelationProperties from './RelationProperties';

export default function WorldImport({book,rootCardId,packages,locked,restore,initialPackageId,invalidLink=false,onState,onConfirm}:{book:BookSummary;rootCardId:string;packages:PublishedWorldPackage[];locked:boolean;restore?:WorldInstallInput;initialPackageId?:string;invalidLink?:boolean;onState:(dirty:boolean,discard:()=>boolean)=>void;onConfirm:(command:WorldCommand)=>Promise<boolean>}){
 const [sourceId,setSourceId]=useState(initialPackageId??''),[input,setInput]=useState<WorldInstallInput|null>(null),[types,setTypes]=useState<CardTypeSummary[]>([]),[relationTypes,setRelationTypes]=useState<RelationTypeSummary[]>([]),[fields,setFields]=useState<Record<string,FieldDefinition[]>>({}),[preview,setPreview]=useState<WorldInstallPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [draftBlocked,setDraftBlocked]=useState(false),[catalogReady,setCatalogReady]=useState(false);
 const disabled=locked||busy||draftBlocked||!catalogReady||types.length===0;
 const source=packages.find(item=>item.id===sourceId),draftKey=`new-design:world-import-draft:${book.id}:${rootCardId}`;
 useEffect(()=>{let active=true;setCatalogReady(false);void Promise.all([newDesignApi.listCardTypes(book.spaceId),newDesignApi.listRelationTypes(book.spaceId),newDesignApi.listRelationTypes()]).then(([cards,relations,global])=>{if(active){setTypes(cards.filter(type=>type.status==='published'&&(WORLD_PROFESSIONAL_TYPE_KEYS as readonly string[]).includes(type.key)));setRelationTypes([...relations,...global].filter(type=>type.status==='published'));setCatalogReady(true);}}).catch(reason=>{if(active)setError(String(reason));});setDraftBlocked(false);try{const saved=localStorage.getItem(draftKey);if(saved){const parsed=worldImportDraftSchema.parse(JSON.parse(saved));setInput(parsed);setSourceId(parsed.packageId);}}catch{setDraftBlocked(true);setError('导入填写无法读取，请保留浏览器记录。');}return()=>{active=false;};},[book.id,book.spaceId,draftKey]);
 useEffect(()=>{if(restore){setInput(restore);setSourceId(restore.packageId);setPreview(null);}},[restore]);
 useEffect(()=>()=>onState(false,()=>true),[onState]);
 function discardDraft(){if(locked||busy)return false;try{localStorage.removeItem(draftKey);if(localStorage.getItem(draftKey)!==null)throw new Error();setDraftBlocked(false);setInput(null);setSourceId('');setPreview(null);setError('');return true;}catch{setDraftBlocked(true);setError('未能清理本地导入填写，原记录保留，请检查浏览器存储。');return false;}}
 useEffect(()=>{onState(!!input||draftBlocked,discardDraft);},[input,locked,busy,draftBlocked,onState,draftKey]);
 useEffect(()=>{let active=true;const missing=[...new Set(input?.cards.map(item=>item.targetTypeId)??[])].filter(id=>id&&!fields[id]);void Promise.all(missing.map(async id=>{const result=await newDesignApi.worldPackages.installFields(book.id,id);if(result.bookId!==book.id||result.typeId!==id)throw new Error('导入字段来源不同，请核对。');return result;})).then(items=>{if(active&&items.length)setFields(previous=>({...previous,...Object.fromEntries(items.map(item=>[item.typeId,item.fields]))}));}).catch(reason=>{if(active)setError(String(reason));});return()=>{active=false;};},[input,book.id,fields]);
 function update(next:WorldInstallInput){if(disabled)return false;try{const raw=JSON.stringify(next);localStorage.setItem(draftKey,raw);if(localStorage.getItem(draftKey)!==raw)throw new Error();setInput(next);setSourceId(next.packageId);setPreview(null);setError('');return true;}catch{setDraftBlocked(true);setError('无法保留导入填写，请恢复浏览器存储。');return false;}}
 function choose(id:string){if(disabled)return;const pkg=packages.find(item=>item.id===id);if(!pkg){setError('请先选择要导入的固定世界版本，当前填写保留。');return;}update({requestKey:crypto.randomUUID(),packageId:id,syncEnabled:true,cards:pkg.frame.cards.map(card=>({sourceCardId:card.cardId,requestKey:crypto.randomUUID(),targetTypeId:types.find(type=>type.key===card.typeKey)?.id??'',title:card.title,mapping:Object.entries({...card.values,...card.localValues}).map(([key,value])=>({sourceKey:key,targetKey:key,value})),additionalValues:{}})),relations:pkg.frame.relations.map(relation=>({sourceRelationId:relation.relationId,targetTypeId:relationTypes.find(type=>type.key===relation.type.relation_key)?.id??'',properties:relation.properties}))});}
 async function review(){if(!input||disabled)return;setBusy(true);try{setPreview(await newDesignApi.worldPackages.installPreview(book.id,input));setError('');}catch(reason){setError(reason instanceof Error?reason.message:'导入预览未读取。');}finally{setBusy(false);}}
 return <section className="nd-world-source"><h3>来源与世界库</h3><p>选择固定世界版本，核对本书字段后导入独立副本。</p><label>世界库版本 <select disabled={disabled} value={sourceId} onChange={event=>choose(event.target.value)}><option value="">请选择世界库版本</option>{packages.map(pkg=><option key={pkg.id} value={pkg.id}>{pkg.frame.cards.find(card=>card.cardId===pkg.rootCardId)?.title} · 第 {pkg.version} 版</option>)}</select></label>{!catalogReady&&<p role="status">正在读取本书类型与关系规格…</p>}{catalogReady&&!types.length&&<p role="alert">本书没有可用的世界资料类型，请先在内容类型中发布对应规格。</p>}{!packages.length&&<p>世界库尚无已发布的固定版本。</p>}{invalidLink&&<p role="alert">样本版本地址无效；请选择目录中的固定版本，原填写保留。</p>}{initialPackageId&&packages.length>0&&!packages.some(item=>item.id===initialPackageId)&&<p role="alert">指定的世界样本版本不存在；原填写保留，请从目录重新选择。</p>}{initialPackageId&&input&&input.packageId!==initialPackageId&&<p role="alert">本书已有另一份未保存的导入填写，已保留原选择；如需改用链接中的样本，请先处理或明确放弃原填写。</p>}{source&&!input&&<button type="button" className="nd-button" disabled={disabled} onClick={()=>choose(source.id)}>准备导入此版本</button>}
 {source&&input&&<><div className="nd-world-sections">{WORLD_SECTIONS.map(section=><span key={section}>{WORLD_SECTION_LABELS[section]} {section==='relations'?source.frame.relations.length:source.frame.cards.filter(card=>card.section===section).length}</span>)}</div>{input.cards.map(item=>{const card=source.frame.cards.find(card=>card.cardId===item.sourceCardId);if(!card)return null;const actualFields=fields[item.targetTypeId]??[],setCard=(next:typeof item)=>update({...input,cards:input.cards.map(old=>old.sourceCardId===item.sourceCardId?next:old)});return <details key={item.sourceCardId}><summary>{WORLD_SECTION_LABELS[card.section]} · {card.title}</summary><label>本书类型 <select disabled={disabled} value={item.targetTypeId} onChange={event=>setCard({...item,targetTypeId:event.target.value})}><option value="">请选择本书类型</option>{types.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label>本书名称 <input disabled={disabled} value={item.title} onChange={event=>setCard({...item,title:event.target.value})}/></label>{item.mapping.map(map=><div className="nd-world-mapping" key={map.sourceKey}><span>{[...card.fields,...card.localFields.map(field=>field.field)].find(field=>field.key===map.sourceKey)?.name??map.sourceKey}：{JSON.stringify({...card.values,...card.localValues}[map.sourceKey])}</span><label>映射到 <select disabled={disabled} value={map.targetKey} onChange={event=>setCard({...item,mapping:item.mapping.map(old=>old.sourceKey===map.sourceKey?{...old,targetKey:event.target.value}:old)})}><option value="">请选择本书字段</option>{actualFields.filter(field=>!field.hidden).map(field=><option key={field.key} value={field.key}>{field.name}</option>)}</select></label></div>)}<DynamicForm fields={actualFields.map(field=>field.optionSource?.kind==='dictionary_tree'?{...field,optionSource:{...field.optionSource,rule:{...field.optionSource.rule,allowInlineCreate:false}}}:field)} values={{...item.additionalValues,...Object.fromEntries(item.mapping.map(map=>[map.targetKey,map.value]))}} disabled={disabled} compactHelp onChange={values=>setCard({...item,mapping:item.mapping.map(map=>({...map,value:Object.hasOwn(values,map.targetKey)?values[map.targetKey]:null})),additionalValues:Object.fromEntries(Object.entries(values).filter(([key])=>!item.mapping.some(map=>map.targetKey===key)))})}/></details>;})}
 {input.relations.map(item=>{const relation=source.frame.relations.find(source=>source.relationId===item.sourceRelationId)!;return <details key={item.sourceRelationId}><summary>关系网络 · {String(relation.type.name)}</summary><label>本书关系类型 <select disabled={disabled} value={item.targetTypeId} onChange={event=>update({...input,relations:input.relations.map(old=>old.sourceRelationId===item.sourceRelationId?{...old,targetTypeId:event.target.value}:old)})}><option value="">请选择关系类型</option>{relationTypes.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></label><RelationProperties type={relationTypes.find(type=>type.id===item.targetTypeId)} values={item.properties} disabled={disabled} onChange={properties=>update({...input,relations:input.relations.map(old=>old.sourceRelationId===item.sourceRelationId?{...old,properties}:old)})}/></details>;})}
 <label><input type="checkbox" disabled={disabled} checked={input.syncEnabled} onChange={event=>update({...input,syncEnabled:event.target.checked})}/> 保留手动同步来源</label><button className="nd-button" disabled={disabled} onClick={()=>void review()}>{busy?'正在核对…':'预览完整导入'}</button></>}
 {preview&&<section className="nd-world-confirm"><h4>确认导入 {preview.targets.length} 份独立资料与 {preview.relationTargets.length} 条关系</h4><p>同名的本书资料保留；事实、状态、认知和正文保留。</p>{preview.targets.map(target=><details key={target.sourceCardId}><summary>{input?.cards.find(card=>card.sourceCardId===target.sourceCardId)?.title}</summary><dl>{target.fields.filter(field=>!field.hidden).map(field=><div key={field.key}><dt>{field.name}</dt><dd>{fieldDisplay(field,target.values[field.key])}</dd></div>)}</dl></details>)}<button className="nd-button nd-button-primary" disabled={disabled} onClick={()=>void onConfirm({kind:'install',bookId:book.id,input:{input:preview.input,previewHash:preview.previewHash}}).then(ok=>{if(ok)discardDraft();})}>确认导入本书</button></section>}{draftBlocked&&<p role="alert">本地导入填写未能完整保留；恢复浏览器存储后再操作，或明确放弃这份未保存填写。<button className="nd-button" disabled={locked||busy} onClick={()=>discardDraft()}>放弃未保存的导入填写</button></p>}{error&&<p role="alert">{error}</p>}</section>;
}


