import {AsyncLocalStorage} from 'node:async_hooks';
import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {creativeHubBindingSchema,creativeHubDiagnosticSchema,creativeHubStateSchema,creativeHubThreadCreateSchema,creativeHubThreadUpdateSchema,creativeHubTurnRequestSchema,type CreativeHubCapability,type CreativeHubSourceLink,type CreativeHubState,type CreativeHubThread,type CreativeHubTurn} from '../../../common/creativeHub';
import {getShelfBookDetail} from '../bookshelf';
import {getAuthorTask} from '../authorTasks';
import {stableHash} from '../aiContracts';
import {getNewDesignPool} from '../runtime';
import {assertFound,NewDesignError} from '../../domain/errors';
import {DEFAULT_SPACE_ID} from '../store';
import {appendWorkflowVersion,createWorkflowCard,recordWorkflowAction,requireCardWorkflowTypes,workflowActionByRequest,workflowCard} from '../cardWorkflow';

const TYPE_KEY='creative_hub_thread';
const TURN_ACTIONS=['creative_hub.turn.started','creative_hub.turn.succeeded','creative_hub.turn.failed','creative_hub.turn.result_unknown','creative_hub.turn.resumed'] as const;
const pools=new AsyncLocalStorage<Pool>();
export const withCreativeHubPool=<T>(pool:Pool,work:()=>Promise<T>)=>pools.run(pool,work);
export const getCreativeHubPool=async()=>pools.getStore()??getNewDesignPool();
type Db=Pick<PoolClient,'query'>;
type Row=Record<string,any>;

export async function getCreativeHubCapability():Promise<CreativeHubCapability>{
  const pool=await getCreativeHubPool();
  try{
    await requireCardWorkflowTypes(pool,[TYPE_KEY],true);
    const row=(await pool.query("SELECT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('new_design.model_route_snapshots') AND conname='model_route_snapshots_managed_scope_check' AND pg_get_constraintdef(oid) LIKE '%creative_hub%') model_scope")).rows[0]??{};
    const operational=Boolean(row.model_scope);
    return{installed:true,operational,reason:operational?'创作中枢会话与不可变诊断动作账本可用。':'创作中枢模型任务范围未完整启用，写入已停用。'};
  }catch{return{installed:false,operational:false,reason:'创作中枢卡片收敛迁移 126 尚未启用。'};}
}
async function requireCreativeHubCapability(write=false){const capability=await getCreativeHubCapability();if(!capability.installed||write&&!capability.operational)throw new NewDesignError(capability.reason,503);}

function asIso(value:unknown):string{return value instanceof Date?value.toISOString():new Date(String(value)).toISOString();}
function thread(row:Row):CreativeHubThread{const values=row.current_values??row.values??{};return{id:String(row.id),title:String(row.title),binding:creativeHubBindingSchema.parse(values.binding??{}),status:row.status as CreativeHubThread['status'],revision:Number(values.thread_revision??row.revision),createdAt:asIso(row.created_at),updatedAt:asIso(row.updated_at)};}
function turnFromAction(row:Row):CreativeHubTurn{const value=row.payload??{};return{id:String(value.turn_id),threadId:String(row.card_id),requestKey:String(value.request_key??row.request_key),requestHash:String(value.request_hash??row.input_hash),question:String(value.question),frozenState:creativeHubStateSchema.parse(value.frozen_state),status:value.status as CreativeHubTurn['status'],result:value.result?creativeHubDiagnosticSchema.parse(value.result):null,failure:value.failure===null||value.failure===undefined?null:String(value.failure),promptSnapshot:value.prompt_snapshot??null,modelSnapshot:value.model_snapshot??null,usedTokens:value.used_tokens===null||value.used_tokens===undefined?null:Number(value.used_tokens),createdAt:asIso(value.turn_created_at??row.created_at),updatedAt:asIso(row.created_at),completedAt:value.completed_at?asIso(value.completed_at):null};}
async function readThread(db:Db,id:string,lock=false):Promise<CreativeHubThread>{return thread(await workflowCard(db,id,TYPE_KEY,lock,true));}
const latestTurnSql=`SELECT DISTINCT ON(action.payload->>'turn_id') action.*
  FROM new_design.card_version_actions action
  JOIN new_design.cards card ON card.id=action.card_id
  JOIN new_design.card_types type ON type.id=card.card_type_id
  WHERE type.type_key=$1 AND action.action_key=ANY($2::text[])`;
async function readTurn(db:Db,id:string):Promise<CreativeHubTurn>{
  const row=assertFound((await db.query(`${latestTurnSql} AND action.payload->>'turn_id'=$3
    ORDER BY action.payload->>'turn_id',action.created_at DESC,action.id DESC`,[TYPE_KEY,TURN_ACTIONS,id])).rows[0],'创作中枢原诊断不存在。');
  return turnFromAction(row);
}
async function appendThreadState(db:Db,current:CreativeHubThread,input:{title:string;binding:CreativeHubThread['binding'];status:CreativeHubThread['status'];source:'edit'|'archive'|'restore'}):Promise<CreativeHubThread>{
  const values={record_kind:TYPE_KEY,binding:input.binding,thread_revision:current.revision+1};
  await appendWorkflowVersion(db,{cardId:current.id,typeKey:TYPE_KEY,title:input.title,values,source:input.source});
  await db.query("UPDATE new_design.cards SET title=$2,status=$3,archived_at=CASE WHEN $3='archived' THEN now() ELSE NULL END WHERE id=$1",[current.id,input.title,input.status]);
  return readThread(db,current.id);
}

export async function listCreativeHubThreads(input:{includeArchived?:boolean}={}):Promise<CreativeHubThread[]>{await requireCreativeHubCapability();const rows=await(await getCreativeHubPool()).query(`SELECT card.*,version.values current_values FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id AND type.type_key=$1 JOIN new_design.card_versions version ON version.id=card.current_version_id AND version.card_id=card.id WHERE ($2::boolean OR card.status='active') ORDER BY card.updated_at DESC,card.id DESC`,[TYPE_KEY,input.includeArchived===true]);return rows.rows.map(thread);}
export async function getCreativeHubThread(id:string):Promise<CreativeHubThread>{await requireCreativeHubCapability();return readThread(await getCreativeHubPool(),id);}
export async function createCreativeHubThread(raw:unknown):Promise<CreativeHubThread>{const input=creativeHubThreadCreateSchema.parse(raw);await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');const id=randomUUID();await createWorkflowCard(db,{id,spaceId:DEFAULT_SPACE_ID,typeKey:TYPE_KEY,title:input.title,values:{record_kind:TYPE_KEY,binding:input.binding,thread_revision:1}});await db.query('COMMIT');return readThread(db,id);}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function updateCreativeHubThread(id:string,raw:unknown):Promise<CreativeHubThread>{const input=creativeHubThreadUpdateSchema.parse(raw);await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');const current=await readThread(db,id,true);if(current.status!=='active')throw new NewDesignError('已归档会话不能再修改。',409);if(current.revision!==input.expectedRevision)throw new NewDesignError('会话已经变化，请读取最新状态后再修改。',409);const updated=await appendThreadState(db,current,{title:input.title??current.title,binding:input.binding??current.binding,status:'active',source:'edit'});await db.query('COMMIT');return updated;}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function archiveCreativeHubThread(id:string,expectedRevision:number):Promise<CreativeHubThread>{await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');const current=await readThread(db,id,true);if(current.status==='archived'){await db.query('COMMIT');return current;}if(current.revision!==expectedRevision)throw new NewDesignError('会话已经变化，请读取最新状态后再归档。',409);const updated=await appendThreadState(db,current,{title:current.title,binding:current.binding,status:'archived',source:'archive'});await db.query('COMMIT');return updated;}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function restoreCreativeHubThread(id:string,expectedRevision:number):Promise<CreativeHubThread>{await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');const current=await readThread(db,id,true);if(current.status==='active'){await db.query('COMMIT');return current;}if(current.revision!==expectedRevision)throw new NewDesignError('会话已经变化，请读取最新状态后再恢复。',409);const updated=await appendThreadState(db,current,{title:current.title,binding:current.binding,status:'active',source:'restore'});await db.query('COMMIT');return updated;}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}

export async function readCreativeHubState(id:string):Promise<CreativeHubState>{
  const current=await getCreativeHubThread(id),binding=current.binding;
  if(!binding.bookId)return{book:null,tasks:[],blockers:['当前会话未绑定作品，只能回答全局入口与使用方式。'],sourceLinks:[{label:'返回项目导航',href:'/new-design',kind:'workspace'}]};
  const pool=await getCreativeHubPool(),book=assertFound((await pool.query("SELECT id,name,revision FROM new_design.books WHERE id=$1 AND status='active'",[binding.bookId])).rows[0],'绑定作品不存在或已归档。'),detail=await getShelfBookDetail(binding.bookId,pool);
  const selected=binding.taskKind&&binding.taskId?[await getAuthorTask(binding.taskKind,binding.taskId)]:detail.records.items;
  const blockers=selected.filter(item=>!['completed','ended'].includes(item.status)).map(item=>`${item.title}：${item.statusLabel}`);
  if(binding.taskId&&!selected.length)blockers.unshift('绑定的原任务不在当前正式运行记录中，请回来源页核对。');
  const links:CreativeHubSourceLink[]=[{label:`打开《${book.name}》`,href:`/new-design/books/${book.id}`,kind:'book'}];
  if(binding.chapterDocumentId){const chapter=assertFound((await pool.query("SELECT id,title FROM new_design.chapter_documents WHERE id=$1 AND book_id=$2 AND status='active'",[binding.chapterDocumentId,book.id])).rows[0],'绑定章节不存在、已归档或不属于当前作品。');links.push({label:`打开${chapter.title}`,href:`/new-design/books/${book.id}/views/chapters?selected=${binding.chapterDocumentId}`,kind:'chapter'});}
  for(const item of selected.slice(0,8))if(!links.some(link=>link.href===item.source.route))links.push({label:item.source.label,href:item.source.route,kind:'task'});
  return creativeHubStateSchema.parse({book:{id:book.id,name:book.name,revision:Number(book.revision)},tasks:selected,blockers,sourceLinks:links});
}

export async function listCreativeHubTurns(threadId:string):Promise<CreativeHubTurn[]>{await getCreativeHubThread(threadId);const rows=await(await getCreativeHubPool()).query(`${latestTurnSql} AND action.card_id=$3 ORDER BY action.payload->>'turn_id',action.created_at DESC,action.id DESC`,[TYPE_KEY,TURN_ACTIONS,threadId]);return rows.rows.map(turnFromAction).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));}
export async function getCreativeHubTurn(id:string):Promise<CreativeHubTurn>{await requireCreativeHubCapability();return readTurn(await getCreativeHubPool(),id);}
export async function startCreativeHubTurn(threadId:string,raw:unknown,frozenRaw:unknown):Promise<{turn:CreativeHubTurn;repeated:boolean}>{
  const input=creativeHubTurnRequestSchema.parse(raw),frozen=creativeHubStateSchema.parse(frozenRaw),requestHash=stableHash({threadId,input});await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();
  try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`creative_hub:${threadId}:${input.requestKey}`]);const prior=await workflowActionByRequest(db,input.requestKey);if(prior){if(prior.action_key!=='creative_hub.turn.started'||prior.input_hash!==requestHash||String(prior.card_id)!==threadId)throw new NewDesignError('原诊断凭证已用于不同问题，请保留原凭证并新建请求。',409);const existing=await readTurn(db,String(prior.payload.turn_id));await db.query('COMMIT');return{turn:existing,repeated:true};}const current=await readThread(db,threadId,true);if(current.status!=='active')throw new NewDesignError('已归档会话不能发起新诊断。',409);if(current.revision!==input.expectedThreadRevision)throw new NewDesignError('会话绑定已经变化，请读取最新状态后再诊断。',409);const id=randomUUID(),now=new Date().toISOString();const action=await recordWorkflowAction(db,{cardId:threadId,actionKey:'creative_hub.turn.started',requestKey:input.requestKey,inputHash:requestHash,payload:{turn_id:id,request_key:input.requestKey,request_hash:requestHash,question:input.question,frozen_state:frozen,status:'running',result:null,failure:null,prompt_snapshot:null,model_snapshot:null,used_tokens:null,turn_created_at:now,completed_at:null}});await db.query('UPDATE new_design.cards SET updated_at=now() WHERE id=$1',[threadId]);await db.query('COMMIT');return{turn:turnFromAction(action),repeated:false};}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}
}
export async function completeCreativeHubTurn(id:string,resultRaw:unknown,promptSnapshot:Record<string,unknown>,modelSnapshot:Record<string,unknown>,usedTokens:number):Promise<CreativeHubTurn>{const result=creativeHubDiagnosticSchema.parse(resultRaw);await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`creative_hub:turn:${id}`]);const current=await readTurn(db,id);if(current.status==='succeeded'){if(stableHash(current.result)!==stableHash(result))throw new NewDesignError('原诊断已有不同完成结果，请读取原结果。',409);await db.query('COMMIT');return current;}if(current.status!=='running')throw new NewDesignError('原诊断不在可完成状态，请读取原回执。',409);const action=await recordWorkflowAction(db,{cardId:current.threadId,actionKey:'creative_hub.turn.succeeded',payload:{turn_id:id,request_key:current.requestKey,request_hash:current.requestHash,question:current.question,frozen_state:current.frozenState,status:'succeeded',result,failure:null,prompt_snapshot:promptSnapshot,model_snapshot:modelSnapshot,used_tokens:usedTokens,turn_created_at:current.createdAt,completed_at:new Date().toISOString()}});await db.query('COMMIT');return turnFromAction(action);}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function failCreativeHubTurn(id:string,message:string,unknown=false):Promise<CreativeHubTurn>{await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`creative_hub:turn:${id}`]);const current=await readTurn(db,id);if(current.status!=='running'){await db.query('COMMIT');return current;}const status=unknown?'result_unknown':'failed',action=await recordWorkflowAction(db,{cardId:current.threadId,actionKey:`creative_hub.turn.${status}`,payload:{turn_id:id,request_key:current.requestKey,request_hash:current.requestHash,question:current.question,frozen_state:current.frozenState,status,result:null,failure:message,prompt_snapshot:current.promptSnapshot,model_snapshot:current.modelSnapshot,used_tokens:current.usedTokens,turn_created_at:current.createdAt,completed_at:new Date().toISOString()}});await db.query('COMMIT');return turnFromAction(action);}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
export async function resumeCreativeHubTurn(id:string):Promise<CreativeHubTurn>{await requireCreativeHubCapability(true);const pool=await getCreativeHubPool(),db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`creative_hub:turn:${id}`]);const current=await readTurn(db,id);if(current.status!=='failed')throw new NewDesignError('只有已确认失败且未产生未知结果的原诊断可以重试。',409);const action=await recordWorkflowAction(db,{cardId:current.threadId,actionKey:'creative_hub.turn.resumed',payload:{turn_id:id,request_key:current.requestKey,request_hash:current.requestHash,question:current.question,frozen_state:current.frozenState,status:'running',result:null,failure:null,prompt_snapshot:current.promptSnapshot,model_snapshot:current.modelSnapshot,used_tokens:current.usedTokens,turn_created_at:current.createdAt,completed_at:null}});await db.query('COMMIT');return turnFromAction(action);}catch(error){await db.query('ROLLBACK').catch(()=>undefined);throw error;}finally{db.release();}}
