import {useCallback,useEffect,useRef,useState} from 'react';
import type {ExperienceWorkspace,ExperienceRequest,ExperienceRecord,ExperienceDraft} from '../../../common/characterExperiences';
import {experienceRequestSchema,validExperienceRecord} from '../../../common/characterExperiences/schema';
import type {PlanningObject} from '../../../common/contracts';
import type {WorkspaceEditor} from '../useGuard';
import {newDesignApi} from '../../api';
import {useReferenceCommand} from '../../referenceParity/useCommand';
import AuthorTimelineEditor from '../../bookComposition/AuthorTimelineEditor';
import Help from '../Help';
import {useExperienceSeries} from './experienceSeries';
import RecentBodyExperiences from '../../characterExperiences/recentBodies';
import type {RecentBodyExperienceDraft} from '../../../common/characterExperiences/recentBodies';
export default function CharacterExperiences({bookId,characterId,onState,onRequest,initialBatchId,recentBatchId}:{bookId:string;characterId:string;onState:(state:WorkspaceEditor)=>void;onRequest:(action:()=>void)=>boolean|void;initialBatchId?:string|null;recentBatchId?:string|null}){
 const [workspace,setWorkspace]=useState<ExperienceWorkspace|null>(null),[objects,setObjects]=useState<PlanningObject[]>([]),[fieldKey,setFieldKey]=useState(''),[instruction,setInstruction]=useState(''),[characterIds,setCharacterIds]=useState([characterId]),[record,setRecord]=useState<ExperienceRecord|null>(null),[candidateDraft,setCandidateDraft]=useState<ExperienceDraft|RecentBodyExperienceDraft|null>(null),[eventIds,setEventIds]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[storageBlocked,setStorageBlocked]=useState(false),[externalPending,setExternalPending]=useState(Boolean(initialBatchId));
 const scopeRef=useRef(`${bookId}:${characterId}`);scopeRef.current=`${bookId}:${characterId}`;
 const alive=useRef(true),epoch=useRef(0),editor=useRef<WorkspaceEditor>({dirty:false,locked:false}),resultStorage=`nd-experience-results:${bookId}:${characterId}`;
 const load=useCallback(async()=>{const seq=++epoch.current;const [next,planning]=await Promise.all([newDesignApi.getExperienceWorkspace(bookId,characterId),newDesignApi.getPlanningCenter(bookId)]);if(!alive.current||seq!==epoch.current)return;if(next.bookId!==bookId||next.characterId!==characterId||planning.bookId!==bookId)throw new Error('经历来源或时间编辑范围不属于当前人物所在书。');setWorkspace(next);setObjects(planning.objects);},[bookId,characterId]);
 const command=useReferenceCommand<ExperienceRequest,ExperienceRecord>(`nd-experience-request:${bookId}:${characterId}`,{valid:(input):input is ExperienceRequest=>experienceRequestSchema.safeParse(input).success&&(input as ExperienceRequest).sources.some(source=>source.characterId===characterId),write:input=>newDesignApi.generateExperiences(bookId,input),read:input=>newDesignApi.readExperienceOriginal(bookId,input),restore:input=>{setCharacterIds(input.sources.map(source=>source.characterId));setFieldKey(input.sources.find(source=>source.characterId===characterId)?.fieldKey??'');setInstruction(input.instruction);},accept:async(next,input)=>{if(next.bookId!==bookId||next.id!==input.requestKey||next.request.requestKey!==input.requestKey||next.request.instruction!==input.instruction||next.request.sources.length!==input.sources.length||next.request.sources.some((source,index)=>source.characterId!==input.sources[index]?.characterId||source.fieldKey!==input.sources[index]?.fieldKey))throw new Error('原经历回执与完整人物、小传字段或要求不同。');setRecord(next);if(next.status==='running')throw new Error(next.error||'原经历模型调用或结果保存待核对，只读核对，不重复生成。');localStorage.setItem(resultStorage,JSON.stringify(next));await load();}});
 const series=useExperienceSeries(bookId,characterId,next=>setRecord(next));
 const [recentLocked,setRecentLocked]=useState(false);
 const [timelineState,setTimelineState]=useState({dirty:false,locked:false});
 const receiveRecent=useCallback((state:WorkspaceEditor)=>{setRecentLocked(state.locked);onState({...editor.current,locked:editor.current.locked||state.locked||busy||command.locked||storageBlocked||externalPending||series.isLocked()});},[onState,busy,command.locked,storageBlocked,externalPending,series]);
 const receiveRecentDraft=useCallback((next:RecentBodyExperienceDraft)=>{setRecentLocked(false);onState({...editor.current,locked:editor.current.locked||busy||command.locked||storageBlocked||externalPending||series.isLocked()});onRequest(()=>setCandidateDraft(next));},[onState,onRequest,busy,command.locked,storageBlocked,externalPending,series]);
 const locked=busy||command.locked||storageBlocked||externalPending||series.isLocked()||recentLocked;
 const publish=useCallback((state:WorkspaceEditor)=>{editor.current=state;setTimelineState(current=>current.dirty===state.dirty&&current.locked===state.locked?current:{dirty:state.dirty,locked:state.locked});onState({...state,locked:state.locked||locked});},[locked,onState]);
 useEffect(()=>{onState({...editor.current,locked:editor.current.locked||locked});},[locked,onState]);
 useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(resultStorage);if(raw){const saved=JSON.parse(raw) as ExperienceRecord;if(!validExperienceRecord(saved)||saved.bookId!==bookId||!experienceRequestSchema.safeParse(saved.request).success||saved.id!==saved.request.requestKey||!saved.request.sources.some(source=>source.characterId===characterId)||!saved.snapshot?.actors.some(actor=>actor.id===characterId))throw new Error();setRecord(saved);if(saved.status==='running')setExternalPending(true);}}catch{setStorageBlocked(true);setError('原经历结果凭证无法完整读取，记录保留，请核对网站存储与运行维护。');}void load().catch(reason=>{if(alive.current)setError(reason instanceof Error?reason.message:'经历来源尚未读取。');});return()=>{alive.current=false;epoch.current++;onState({dirty:false,locked:false});};},[bookId,characterId]);
 const verifyExternal=async(batchId:string)=>{const scope=scopeRef.current;if(command.isLocked()&&command.pending?.requestKey!==batchId){setError('当前有另一份原经历凭证，请先只读核对原请求；未覆盖。');return;}setBusy(true);try{const next=await newDesignApi.getExperienceRecord(bookId,batchId);if(!alive.current||scope!==scopeRef.current)return;if(!next||!validExperienceRecord(next)||next.bookId!==bookId||!next.request.sources.some(source=>source.characterId===characterId))throw new Error('原经历结果来源未完整读取，凭证保留。');setRecord(next);localStorage.setItem(resultStorage,JSON.stringify(next));if(next.status==='running'){setExternalPending(true);return;}await load();setExternalPending(false);}catch(reason){if(alive.current&&scope===scopeRef.current){setError(reason instanceof Error?reason.message:'原经历结果未读取。');setExternalPending(true);}}finally{if(alive.current&&scope===scopeRef.current)setBusy(false);}};
 useEffect(()=>{if(initialBatchId)void verifyExternal(initialBatchId);},[initialBatchId]);
 const endUnknown=async()=>{const scope=scopeRef.current;const input=command.pending??record?.request;if(!input||busy||command.busy||!confirm('明确结束这份未知经历请求的占用，保留原模型是否完成与用量未知。不会自动再次生成；已有来源与领取仍保留。是否继续？'))return;setBusy(true);try{const next=await newDesignApi.endUnknownExperiences(bookId,input);if(!alive.current||scope!==scopeRef.current)return;setRecord(next);localStorage.setItem(resultStorage,JSON.stringify(next));if(command.pending){setBusy(false);await command.verify();}else{await load();setExternalPending(false);}}catch(reason){if(alive.current&&scope===scopeRef.current)setError(reason instanceof Error?reason.message:'原请求占用未结束，请保留凭证核对。');}finally{if(alive.current&&scope===scopeRef.current)setBusy(false);}};
 const prepare=(scope:'one'|'all'|'selected')=>{if(locked||!fieldKey||!workspace||workspace.truncated)return;onRequest(()=>{if(command.isLocked()||series.isLocked())return;if(scope==='one')void command.perform({requestKey:crypto.randomUUID(),instruction:instruction.trim(),sources:[{characterId,fieldKey}]});else void series.start({characterIds:scope==='all'?workspace.characters.map(actor=>actor.id):characterIds,fieldKey},instruction);});};
 const select=async(candidateId:string)=>{if(locked||!record||!eventIds[candidateId])return;const original=record,seq=epoch.current;setBusy(true);setError('');try{const next=await newDesignApi.getExperienceDraft(bookId,original.id,candidateId,eventIds[candidateId]);if(!alive.current||seq!==epoch.current)return;if(next.source.batchId!==original.id||next.source.candidateId!==candidateId)throw new Error('候选来源未匹配，原时间草稿保留。');setBusy(false);onState({...editor.current,locked:editor.current.locked||command.isLocked()||storageBlocked});onRequest(()=>setCandidateDraft(next));}catch(reason){if(alive.current)setError(reason instanceof Error?reason.message:'经历候选未载入。');}finally{if(alive.current)setBusy(false);}};
 const receiveLoaded=useCallback((accepted:boolean)=>{if(accepted)setCandidateDraft(null);},[]),onSaved=useCallback(async()=>{await load();},[load]),preserve=useCallback(()=>!command.isLocked()&&!series.isLocked()&&!storageBlocked,[storageBlocked,series]);
 return <section className="nd-character-experiences"><header className="nd-section-heading"><div><h3>角色事件流 <Help label="人物经历来源">从本书人物明确选择的小传文本准备有出处的经历与时间候选，先核对完整人物来源，再按每批最多20人依次准备；中断后核对原批次并明确继续剩余人物。选择实际事件并载入原时间编辑器，检查、预览、保存提案，再单独审核。候选不写已发生事实、状态、持有或角色所知。日期与事件对应未知时保持未确认，不按名称合并。</Help></h3><p>用有来源的经历与时间安排观察角色处境，核对后再继续写作。</p></div><div className="nd-row-actions"><button className="nd-button" disabled={locked||!fieldKey||!workspace||workspace.truncated} onClick={()=>prepare('one')}>同步角色时间线</button><button className="nd-button" disabled={locked||!fieldKey||!workspace||workspace.truncated} onClick={()=>prepare('all')}>同步全部角色时间线</button><button className="nd-button" disabled={locked||!fieldKey||!workspace||workspace.truncated||!characterIds.length} onClick={()=>prepare('selected')}>同步所选角色时间线</button></div></header>
 {error&&<p role="alert">{error}</p>}{command.message&&<p role="status">{command.message}</p>}{command.pending&&<button className="nd-button" disabled={command.busy||busy} onClick={()=>void command.verify()}>只读核对原经历请求</button>}
 {externalPending&&record&&!command.pending&&<button className="nd-button" disabled={busy} onClick={()=>void verifyExternal(record.id)}>只读核对原人物经历结果</button>}{(command.pending||externalPending)&&record?.status==='running'&&<button className="nd-button" disabled={busy||command.busy} onClick={()=>void endUnknown()}>明确结束原未知经历占用</button>}
 <div className="nd-experience-input"><label>小传来源字段<select disabled={locked} value={fieldKey} onChange={event=>setFieldKey(event.target.value)}><option value="">明确选择已填写文本</option>{workspace?.sourceFields.map(field=><option key={field.key} value={field.key}>{field.label}</option>)}</select></label><label>同步指导<textarea disabled={locked} rows={3} value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="说明希望核对的经历范围与时间安排"/></label><details><summary>批量人物范围（每批最多20人）</summary><p>所选人物分别使用同一稳定字段的小传，先检查整个范围，未填写或字段不可用时停止，未发送模型请求；后续人物来源变化时停止剩余批次，不忽略人物。</p>{workspace?.characters.map(actor=><label key={actor.id}><input type="checkbox" disabled={locked||actor.id===characterId} checked={characterIds.includes(actor.id)} onChange={event=>setCharacterIds(current=>event.target.checked?[...current,actor.id]:current.filter(id=>id!==actor.id))}/>{actor.title}</label>)}</details></div>
 {series.plan&&<section aria-label="人物分批进度"><h4>人物分批进度：{series.plan.next}／{series.plan.parts.length}</h4><p role="status">{series.message}</p>{series.plan.records.map((item,index)=><button className="nd-button" key={item.id} disabled={busy||command.locked||series.isLocked()||editor.current.locked} onClick={()=>onRequest(()=>setRecord(item))}>检查第{index+1}批候选（{item.request.sources.length}人）</button>)}{['ready','pending'].includes(series.plan.stage)&&<button className="nd-button" disabled={series.busy||series.blocked||command.locked||busy} onClick={()=>void series.resume()}>{series.plan.stage==='pending'?'核对原批次并继续剩余人物':'继续剩余人物'}</button>}{series.plan.stage==='pending'&&<button className="nd-button" disabled={series.busy||series.blocked||command.locked||busy} onClick={()=>{if(confirm('明确结束原未知经历占用与本次后续分批，保留模型完成与用量未知、原来源和已保存结果，不自动再生成。是否继续？'))void series.endUnknown();}}>明确结束原未知分批占用</button>}{series.plan.stage==='ready'&&<button className="nd-button" disabled={series.busy||command.locked||busy} onClick={()=>series.stop()}>结束本次剩余分批</button>}</section>}{!series.plan&&series.message&&<p role="status">{series.message}</p>}
 {workspace?.truncated&&<p role="alert">人物或事件来源超出展示范围，未显示不代表不存在；不能据不完整清单批量同步。</p>}
 {record&&<section><h4>有出处的经历候选</h4>{record.error&&<p role="alert">{record.error}</p>}{record.output?.notes.map((note,index)=><p key={index} role="status">{note}</p>)}{record.output?.candidates.map(candidate=><article key={candidate.id}><header><h4>{candidate.title}</h4><span>{record.snapshot.actors.find(actor=>actor.id===candidate.characterId)?.title} · 待核对安排</span></header><p>{candidate.summary}</p><blockquote>{candidate.evidenceLabel}</blockquote><p>来源：{record.snapshot.actors.find(actor=>actor.id===candidate.characterId)?.fieldLabel}；字位 {candidate.evidenceStart}—{candidate.evidenceEnd}。</p><label>对应本书事件<select disabled={locked} value={eventIds[candidate.id]??''} onChange={event=>setEventIds(current=>({...current,[candidate.id]:event.target.value}))}><option value="">明确选择实际事件，不按名称合并</option>{workspace?.events.map(event=><option key={event.id} value={event.id}>{event.title}</option>)}</select></label><button className="nd-button" disabled={locked||!eventIds[candidate.id]} onClick={()=>void select(candidate.id)}>载入时间编辑器检查</button>{workspace?.eventTypeId&&<a target="_blank" rel="noreferrer" href={`/new-design/books/${bookId}/story-setting?tab=other&type=${workspace.eventTypeId}&new=1&detail=basic`}>创建事件资料</a>}</article>)}{record.output&&!record.output.candidates.length&&<p>原小传未提取出足够可靠的经历；说明与原请求保留。</p>}</section>}
 <button className="nd-button" disabled={locked} onClick={()=>void load().catch(reason=>setError(reason instanceof Error?reason.message:'来源尚未读取。'))}>重新读取经历与事件来源</button>
 <RecentBodyExperiences bookId={bookId} characterId={characterId} initialBatchId={recentBatchId} disabled={busy||command.locked||storageBlocked||externalPending||series.isLocked()||timelineState.dirty||timelineState.locked} onState={receiveRecent} onDraft={receiveRecentDraft}/>
 <AuthorTimelineEditor bookId={bookId} objects={objects} disabled={locked} preserveBody={preserve} onSaved={onSaved} candidateDraft={candidateDraft} onCandidateLoaded={receiveLoaded} onState={publish}/>
 </section>;
}
