import {useReferenceCommand} from "../referenceParity/useCommand";
import type {VisibleAdoptionInput,VisibleBatchWriteInput,VisibleBatchWriteReceipt} from "../../common/storyWorkspace";
import {useEffect,useRef,useState} from 'react';
import type {StoryBatchDraft,StoryBatchRecord,StoryBatchRequest} from '../../common/storyWorkspace';
import {canonicalWriteInput,writeInputHash} from '../../common/storyWorkspace';
import {ApiError,newDesignApi} from '../api';
import type {WorkspaceEditor} from './useGuard';
import Help from './Help';

export type StoryBatchSeed={mode:'setting';typeIds:string[];newTypeId:string}|{mode:'planning';scopeId:string}|{mode:'visible_prepare'|'visible_adjust';cardIds:string[]};
const labels:Record<string,string>={__title:'资料名称',goal:'目标',storyTime:'故事时间',mustHappen:'必须发生',mustPreserve:'必须保留',forbiddenBoundaries:'禁止越界',expectedChanges:'预期变化',characterArc:'人物弧',notes:'备注',eventSchedule:'事件发生顺序与时间',relationshipPlans:'人物关系发展安排'};
const blank=(value:unknown)=>value==null||value===''||Array.isArray(value)&&value.length===0;
const display=(value:unknown)=>Array.isArray(value)?value.join('；'):value&&typeof value==='object'?JSON.stringify(value):String(value??'未填写');
export default function BatchAiPanel({bookId,seed,open,onClose,onState,onLoad,onRequest,initialRequestKey,generationNonce,instructionSeed,hidePreparationControls=false,onBatchSaved}:{onBatchSaved?:()=>Promise<void>;generationNonce?:string;instructionSeed?:string;hidePreparationControls?:boolean;initialRequestKey?:string|null;bookId:string;seed:StoryBatchSeed;open:boolean;onClose:()=>void;onState:(state:WorkspaceEditor)=>void;onLoad:(draft:StoryBatchDraft)=>void;onRequest:(action:()=>void)=>boolean|void}){
 const [loadedAdoption,setLoadedAdoption]=useState<StoryBatchDraft|null>(null);
 const [savedSlots,setSavedSlots]=useState<string[]>([]),[batchConfirm,setBatchConfirm]=useState(false);
 const [instruction,setInstruction]=useState(''),[newCount,setNewCount]=useState(1),[record,setRecord]=useState<StoryBatchRecord|null>(null),[pending,setPending]=useState<StoryBatchRequest|null>(null),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Record<string,string[]>>({}),[confirmEnd,setConfirmEnd]=useState(false);
 const commandStorage=seed.mode==="visible_prepare"||seed.mode==="visible_adjust"?localStorage:sessionStorage;
 const storageKey=`new-design:story-batch:${bookId}:${seed.mode}`,sequence=useRef(0),inFlight=useRef(false),scope=useRef(storageKey);scope.current=storageKey;
 const modelLocked=unknown||record?.status==='running'||busy&&!record?.output;
 const adoption=useReferenceCommand<{batchKey:string;input:VisibleAdoptionInput},StoryBatchDraft>(`nd-visible-adoption:${bookId}:${seed.mode}`,{valid:(value):value is {batchKey:string;input:VisibleAdoptionInput}=>{const command=value as {batchKey:string;input:VisibleAdoptionInput};return typeof command?.batchKey==='string'&&typeof command.input?.requestKey==='string'&&typeof command.input.slotId==='string'&&typeof command.input.sourceHash==='string'&&Array.isArray(command.input.fieldKeys);},write:command=>newDesignApi.adoptVisibleFields(bookId,command.batchKey,command.input),read:command=>newDesignApi.readVisibleAdoption(bookId,command.batchKey,command.input),accept:async(draft,command)=>{if(!draft.decisionId||draft.bookId!==bookId||draft.slot.id!==command.input.slotId||draft.slot.sourceHash!==command.input.sourceHash||Object.keys(draft.values).length!==command.input.fieldKeys.length||command.input.fieldKeys.some(key=>!Object.hasOwn(draft.values,key)))throw new Error('原外显采用回执与本次范围不同。');setLoadedAdoption(draft);}});
 const batchWrite=useReferenceCommand<{batchKey:string;input:VisibleBatchWriteInput},VisibleBatchWriteReceipt>(`nd-visible-batch-write:${bookId}:${seed.mode}`,{
  valid:(value):value is {batchKey:string;input:VisibleBatchWriteInput}=>{const command=value as {batchKey:string;input:VisibleBatchWriteInput};return typeof command?.batchKey==='string'&&typeof command.input?.requestKey==='string'&&Array.isArray(command.input.items)&&command.input.items.length>0&&command.input.items.every(item=>typeof item.slotId==='string'&&typeof item.sourceHash==='string'&&Array.isArray(item.fieldKeys)&&typeof item.requestKey==='string'&&typeof item.saveRequestKey==='string');},
  write:command=>newDesignApi.writeVisibleBatch(bookId,command.batchKey,command.input),read:command=>newDesignApi.readVisibleBatchWrite(bookId,command.batchKey,command.input),
  accept:async(result,command)=>{if(result.contract!=='visible_batch_write_v1'||result.bookId!==bookId||result.batchKey!==command.batchKey||result.requestKey!==command.input.requestKey||result.inputHash!==await writeInputHash({contract:'visible_batch_write_v1',bookId,batchKey:command.batchKey,input:command.input})||result.items.length!==command.input.items.length||command.input.items.some(item=>!result.items.some(saved=>saved.bookId===bookId&&saved.card.id===item.slotId&&saved.requestKey===item.saveRequestKey&&saved.operation==='update'&&saved.aiDraftDecisionIds.length===1)))throw new Error('原批量保存回执与本次完整范围不同。');setSavedSlots(current=>[...new Set([...current,...result.items.map(item=>item.card.id)])]);setBatchConfirm(false);await onBatchSaved?.();}
 });
 const locked=!!modelLocked||adoption.locked||batchWrite.locked;
 useEffect(()=>{onState({dirty:false,locked:!!locked,save:async()=>!locked,discard:()=>!locked});},[locked,onState]);
 useEffect(()=>{if(loadedAdoption&&!locked){const draft=loadedAdoption;if(onRequest(()=>onLoad(draft))!==false)setLoadedAdoption(null);}},[loadedAdoption,locked,onRequest,onLoad]);
 const accept=(next:StoryBatchRecord,request:StoryBatchRequest)=>{if(next.bookId!==bookId||next.requestKey!==request.requestKey||canonicalWriteInput(next.request)!==canonicalWriteInput(request))throw new Error('原请求来源不匹配，凭证保留。');setRecord(next);setBatchConfirm(false);setUnknown(next.status==='running');setSelected(Object.fromEntries(next.snapshot.slots.map(slot=>[slot.id,Object.keys(next.output?.candidates[slot.id]??{}).filter(key=>blank(slot.values[key]))])));};
 useEffect(()=>{
  let active=true;sequence.current++;setBusy(false);setRecord(null);setPending(null);setUnknown(false);setError('');
  try{
   const raw=commandStorage.getItem(storageKey),retained=raw?JSON.parse(raw) as StoryBatchRequest:null;
   if(retained&&(retained.mode!==seed.mode||!retained.requestKey))throw new Error('原候选凭证无法匹配。');
   if(retained||initialRequestKey){
    setPending(retained);setUnknown(true);
    void (async()=>{
     if(retained&&initialRequestKey&&retained.requestKey!==initialRequestKey){
      const original=await newDesignApi.readStoryBatch(bookId,retained.requestKey);if(!active)return;
      if(!original||original.status==='running'){if(original)accept(original,retained);setError('本机还有另一原请求待核对；保留原请求，确认后再打开所选记录。');return;}
     }
     const key=initialRequestKey??retained!.requestKey,next=await newDesignApi.readStoryBatch(bookId,key);if(!active)return;
     if(!next||next.snapshot.mode!==seed.mode||next.requestKey!==key){setError('指定原候选未在本书找到，不推断未执行或改选其他请求。');return;}
     const request=key===retained?.requestKey?retained:next.request;
     accept(next,request);setPending(request);commandStorage.setItem(storageKey,JSON.stringify(request));
    })().catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'原候选未读取。');});
   }
  }catch(reason){setUnknown(true);setError(reason instanceof Error?reason.message:'原请求凭证未读取。');}
  return()=>{active=false;sequence.current++;};
 },[storageKey,initialRequestKey]);
 const generate=async(overrideInstruction?:string)=>{
  if(inFlight.current||locked)return;
  if(seed.mode==='setting'&&(!Number.isInteger(newCount)||newCount<0||newCount>10)){setError("新增数量请填写 0 至 10 的整数。");return;}
  const request:StoryBatchRequest=seed.mode==='setting'?{...seed,requestKey:crypto.randomUUID(),instruction:(overrideInstruction??instruction).trim(),newCount}:{...seed,requestKey:crypto.randomUUID(),instruction:(overrideInstruction??instruction).trim()};
  try{commandStorage.setItem(storageKey,JSON.stringify(request));}catch{setError('未能保留候选请求，尚未提交，请检查浏览器存储权限。');return;}
  const expected=storageKey,seq=++sequence.current;inFlight.current=true;setPending(request);setRecord(null);setSavedSlots([]);setBatchConfirm(false);setBusy(true);setUnknown(true);setError('');
  try{const next=await newDesignApi.generateStoryBatch(bookId,request);if(seq===sequence.current&&scope.current===expected)accept(next,request);}catch(reason){if(seq!==sequence.current||scope.current!==expected)return;const notWritten=reason instanceof ApiError&&reason.recovery?.mutationOutcome==='not_written';setUnknown(!notWritten);if(notWritten){commandStorage.removeItem(storageKey);setPending(null);}setError(reason instanceof Error?reason.message:'候选结果待核对。');}finally{inFlight.current=false;if(seq===sequence.current&&scope.current===expected)setBusy(false);}
 };
 const handledGeneration=useRef<string|undefined>(undefined);
 useEffect(()=>{if(!generationNonce||handledGeneration.current===generationNonce)return;handledGeneration.current=generationNonce;if(!locked&&!inFlight.current)void generate(instructionSeed);},[generationNonce]);
 const read=async()=>{if(!pending||inFlight.current)return;const seq=++sequence.current,expected=storageKey;setBusy(true);setError('');try{const next=await newDesignApi.readStoryBatch(bookId,pending.requestKey);if(seq!==sequence.current||scope.current!==expected)return;if(next)accept(next,pending);else setError('未找到原请求回执，不代表未执行；原请求和已有资料保留。');}catch(reason){if(seq===sequence.current)setError(reason instanceof Error?reason.message:'原请求未读取。');}finally{if(seq===sequence.current)setBusy(false);}};
 const showValue=(key:string,value:unknown)=>{const name=(id:string)=>record?.snapshot.materials.find(item=>item.id===id)?.title??'指定对象';if(key==='relationshipPlans'&&Array.isArray(value))return value.map(row=>`${name(row.sourceId)} → ${name(row.targetId)}：${row.description}`).join('；');if(key==='eventSchedule'&&value&&typeof value==='object')return Object.entries(value as Record<string,{occurrenceOrder:number|null;timeLabel:string}>).map(([id,row])=>`${name(id)}：${row.occurrenceOrder==null?'未分配发生顺序':'发生顺序 '+row.occurrenceOrder}${row.timeLabel?' · '+row.timeLabel:''}`).join('；');return display(value);};
 const end=async()=>{if(!pending||busy||!confirmEnd)return;setBusy(true);setError('');try{const next=await newDesignApi.endUnknownStoryBatch(bookId,pending.requestKey);if(scope.current===storageKey){accept(next,pending);setConfirmEnd(false);}}catch(reason){setError(reason instanceof Error?reason.message:'原请求结束结果待核对，请读取原回执。');}finally{setBusy(false);}};
 const load=async(slotId:string)=>{if(!record||!record.output||busy)return;const keys=selected[slotId]??[];if(!keys.length){setError('请先勾选需要载入的字段。');return;}setBusy(true);setError('');const expected=storageKey,seq=++sequence.current;try{if(record.snapshot.mode==='visible_prepare'||record.snapshot.mode==='visible_adjust'){const slot=record.snapshot.slots.find(slot=>slot.id===slotId);if(!slot)throw new Error('所选人物候选未匹配。');const command={batchKey:record.requestKey,input:{slotId,fieldKeys:[...keys],sourceHash:slot.sourceHash,requestKey:crypto.randomUUID()}};onRequest(()=>void adoption.perform(command));return;}const checked=await newDesignApi.checkStoryBatchSlot(bookId,record.requestKey,slotId);if(seq!==sequence.current||scope.current!==expected)return;const values=Object.fromEntries(keys.map(key=>[key,checked.values[key]]));onRequest(()=>onLoad({...checked,values}));}catch(reason){if(seq===sequence.current)setError(reason instanceof Error?reason.message:'候选来源未核对。');}finally{if(seq===sequence.current)setBusy(false);}};
 const saveBatch=()=>{if(!record?.output||locked||!batchConfirm)return;const items=record.snapshot.slots.filter(slot=>!savedSlots.includes(slot.id)&&(selected[slot.id]?.length??0)>0).map(slot=>({slotId:slot.id,fieldKeys:[...selected[slot.id]],sourceHash:slot.sourceHash,requestKey:crypto.randomUUID(),saveRequestKey:crypto.randomUUID()}));if(!items.length)return;onRequest(()=>void batchWrite.perform({batchKey:record.requestKey,input:{requestKey:crypto.randomUUID(),items}}));};
 if(!open&&!pending&&!unknown&&!adoption.locked&&!batchWrite.locked)return null;
 return <section className="nd-story-batch" aria-label={seed.mode==='setting'?'整组设定 AI 候选':seed.mode==='planning'?'范围规划 AI 候选':'人物外显 AI 候选'} hidden={!open&&!locked}>
  <header className="nd-section-heading"><h3>{seed.mode==='setting'?'AI 准备本组设定':seed.mode==='visible_prepare'?'AI 准备人物外显':seed.mode==='visible_adjust'?'AI 调整人物外显':'AI 规划当前范围'} <Help label="整组候选">设定补充空白字段；外显与规划已有内容默认不勾选覆盖。只载入勾选字段，原候选与来源版本保留。请在标准表单检查后保存；规划还需明确采用。</Help></h3><button type="button" className="nd-button" disabled={!!locked} onClick={onClose}>收起候选</button></header>
  {record?.error&&<p role="alert" className="nd-message is-error">{record.error}</p>}
  {batchWrite.message&&<p role="status">{batchWrite.message}</p>}{batchWrite.pending&&<button className="nd-button" disabled={batchWrite.busy} onClick={()=>void batchWrite.verify()}>核对原批量保存结果</button>}{adoption.message&&<p role="status">{adoption.message}</p>}{adoption.pending&&<button className="nd-button" disabled={adoption.busy} onClick={()=>void adoption.verify()}>核对原外显采用</button>}{error&&<p role="alert" className="nd-message is-error">{error}</p>}
  {(error||record?.error)&&<button type="button" className="nd-button" disabled={!!locked} onClick={()=>onRequest(()=>location.assign('/new-design/structure/models'))}>核对创作模型设置</button>}
  {!hidePreparationControls&&<><label>本次创作要求<textarea value={instruction} maxLength={2000} disabled={!!locked} rows={2} onChange={event=>setInstruction(event.target.value)} placeholder="可留空，由 AI 根据本书资料推荐"/></label>
  {seed.mode==='setting'&&<label>新增设定数量<input type="number" min={0} max={10} value={newCount} disabled={!!locked} onChange={event=>setNewCount(Number(event.target.value))}/></label>}
  <div className="nd-row-actions"><button type="button" className="nd-button nd-button-primary" disabled={!!locked||seed.mode==='setting'&&(!seed.typeIds.length||!seed.newTypeId)} onClick={()=>onRequest(()=>void generate())}>{record?.status==='review'?'另行准备一组候选':'准备候选'}</button>{pending&&<button type="button" className="nd-button" disabled={busy} onClick={()=>void read()}>核对原请求结果</button>}</div></>}{hidePreparationControls&&pending&&<button className="nd-button" disabled={busy} onClick={()=>void read()}>核对原生成请求</button>}
  {locked&&<p role="status">{busy?'正在处理候选请求…':'原请求结果待核对，请保留此页和请求凭证。'}</p>}
  {record?.status==='running'&&!busy&&<div><label><input type="checkbox" checked={confirmEnd} onChange={event=>setConfirmEnd(event.target.checked)}/>我确认结束此原请求的页面占用，生成结果与用量仍可能未知。</label><button type="button" className="nd-button" disabled={!confirmEnd} onClick={()=>void end()}>结束原请求占用</button></div>}
  {initialRequestKey&&pending&&pending.requestKey!==initialRequestKey&&record&&record.status!=='running'&&<button type="button" className="nd-button" onClick={()=>onRequest(()=>{commandStorage.removeItem(storageKey);location.reload();})}>打开所选原候选</button>}
  {record&&<p>本次准备 {record.snapshot.slots.length} 项 · {record.snapshot.mode==='setting'?'故事设定':record.snapshot.mode==='visible_prepare'?'外显准备':record.snapshot.mode==='visible_adjust'?'外显调整':'故事规划'}{record.request.mode==='planning'&&record.request.scopeId!=='book'?' · 指定卷章范围':''}</p>}
  {record?.output&&record.snapshot.slots.map(slot=>{const values=record.output!.candidates[slot.id]??{},chosen=selected[slot.id]??[];return <article key={slot.id} className="nd-story-batch-item"><h4>{slot.title}{savedSlots.includes(slot.id)?" · 已保存":null}</h4>{Object.entries(values).map(([key,value])=><label key={key} className="nd-story-batch-field"><input type="checkbox" disabled={busy||locked||savedSlots.includes(slot.id)} checked={chosen.includes(key)} onChange={event=>setSelected(current=>({...current,[slot.id]:event.target.checked?[...chosen,key]:chosen.filter(item=>item!==key)}))}/><span><strong>{slot.fields.find(field=>field.key===key)?.name??labels[key]??key}</strong>{!blank(slot.values[key])&&<small>原内容：{showValue(key,slot.values[key])}；勾选后将替换此字段。</small>}<p>{showValue(key,value)}</p></span></label>)}<button type="button" className="nd-button" disabled={busy||locked||savedSlots.includes(slot.id)||!chosen.length} onClick={()=>void load(slot.id)}>载入编辑器检查</button></article>;})}
  {record?.output&&(seed.mode==='visible_prepare'||seed.mode==='visible_adjust')&&<div className="nd-visible-batch-save"><label><input type="checkbox" disabled={locked} checked={batchConfirm} onChange={event=>setBatchConfirm(event.target.checked)}/>确认将勾选字段保存到对应角色卡；其余内容保留。</label><button className="nd-button nd-button-primary" disabled={locked||!batchConfirm||!record.snapshot.slots.some(slot=>!savedSlots.includes(slot.id)&&(selected[slot.id]?.length??0)>0)} onClick={saveBatch}>写入批量结果</button></div>}
 </section>;
}
