import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {BookSummary,BookViewWorkspace,PlanningCenterWorkspace,PlanningObject} from '../../common/contracts';
import {newDesignApi} from '../api';
import BookShell from '../BookShell';
import PlanningCenterPage,{type PlanningEditorState} from '../planningCenter/PlanningCenterPage';
import {GraphCanvas,type GraphEdge} from '../professionalViews';
import {PLANNING_TABS,plansInScope,planningCardIds,cardsForDimension,settingHref,writingHref,plannedTime,plannedRelations,hasAmbiguousNavigation,type PlanningTab} from './model';
import type {StoryBatchDraft} from '../../common/storyWorkspace';
import BatchAiPanel from './BatchAiPanel';
import {useWorkspaceGuard,type WorkspaceEditor} from './useGuard';
import {useWorkspaceLocation} from './useLocation';
import Help from './Help';
import './workspace.css';

export default function PlanningWorkspace({bookId}:{bookId:string}) {
 const [book,setBook]=useState<BookSummary|null>(null),[workspace,setWorkspace]=useState<PlanningCenterWorkspace|null>(null),[materials,setMaterials]=useState<BookViewWorkspace|null>(null),[error,setError]=useState(''),[flags,setFlags]=useState({dirty:false,locked:false});
 const [batchOpen,setBatchOpen]=useState(()=>new URLSearchParams(location.search).has('batch')),[batchDraft,setBatchDraft]=useState<StoryBatchDraft|undefined>();
 const batch=useRef<WorkspaceEditor|null>(null),receiveBatch=useCallback((state:WorkspaceEditor)=>{batch.current=state;},[]);
 const editor=useRef<PlanningEditorState|null>(null),generation=useRef(0),guard=useWorkspaceGuard(()=>[editor.current,batch.current].filter((item):item is WorkspaceEditor=>item!==null)),url=useWorkspaceLocation(guard.request);
 const rawTab=url.query.get('tab')??'chapters',tab=PLANNING_TABS.some(item=>item.key===rawTab)?rawTab as PlanningTab:'chapters',scope=url.query.get('scope')??'book',search=url.query.get('q')??'',display=url.query.get('display')==='graph'?'graph':'table',selectedId=url.query.get('selected')??'',planId=url.query.get('plan')??(location.hash.startsWith('#plan-')?location.hash.slice(6):''),creating=url.query.get('new')==='1',collapsed=url.query.get('detail')==='closed';
 const receive=useCallback((state:PlanningEditorState)=>{editor.current=state;setFlags({dirty:state.dirty,locked:state.locked});},[]);
 const load=async()=>{const seq=++generation.current;try{const [nextBook,nextWorkspace,nextMaterials]=await Promise.all([newDesignApi.getBook(bookId),newDesignApi.getPlanningCenter(bookId),newDesignApi.getBookViewWorkspace(bookId)]);if(seq!==generation.current)return;if(nextBook.id!==bookId||nextWorkspace.bookId!==bookId||nextMaterials.bookId!==bookId)throw new Error('规划来源不属于本书。');setBook(nextBook);setWorkspace(nextWorkspace);setMaterials(nextMaterials);setError('');}catch(reason){if(seq===generation.current)setError(reason instanceof Error?reason.message:'规划来源未读取。');}};
 useEffect(()=>{void load();return()=>{generation.current++;};},[bookId]);
 const plans=useMemo(()=>plansInScope(workspace?.objects??[],scope),[workspace,scope]),cardIds=planningCardIds(plans),cards=cardsForDimension(materials?.cards??[],tab).filter(item=>scope==='book'||cardIds.has(item.id)),selectedPlan=workspace?.objects.find(item=>item.id===planId&&item.status==='active'),selectedCard=materials?.cards.find(item=>item.id===(selectedId||selectedPlan?.cardId)&&item.status==='active');
 const filteredPlans=plans.filter(item=>item.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())),filteredCards=cards.filter(item=>item.title.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const change=(patch:Record<string,string|null>,reset=false)=>url.update(patch,()=>{if(reset)editor.current=null;});
 const selectPlan=(item:PlanningObject)=>change({plan:item.id,selected:item.cardId,detail:'open',new:null},true);
 const linkedPlans=(id:string)=>plans.filter(item=>item.cardId===id||item.currentVersion.references.some(ref=>ref.cardId===id)||plannedRelations(item).some(row=>row.sourceId===id||row.targetId===id));
 const selectCard=(id:string)=>{const linked=linkedPlans(id),current=linked.find(item=>item.id===planId);change({selected:id,plan:current?.id??linked[0]?.id??null,detail:'open',new:null},true);};
 const ambiguous=hasAmbiguousNavigation(url.query);
 const chapter=selectedPlan?.level==='chapter'?selectedPlan.cardId:selectedCard&&['chapter','chapter_plan'].includes(selectedCard.typeKey)?selectedCard.id:null;
 const graphObjects=tab==='chapters'?filteredPlans.map(item=>({id:item.id,title:item.title,typeLabel:({story:'全书',volume:'卷',chapter:'章',scene:'场景'}as const)[item.level]})):[...filteredPlans.map(item=>({id:item.id,title:item.title,typeLabel:'规划'})),...filteredCards.map(item=>({id:item.id,title:item.title,typeLabel:item.cardTypeName}))];
 const edges:GraphEdge[]=tab==='chapters'?filteredPlans.filter(item=>item.parentObjectId).map(item=>({id:item.id,sourceId:item.parentObjectId!,targetId:item.id,label:'包含',directed:true,available:true})):filteredPlans.flatMap(item=>item.currentVersion.references.filter(ref=>filteredCards.some(card=>card.id===ref.cardId)).map(ref=>({id:ref.id,sourceId:item.id,targetId:ref.cardId,label:ref.action?({plant:'计划埋设',reinforce:'计划推进',recover:'计划回收',misdirect:'计划误导',reveal:'计划揭示'}as const)[ref.action]:'计划关联',directed:true,available:true})));
 if(tab==='relations')for(const plan of filteredPlans)for(const [index,row]of plannedRelations(plan).entries())edges.push({id:`relationship:${plan.id}:${index}`,sourceId:row.sourceId,targetId:row.targetId,label:`计划：${row.description}`,directed:true,available:true});
 const graphSelect=(id:string)=>{const plan=plans.find(item=>item.id===id);if(plan)selectPlan(plan);else selectCard(id);};
 if(!book)return <div className="nd-shell"><p role={error?'alert':'status'}>{error||'正在读取故事规划…'}</p>{error&&<button className="nd-button" onClick={()=>void load()}>重新读取</button>}</div>;
 return <BookShell compact book={book} active="planning"><main className="nd-story-workspace nd-story-planning"><header className="nd-story-heading"><h2>③ 故事规划 <Help label="故事规划">各维度查看同一组全书、卷、章和场景计划及其引用。保存形成候选，采用后成为创作依据；人物、关系、伏笔和道具的计划变化不代表事情已经发生。</Help></h2><div className="nd-row-actions"><a className="nd-button" href={selectedCard?settingHref(bookId,selectedCard,location.pathname+location.search+location.hash):`/new-design/books/${bookId}/story-setting`}>查看设定档案</a><a className="nd-button nd-button-primary" href={writingHref(bookId,chapter)}>进入正文创作</a></div></header>
 {guard.dialog}{ambiguous&&<p role="alert">来源参数重复，不能编辑；请从本书目录重新选择。</p>}{error&&<p className="nd-message is-error" role="alert">{error}</p>}
 <nav className="nd-story-tabs" aria-label="规划维度">{PLANNING_TABS.map(item=><button key={item.key} aria-pressed={item.key===tab} onClick={()=>change({tab:item.key})}>{item.label}</button>)}</nav>
 <div className="nd-story-toolbar"><label>规划范围<select value={scope} onChange={event=>change({scope:event.target.value})}><option value="book">全书</option>{scope!=="book"&&!workspace?.objects.some(item=>item.id===scope)&&<option value={scope}>指定范围未找到</option>}{workspace?.objects.filter(item=>item.status==='active'&&['volume','chapter'].includes(item.level)).map(item=><option key={item.id} value={item.id}>{item.level==='volume'?'卷':'章'} · {item.title}</option>)}</select></label><label>搜索<input value={search} placeholder="按名称搜索" onChange={event=>change({q:event.target.value})}/></label><div className="nd-row-actions"><button className="nd-button" aria-pressed={display==='table'} onClick={()=>change({display:'table'})}>表格</button><button className="nd-button" aria-pressed={display==='graph'} onClick={()=>change({display:'graph'})}>图形</button><button className="nd-button" onClick={()=>change({new:'1',plan:null,detail:'open'},true)}>新增规划</button><button className="nd-button" disabled={!editor.current||flags.locked} onClick={()=>void editor.current?.save()}>保存</button><button className="nd-button" aria-expanded={!collapsed} onClick={()=>change({detail:collapsed?'open':'closed'})}>{collapsed?'展开详情':'收起详情'}</button></div><button type="button" className="nd-button" disabled={ambiguous||scope!=="book"&&!workspace?.objects.some(item=>item.id===scope&&item.status==="active")} onClick={()=>guard.request(()=>setBatchOpen(true))}>AI 规划当前范围</button></div>
 <BatchAiPanel initialRequestKey={url.query.get("batch")} bookId={bookId} seed={{mode:'planning',scopeId:scope}} open={batchOpen} onClose={()=>setBatchOpen(false)} onState={receiveBatch} onRequest={guard.request} onLoad={draft=>{setBatchDraft(draft);url.commit({plan:draft.slot.planningId,selected:null,new:draft.slot.planningId?null:'1',detail:'open'},true);}}/>
 {scope!=='book'&&!workspace?.objects.some(item=>item.id===scope&&item.status==='active')&&<p role="alert">指定范围未找到，未切换成全书或其他范围。</p>}
 {selectedPlan&&!plans.some(item=>item.id===selectedPlan.id)&&<p role="status">选中规划不在当前筛选范围内，原详情保留。</p>}<div className={`nd-story-planning-layout${collapsed?' is-detail-closed':''}`}><aside className="nd-story-index" aria-label="规划对象索引">{tab==='chapters'?filteredPlans.map(item=><button key={item.id} className={item.id===planId?'is-selected':''} aria-pressed={item.id===planId} onClick={()=>selectPlan(item)}><strong>{item.title}</strong><small>{({story:'全书',volume:'卷',chapter:'章',scene:'场景'}as const)[item.level]}</small></button>):filteredCards.map(item=><button key={item.id} className={item.id===selectedId?'is-selected':''} aria-pressed={item.id===selectedId} onClick={()=>selectCard(item.id)}><strong>{item.title}</strong><small>{linkedPlans(item.id).length} 项规划关联</small></button>)}</aside>
 <section className="nd-story-canvas" aria-label="当前维度计划">{display==='graph'?<><GraphCanvas objects={graphObjects.slice(0,80)} points={graphObjects.slice(0,80).map((item,index)=>({id:item.id,x:30+(index%4)*230,y:30+Math.floor(index/4)*120}))} edges={edges} selected={selectedId||planId} onSelect={graphSelect} onEdge={id=>{const edge=edges.find(item=>item.id===id),plan=plans.find(item=>item.id===edge?.sourceId)||plans.find(item=>id.startsWith(`relationship:${item.id}:`));if(plan)selectPlan(plan);}}/>{graphObjects.length>80&&<p role="status">图形展示前 80 个匹配对象，左侧索引保留全部已读取结果；可搜索缩小范围。</p>}</>:<table className="nd-story-table"><thead><tr><th>{tab==='chapters'?'卷章场景':'对象'}</th><th>{tab==='timeline'?'计划发生顺序／时间':'计划安排'}</th><th>{tab==='timeline'?'叙述位置':'关联卷章'}</th></tr></thead><tbody>{tab==='chapters'?filteredPlans.map(item=><tr key={item.id}><td><button onClick={()=>selectPlan(item)}>{item.title}</button></td><td>{String(item.currentVersion.content.goal??'未填写目标')}<small>{item.adoptedVersionId===item.currentVersionId?'此版本已采用':'此版本为候选'}</small></td><td>{workspace?.objects.find(parent=>parent.id===item.parentObjectId)?.title??'全书'}</td></tr>):filteredCards.map(item=>{const linked=linkedPlans(item.id);return <tr key={item.id}><td><button onClick={()=>selectCard(item.id)}>{item.title}</button></td><td>{linked.length?linked.map(plan=><p key={plan.id}>{tab==='timeline'?plannedTime(plan,item.id):tab==='characters'?[...plan.currentVersion.references.filter(ref=>ref.cardId===item.id&&ref.note).map(ref=>ref.note),String(plan.currentVersion.content.characterArc??plan.currentVersion.content.goal??'未填写人物安排')].join('；'):tab==='relations'?plannedRelations(plan).filter(row=>row.sourceId===item.id||row.targetId===item.id).map(row=>`${materials?.cards.find(card=>card.id===row.sourceId)?.title??'来源人物'} → ${materials?.cards.find(card=>card.id===row.targetId)?.title??'关联人物'}：${row.description}`).join('；')||'未填写关系发展安排':tab==='props'?Array.isArray(plan.currentVersion.content.expectedChanges)?plan.currentVersion.content.expectedChanges.join('；'):'未填写预期变化':tab==='clues'?plan.currentVersion.references.filter(ref=>ref.cardId===item.id).map(ref=>ref.action?({plant:'埋设',reinforce:'推进',recover:'回收',misdirect:'误导',reveal:'揭示'}as const)[ref.action]:'关联').join('、'):String(plan.currentVersion.content.goal??'未填写事件安排')}</p>):'尚无规划关联'}</td><td>{linked.map(plan=><button key={plan.id} onClick={()=>selectPlan(plan)}>{plan.title}</button>)}</td></tr>;})}</tbody></table>}</section>
 <aside className="nd-story-plan-detail" hidden={collapsed}>{selectedCard&&<div className="nd-story-selected"><h3>{selectedCard.title}</h3><a className="nd-button" href={settingHref(bookId,selectedCard,location.pathname+location.search+location.hash)}>查看该对象设定档案</a></div>}{selectedId&&!selectedCard&&<p role="alert">指定资料不属于已读取的本书对象，原位置保留。</p>}{ambiguous?<p>原来源未确认，不能写入规划。</p>:creating||selectedPlan?<PlanningCenterPage key={`${planId}:${creating}`} embedded batchDraft={batchDraft} bookId={bookId} createNew={creating} onEditorStateChange={receive} onRequestChange={guard.request} onSavedObject={saved=>{setBatchDraft(undefined);setWorkspace(current=>current?{...current,objects:current.objects.some(item=>item.id===saved.id)?current.objects.map(item=>item.id===saved.id?saved:item):[...current.objects,saved]}:current);if(creating)url.commit({plan:saved.id,selected:saved.cardId,new:null,detail:'open'},true);void load();}}/>:planId?<p role="alert">指定规划未找到，未自动打开其他规划。</p>:<p>选择一项关联规划查看详情，或新增规划。尚无关联的资料可在设定档案中编辑，不能把档案保存冒充规划。</p>}</aside></div>
 </main></BookShell>;
}
