import {useCallback,useEffect,useRef,useState} from 'react';
import type {BookSummary,BookViewWorkspace,CardTypeSummary,FieldDefinition} from '../../common/contracts';
import {newDesignApi} from '../api';
import BookShell from '../BookShell';
import {BusinessFormWorkspace,type BusinessEditorState} from '../businessForms';
import {SETTING_TABS,settingTabForType,safePlanningReturn,hasAmbiguousNavigation,type SettingTab} from './model';
import {useWorkspaceGuard,type WorkspaceEditor} from './useGuard';
import {useWorkspaceLocation} from './useLocation';
import Help from './Help';
import BatchAiPanel from './BatchAiPanel';
import type {StoryBatchDraft} from '../../common/storyWorkspace';
import InitialStates from './InitialStates';
import Relations from './Relations';
import {CHARACTER_DETAILS,WORLD_DETAILS,CastIndex,SelectedSummary,ReferenceDetail} from './referenceLayout';
import './workspace.css';

export default function SettingWorkspace({bookId,initialTab}:{bookId:string;initialTab?:SettingTab}) {
 const [book,setBook]=useState<BookSummary|null>(null),[types,setTypes]=useState<CardTypeSummary[]>([]),[workspace,setWorkspace]=useState<BookViewWorkspace|null>(null),[error,setError]=useState(''),[initialFields,setInitialFields]=useState<FieldDefinition[]>([]),[flags,setFlags]=useState({dirty:false,locked:false});
 const [materialEpoch,setMaterialEpoch]=useState(0);
 const [batchOpen,setBatchOpen]=useState(()=>{const q=new URLSearchParams(location.search);return q.has('batch')&&!q.has('batchMode');}),[batchDraft,setBatchDraft]=useState<StoryBatchDraft|undefined>();
 const [visibleMode,setVisibleMode]=useState<"visible_prepare"|"visible_adjust">(()=>new URLSearchParams(location.search).get("batchMode")==="visible_adjust"?"visible_adjust":"visible_prepare"),[visibleOpen,setVisibleOpen]=useState(()=>["visible_prepare","visible_adjust"].includes(new URLSearchParams(location.search).get("batchMode")??"")),[visibleIds,setVisibleIds]=useState<string[]>([]);
 const [visibleGuidance,setVisibleGuidance]=useState(""),[prepareNonce,setPrepareNonce]=useState<string>(),[adjustNonce,setAdjustNonce]=useState<string>(),[visibleBusy,setVisibleBusy]=useState({prepare:false,adjust:false});
 const visibleBatch=useRef<WorkspaceEditor|null>(null),visibleAdjust=useRef<WorkspaceEditor|null>(null),receiveVisible=useCallback((state:WorkspaceEditor)=>{visibleBatch.current=state;setVisibleBusy(current=>current.prepare===state.locked?current:{...current,prepare:state.locked});},[]),receiveVisibleAdjust=useCallback((state:WorkspaceEditor)=>{visibleAdjust.current=state;setVisibleBusy(current=>current.adjust===state.locked?current:{...current,adjust:state.locked});},[]);
 const batch=useRef<WorkspaceEditor|null>(null),reference=useRef<WorkspaceEditor|null>(null);
 const receiveReference=useCallback((state:WorkspaceEditor)=>{reference.current=state;},[]);
 const receiveBatch=useCallback((state:WorkspaceEditor)=>{batch.current=state;},[]);
 const editor=useRef<BusinessEditorState|null>(null),initial=useRef<WorkspaceEditor|null>(null),relations=useRef<WorkspaceEditor|null>(null),generation=useRef(0);
 const guard=useWorkspaceGuard(()=>[editor.current,initial.current,relations.current,batch.current,visibleBatch.current,visibleAdjust.current,reference.current].filter((item):item is BusinessEditorState=>item!==null) as WorkspaceEditor[]),url=useWorkspaceLocation(guard.request);
 const rawTab=url.query.get('tab')??initialTab??'characters',tab=SETTING_TABS.some(item=>item.key===rawTab)?rawTab as SettingTab:'characters',search=url.query.get('q')??'',selectedId=url.query.get('selected')??'',typeId=url.query.get('type')??'',creating=url.query.get('new')==='1',detail=url.query.get('detail')??(creating?'basic':['characters','world'].includes(tab)?'overview':'basic');
 const receiveEditor=useCallback((state:BusinessEditorState)=>{editor.current=state;setFlags({dirty:state.dirty,locked:state.locked});},[]),receiveInitial=useCallback((state:WorkspaceEditor)=>{initial.current=state;},[]),receiveRelations=useCallback((state:WorkspaceEditor)=>{relations.current=state;},[]);
 const load=async()=>{const seq=++generation.current;try{const nextBook=await newDesignApi.getBook(bookId);const [nextTypes,nextWorkspace]=await Promise.all([newDesignApi.listCardTypes(nextBook.spaceId),newDesignApi.getBookViewWorkspace(bookId)]);if(seq!==generation.current)return;if(nextBook.id!==bookId||nextWorkspace.bookId!==bookId||nextWorkspace.spaceId!==nextBook.spaceId)throw new Error('故事设定来源不属于本书。');setBook(nextBook);setTypes(nextTypes);setWorkspace(nextWorkspace);setError('');}catch(reason){if(seq===generation.current)setError(reason instanceof Error?reason.message:'故事设定未读取。');}};
 useEffect(()=>{void load();return()=>{generation.current++;};},[bookId]);
 const ownTypes=types.filter(item=>item.status==='published'&&item.currentVersionId&&settingTabForType(item.key)===tab),cards=(workspace?.cards??[]).filter(item=>item.status==='active'&&settingTabForType(item.typeKey)===tab),selected=cards.find(item=>item.id===selectedId),currentType=ownTypes.find(item=>item.id===(selected?.cardTypeId??typeId))??(!selectedId&&!typeId?ownTypes[0]:undefined);
 useEffect(()=>{editor.current=null;initial.current=null;relations.current=null;setInitialFields([]);if(!book||!selected)return;let active=true;void Promise.all([newDesignApi.getStateCapabilities(book.spaceId),newDesignApi.listCardTypeVersions(selected.cardTypeId),newDesignApi.listScopedFields(book.id,selected.cardTypeId,selected.id)]).then(([capabilities,versions,scoped])=>{if(!active)return;const capability=capabilities.types.find(item=>item.typeKey===selected.typeKey),version=versions.find(item=>item.id===types.find(type=>type.id===selected.cardTypeId)?.currentVersionId);const fields=[...(version?.fields??[]),...scoped.definitions.filter(item=>item.status==='active').map(item=>item.currentVersion.field)];setInitialFields([...new Map(fields.map(field=>[field.key,field])).values()].filter(field=>{const policy=capability?.fieldPolicies.find(item=>item.fieldKey===field.key)?.settlementPolicy??capability?.defaultFieldPolicy;return !!capability&&policy!==undefined&&policy!=='none'&&policy!=='derived'&&!field.hidden;}));}).catch(reason=>{if(active)setError(`初始状态规格未读取：${reason instanceof Error?reason.message:'请重新读取来源'}`);});return()=>{active=false;};},[book?.id,selectedId,tab,creating]);
 const change=(patch:Record<string,string|null>)=>url.update(patch,()=>{editor.current=null;initial.current=null;relations.current=null;});
 const ambiguous=hasAmbiguousNavigation(url.query);
 const returnTo=safePlanningReturn(bookId,url.query.get('returnTo'));
 if(!book)return <div className="nd-shell"><p role={error?'alert':'status'}>{error||'正在读取故事设定…'}</p>{error&&<button className="nd-button" onClick={()=>void load()}>重新读取</button>}</div>;
 return <BookShell compact book={book} active="story-setting"><main className="nd-story-workspace nd-story-setting"><header className="nd-story-heading"><h2>② 故事设定 <Help label="故事设定">在同一本书中维护人物、世界和其他资料。人工填写与 AI 候选采用到同一标准表单，保存后才成为正式档案。</Help></h2><div className="nd-row-actions">{returnTo&&<a className="nd-button" href={returnTo}>返回原规划位置</a>}<a className="nd-button nd-button-primary" href={`/new-design/books/${bookId}/planning`}>进入故事规划</a></div></header>
 {guard.dialog}{ambiguous&&<p role="alert">来源参数重复，不能编辑；请从本书目录重新选择。</p>}{error&&<p className="nd-message is-error" role="alert">{error}</p>}
 <nav className="nd-story-tabs" aria-label="设定分类">{SETTING_TABS.map(item=><button type="button" key={item.key} aria-pressed={item.key===tab} onClick={()=>change({tab:item.key,selected:null,type:null,new:null,detail:'basic',relation:null})}>{item.label}</button>)}</nav>
 <div className="nd-story-toolbar"><label>搜索对象<input value={search} onChange={event=>url.update({q:event.target.value})} placeholder="按名称搜索"/></label><label>内容类型<select value={currentType?.id??''} onChange={event=>change({type:event.target.value,selected:null,new:null})}><option value="">选择类型</option>{ownTypes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="nd-button" disabled={!currentType} onClick={()=>change({new:'1',selected:null,type:currentType?.id??null})}>新增</button><button className="nd-button nd-button-primary" disabled={!(["basic","visible"].includes(detail))||!editor.current||flags.locked||!flags.dirty} onClick={()=>void editor.current?.save?.()}>保存</button><button type="button" className="nd-button" disabled={ambiguous||!currentType} onClick={()=>guard.request(()=>setBatchOpen(true))}>AI 准备本组设定</button></div>
 <BatchAiPanel initialRequestKey={!url.query.has("batchMode")?url.query.get("batch"):null} bookId={bookId} seed={{mode:'setting',typeIds:ownTypes.map(item=>item.id),newTypeId:currentType?.id??''}} open={batchOpen} onClose={()=>setBatchOpen(false)} onState={receiveBatch} onRequest={guard.request} onLoad={draft=>{const target=draft.slot.target;if(!target)return;setBatchDraft(draft);url.commit({tab:settingTabForType(types.find(type=>type.id===target.cardTypeId)?.key??''),selected:target.cardId,type:target.cardTypeId,new:target.cardId?null:'1',detail:'basic'},true);}}/>
 <div className={`nd-story-setting-layout${tab==='characters'?' is-character':tab==='world'?' is-world':''}`}><aside className="nd-story-index" aria-label="设定对象索引">{tab==='characters'?<CastIndex cards={cards} search={search} selectedId={selectedId} onSelect={item=>change({selected:item.id,type:item.cardTypeId,new:null,detail:'overview',relation:null})}/>:<>{cards.filter(item=>item.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(item=><button key={item.id} className={item.id===selectedId?'is-selected':''} aria-pressed={item.id===selectedId} onClick={()=>change({selected:item.id,type:item.cardTypeId,new:null,detail:tab==='world'?'overview':'basic',relation:null})}><strong>{item.title}</strong><small>{item.cardTypeName}</small></button>)}{!cards.length&&<p>本分类尚无资料，请选择内容类型后新增。</p>}</>}{tab==='world'&&selected&&!creating&&<nav className="nd-world-handbook-tabs" aria-label="世界手册">{WORLD_DETAILS.map(([key,label])=><button key={key} aria-pressed={detail===key} onClick={()=>url.update({detail:key},()=>{initial.current=null;relations.current=null;})}>{label}</button>)}</nav>}</aside>
 <section className="nd-story-detail">{ambiguous?<p>原来源未确认。</p>:selectedId&&!selected?<p role="alert">指定对象不在本书此分类中；未自动改选其他资料。</p>:!selected&&!creating?<p>选择左侧对象，或新增一项设定。</p>:currentType?<>{selected&&<SelectedSummary card={selected}/>}{(tab!=='world'||creating)&&<nav className="nd-story-tabs" aria-label="对象详情">{(creating?(currentType.key==='character'?[['basic','档案'],['visible','外显']]:[['basic','档案']]):selected?.typeKey==='character'?CHARACTER_DETAILS:tab==='world'?WORLD_DETAILS:[['basic','基础资料'],['initial','初始状态']]).map(([key,label])=><button key={key} aria-pressed={detail===key} onClick={()=>{if(['basic','visible'].includes(detail)&&['basic','visible'].includes(key))url.commit({detail:key});else url.update({detail:key},()=>{initial.current=null;relations.current=null;});}}>{label}</button>)}</nav>}
 {tab==='characters'&&detail==='visible'&&selected&&!creating&&<section className="nd-visible-generation"><header className="nd-section-heading"><h3>外显资料生成 <Help label="外显资料">根据本书已发布外显字段准备外貌、体态、声音与登场记忆点；先比较候选，勾选后在标准表单确认保存。已有内容默认保留。</Help></h3><div className="nd-row-actions"><button className="nd-button" disabled={visibleBusy.prepare||visibleBusy.adjust} onClick={()=>guard.request(()=>{setVisibleMode('visible_prepare');setVisibleIds([selected.id]);setVisibleOpen(true);setPrepareNonce(crypto.randomUUID());})}>{visibleBusy.prepare?'生成中…':'AI 补全外显资料'}</button><button className="nd-button" disabled={visibleBusy.prepare||visibleBusy.adjust||cards.length>20} onClick={()=>guard.request(()=>{setVisibleMode('visible_prepare');setVisibleIds(cards.map(card=>card.id));setVisibleOpen(true);setPrepareNonce(crypto.randomUUID());})}>批量补全角色外显资料</button><button className="nd-button" disabled={visibleBusy.prepare||visibleBusy.adjust} onClick={()=>guard.request(()=>{setVisibleMode('visible_adjust');setVisibleIds([selected.id]);setVisibleOpen(true);setAdjustNonce(crypto.randomUUID());})}>{visibleBusy.adjust?'调整中…':'AI 调整外显资料'}</button></div></header><textarea rows={3} maxLength={2000} disabled={visibleBusy.prepare||visibleBusy.adjust} value={visibleGuidance} onChange={event=>setVisibleGuidance(event.target.value)} placeholder="补全倾向（可选）：例如更有压迫感、声音更温和、保留已有外貌"/></section>}
 <div className="nd-visible-candidates" hidden={detail!=='visible'&&!visibleBusy.prepare&&!visibleBusy.adjust}>{(["visible_prepare","visible_adjust"] as const).map(mode=><BatchAiPanel key={mode} initialRequestKey={url.query.get("batchMode")===mode?url.query.get("batch"):null} bookId={bookId} seed={{mode,cardIds:visibleIds}} generationNonce={mode==='visible_prepare'?prepareNonce:adjustNonce} instructionSeed={visibleGuidance} hidePreparationControls onBatchSaved={async()=>{await load();setMaterialEpoch(value=>value+1);}} open={visibleOpen&&mode===visibleMode} onClose={()=>setVisibleOpen(false)} onState={mode==="visible_prepare"?receiveVisible:receiveVisibleAdjust} onRequest={guard.request} onLoad={draft=>{const target=draft.slot.target;if(!target)return;setBatchDraft(draft);url.commit({tab:'characters',selected:target.cardId,type:target.cardTypeId,new:null,detail:'visible'},true);}}/>)}</div>
 <div hidden={!['basic','visible'].includes(detail)}><BusinessFormWorkspace key={`${tab}:${selectedId}:${currentType.id}:${creating}:${materialEpoch}`} compact embedded fieldSection={selected?.typeKey==='character'||currentType.key==='character'?detail==='visible'?'visible':'profile':undefined} batchDraft={batchDraft} book={book} cardTypes={ownTypes} scope="all" initialCardId={selected?.id} initialTypeId={currentType.id} startCreating={creating} onEditorStateChange={receiveEditor} onSavedReceipt={receipt=>{setBatchDraft(undefined);setWorkspace(current=>current?{...current,cards:[...current.cards.filter(item=>item.id!==receipt.card.id),{...receipt.card,typeKey:currentType.key,typeFields:selected?.typeFields??currentType.draftFields}]}:current);url.commit({selected:receipt.card.id,type:receipt.card.cardTypeId,new:null},true);}} onSaved={load}/></div>
 {detail==='relations'&&selected&&<><a className="nd-button" href={`/new-design/books/${book.id}/professional-views?view=relationships&selected=${selected.id}`}>查看{selected.title}的关系图</a><Relations key={selected.id} book={book} card={selected} onState={receiveRelations} selected={url.query.get("relation")??""} onSelection={id=>url.update({relation:id})}/></>}
 {detail==='initial'&&selected&&<InitialStates key={selected.id} bookId={bookId} subjectId={selected.id} fields={initialFields} onState={receiveInitial}/>}
 {selected&&workspace&&['overview','resources','timeline','dynamics','intelligence','rules','guidance','usage','sync'].includes(detail)&&<ReferenceDetail key={selected.id} book={book} card={selected} workspace={workspace} detail={detail} onState={receiveReference} onRequest={guard.request} experienceBatch={url.query.get("experienceBatch")} onEdit={item=>change({tab:settingTabForType(item.typeKey),selected:item.id,type:item.cardTypeId,new:null,detail:'basic',relation:null})}/>}
 {!['basic','visible','relations','initial','overview','resources','timeline','dynamics','intelligence','rules','guidance','usage','sync'].includes(detail)&&<p role="alert">详情位置无效，请选择上方页签；填写保留。</p>}
 </>:<p role="alert">此类型缺少已发布标准表单；请核对本书内容配置。</p>}</section></div>
 </main></BookShell>;
}
