import {randomUUID} from 'node:crypto';
import {classificationWriteSchema,classificationSchema,EMPTY_CLASSIFICATION,PLATFORM_CHOICES,type ClassificationWorkspace} from '../../../common/bookClassification';
import type {FieldDefinition} from '../../../common/contracts';
import {updateAuthorMaterialInTransaction,readAuthorMaterialWriteReceipt} from '../authorMaterials';
import {getNewDesignPool} from '../runtime';
import {formHash} from '../formAssist';
import {NewDesignError,assertFound} from '../../domain/errors';
import type {PoolClient} from 'pg';
export class ClassificationWriteError extends NewDesignError {readonly recovery;constructor(bookId:string,message:string,status:number,outcome:'unknown'|'not_written'){super(message,status);this.recovery={failedStep:'保存作品分类',summary:message,savedResult:'完整填写与原请求保留；只读核对原卡片保存回执。',sourceRoute:`/new-design/books/${bookId}/overview#classification`,actionLabel:'返回作品分类',mutationOutcome:outcome};}}
const keys={publicationStatus:'publication_status',writingMode:'writing_mode',platform:'writing_platform_preference',creationExperience:'creation_experience'} as const;
const select=`SELECT card.* FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id JOIN new_design.books book ON book.space_id=card.space_id WHERE book.id=$1 AND card.status='active' AND type.type_key='project_rule' ORDER BY card.id`;
export function readClassification(values:Record<string,unknown>){const value=Object.fromEntries(Object.entries(keys).map(([name,key])=>[name,values[key]??null])),parsed=classificationSchema.safeParse(value);if(!parsed.success)throw new NewDesignError('作品分类原值不符合约定，请到作品约定核对，不能推断替代分类。',409);return parsed.data;}
export async function classificationValues(client:PoolClient,cardId:string){const rows=(await client.query('SELECT definition.field_key,local.value FROM new_design.cards card JOIN new_design.card_version_local_values local ON local.card_version_id=card.current_version_id JOIN new_design.field_definitions definition ON definition.id=local.field_definition_id WHERE card.id=$1',[cardId])).rows;return Object.fromEntries(rows.map(row=>[row.field_key,row.value]));}
export async function readBookClassification(bookId:string):Promise<ClassificationWorkspace>{const client=await(await getNewDesignPool()).connect();try{await client.query('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');assertFound((await client.query('SELECT id FROM new_design.books WHERE id=$1',[bookId])).rows[0],'本书不存在。');const cards=(await client.query(select,[bookId])).rows;const card=cards.length===1?cards[0]:null,result={bookId,cardId:card?.id??null,revision:card?Number(card.revision):null,classification:card?readClassification({...card.values,...await classificationValues(client,card.id)}):{...EMPTY_CLASSIFICATION},issue:cards.length===1?null:cards.length?'本书有多份作品约定，请先明确保留一份书级约定。':'请先在故事设定创建本书作品约定，再设置分类。'};await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
export async function saveBookClassification(bookId:string,raw:unknown){const input=classificationWriteSchema.parse(raw),original=await readAuthorMaterialWriteReceipt(bookId,input.requestKey);if(original){const card=original.card,local=original.localValues;if(card.id!==input.cardId||card.revision!==input.expectedRevision+1||formHash(readClassification({...card.values,...local}))!==formHash(input.classification))throw new NewDesignError('原分类请求用于不同输入，请保留原回执。',409);return original;}
 const client=await(await getNewDesignPool()).connect();let committing=false,absent=false;try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`author-material:${bookId}:${input.requestKey}`]);const replay=(await client.query('SELECT author_write_receipt receipt FROM new_design.card_versions WHERE author_book_id=$1 AND author_request_key=$2',[bookId,input.requestKey])).rows[0]?.receipt;if(replay){if(replay.card.id!==input.cardId||replay.card.revision!==input.expectedRevision+1||formHash(readClassification({...replay.card.values,...replay.localValues}))!==formHash(input.classification))throw new NewDesignError('原分类请求输入不一致。',409);committing=true;await client.query('COMMIT');return replay;}absent=true;assertFound((await client.query("SELECT id FROM new_design.books WHERE id=$1 AND status='active' FOR UPDATE",[bookId])).rows[0],'本书不存在或已归档。');const cards=(await client.query(select+' FOR UPDATE OF card',[bookId])).rows,card=assertFound(cards.length===1&&cards[0].id===input.cardId?cards[0]:null,'作品约定来源已变化，请重新读取。');if(Number(card.revision)!==input.expectedRevision)throw new NewDesignError('作品约定修订已变化，分类填写保留。',409);
 const localValues=await classificationValues(client,card.id),fields=(await client.query('SELECT fields FROM new_design.card_type_versions WHERE id=$1',[card.type_version_id])).rows[0].fields as FieldDefinition[];
 const definitions:Array<[keyof typeof keys,string,ReadonlyArray<readonly[string,string]>]>=[['publicationStatus','作品发布分类',[['draft','草稿'],['published','已发布']]],['writingMode','原创或续写',[['original','原创'],['continuation','续写']]],['platform','写作平台偏好',PLATFORM_CHOICES],['creationExperience','默认创作体验',[['simple','简易创作'],['professional','专业工作台']]]];
 for(const[name,label,choices]of definitions){const key=keys[name],base=fields.find(field=>field.key===key);if(base){if(base.type!=='select'||choices.some(([value])=>!base.options.some(option=>option.value===value)))throw new NewDesignError('现有作品约定字段与分类语义不一致，请核对字段规格。',409);continue;}const existing=(await client.query('SELECT definition.id,version.field_schema FROM new_design.field_definitions definition JOIN new_design.field_definition_versions version ON version.id=definition.current_version_id WHERE definition.card_id=$1 AND definition.field_key=$2 AND definition.status=\'active\'',[card.id,key])).rows[0];if(existing){if(existing.field_schema.type!=='select'||choices.some(([value])=>!existing.field_schema.options.some((option:{value:string})=>option.value===value)))throw new NewDesignError('原补充字段与分类语义不一致，请核对原规格。',409);continue;}const id=randomUUID(),version=randomUUID(),field:FieldDefinition={key,name:label,description:name==='publicationStatus'?'作者维护的草稿或已发布分类；不执行外部发布。':'作者明确选择的创作偏好。',type:'select',required:false,defaultValue:null,options:choices.map(([value,label])=>({value,label})),group:'作品分类',order:100,aiSuggestible:false,stateSettlement:'none'};await client.query("INSERT INTO new_design.field_definitions(id,space_id,card_type_id,card_id,field_key,origin,scope,created_by) VALUES($1,$2,$3,$4,$5,'local_supplement','card','book_classification')",[id,card.space_id,card.card_type_id,card.id,key]);await client.query("INSERT INTO new_design.field_definition_versions(id,field_definition_id,version,field_schema,created_by) VALUES($1,$2,1,$3::jsonb,'book_classification')",[version,id,JSON.stringify(field)]);await client.query('UPDATE new_design.field_definitions SET current_version_id=$2 WHERE id=$1',[id,version]);await client.query("INSERT INTO new_design.field_scope_adoptions(id,field_definition_id,action,idempotency_key,to_version_id,expected_subject_revision,impact,created_by) VALUES($1,$2,'create',$3,$4,$5,$6::jsonb,'book_classification')",[randomUUID(),id,`${input.requestKey}:field:${key}`,version,input.expectedRevision,JSON.stringify({originalInput:input,field})]);}
 const values={...card.values};for(const[name,key]of Object.entries(keys)){const value=input.classification[name as keyof typeof keys];if(fields.some(field=>field.key===key))values[key]=value;else localValues[key]=value;}
 const version=(await client.query('SELECT form_version_id,form_resolution_kind FROM new_design.card_versions WHERE id=$1',[card.current_version_id])).rows[0],receipt=await updateAuthorMaterialInTransaction(client,bookId,card.id,{requestKey:input.requestKey,cardTypeId:card.card_type_id,revision:input.expectedRevision,title:card.title,values,localValues,formVersionId:version.form_version_id,formResolutionKind:version.form_resolution_kind});committing=true;await client.query('COMMIT');return receipt;
 }catch(error){let ack=false;try{await client.query('ROLLBACK');ack=true;}catch{}throw new ClassificationWriteError(bookId,error instanceof NewDesignError?error.message:'原分类保存回执未确认，保留原键只读核对。',error instanceof NewDesignError?error.status:503,absent&&!committing&&ack?'not_written':'unknown');}finally{client.release();}}
