import {readCardLocalSnapshot} from '../fieldExtensions/localValues';
import {insertProductionRecords,updateProductionRecords} from './persistence';
import {chapterWritingRequestRows,planningObjectRows,planningVersionReferenceRows,planningVersionRows} from './persistence';
import {readActiveCharacterAuthorGuidance,influenceCapability} from "../characterAuthor/influences";
import {randomUUID} from "node:crypto";
import {readStoryFormat} from '../../../common/storyFormat';
export {readChapterContinuitySources,type ChapterContinuitySource,type ChapterContinuitySources} from './continuitySources';
import type {PoolClient} from "pg";
import type {ChapterGenerationOutput,ChapterKnowledgeSelection} from "../../../common/productionDirector";
import {readChapterContinuitySources} from './continuitySources';
import {readChapterKnowledgeSources} from './knowledgeSources';
import type {ChapterWritingRequest,ChapterWritingOperation} from "../../../common/contracts";
import {NewDesignError,assertFound} from "../../domain/errors";
import {getNewDesignPool} from "../runtime";
import {stableHash} from "../aiContracts";
import {preparePrompt,type ChapterGenerationInput} from "../../ai/prompts";
import {freezeControlledChapter,type ControlledChapterSnapshot} from "../controlledTaskSnapshot";
import {getChapterWritingRequest} from "../chapterWriting";
import {getAdoptedChapterPlanContractInTransaction} from '../planning';
import {readActiveWorldUsageScopes} from '../worldUsage';
import {worldUsageCreativeScopes} from '../../../common/worldUsage';
import {lockOriginalChapterExecution,finishKnownChapterFailure,endExpiredOriginalChapter,endSavedReplyOriginalChapter,retainOriginalChapterUsage} from './ledger';
export {endExpiredOriginalChapter} from './ledger';
export interface ChapterProductionInput {requestKey:string;bookId:string;chapterCardId:string;planningObjectId:string;planningVersionId:string;expectedPlanningRevision:number;documentId:string;expectedDocumentRevision:number;instruction:string;issuePolicy:"completion_first"|"quality_first";operation?:Exclude<ChapterWritingOperation,'manual_draft'|'copy'>;baseBodyVersionId?:string|null;selectionStart?:number|null;selectionEnd?:number|null;commandHash?:string;actor?:'user'|'production_director';knowledgeSources?:ChapterKnowledgeSelection[];excludedMaterialIds?:string[];sourcePreviewHash?:string;}
export interface SelectedChapterProductionInput {operationKind:Exclude<ChapterWritingOperation,'manual_draft'|'copy'>;baseBodyVersionId?:string|null;selectionStart?:number|null;selectionEnd?:number|null;instruction?:string;expectedRevision:number;idempotencyKey:string;createdBy?:string;knowledgeSources?:ChapterKnowledgeSelection[];excludedMaterialIds?:string[];sourcePreviewHash?:string;}
type Row=Record<string,unknown>;
export {prepareSelectedChapterProduction} from './selectedChapter';
export class ChapterProductionError extends NewDesignError {constructor(message:string,status:number,readonly mutationOutcome:"not_written"|"unknown",issues?:Record<string,string>){super(message,status,issues);}}
async function transaction<T>(work:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await getNewDesignPool().then(pool=>pool.connect()).catch(()=>{throw new ChapterProductionError('数据库连接未建立，本次数据库动作未提交；原请求、已保存回复和稿件保留，请打开运行维护。',503,'not_written');});let committing=false;try{await client.query("BEGIN");const value=await work(client);committing=true;await client.query("COMMIT");return value;}catch(error){let ack=false;try{await client.query("ROLLBACK");ack=true;}catch{}throw new ChapterProductionError(error instanceof NewDesignError?error.message:"章节生成凭证未确认，请保留原请求并只读核对。",error instanceof NewDesignError?error.status:503,ack&&!committing?"not_written":"unknown",error instanceof NewDesignError?error.issues:undefined);}finally{client.release();}}
const lock=(client:PoolClient,key:string)=>client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`chapter-production:${key}`]);

export async function readChapterGenerationSources(client:PoolClient,input:ChapterProductionInput,preview=false){
    const document=assertFound((await client.query(`SELECT document.*,book.name,book.space_id FROM new_design.chapter_documents document JOIN new_design.books book ON book.id=document.book_id AND book.status='active' WHERE document.id=$1 AND document.book_id=$2 AND document.chapter_card_id=$3 AND document.status='active' ${preview?'':'FOR UPDATE OF document'}`,[input.documentId,input.bookId,input.chapterCardId])).rows[0],"本书目标章档案不可用，请返回章节创作核对。");
    if(Number(document.revision)!==input.expectedDocumentRevision)throw new NewDesignError("目标章稿件发生变化，本次未生成；请核对现有候选后再准备。",409);
    if((await client.query(`SELECT id FROM ${chapterWritingRequestRows} chapter_writing_request_rows_record WHERE chapter_document_id=$1 AND status IN ('preparing','queued','running')`,[document.id])).rowCount)throw new NewDesignError("目标章已有未确认的生成请求，请先核对原结果。",409);
    const ancestors=(await client.query(`WITH RECURSIVE ancestors AS (SELECT object.*,ARRAY[object.id] path FROM ${planningObjectRows} object WHERE object.id=$1 AND object.book_id=$2 UNION ALL SELECT parent.*,child.path||parent.id FROM ${planningObjectRows} parent JOIN ancestors child ON child.parent_object_id=parent.id WHERE parent.book_id=$2 AND cardinality(child.path)<4 AND NOT parent.id=ANY(child.path)) SELECT object.id,object.level,object.title,object.card_id,object.parent_object_id,object.status,object.revision,object.adopted_version_id,version.status version_status,version.content_hash,version.content,version.stale_at FROM ancestors object LEFT JOIN ${planningVersionRows} version ON version.id=object.adopted_version_id AND version.object_id=object.id`,[input.planningObjectId,input.bookId])).rows;
    const ancestorChapter=ancestors.find(plan=>plan.id===input.planningObjectId&&plan.level==='chapter'),volume=ancestors.find(plan=>plan.level==='volume'),story=ancestors.find(plan=>plan.level==='story');
    if(ancestors.length!==3||!ancestorChapter||!volume||!story||ancestorChapter.parent_object_id!==volume.id||volume.parent_object_id!==story.id||story.parent_object_id!==null||ancestors.some(plan=>plan.status!=='active'||plan.version_status!=='adopted'||!plan.adopted_version_id||!plan.content_hash||plan.stale_at))throw new NewDesignError("本章、所属卷或全书总计划未完整采用，或上级关系已变化；请回故事规划逐层核对后再生成。",409);
    const format=readStoryFormat((story.content as Record<string,unknown>).storyFormat);
    if((story.content as Record<string,unknown>).storyFormat!==undefined&&!format)throw new NewDesignError('采用故事总纲的作品形式或目标字数无效，请回原规划核对；本次未生成正文。',409);
    if(format?.form==='short_story'&&Number((await client.query(`SELECT count(*) total FROM ${planningObjectRows} planning_object_rows_record WHERE book_id=$1 AND status='active' AND level='chapter'`,[input.bookId])).rows[0].total)!==1)throw new NewDesignError('短篇须由唯一正文计划承载整篇，请回故事规划核对；本次未生成或改变已有正文。',409);
    const scenes=(await client.query(`SELECT scene.id,scene.level,scene.title,scene.card_id,scene.revision,scene.adopted_version_id,version.status version_status,version.content_hash,version.content,version.stale_at FROM ${planningObjectRows} scene LEFT JOIN ${planningVersionRows} version ON version.id=scene.adopted_version_id AND version.object_id=scene.id WHERE scene.parent_object_id=$1 AND scene.book_id=$2 AND scene.level='scene' AND scene.status='active' ORDER BY scene.sort_order,scene.id LIMIT 301`,[input.planningObjectId,input.bookId])).rows;
    if(scenes.length>297||scenes.some(scene=>scene.version_status!=='adopted'||!scene.adopted_version_id||!scene.content_hash||scene.stale_at))throw new NewDesignError("本章存在未采用、已失效或超过完整冻结范围的场景计划，请在故事规划核对；不会遗漏场景后生成。",409);
    const plans=[story,volume,ancestorChapter,...scenes];
    const adopted=await getAdoptedChapterPlanContractInTransaction(client,input.bookId,input.chapterCardId);
    if(adopted.planningObjectId!==input.planningObjectId||adopted.planningVersionId!==input.planningVersionId||adopted.planningObjectRevision!==input.expectedPlanningRevision||adopted.basedOnVolumePlanVersionId!==volume.adopted_version_id)throw new NewDesignError('本章计划依据的卷版本与当前采用版本不一致，请回故事规划核对后再生成。',409);
    const references=(await client.query(`SELECT reference.*,type.type_key,version.title,version.values,plan.execution_mode FROM ${planningVersionReferenceRows} reference JOIN new_design.card_versions version ON version.id=reference.card_version_id AND version.card_id=reference.card_id JOIN new_design.cards card ON card.id=version.card_id AND card.space_id=$1 AND card.status='active' JOIN new_design.card_types type ON type.id=card.card_type_id AND NOT type.is_internal JOIN ${planningVersionRows} plan ON plan.id=reference.planning_version_id WHERE reference.book_id=$2 AND reference.planning_version_id=ANY($3::uuid[]) ORDER BY reference.planning_version_id,reference.reference_role,reference.sort_order,reference.id LIMIT 301`,[document.space_id,input.bookId,plans.map(plan=>plan.adopted_version_id)])).rows;
    if(references.some(reference=>reference.type_key==='character_author_guidance'))throw new NewDesignError('谈话创作指导不是规划的正式事实引用，请移除这项直接引用；仅从有效人物范围进入生成来源预览。',422);
    const referenceCount=Number((await client.query(`SELECT count(*) total FROM ${planningVersionReferenceRows} planning_version_reference_rows_record WHERE book_id=$1 AND planning_version_id=ANY($2::uuid[])`,[input.bookId,plans.map(plan=>plan.adopted_version_id)])).rows[0].total);
    if(referenceCount!==references.length||referenceCount>300)throw new NewDesignError('已采用规划的精确资料引用未完整读取或超过冻结范围，不能用当前另一版资料代替。',409);
    for(const reference of references)reference.values={...reference.values,...Object.fromEntries((await readCardLocalSnapshot(client,String(reference.card_version_id))).map(value=>[value.field_key,value.value]))};
    const modes=(await client.query(`SELECT id,execution_mode FROM ${planningVersionRows} planning_version_rows_record WHERE id=ANY($1::uuid[])`,[plans.map(plan=>plan.adopted_version_id)])).rows;
    const chapter=assertFound(plans.find(plan=>plan.id===input.planningObjectId&&plan.level==='chapter'&&plan.card_id===input.chapterCardId),"目标章未采用正式计划。");
    if(chapter.adopted_version_id!==input.planningVersionId||Number(chapter.revision)!==input.expectedPlanningRevision||plans.some(plan=>plan.stale_at))throw new NewDesignError("本章或上级已采用计划已变化，需要回故事规划核对后再生成。",409);
    const cards=(await client.query(`SELECT card.id,card.title,card.current_version_id,version.values,type.name type_name,type.type_key FROM new_design.cards card JOIN new_design.card_versions version ON version.id=card.current_version_id JOIN new_design.card_types type ON type.id=card.card_type_id AND NOT type.is_internal WHERE card.space_id=$1 AND card.status='active' AND type.type_key<>'character_author_guidance' ORDER BY card.id LIMIT 301`,[document.space_id])).rows;
    for(const card of cards)card.values={...card.values,...Object.fromEntries((await readCardLocalSnapshot(client,String(card.current_version_id))).map(value=>[value.field_key,value.value]))};
    if(cards.length>300)throw new NewDesignError("本书资料超过本次完整冻结范围，请先配置适用范围，不能静默截断后生成。",422);
    const participantVersions=new Set([ancestorChapter.adopted_version_id,...scenes.map(scene=>scene.adopted_version_id)]),participantIds=references.filter(reference=>participantVersions.has(reference.planning_version_id)&&['participant','viewpoint'].includes(reference.reference_role)).map(reference=>String(reference.card_id));
    const guidance=await readActiveCharacterAuthorGuidance(client,input.bookId,Number(document.logical_order),participantIds);cards.push(...guidance);
    if(cards.length>300)throw new NewDesignError("\u672c\u4e66\u8d44\u6599\u53ca\u9002\u7528\u521b\u4f5c\u6307\u5bfc\u8d85\u8fc7\u5b8c\u6574\u51bb\u7ed3\u8303\u56f4\uff0c\u672a\u622a\u65ad\u540e\u751f\u6210\u3002",422);
    const continuity=await readChapterContinuitySources(client,input.bookId,input.chapterCardId),knowledge=await readChapterKnowledgeSources(client,input.bookId,input.knowledgeSources),worldScopes=await readActiveWorldUsageScopes(client,input.bookId);
    const base=input.actor==='user'?input.baseBodyVersionId:document.adopted_version_id;
    const body=base?assertFound((await client.query("SELECT id,content_hash,content FROM new_design.chapter_body_versions WHERE id=$1 AND chapter_document_id=$2 AND archived_at IS NULL",[base,document.id])).rows[0],"本章输入正文的精确版本未读取到，不能当作空正文生成。"):null;
    const operation=input.operation??'regenerate',start=input.selectionStart??null,end=input.selectionEnd??null;
    if(operation!=='regenerate'&&!body)throw new NewDesignError('该操作需要本章已保存输入正文，请先选择真实候选版本。',422);
    if((start===null)!==(end===null)||start!==null&&(!body||start<0||end!<=start||end!>String(body.content).length)||operation==='continue'&&start!==null)throw new NewDesignError('选区与原输入正文不一致；续写请选择整章来源，不使用局部选区。',422);
    const promptInput:ChapterGenerationInput={bookId:input.bookId,bookName:String(document.name),chapterCardId:input.chapterCardId,chapterTitle:String(chapter.title),operation,continuity,knowledge,
      plans:plans.map(plan=>({objectId:String(plan.id),versionId:String(plan.adopted_version_id),level:plan.level,contentHash:String(plan.content_hash),content:plan.content,executionMode:modes.find(mode=>mode.id===plan.adopted_version_id)?.execution_mode,references:references.filter(reference=>reference.planning_version_id===plan.adopted_version_id).map(reference=>({id:String(reference.id),role:reference.reference_role,cardId:String(reference.card_id),cardVersionId:String(reference.card_version_id),title:String(reference.title),contentHash:stableHash(reference.values),values:reference.values,action:reference.action_key??null,note:String(reference.note)}))})),
      materials:cards.map(card=>({cardId:String(card.id),versionId:String(card.current_version_id),title:String(card.title),typeName:String(card.type_name),values:card.values})),worldUsage:worldUsageCreativeScopes(worldScopes),body:body?{versionId:String(body.id),contentHash:String(body.content_hash),content:String(body.content)}:null,selection:start===null?null:{start,end:end!,text:String(body!.content).slice(start,end!)},instruction:input.instruction,issuePolicy:input.issuePolicy};
    const selectedWorldVersions=new Map<string,string>();
    for(const scope of worldScopes){selectedWorldVersions.set(scope.rootCardId,scope.sources.rootVersionId);const ids=new Set([...scope.selection.factionIds,...scope.selection.locationIds,...scope.selection.ruleIds]);for(const card of scope.sources.cards)if(ids.has(card.cardId))selectedWorldVersions.set(card.cardId,card.versionId);}
    const selectedWorldIds=new Set(selectedWorldVersions.keys());
    const worldTypeKeys=new Set(['world_setting','world_overview','faction','organization','location','world_rule','time_rule','power_system']);
    const inWorldScope=(card:Record<string,unknown>)=>!worldScopes.length||!worldTypeKeys.has(String(card.type_key))||selectedWorldIds.has(String(card.id));
    if(worldScopes.length&&references.some(reference=>worldTypeKeys.has(String(reference.type_key))&&selectedWorldVersions.get(String(reference.card_id))!==String(reference.card_version_id)))throw new NewDesignError('已采用规划引用的世界资料不在正式使用范围内，或并非本次采用的精确版本；本次未生成正文。',409);
    promptInput.materials=promptInput.materials.filter(card=>inWorldScope(cards.find(row=>String(row.id)===card.cardId)!));
    const sourceHash=stableHash(promptInput),required=new Set([...references.map(reference=>String(reference.card_id)),...cards.filter(card=>card.type_key==='project_rule').map(card=>String(card.id)),...selectedWorldIds]),excluded=new Set(input.excludedMaterialIds??[]);
    if(excluded.size!==(input.excludedMaterialIds??[]).length||[...excluded].some(id=>!cards.some(card=>card.id===id&&inWorldScope(card))||required.has(id)))throw new NewDesignError('只能排除本次范围内非规划必需的补充资料；正式计划引用不能删除。',422);
    if(input.sourcePreviewHash&&input.sourcePreviewHash!==sourceHash)throw new NewDesignError('本章生成来源已变化，请重新只读预览；原稿与选择保留，本次未调用模型。',409);
    const decisions=cards.map(card=>({cardId:String(card.id),versionId:String(card.current_version_id),title:String(card.title),required:required.has(String(card.id)),included:inWorldScope(card)&&!excluded.has(String(card.id))}));
    promptInput.materials=promptInput.materials.filter(card=>!excluded.has(card.cardId));
    return{document,chapter,body,operation,start,end,promptInput,sourceHash,decisions};
}

export async function prepareChapterProduction(input:ChapterProductionInput):Promise<{requestId:string;snapshot:ControlledChapterSnapshot;taskId:string;stepId:string;repeated:boolean}> {
  return transaction(async client=>{
    await client.query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ");
    await lock(client,`${input.bookId}:${input.requestKey}`);await lock(client,`book:${input.bookId}`);
    const requestHash=input.commandHash??stableHash(input),prior=(await client.query(`SELECT * FROM ${chapterWritingRequestRows} chapter_writing_request_rows_record WHERE book_id=$1 AND idempotency_key=$2`,[input.bookId,input.requestKey])).rows[0];
    if(prior){if(prior.request_hash!==requestHash||!prior.controlled_snapshot)throw new NewDesignError("原请求用于其他章节或输入，请核对原凭证。",409);const step=assertFound((await client.query("SELECT id FROM new_design.ai_task_steps WHERE task_id=$1 AND step_key='generate_candidate'",[prior.ai_task_id])).rows[0],"原章节步骤未读取。");return {requestId:String(prior.id),snapshot:prior.controlled_snapshot as ControlledChapterSnapshot,taskId:String(prior.ai_task_id),stepId:String(step.id),repeated:true};}
    const {document,chapter,body,operation,start,end,promptInput}=await readChapterGenerationSources(client,input);
    const requestId=randomUUID(),taskId=randomUUID(),stepId=randomUUID(),prompt=preparePrompt("chapter_generation",promptInput,(await influenceCapability(client)).operational?'v2':'v1'),snapshot=await freezeControlledChapter(client,requestId,promptInput,prompt);
    await client.query("INSERT INTO new_design.ai_tasks(id,space_id,book_id,task_key,task_contract_version_id,source_route,source_kind,source_id,request_idempotency_key,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,'chapter_writing_request',$7,$8,$9,$10)",[taskId,document.space_id,input.bookId,snapshot.taskKey,snapshot.taskContractVersionId,`/new-design/books/${input.bookId}/writing?chapter=${input.chapterCardId}`,requestId,`production:${input.requestKey}`,requestHash,input.actor??'production_director']);
    await client.query("INSERT INTO new_design.ai_task_steps(id,task_id,step_key,sort_order,max_attempts) VALUES($1,$2,'generate_candidate',0,1)",[stepId,taskId]);
    for(const kind of ['task','step'])await client.query("INSERT INTO new_design.ai_task_events(id,task_id,step_id,entity_kind,to_status,checkpoint_key,reason_code,reason_detail,actor_kind,actor,entity_revision) VALUES($1,$2,$3,$4,'queued','generate_candidate','controlled_chapter_prepared','按精确正式规划准备原请求，尚未生成或采用','user',$5,1)",[randomUUID(),taskId,kind==='task'?null:stepId,kind,input.actor??'production_director']);
    await insertProductionRecords(client, 'chapter_writing_request', `SELECT ($1)::uuid AS id,($2)::uuid AS book_id,($3)::uuid AS chapter_document_id,($19)::text AS operation_kind,($4)::uuid AS planning_object_id,($5)::uuid AS planning_version_id,($6)::char(64) AS planning_content_hash,($7)::uuid AS context_manifest_id,($8)::uuid AS task_contract_version_id,($9)::uuid AS prompt_recipe_version_id,($10)::uuid AS model_route_snapshot_id,($11)::uuid AS input_body_version_id,($12)::char(64) AS input_body_hash,($21)::integer AS selection_start,($22)::integer AS selection_end,($13)::text AS instruction,($14)::integer AS expected_document_revision,($15)::uuid AS ai_task_id,(NULL)::uuid AS result_body_version_id,('queued')::text AS status,('')::text AS error_summary,($16)::char(64) AS request_hash,($17)::text AS idempotency_key,($20)::text AS created_by,(now())::timestamptz AS created_at,(now())::timestamptz AS updated_at,($18::jsonb)::jsonb AS controlled_snapshot,(NULL)::jsonb AS controlled_output,(NULL)::jsonb AS controlled_execution`, [requestId,input.bookId,document.id,input.planningObjectId,input.planningVersionId,chapter.content_hash,snapshot.contextManifestId,snapshot.taskContractVersionId,snapshot.promptRecipeVersionId,snapshot.snapshotId,body?.id??null,body?.content_hash??null,input.instruction,input.expectedDocumentRevision,taskId,requestHash,input.requestKey,JSON.stringify(snapshot),operation,input.actor??'production_director',start,end], [["id"],["ai_task_id"],["book_id","idempotency_key"]]);
    return {requestId,snapshot,taskId,stepId,repeated:false};
  });
}
export async function readChapterProduction(bookId:string,requestId:string):Promise<{request:ChapterWritingRequest;output:ChapterGenerationOutput|null;execution:Record<string,unknown>|null;snapshot:ControlledChapterSnapshot;attemptId:string|null}> {
  const row=assertFound((await(await getNewDesignPool()).query(`SELECT request.*,step.current_attempt_id FROM ${chapterWritingRequestRows} request JOIN new_design.ai_task_steps step ON step.task_id=request.ai_task_id AND step.step_key='generate_candidate' WHERE request.book_id=$1 AND request.id=$2 AND request.controlled_snapshot IS NOT NULL`,[bookId,requestId])).rows[0],"本书原正文生成请求不存在。");
  return {request:await getChapterWritingRequest(requestId),output:row.controlled_output??null,execution:row.controlled_execution??null,snapshot:row.controlled_snapshot,attemptId:row.current_attempt_id??null};
}
export async function markChapterProductionRunning(bookId:string,id:string):Promise<void>{await transaction(async client=>{const row=await updateProductionRecords(client, 'chapter_writing_request', `SELECT to_jsonb(record) AS record_values,jsonb_build_object('status',('running')::text,'updated_at',(now())::timestamptz) AS record_patch FROM ${chapterWritingRequestRows} record WHERE id=$1 AND book_id=$2 AND status='queued' FOR UPDATE OF record`, [id,bookId], ["id"]);if(row.rowCount!==1)throw new NewDesignError("原章节请求已领取，不可重复生成。",409);});}
export async function retainChapterProductionOutput(bookId:string,id:string,attemptId:string,output:ChapterGenerationOutput,execution:Record<string,unknown>):Promise<void>{await transaction(async client=>{
  const row=await lockOriginalChapterExecution(client,bookId,id);
  if(row.controlled_output){if(stableHash(row.controlled_output)!==stableHash(output))throw new NewDesignError("已保存模型回复不可替换。",409);return;}
  if(row.status!=='running'||row.current_attempt_id!==attemptId||row.attempt_status!=='running'||row.step_status!=='running'||row.task_status!=='running'||!row.lease_expires_at||new Date(row.lease_expires_at).getTime()<=Date.now())throw new NewDesignError('正文原领取已结束或过期，迟到结果拒绝覆盖。',409);
  await updateProductionRecords(client, 'chapter_writing_request', `SELECT to_jsonb(record) AS record_values,jsonb_build_object('controlled_output',($2::jsonb)::jsonb,'controlled_execution',($3::jsonb)::jsonb,'updated_at',(now())::timestamptz) AS record_patch FROM ${chapterWritingRequestRows} record WHERE id=$1 FOR UPDATE OF record`, [id,JSON.stringify(output),JSON.stringify(execution)], ["id"]);
});}
export async function recordChapterProductionFailure(bookId:string,id:string,execution:Record<string,unknown>|null,message:string,unknown:boolean,category='unknown'):Promise<void>{await transaction(async client=>{const row=await lockOriginalChapterExecution(client,bookId,id);if(!['queued','running'].includes(row.status)||row.controlled_output)throw new NewDesignError('原请求已保存或结束，迟到失败拒绝覆盖。',409);if(!unknown)await finishKnownChapterFailure(client,row,execution??{},message.slice(0,2000),category);await updateProductionRecords(client, 'chapter_writing_request', `SELECT to_jsonb(record) AS record_values,jsonb_build_object('status',(CASE WHEN $4 THEN status ELSE 'failed' END)::text,'controlled_execution',($3::jsonb)::jsonb,'error_summary',($5)::text,'updated_at',(now())::timestamptz) AS record_patch FROM ${chapterWritingRequestRows} record WHERE book_id=$1 AND id=$2 AND status IN ('queued','running') AND controlled_output IS NULL FOR UPDATE OF record`, [bookId,id,execution?JSON.stringify(execution):null,unknown,message.slice(0,2000)], ["id"]);});}
export async function endExpiredChapterProduction(bookId:string,id:string){await transaction(async client=>{const row=await lockOriginalChapterExecution(client,bookId,id);if(row.status==='cancelled')return;if(!row.lease_expires_at||new Date(row.lease_expires_at).getTime()>Date.now())throw new NewDesignError('原章节领取没有过期证据，只能继续读取原请求。',409);await endExpiredOriginalChapter(client,bookId,id);});return getChapterWritingRequest(id);}
export async function endUnclaimedChapterProduction(bookId:string,id:string){
  await transaction(async client=>{const row=await lockOriginalChapterExecution(client,bookId,id);
    if(row.status==='cancelled'&&!row.current_attempt_id&&!row.controlled_output&&!row.result_body_version_id)return;
    if(row.status!=='queued'||row.step_status!=='queued'||row.task_status!=='queued'||row.current_attempt_id||row.controlled_output||row.result_body_version_id||(await client.query('SELECT id FROM new_design.ai_task_attempts WHERE task_id=$1 LIMIT 1',[row.ai_task_id])).rowCount)throw new NewDesignError('原请求已有领取、调用或回复，不能当作尚未执行取消；请只读核对对应原记录。',409);
    await endExpiredOriginalChapter(client,bookId,id);
  });return getChapterWritingRequest(id);
}
export async function endSavedReplyChapterProduction(bookId:string,id:string){await transaction(client=>endSavedReplyOriginalChapter(client,bookId,id));return getChapterWritingRequest(id);}
/** Complete bookkeeping for an already saved immutable candidate; never starts a new attempt. */
export async function completeChapterProductionLedger(bookId:string,id:string):Promise<void>{await transaction(async client=>{
  const original=await lockOriginalChapterExecution(client,bookId,id);
  const row=assertFound((await client.query(`SELECT request.*,step.id step_id,step.current_attempt_id,attempt.status attempt_status,body.content_hash FROM ${chapterWritingRequestRows} request JOIN new_design.ai_task_steps step ON step.task_id=request.ai_task_id AND step.step_key='generate_candidate' JOIN new_design.ai_task_attempts attempt ON attempt.id=step.current_attempt_id JOIN new_design.chapter_body_versions body ON body.id=request.result_body_version_id AND body.ai_attempt_id=attempt.id AND body.ai_task_id=request.ai_task_id WHERE request.book_id=$1 AND request.id=$2 AND request.controlled_output IS NOT NULL FOR UPDATE OF step,attempt`,[bookId,id])).rows[0],"本章已保存候选的运行来源未核对成功，请保留原请求。");
  if(row.attempt_status==='succeeded'){if(!(await client.query("SELECT id FROM new_design.ai_task_attempts WHERE id=$1 AND result_kind='chapter_body_version' AND result_stable_id=$2 AND result_version_id=$3 AND result_hash=$4",[row.current_attempt_id,row.chapter_document_id,row.result_body_version_id,row.content_hash])).rowCount)throw new NewDesignError('原成功运行回执与本章候选不一致，不能用其他成功记录代替。',409);return;}
  if(row.attempt_status!=='running'||original.step_status!=='running'||original.task_status!=='running')throw new NewDesignError("原尝试已结束或被接管，不能覆盖运行回执。",409);
  await client.query("UPDATE new_design.ai_task_attempts SET status='succeeded',result_kind='chapter_body_version',result_stable_id=$2,result_version_id=$3,result_hash=$4,ended_at=now() WHERE id=$1",[row.current_attempt_id,row.chapter_document_id,row.result_body_version_id,row.content_hash]);
  await client.query("UPDATE new_design.ai_task_steps SET status='succeeded',lease_token=NULL,lease_expires_at=NULL,revision=revision+1,completed_at=now(),updated_at=now() WHERE id=$1",[row.step_id]);
  await client.query("UPDATE new_design.ai_tasks SET status='succeeded',revision=revision+1,current_step_key=NULL,completed_at=now(),updated_at=now() WHERE id=$1",[row.ai_task_id]);
  for(const kind of ['attempt','step','task'])await client.query("INSERT INTO new_design.ai_task_events(id,task_id,step_id,attempt_id,entity_kind,from_status,to_status,checkpoint_key,reason_code,reason_detail,actor_kind,actor) VALUES($1,$2,$3,$4,$5,'running','succeeded','generate_candidate','saved_candidate_receipt','按原回复完成候选运行回执；无新模型调用','user','production_director')",[randomUUID(),row.ai_task_id,kind==='task'?null:row.step_id,kind==='attempt'?row.current_attempt_id:null,kind]);
  const execution=(row.controlled_execution??{}) as Row;
  await retainOriginalChapterUsage(client,row,execution);
});}
