import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {bookHistoryPayloadSchema,bookHistorySummarySchema,bookHistorySnapshotSchema,bookHistorySaveSchema,bookHistoryRestoreSchema,bookHistoryReceiptSchema,bookHistoryWorkspaceSchema,type BookHistoryReceipt} from '../../../common/bookHistory';
import {getNewDesignPool} from '../runtime';
import {stableHash} from '../aiContracts';
import {NewDesignError,assertFound} from '../../domain/errors';
import {addPlanningVersionInTransaction,adoptPlanningVersionInTransaction} from '../planning/store';
import {saveChapterCandidateInTransaction} from '../chapterWriting/store';
export class BookHistoryError extends NewDesignError{readonly recovery;constructor(bookId:string,message:string,status=503,outcome:'not_written'|'unknown'='unknown'){super(message,status);this.recovery={summary:message,mutationOutcome:outcome,sourceRoute:`/new-design/books/${bookId}/history`,actionLabel:'返回整书历史',savedResult:'原历史、当前稿件与恢复原键保留；只读核对不调用模型。'};}}
async function transaction<T>(bookId:string,key:string|undefined,work:(client:PoolClient,absent:()=>void)=>Promise<T>){const client=await(await getNewDesignPool()).connect();let committing=false,missing=false;try{await client.query(key?'BEGIN':'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');if(key)await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`book-history:${bookId}:${key}`]);const result=await work(client,()=>{missing=true;});committing=true;await client.query('COMMIT');return result;}catch(error){const rolledBack=await client.query('ROLLBACK').then(()=>true,()=>false);throw new BookHistoryError(bookId,error instanceof NewDesignError?error.message:'原历史操作未确认，请保留原键只读核对。',error instanceof NewDesignError?error.status:503,missing&&!committing&&rolledBack?'not_written':'unknown');}finally{client.release();}}
export async function bookHistoryCapability(client:PoolClient){const installed=(await client.query("SELECT to_regclass('new_design.book_content_history_snapshots') IS NOT NULL AND to_regclass('new_design.book_content_history_restores') IS NOT NULL AND to_regclass('new_design.book_content_history_capability') IS NOT NULL installed")).rows[0].installed===true;if(!installed)return{installed:false,operational:false};const operational=(await client.query("SELECT operational AND EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='new_design.book_content_history_snapshots'::regclass AND tgname='book_content_history_snapshot_guard' AND tgfoid=to_regprocedure('new_design.guard_book_content_history_snapshot()') AND tgenabled IN('O','A')) AND EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='new_design.book_content_history_restores'::regclass AND tgname='book_content_history_restore_guard' AND tgfoid=to_regprocedure('new_design.guard_book_content_history_restore()') AND tgenabled IN('O','A')) operational FROM new_design.book_content_history_capability WHERE contract='book_content_history_v1'")).rows[0]?.operational===true;return{installed:true,operational};}
async function currentState(client:PoolClient,bookId:string){
 const row=assertFound((await client.query(`SELECT jsonb_build_object('bookId',book.id,'plans',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',object.id,'versionId',version.id,'parentObjectId',object.parent_object_id,'cardId',object.card_id,'level',object.level,'title',object.title,'sortOrder',object.sort_order,'content',version.content,'executionMode',version.execution_mode,'references',COALESCE((SELECT jsonb_agg(jsonb_build_object('role',ref.reference_role,'cardId',ref.card_id,'cardVersionId',ref.card_version_id,'action',ref.action_key,'note',ref.note,'sortOrder',ref.sort_order) ORDER BY ref.sort_order,ref.id) FROM new_design.planning_version_references ref WHERE ref.planning_version_id=version.id),'[]'::jsonb)) ORDER BY object.level,object.sort_order,object.id) FROM new_design.planning_objects object JOIN new_design.planning_versions version ON version.id=object.adopted_version_id AND version.object_id=object.id WHERE object.book_id=book.id AND object.status='active'),'[]'::jsonb),'chapters',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',document.id,'cardId',document.chapter_card_id,'bodyVersionId',version.id,'logicalOrder',document.logical_order,'title',COALESCE((SELECT title FROM new_design.planning_objects object WHERE object.book_id=book.id AND object.card_id=document.chapter_card_id AND object.level='chapter' AND object.status='active'),document.title),'content',version.content,'contentHash',version.content_hash) ORDER BY document.logical_order,document.id) FROM new_design.chapter_documents document JOIN new_design.chapter_body_versions version ON version.id=document.adopted_version_id AND version.chapter_document_id=document.id WHERE document.book_id=book.id AND document.status='active'),'[]'::jsonb)) payload,
 jsonb_build_object('bookRevision',book.revision,'plans',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'revision',revision,'status',status,'adoptedVersionId',adopted_version_id,'currentVersionId',current_version_id) ORDER BY id) FROM new_design.planning_objects WHERE book_id=book.id),'[]'::jsonb),'documents',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'revision',revision,'status',status,'adoptedVersionId',adopted_version_id) ORDER BY id) FROM new_design.chapter_documents WHERE book_id=book.id),'[]'::jsonb)) heads FROM new_design.books book WHERE book.id=$1 AND book.status='active'`,[bookId])).rows[0],'本书不存在或已归档。');
 const payload=bookHistoryPayloadSchema.parse(row.payload);return{payload,fingerprint:stableHash({payload,heads:row.heads}),heads:row.heads as {plans:Array<{id:string;revision:number;status:string;adoptedVersionId:string|null;currentVersionId:string|null}>;documents:Array<{id:string;revision:number;status:string;adoptedVersionId:string|null}>}};
}
function summary(row:Record<string,unknown>){const payload=bookHistoryPayloadSchema.parse(row.payload);return bookHistorySummarySchema.parse({id:row.id,bookId:row.book_id,kind:row.kind,label:row.label,sourceId:row.source_id,requestKey:row.request_key,inputHash:row.request_hash,sourceHash:row.source_hash,createdAt:new Date(String(row.created_at)).toISOString(),planCount:payload.plans.length,chapterCount:payload.chapters.length});}
function snapshot(row:Record<string,unknown>){return bookHistorySnapshotSchema.parse({...summary(row),payload:row.payload});}
async function readSnapshot(client:PoolClient,bookId:string,id:string){return snapshot(assertFound((await client.query('SELECT * FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND id=$2',[bookId,id])).rows[0],'原整书历史不存在。'));}
export async function captureBookHistoryInTransaction(client:PoolClient,input:{bookId:string;requestKey:string;kind:'manual'|'before_restore'|'auto_milestone'|'before_pipeline';label:string;sourceId?:string|null;requestInput?:unknown}){
 if(!(await bookHistoryCapability(client)).operational)return null;
 const prior=(await client.query('SELECT * FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND request_key=$2',[input.bookId,input.requestKey])).rows[0];if(prior){if(prior.kind!==input.kind||prior.label!==input.label||prior.source_id!==(input.sourceId??null)||prior.request_hash!==stableHash(input.requestInput??input))throw new NewDesignError('原历史保存键不能改动保存用途或来源。',409);return summary(prior);}
 const current=await currentState(client,input.bookId),payload=current.payload;if(Buffer.byteLength(JSON.stringify(payload),'utf8')>50*1024*1024)throw new NewDesignError('当前正文超出单次历史保存容量，未截断内容。',422);
 const result=(await client.query('INSERT INTO new_design.book_content_history_snapshots(id,book_id,request_key,request_hash,kind,label,source_id,source_hash,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) RETURNING *',[randomUUID(),input.bookId,input.requestKey,stableHash(input.requestInput??input),input.kind,input.label,input.sourceId??null,stableHash(payload),JSON.stringify(payload)])).rows[0];return summary(result);
}
export const saveBookHistory=(bookId:string,raw:unknown)=>{const input=bookHistorySaveSchema.parse(raw);return transaction(bookId,input.requestKey,async(client,absent)=>{if(!(await bookHistoryCapability(client)).installed){absent();throw new NewDesignError('本书历史保存尚未启用。',503);}const prior=(await client.query('SELECT * FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND request_key=$2',[bookId,input.requestKey])).rows[0];if(prior){if(prior.kind!=='manual'||prior.label!==input.label||prior.request_hash!==stableHash(input))throw new NewDesignError('原历史保存键不能改变保存说明。',409);return summary(prior);}absent();await client.query('SELECT id FROM new_design.books WHERE id=$1 FOR UPDATE',[bookId]);await client.query('SELECT id FROM new_design.planning_objects WHERE book_id=$1 ORDER BY id FOR UPDATE',[bookId]);await client.query('SELECT id FROM new_design.chapter_documents WHERE book_id=$1 ORDER BY id FOR UPDATE',[bookId]);const current=await currentState(client,bookId);if(current.fingerprint!==input.expectedFingerprint)throw new NewDesignError('当前规划或正文已变化，请只读刷新后明确保存。',409);return assertFound(await captureBookHistoryInTransaction(client,{bookId,requestKey:input.requestKey,kind:'manual',label:input.label,requestInput:input}),'本书历史保存尚未启用。');});};
export const readBookHistorySave=(bookId:string,key:string)=>transaction(bookId,undefined,async client=>{if(!(await bookHistoryCapability(client)).installed)return null;const row=(await client.query('SELECT * FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND request_key=$2',[bookId,key])).rows[0];return row?summary(row):null;});
export const previewBookHistory=(bookId:string,id:string)=>transaction(bookId,undefined,async client=>{const saved=await readSnapshot(client,bookId,id),current=await currentState(client,bookId),items=[];
 for(const plan of saved.payload.plans){const head=current.heads.plans.find(item=>item.id===plan.id&&item.status==='active'),now=current.payload.plans.find(item=>item.id===plan.id),before=JSON.stringify(now?.content??{},null,2),after=JSON.stringify(plan.content,null,2);items.push({kind:'plan' as const,id:plan.id,title:plan.title,sourceVersionId:plan.versionId,targetRevision:head?.revision??null,status:!head?'missing' as const:now&&stableHash({content:now.content,references:now.references,executionMode:now.executionMode})===stableHash({content:plan.content,references:plan.references,executionMode:plan.executionMode})?'same' as const:'changed' as const,before,after});}
 for(const chapter of saved.payload.chapters){const head=current.heads.documents.find(item=>item.id===chapter.id&&item.status==='active'),now=current.payload.chapters.find(item=>item.id===chapter.id);items.push({kind:'body' as const,id:chapter.id,title:chapter.title,sourceVersionId:chapter.bodyVersionId,targetRevision:head?.revision??null,status:!head?'missing' as const:now?.contentHash===chapter.contentHash&&now.title===chapter.title&&now.logicalOrder===chapter.logicalOrder?'same' as const:'changed' as const,before:now?`第 ${now.logicalOrder} 章：${now.title}\n\n${now.content}`:'',after:`第 ${chapter.logicalOrder} 章：${chapter.title}\n\n${chapter.content}`});}
 return{snapshot:saved,currentFingerprint:current.fingerprint,items};});
async function presentReceipt(client:PoolClient,raw:unknown){const receipt=bookHistoryReceiptSchema.parse(raw),items=[];for(const item of receipt.items){if(item.kind==='plan'){const row=(await client.query('SELECT adopted_version_id FROM new_design.planning_objects WHERE book_id=$1 AND id=$2',[receipt.bookId,item.id])).rows[0];const adopted=row?.adopted_version_id===item.resultVersionId;items.push({...item,status:adopted?'adopted' as const:'prepared' as const,summary:adopted?'恢复规划已按原采用流程生效。':'恢复规划未作为当前采用版本，请返回原规划核对。'});}else{const row=(await client.query("SELECT document.adopted_version_id,document.title,document.logical_order,EXISTS(SELECT 1 FROM new_design.chapter_stable_checkpoints checkpoint JOIN new_design.chapter_adoption_sessions session ON session.id=checkpoint.session_id WHERE checkpoint.chapter_document_id=document.id AND checkpoint.body_version_id=$3 AND checkpoint.status='stable' AND checkpoint.chapter_order=document.logical_order AND session.status='stable') settled FROM new_design.chapter_documents document WHERE document.book_id=$1 AND document.id=$2",[receipt.bookId,item.id,item.resultVersionId])).rows[0];const adopted=row?.adopted_version_id===item.resultVersionId,directoryReady=row?.title===item.targetTitle&&Number(row?.logical_order)===item.targetOrder;items.push({...item,directoryReady,status:!directoryReady?'directory_pending' as const:adopted&&row.settled?'settled' as const:adopted?'adopted' as const:'prepared' as const,summary:!directoryReady?`恢复目录待完成：需为第 ${item.targetOrder} 章《${item.targetTitle}》，请继续原编排与采用结算。`:adopted&&row.settled?'恢复正文已明确采用并按原流程结算。':adopted?'恢复正文已采用；继续原结算，未复制历史状态。':'恢复正文候选已保存；继续原采用与结算。'});}}
 return bookHistoryReceiptSchema.parse({...receipt,items,completed:items.every(item=>item.kind==='plan'?item.status==='adopted':item.status==='settled')});
}
export const readBookHistoryRestore=(bookId:string,key:string)=>transaction(bookId,undefined,async client=>{if(!(await bookHistoryCapability(client)).installed)return null;const row=(await client.query('SELECT receipt FROM new_design.book_content_history_restores WHERE book_id=$1 AND request_key=$2',[bookId,key])).rows[0];return row?presentReceipt(client,row.receipt):null;});
export const prepareBookHistoryRestore=(bookId:string,raw:unknown)=>{const input=bookHistoryRestoreSchema.parse(raw),hash=stableHash(input);return transaction(bookId,input.requestKey,async(client,absent)=>{
 if(!(await bookHistoryCapability(client)).installed){absent();throw new NewDesignError('整书历史恢复尚未启用。',503);}const prior=(await client.query('SELECT input_hash,receipt FROM new_design.book_content_history_restores WHERE book_id=$1 AND request_key=$2',[bookId,input.requestKey])).rows[0];if(prior){if(prior.input_hash!==hash)throw new NewDesignError('原恢复键不能改变历史或恢复选择。',409);return presentReceipt(client,prior.receipt);}absent();if(!(await bookHistoryCapability(client)).operational)throw new NewDesignError('整书历史恢复尚未启用。',503);
 await client.query('SELECT id FROM new_design.books WHERE id=$1 FOR UPDATE',[bookId]);await client.query('SELECT id FROM new_design.planning_objects WHERE book_id=$1 ORDER BY id FOR UPDATE',[bookId]);await client.query('SELECT id FROM new_design.chapter_documents WHERE book_id=$1 ORDER BY id FOR UPDATE',[bookId]);
 const saved=await readSnapshot(client,bookId,input.snapshotId),current=await currentState(client,bookId);if(saved.sourceHash!==input.sourceHash||current.fingerprint!==input.currentFingerprint)throw new NewDesignError('历史确切来源或当前规划／正文已变化；未自动套用新的来源。',409);
 for(const selected of input.items){const source=selected.kind==='plan'?saved.payload.plans.find(item=>item.id===selected.id):saved.payload.chapters.find(item=>item.id===selected.id),head=(selected.kind==='plan'?current.heads.plans:current.heads.documents).find(item=>item.id===selected.id&&item.status==='active');if(!source||!head||head.revision!==selected.expectedRevision)throw new NewDesignError('原恢复项不存在、已归档或修订变化；未部分覆盖。',409);}
 const before=assertFound(await captureBookHistoryInTransaction(client,{bookId,requestKey:input.requestKey,kind:'before_restore',label:'恢复前的当前规划与正文',sourceId:saved.id,requestInput:input}),'恢复前历史未保存。'),items:BookHistoryReceipt['items']=[],levels={story:0,volume:1,chapter:2,scene:3};
 const plans=saved.payload.plans.filter(item=>input.items.some(selected=>selected.kind==='plan'&&selected.id===item.id)).sort((a,b)=>levels[a.level]-levels[b.level]||a.sortOrder-b.sortOrder||a.id.localeCompare(b.id));
 for(const plan of plans){const head=assertFound((await client.query('SELECT revision FROM new_design.planning_objects WHERE book_id=$1 AND id=$2',[bookId,plan.id])).rows[0],'原规划不存在。'),parent=plan.parentObjectId?(await client.query('SELECT adopted_version_id FROM new_design.planning_objects WHERE book_id=$1 AND id=$2',[bookId,plan.parentObjectId])).rows[0]?.adopted_version_id:null;
  const created=await addPlanningVersionInTransaction(client,plan.id,{content:{...plan.content,title:plan.title},source:'manual',executionMode:plan.executionMode,references:plan.references,baseVersionId:plan.versionId,basedOnParentVersionId:parent??null,expectedRevision:Number(head.revision),idempotencyKey:`${input.requestKey}:plan:${plan.id}`,createdBy:'user'});await adoptPlanningVersionInTransaction(client,plan.id,{versionId:created.versionId,expectedRevision:created.revision,idempotencyKey:`${input.requestKey}:adopt:${plan.id}`,source:'user',actor:'user'});items.push({kind:'plan',id:plan.id,sourceVersionId:plan.versionId,resultVersionId:created.versionId,sourceRoute:`/new-design/books/${bookId}/planning?stage=${plan.level==='story'?'story_macro':plan.level==='volume'?'outline':'structured'}#plan-${plan.id}`,status:'adopted',targetTitle:null,targetOrder:null,directoryReady:true,directoryRoute:null,summary:'恢复规划按原候选、采用及下游影响流程生效。'});
 }
 for(const chapter of saved.payload.chapters.filter(item=>input.items.some(selected=>selected.kind==='body'&&selected.id===item.id))){let latest=(await client.query('SELECT revision,title FROM new_design.chapter_documents WHERE id=$1 AND book_id=$2',[chapter.id,bookId])).rows[0];if(latest.title!==chapter.title){const object=assertFound((await client.query("SELECT object.*,version.content,version.execution_mode FROM new_design.planning_objects object JOIN new_design.planning_versions version ON version.id=object.adopted_version_id WHERE object.book_id=$1 AND object.card_id=$2 AND object.level='chapter' AND object.status='active'",[bookId,chapter.cardId])).rows[0],'Original chapter plan unavailable.');const originalReferences=(await client.query('SELECT reference_role role,card_id "cardId",card_version_id "cardVersionId",action_key action,note,sort_order "sortOrder" FROM new_design.planning_version_references WHERE planning_version_id=$1 ORDER BY sort_order,id',[object.adopted_version_id])).rows;const renamed=await addPlanningVersionInTransaction(client,object.id,{content:{...object.content,title:chapter.title},source:'manual',executionMode:object.execution_mode,references:originalReferences,basedOnParentVersionId:(await client.query('SELECT adopted_version_id FROM new_design.planning_objects WHERE id=$1',[object.parent_object_id])).rows[0]?.adopted_version_id,baseVersionId:object.adopted_version_id,expectedRevision:Number(object.revision),idempotencyKey:`${input.requestKey}:title:${chapter.id}`,createdBy:'user'});await adoptPlanningVersionInTransaction(client,object.id,{versionId:renamed.versionId,expectedRevision:renamed.revision,idempotencyKey:`${input.requestKey}:title-adopt:${chapter.id}`,source:'user',actor:'user'});latest=(await client.query('SELECT revision,title FROM new_design.chapter_documents WHERE id=$1 AND book_id=$2',[chapter.id,bookId])).rows[0];}const created=await saveChapterCandidateInTransaction(client,chapter.id,{content:chapter.content,operationKind:'copy',baseVersionId:chapter.bodyVersionId,expectedRevision:Number(latest.revision),idempotencyKey:`${input.requestKey}:body:${chapter.id}`,createdBy:'user'});items.push({kind:'body',id:chapter.id,sourceVersionId:chapter.bodyVersionId,resultVersionId:created.versionId,sourceRoute:`/new-design/books/${bookId}/writing?chapter=${chapter.cardId}&bodyVersion=${created.versionId}`,status:'prepared',targetTitle:chapter.title,targetOrder:chapter.logicalOrder,directoryReady:Number(latest.logical_order??(await client.query('SELECT logical_order FROM new_design.chapter_documents WHERE id=$1',[chapter.id])).rows[0].logical_order)===chapter.logicalOrder,directoryRoute:`/new-design/books/${bookId}/composition`,summary:'恢复正文候选已保存；继续原采用与结算。'});}
 const receipt=bookHistoryReceiptSchema.parse({requestKey:input.requestKey,bookId,inputHash:hash,input,beforeSnapshotId:before.id,items,completed:items.every(item=>item.kind==='plan')});await client.query('INSERT INTO new_design.book_content_history_restores(book_id,request_key,input_hash,input_payload,before_snapshot_id,receipt) VALUES($1,$2,$3,$4::jsonb,$5,$6::jsonb)',[bookId,input.requestKey,hash,JSON.stringify(input),before.id,JSON.stringify(receipt)]);return presentReceipt(client,receipt);
 });};
export const getBookHistoryWorkspace=(bookId:string,before?:string)=>transaction(bookId,undefined,async client=>{const capability=await bookHistoryCapability(client),current=await currentState(client,bookId);if(!capability.installed)return bookHistoryWorkspaceSchema.parse({bookId,capability,currentFingerprint:current.fingerprint,snapshots:[],nextCursor:null,restores:[],restoresTruncated:false});const snapshots=(await client.query('SELECT * FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND ($2::uuid IS NULL OR (created_at,id)<(SELECT created_at,id FROM new_design.book_content_history_snapshots WHERE book_id=$1 AND id=$2)) ORDER BY created_at DESC,id DESC LIMIT 51',[bookId,before??null])).rows,restores=(await client.query('SELECT receipt FROM new_design.book_content_history_restores WHERE book_id=$1 ORDER BY created_at DESC,request_key DESC LIMIT 51',[bookId])).rows;return bookHistoryWorkspaceSchema.parse({bookId,capability,currentFingerprint:current.fingerprint,snapshots:snapshots.slice(0,50).map(summary),nextCursor:snapshots.length>50?snapshots[49].id:null,restores:await Promise.all(restores.slice(0,50).map(row=>presentReceipt(client,row.receipt))),restoresTruncated:restores.length>50});});
