import {useEffect,useRef,useState} from "react";
import type {BookCompositionOrderInput,BookCompositionOrderPreview,BookCompositionOrderSaveInput,BookCompositionOrderReceipt,BookCompositionWorkspace} from "../../common/bookComposition";
import {moveCompositionItem} from "../../common/bookComposition";
import {ApiError,newDesignApi} from "../api";
import type {PlanningObject} from "../../common/contracts";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,hash=/^[a-f0-9]{64}$/;
type Pending={input:BookCompositionOrderSaveInput;notWritten:boolean;checked:boolean};
export function parseRetainedCompositionOrder(raw:string|null,bookId:string):{draft:BookCompositionOrderInput;pending:Pending|null}|null{try{if(!raw||raw.length>1000000)return null;const stored=JSON.parse(raw),valid=(input:BookCompositionOrderInput)=>!!input&&uuid.test(input.requestKey)&&uuid.test(input.parentObjectId)&&["volume","chapter","scene"].includes(input.level)&&hash.test(input.expectedBookOrderHash)&&Array.isArray(input.items)&&input.items.length>0&&input.items.length<=10000&&input.items.every(item=>!!item&&uuid.test(item.objectId)&&Number.isSafeInteger(item.expectedRevision)&&item.expectedRevision>0)&&new Set(input.items.map(item=>item.objectId)).size===input.items.length;if(stored.version!==1||stored.bookId!==bookId||!uuid.test(bookId)||!valid(stored.draft)||stored.pending!==null&&(!stored.pending||!valid(stored.pending.input)||!hash.test(stored.pending.input.previewHash)||stored.pending.input.requestKey!==stored.draft.requestKey))return null;return {draft:stored.draft,pending:stored.pending?{input:stored.pending.input,notWritten:false,checked:false}:null};}catch{return null;}}
export default function CompositionOrderEditor({workspace,selected,disabled,preserveBody,onRead}:{workspace:BookCompositionWorkspace;selected:PlanningObject|null;disabled:boolean;preserveBody:()=>boolean;onRead:()=>Promise<void>}){
 const [draft,setDraft]=useState<BookCompositionOrderInput|null>(null),[preview,setPreview]=useState<BookCompositionOrderPreview|null>(null),[pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[proof,setProof]=useState<BookCompositionOrderReceipt|null>(null),[step,setStep]=useState(""),[stateBook,setStateBook]=useState(workspace.bookId),drag=useRef<number|null>(null),restoredScope=useRef("");
 const storageKey=`new-design:composition-order:v1:${workspace.bookId}`;
 const [storageIssue,setStorageIssue]=useState("");const storageBlocked=useRef(false);const blockStorage=()=>{storageBlocked.current=true;setStorageIssue("排序草稿或原请求凭证无法完整读取或保留，已锁定提交，原凭证不会覆盖或删除。请核对网站存储后回到原书只读查询。");};
 const retain=(nextDraft=draft,nextPending=pending)=>{if(storageBlocked.current)return false;try{if(!nextDraft)return true;if(stateBook!==workspace.bookId)return false;sessionStorage.setItem(storageKey,JSON.stringify({version:1,bookId:workspace.bookId,draft:nextDraft,pending:nextPending}));return true;}catch{blockStorage();return false;}};
 useEffect(()=>{restoredScope.current="";setStateBook(workspace.bookId);setDraft(null);setPreview(null);setPending(null);setProof(null);try{const raw=sessionStorage.getItem(storageKey),stored=parseRetainedCompositionOrder(raw,workspace.bookId);if(raw!==null&&!stored)blockStorage();else if(stored){setDraft(stored.draft);setPending(stored.pending);}}catch{blockStorage();}restoredScope.current=workspace.bookId;},[workspace.bookId]);
 useEffect(()=>{if(restoredScope.current===workspace.bookId&&stateBook===workspace.bookId&&draft)retain();},[draft,pending,workspace.bookId,stateBook]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(draft||pending){retain();event.preventDefault();event.returnValue="";}};addEventListener("beforeunload",leave);return()=>removeEventListener("beforeunload",leave);},[draft,pending,workspace.bookId]);
 const open=()=>{if(!selected||selected.level==="story"||!selected.parentObjectId||disabled||busy||pending||!preserveBody())return;const siblings=workspace.planning.objects.filter(item=>item.status==="active"&&item.parentObjectId===selected.parentObjectId&&item.level===selected.level).sort((a,b)=>a.sortOrder-b.sortOrder||a.id.localeCompare(b.id));setDraft({requestKey:crypto.randomUUID(),parentObjectId:selected.parentObjectId,level:selected.level,expectedBookOrderHash:workspace.orderBasisHash,items:siblings.map(item=>({objectId:item.id,expectedRevision:item.revision}))});setPreview(null);setMessage("");setProof(null);};
 const move=(from:number,to:number)=>{if(!draft||busy||pending||disabled||!preserveBody())return;setDraft({...draft,items:moveCompositionItem(draft.items,from,to)});setPreview(null);};
 const inspect=async()=>{if(!draft||busy||pending||disabled||!preserveBody())return;setBusy(true);setStep("预览全书顺序影响");try{const next=await newDesignApi.previewBookCompositionOrder(workspace.bookId,draft);if(next.bookId!==workspace.bookId||next.input.requestKey!==draft.requestKey)throw new Error("影响预览来源不匹配，排序草稿保留。");setPreview(next);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"影响预览未完成，排序草稿与正文保留。");}finally{setBusy(false);}};
 const accept=(receipt:BookCompositionOrderReceipt,key:string)=>{if(receipt.bookId!==workspace.bookId||receipt.requestKey!==key||receipt.parentObjectId!==draft?.parentObjectId||receipt.level!==draft?.level)throw new Error("原排序回执来源不匹配，请保留原请求并只读核对。");setProof(receipt);setPending(null);setDraft(null);setPreview(null);try{sessionStorage.removeItem(storageKey);}catch{/* Proof remains shown. */}};
 const save=async()=>{if(!draft||!preview||pending||busy||disabled||!preserveBody())return;const input={...draft,previewHash:preview.previewHash},nextPending={input,notWritten:false,checked:false};if(!retain(draft,nextPending)){setMessage("原请求与排序草稿未能保留，保存未提交；请检查网站存储。");return;}setPending(nextPending);setBusy(true);setStep("确认保存全书顺序");let saved=false;try{const receipt=await newDesignApi.saveBookCompositionOrder(workspace.bookId,input);accept(receipt,input.requestKey);saved=true;await onRead();setMessage("");}catch(error){if(saved)setMessage("排序已保存；目录读取未完成，已成功凭证保留，请只读重新读取。");else{setMessage(error instanceof Error?error.message:"排序回执未确认，原请求保留；只读核对，不再次保存。");if(error instanceof ApiError&&error.recovery?.mutationOutcome==="not_written")setPending(current=>current?{...current,notWritten:true}:current);}}finally{setBusy(false);}};
 const check=async()=>{if(!pending||busy)return;setBusy(true);setStep("只读核对原排序请求");let found=false;try{const receipt=await newDesignApi.getBookCompositionOrderReceipt(workspace.bookId,pending.input.requestKey);if(receipt){accept(receipt,pending.input.requestKey);found=true;await onRead();}else{setPending(current=>current?{...current,checked:true}:current);setMessage("原排序回执未找到，不能断言未执行；原请求保留，不重复提交。");}}catch(error){setMessage(found?"原排序已保存；目录读取失败，成功凭证保留。":error instanceof Error?error.message:"核对未完成，原请求保留。");}finally{setBusy(false);}};
 const prepareLatest=()=>{if(!draft||busy||disabled||pending&&(!pending.notWritten||!pending.checked)||!preserveBody())return;const siblings=workspace.planning.objects.filter(item=>item.status==="active"&&item.parentObjectId===draft.parentObjectId&&item.level===draft.level);if(!siblings.length){setMessage("原同级目录已变化，请保留草稿并在本书目录选择合法上级。");return;}const ordered=[...draft.items.map(item=>siblings.find(sibling=>sibling.id===item.objectId)).filter((item):item is PlanningObject=>!!item),...siblings.filter(item=>!draft.items.some(prior=>prior.objectId===item.id))];setDraft({...draft,requestKey:crypto.randomUUID(),expectedBookOrderHash:workspace.orderBasisHash,items:ordered.map(item=>({objectId:item.id,expectedRevision:item.revision}))});setPending(null);setPreview(null);setMessage("保留仍存在目录的人工顺序；新增目录追加在末尾，已明确采用当前修订。请核对顺序并重新预览。");};
 if(storageIssue)return <section role="alert"><h3>未完成步骤：恢复原排序草稿与请求凭证</h3><p>{storageIssue}</p><a className="nd-button" href="/new-design/structure/maintenance">打开运行维护</a><p>只导航，不重发请求或替换原凭证。</p></section>;
 if(!draft&&!proof)return <button className="nd-button nd-button-secondary" type="button" disabled={!selected||selected.level==="story"||disabled||busy} onClick={open}>调整同级目录顺序</button>;
 return <section className="nd-composition-order"><h3>同级排序与全书影响</h3><p>拖动或上下移动只改变预览；确认影响后才保存目录。正文保持不变。</p>{draft&&<><ul>{draft.items.map((item,index)=><li key={item.objectId} draggable={!busy&&!pending&&!disabled} onDragStart={()=>{drag.current=index;}} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(drag.current!==null)move(drag.current,index);drag.current=null;}}><span>{workspace.planning.objects.find(object=>object.id===item.objectId)?.title??"原目录来源待核对"}</span><div><button className="nd-button nd-button-secondary" type="button" disabled={busy||Boolean(pending)||disabled||index===0} onClick={()=>move(index,index-1)}>上移</button><button className="nd-button nd-button-secondary" type="button" disabled={busy||Boolean(pending)||disabled||index===draft.items.length-1} onClick={()=>move(index,index+1)}>下移</button></div></li>)}</ul>{draft.expectedBookOrderHash!==workspace.orderBasisHash&&<p role="alert">全书正式修订已变化；原排序草稿保留，不能沿用旧影响预览。</p>}<button className="nd-button nd-button-secondary" type="button" disabled={busy||Boolean(pending)||disabled} onClick={()=>void inspect()}>预览全书影响</button>{!pending&&<button className="nd-button nd-button-secondary" type="button" disabled={busy||disabled} onClick={prepareLatest}>保留顺序，明确采用最新修订重新预览</button>}</>}{preview&&<><h4>所有章节的目标正文档案顺序</h4><ul>{preview.chapters.map(chapter=><li key={chapter.chapterCardId}>{chapter.title}：{chapter.beforeOrder??"尚未起稿"} → {chapter.afterOrder}</li>)}</ul>{preview.warnings.map(warning=><p key={warning}>{warning}</p>)}<button className="nd-button nd-button-primary" type="button" disabled={busy||Boolean(pending)||disabled} onClick={()=>void save()}>确认影响并保存排序</button></>}{pending&&<section role="alert"><p>原排序回执待核对，草稿与原请求保留；结果未知只读查询。</p><button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void check()}>只读核对原排序请求</button>{pending.notWritten&&pending.checked&&<button className="nd-button nd-button-secondary" type="button" disabled={busy||disabled} onClick={prepareLatest}>保留顺序，明确重新准备</button>}</section>}{proof&&<section role="status"><p>原请求排序已保存，正文内容保持不变。</p><p>复核下游采用计划、故事时间、人物关系与状态结算、伏笔安排；本页不自动采用或结算。</p><a className="nd-button nd-button-secondary" href={`/new-design/books/${workspace.bookId}/planning`}>复核原故事规划</a><button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void onRead().catch(()=>setMessage("目录读取失败，已保存排序凭证保留。"))}>只读读取已保存目录</button></section>}{message&&<section role="alert"><strong>未完成步骤：{step||"保留排序草稿"}</strong><p>{message}</p><p>正文、草稿和已保存证据保留；返回本页只读核对原请求。</p><a className="nd-button nd-button-secondary" href="/new-design/structure/maintenance" onClick={event=>{if(!retain()||!preserveBody())event.preventDefault();}}>打开运行维护</a></section>}</section>;
}
