import type {RecentBodySeriesPreview,RecentBodyExperienceRequest,RecentBodyExperienceRecord} from '../../../../common/characterExperiences/recentBodies';
import {recentBodySeriesSelectionSchema,recentBodyExperienceRequestSchema,validRecentBodyExperienceRecord} from '../../../../common/characterExperiences/recentBodies';
import {sameRecentBodyExperienceValue as same} from '../recovery';
export interface RecentBodySeriesPlan {format:1;id:string;bookId:string;characterId:string;preview:RecentBodySeriesPreview;parts:RecentBodyExperienceRequest[];next:number;stage:'ready'|'pending'|'complete'|'stopped';records:RecentBodyExperienceRecord[];message:string;}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,hash=/^[a-f0-9]{64}$/;
export function validRecentBodySeriesPreview(preview:RecentBodySeriesPreview,bookId:string,characterId:string){try{const selected=preview.selection;return preview.bookId===bookId&&preview.snapshot.bookId===bookId&&preview.snapshot.contract==='character_recent_body_experiences_v1'&&recentBodySeriesSelectionSchema.safeParse(selected).success&&selected.characterIds.includes(characterId)&&hash.test(preview.sourceHash)&&same(preview.snapshot.actors.map(actor=>actor.id),selected.characterIds)&&same(preview.snapshot.bodies.map(body=>body.documentId),selected.chapterDocumentIds)&&preview.parts.length===Math.ceil(selected.characterIds.length/20)&&preview.parts.every((part,index)=>same(part.characterIds,selected.characterIds.slice(index*20,index*20+20))&&hash.test(part.expectedSourceHash));}catch{return false;}}
export function validRecentBodySeriesPlan(value:unknown,bookId:string,characterId:string):value is RecentBodySeriesPlan {try{const p=value as RecentBodySeriesPlan;if(!p||p.format!==1||!uuid.test(p.id)||p.bookId!==bookId||p.characterId!==characterId||!validRecentBodySeriesPreview(p.preview,bookId,characterId)||!Array.isArray(p.parts)||p.parts.length!==p.preview.parts.length||new Set(p.parts.map(part=>part.requestKey)).size!==p.parts.length||!Number.isInteger(p.next)||p.next<0||p.next>p.parts.length||!['ready','pending','complete','stopped'].includes(p.stage)||typeof p.message!=='string'||!Array.isArray(p.records)||p.records.length!==p.next||p.stage==='complete'&&p.next!==p.parts.length||['ready','pending'].includes(p.stage)&&p.next===p.parts.length)return false;for(const [index,input]of p.parts.entries()){const original=p.preview.parts[index]!;if(!recentBodyExperienceRequestSchema.safeParse(input).success||input.instruction!==p.parts[0]!.instruction||!same(input.characterIds,original.characterIds)||!same(input.chapterDocumentIds,p.preview.selection.chapterDocumentIds)||input.expectedSourceHash!==original.expectedSourceHash)return false;}return p.records.every((record,index)=>validRecentBodyExperienceRecord(record)&&record.bookId===bookId&&record.status!=='running'&&same(record.request,p.parts[index])&&matchesFrozen(record,p.preview,index)&&(record.status==='review'||p.stage==='stopped'&&index===p.records.length-1));}catch{return false;}}
function matchesFrozen(record:RecentBodyExperienceRecord,preview:RecentBodySeriesPreview,index:number){return same({...record.snapshot,actors:record.snapshot.actors.map(actor=>({...actor,slotIds:[]}))},{...preview.snapshot,actors:preview.snapshot.actors.slice(index*20,index*20+20)});}
interface Ports {bookId:string;characterId:string;key:string;singleKey:string;storage:Pick<Storage,'getItem'|'setItem'>;lock:(run:()=>Promise<void>)=>Promise<void>;uuid:()=>string;write:(input:RecentBodyExperienceRequest)=>Promise<RecentBodyExperienceRecord>;read:(input:RecentBodyExperienceRequest)=>Promise<RecentBodyExperienceRecord|null>;endUnknown:(input:RecentBodyExperienceRequest)=>Promise<RecentBodyExperienceRecord>;notWritten:(reason:unknown)=>boolean;changed:()=>void;result:(record:RecentBodyExperienceRecord)=>void;}
/** Whole-range plan and each original send are persisted before dispatch. Reads
 * never continue later parts. Cross-page progress changes require a new action. */
export class RecentBodySeriesController {
 plan:RecentBodySeriesPlan|null=null;busy=false;blocked=false;message='';private active=true;private lifetime=0;private execution=-1;
 constructor(private readonly ports:Ports){}
 private notify(){if(this.active)this.ports.changed();}
 private stored(){const raw=this.ports.storage.getItem(this.ports.key);if(!raw)return null;const parsed=JSON.parse(raw);if(!validRecentBodySeriesPlan(parsed,this.ports.bookId,this.ports.characterId))throw new Error('原正文分批凭证不完整，记录保留，停止新发送。');return parsed;}
 restore(){this.active=true;this.lifetime++;this.busy=false;try{this.plan=this.stored();this.message=this.plan?.stage==='pending'?'原正文批次待只读核对，剩余人物未继续。':this.plan?.message??'';}catch(reason){this.blocked=true;this.message=reason instanceof Error?reason.message:'原正文分批未读取。';}this.notify();}
 cancel(){this.active=false;this.lifetime++;}
 private current(){return this.active&&this.execution===this.lifetime;}
 isLocked(){return this.blocked||this.busy||this.plan?.stage==='pending'||this.plan?.stage==='ready';}
 private synchronize(expected:RecentBodySeriesPlan|null){const saved=this.stored();if(!same(saved,expected)){this.plan=saved;throw new Error('另一页面的完整正文分批进度已变化，本页已核对新进度，未覆盖或发送。');}if(this.ports.storage.getItem(this.ports.singleKey))throw new Error('原单批正文请求待核对，未覆盖或继续分批。');}
 private persist(plan:RecentBodySeriesPlan){try{this.synchronize(this.plan);if(!validRecentBodySeriesPlan(plan,this.ports.bookId,this.ports.characterId))throw new Error('正文分批完整范围或原结果未匹配。');this.ports.storage.setItem(this.ports.key,JSON.stringify(plan));this.plan=plan;this.message=plan.message;this.notify();return true;}catch(reason){this.blocked=true;this.message=reason instanceof Error?reason.message:'正文分批原结果无法保存，停止剩余人物。';this.notify();return false;}}
 private async exclusive(action:()=>Promise<void>){if(!this.active||this.busy||this.blocked)return;const expected=this.plan,seq=this.lifetime;this.busy=true;this.notify();try{await this.ports.lock(async()=>{if(!this.active||seq!==this.lifetime)return;this.execution=seq;this.synchronize(expected);await action();});}catch(reason){if(this.active&&seq===this.lifetime){this.message=reason instanceof Error?reason.message:'原正文分批未完成，凭证保留。';this.notify();}}finally{if(this.active&&seq===this.lifetime){this.busy=false;this.notify();}}}
 async start(preview:RecentBodySeriesPreview,instruction:string){if(this.isLocked())return;await this.exclusive(async()=>{if(!validRecentBodySeriesPreview(preview,this.ports.bookId,this.ports.characterId))throw new Error('整个原正文范围未完整核对，未发送。');if(this.plan)this.ports.storage.setItem(`${this.ports.key}:history:${this.plan.id}`,JSON.stringify(this.plan));const parts=preview.parts.map(part=>({requestKey:this.ports.uuid(),instruction:instruction.trim(),characterIds:part.characterIds,chapterDocumentIds:preview.selection.chapterDocumentIds,expectedSourceHash:part.expectedSourceHash}));if(this.persist({format:1,id:this.ports.uuid(),bookId:this.ports.bookId,characterId:this.ports.characterId,preview:structuredClone(preview),parts,next:0,stage:'ready',records:[],message:'整个采用正文与人物范围已冻结，依次准备每批最多20人。'}))await this.run();});}
 private accept(record:RecentBodyExperienceRecord,input:RecentBodyExperienceRequest){if(!this.plan||!validRecentBodyExperienceRecord(record)||record.bookId!==this.ports.bookId||!same(record.request,input)||!matchesFrozen(record,this.plan.preview,this.plan.next))throw new Error('原正文分批结果与整个冻结范围、原请求或正文依据不同。');if(record.status==='running')throw new Error(record.error||'原正文批次仍待核对，未继续剩余人物。');const next=this.plan.next+1,stage=record.status!=='review'?'stopped':next===this.plan.parts.length?'complete':'ready';if(!this.persist({...this.plan,next,stage,records:[...this.plan.records,record],message:stage==='complete'?'本次正文人物分批候选已保存，请逐项检查并单独审核时间提案。':stage==='stopped'?'本次正文分批已停止，原范围与已保存结果保留。':'原正文批次结果已保存，剩余人物等待继续。'}))return false;this.ports.result(record);return true;}
 private async run(){while(this.current()&&!this.blocked&&this.plan?.stage==='ready'){const input=this.plan.parts[this.plan.next]!;if(!this.persist({...this.plan,stage:'pending',message:`准备第${this.plan.next+1}／${this.plan.parts.length}批正文人物候选。`}))return;try{const record=await this.ports.write(input);if(!this.current())return;if(!this.accept(record,input))return;}catch(reason){if(!this.current())return;if(this.ports.notWritten(reason)&&!this.blocked)this.persist({...this.plan!,stage:'stopped',message:'本批确认未写入，剩余人物已停止；请重新核对整个范围。'});else{this.message=`${reason instanceof Error?reason.message:'原回复中断'}；只读核对原正文批次，未继续剩余人物。`;this.notify();}return;}}}
 async verify(){if(this.plan?.stage!=='pending')return;await this.exclusive(async()=>{const input=this.plan!.parts[this.plan!.next]!,record=await this.ports.read(input);if(!this.current())return;if(!record)throw new Error('原正文回执未读取，不证明未写入；原请求保留。');this.accept(record,input);});}
 async resume(){if(this.plan?.stage!=='ready')return;await this.exclusive(()=>this.run());}
 async endUnknown(){if(this.plan?.stage!=='pending')return;await this.exclusive(async()=>{const input=this.plan!.parts[this.plan!.next]!,record=await this.ports.endUnknown(input);if(this.current()&&this.accept(record,input)&&this.plan?.stage==='ready')this.persist({...this.plan,stage:'stopped',message:'原未知占用已明确结束，本次剩余人物不再发送。'});});}
 async stop(){if(this.plan?.stage!=='ready')return;await this.exclusive(async()=>{this.persist({...this.plan!,stage:'stopped',message:'本次剩余正文人物分批已明确结束，原来源和结果保留。'});});}
 async inspect(index:number){const expected=this.plan,input=expected?.parts[index];if(!input||index<0||index>=expected!.next)return;await this.exclusive(async()=>{const record=await this.ports.read(input);if(!this.current())return;if(!record||!validRecentBodyExperienceRecord(record)||record.bookId!==this.ports.bookId||!same(record,expected!.records[index]))throw new Error('原正文批次的完整已保存结果未读取，保留原凭证。');this.ports.result(record);});}
}
