import {z} from 'zod';
import type {DialogueCreateInput,DialogueRoundInput,DialogueWorkspace,DialogueActionSelectionInput,DialogueRoundOutput} from '../../../common/characterDialogue';
import * as domain from '../../database/characterDialogue';
import {preparePrompt} from '../../ai/prompts';
import {executeManagedPrompt,type ExecutionDependencies} from '../../ai/runtime/managedExecution';
import {AiExecutionError} from '../../ai/runtime/errors';
import {getManagedCredentialEnvironment} from '../../database/modelManagement';
import {assertFound,NewDesignError} from '../../domain/errors';
export {dialogueCreateSchema,dialogueRoundSchema,dialogueSelectionSchema,DialogueError} from '../../database/characterDialogue';
export const dialogueWorkspaceQuerySchema=z.object({checkpointId:z.string().uuid().optional(),participantCardIds:z.array(z.string().uuid()).min(2).max(10).optional()}).strict().refine(v=>Boolean(v.checkpointId)===Boolean(v.participantCardIds),'请同时选择截至章和全部参与对象。');
export async function getCharacterDialogueWorkspace(bookId:string,value:{checkpointId?:string;participantCardIds?:string[]}={}):Promise<DialogueWorkspace>{z.string().uuid().parse(bookId);const query=dialogueWorkspaceQuerySchema.parse(value),client=await(await domain.getDialoguePool()).connect();try{await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const book=assertFound((await client.query("SELECT space_id,status FROM new_design.books WHERE id=$1",[bookId])).rows[0],'原书不存在。');if(book.status!=='active')throw new NewDesignError('本书已归档，不准备当前沙盘。',409);const checkpoints=(await client.query(`${domain.checkpointSql} ORDER BY checkpoint.chapter_order LIMIT 301`,[bookId])).rows;if(checkpoints.length>300)throw new NewDesignError('截至章目录超过300项，不用截断选择假装全部来源。',422);const participants=(await client.query("SELECT id,title FROM new_design.cards WHERE space_id=$1 AND status='active' ORDER BY title,id LIMIT 301",[book.space_id])).rows;if(participants.length>300)throw new NewDesignError('参与资料目录超过300项，不静默截断。',422);const sources=query.checkpointId&&query.participantCardIds?await domain.readDialogueSources(client,bookId,query.checkpointId,query.participantCardIds):null,ids=(await client.query('SELECT id FROM new_design.character_dialogue_sessions WHERE book_id=$1 ORDER BY created_at DESC LIMIT 100',[bookId])).rows,sessions=[];for(const row of ids)sessions.push(await domain.readDialogueSession(client,bookId,String(row.id)));const targets=(await client.query("SELECT object.id,object.title,object.revision,version.id version_id FROM new_design.planning_objects object JOIN new_design.planning_versions version ON version.id=object.current_version_id AND version.object_id=object.id AND version.stale_at IS NULL WHERE object.book_id=$1 AND object.status='active' ORDER BY object.level,object.sort_order,object.id LIMIT 301",[bookId])).rows;if(targets.length>300)throw new NewDesignError('规划目标超过目录上限，不替选其他规划。',422);await client.query('COMMIT');return{bookId,checkpoints:checkpoints.map(domain.checkpointRow),participants:participants.map(r=>({id:String(r.id),label:String(r.title)})),sources,sessions,planningTargets:targets.map(r=>({id:String(r.id),label:String(r.title),revision:Number(r.revision),versionId:String(r.version_id)}))};}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
export const createCharacterDialogueSession=(bookId:string,input:DialogueCreateInput)=>domain.createDialogueSession(z.string().uuid().parse(bookId),domain.dialogueCreateSchema.parse(input));
export const getCharacterDialogueSession=(bookId:string,id:string)=>domain.dialogueTransaction(z.string().uuid().parse(bookId),undefined,client=>domain.readDialogueSession(client,bookId,z.string().uuid().parse(id)));
export const getCharacterDialogueSessionByKey=(bookId:string,key:string)=>domain.dialogueTransaction(z.string().uuid().parse(bookId),z.string().uuid().parse(key),async client=>{const row=(await client.query('SELECT id FROM new_design.character_dialogue_sessions WHERE book_id=$1 AND request_key=$2',[bookId,key])).rows[0];return row?domain.readDialogueSession(client,bookId,String(row.id)):null;});
async function exactRound(bookId:string,sessionId:string,id?:string,key?:string){z.string().uuid().parse(bookId);z.string().uuid().parse(sessionId);z.string().uuid().parse(id??key);return domain.dialogueTransaction(bookId,key,async client=>{const row=await domain.readDialogueRound(client,bookId,id,key);if(row&&row.session_id!==sessionId)throw new NewDesignError('原回合不属于指定会话，不选择其他来源代替。',409);return row?domain.dialogueRoundReceipt(row):null;});}
export const getCharacterDialogueRoundByKey=(bookId:string,sessionId:string,key:string)=>exactRound(bookId,sessionId,undefined,key);
export const getCharacterDialogueRound=(bookId:string,sessionId:string,id:string)=>exactRound(bookId,sessionId,id).then(row=>assertFound(row,'指定原回合不存在。'));
async function recover(bookId:string,sessionId:string,id:string,kind:'complete'|'release'|'end'){await getCharacterDialogueRound(bookId,sessionId,id);return kind==='end'?domain.endExpiredDialogueRound(bookId,id):domain.completeDialogueOutput(bookId,id,kind==='release');}
export const completeSavedCharacterDialogueRound=(bookId:string,sessionId:string,id:string)=>recover(bookId,sessionId,id,'complete');
export const releaseSavedCharacterDialogueRound=(bookId:string,sessionId:string,id:string)=>recover(bookId,sessionId,id,'release');
export const endExpiredCharacterDialogueRound=(bookId:string,sessionId:string,id:string)=>recover(bookId,sessionId,id,'end');
export const selectCharacterDialogueActions=(bookId:string,sessionId:string,input:DialogueActionSelectionInput)=>domain.selectDialogueActions(z.string().uuid().parse(bookId),z.string().uuid().parse(sessionId),domain.dialogueSelectionSchema.parse(input));
export const getCharacterDialogueSelectionByKey=(bookId:string,sessionId:string,key:string)=>domain.getDialogueSelectionByKey(z.string().uuid().parse(bookId),z.string().uuid().parse(sessionId),z.string().uuid().parse(key));
export async function runCharacterDialogueRound(bookId:string,sessionId:string,value:DialogueRoundInput,dependencies:ExecutionDependencies={}){z.string().uuid().parse(bookId);z.string().uuid().parse(sessionId);const input=domain.dialogueRoundSchema.parse(value),claimed=await domain.claimDialogueRound(bookId,sessionId,input);if(!claimed.claimed)return claimed.receipt;const prompt=preparePrompt('character_dialogue',claimed.plan.input);await domain.markDialogueSending(bookId,claimed.receipt.id);const started=Date.now();let result:Awaited<ReturnType<typeof executeManagedPrompt<DialogueRoundOutput>>>;try{result=await executeManagedPrompt<DialogueRoundOutput>('character_dialogue',prompt,{...dependencies,stopOnUnknownResponse:true,credentialResolver:dependencies.credentialResolver??((id,provider)=>domain.dialogueTransaction(bookId,undefined,client=>getManagedCredentialEnvironment(id,provider,{client}))),routeResolver:async()=>claimed.plan.route,snapshotWriter:async()=>({id:claimed.plan.snapshotId,snapshotHash:claimed.plan.snapshotHash,taskType:'character_dialogue',route:claimed.plan.route})});}catch(error){const failure=error instanceof AiExecutionError?error:null,trace=failure?.executionSnapshot??null,attempts=trace&&Array.isArray(trace.attempts)?trace.attempts:[],received=attempts.some(a=>a&&typeof a==='object'&&'responseReceived'in a&&a.responseReceived===true),sent=attempts.some(a=>a&&typeof a==='object'&&'requestSent'in a&&a.requestSent===true),state=received?'completed':sent||!trace?'sent_unknown':'not_sent';return domain.failDialogueRound(bookId,claimed.receipt.id,state,trace?{...trace,durationMs:Date.now()-started}:null,failure?.message??'本轮模型回执尚未确认；原沙盘保留，只核对原请求，不再次调用。');}await domain.retainDialogueOutput(bookId,claimed.receipt.id,result.output,{...result.modelSnapshot,durationMs:Date.now()-started});return domain.completeDialogueOutput(bookId,claimed.receipt.id);}
