import type {KnowledgeEmbeddingReply} from "../../../common/knowledgeIndex";
import {getManagedCredentialEnvironment,readManagedEmbeddingConnectionVersion} from "../../database/modelManagement";
import * as db from "../../database/knowledgeIndex";
import {invokeKnowledgeEmbedding,KnowledgeEmbeddingTransportError,type EmbeddingConnection} from "../../ai/knowledgeEmbedding";
import {readKnowledgeEmbeddingReply,writeKnowledgeEmbeddingReply} from "../../ai/knowledgeEmbedding/receipts";
import {NewDesignError} from "../../domain/errors";
export {prepareKnowledgeIndexSchema,executeKnowledgeEmbeddingSchema,buildKnowledgeIndexSchema,searchKnowledgeSemanticSchema,createKnowledgeProfileSchema,KnowledgeEmbeddingError,KnowledgePreparationError,getKnowledgeIndexWorkspace,prepareKnowledgeIndex,getKnowledgeIndexByKey,buildKnowledgeIndex,getKnowledgeGenerationByKey,createKnowledgeProfile,getKnowledgeProfileByKey} from "../../database/knowledgeIndex";
export interface KnowledgeEmbeddingDependencies {fetcher?:typeof fetch}
async function connectionFor(freeze:db.EmbeddingFreeze):Promise<EmbeddingConnection>{return db.indexRead(async client=>{const version=await readManagedEmbeddingConnectionVersion(freeze.connectionVersionId,{client});if(version.connectionHash!==freeze.connectionHash||version.provider!==freeze.provider||version.model!==freeze.model)throw new NewDesignError("冻结向量模型版本不一致，请返回原模型设置核对。",409);if(version.maxRetries!==0)throw new NewDesignError("首次知识嵌入仅支持单次请求，请明确配置为不自动重试；不会忽略原重试设置。",422);const apiKey=await getManagedCredentialEnvironment(version.credentialId,version.provider,{client})??"";return{provider:version.provider,endpoint:version.endpoint,model:version.model,timeoutMs:version.timeoutMs,apiKey};});}
const transportState=(error:KnowledgeEmbeddingTransportError)=>error.responseReceived?"completed" as const:error.requestSent?"sent_unknown" as const:"not_sent" as const;
const refs=(bookId:string,requestId:string,attemptId:string,inputHash:string)=>({bookId,requestId,attemptId,inputHash});
export async function getKnowledgeEmbeddingResult(bookId:string,id:string){const receipt=await db.getKnowledgeEmbeddingRequest(bookId,id),original=await db.readKnowledgeEmbeddingFrozen(bookId,id);if(!original.reply&&original.attemptId){const local=await readKnowledgeEmbeddingReply(refs(bookId,id,original.attemptId,original.freeze.inputHash));if(local)return{...receipt,modelRequestState:"completed" as const,replySaved:true,replyStorage:"local_evidence" as const,usage:{knownInputTokens:local.inputTokens,unknownUsage:local.inputTokens===null},canCompleteSavedResult:original.status==="running"&&!original.leaseExpired};}return receipt;}
export async function executeKnowledgeEmbedding(bookId:string,id:string,input:import("../../../common/knowledgeIndex").ExecuteKnowledgeEmbeddingInput,dependencies:KnowledgeEmbeddingDependencies={}){
 const claim=await db.claimKnowledgeEmbedding(bookId,id,input);if(!claim.claimed)return getKnowledgeEmbeddingResult(bookId,id);let connection:EmbeddingConnection;
 try{connection=await connectionFor(claim.freeze);}catch(error){await db.failKnowledgeEmbedding(bookId,id,claim.attemptId,error instanceof NewDesignError?error.message:"原向量模型配置读取失败，尚未发送模型请求。","not_sent");throw new db.KnowledgeEmbeddingError(bookId,"读取明确选择的向量模型",error instanceof NewDesignError?error.message:"向量配置读取失败，尚未发送请求。","unknown","not_sent",error instanceof NewDesignError?error.status:503);}
 await db.markKnowledgeEmbeddingSending(bookId,id,claim.attemptId);let output:KnowledgeEmbeddingReply;
 try{output=await invokeKnowledgeEmbedding(connection,claim.text,claim.freeze.dimensions,claim.freeze.normalize,dependencies.fetcher);}catch(error){const safe=error instanceof KnowledgeEmbeddingTransportError?error:new KnowledgeEmbeddingTransportError("原嵌入调用回执未知，请核对原请求。",true,false),state=transportState(safe);await db.failKnowledgeEmbedding(bookId,id,claim.attemptId,safe.message,state,{requestSent:safe.requestSent,responseReceived:safe.responseReceived,inputTokens:safe.inputTokens});throw new db.KnowledgeEmbeddingError(bookId,"生成此分块的向量",safe.message,"unknown",state);}
 try{await writeKnowledgeEmbeddingReply(refs(bookId,id,claim.attemptId,claim.freeze.inputHash),output);}catch{throw new db.KnowledgeEmbeddingError(bookId,"保留原向量回复本地凭证","模型已回复，但本地保留尚未确认；不能重发原调用，请核对原请求与凭证。","unknown","completed");}
 await db.retainKnowledgeEmbeddingReply(bookId,id,claim.attemptId,output);return db.completeKnowledgeEmbeddingReply(bookId,id);
}
export async function completeSavedKnowledgeEmbedding(bookId:string,id:string){const original=await db.readKnowledgeEmbeddingFrozen(bookId,id);if(!original.reply){if(!original.attemptId)throw new db.KnowledgeEmbeddingError(bookId,"核对原向量回复","原尝试不存在，不能用另一份向量补写。","unknown","sent_unknown",409);const local=await readKnowledgeEmbeddingReply(refs(bookId,id,original.attemptId,original.freeze.inputHash));if(!local)throw new db.KnowledgeEmbeddingError(bookId,"核对原向量回复","未找到已保留的原回复；这不证明未调用，禁止重新生成。","unknown","sent_unknown",409);await db.retainKnowledgeEmbeddingReply(bookId,id,original.attemptId,local);}return db.completeKnowledgeEmbeddingReply(bookId,id);}
export async function getKnowledgeSemanticResult(bookId:string,id:string){const receipt=await db.getKnowledgeSemanticResult(bookId,id),original=await db.readKnowledgeSemanticFrozen(bookId,id);if(!original.reply){const local=await readKnowledgeEmbeddingReply(refs(bookId,id,id,original.freeze.inputHash));if(local)return{...receipt,modelRequestState:"completed" as const,replySaved:true,replyStorage:"local_evidence" as const,usage:{knownInputTokens:local.inputTokens,unknownUsage:local.inputTokens===null},canCompleteSavedResult:original.status==="running"&&!original.leaseExpired};}return receipt;}
export async function getKnowledgeSemanticByKey(bookId:string,key:string){const receipt=await db.getKnowledgeSemanticByKey(bookId,key);return receipt?getKnowledgeSemanticResult(bookId,receipt.run.id):null;}
export async function searchKnowledgeSemantic(bookId:string,input:import("../../../common/knowledgeIndex").SearchKnowledgeSemanticInput,dependencies:KnowledgeEmbeddingDependencies={}){const claim=await db.claimKnowledgeSemantic(bookId,input);if(!claim.claimed)return getKnowledgeSemanticResult(bookId,claim.id);let connection:EmbeddingConnection;
 try{connection=await connectionFor(claim.freeze);}catch(error){await db.failKnowledgeSemantic(bookId,claim.id,"not_sent");throw new db.KnowledgeEmbeddingError(bookId,"读取语义查询的向量模型",error instanceof NewDesignError?error.message:"向量模型配置读取失败，尚未发送请求。","unknown","not_sent",error instanceof NewDesignError?error.status:503);}
 await db.markKnowledgeSemanticSending(bookId,claim.id);let output:KnowledgeEmbeddingReply;try{output=await invokeKnowledgeEmbedding(connection,claim.freeze.query??"",claim.freeze.dimensions,claim.freeze.normalize,dependencies.fetcher);}catch(error){const safe=error instanceof KnowledgeEmbeddingTransportError?error:new KnowledgeEmbeddingTransportError("原查询嵌入回执未知，不能再次调用。",true,false),state=transportState(safe);await db.failKnowledgeSemantic(bookId,claim.id,state,{requestSent:safe.requestSent,responseReceived:safe.responseReceived,inputTokens:safe.inputTokens});throw new db.KnowledgeEmbeddingError(bookId,"生成语义查询向量",safe.message,"unknown",state);}
 try{await writeKnowledgeEmbeddingReply(refs(bookId,claim.id,claim.id,claim.freeze.inputHash),output);}catch{throw new db.KnowledgeEmbeddingError(bookId,"保留原查询向量本地凭证","模型已回复，但原查询向量的本地保留尚未确认；请核对原请求，不重发。","unknown","completed");}
 await db.retainKnowledgeSemanticReply(bookId,claim.id,output);return db.completeKnowledgeSemanticReply(bookId,claim.id);
}
export async function completeSavedKnowledgeSemantic(bookId:string,id:string){const original=await db.readKnowledgeSemanticFrozen(bookId,id);if(!original.reply){const local=await readKnowledgeEmbeddingReply(refs(bookId,id,id,original.freeze.inputHash));if(!local)throw new db.KnowledgeEmbeddingError(bookId,"核对原查询向量","没有找到原回复凭证，不能重新调用模型或用其他查询向量代替。","unknown","sent_unknown",409);await db.retainKnowledgeSemanticReply(bookId,id,local);}return db.completeKnowledgeSemanticReply(bookId,id);}
export async function endExpiredKnowledgeEmbedding(bookId:string,id:string){const original=await db.readKnowledgeEmbeddingFrozen(bookId,id);const local=original.reply??(original.attemptId?await readKnowledgeEmbeddingReply(refs(bookId,id,original.attemptId,original.freeze.inputHash)):null);return local?db.releaseExpiredKnowledgeEmbeddingReply(bookId,id,local):db.endExpiredKnowledgeEmbedding(bookId,id);}
export async function endExpiredKnowledgeSemantic(bookId:string,id:string){const original=await db.readKnowledgeSemanticFrozen(bookId,id),local=original.reply??await readKnowledgeEmbeddingReply(refs(bookId,id,id,original.freeze.inputHash));return local?db.releaseExpiredKnowledgeSemanticReply(bookId,id,local):db.endExpiredKnowledgeSemantic(bookId,id);}
