import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,lstat} from 'node:fs/promises';
import path from 'node:path';
import {comicExportManifestSchema,comicExportSubmitSchema,type ComicExportArtifact,type ComicExportManifest,type ComicExportManifestInput,type ComicExportReceipt,type ComicExportSubmitInput} from '../../common/comicRendering';
import {NewDesignError,assertFound} from '../domain/errors';
import {comicStableHash} from '../database/comicRendering';
import {getNewDesignPool} from '../database/runtime';
import {ensurePrivateRuntimeLayout,resolvePrivateRuntimeLayout,contained,assertNoReparseChain} from '../runtime/layout';
import {readVisualBytes} from '../database/visualAssets/files';

type Row=Record<string,any>;const date=(value:unknown)=>new Date(String(value)).toISOString();
async function capable(){if(!(await(await getNewDesignPool()).query("SELECT to_regclass('new_design.comic_export_manifests') IS NOT NULL ready")).rows[0].ready)throw new NewDesignError('漫画成图与导出手动迁移 117 尚未启用。',503);}
function manifest(row:Row):ComicExportManifest{return{id:String(row.id),projectId:String(row.project_id),variant:row.variant,sourceHash:String(row.source_hash),sourceSnapshot:row.source_snapshot,createdAt:date(row.created_at)};}
function artifact(row:Row):ComicExportArtifact{return{id:String(row.id),manifestId:String(row.manifest_id),variant:row.variant,filename:String(row.display_filename),mediaType:String(row.media_type),checksum:String(row.checksum),byteSize:Number(row.byte_size),downloadUrl:`/api/new-design/comic/exports/${row.id}/download`,createdAt:date(row.created_at)};}
async function currentSnapshot(projectId:string){const db=await getNewDesignPool(),project=assertFound((await db.query('SELECT id,title,comic_format,style_preset FROM new_design.comic_projects WHERE id=$1',[projectId])).rows[0],'漫画项目不存在。'),rows=(await db.query(`SELECT episode.id episode_id,episode.episode_order,episode.adopted_panel_set_id,panel.id panel_id,panel.panel_order,panel.action,panel.dialogues,panel.layout_data,state.adopted_version_id,version.content_object_id,content.checksum,content.byte_size,content.mime_type,content.storage_locator
FROM new_design.comic_episodes episode JOIN new_design.comic_panels panel ON panel.panel_set_id=episode.adopted_panel_set_id
LEFT JOIN new_design.comic_render_target_state state ON state.project_id=episode.project_id AND state.target_kind='panel' AND state.target_id=panel.id AND state.asset_type=''
LEFT JOIN new_design.comic_render_versions version ON version.id=state.adopted_version_id
LEFT JOIN new_design.asset_content_objects content ON content.id=version.content_object_id
WHERE episode.project_id=$1 ORDER BY episode.episode_order,panel.panel_order`,[projectId])).rows;if(!rows.length)throw new NewDesignError('尚无已采用整话分镜，不能导出漫画。',409);if(rows.some((row:Row)=>!row.adopted_version_id))throw new NewDesignError('仍有分格没有明确采用成图，请补齐后再预览导出。',409);return{project:{id:String(project.id),title:String(project.title),format:String(project.comic_format),style:String(project.style_preset)},panels:rows.map((row:Row)=>({episodeId:String(row.episode_id),episodeOrder:Number(row.episode_order),panelSetId:String(row.adopted_panel_set_id),panelId:String(row.panel_id),panelOrder:Number(row.panel_order),action:String(row.action),dialogues:row.dialogues,layoutData:row.layout_data,renderVersionId:String(row.adopted_version_id),contentObjectId:String(row.content_object_id),checksum:String(row.checksum),byteSize:Number(row.byte_size),mimeType:String(row.mime_type),storageLocator:String(row.storage_locator)}))};}
export async function previewComicExport(projectId:string,raw:ComicExportManifestInput):Promise<ComicExportManifest>{const input=comicExportManifestSchema.parse(raw);await capable();const db=await getNewDesignPool(),inputHash=comicStableHash({projectId,...input}),prior=(await db.query('SELECT * FROM new_design.comic_export_manifests WHERE request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.input_hash!==inputHash)throw new NewDesignError('原导出预览请求已用于其他输入。',409);return manifest(prior);}const snapshot=await currentSnapshot(projectId),sourceHash=comicStableHash(snapshot),id=randomUUID(),row=(await db.query('INSERT INTO new_design.comic_export_manifests(id,project_id,variant,source_snapshot,source_hash,request_key,input_hash) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7) RETURNING *',[id,projectId,input.variant,JSON.stringify(snapshot),sourceHash,input.requestKey,inputHash])).rows[0];return manifest(row);}
function escape(value:unknown){return String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));}
async function renderExport(item:ComicExportManifest){const snapshot=item.sourceSnapshot as any;if(item.variant==='project_manifest')return{bytes:Buffer.from(JSON.stringify({formatVersion:1,manifest:item},null,2),'utf8'),extension:'json',mediaType:'application/json'};const panels=[] as string[];for(const panel of snapshot.panels as any[]){const locator=String(panel.storageLocator);if(!locator.startsWith('visual-assets/'))throw new NewDesignError('导出引用了非受管漫画图片。',422);const bytes=await readVisualBytes(locator.slice(14),String(panel.checksum),Number(panel.byteSize),panel.mimeType),image=`data:${panel.mimeType};base64,${bytes.toString('base64')}`,bubbles=item.variant==='bubble_preview'?(panel.dialogues as any[]).map(dialogue=>`<p class="bubble ${escape(dialogue.bubbleType)}"><b>${escape(dialogue.speaker)}</b>${escape(dialogue.text)}</p>`).join(''):'';panels.push(`<article><h2>第 ${panel.episodeOrder} 话 · 第 ${panel.panelOrder} 格</h2><img src="${image}" alt="${escape(panel.action)}">${bubbles}</article>`);}const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(snapshot.project.title)}</title><style>body{max-width:900px;margin:auto;background:#111827;color:#f8fafc;font-family:sans-serif}article{margin:32px 0}img{width:100%;display:block}.bubble{background:white;color:#111;padding:12px 16px;border-radius:18px;margin:10px}.caption{border-radius:4px}</style><h1>${escape(snapshot.project.title)}</h1>${panels.join('')}</html>`;return{bytes:Buffer.from(html,'utf8'),extension:'html',mediaType:'text/html; charset=utf-8'};}
export async function createComicExport(projectId:string,raw:ComicExportSubmitInput):Promise<ComicExportReceipt>{const input=comicExportSubmitSchema.parse(raw);await capable();const db=await getNewDesignPool(),itemRow=assertFound((await db.query('SELECT * FROM new_design.comic_export_manifests WHERE id=$1 AND project_id=$2',[input.manifestId,projectId])).rows[0],'漫画导出预览不存在。'),item=manifest(itemRow);if(item.sourceHash!==input.expectedSourceHash)throw new NewDesignError('导出预览来源哈希不一致，请重新预览。',409);const inputHash=comicStableHash({projectId,...input}),prior=(await db.query('SELECT * FROM new_design.comic_export_artifacts WHERE request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.input_hash!==inputHash)throw new NewDesignError('原导出提交请求已用于其他清单。',409);return{manifest:item,artifact:artifact(prior),requestKey:input.requestKey,repeated:true};}if(comicStableHash(await currentSnapshot(projectId))!==item.sourceHash)throw new NewDesignError('来源已变化，请重新预览导出。',409);if(item.variant==='bubble_preview')for(const panel of (item.sourceSnapshot as any).panels as any[]){const bubbleHash=comicStableHash({renderVersionId:panel.renderVersionId,dialogues:panel.dialogues,layoutData:panel.layoutData});await db.query('INSERT INTO new_design.comic_bubble_outputs(id,render_version_id,dialogue_snapshot,layout_snapshot,source_hash) VALUES($1,$2,$3::jsonb,$4::jsonb,$5) ON CONFLICT(render_version_id,source_hash) DO NOTHING',[randomUUID(),panel.renderVersionId,JSON.stringify(panel.dialogues??[]),JSON.stringify(panel.layoutData??{}),bubbleHash]);}const output=await renderExport(item),layout=resolvePrivateRuntimeLayout();await ensurePrivateRuntimeLayout(layout);const folder=contained(layout.exportsDirectory,'comic',projectId);await mkdir(folder,{recursive:true});await assertNoReparseChain(layout.dataRoot,folder);const filename=`${item.variant}-${item.id}.${output.extension}`,target=contained(folder,filename),locator=`comic/${projectId}/${filename}`;await writeFile(target,output.bytes,{flag:'wx'});const checksum=createHash('sha256').update(output.bytes).digest('hex'),id=randomUUID();try{const row=(await db.query('INSERT INTO new_design.comic_export_artifacts(id,manifest_id,variant,storage_locator,display_filename,media_type,checksum,byte_size,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,item.id,item.variant,locator,filename,output.mediaType,checksum,output.bytes.length,input.requestKey,inputHash])).rows[0];return{manifest:item,artifact:artifact(row),requestKey:input.requestKey,repeated:false};}catch(error){throw new NewDesignError('导出文件已生成但登记结果未确认，请按原请求键只读核对。',503);}}
export async function listComicExports(projectId:string):Promise<ComicExportReceipt[]>{await capable();const db=await getNewDesignPool(),rows=(await db.query('SELECT manifest.*,artifact.id artifact_id,artifact.variant artifact_variant,artifact.display_filename,artifact.media_type,artifact.checksum artifact_checksum,artifact.byte_size artifact_byte_size,artifact.created_at artifact_created FROM new_design.comic_export_manifests manifest LEFT JOIN new_design.comic_export_artifacts artifact ON artifact.manifest_id=manifest.id WHERE manifest.project_id=$1 ORDER BY manifest.created_at DESC,manifest.id DESC LIMIT 50',[projectId])).rows;return rows.map((row:Row)=>({manifest:manifest(row),artifact:row.artifact_id?artifact({id:row.artifact_id,manifest_id:row.id,variant:row.artifact_variant,display_filename:row.display_filename,media_type:row.media_type,checksum:row.artifact_checksum,byte_size:row.artifact_byte_size,created_at:row.artifact_created}):null,requestKey:String(row.request_key),repeated:true}));}
export async function resolveComicExportDownload(id:string){await capable();const db=await getNewDesignPool(),row=assertFound((await db.query('SELECT * FROM new_design.comic_export_artifacts WHERE id=$1',[id])).rows[0],'漫画导出文件不存在。'),layout=resolvePrivateRuntimeLayout(),target=contained(layout.exportsDirectory,...String(row.storage_locator).split('/'));await assertNoReparseChain(layout.dataRoot,path.dirname(target));const info=await lstat(target);if(!info.isFile()||info.isSymbolicLink()||info.size!==Number(row.byte_size))throw new NewDesignError('漫画导出文件缺失或已变化。',503);const bytes=await readFile(target);if(createHash('sha256').update(bytes).digest('hex')!==row.checksum)throw new NewDesignError('漫画导出文件校验失败。',503);return{path:target,filename:String(row.display_filename),mediaType:String(row.media_type)};}
