import type {PoolClient} from "pg";
import type {KnowledgeContent,KnowledgeReferenceCandidate} from "../../../common/knowledgeReference";
import {NewDesignError,assertFound} from "../../domain/errors";
import {knowledgePool} from "./repository";
export async function readReadyKnowledgeRows(client:Pick<PoolClient,"query">,bookId:string,assetId?:string,q?:string){return(await client.query(`SELECT source.id asset_id,original.id source_version_id,source.title,parsed.asset_id parsed_asset_id,parsed.id parsed_version_id,resource.id resource_id,content.checksum,parsed.metadata->'knowledgeReference'->>'text' text FROM new_design.assets source JOIN new_design.asset_versions original ON original.id=source.current_version_id AND original.book_id=source.book_id AND original.metadata->'knowledgeReference'->>'kind'='source' JOIN new_design.asset_derivations request ON request.source_asset_version_id=original.id AND request.book_id=source.book_id AND request.status='succeeded' AND request.recipe_key='knowledge.utf8' JOIN new_design.assets output ON output.id=request.output_asset_id AND output.book_id=source.book_id AND output.status='active' JOIN new_design.asset_versions parsed ON parsed.id=output.current_version_id AND parsed.book_id=source.book_id AND parsed.metadata->'knowledgeReference'->>'kind'='parsed' JOIN new_design.asset_content_objects content ON content.id=parsed.content_object_id AND content.integrity_state='verified' AND jsonb_typeof(parsed.metadata->'knowledgeReference'->'text')='string' AND content.checksum=encode(sha256(convert_to(parsed.metadata->'knowledgeReference'->>'text','UTF8')),'hex') JOIN new_design.asset_derivation_results result ON result.derivation_id=request.id AND result.output_asset_version_id=parsed.id AND result.source_asset_version_id=original.id AND result.book_id=source.book_id AND result.outcome='applied' AND result.output_checksum=content.checksum JOIN new_design.dependency_resources resource ON resource.resource_kind='asset_version' AND resource.stable_object_id=parsed.asset_id AND resource.exact_version_id=parsed.id AND resource.book_id=source.book_id JOIN new_design.dependency_resource_states state ON state.resource_id=resource.id AND state.book_id=source.book_id AND state.state IN ('fresh','recomputed') WHERE source.book_id=$1 AND source.status='active' AND ($2::uuid IS NULL OR source.id=$2) AND ($3::text IS NULL OR position(lower($3) in lower(parsed.metadata->'knowledgeReference'->>'text'))>0) ORDER BY source.title,source.id LIMIT 101`,[bookId,assetId??null,q??null])).rows;}
/** Resolve a single exact derived version, never whichever historical derivation happens to sort first. */
export async function resolveReadyKnowledgeVersion(client:Pick<PoolClient,"query">,bookId:string,stableId:string,exactId:string|null){
 const source=(await client.query("SELECT source.id FROM new_design.assets source JOIN new_design.asset_derivations request ON request.source_asset_version_id=source.current_version_id AND request.book_id=source.book_id JOIN new_design.asset_derivation_results result ON result.derivation_id=request.id AND result.book_id=source.book_id AND result.outcome='applied' WHERE source.book_id=$1 AND request.output_asset_id=$2 AND result.output_asset_version_id=$3",[bookId,stableId,exactId])).rows;
 if(source.length!==1)return null;
 const rows=await readReadyKnowledgeRows(client,bookId,String(source[0].id));
 const matches=rows.filter(row=>row.parsed_asset_id===stableId&&row.parsed_version_id===exactId);
 return matches.length===1?matches[0]:null;
}
export async function getKnowledgeContent(bookId:string,id:string,input:{offset:number;limit:number;parsedVersionId?:string}):Promise<KnowledgeContent>{const client=await(await knowledgePool()).connect();try{const rows=await readReadyKnowledgeRows(client,bookId,id),row=assertFound(rows.length===1?rows[0]:null,"该资料尚未真实解析、已归档、已失效或存在需核对的重复解析来源，请返回知识参考核对状态。"),text=String(row.text);if(input.parsedVersionId&&input.parsedVersionId!==row.parsed_version_id)throw new NewDesignError("查看正文的精确解析版本已变化，请重新选择当前正文。",409);const end=Math.min(text.length,input.offset+input.limit);return{assetId:id,sourceVersionId:String(row.source_version_id),parsedAssetId:String(row.parsed_asset_id),parsedVersionId:String(row.parsed_version_id),checksum:String(row.checksum),title:String(row.title),text:text.slice(input.offset,end),offset:input.offset,totalCharacters:text.length,nextOffset:end<text.length?end:null,truncated:end<text.length||input.offset>0};}finally{client.release();}}
export async function getKnowledgeReferenceCandidates(bookId:string):Promise<{items:KnowledgeReferenceCandidate[];truncated:boolean}>{const client=await(await knowledgePool()).connect();try{const rows=await readReadyKnowledgeRows(client,bookId);return{items:rows.slice(0,100).map(row=>({assetId:String(row.asset_id),sourceVersionId:String(row.source_version_id),parsedAssetId:String(row.parsed_asset_id),parsedVersionId:String(row.parsed_version_id),resourceId:String(row.resource_id),checksum:String(row.checksum),title:String(row.title),excerpt:String(row.text).slice(0,1000)})),truncated:rows.length>100};}finally{client.release();}}
