import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {RESOURCE_KINDS,RESOURCE_LABELS,PROFESSIONAL_ROUTE,professionalCommandSchema,type ProfessionalCatalog,type ProfessionalCommand,type ProfessionalReceipt,type ProfessionalResource,type ProfessionalResourceKind,type ProfessionalResourcesApi,type ProfessionalTrialApi} from "../../common/professionalResources";
import DynamicForm from "../DynamicForm";
import ProfessionalTrial from "./Trial";
import "./professional-resources.css";
const STORAGE="new-design:professional-resource-command:v1";
function previousCommand():ProfessionalCommand|null{try{const parsed=professionalCommandSchema.safeParse(JSON.parse(sessionStorage.getItem(STORAGE)??"null"));return parsed.success?parsed.data:null;}catch{return null;}}
function outcome(error:unknown):"not_written"|"unknown"{if(error&&typeof error==="object"&&"recovery" in error&&error.recovery&&typeof error.recovery==="object"&&"mutationOutcome" in error.recovery&&error.recovery.mutationOutcome==="not_written")return "not_written";return "unknown";}
const STEP_LABELS:Record<ProfessionalCommand["operation"],string>={create:"保存新资源",edit:"保存原资源修订",archive:"归档原资源",favorite:"保存资源收藏",adopt_title:"明确采用标题到本书名称",install:"安装组合为本书独立快照",rule_settings:"保存质量规则启停与范围",feedback:"记录真实结果的作者反馈"};
function fieldIssues(error:unknown):Record<string,string>{if(!error||typeof error!=="object"||!("issues" in error)||!error.issues||typeof error.issues!=="object")return{};return Object.fromEntries(Object.entries(error.issues).filter(([key,value])=>key.length<=160&&typeof value==="string").map(([key])=>[key,"此项未满足原发布规格，请保留填写并核对允许值。"]));}
export default function ProfessionalResourcesPage({api,trialApi}:{api:ProfessionalResourcesApi;trialApi:ProfessionalTrialApi}){
 const [catalog,setCatalog]=useState<ProfessionalCatalog|null>(null),[kind,setKind]=useState<ProfessionalResourceKind>("title_candidate"),[selectedId,setSelectedId]=useState<string|null>(null),[creating,setCreating]=useState(false),[title,setTitle]=useState(""),[values,setValues]=useState<Record<string,unknown>>({}),[baseline,setBaseline]=useState(JSON.stringify({title:"",values:{}}));
 const [search,setSearch]=useState(""),[favoritesOnly,setFavoritesOnly]=useState(false),[includeArchived,setIncludeArchived]=useState(false),[bookId,setBookId]=useState(""),[installation,setInstallation]=useState<string[]>([]),[comparison,setComparison]=useState<string[]>([]),[pendingSelection,setPendingSelection]=useState<{id:string|null;kind:ProfessionalResourceKind}|null>(null);
 const [pending,setPending]=useState<ProfessionalCommand|null>(previousCommand),[busy,setBusy]=useState(false),[error,setError]=useState(""),[failedStep,setFailedStep]=useState(""),[receipt,setReceipt]=useState<ProfessionalReceipt|null>(null),[confirmation,setConfirmation]=useState<ProfessionalCommand|null>(null),[notice,setNotice]=useState(""),[resultId,setResultId]=useState<string|null>(null),[feedbackEffect,setFeedbackEffect]=useState<"helpful"|"neutral"|"harmful">("neutral"),[feedbackNote,setFeedbackNote]=useState("");
 const mounted=useRef(true),generation=useRef(0),query=useRef(new URLSearchParams(window.location.search)),initialized=useRef(false),dirtyRef=useRef(false);
 const [issues,setIssues]=useState<Record<string,string>>({});
 const selected=catalog?.resources.find(item=>item.id===selectedId)??null,type=creating?catalog?.types.find(item=>item.kind===kind)??null:null,fields=selected?.fields??type?.fields??[],book=catalog?.books.find(item=>item.id===bookId)??null,dirty=JSON.stringify({title,values})!==baseline;dirtyRef.current=dirty;
 const locked=busy||Boolean(pending),selectedActive=Boolean(selected?.status==="active"),key=()=>crypto.randomUUID(),source=()=>selected?{resourceId:selected.id,versionId:selected.versionId,expectedRevision:selected.revision}:null;
 const load=useCallback(async()=>{const current=++generation.current;const next=await api.catalog();if(!mounted.current||current!==generation.current)return null;setCatalog(next);return next;},[api]);
 const open=(item:ProfessionalResource|null,nextKind:ProfessionalResourceKind)=>{setSelectedId(item?.id??null);setKind(nextKind);setCreating(!item);setTitle(item?.title??"");setValues(item?.values??{});setBaseline(JSON.stringify({title:item?.title??"",values:item?.values??{}}));setIssues({});setError("");setFailedStep("");};
 useEffect(()=>{mounted.current=true;void load().then(next=>{if(!next||initialized.current)return;initialized.current=true;const ids=query.current.getAll("resource");if(ids.length){if(ids.length!==1||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(ids[0])){setFailedStep("定位原专业资源");setError("原资源凭证格式不正确，未选择其他资源代替。");return;}const item=next.resources.find(candidate=>candidate.id===ids[0].toLowerCase());if(!item){setFailedStep("定位原专业资源");setError("指定资源不存在于已加载列表，未选择其他候选代替；当前填写保留。");return;}open(item,item.kind);}}).catch(()=>{setFailedStep("读取专业资源目录");setError("原资源和人工填写保留，请只读刷新目录核对。");});return()=>{mounted.current=false;generation.current++;};},[load]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty||pending||feedbackNote){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty,pending,feedbackNote]);
 const remember=(input:ProfessionalCommand|null)=>{try{input?sessionStorage.setItem(STORAGE,JSON.stringify(input)):sessionStorage.removeItem(STORAGE);}catch{setNotice("浏览器未能持久保存请求凭证，请记下本页原凭证，刷新前保留人工填写。");}setPending(input);};
 const choose=(id:string|null,nextKind:ProfessionalResourceKind)=>{if(locked)return;if(dirtyRef.current){setPendingSelection({id,kind:nextKind});return;}const item=id?catalog?.resources.find(candidate=>candidate.id===id)??null:null;if(id&&!item){setError("所选资源未读取，当前填写保留，不用其他资源代替。");return;}open(item,nextKind);};
 const refresh=async()=>{if(busy)return;setBusy(true);try{await load();setNotice(dirtyRef.current?"目录已只读刷新，当前未保存填写没有被替换。":"目录已只读刷新；资源编辑和试验文本保持在本页。");}catch{setFailedStep("读取资源目录");setError("目录未读取，原资源、原请求及本页填写保留。");}finally{setBusy(false);}};
 const accept=async(saved:ProfessionalReceipt)=>{setReceipt(saved);remember(null);setError("");setFailedStep("");setConfirmation(null);setNotice(saved.retainedResult);try{const next=await load();if(saved.operation==="create"||saved.operation==="edit"||saved.operation==="rule_settings"||saved.operation==="archive"){const item=next?.resources.find(candidate=>candidate.id===saved.resourceIds[0]);if(item)open(item,item.kind);}}catch{setFailedStep("读取已保存资源回执后的目录");setError("原操作已经保存，回执保留；目录未读取，不重复原安装或采用。");}};
 const run=async(input:ProfessionalCommand)=>{if(locked)return;remember(input);setBusy(true);setFailedStep(STEP_LABELS[input.operation]);setError("");setIssues({});try{await accept(await api.command(input));}catch(error){setIssues(fieldIssues(error));if(outcome(error)==="not_written"){remember(null);setError("本次资源操作已确认未写入；原填写和资源保留，核对字段或底座后可明确重新提交。");}else setError("本次操作保存结果未确认；原请求与填写保留。先只读核对原回执，不重复安装、采用或新建。");}finally{setBusy(false);}};
 const check=async()=>{if(!pending||busy)return;setBusy(true);try{const saved=await api.receipt(pending.requestKey);if(saved)await accept(saved);else setError("原操作回执尚未读取到，不证明请求未提交；保持原请求凭证，继续只读核对。");}catch{setFailedStep("读取原资源操作回执");setError("读取失败不作废原操作；当前输入和原请求保持，恢复连接后继续核对。");}finally{setBusy(false);}};
 const completeOriginal=async()=>{if(!pending||busy)return;const original=pending;let writeAttempted=false;setBusy(true);setFailedStep(`按原凭证核对并完成${STEP_LABELS[original.operation]}`);setError("");try{const saved=await api.receipt(original.requestKey);if(saved){await accept(saved);return;}writeAttempted=true;await accept(await api.command(original));}catch(error){setIssues(fieldIssues(error));if(writeAttempted&&outcome(error)==="not_written"){if(original.operation==="create"||original.operation==="edit"){setTitle(original.title);setValues(original.values);}remember(null);setError("同一原操作已确认未写入，原完整填写保留；核对发布规格和版本后明确重新准备，不伪装已安装或采用。");}else setError("原凭证核对或同一原操作仍未确认，原完整输入和凭证保留；只读失败不证明原写入未提交，不换新凭证重复安装或采用。此恢复不含任何模型调用。");}finally{setBusy(false);}};
 const save=()=>{if(!title.trim())return;const reference=source();if(creating&&type)void run({operation:"create",requestKey:key(),typeId:type.id,title,values});else if(reference)void run({...reference,operation:"edit",requestKey:key(),title,values});};
 const visible=useMemo(()=>catalog?.resources.filter(item=>item.kind===kind&&(includeArchived||item.status==="active")&&(!favoritesOnly||item.favorite)&&(!search.trim()||item.title.toLowerCase().includes(search.trim().toLowerCase())))??[],[catalog,kind,includeArchived,favoritesOnly,search]);
 const requestInstall=()=>{if(!book||!catalog)return;const resources=installation.map(id=>catalog.resources.find(item=>item.id===id&&item.status==="active"&&item.kind!=="title_candidate"));if(resources.some(item=>!item)){setError("组合含未读取或已归档资源，保留选择并重新核对，不替换其他资源。");return;}setConfirmation({operation:"install",requestKey:key(),bookId:book.id,expectedBookRevision:book.revision,resources:resources.filter((item):item is ProfessionalResource=>Boolean(item)).map(item=>({resourceId:item.id,versionId:item.versionId,expectedRevision:item.revision}))});};
 return <div className="nd-shell nd-professional-page"><header className="nd-page-header"><div><p className="nd-eyebrow">新设计／创作资源</p><h1>专业创作资源</h1><p>标题比较、写法试验和质量规则统一维护；选择满意内容后明确采用或安装，本书与原资源始终独立。</p></div><a href="/new-design/resources">返回资源总览</a></header>
 <div className="nd-action-row"><button disabled={busy} onClick={()=>void refresh()} type="button">只读刷新资源目录</button><a href="/new-design/operations/records">查看原运行记录</a></div>
 {error&&<div className="nd-message is-error" role="alert"><p>未完成步骤：{failedStep||"核对资源填写"}</p><p>{error}</p><p>保留内容：原资源历史、本书资料、当前表单与试验文本。</p><a href="/new-design/structure/maintenance">检查运行维护（仅导航）</a></div>}{notice&&<p role="status">{notice}</p>}
 {!!Object.keys(issues).length&&<div className="nd-message is-error" role="alert"><p>需要核对的表单位置：</p><ul>{Object.entries(issues).map(([key,message])=><li key={key}>{key==="title"?"资源名称":fields.find(field=>field.key===key)?.name??"本次操作输入"}：{message}</li>)}</ul><p>回到当前资源编辑表单修正；原填写和已发布版本没有被替换。</p></div>}
 {pending&&<div className="nd-message" role="alert"><p>原操作：{STEP_LABELS[pending.operation]} · 原请求凭证 {pending.requestKey}</p><p>读取原回执只核对结果。需要完成时，先核对已保存回执；否则按原完整输入与同一凭证完成原数据库操作，不用当前选择替代，不调用模型。</p>{"resourceId" in pending&&<a href={`${PROFESSIONAL_ROUTE}?resource=${pending.resourceId}`}>打开原资源（仅导航，不重新提交）</a>}{"bookId" in pending&&<a href={`/new-design/books/${pending.bookId}/cards`}>查看原目标书籍资料</a>}<details><summary>核对原完整资源操作输入（只读）</summary><pre>{JSON.stringify(pending,null,2)}</pre></details><button disabled={busy} type="button" onClick={()=>void check()}>只读核对原操作回执</button><button disabled={busy} type="button" onClick={()=>void completeOriginal()}>按原凭证核对并完成原资源操作</button></div>}
 {pendingSelection&&<div className="nd-message" role="alert"><p>有未保存资源填写；切换只放弃本页未保存内容，不影响资源历史、本书或原试验。</p><button disabled={locked} onClick={()=>setPendingSelection(null)} type="button">保留填写，暂不切换</button><button disabled={locked} onClick={()=>{const next=pendingSelection;setPendingSelection(null);const item=next.id?catalog?.resources.find(candidate=>candidate.id===next.id)??null:null;if(next.id&&!item){setError("原选择已不在目录，填写保留，未切换。");return;}open(item,next.kind);}} type="button">放弃未保存填写并切换</button></div>}
 <div className="nd-professional-workspace"><aside className="nd-professional-catalog"><nav aria-label="专业资源分类">{RESOURCE_KINDS.map(item=><button disabled={locked} aria-pressed={kind===item} key={item} type="button" onClick={()=>choose(null,item)}>{RESOURCE_LABELS[item]} <small>{catalog?.resources.filter(resource=>resource.kind===item&&resource.status==="active").length??0}</small></button>)}</nav><label className="nd-control">搜索名称<input value={search} onChange={event=>setSearch(event.target.value)}/></label><label><input type="checkbox" checked={favoritesOnly} onChange={event=>setFavoritesOnly(event.target.checked)}/>仅收藏</label><label><input type="checkbox" checked={includeArchived} onChange={event=>setIncludeArchived(event.target.checked)}/>显示归档历史</label><div>{visible.map(item=><button disabled={locked} className={item.id===selectedId?"is-selected":""} aria-pressed={item.id===selectedId} key={item.id} type="button" onClick={()=>choose(item.id,item.kind)}><span>{item.favorite?"★ ":""}{item.title}</span><small>修订 {item.revision} · {item.status==="active"?"可使用":"已归档，只读"}</small></button>)}{!visible.length&&<p>没有匹配的原资源。可以新建并保存自己的资源，不生成空壳假成功。</p>}</div><button type="button" disabled={locked} onClick={()=>choose(null,kind)}>新建{RESOURCE_LABELS[kind]}</button></aside>
 <main><section className="nd-professional-editor"><header><h2>{creating?`新建${RESOURCE_LABELS[kind]}`:selected?.title??"选择原资源"}</h2><small>{selected?`原版本凭证：${selected.versionId}`:"使用已发布字段规格"}</small></header>{(selected||creating&&type)?<><fieldset disabled={locked||Boolean(selected&&!selectedActive)} style={{border:0,padding:0,margin:0}}><label className="nd-control">{kind==="title_candidate"?"书名候选":"资源名称"}<input maxLength={240} value={title} onChange={event=>setTitle(event.target.value)}/></label><DynamicForm fields={fields} values={values} onChange={setValues}/></fieldset><p role="status">{dirty?"当前填写未保存，刷新不替换。":"当前填写与原版本一致。"}</p><div className="nd-action-row"><button disabled={locked||!title.trim()||Boolean(selected&&!selectedActive)} type="button" onClick={save}>保存到原资源库</button>{selected&&selectedActive&&<><button disabled={locked||dirty} type="button" onClick={()=>{const reference=source();if(reference)void run({...reference,operation:"favorite",requestKey:key(),favorite:!selected.favorite});}}>{selected.favorite?"取消收藏":"收藏原资源"}</button><button disabled={locked||dirty} type="button" onClick={()=>{const reference=source();if(reference)setConfirmation({...reference,operation:"archive",requestKey:key()});}}>归档原资源（保留版本）</button></>}</div></>:<p>原内容类型尚未发布，当前填写保留。<a href="/new-design/structure/card-types">查看内容类型规格</a></p>}
 {selected?.kind==="title_candidate"&&<section><h3>中文标题比较</h3><p>比较读者承诺、受众和误导风险；收藏不等于采用，采用只改变目标书名。</p><label><input type="checkbox" checked={comparison.includes(selected.id)} onChange={event=>setComparison(event.target.checked?[...comparison,selected.id].slice(-4):comparison.filter(id=>id!==selected.id))}/>加入比较（最多四项）</label><div className="nd-professional-comparison">{comparison.map(id=>catalog?.resources.find(item=>item.id===id)).filter((item):item is ProfessionalResource=>Boolean(item&&item.kind==="title_candidate")).map(item=><article key={item.id}><h4>{item.title}</h4>{item.fields.map(field=><p key={field.key}>{field.name}：{String(item.values[field.key]??"未填写")}</p>)}</article>)}</div></section>}
 {selected?.kind==="quality_rule"&&<section><h3>质量规则启停与适用范围</h3><p>这里只调整原资源，已安装的书内规则保持独立。提醒和质量债不会自动升级成全书阻断。</p><fieldset disabled={locked||!selectedActive} style={{border:0,padding:0,margin:0}}><label><input checked={values.enabled===true} type="checkbox" onChange={event=>setValues({...values,enabled:event.target.checked})}/>启用原资源规则</label><div>{fields.find(field=>field.key==="check_scope")?.options.map(option=><label key={option.value}><input type="checkbox" checked={Array.isArray(values.check_scope)&&values.check_scope.includes(option.value)} onChange={event=>setValues({...values,check_scope:event.target.checked?[...(Array.isArray(values.check_scope)?values.check_scope:[]),option.value]:(Array.isArray(values.check_scope)?values.check_scope:[]).filter(item=>item!==option.value)})}/>{option.label}</label>)}</div></fieldset><p>修改后点击“保存到原资源库”，形成原规则新版本；需要用于书籍时再明确安装。</p></section>}
 </section>
 <section className="nd-professional-installation"><h2>明确采用与组合安装</h2><label className="nd-control">目标书籍<select disabled={locked} value={bookId} onChange={event=>setBookId(event.target.value)}><option value="">请选择真实目标书籍</option>{catalog?.books.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{selected?.kind==="title_candidate"&&<button disabled={locked||dirty||!selectedActive||!book} type="button" onClick={()=>{const reference=source();if(reference&&book)setConfirmation({...reference,operation:"adopt_title",requestKey:key(),bookId:book.id,expectedBookRevision:book.revision});}}>明确采用此标题为本书书名</button>}<fieldset disabled={locked} style={{border:0,padding:0,margin:0}}><legend>组合中的原资源（精确版本）</legend>{catalog?.resources.filter(item=>item.kind!=="title_candidate"&&item.status==="active").map(item=><label key={item.id}><input type="checkbox" checked={installation.includes(item.id)} onChange={event=>setInstallation(event.target.checked?[...installation,item.id]:installation.filter(id=>id!==item.id))}/>{RESOURCE_LABELS[item.kind]} · {item.title} · 修订 {item.revision}</label>)}</fieldset><button disabled={locked||dirty||!book||!installation.length||installation.length>20} type="button" onClick={requestInstall}>确认组合安装为本书独立快照</button></section>
 {confirmation&&<div className="nd-message" role="alert"><p>即将{STEP_LABELS[confirmation.operation]}。{confirmation.operation==="adopt_title"?`《${book?.name??"原目标书籍"}》名称将改变，正文不变。`:confirmation.operation==="install"?"全部选中资源一起成功或一起回滚，不覆盖现有资料；原资源更新不自动同步。":"仅归档原资源，历史与已安装的本书资料保留。"}</p><button disabled={locked} type="button" onClick={()=>setConfirmation(null)}>取消，保留当前选择</button><button disabled={locked} type="button" onClick={()=>void run(confirmation)}>明确确认本次操作</button></div>}
 <ProfessionalTrial api={trialApi} resource={selected} onResult={setResultId}/>
 {selected&&<section><h2>作者效果反馈</h2><p>只引用本页已保存的真实试运行。反馈是个人观察，不等于已验证修复或正式质量审计。</p><fieldset disabled={locked||!selectedActive} style={{border:0,padding:0,margin:0}}><label className="nd-control">效果<select value={feedbackEffect} onChange={event=>setFeedbackEffect(event.target.value as "helpful"|"neutral"|"harmful")}><option value="helpful">有帮助</option><option value="neutral">没有明显变化</option><option value="harmful">带来负面影响</option></select></label><label className="nd-control">具体观察<textarea value={feedbackNote} maxLength={2000} onChange={event=>setFeedbackNote(event.target.value)}/></label><button disabled={!resultId||!feedbackNote.trim()||dirty} type="button" onClick={()=>{const reference=source();if(reference&&resultId)void run({...reference,operation:"feedback",requestKey:key(),previewId:resultId,issueId:null,effect:feedbackEffect,note:feedbackNote});}}>保存对原试验的反馈</button></fieldset>{catalog?.feedback.filter(item=>item.resourceId===selected.id).map((item,index)=><article key={`${item.createdAt}:${index}`}><p>{item.effect==="helpful"?"有帮助":item.effect==="neutral"?"没有明显变化":"带来负面影响"}：{item.note}</p><a href={item.previewId?`/new-design/resources/ai/prompt-composition?previewId=${item.previewId}`:"/new-design/operations/records"}>查看原结果来源</a></article>)}</section>}
 {receipt&&<section><h2>原资源操作已保存回执</h2><p>{receipt.retainedResult}</p><small>原请求：{receipt.requestKey}</small>{receipt.bookId&&<a href={`/new-design/books/${receipt.bookId}/cards`}>查看原目标书籍资料</a>}</section>}
 </main></div><footer><small>专业资源入口：{PROFESSIONAL_ROUTE}；已归档原资源不影响既有书内快照。</small></footer></div>;
}
