import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {RESOURCE_KINDS,RESOURCE_LABELS,PROFESSIONAL_ROUTE,professionalCommandSchema,type ProfessionalCatalog,type ProfessionalCommand,type ProfessionalReceipt,type ProfessionalResource,type ProfessionalResourceKind,type ProfessionalResourcesApi,type ProfessionalTrialApi} from "../../common/professionalResources";
import DynamicForm from "../DynamicForm";
import {TreeNavigation,type TreeNavigationNode} from "../tree";
import {buildProfessionalResourceTree} from "./catalog";
import ProfessionalTrial from "./Trial";
import "./professional-resources.css";
import ResourceVersionHistory from './VersionHistory';
const STORAGE="new-design:professional-resource-command:v1";
function previousCommand():{input:ProfessionalCommand|null;blocked:boolean}{try{const raw=sessionStorage.getItem(STORAGE);if(raw===null)return{input:null,blocked:false};if(raw.length>1000000)return{input:null,blocked:true};const parsed=professionalCommandSchema.safeParse(JSON.parse(raw));return parsed.success?{input:parsed.data,blocked:false}:{input:null,blocked:true};}catch{return{input:null,blocked:true};}}
function outcome(error:unknown):"not_written"|"unknown"{if(error&&typeof error==="object"&&"recovery" in error&&error.recovery&&typeof error.recovery==="object"&&"mutationOutcome" in error.recovery&&error.recovery.mutationOutcome==="not_written")return "not_written";return "unknown";}
const STEP_LABELS:Record<ProfessionalCommand["operation"],string>={create:"保存新资源",edit:"保存原资源修订",archive:"归档原资源",favorite:"保存资源收藏",adopt_title:"明确采用标题到本书名称",install:"安装组合为本书独立快照",rule_settings:"保存质量规则启停与范围",feedback:"记录真实结果的作者反馈"};
function fieldIssues(error:unknown):Record<string,string>{if(!error||typeof error!=="object"||!("issues" in error)||!error.issues||typeof error.issues!=="object")return{};return Object.fromEntries(Object.entries(error.issues).filter(([key,value])=>key.length<=160&&typeof value==="string").map(([key])=>[key,"此项未满足原发布规格，请保留填写并核对允许值。"]));}
export default function ProfessionalResourcesPage({api,trialApi,initialKind='title_candidate',heading='资源工作台',kinds=RESOURCE_KINDS}:{api:ProfessionalResourcesApi;trialApi:ProfessionalTrialApi;initialKind?:ProfessionalResourceKind;heading?:string;kinds?:readonly ProfessionalResourceKind[]}){
 const recovered=useRef(previousCommand()),[storageBlocked,setStorageBlocked]=useState(recovered.current.blocked);
 const requestedKind=new URLSearchParams(location.search).get("type") as ProfessionalResourceKind|null;
 const [catalog,setCatalog]=useState<ProfessionalCatalog|null>(null),[kind,setKind]=useState<ProfessionalResourceKind>(requestedKind&&kinds.includes(requestedKind)?requestedKind:initialKind),[selectedId,setSelectedId]=useState<string|null>(null),[creating,setCreating]=useState(false),[title,setTitle]=useState(""),[values,setValues]=useState<Record<string,unknown>>({}),[baseline,setBaseline]=useState(JSON.stringify({title:"",values:{}}));
 const [search,setSearch]=useState(""),[favoritesOnly,setFavoritesOnly]=useState(false),[includeArchived,setIncludeArchived]=useState(false),[bookId,setBookId]=useState(""),[installation,setInstallation]=useState<string[]>([]),[comparison,setComparison]=useState<string[]>([]),[pendingSelection,setPendingSelection]=useState<{id:string|null;kind:ProfessionalResourceKind}|null>(null);
 const [pending,setPending]=useState<ProfessionalCommand|null>(recovered.current.input),[busy,setBusy]=useState(false),[error,setError]=useState(""),[failedStep,setFailedStep]=useState(""),[receipt,setReceipt]=useState<ProfessionalReceipt|null>(null),[confirmation,setConfirmation]=useState<ProfessionalCommand|null>(null),[notice,setNotice]=useState(""),[resultId,setResultId]=useState<string|null>(null),[feedbackEffect,setFeedbackEffect]=useState<"helpful"|"neutral"|"harmful">("neutral"),[feedbackNote,setFeedbackNote]=useState("");
 const mounted=useRef(true),generation=useRef(0),query=useRef(new URLSearchParams(window.location.search)),initialized=useRef(false),dirtyRef=useRef(false);
 const [issues,setIssues]=useState<Record<string,string>>({});
 const [selectedSnapshot,setSelectedSnapshot]=useState<ProfessionalResource|null>(null),[creationType,setCreationType]=useState<ProfessionalCatalog['types'][number]|null>(null);
 const selected=selectedSnapshot,type=creating?creationType:null,fields=selected?.fields??type?.fields??[],book=catalog?.books.find(item=>item.id===bookId)??null,dirty=JSON.stringify({title,values})!==baseline;dirtyRef.current=dirty;
 const latestResource=catalog?.resources.find(item=>item.id===selectedId),latestType=catalog?.types.find(item=>item.kind===kind);
 const editorChanged=Boolean(selected&&latestResource&&(selected.versionId!==latestResource.versionId||selected.revision!==latestResource.revision||selected.status!==latestResource.status)||creating&&type&&latestType&&type.typeVersionId!==latestType.typeVersionId);
 const publicOnly=kinds.length===1&&kinds[0]==='character';
 const publicEnabled=catalog?.publicCharactersCapability?.operational===true;
 const resourceLocked=busy||Boolean(pending)||storageBlocked||(selected?.kind??kind)==='character'&&!publicEnabled;
 const locked=busy||Boolean(pending)||storageBlocked,selectedActive=Boolean(selected?.status==="active"),key=()=>crypto.randomUUID(),source=()=>selected?{resourceId:selected.id,versionId:selected.versionId,expectedRevision:selected.revision}:null;
 const load=useCallback(async()=>{const current=++generation.current;const next=await api.catalog();if(!mounted.current||current!==generation.current)return null;setCatalog(next);return next;},[api]);
 const open=(item:ProfessionalResource|null,nextKind:ProfessionalResourceKind)=>{setSelectedId(item?.id??null);setSelectedSnapshot(item);setCreationType(item?null:catalog?.types.find(candidate=>candidate.kind===nextKind)??null);setKind(nextKind);setCreating(!item);setTitle(item?.title??"");setValues(item?.values??{});setBaseline(JSON.stringify({title:item?.title??"",values:item?.values??{}}));setIssues({});setError("");setFailedStep("");};
 useEffect(()=>{mounted.current=true;void load().then(next=>{if(!next||initialized.current)return;initialized.current=true;const ids=query.current.getAll("resource");if(ids.length){if(ids.length!==1||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(ids[0])){setFailedStep("定位原专业资源");setError("原资源凭证格式不正确，未选择其他资源代替。");return;}const item=next.resources.find(candidate=>candidate.id===ids[0].toLowerCase());if(!item){setFailedStep("定位原专业资源");setError("指定资源不存在于已加载列表，未选择其他候选代替；当前填写保留。");return;}open(item,item.kind);}}).catch(()=>{setFailedStep("读取专业资源目录");setError("原资源和人工填写保留，请只读刷新目录核对。");});return()=>{mounted.current=false;generation.current++;};},[load]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty||pending||feedbackNote){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty,pending,feedbackNote]);
 const remember=(input:ProfessionalCommand|null):boolean=>{try{if(input){const raw=JSON.stringify(input);sessionStorage.setItem(STORAGE,raw);if(sessionStorage.getItem(STORAGE)!==raw)throw new Error("原输入未完整保留");}else{sessionStorage.removeItem(STORAGE);if(sessionStorage.getItem(STORAGE)!==null)throw new Error("原标记未清除");}}catch{setStorageBlocked(true);setNotice("浏览器不能完整保留或读取原请求凭证，已锁定写入；当前填写及已确认回执保留，请核对网站存储，不换新凭证重发。");return false;}setPending(input);return true;};
 const choose=(id:string|null,nextKind:ProfessionalResourceKind)=>{if(locked)return;if(dirtyRef.current){setPendingSelection({id,kind:nextKind});return;}const item=id?catalog?.resources.find(candidate=>candidate.id===id)??null:null;if(id&&!item){setError("所选资源未读取，当前填写保留，不用其他资源代替。");return;}open(item,nextKind);};
 const refresh=async()=>{if(busy)return;setBusy(true);try{await load();setNotice(dirtyRef.current?"目录已只读刷新，当前未保存填写没有被替换。":"目录已只读刷新；资源编辑和试验文本保持在本页。");}catch{setFailedStep("读取资源目录");setError("目录未读取，原资源、原请求及本页填写保留。");}finally{setBusy(false);}};
 const accept=async(saved:ProfessionalReceipt)=>{setReceipt(saved);remember(null);setError("");setFailedStep("");setConfirmation(null);setNotice(saved.retainedResult);try{const next=await load();if(saved.operation==="create"||saved.operation==="edit"||saved.operation==="rule_settings"||saved.operation==="archive"||saved.operation==="favorite"){const item=next?.resources.find(candidate=>candidate.id===saved.resourceIds[0]);if(item)open(item,item.kind);}}catch{setFailedStep("读取已保存资源回执后的目录");setError("原操作已经保存，回执保留；目录未读取，不重复原安装或采用。");}};
 const run=async(input:ProfessionalCommand)=>{if(resourceLocked||!remember(input))return;setBusy(true);setFailedStep(STEP_LABELS[input.operation]);setError("");setIssues({});try{await accept(await api.command(input));}catch(error){setIssues(fieldIssues(error));if(outcome(error)==="not_written"){remember(null);setError("本次资源操作已确认未写入；原填写和资源保留，核对字段或底座后可明确重新提交。");}else setError("本次操作保存结果未确认；原请求与填写保留。先只读核对原回执，不重复安装、采用或新建。");}finally{setBusy(false);}};
 const check=async()=>{if(!pending||busy)return;setBusy(true);try{const saved=await api.receipt(pending.requestKey);if(saved)await accept(saved);else setError("原操作回执尚未读取到，不证明请求未提交；保持原请求凭证，继续只读核对。");}catch{setFailedStep("读取原资源操作回执");setError("读取失败不作废原操作；当前输入和原请求保持，恢复连接后继续核对。");}finally{setBusy(false);}};
 const completeOriginal=async()=>{if(!pending||busy||storageBlocked)return;const original=pending;let writeAttempted=false;setBusy(true);setFailedStep(`按原凭证核对并完成${STEP_LABELS[original.operation]}`);setError("");try{const saved=await api.receipt(original.requestKey);if(saved){await accept(saved);return;}writeAttempted=true;await accept(await api.command(original));}catch(error){setIssues(fieldIssues(error));if(writeAttempted&&outcome(error)==="not_written"){if(original.operation==="create"||original.operation==="edit"){setTitle(original.title);setValues(original.values);}remember(null);setError("同一原操作已确认未写入，原完整填写保留；核对发布规格和版本后明确重新准备，不伪装已安装或采用。");}else setError("原凭证核对或同一原操作仍未确认，原完整输入和凭证保留；只读失败不证明原写入未提交，不换新凭证重复安装或采用。此恢复不含任何模型调用。");}finally{setBusy(false);}};
 const save=()=>{if(resourceLocked||!title.trim())return;const reference=source();if(creating&&type)void run({operation:"create",requestKey:key(),typeId:type.id,expectedTypeVersionId:type.typeVersionId,title,values});else if(reference)void run({...reference,operation:"edit",requestKey:key(),title,values});};
 const directory=useMemo(()=>buildProfessionalResourceTree(catalog?.resources??[],{search,favoritesOnly,includeArchived},kinds),[catalog,includeArchived,favoritesOnly,search,kinds]);
 const directoryNodes:TreeNavigationNode[]=directory.map(category=>({...category,expandable:true,body:category.children?.length?undefined:<p className="nd-help-text">此分类没有符合筛选条件的资源。</p>,actions:<button type="button" disabled={locked||!catalog?.types.some(item=>item.kind===category.kind)||category.kind==="character"&&!publicEnabled} title={`新建${category.name}`} aria-label={`新建${category.name}`} onClick={()=>choose(null,category.kind)}>＋</button>,children:category.children?.map(node=>({...node,onSelect:()=>choose(node.resource!.id,node.kind),badge:node.resource?.status==="archived"?"已归档":undefined,leading:node.resource?.favorite?<svg className="nd-professional-favorite" viewBox="0 0 20 20" aria-label="已收藏" role="img"><path d="m10 2.5 2.3 4.8 5.2.7-3.7 3.7.9 5.3-4.7-2.5-4.7 2.5.9-5.3L2.5 8l5.2-.7Z"/></svg>:undefined}))}));
 const requestInstall=()=>{if(!book||!catalog)return;const resources=installation.map(id=>catalog.resources.find(item=>item.id===id&&item.status==="active"&&item.kind!=="title_candidate"&&item.kind!=="character"));if(resources.some(item=>!item)){setError("组合含未读取或已归档资源，保留选择并重新核对，不替换其他资源。");return;}setConfirmation({operation:"install",requestKey:key(),bookId:book.id,expectedBookRevision:book.revision,resources:resources.filter((item):item is ProfessionalResource=>Boolean(item)).map(item=>({resourceId:item.id,versionId:item.versionId,expectedRevision:item.revision}))});};
 return <div className="nd-shell nd-professional-page"><header className="nd-page-header"><div><p className="nd-eyebrow">新设计／创作资源</p><h1>{heading}</h1><p>{publicOnly?"创建和维护可复用的角色样本，核对固定历史版本，再通过字段映射导入书内独立人物。":"编辑、比较和试用标题、写法与质量规则；满意后确认采用或加入本书，本书内容与公共资源独立保存。"}</p></div><a href="/new-design/resources">返回资源总览</a>{publicOnly&&<a href="/new-design/resources/characters">导入角色到书籍</a>}</header>
 {publicOnly&&!publicEnabled&&<p role="status">公共角色样本管理未启用。可以只读核对已有版本，或通过公共角色导入使用有效样本；书内人物不会自动公开。</p>}
 <div className="nd-action-row"><button disabled={busy} onClick={()=>void refresh()} type="button">只读刷新资源目录</button><a href="/new-design/operations/records">查看原运行记录</a></div>
 {error&&<div className="nd-message is-error" role="alert"><p>未完成步骤：{failedStep||"核对资源填写"}</p><p>{error}</p><p>保留内容：原资源历史、本书资料、当前表单与试验文本。</p><a href="/new-design/structure/maintenance">检查运行维护（仅导航）</a></div>}{notice&&<p role="status">{notice}</p>}
 {!!Object.keys(issues).length&&<div className="nd-message is-error" role="alert"><p>需要核对的表单位置：</p><ul>{Object.entries(issues).map(([key,message])=><li key={key}>{key==="title"?"资源名称":fields.find(field=>field.key===key)?.name??"本次操作输入"}：{message}</li>)}</ul><p>回到当前资源编辑表单修正；原填写和已发布版本没有被替换。</p></div>}
 {storageBlocked&&<p role="alert">原资源操作凭证不能完整读取或保留，写入锁定；原浏览器记录和当前填写保留，不覆盖损坏凭证。</p>}{pending&&<div className="nd-message" role="alert"><p>原操作：{STEP_LABELS[pending.operation]} · 原请求凭证 {pending.requestKey}</p><p>读取原回执只核对结果。需要完成时，先核对已保存回执；否则按原完整输入与同一凭证完成原数据库操作，不用当前选择替代，不调用模型。</p>{"resourceId" in pending&&<a href={`${PROFESSIONAL_ROUTE}?resource=${pending.resourceId}`}>打开原资源（仅导航，不重新提交）</a>}{"bookId" in pending&&<a href={`/new-design/books/${pending.bookId}/cards`}>查看原目标书籍资料</a>}<details><summary>核对原完整资源操作输入（只读）</summary><pre>{JSON.stringify(pending,null,2)}</pre></details><button disabled={busy} type="button" onClick={()=>void check()}>只读核对原操作回执</button><button disabled={busy||storageBlocked} type="button" onClick={()=>void completeOriginal()}>按原凭证核对并完成原资源操作</button></div>}
 {editorChanged&&<div className="nd-message" role="alert"><p>目录中的原资源或填写规格已经变化。当前填写和原版本凭证保留，保存会核对原版本。</p><details><summary>核对最新版本与规格（只读）</summary><pre>{JSON.stringify(selected?latestResource:latestType,null,2)}</pre></details><button type="button" disabled={resourceLocked||Boolean(selected&&latestResource?.status!=='active')} onClick={()=>{if(selected&&latestResource)setSelectedSnapshot(latestResource);else if(creating&&latestType)setCreationType(latestType);setConfirmation(null);setNotice('已明确改用核对后的版本；原填写保留，未匹配字段仍须检查，不会静默删除。');}}>核对后使用新版，保留当前填写</button></div>}
 {pendingSelection&&<div className="nd-message" role="alert"><p>有未保存资源填写；切换只放弃本页未保存内容，不影响资源历史、本书或原试验。</p><button disabled={locked} onClick={()=>setPendingSelection(null)} type="button">保留填写，暂不切换</button><button disabled={locked} onClick={()=>{const next=pendingSelection;setPendingSelection(null);const item=next.id?catalog?.resources.find(candidate=>candidate.id===next.id)??null:null;if(next.id&&!item){setError("原选择已不在目录，填写保留，未切换。");return;}open(item,next.kind);}} type="button">放弃未保存填写并切换</button></div>}
 <div className="nd-professional-workspace"><aside className="nd-professional-catalog"><label className="nd-control">资源目录<input value={search} placeholder="搜索资源名称或类型" onChange={event=>setSearch(event.target.value)}/></label><div className="nd-professional-filters"><label><input type="checkbox" checked={favoritesOnly} onChange={event=>setFavoritesOnly(event.target.checked)}/>仅收藏</label><label><input type="checkbox" checked={includeArchived} onChange={event=>setIncludeArchived(event.target.checked)}/>显示归档历史</label></div><TreeNavigation label="资源类型与具体资源目录" nodes={directoryNodes} selectedIds={selectedId?[`resource:${selectedId}`]:creating?[`kind:${kind}`]:[]} initialExpandedIds={[`kind:${kind}`]} query={search} disabled={locked} emptyText={catalog?"没有匹配资源，请调整搜索或筛选条件。":"资源目录尚未读取，请只读刷新目录。"}/><p className="nd-help-text">展开分类选择资源；点击分类旁的加号新建。</p></aside>
 <main><section className="nd-professional-editor"><header><h2>{creating?`新建${RESOURCE_LABELS[kind]}`:selected?.title??"选择原资源"}</h2><small>{selected?`原版本凭证：${selected.versionId}`:"使用已发布字段规格"}</small></header>{(selected||creating&&type)?<><fieldset disabled={resourceLocked||Boolean(selected&&!selectedActive)} style={{border:0,padding:0,margin:0}}><label className="nd-control">{kind==="title_candidate"?"书名候选":"资源名称"}<input maxLength={240} value={title} onChange={event=>setTitle(event.target.value)}/></label><DynamicForm fields={fields} values={values} onChange={setValues}/></fieldset><p role="status">{dirty?"当前填写未保存，刷新不替换。":"当前填写与原版本一致。"}</p><div className="nd-action-row"><button disabled={resourceLocked||!title.trim()||Boolean(selected&&!selectedActive)} type="button" onClick={save}>保存到原资源库</button>{selected&&selectedActive&&<><button disabled={resourceLocked||dirty} type="button" onClick={()=>{const reference=source();if(reference)void run({...reference,operation:"favorite",requestKey:key(),favorite:!selected.favorite});}}>{selected.favorite?"取消收藏":"收藏原资源"}</button><button disabled={resourceLocked||dirty} type="button" onClick={()=>{const reference=source();if(reference)setConfirmation({...reference,operation:"archive",requestKey:key()});}}>归档原资源（保留版本）</button></>}</div></>:<p>原内容类型尚未发布，当前填写保留。<a href="/new-design/structure/card-types">查看内容类型规格</a></p>}
 {selected?.kind==="title_candidate"&&<section><h3>中文标题比较</h3><p>比较读者承诺、受众和误导风险；收藏不等于采用，采用只改变目标书名。</p><label><input type="checkbox" checked={comparison.includes(selected.id)} onChange={event=>setComparison(event.target.checked?[...comparison,selected.id].slice(-4):comparison.filter(id=>id!==selected.id))}/>加入比较（最多四项）</label><div className="nd-professional-comparison">{comparison.map(id=>catalog?.resources.find(item=>item.id===id)).filter((item):item is ProfessionalResource=>Boolean(item&&item.kind==="title_candidate")).map(item=><article key={item.id}><h4>{item.title}</h4>{item.fields.map(field=><p key={field.key}>{field.name}：{String(item.values[field.key]??"未填写")}</p>)}</article>)}</div></section>}
 {selected?.kind==="quality_rule"&&<section><h3>质量规则启停与适用范围</h3><p>这里只调整原资源，已安装的书内规则保持独立。提醒和质量债不会自动升级成全书阻断。</p><fieldset disabled={locked||!selectedActive} style={{border:0,padding:0,margin:0}}><label><input checked={values.enabled===true} type="checkbox" onChange={event=>setValues({...values,enabled:event.target.checked})}/>启用原资源规则</label><div>{fields.find(field=>field.key==="check_scope")?.options.map(option=><label key={option.value}><input type="checkbox" checked={Array.isArray(values.check_scope)&&values.check_scope.includes(option.value)} onChange={event=>setValues({...values,check_scope:event.target.checked?[...(Array.isArray(values.check_scope)?values.check_scope:[]),option.value]:(Array.isArray(values.check_scope)?values.check_scope:[]).filter(item=>item!==option.value)})}/>{option.label}</label>)}</div></fieldset><p>修改后点击“保存到原资源库”，形成原规则新版本；需要用于书籍时再明确安装。</p></section>}
 </section>
 {!publicOnly&&<section className="nd-professional-installation"><h2>明确采用与组合安装</h2><label className="nd-control">目标书籍<select disabled={locked} value={bookId} onChange={event=>setBookId(event.target.value)}><option value="">请选择真实目标书籍</option>{catalog?.books.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{selected?.kind==="title_candidate"&&<button disabled={locked||dirty||!selectedActive||!book} type="button" onClick={()=>{const reference=source();if(reference&&book)setConfirmation({...reference,operation:"adopt_title",requestKey:key(),bookId:book.id,expectedBookRevision:book.revision});}}>明确采用此标题为本书书名</button>}<fieldset disabled={locked} style={{border:0,padding:0,margin:0}}><legend>组合中的原资源（精确版本）</legend>{catalog?.resources.filter(item=>item.kind!=="title_candidate"&&item.kind!=="character"&&item.status==="active").map(item=><label key={item.id}><input type="checkbox" checked={installation.includes(item.id)} onChange={event=>setInstallation(event.target.checked?[...installation,item.id]:installation.filter(id=>id!==item.id))}/>{RESOURCE_LABELS[item.kind]} · {item.title} · 修订 {item.revision}</label>)}</fieldset><button disabled={locked||dirty||!book||!installation.length||installation.length>20} type="button" onClick={requestInstall}>确认组合安装为本书独立快照</button></section>}
 {confirmation&&<div className="nd-message" role="alert"><p>即将{STEP_LABELS[confirmation.operation]}。{confirmation.operation==="adopt_title"?`《${book?.name??"原目标书籍"}》名称将改变，正文不变。`:confirmation.operation==="install"?"全部选中资源一起成功或一起回滚，不覆盖现有资料；原资源更新不自动同步。":"仅归档原资源，历史与已安装的本书资料保留。"}</p><button disabled={locked} type="button" onClick={()=>setConfirmation(null)}>取消，保留当前选择</button><button disabled={resourceLocked} type="button" onClick={()=>void run(confirmation)}>明确确认本次操作</button></div>}
 {selected?.kind==="character"&&<a className="nd-button" href={`/new-design/resources/characters/workshop?resource=${selected.id}&version=${selected.versionId}`}>按此固定版本试聊与生成图片</a>}{selected&&<ResourceVersionHistory key={selected.id} resource={selected}/>}{!publicOnly&&selected?.kind!=="character"&&<ProfessionalTrial api={trialApi} resource={selected} onResult={setResultId}/>}
 {selected&&selected.kind!=="character"&&<section><h2>作者效果反馈</h2><p>只引用本页已保存的真实试运行。反馈是个人观察，不等于已验证修复或正式质量审计。</p><fieldset disabled={locked||!selectedActive} style={{border:0,padding:0,margin:0}}><label className="nd-control">效果<select value={feedbackEffect} onChange={event=>setFeedbackEffect(event.target.value as "helpful"|"neutral"|"harmful")}><option value="helpful">有帮助</option><option value="neutral">没有明显变化</option><option value="harmful">带来负面影响</option></select></label><label className="nd-control">具体观察<textarea value={feedbackNote} maxLength={2000} onChange={event=>setFeedbackNote(event.target.value)}/></label><button disabled={!resultId||!feedbackNote.trim()||dirty} type="button" onClick={()=>{const reference=source();if(reference&&resultId)void run({...reference,operation:"feedback",requestKey:key(),previewId:resultId,issueId:null,effect:feedbackEffect,note:feedbackNote});}}>保存对原试验的反馈</button></fieldset>{catalog?.feedback.filter(item=>item.resourceId===selected.id).map((item,index)=><article key={`${item.createdAt}:${index}`}><p>{item.effect==="helpful"?"有帮助":item.effect==="neutral"?"没有明显变化":"带来负面影响"}：{item.note}</p><a href={item.previewId?`/new-design/resources/ai/prompt-composition?previewId=${item.previewId}`:"/new-design/operations/records"}>查看原结果来源</a></article>)}</section>}
 {receipt&&<section><h2>原资源操作已保存回执</h2><p>{receipt.retainedResult}</p><small>原请求：{receipt.requestKey}</small>{receipt.bookId&&<a href={`/new-design/books/${receipt.bookId}/cards`}>查看原目标书籍资料</a>}</section>}
 </main></div><footer><small>专业资源入口：{PROFESSIONAL_ROUTE}；已归档原资源不影响既有书内快照。</small></footer></div>;
}
