import {useEffect,useMemo,useRef,useState} from "react";
import {DEFAULT_DEBUG_PARAMETERS,COMPOSITION_ROUTE,type CompositionCatalog,type CompositionDebugPreview,type CompositionDebugResult} from "../../common/promptComposition";
import type {ProfessionalResource,ProfessionalTrialApi} from "../../common/professionalResources";
const STORAGE="new-design:professional-trial:v1";
type Pending={kind:"preview";key:string}|{kind:"run";key:string;previewId:string};
function readPending():Pending|null{try{const value:unknown=JSON.parse(sessionStorage.getItem(STORAGE)??"null");if(!value||typeof value!=="object"||!("kind" in value)||!("key" in value)||typeof value.key!=="string")return null;if(value.kind==="preview")return{kind:"preview",key:value.key};if(value.kind==="run"&&"previewId" in value&&typeof value.previewId==="string"&&/^[0-9a-f-]{36}$/i.test(value.previewId))return{kind:"run",key:value.key,previewId:value.previewId};return null;}catch{return null;}}
function ResultValue({value,resource,depth=0}:{value:unknown;resource:ProfessionalResource|null;depth?:number}){
 if(value===null||value===undefined)return <span>无</span>;if(depth>8)return <span>完整内容保留在原试运行页面。</span>;
 if(Array.isArray(value))return <ol>{value.slice(0,100).map((item,index)=><li key={index}><ResultValue value={item} resource={resource} depth={depth+1}/></li>)}</ol>;
 if(typeof value==="object"){const labels:Record<string,string>={overview:"总体结论",summary:"概要",dimensions:"分析项目",key:"检查项目",evidence:"依据",excerpt:"原文摘录",note:"说明",strengths:"优势",risks:"风险",opportunities:"改进方向",candidates:"参考候选",title:"名称",rationale:"理由",confidence:"把握程度",copyrightBoundary:"引用边界",questions:"待确认问题",suggestions:"表单建议",values:"填写内容",description:"说明",reason:"理由",score:"评估"};return <dl>{Object.entries(value).slice(0,100).map(([key,item],index)=><div key={key}><dt>{resource?.fields.find(field=>field.key===key)?.name??labels[key]??`结果项 ${index+1}`}</dt><dd><ResultValue value={item} resource={resource} depth={depth+1}/></dd></div>)}</dl>;}
 const choices:Record<string,string>={high:"较高",medium:"中等",low:"较低",story_structure:"故事结构",characters:"人物塑造",world:"世界设定",conflict:"冲突",pacing:"节奏",hooks_payoffs:"悬念与回收",writing_technique:"写作技巧",quality_risks:"质量风险"};return <span>{typeof value==="boolean"?value?"是":"否":choices[String(value)]??String(value)}</span>;
}
export default function ProfessionalTrial({api,resource,onResult}:{api:ProfessionalTrialApi;resource:ProfessionalResource|null;onResult(id:string|null):void}){
 const [catalog,setCatalog]=useState<CompositionCatalog|null>(null),[recipeId,setRecipeId]=useState(""),[text,setText]=useState(""),[instruction,setInstruction]=useState(""),[variables,setVariables]=useState<Record<string,string|number|boolean>>({});
 const [preview,setPreview]=useState<CompositionDebugPreview|null>(null),[result,setResult]=useState<CompositionDebugResult|null>(null),[pending,setPending]=useState<Pending|null>(readPending),[busy,setBusy]=useState(false),[error,setError]=useState(""),[fingerprint,setFingerprint]=useState("");
 const mounted=useRef(true),attempted=useRef(new Set<string>()),frozenResource=useRef<{id:string;versionId:string}|null>(null);
 useEffect(()=>{if(frozenResource.current?.id!==resource?.id||frozenResource.current?.versionId!==resource?.versionId)onResult(null);},[resource?.id,resource?.versionId,onResult]);
 useEffect(()=>{mounted.current=true;void api.catalog().then(value=>{if(mounted.current)setCatalog(value);}).catch(()=>{if(mounted.current)setError("未完成步骤：读取正式组合。原资源与试验文本保留，打开组合页检查后重新读取。");});return()=>{mounted.current=false;};},[api]);
 const recipes=useMemo(()=>catalog?.recipes.filter(item=>item.editable&&item.taskType==="book_analysis"&&item.context.bookId)??[],[catalog]);const recipe=recipes.find(item=>item.id===recipeId)??null;
 const currentFingerprint=JSON.stringify({recipeId,recipeVersionId:recipe?.versionId,text,instruction,variables,resourceId:resource?.id,resourceVersionId:resource?.versionId});
 const locked=busy||Boolean(pending),fresh=Boolean(preview&&fingerprint===currentFingerprint),sourceRoute=COMPOSITION_ROUTE+(preview?`?previewId=${preview.id}`:"");
 const remember=(next:Pending|null)=>{try{next?sessionStorage.setItem(STORAGE,JSON.stringify(next)):sessionStorage.removeItem(STORAGE);}catch{setError("浏览器未能保留原请求凭证，请记下页面凭证后核对；不要重新调用。");}setPending(next);};
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(text||instruction||pending){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[text,instruction,pending]);
 const prepare=async()=>{if(!recipe||!text.trim()||locked)return;const data=JSON.stringify({request:instruction,resource:resource?{id:resource.id,versionId:resource.versionId,title:resource.title,fields:resource.fields.map(field=>({name:field.name,value:resource.values[field.key]}))}:null});if(data.length>30000){setError("未完成步骤：核对试验输入范围。原资源加本次要求超过 30000 字符，尚未提交预览或调用模型；请选择较小资源或减少要求，原内容不裁剪。");return;}const key=crypto.randomUUID();frozenResource.current=resource?{id:resource.id,versionId:resource.versionId}:null;remember({kind:"preview",key});setBusy(true);setError("");try{const next=await api.preview({recipeId:recipe.id,recipeVersionId:recipe.versionId,parameters:{...structuredClone(DEFAULT_DEBUG_PARAMETERS),sourceText:text,sourceReference:"作者提供的局部试验文本",instruction:data,analysis:{purpose:"diagnosis",preset:"standard",dimensions:["writing_technique","quality_risks"]}},variableValues:variables,idempotencyKey:key});setPreview(next);setResult(null);onResult(null);setFingerprint(currentFingerprint);remember(null);}catch{setError("未完成步骤：保存冻结试验预览。原输入和资源保留；先按原凭证只读核对，尚不调用模型。");}finally{setBusy(false);}};
 const publishResult=(next:CompositionDebugResult|null)=>{onResult(next?.status==="succeeded"&&frozenResource.current?.id===resource?.id&&frozenResource.current?.versionId===resource?.versionId?next.previewId:null);};
 const run=async()=>{if(!preview||!fresh||preview.status!=="ready"||locked||result||attempted.current.has(preview.id))return;const key=crypto.randomUUID();attempted.current.add(preview.id);remember({kind:"run",key,previewId:preview.id});setBusy(true);setError("");try{const next=await api.run(preview.id,{expectedRevision:preview.revision,idempotencyKey:key});setResult(next);if(next.status!=="running"){remember(null);publishResult(next);}}catch{setError("未完成步骤：核对原试运行回执。发送或保存结果未确认，原预览和文本保留；只读取原结果，不再次调用模型。");}finally{setBusy(false);}};
 const check=async()=>{if(busy)return;setBusy(true);try{if(pending?.kind==="preview"){const next=await api.previewByKey(pending.key);if(!next){setError("原预览尚未读取到，不证明原请求未写入；继续按原凭证核对，未生成其他预览代替。");return;}setPreview(next);setFingerprint("");remember(null);setError("原预览已定位；仅查看冻结内容，输入需明确重新准备才产生新预览。");}else {const id=pending?.kind==="run"?pending.previewId:preview?.id;if(!id)return;const [saved,next]=await Promise.all([api.readPreview(id),api.result(id)]);setPreview(saved);setResult(next);if(next&&next.status!=="running"){remember(null);publishResult(next);}else setError("原试运行结果未终止确认；保留原凭证继续只读核对，不重发模型。");}}catch{setError("未完成步骤：读取原试验结果。读取失败不会作废原请求；原资源、冻结预览和人工文本保留。");}finally{setBusy(false);}};
 return <section className="nd-professional-trial"><header><h2>局部写法与质量试验</h2><p>只使用已保存的稿件诊断组合；明确预览和确认后调用受控模型。结果供比较，不写入小说或质量修复事实。</p></header>{!recipes.length&&<p>没有兼容的已保存组合。<a href={COMPOSITION_ROUTE}>配置稿件诊断组合与模型</a>，不会硬套其他任务假运行。</p>}
 <fieldset disabled={locked} style={{border:0,padding:0,margin:0}}><label className="nd-control">正式组合<select value={recipeId} onChange={event=>{setRecipeId(event.target.value);setVariables({});}}><option value="">请选择诊断组合</option>{recipes.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version} · {catalog?.books.find(book=>book.id===item.context.bookId)?.name??"原参考书籍"}</option>)}</select></label><label className="nd-control">局部文本<textarea rows={6} value={text} maxLength={400000} onChange={event=>setText(event.target.value)}/></label><label className="nd-control">本次试验要求<textarea value={instruction} maxLength={20000} onChange={event=>setInstruction(event.target.value)}/></label>{recipe?.variables.map(variable=><label className="nd-control" key={variable.key}>{variable.label}{variable.type==="boolean"?<input type="checkbox" checked={variables[variable.key]===undefined?variable.defaultValue===true:variables[variable.key]===true} onChange={event=>setVariables({...variables,[variable.key]:event.target.checked})}/>:variable.type==="select"?<select value={String(variables[variable.key]??variable.defaultValue)} onChange={event=>setVariables({...variables,[variable.key]:event.target.value})}>{variable.options.map(option=><option key={option}>{option}</option>)}</select>:<input type={variable.type==="number"?"number":"text"} value={String(variables[variable.key]??variable.defaultValue)} onChange={event=>setVariables({...variables,[variable.key]:variable.type==="number"?Number(event.target.value):event.target.value})}/>}</label>)}</fieldset>
 <div className="nd-action-row"><button type="button" disabled={locked||!recipe||!text.trim()} onClick={()=>void prepare()}>准备冻结预览（不调用模型）</button><button type="button" disabled={locked||!fresh||preview?.status!=="ready"||Boolean(result)||Boolean(preview&&attempted.current.has(preview.id))} onClick={()=>void run()}>确认试运行</button><button type="button" disabled={busy||!preview&&!pending} onClick={()=>void check()}>只读核对原试验结果</button><a href={sourceRoute}>打开原组合／试运行来源</a></div>
 {pending&&<p role="status">保留原请求凭证：{pending.key}；未确认期间不准备或发送另一请求。</p>}{error&&<p className="nd-message is-error" role="alert">{error}</p>}
 {preview&&<section><h3>原冻结预览</h3><p>精确组合 v{preview.recipeVersion} · {preview.status==="ready"?"可确认":preview.status==="submitted"?"已提交":preview.status==="blocked"?"有未满足条件":"来源已变化"}</p>{preview.blockers.map((item,index)=><p key={index}>{item}</p>)}<details><summary>核对实际指令、资源与模型</summary>{preview.messages.map((message,index)=><pre key={index}>{message.content}</pre>)}<p>模型：{preview.route?.primary.model??"尚未配置"}</p></details><small>预览凭证：{preview.id}</small></section>}
 {result&&<section><h3>{result.status==="succeeded"?"试验结果（仅供审阅）":result.status==="running"?"等待原试验回执":"本次试验未得到可用结果"}</h3>{result.failure&&<div className="nd-message is-error"><p>未完成步骤：{result.failure.failedStep}</p><p>{result.failure.summary}</p><p>{result.failure.savedResult}</p><a href={sourceRoute}>回到原冻结预览核对</a></div>}{result.output!==null&&<ResultValue value={result.output} resource={resource}/>}<p>{result.usageRecorded?"真实用量已登记。":"用量未确认，不表示模型未调用。"}</p></section>}
 </section>;
}
