import { useEffect, useMemo, useRef, useState } from "react";
import type { BookSummary, ForeshadowPlanAction, PlanningCenterWorkspace, PlanningExecutionMode, PlanningLevel, PlanningObject, PlanningReference, PlanningVersion } from "../../common/contracts";
import { ApiError, newDesignApi, type PlanningVersionInput } from "../api";
import BookShell from "../BookShell";

type Focus="all"|PlanningLevel|"event"|"arc"|"foreshadow";
type Draft={title:string;level:PlanningLevel;parentObjectId:string;cardId:string;goal:string;storyTime:string;mustHappen:string;mustPreserve:string;forbiddenBoundaries:string;expectedChanges:string;characterArc:string;notes:string;executionMode:PlanningExecutionMode;viewpointId:string;locationId:string;participantIds:string[];eventIds:string[];itemIds:string[];organizationIds:string[];foreshadowActions:Record<string,ForeshadowPlanAction|"">;baseVersionId:string|null;};
const blankDraft:Draft={title:"",level:"story",parentObjectId:"",cardId:"",goal:"",storyTime:"",mustHappen:"",mustPreserve:"",forbiddenBoundaries:"",expectedChanges:"",characterArc:"",notes:"",executionMode:"manual",viewpointId:"",locationId:"",participantIds:[],eventIds:[],itemIds:[],organizationIds:[],foreshadowActions:{},baseVersionId:null};
const focusItems:Array<{key:Focus;label:string}>=[{key:"all",label:"全部"},{key:"story",label:"故事总览"},{key:"volume",label:"卷"},{key:"chapter",label:"章节"},{key:"scene",label:"场景"},{key:"event",label:"事件安排"},{key:"arc",label:"人物弧"},{key:"foreshadow",label:"伏笔安排"}];
const levelLabels:Record<PlanningLevel,string>={story:"故事总览",volume:"卷",chapter:"章节",scene:"场景"};
const executionLabels:Record<PlanningExecutionMode,string>={manual:"人工",ai_assisted:"AI 辅助",automatic:"自动"};
const sourceLabels:Record<PlanningVersion["source"],string>={manual:"人工",ai:"AI 候选",import:"导入",system:"系统",body_revision:"正文修正"};
const statusLabels:Record<PlanningVersion["status"],string>={draft:"候选",proposed:"待采用",adopted:"采用中",superseded:"历史",rejected:"未采用"};
const foreshadowActions:Array<{value:ForeshadowPlanAction;label:string}>=[{value:"plant",label:"埋设"},{value:"reinforce",label:"推进"},{value:"recover",label:"回收"},{value:"misdirect",label:"误导"},{value:"reveal",label:"揭示"}];
const lines=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==="string").join("\n"):"";
const splitLines=(value:string)=>value.split(/\r?\n/).map(item=>item.trim()).filter(Boolean);
const uuid=()=>crypto.randomUUID();
const sourceUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function requestedPlanningSource(search:string,hash:string):{specified:boolean;id:string;valid:boolean}{const query=new URLSearchParams(search);if(query.has("plan")){const id=query.get("plan")??"";return {specified:true,id,valid:sourceUuid.test(id)};}if(hash.startsWith("#plan-")){const id=hash.slice(6);return {specified:true,id,valid:sourceUuid.test(id)};}return {specified:false,id:"",valid:true};}

function draftFrom(object:PlanningObject,version:PlanningVersion):Draft{
  const refs=(role:PlanningReference["role"])=>version.references.filter(item=>item.role===role);
  return{title:object.title,level:object.level,parentObjectId:object.parentObjectId??"",cardId:object.cardId??"",goal:String(version.content.goal??""),storyTime:String(version.content.storyTime??""),mustHappen:lines(version.content.mustHappen),mustPreserve:lines(version.content.mustPreserve),forbiddenBoundaries:lines(version.content.forbiddenBoundaries),expectedChanges:lines(version.content.expectedChanges),characterArc:String(version.content.characterArc??""),notes:String(version.content.notes??""),executionMode:version.executionMode,viewpointId:refs("viewpoint")[0]?.cardId??"",locationId:refs("location")[0]?.cardId??"",participantIds:refs("participant").map(item=>item.cardId),eventIds:refs("event").map(item=>item.cardId),itemIds:refs("item").map(item=>item.cardId),organizationIds:refs("organization").map(item=>item.cardId),foreshadowActions:Object.fromEntries(refs("foreshadow").map(item=>[item.cardId,item.action??""])),baseVersionId:version.id};
}

export default function PlanningCenterPage({bookId}:{bookId:string}){
  const [book,setBook]=useState<BookSummary|null>(null),[workspace,setWorkspace]=useState<PlanningCenterWorkspace|null>(null),[selectedId,setSelectedId]=useState(""),[draft,setDraft]=useState<Draft>(blankDraft),[focus,setFocus]=useState<Focus>("all"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[conflict,setConflict]=useState(""),[aiOpen,setAiOpen]=useState(()=>new URLSearchParams(window.location.search).get("ai")==="1"),[aiInstruction,setAiInstruction]=useState(""),[aiTargetId,setAiTargetId]=useState("");
  const [sourceUnavailable,setSourceUnavailable]=useState(false);
  const readSequence=useRef(0),readScope=useRef(bookId),draftRef=useRef(draft),baselineRef=useRef(JSON.stringify(blankDraft)),selectedRef=useRef(selectedId);
  draftRef.current=draft;selectedRef.current=selectedId;
  const dirty=JSON.stringify(draft)!==baselineRef.current;
  const load=async(preferredId?:string)=>{const sequence=++readSequence.current,scope=bookId,atStart=JSON.stringify(preferredId?draft:draftRef.current),source=requestedPlanningSource(location.search,location.hash);const [nextBook,nextWorkspace]=await Promise.all([newDesignApi.getBook(scope),newDesignApi.getPlanningCenter(scope)]);if(readScope.current!==scope||sequence!==readSequence.current)return;if(nextBook.id!==scope||nextWorkspace.bookId!==scope)throw new Error("规划来源不属于本书，填写与选中位置保留。");setBook(nextBook);setWorkspace(nextWorkspace);if(JSON.stringify(draftRef.current)!==atStart){setMessage("读取期间已有人工修改；填写保留，未用迟到版本覆盖。");return;}const explicit=preferredId?{specified:true,id:preferredId,valid:sourceUuid.test(preferredId)}:source;const nextId=explicit.specified?explicit.id:selectedRef.current||nextWorkspace.objects[0]?.id||"";setSelectedId(nextId);const object=explicit.valid?nextWorkspace.objects.find(item=>item.id===nextId&&item.bookId===scope):null;if(explicit.specified&&!object){setSourceUnavailable(true);setMessage("指定规划未在本书找到；保留来源位置，不自动选择其他计划。请从本书目录明确选择。");return;}setSourceUnavailable(false);if(object){const nextDraft=draftFrom(object,object.currentVersion);baselineRef.current=JSON.stringify(nextDraft);setDraft(nextDraft);}};
  useEffect(()=>{readScope.current=bookId;void load().catch(error=>{if(readScope.current===bookId)setMessage(error instanceof Error?error.message:"故事规划加载失败。");});return()=>{readSequence.current++;};},[bookId]);
  useEffect(()=>{const changed=()=>{const source=requestedPlanningSource(location.search,location.hash);if(!source.specified)return;if(busy||JSON.stringify(draftRef.current)!==baselineRef.current){setMessage("当前规划填写尚未保存，已保留；请先保存候选再打开指定来源。");return;}void load().catch(error=>setMessage(error instanceof Error?error.message:"指定规划读取失败。"));};addEventListener("popstate",changed);addEventListener("hashchange",changed);return()=>{removeEventListener("popstate",changed);removeEventListener("hashchange",changed);};},[bookId,busy]);
  useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(JSON.stringify(draftRef.current)!==baselineRef.current||busy){event.preventDefault();event.returnValue="";}};addEventListener("beforeunload",leave);return()=>removeEventListener("beforeunload",leave);},[busy]);
  const selected=workspace?.objects.find(item=>item.id===selectedId)??null;
  const objects=workspace?.objects??[],materials=workspace?.materials??[];
  const aiTargets=objects.filter(item=>item.status==="active"),aiTargetValue=aiTargetId||(selected?.status==="active"?selected.id:aiTargets[0]?.id??"");
  const orderedObjects=useMemo(()=>{const result:PlanningObject[]=[],seen=new Set<string>(),children=new Map<string|null,PlanningObject[]>();for(const object of objects){const key=object.parentObjectId??null,items=children.get(key)??[];items.push(object);children.set(key,items);}for(const items of children.values())items.sort((a,b)=>a.sortOrder-b.sortOrder||a.title.localeCompare(b.title));const visit=(parentId:string|null)=>{for(const object of children.get(parentId)??[]){if(seen.has(object.id))continue;seen.add(object.id);result.push(object);visit(object.id);}};visit(null);for(const object of objects)if(!seen.has(object.id))result.push(object);return result;},[objects]);
  const filtered=useMemo(()=>orderedObjects.filter(object=>focus==="all"||focus==="story"||focus==="volume"||focus==="chapter"||focus==="scene"?focus==="all"||object.level===focus:focus==="event"?object.currentVersion.references.some(item=>item.role==="event"):focus==="foreshadow"?object.currentVersion.references.some(item=>item.role==="foreshadow"):Boolean(object.currentVersion.content.characterArc)),[orderedObjects,focus]);
  const candidates=(typeKey:string)=>materials.filter(item=>item.typeKey===typeKey);
  const parentCandidates=objects.filter(item=>item.status==="active"&&(draft.level==="volume"?item.level==="story":draft.level==="chapter"?item.level==="volume":draft.level==="scene"?item.level==="chapter":false));
  const structuralMaterials=candidates(draft.level).filter(item=>!objects.some(object=>object.cardId===item.cardId&&object.id!==selectedId));
  const firstThree=objects.filter(item=>item.level==="chapter"&&item.status==="active").sort((a,b)=>a.sortOrder-b.sortOrder).slice(0,3),firstThreeAdopted=firstThree.filter(item=>item.adoptedVersionId).length;
  const selectObject=(object:PlanningObject)=>{if(object.bookId!==bookId||busy||dirty){setMessage("当前规划填写尚未保存或请求正在处理，已保留；请先保存候选再切换。");return;}readSequence.current++;const next=draftFrom(object,object.currentVersion);baselineRef.current=JSON.stringify(next);setSourceUnavailable(false);setSelectedId(object.id);setDraft(next);setMessage("");setConflict("");const url=new URL(location.href);url.searchParams.set("plan",object.id);url.hash="";history.replaceState(null,"",url);};
  const beginNew=()=>{
    if(busy||dirty){setMessage("当前填写尚未保存，已保留；请先保存候选再新增规划。");return;}
    setSourceUnavailable(false);
    const story=objects.find(item=>item.level==="story"&&item.status==="active");
    if(story&&!story.adoptedVersionId){selectObject(story);setMessage("请先采用故事总览，再建立卷计划。");return;}
    const volume=objects.find(item=>item.level==="volume"&&item.status==="active"&&item.adoptedVersionId);
    const pendingVolume=objects.find(item=>item.level==="volume"&&item.status==="active"&&!item.adoptedVersionId);
    if(story&&!volume&&pendingVolume){selectObject(pendingVolume);setMessage("请先采用卷计划，再建立章节计划。");return;}
    const level:PlanningLevel=!story?"story":!volume?"volume":"chapter";
    const parentObjectId=level==="volume"?story?.id??"":level==="chapter"?volume?.id??"":"";
    const usedCardIds=new Set(objects.filter(item=>item.level===level).map(item=>item.cardId));
    const material=materials.find(item=>item.typeKey===level&&!usedCardIds.has(item.cardId));
    setSelectedId("");setDraft({...blankDraft,level,parentObjectId,cardId:material?.cardId??"",title:material?.title??""});setMessage("");setConflict("");
  };
  const setLevel=(level:PlanningLevel)=>setDraft(value=>({...value,level,parentObjectId:"",cardId:"",title:""}));
  const multiSelect=(event:React.ChangeEvent<HTMLSelectElement>)=>Array.from(event.target.selectedOptions,item=>item.value);
  const buildReferences=():PlanningVersionInput["references"]=>{let order=0;const result:PlanningVersionInput["references"]=[],add=(role:PlanningReference["role"],ids:string[])=>{for(const id of ids){const item=materials.find(option=>option.cardId===id);if(item)result.push({role,cardId:item.cardId,cardVersionId:item.cardVersionId,action:null,note:"",sortOrder:order++});}};add("viewpoint",draft.viewpointId?[draft.viewpointId]:[]);add("location",draft.locationId?[draft.locationId]:[]);add("participant",draft.participantIds);add("event",draft.eventIds);add("item",draft.itemIds);add("organization",draft.organizationIds);for(const [id,action] of Object.entries(draft.foreshadowActions)){const item=materials.find(option=>option.cardId===id);if(item&&action)result.push({role:"foreshadow",cardId:item.cardId,cardVersionId:item.cardVersionId,action,note:"",sortOrder:order++});}return result;};
  const versionInput=():PlanningVersionInput=>({content:{goal:draft.goal,storyTime:draft.storyTime,mustHappen:splitLines(draft.mustHappen),mustPreserve:splitLines(draft.mustPreserve),forbiddenBoundaries:splitLines(draft.forbiddenBoundaries),expectedChanges:splitLines(draft.expectedChanges),characterArc:draft.characterArc,notes:draft.notes},source:"manual",executionMode:draft.executionMode,references:buildReferences(),baseVersionId:draft.baseVersionId,basedOnParentVersionId:draft.level==="story"?null:objects.find(item=>item.id===draft.parentObjectId)?.adoptedVersionId??null,sourceBodyVersionId:null,createdBy:"user",idempotencyKey:uuid()});
  const handleError=(error:unknown,fallback:string)=>{if(error instanceof ApiError&&error.status===409)setConflict(`服务器修订 ${error.issues.serverRevision??"未知"}，你的填写仍保留。请核对后再保存。`);setMessage(error instanceof Error?error.message:fallback);};
  const save=async()=>{if(busy||sourceUnavailable){setMessage("指定来源尚未匹配本书规划，请先从本书目录明确选择；填写仍保留。");return;}if(selected?.status==="archived"){setMessage("请先恢复该规划，再保存候选。");return;}if(!workspace||!draft.title.trim()){setMessage("请填写规划名称。");return;}if(draft.level!=="story"&&(!draft.parentObjectId||!draft.cardId)){setMessage("请选择上级规划和对应的本书资料。");return;}setBusy(true);setMessage("");setConflict("");try{let saved:PlanningObject;if(selected){saved=await newDesignApi.addPlanningVersion(selected.id,{...versionInput(),expectedRevision:selected.revision});setMessage("新候选已保存。采用后才会作为后续创作依据。");}else{const siblings=objects.filter(item=>item.parentObjectId===(draft.parentObjectId||null)&&item.level===draft.level);saved=await newDesignApi.createPlanningObject(bookId,{...versionInput(),level:draft.level,parentObjectId:draft.level==="story"?null:draft.parentObjectId,cardId:draft.level==="story"?null:draft.cardId,title:draft.title.trim(),sortOrder:siblings.reduce((max,item)=>Math.max(max,item.sortOrder),-1)+1});setMessage("规划候选已建立。确认内容后可以采用。");}await load(saved.id);}catch(error){handleError(error,"规划保存失败。");}finally{setBusy(false);}};
  const adopt=async(version:PlanningVersion)=>{if(!selected)return;setBusy(true);setConflict("");try{const saved=await newDesignApi.adoptPlanningVersion(selected.id,{versionId:version.id,expectedRevision:selected.revision,idempotencyKey:uuid(),actor:"user"});await load(saved.id);setMessage(`版本 ${version.version} 已设为创作依据。`);}catch(error){handleError(error,"规划采用失败。");}finally{setBusy(false);}};
  const reject=async(version:PlanningVersion)=>{if(!selected)return;setBusy(true);try{const saved=await newDesignApi.rejectPlanningVersion(selected.id,{versionId:version.id,expectedRevision:selected.revision,idempotencyKey:uuid(),actor:"user",note:"作者在规划中心标记为不采用"});await load(saved.id);setMessage("候选已标记为不采用，历史仍可查看。");}catch(error){handleError(error,"候选处理失败。");}finally{setBusy(false);}};
  const archive=async()=>{if(!selected)return;setBusy(true);try{const saved=await newDesignApi.archivePlanningObject(selected.id,{expectedRevision:selected.revision,idempotencyKey:uuid(),actor:"user",note:selected.status==="active"?"作者在规划中心归档":"作者在规划中心恢复"},selected.status==="archived");await load(saved.id);setMessage(selected.status==="active"?"规划已归档，版本历史仍保留。":"规划已恢复。");}catch(error){handleError(error,"规划状态更新失败。");}finally{setBusy(false);}};
  const generateWithAi=async()=>{if(!workspace||busy||sourceUnavailable||dirty){setMessage("先保存当前填写并选择本书明确来源，再准备 AI 候选；人工填写保留。");return;}setBusy(true);setMessage("");setConflict("");try{const targetObjectId=aiTargetValue||null;const run=await newDesignApi.generatePlanningCandidate(bookId,{targetObjectId,instruction:aiInstruction,createdBy:"user"});await load(run.planningObjectId);setAiOpen(false);setAiInstruction("");setMessage("AI 规划候选已生成。请先比较和修改，确认后再采用。");}catch(error){handleError(error,"AI 规划候选生成失败。");}finally{setBusy(false);}};
  if(message&&!book)return <div className="nd-shell nd-fatal"><h1>无法打开故事规划</h1><p>{message}</p><a className="nd-button nd-button-primary" href="/new-design/books">返回我的书籍</a></div>;
  if(!book||!workspace)return <div className="nd-shell nd-loading-screen"><div className="nd-loader"/><strong>正在读取规划版本</strong></div>;
  return <BookShell book={book} active="planning"><main className="nd-planning-page">
    <section className="nd-planning-summary"><div><p className="nd-kicker">前三章准备</p><h2>{firstThreeAdopted}/3 章具有采用计划</h2><p>采用的章节计划会成为章节创作入口读取的唯一规划依据；候选不会改变正文或正式事实。</p><small>稳定章节 {workspace.settlementSummary.stable} · 待结算 {workspace.settlementSummary.pending} · 结算需处理 {workspace.settlementSummary.failed} · 待看改稿影响 {workspace.settlementSummary.impactReview} · 换稿处理中 {workspace.settlementSummary.revisionRunning} · 换稿需恢复 {workspace.settlementSummary.revisionFailed} · 后续正文待复核 {workspace.settlementSummary.downstreamReview}</small></div><div className="nd-planning-mode-strip">{firstThree.length?firstThree.map((item,index)=><button type="button" onClick={()=>{setFocus("all");selectObject(item);}} key={item.id}><span>第 {index+1} 章</span><strong>{item.title}</strong><small>{item.adoptedVersion?`${executionLabels[item.adoptedVersion.executionMode]} · 采用版本 ${item.adoptedVersion.version}`:"等待采用"}</small></button>):<p>先建立故事总览和卷计划，再为前三章添加规划。</p>}</div></section>
    <nav className="nd-planning-focus" aria-label="规划层级">{focusItems.map(item=><button className={focus===item.key?"active":""} type="button" onClick={()=>setFocus(item.key)} key={item.key}>{item.label}</button>)}</nav>
    <div className="nd-planning-layout">
      <aside className="nd-planning-tree"><div className="nd-panel-title"><div><p className="nd-kicker">规划目录</p><h2>{filtered.length} 项</h2></div><button className="nd-button nd-button-primary" type="button" onClick={beginNew}>新增规划</button></div>{filtered.length?<div className="nd-plan-tree-list" role="tree">{filtered.map(object=><button id={`plan-${object.id}`} className={`${selectedId===object.id?"is-selected":""} level-${object.level}`} type="button" role="treeitem" aria-level={{story:1,volume:2,chapter:3,scene:4}[object.level]} aria-current={selectedId===object.id?"true":undefined} onClick={()=>selectObject(object)} key={object.id}><span>{levelLabels[object.level]}</span><strong>{object.title}</strong><small>{object.status==="archived"?"已归档":object.adoptedVersion?`采用版本 ${object.adoptedVersion.version}`:"等待采用"}</small></button>)}</div>:<div className="nd-empty-state"><strong>该视图暂无安排</strong><p>切换层级或新增规划；事件、人物弧和伏笔视图读取同一份计划。</p></div>}</aside>
      <section className="nd-plan-editor" aria-labelledby="plan-editor-title"><div className="nd-panel-title"><div><p className="nd-kicker">{selected?"另存候选":"新规划"}</p><h2 id="plan-editor-title">{selected?selected.title:"建立规划起点"}</h2></div>{selected?<button className="nd-button" type="button" onClick={archive} disabled={busy}>{selected.status==="active"?"归档":"恢复"}</button>:null}</div>
        {conflict?<div className="nd-conflict" role="alert"><strong>发现其他位置的修改</strong><p>{conflict}</p></div>:null}{message?<p className="nd-inline-message" aria-live="polite">{message}</p>:null}
        <div className="nd-plan-form-grid"><label>规划层级<select value={draft.level} onChange={event=>setLevel(event.target.value as PlanningLevel)} disabled={Boolean(selected)}>{(["story","volume","chapter","scene"] as PlanningLevel[]).map(level=><option value={level} key={level}>{levelLabels[level]}</option>)}</select></label><label>规划名称<input value={draft.title} onChange={event=>setDraft(value=>({...value,title:event.target.value}))} disabled={Boolean(selected)} placeholder="例如：第一卷·入山"/></label>
          {draft.level!=="story"?<><label>上级规划<select value={draft.parentObjectId} onChange={event=>setDraft(value=>({...value,parentObjectId:event.target.value}))} disabled={Boolean(selected)}><option value="">请选择已采用的上级规划</option>{parentCandidates.map(parent=><option value={parent.id} disabled={!parent.adoptedVersionId} key={parent.id}>{parent.title}{parent.adoptedVersionId?"":"（等待采用）"}</option>)}</select></label><label>对应本书资料<select value={draft.cardId} onChange={event=>{const card=materials.find(item=>item.cardId===event.target.value);setDraft(value=>({...value,cardId:event.target.value,title:card?.title??value.title}));}} disabled={Boolean(selected)}><option value="">请选择{levelLabels[draft.level]}资料</option>{structuralMaterials.map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select><small>没有可选资料时，先到 <a href={`/new-design/books/${bookId}/cards`}>本书资料</a> 新建。</small></label></>:null}
          <label>后续执行方式<select value={draft.executionMode} onChange={event=>setDraft(value=>({...value,executionMode:event.target.value as PlanningExecutionMode}))}><option value="manual">人工创作</option><option value="ai_assisted">AI 辅助</option><option value="automatic">自动执行意图</option></select><small>这里只记录意图，不会生成正文。</small></label><label>故事时间<input value={draft.storyTime} onChange={event=>setDraft(value=>({...value,storyTime:event.target.value}))} placeholder="例如：入山试炼第一日清晨"/></label></div>
        <label className="nd-plan-wide">目标<textarea value={draft.goal} onChange={event=>setDraft(value=>({...value,goal:event.target.value}))} rows={3} placeholder="完成后，故事必须发生什么变化？"/></label>
        <div className="nd-plan-form-grid"><label>视角人物<select value={draft.viewpointId} onChange={event=>setDraft(value=>({...value,viewpointId:event.target.value}))}><option value="">暂不指定</option>{candidates("character").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select></label><label>地点<select value={draft.locationId} onChange={event=>setDraft(value=>({...value,locationId:event.target.value}))}><option value="">暂不指定</option>{candidates("location").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select></label><label>参与者<select multiple value={draft.participantIds} onChange={event=>setDraft(value=>({...value,participantIds:multiSelect(event)}))}>{candidates("character").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select><small>按住 Ctrl 或 Command 可多选。</small></label><label>相关事件<select multiple value={draft.eventIds} onChange={event=>setDraft(value=>({...value,eventIds:multiSelect(event)}))}>{candidates("event").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select></label><label>相关道具<select multiple value={draft.itemIds} onChange={event=>setDraft(value=>({...value,itemIds:multiSelect(event)}))}>{candidates("prop").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select></label><label>相关组织／势力<select multiple value={draft.organizationIds} onChange={event=>setDraft(value=>({...value,organizationIds:multiSelect(event)}))}>{candidates("organization").map(item=><option value={item.cardId} key={item.cardId}>{item.title}</option>)}</select></label></div>
        <div className="nd-plan-text-grid"><label>必须发生<textarea value={draft.mustHappen} onChange={event=>setDraft(value=>({...value,mustHappen:event.target.value}))} rows={4} placeholder="每行一项"/></label><label>必须保留<textarea value={draft.mustPreserve} onChange={event=>setDraft(value=>({...value,mustPreserve:event.target.value}))} rows={4} placeholder="不能丢失的承诺或信息，每行一项"/></label><label>禁止越界<textarea value={draft.forbiddenBoundaries} onChange={event=>setDraft(value=>({...value,forbiddenBoundaries:event.target.value}))} rows={4} placeholder="不能提前揭示或改变的边界，每行一项"/></label><label>预期变化<textarea value={draft.expectedChanges} onChange={event=>setDraft(value=>({...value,expectedChanges:event.target.value}))} rows={4} placeholder="人物、关系、道具或状态的预期变化，每行一项；不会提前结算"/></label></div>
        <label className="nd-plan-wide">人物弧安排<textarea value={draft.characterArc} onChange={event=>setDraft(value=>({...value,characterArc:event.target.value}))} rows={3} placeholder="人物在这一层计划中的选择、代价和变化"/></label>
        <section className="nd-foreshadow-picker" aria-labelledby="foreshadow-title"><div className="nd-section-heading"><div><p className="nd-kicker">关联安排</p><h3 id="foreshadow-title">伏笔动作</h3></div><a href={`/new-design/books/${bookId}/views/clues`}>维护线索与伏笔</a></div>{[...candidates("foreshadow"),...candidates("clue")].length?<div>{[...candidates("foreshadow"),...candidates("clue")].map(item=><label key={item.cardId}><span>{item.title}</span><select value={draft.foreshadowActions[item.cardId]??""} onChange={event=>setDraft(value=>({...value,foreshadowActions:{...value.foreshadowActions,[item.cardId]:event.target.value as ForeshadowPlanAction|""}}))}><option value="">不安排</option>{foreshadowActions.map(action=><option value={action.value} key={action.value}>{action.label}</option>)}</select></label>)}</div>:<div className="nd-empty-state"><strong>暂无伏笔资料</strong><p>先在线索与伏笔页面建立资料，再回来选择动作。</p></div>}</section>
        <label className="nd-plan-wide">补充说明<textarea value={draft.notes} onChange={event=>setDraft(value=>({...value,notes:event.target.value}))} rows={3}/></label>
        <div className="nd-plan-actions"><p>{selected?.status==="archived"?"恢复规划后才能追加候选。":selected?"保存会追加候选版本，不会覆盖采用版本。":"建立后先检查候选，再明确采用。"}</p><button className="nd-button nd-button-primary" type="button" onClick={save} disabled={busy||selected?.status==="archived"}>{busy?"处理中…":selected?"另存新候选":"建立规划候选"}</button></div>
      </section>
      <aside className="nd-plan-versions"><section><div className="nd-panel-title"><div><p className="nd-kicker">候选比较</p><h2>版本与采用</h2></div></div>{selected?<div className="nd-version-list">{selected.versions.map(version=><article className={version.id===selected.adoptedVersionId?"is-adopted":""} key={version.id}><div><strong>版本 {version.version}</strong><span>{statusLabels[version.status]}</span></div><small>{sourceLabels[version.source]} · {executionLabels[version.executionMode]} · {new Date(version.createdAt).toLocaleString()}</small><p>{String(version.content.goal??"未填写目标")}</p><small>{version.references.length} 项资料引用 · {version.staleAt?"等待复核":"来源可追溯"}</small><div>{version.status!=="rejected"?<button type="button" onClick={()=>setDraft(draftFrom(selected,version))}>载入另存</button>:null}{version.id!==selected.adoptedVersionId&&version.status!=="rejected"&&!version.staleAt?<button type="button" onClick={()=>void adopt(version)} disabled={busy||selected.status==="archived"}>采用</button>:null}{["draft","proposed"].includes(version.status)?<button type="button" onClick={()=>void reject(version)} disabled={busy||selected.status==="archived"}>不采用</button>:null}</div></article>)}</div>:<div className="nd-empty-state"><strong>等待建立规划</strong><p>保存第一个候选后，可在这里比较和采用。</p></div>}</section><section className={`nd-ai-planning-state ${workspace.aiCapability.configured?"is-ready":"is-empty"}`}><p className="nd-kicker">AI 规划</p><h3>生成可审阅的规划候选</h3><p>{workspace.aiCapability.message}</p>{aiOpen?<div className="nd-ai-planning-form">{aiTargets.length?<label>规划目标<select value={aiTargetValue} onChange={event=>setAiTargetId(event.target.value)}>{aiTargets.map(item=><option value={item.id} key={item.id}>{levelLabels[item.level]} · {item.title}</option>)}</select></label>:<p>当前还没有规划，AI 将先建立“故事总览”候选。</p>}<label>这次希望 AI 重点考虑什么<textarea rows={4} value={aiInstruction} onChange={event=>setAiInstruction(event.target.value)} placeholder="可不填。例如：突出师徒关系，前三章快速建立主线危机。"/></label><div className="nd-ai-planning-actions"><button className="nd-button" type="button" onClick={()=>setAiOpen(false)} disabled={busy}>取消</button><button className="nd-button nd-button-primary" type="button" onClick={()=>void generateWithAi()} disabled={busy}>{busy?"正在生成…":"生成候选"}</button></div><small>AI 只会新增候选版本，不会自动采用或覆盖现有规划。</small></div>:<button className="nd-button" type="button" onClick={()=>setAiOpen(true)} disabled={!workspace.aiCapability.configured}>AI 帮我规划</button>}<small>能力：{workspace.aiCapability.taskKey}</small></section></aside>
    </div>
  </main></BookShell>;
}
