import { createHash, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import type { ChapterAdoptionPreparation, ChapterDocumentDetail, ChapterWritingOperation, ChapterWritingRequest, ChapterWritingWorkspace } from "../../../common/contracts";
import { NewDesignError, assertFound } from "../../domain/errors";
import { createAiRunPreview, submitAiRunPreview } from "../aiRunOrchestration";
import { stableHash } from "../aiContracts/integrity";
import { getChapterDocument } from "../chapterBodyStore";
import { getNewDesignPool } from "../runtime";

type CandidateOperation=Extract<ChapterWritingOperation,"manual_draft"|"copy">;
type AiOperation=Exclude<ChapterWritingOperation,CandidateOperation>;
type Row=Record<string,unknown>;
const asDate=(value:unknown)=>value instanceof Date?value.toISOString():new Date(String(value)).toISOString();
const asText=(value:unknown)=>value===null||value===undefined?null:String(value);
const hashText=(value:string)=>createHash("sha256").update(value,"utf8").digest("hex");

function mapRequest(row:Row):ChapterWritingRequest{return{id:String(row.id),bookId:String(row.book_id),chapterDocumentId:String(row.chapter_document_id),operationKind:row.operation_kind as AiOperation,planningObjectId:String(row.planning_object_id),planningVersionId:String(row.planning_version_id),planningContentHash:String(row.planning_content_hash),contextManifestId:String(row.context_manifest_id),taskContractVersionId:String(row.task_contract_version_id),promptRecipeVersionId:String(row.prompt_recipe_version_id),modelRouteSnapshotId:String(row.model_route_snapshot_id),inputBodyVersionId:asText(row.input_body_version_id),inputBodyHash:asText(row.input_body_hash),selectionStart:row.selection_start===null?null:Number(row.selection_start),selectionEnd:row.selection_end===null?null:Number(row.selection_end),instruction:String(row.instruction),expectedDocumentRevision:Number(row.expected_document_revision),aiTaskId:asText(row.ai_task_id),resultBodyVersionId:asText(row.result_body_version_id),status:row.status as ChapterWritingRequest["status"],errorSummary:String(row.error_summary),createdBy:String(row.created_by),createdAt:asDate(row.created_at),updatedAt:asDate(row.updated_at)};}
function mapPreparation(row:Row):ChapterAdoptionPreparation{return{id:String(row.id),bookId:String(row.book_id),chapterDocumentId:String(row.chapter_document_id),bodyVersionId:String(row.body_version_id),expectedDocumentRevision:Number(row.expected_document_revision),planningObjectId:String(row.planning_object_id),planningVersionId:String(row.planning_version_id),planningContentHash:String(row.planning_content_hash),contextManifestId:asText(row.context_manifest_id),dependencySnapshot:(row.dependency_snapshot??{}) as Record<string,unknown>,dependencyHash:String(row.dependency_hash),status:row.status as ChapterAdoptionPreparation["status"],idempotencyKey:String(row.idempotency_key),createdBy:String(row.created_by),createdAt:asDate(row.created_at)};}
function conflict(document:Row):never{throw new NewDesignError("章节正文已在其他页面更新，本地稿件仍保留。请对照服务器候选后另存。",409,{serverRevision:String(document.revision),serverVersionId:String(document.adopted_version_id??"")});}

async function adoptedPlan(client:PoolClient,document:Row):Promise<Row>{return assertFound((await client.query(`SELECT object.id planning_object_id,object.adopted_version_id planning_version_id,version.content_hash planning_content_hash
  FROM new_design.planning_objects object JOIN new_design.planning_versions version ON version.id=object.adopted_version_id
  WHERE object.book_id=$1 AND object.card_id=$2 AND object.level='chapter' AND object.status='active'`,[document.book_id,document.chapter_card_id])).rows[0],"请先采用本章计划，再开始章节创作。");}

async function requireBodyVersion(client:PoolClient,documentId:string,versionId:string|null|undefined,label:string):Promise<Row|null>{if(!versionId)return null;return assertFound((await client.query("SELECT * FROM new_design.chapter_body_versions WHERE id=$1 AND chapter_document_id=$2",[versionId,documentId])).rows[0],`${label}不存在或属于其他章节。`);}

export async function getChapterWritingWorkspace(bookId:string):Promise<ChapterWritingWorkspace>{
  const pool=await getNewDesignPool();
  assertFound((await pool.query("SELECT id FROM new_design.books WHERE id=$1",[bookId])).rows[0],"书籍不存在。");
  const [chapters,contract]=await Promise.all([
    pool.query(`SELECT chapter.card_id chapter_card_id,chapter.id planning_object_id,chapter.parent_object_id volume_planning_object_id,
      COALESCE(volume.title,'未分卷') volume_title,chapter.title,chapter.sort_order logical_order,chapter.adopted_version_id planning_version_id,
      planning.version planning_version_number,document.id document_id,document.revision document_revision,document.adopted_version_id adopted_body_version_id,
      COALESCE(body.candidate_count,0) candidate_count,COALESCE(request.pending_count,0) pending_request_count,COALESCE(issue.open_count,0) open_issue_count,
      session.id settlement_session_id,session.body_version_id settlement_body_version_id,session.status settlement_status,checkpoint.id stable_checkpoint_id,
      revision.status revision_status,COALESCE(revision_review.open_count,0) revision_review_count,
      GREATEST(chapter.updated_at,COALESCE(document.updated_at,chapter.updated_at)) updated_at
    FROM new_design.planning_objects chapter
    LEFT JOIN new_design.planning_objects volume ON volume.id=chapter.parent_object_id
    LEFT JOIN new_design.planning_versions planning ON planning.id=chapter.adopted_version_id
    LEFT JOIN new_design.chapter_documents document ON document.book_id=chapter.book_id AND document.chapter_card_id=chapter.card_id AND document.status='active'
    LEFT JOIN LATERAL (SELECT count(*)::int candidate_count FROM new_design.chapter_body_versions version WHERE version.chapter_document_id=document.id AND version.archived_at IS NULL) body ON true
    LEFT JOIN LATERAL (SELECT count(*)::int pending_count FROM new_design.chapter_writing_requests item WHERE item.chapter_document_id=document.id AND item.status IN ('preparing','queued','running')) request ON true
    LEFT JOIN LATERAL (SELECT count(DISTINCT quality.id)::int open_count FROM new_design.quality_issues quality JOIN new_design.quality_audit_reports report ON report.id=quality.report_id JOIN new_design.quality_report_body_versions binding ON binding.report_id=report.id WHERE binding.chapter_document_id=document.id AND report.stale_at IS NULL AND quality.current_status IN ('open','acknowledged','fix_proposed')) issue ON true
    LEFT JOIN LATERAL (SELECT item.id,item.body_version_id,item.status FROM new_design.chapter_adoption_sessions item WHERE item.chapter_document_id=document.id ORDER BY item.created_at DESC,item.id DESC LIMIT 1) session ON true
    LEFT JOIN LATERAL (SELECT item.id FROM new_design.chapter_stable_checkpoints item WHERE item.chapter_document_id=document.id AND item.status='stable' ORDER BY item.created_at DESC,item.id DESC LIMIT 1) checkpoint ON true
    LEFT JOIN LATERAL (SELECT item.status FROM new_design.chapter_revision_executions item WHERE item.chapter_document_id=document.id ORDER BY item.created_at DESC,item.id DESC LIMIT 1) revision ON true
    LEFT JOIN LATERAL (SELECT count(*)::int open_count FROM new_design.chapter_revision_review_flags item WHERE item.target_chapter_document_id=document.id AND item.status IN ('pending_review','in_review')) revision_review ON true
    WHERE chapter.book_id=$1 AND chapter.level='chapter' AND chapter.status='active'
    ORDER BY COALESCE(volume.sort_order,0),chapter.sort_order,chapter.id`,[bookId]),
    pool.query(`SELECT contract.task_key,version.id version_id FROM new_design.task_contracts contract
      JOIN new_design.task_contract_versions version ON version.id=contract.published_version_id
      WHERE contract.status='active' AND version.task_group IN ('writing','chapter','chapter_writing')
      ORDER BY CASE WHEN contract.task_key='chapter.write' THEN 0 ELSE 1 END,version.created_at DESC LIMIT 1`),
  ]);
  const capability=contract.rows[0];
  return{bookId,chapters:chapters.rows.map(row=>{const adopted=Boolean(row.adopted_body_version_id),pending=Number(row.pending_request_count)>0,issues=Number(row.open_issue_count)>0,hasPlan=Boolean(row.planning_version_id),settlement=String(row.settlement_status??""),revision=String(row.revision_status??""),hasRevisionReview=Number(row.revision_review_count)>0;const state:ChapterWritingWorkspace["chapters"][number]["state"]=!hasPlan?"needs_plan":["failed","dead_letter","partially_failed"].includes(revision)?"revision_partial_failure":hasRevisionReview?"downstream_review":["queued","running","awaiting_review"].includes(revision)?"revision_running":settlement==="impact_review_required"?"impact_review_required":settlement==="failed"?"settlement_failed":Boolean(row.stable_checkpoint_id)?"stable":["reviewing","adopted_pending_proposals","pending_review","partially_confirmed","settling"].includes(settlement)?"settlement_pending":pending?"writing":issues?"review":adopted?"adopted":"ready";return{chapterCardId:String(row.chapter_card_id),planningObjectId:String(row.planning_object_id),volumePlanningObjectId:asText(row.volume_planning_object_id),volumeTitle:String(row.volume_title),title:String(row.title),logicalOrder:Number(row.logical_order),hasAdoptedPlan:hasPlan,planningVersionId:asText(row.planning_version_id),planningVersionNumber:row.planning_version_number===null?null:Number(row.planning_version_number),documentId:asText(row.document_id),documentRevision:row.document_revision===null?null:Number(row.document_revision),candidateCount:Number(row.candidate_count),adoptedBodyVersionId:asText(row.adopted_body_version_id),settlementSessionId:asText(row.settlement_session_id),settlementBodyVersionId:asText(row.settlement_body_version_id),pendingRequestCount:Number(row.pending_request_count),openIssueCount:Number(row.open_issue_count),state,updatedAt:asDate(row.updated_at)};}),aiCapability:capability?{configured:true,taskKey:String(capability.task_key),taskContractVersionId:String(capability.version_id),message:"已接入章节写作任务；请求会进入任务队列，结果仅保存为正文候选。"}:{configured:false,taskKey:null,taskContractVersionId:null,message:"章节写作任务尚未配置。人工写稿可继续使用，AI 操作暂不可提交。"},updatedAt:new Date().toISOString()};
}

export async function saveChapterCandidate(documentId:string,input:{content:string;operationKind:CandidateOperation;baseVersionId?:string|null;expectedRevision:number;idempotencyKey:string;createdBy?:string}):Promise<ChapterDocumentDetail>{
  const pool=await getNewDesignPool(),requestHash=stableHash({documentId,...input,createdBy:input.createdBy??""});
  const client=await pool.connect();
  try{await client.query("BEGIN");const document=assertFound((await client.query("SELECT * FROM new_design.chapter_documents WHERE id=$1 FOR UPDATE",[documentId])).rows[0],"章节正文档案不存在。"),committed=(await client.query("SELECT chapter_document_id,request_hash FROM new_design.chapter_body_operations WHERE book_id=$1 AND idempotency_key=$2",[document.book_id,input.idempotencyKey])).rows[0];if(committed){if(String(committed.chapter_document_id)!==documentId||String(committed.request_hash)!==requestHash)throw new NewDesignError("保存幂等键已用于不同稿件。",409);await client.query("ROLLBACK");return getChapterDocument(documentId);}if(document.status!=="active")throw new NewDesignError("章节正文档案已归档。",409);if(Number(document.revision)!==input.expectedRevision)conflict(document);const plan=await adoptedPlan(client,document),base=await requireBodyVersion(client,documentId,input.baseVersionId,"基础正文版本");if(input.operationKind==="copy"&&!base)throw new NewDesignError("复制候选必须指定来源正文版本。",422);const content=input.content;if(!content.trim())throw new NewDesignError("正文不能为空。",422);const number=Number((await client.query("SELECT COALESCE(max(version),0)+1 version FROM new_design.chapter_body_versions WHERE chapter_document_id=$1",[documentId])).rows[0].version),id=randomUUID(),contentHash=hashText(content),revision=Number(document.revision)+1;await client.query(`INSERT INTO new_design.chapter_body_versions(id,chapter_document_id,version,parent_version_id,base_version_id,source,operation_kind,planning_object_id,planning_version_id,input_body_version_id,created_by_kind,created_by,content,content_hash)
      VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8,$4,'user',$9,$10,$11)`,[id,documentId,number,base?String(base.id):null,input.operationKind==="copy"?"revision":"manual",input.operationKind,plan.planning_object_id,plan.planning_version_id,input.createdBy??"user",content,contentHash]);await client.query("UPDATE new_design.chapter_documents SET revision=$2,updated_at=now() WHERE id=$1",[documentId,revision]);await client.query("INSERT INTO new_design.chapter_body_operations(id,book_id,chapter_document_id,operation_kind,expected_revision,result_revision,result_body_version_id,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),document.book_id,documentId,input.operationKind==="copy"?"copy_candidate":"save_candidate",input.expectedRevision,revision,id,requestHash,input.idempotencyKey,input.createdBy??"user"]);await client.query("COMMIT");return getChapterDocument(documentId);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}

export async function listChapterWritingRequests(documentId:string):Promise<ChapterWritingRequest[]>{const rows=await(await getNewDesignPool()).query(`SELECT request.*,CASE WHEN request.result_body_version_id IS NOT NULL THEN 'succeeded' ELSE CASE task.status WHEN 'queued' THEN 'queued' WHEN 'running' THEN 'running' WHEN 'waiting_approval' THEN 'running' WHEN 'retry_scheduled' THEN 'queued' WHEN 'paused' THEN 'failed' WHEN 'succeeded' THEN 'succeeded' WHEN 'failed' THEN 'failed' WHEN 'cancelled' THEN 'cancelled' ELSE request.status END END effective_status FROM new_design.chapter_writing_requests request LEFT JOIN new_design.ai_tasks task ON task.id=request.ai_task_id WHERE request.chapter_document_id=$1 ORDER BY request.created_at DESC,request.id DESC`,[documentId]);return rows.rows.map(row=>mapRequest({...row,status:row.effective_status}));}
export async function getChapterWritingRequest(id:string):Promise<ChapterWritingRequest>{const row=assertFound((await(await getNewDesignPool()).query(`SELECT request.*,CASE WHEN request.result_body_version_id IS NOT NULL THEN 'succeeded' ELSE CASE task.status WHEN 'queued' THEN 'queued' WHEN 'running' THEN 'running' WHEN 'waiting_approval' THEN 'running' WHEN 'retry_scheduled' THEN 'queued' WHEN 'paused' THEN 'failed' WHEN 'succeeded' THEN 'succeeded' WHEN 'failed' THEN 'failed' WHEN 'cancelled' THEN 'cancelled' ELSE request.status END END effective_status FROM new_design.chapter_writing_requests request LEFT JOIN new_design.ai_tasks task ON task.id=request.ai_task_id WHERE request.id=$1`,[id])).rows[0],"章节写作请求不存在。");return mapRequest({...row,status:row.effective_status});}

export async function createChapterWritingRequest(documentId:string,input:{operationKind:AiOperation;baseBodyVersionId?:string|null;selectionStart?:number|null;selectionEnd?:number|null;instruction?:string;expectedRevision:number;idempotencyKey:string;createdBy?:string}):Promise<ChapterWritingRequest>{
  const pool=await getNewDesignPool(),documentHead=assertFound((await pool.query("SELECT * FROM new_design.chapter_documents WHERE id=$1",[documentId])).rows[0],"章节正文档案不存在。"),requestHash=stableHash({documentId,...input,createdBy:input.createdBy??""}),prior=(await pool.query("SELECT * FROM new_design.chapter_writing_requests WHERE book_id=$1 AND idempotency_key=$2",[documentHead.book_id,input.idempotencyKey])).rows[0];
  if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError("请求幂等键已用于不同的 AI 操作。",409);return mapRequest(prior);}
  const client=await pool.connect(),requestId=randomUUID();
    try{await client.query("BEGIN");const document=assertFound((await client.query("SELECT document.*,book.space_id FROM new_design.chapter_documents document JOIN new_design.books book ON book.id=document.book_id WHERE document.id=$1 FOR UPDATE OF document",[documentId])).rows[0],"章节正文档案不存在。"),committed=(await client.query("SELECT * FROM new_design.chapter_writing_requests WHERE book_id=$1 AND idempotency_key=$2",[document.book_id,input.idempotencyKey])).rows[0];if(committed){if(String(committed.request_hash)!==requestHash)throw new NewDesignError("请求幂等键已用于不同的 AI 操作。",409);await client.query("ROLLBACK");return mapRequest(committed);}if(Number(document.revision)!==input.expectedRevision)conflict(document);const plan=await adoptedPlan(client,document),base=await requireBodyVersion(client,documentId,input.baseBodyVersionId,"输入正文版本");if(input.operationKind!=="regenerate"&&!base)throw new NewDesignError("该操作需要选择一个输入正文版本。",422);const start=input.selectionStart??null,end=input.selectionEnd??null;if((start===null)!==(end===null))throw new NewDesignError("选区起止位置必须同时提供。",422);if(base&&start!==null&&(start<0||end!<=start||end!>String(base.content).length))throw new NewDesignError("选区超出输入正文范围。",422);const contract=assertFound((await client.query(`SELECT contract.task_key,version.id version_id,version.prompt_recipe_version_id,version.output_schema_version FROM new_design.task_contracts contract JOIN new_design.task_contract_versions version ON version.id=contract.published_version_id WHERE contract.status='active' AND version.task_group IN ('writing','chapter','chapter_writing') ORDER BY CASE WHEN contract.task_key='chapter.write' THEN 0 ELSE 1 END,version.created_at DESC LIMIT 1`)).rows[0],"章节写作任务尚未配置，AI 操作暂不可提交。"),manifest=assertFound((await client.query(`SELECT manifest.id,manifest.model_route_snapshot_id FROM new_design.context_manifests manifest WHERE manifest.book_id=$1 AND manifest.task_contract_version_id=$2 AND manifest.chapter_id=$3 AND manifest.status='finalized' ORDER BY manifest.finalized_at DESC,manifest.id DESC LIMIT 1`,[document.book_id,contract.version_id,document.chapter_card_id])).rows[0],"本章还没有可运行的上下文快照，请先完成上下文装配。");await client.query(`INSERT INTO new_design.chapter_writing_requests(id,book_id,chapter_document_id,operation_kind,planning_object_id,planning_version_id,planning_content_hash,context_manifest_id,task_contract_version_id,prompt_recipe_version_id,model_route_snapshot_id,input_body_version_id,input_body_hash,selection_start,selection_end,instruction,expected_document_revision,request_hash,idempotency_key,created_by)
      VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`,[requestId,document.book_id,documentId,input.operationKind,plan.planning_object_id,plan.planning_version_id,plan.planning_content_hash,manifest.id,contract.version_id,contract.prompt_recipe_version_id,manifest.model_route_snapshot_id,base?String(base.id):null,base?String(base.content_hash):null,start,end,input.instruction??"",input.expectedRevision,requestHash,input.idempotencyKey,input.createdBy??"user"]);await client.query("COMMIT");
  }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  try{const frozen=(await pool.query("SELECT * FROM new_design.chapter_writing_requests WHERE id=$1",[requestId])).rows[0],run=await createAiRunPreview({bookId:String(documentHead.book_id),taskContractVersionId:String(frozen.task_contract_version_id),taskNodeKey:"generate_candidate",sourceRoute:`/new-design/books/${documentHead.book_id}/writing?chapter=${documentHead.chapter_card_id}`,sourceKind:"chapter_writing_request",sourceId:requestId,chapterId:String(documentHead.chapter_card_id),inputSnapshot:{operationKind:input.operationKind,inputBodyVersionId:frozen.input_body_version_id,selectionStart:frozen.selection_start,selectionEnd:frozen.selection_end,instruction:frozen.instruction,planningVersionId:frozen.planning_version_id},safeCheckpoint:{chapterDocumentId:documentId,documentRevision:input.expectedRevision,bodyVersionId:documentHead.adopted_version_id??undefined},totalBudget:16000,idempotencyKey:`cw-preview:${input.idempotencyKey}`,createdBy:input.createdBy??"user"}),submitted=await submitAiRunPreview(run.id,{expectedRevision:run.revision,idempotencyKey:`cw-submit:${input.idempotencyKey}`,submittedBy:input.createdBy??"user"});const row=(await pool.query("UPDATE new_design.chapter_writing_requests SET context_manifest_id=$2,prompt_recipe_version_id=$3,model_route_snapshot_id=$4,ai_task_id=$5,status='queued',updated_at=now() WHERE id=$1 RETURNING *",[requestId,run.contextManifestId,run.promptRecipeVersionId,run.modelRouteSnapshotId,submitted.aiTaskId])).rows[0];return mapRequest(row);}catch(error){const message=error instanceof Error?error.message:"AI 任务进入队列失败。";const row=(await pool.query("UPDATE new_design.chapter_writing_requests SET status='unavailable',error_summary=$2,updated_at=now() WHERE id=$1 RETURNING *",[requestId,message.slice(0,2000)])).rows[0];return mapRequest(row);}
}

export async function ingestChapterWritingResult(requestId:string,input:{attemptId:string;content:string;idempotencyKey:string;createdBy?:string}):Promise<ChapterDocumentDetail>{
  const pool=await getNewDesignPool(),client=await pool.connect();
  try{
    await client.query("BEGIN");
    const request=assertFound((await client.query("SELECT * FROM new_design.chapter_writing_requests WHERE id=$1 FOR UPDATE",[requestId])).rows[0],"章节写作请求不存在。");
    const document=assertFound((await client.query("SELECT * FROM new_design.chapter_documents WHERE id=$1 FOR UPDATE",[request.chapter_document_id])).rows[0],"章节正文档案不存在。");
    const content=input.content;
    if(!content.trim())throw new NewDesignError("AI 返回正文不能为空。",422);
    const resultRequestHash=stableHash({requestId,attemptId:input.attemptId,contentHash:hashText(content)});
    const prior=(await client.query("SELECT * FROM new_design.chapter_body_operations WHERE book_id=$1 AND idempotency_key=$2",[request.book_id,input.idempotencyKey])).rows[0];
    if(prior){if(String(prior.chapter_document_id)!==String(document.id)||String(prior.request_hash)!==resultRequestHash)throw new NewDesignError("结果幂等键已用于不同的正文候选。",409);await client.query("ROLLBACK");return getChapterDocument(String(document.id));}
    if(request.result_body_version_id)throw new NewDesignError("该写作请求已保存正文候选，不能再次接收不同结果。",409);
    if(Number(document.revision)!==Number(request.expected_document_revision))conflict(document);
    const attempt=assertFound((await client.query("SELECT * FROM new_design.ai_task_attempts WHERE id=$1 AND task_id=$2 AND status='running'",[input.attemptId,request.ai_task_id])).rows[0],"AI 尝试不存在、未运行或不属于本次请求。");
    if(String(attempt.context_manifest_id)!==String(request.context_manifest_id)||String(attempt.task_contract_version_id)!==String(request.task_contract_version_id)||String(attempt.prompt_recipe_version_id)!==String(request.prompt_recipe_version_id)||String(attempt.model_route_snapshot_id)!==String(request.model_route_snapshot_id))throw new NewDesignError("AI 尝试使用的冻结来源与写作请求不一致。",422);
    const number=Number((await client.query("SELECT COALESCE(max(version),0)+1 version FROM new_design.chapter_body_versions WHERE chapter_document_id=$1",[document.id])).rows[0].version),versionId=randomUUID(),revision=Number(document.revision)+1;
    await client.query(`INSERT INTO new_design.chapter_body_versions(id,chapter_document_id,version,parent_version_id,base_version_id,source,operation_kind,planning_object_id,planning_version_id,context_manifest_id,task_contract_version_id,prompt_recipe_version_id,model_route_snapshot_id,ai_task_id,ai_attempt_id,input_body_version_id,selection_start,selection_end,created_by_kind,created_by,content,content_hash)
      VALUES($1,$2,$3,$4,$4,'ai_candidate',$5,$6,$7,$8,$9,$10,$11,$12,$13,$4,$14,$15,'ai',$16,$17,$18)`,[versionId,document.id,number,request.input_body_version_id,request.operation_kind,request.planning_object_id,request.planning_version_id,request.context_manifest_id,request.task_contract_version_id,request.prompt_recipe_version_id,request.model_route_snapshot_id,request.ai_task_id,input.attemptId,request.selection_start,request.selection_end,input.createdBy??"ai",content,hashText(content)]);
    await client.query("UPDATE new_design.chapter_documents SET revision=$2,updated_at=now() WHERE id=$1",[document.id,revision]);
    await client.query("UPDATE new_design.chapter_writing_requests SET result_body_version_id=$2,status='succeeded',updated_at=now() WHERE id=$1",[requestId,versionId]);
    await client.query("INSERT INTO new_design.chapter_body_operations(id,book_id,chapter_document_id,operation_kind,expected_revision,result_revision,result_body_version_id,request_hash,idempotency_key,actor) VALUES($1,$2,$3,'save_candidate',$4,$5,$6,$7,$8,$9)",[randomUUID(),request.book_id,document.id,request.expected_document_revision,revision,versionId,resultRequestHash,input.idempotencyKey,input.createdBy??"ai"]);
    await client.query("COMMIT");
    return getChapterDocument(String(document.id));
  }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}

export async function prepareChapterAdoption(documentId:string,input:{bodyVersionId:string;expectedRevision:number;idempotencyKey:string;createdBy?:string}):Promise<ChapterAdoptionPreparation>{
  const pool=await getNewDesignPool(),client=await pool.connect();
  try{await client.query("BEGIN");const document=assertFound((await client.query("SELECT * FROM new_design.chapter_documents WHERE id=$1 FOR UPDATE",[documentId])).rows[0],"章节正文档案不存在。"),prior=(await client.query("SELECT * FROM new_design.chapter_adoption_preparations WHERE book_id=$1 AND idempotency_key=$2",[document.book_id,input.idempotencyKey])).rows[0];if(prior){if(String(prior.chapter_document_id)!==documentId||String(prior.body_version_id)!==input.bodyVersionId)throw new NewDesignError("采用确认幂等键已用于其他候选。",409);await client.query("ROLLBACK");return mapPreparation(prior);}if(Number(document.revision)!==input.expectedRevision)conflict(document);const body=assertFound((await client.query("SELECT * FROM new_design.chapter_body_versions WHERE id=$1 AND chapter_document_id=$2",[input.bodyVersionId,documentId])).rows[0],"正文候选不存在或属于其他章节。");if(body.archived_at)throw new NewDesignError("已归档候选不能进入采用确认。",409);const plan=await adoptedPlan(client,document);if(String(body.planning_version_id??"")!==String(plan.planning_version_id))throw new NewDesignError("候选依据的章节计划已变化，请重新生成或另存候选。",409);const dependency={chapterDocumentId:documentId,bodyVersionId:input.bodyVersionId,bodyContentHash:String(body.content_hash),documentRevision:Number(document.revision),planningObjectId:String(plan.planning_object_id),planningVersionId:String(plan.planning_version_id),planningContentHash:String(plan.planning_content_hash),contextManifestId:asText(body.context_manifest_id),aiTaskId:asText(body.ai_task_id),aiAttemptId:asText(body.ai_attempt_id)},hash=stableHash(dependency),id=randomUUID(),row=(await client.query(`INSERT INTO new_design.chapter_adoption_preparations(id,book_id,chapter_document_id,body_version_id,expected_document_revision,planning_object_id,planning_version_id,planning_content_hash,context_manifest_id,dependency_snapshot,dependency_hash,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13) RETURNING *`,[id,document.book_id,documentId,input.bodyVersionId,input.expectedRevision,plan.planning_object_id,plan.planning_version_id,plan.planning_content_hash,body.context_manifest_id,JSON.stringify(dependency),hash,input.idempotencyKey,input.createdBy??"user"])).rows[0];await client.query("COMMIT");return mapPreparation(row);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}

export async function getChapterAdoptionPreparation(id:string):Promise<ChapterAdoptionPreparation>{const row=assertFound((await(await getNewDesignPool()).query("SELECT * FROM new_design.chapter_adoption_preparations WHERE id=$1",[id])).rows[0],"采用确认资料不存在。");return mapPreparation(row);}
