import {imageGenerationInputSchema,imageConnectionInputSchema,IMAGE_SIZES,type ImageGenerationInput,type SaveImageConnectionInput,type ImageGenerationResult} from "../../common/imageGeneration";
export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface ImageDraft {title:string;description:string;prompt:string;kind:"cover"|"illustration";size:typeof IMAGE_SIZES[number];connectionVersionId:string}
export interface ImagePending {input:ImageGenerationInput;requestId:string|null;operation:"generate"|"complete"|"end";checked:boolean;notWritten:boolean}
export interface ImageEditorMarker {version:1;bookId:string;draft:ImageDraft;pending:ImagePending|null}
export const blankImageDraft=():ImageDraft=>({title:"",description:"",prompt:"",kind:"cover",size:"1024x1024",connectionVersionId:""});
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value&&typeof value==='object'&&!Array.isArray(value));
export function parseImageMarker(raw:string,bookId:string):ImageEditorMarker|null{try{if(raw.length>30000)return null;const value:unknown=JSON.parse(raw);if(!record(value)||value.version!==1||value.bookId!==bookId||!record(value.draft))return null;const draft=value.draft;if(typeof draft.title!=='string'||draft.title.length>240||typeof draft.description!=='string'||draft.description.length>4000||typeof draft.prompt!=='string'||draft.prompt.length>4000||!['cover','illustration'].includes(String(draft.kind))||!(IMAGE_SIZES as readonly string[]).includes(String(draft.size))||typeof draft.connectionVersionId!=='string'||draft.connectionVersionId!==''&&!UUID.test(draft.connectionVersionId))return null;
 let pending:ImagePending|null=null;if(value.pending!==null){if(!record(value.pending))return null;const input=imageGenerationInputSchema.safeParse(value.pending.input);if(!input.success||input.data.bookId!==bookId||value.pending.requestId!==null&&(typeof value.pending.requestId!=='string'||!UUID.test(value.pending.requestId))||!['generate','complete','end'].includes(String(value.pending.operation)))return null;pending={input:input.data,requestId:value.pending.requestId as string|null,operation:value.pending.operation as ImagePending['operation'],checked:false,notWritten:false};}
 return{version:1,bookId,draft:draft as unknown as ImageDraft,pending};}catch{return null;}}
export function parseImageConnectionMarker(raw:string):SaveImageConnectionInput|null{try{if(raw.length>30000)return null;const value:unknown=JSON.parse(raw),parsed=imageConnectionInputSchema.safeParse(value);return parsed.success?parsed.data:null;}catch{return null;}}
export interface ImageConnectionDraft {endpoint:string;model:string;credential:string;timeout:number;sizes:SaveImageConnectionInput['sizes'];confirmed:boolean;baseline:{id:string|null;revision:number|null}}
export function parseImageConnectionDraft(raw:string):ImageConnectionDraft|null{try{if(raw.length>30000)return null;const value:unknown=JSON.parse(raw);if(!record(value)||typeof value.endpoint!=='string'||value.endpoint.length>1000||/[?@#]/.test(value.endpoint)||typeof value.model!=='string'||value.model.length>300||typeof value.credential!=='string'||value.credential!==''&&!UUID.test(value.credential)||typeof value.timeout!=='number'||!Number.isInteger(value.timeout)||value.timeout<1000||value.timeout>600000||!Array.isArray(value.sizes)||value.sizes.length>3||!value.sizes.every(size=>(IMAGE_SIZES as readonly unknown[]).includes(size))||new Set(value.sizes).size!==value.sizes.length||typeof value.confirmed!=='boolean'||!record(value.baseline)||value.baseline.id!==null&&(typeof value.baseline.id!=='string'||!UUID.test(value.baseline.id))||value.baseline.revision!==null&&(typeof value.baseline.revision!=='number'||!Number.isInteger(value.baseline.revision)||value.baseline.revision<1)||(value.baseline.id===null)!==(value.baseline.revision===null))return null;return value as unknown as ImageConnectionDraft;}catch{return null;}}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`;return JSON.stringify(value);}
export async function imageInputHash(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(stable(value)));return Array.from(new Uint8Array(bytes),item=>item.toString(16).padStart(2,'0')).join('');}
export async function sameImageResult(pending:ImagePending,result:ImageGenerationResult){return UUID.test(result.requestId)&&result.bookId===pending.input.bookId&&result.requestKey===pending.input.requestKey&&result.inputHash===await imageInputHash(pending.input)&&(!pending.requestId||pending.requestId===result.requestId)&&(!result.asset||result.asset.bookId===result.bookId&&result.asset.requestKey===result.requestKey);}
export const hasNotWrittenProof=(error:unknown)=>record(error)&&record(error.recovery)&&error.recovery.mutationOutcome==='not_written';
export function imageFailure(error:unknown,stage:string){const fields:Record<string,string>={title:'图片名称',description:'画面说明',prompt:'画面要求',kind:'图片用途',size:'图片尺寸',connectionVersionId:'图片连接版本',endpoint:'服务地址',model:'图像模型',credentialId:'服务凭据引用',timeoutMs:'等待时间',capabilities:'图片输出能力',sizes:'支持尺寸'};let locations:string[]=[];if(record(error)){if(record(error.issues))locations=Object.keys(error.issues).map(key=>fields[key.split('.').at(-1)??'']??'图片输入');else if(Array.isArray(error.issues))locations=error.issues.flatMap(issue=>record(issue)&&Array.isArray(issue.path)?[fields[String(issue.path.at(-1))]??'图片输入']:[]);}const recovery=record(error)&&record(error.recovery)?error.recovery:null;return{stage:typeof recovery?.failedStep==='string'?recovery.failedStep:stage,message:error instanceof Error?error.name==='ZodError'?'请核对图片必填项、连接版本及尺寸。':error.message:'原图片操作结果未确认，请核对原请求。',retained:typeof recovery?.savedResult==='string'?recovery.savedResult:'画面填写、原请求、已有图片与已保存原回复保留。',locations:[...new Set(locations)].join('、')};}
export function focusImageFailure(container:HTMLElement|null,locations:string){const fields:Record<string,string>={'图片名称':'title','画面说明':'description','画面要求':'prompt','图片用途':'kind','图片尺寸':'size','图片连接版本':'connectionVersionId','服务地址':'endpoint','图像模型':'model','服务凭据引用':'credentialId','等待时间':'timeoutMs','图片输出能力':'capabilities','支持尺寸':'sizes'};for(const label of locations.split('、')){const key=fields[label],target=key?container?.querySelector<HTMLElement>(`[data-image-field="${key}"]`):null;if(target){target.focus();target.scrollIntoView({block:'nearest'});return;}}}
