import type {PoolClient} from "pg";
import type {WorldConsistencyCatalog,WorldConsistencySubject} from "../../../common/worldConsistency";
import {getBookInTransaction} from "../templateStore";
import {readProfessionalObjectsInTransaction,professionalFields} from "../worldCharacterMaintenance";
import {stableHash} from "../aiContracts";
import {NewDesignError} from "../../domain/errors";
export async function readWorldConsistencyCatalog(client:PoolClient,bookId:string,selection?:{cardIds:string[];relationIds:string[]},lock=false):Promise<WorldConsistencyCatalog>{
 const book=await getBookInTransaction(client,bookId);if(book.status!=="active")throw new NewDesignError("本书已归档；一致性检查不会覆盖历史。",409);
 if(lock){await client.query("SELECT id FROM new_design.cards WHERE space_id=$1 ORDER BY id FOR SHARE",[book.spaceId]);await client.query("SELECT id FROM new_design.field_definitions WHERE space_id=$1 ORDER BY id FOR SHARE",[book.spaceId]);await client.query("SELECT id FROM new_design.card_types WHERE space_id=$1 ORDER BY id FOR SHARE",[book.spaceId]);await client.query("SELECT id FROM new_design.relation_types WHERE owner_space_id=$1 OR owner_space_id IS NULL ORDER BY id FOR SHARE",[book.spaceId]);await client.query("SELECT id FROM new_design.card_relations WHERE space_id=$1 ORDER BY id FOR SHARE",[book.spaceId]);}
 const read=await readProfessionalObjectsInTransaction(client,book.spaceId);if(read.truncated)throw new NewDesignError("本书资料超过检查目录上限，请在来源页分范围维护；不会截断后声称全书检查。",422);
 const subjects:WorldConsistencySubject[]=read.objects.filter(object=>!selection||selection.cardIds.includes(object.id)).map(object=>{if(object.unavailableReason||!object.versionId)throw new NewDesignError(`“${object.title}”的正式来源不可用，请先核对档案。`,409);return{kind:"card",id:object.id,versionId:object.versionId,revision:object.revision,label:object.title,typeId:object.typeId,typeLabel:object.typeLabel,fields:object.fields.map(({field,versionId})=>({key:field.key,label:field.name,specVersionId:versionId,specHash:stableHash(field),specification:field,value:object.values[field.key]??null}))};});
 const relations=(await client.query(`SELECT relation.*,type.name type_label,type.status type_status,type.properties_schema,version.properties frozen_properties,version.revision frozen_revision,version.status frozen_status,source.current_version_id source_version,target.current_version_id target_version,version.source_card_version_id,version.target_card_version_id
 FROM new_design.card_relations relation JOIN new_design.relation_types type ON type.id=relation.relation_type_id
 JOIN new_design.card_relation_versions version ON version.id=relation.current_version_id AND version.card_relation_id=relation.id
 JOIN new_design.cards source ON source.id=relation.source_card_id AND source.space_id=relation.space_id AND source.status='active'
 JOIN new_design.cards target ON target.id=relation.target_card_id AND target.space_id=relation.space_id AND target.status='active'
 WHERE relation.space_id=$1 AND relation.status='active' AND (type.owner_space_id IS NULL OR type.owner_space_id=$1) ORDER BY relation.id LIMIT 301`,[book.spaceId])).rows;
 if(relations.length>300)throw new NewDesignError("正式关系超过检查上限，不会默默截断。",422);
 for(const row of relations.filter(row=>!selection||selection.relationIds.includes(String(row.id)))){if(row.type_status!=="published"||row.revision!==row.frozen_revision||row.frozen_status!=="active"||stableHash(row.properties)!==stableHash(row.frozen_properties)||row.source_version!==row.source_card_version_id||row.target_version!==row.target_card_version_id)throw new NewDesignError("正式关系或端点版本已变化，请明确维护真实关系后检查。",409);subjects.push({kind:"relation",id:String(row.id),versionId:String(row.current_version_id),revision:Number(row.revision),label:String(row.type_label),typeId:String(row.relation_type_id),typeLabel:String(row.type_label),sourceId:String(row.source_card_id),targetId:String(row.target_card_id),fields:professionalFields(row.properties_schema).map(field=>({key:field.key,label:field.name,specVersionId:null,specHash:stableHash(field),specification:field,value:row.properties[field.key]??null}))});}
 if(selection&&(selection.cardIds.some(id=>!subjects.some(s=>s.kind==="card"&&s.id===id))||selection.relationIds.some(id=>!subjects.some(s=>s.kind==="relation"&&s.id===id))))throw new NewDesignError("所选资料／关系不属于当前本书正式来源，不替换其他对象。",409);
 const dictionaryIds=[...new Set(subjects.flatMap(subject=>subject.fields.flatMap(field=>field.specification.optionSource?.kind==="dictionary_tree"?[field.specification.optionSource.dictionaryId]:[])))];
 if(lock&&dictionaryIds.length){await client.query("SELECT id FROM new_design.dictionary_definitions WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE",[dictionaryIds]);await client.query("SELECT id FROM new_design.dictionary_items WHERE dictionary_id=ANY($1::uuid[]) ORDER BY id FOR SHARE",[dictionaryIds]);}
 const dictionaryRows=dictionaryIds.length?(await client.query("SELECT item.*,version.label FROM new_design.dictionary_items item JOIN new_design.dictionary_definitions definition ON definition.id=item.dictionary_id AND definition.status='published' AND (definition.owner_space_id IS NULL OR definition.owner_space_id=$2) JOIN new_design.dictionary_item_versions version ON version.id=item.current_version_id AND version.item_id=item.id WHERE item.dictionary_id=ANY($1::uuid[]) ORDER BY item.dictionary_id,item.id LIMIT 5001",[dictionaryIds,book.spaceId])).rows:[];
 if(dictionaryRows.length>5000||dictionaryIds.some(id=>!dictionaryRows.some(row=>row.dictionary_id===id)))throw new NewDesignError("正式字典目录缺失或超过冻结上限，请核对原字典，不以自由文字替代选项。",422);
 const dictionaryNodes:WorldConsistencyCatalog["dictionaryNodes"]=dictionaryRows.map(row=>({dictionaryId:String(row.dictionary_id),id:String(row.id),parentId:row.parent_id?String(row.parent_id):null,versionId:String(row.current_version_id),label:String(row.label),status:row.status}));
 const payload={bookId,subjects,dictionaryNodes};return{...payload,hash:stableHash(payload)};
}
