import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import type {WorldConsistencyInput,WorldConsistencyReceipt,WorldConsistencyFailure,WorldConsistencyOutput} from "../../../common/worldConsistency";
import {getWorldConsistencyPool as getNewDesignPool} from "./pool";
import {assertFound,NewDesignError} from "../../domain/errors";
import {stableHash} from "../aiContracts";
import {readWorldConsistencyCatalog} from "./catalog";
import {freezeWorldConsistency,type WorldFrozenPlan} from "./freeze";
export class WorldConsistencyError extends NewDesignError {readonly recovery:WorldConsistencyFailure;constructor(bookId:string,step:string,summary:string,outcome:"unknown"|"not_written"="unknown",status=503,savedResult?:string){super(summary,status);this.recovery={failedStep:step,summary,savedResult:savedResult??(outcome==='not_written'?"本次领取准备已确认回滚且尚未开始提交，未发送模型；原档案、关系、问题和人工填写保留。":"原正式档案、关系、问题与已保存模型回复保留；未知请核对同一原凭证，不重发模型。"),sourceRoute:`/new-design/books/${bookId}/world`,actionLabel:"返回世界维护",mutationOutcome:outcome};}}
export async function worldTransaction<T>(bookId:string,key:string|undefined,action:(client:PoolClient,markPreparationAbsent:()=>void)=>Promise<T>,proofKind:'preparation'|'repair'='preparation'):Promise<T>{
 const client=await(await getNewDesignPool()).connect();let preparationAbsent=false,commitStarted=false;try{await client.query("BEGIN");if(key)await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[proofKind==='repair'?`world_repair:${key}`:`world_consistency:${bookId}:${key}`]);await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`world_consistency_book:${bookId}`]);const result=await action(client,()=>{preparationAbsent=true;});commitStarted=true;await client.query("COMMIT");return result;}catch(error){let rollbackAcknowledged=false;try{await client.query("ROLLBACK");rollbackAcknowledged=true;}catch{/* Never turn a missing acknowledgement into proof. */}if(error instanceof WorldConsistencyError)throw error;const absent=preparationAbsent&&!commitStarted&&rollbackAcknowledged,repair=proofKind==='repair';throw new WorldConsistencyError(bookId,repair?'登记原正常资料修复':absent?"准备世界检查来源":"核对世界检查回执",error instanceof NewDesignError?error.message:absent?(repair?'本次修复登记已确认回滚；原正常保存不撤销，请核对并明确完成同一原登记。':"本次准备已确认未保存、未调用模型；原填写保留，请修复来源或配置后明确重新准备。"):"世界检查保存回执尚未确认，请核对原请求，不会自动重发。",absent?"not_written":"unknown",error instanceof NewDesignError?error.status:503,repair?'原资料已经正常保存，原AI回复与人工修改保留；本操作只登记原修复，不保存资料、不调用模型。':undefined);}finally{client.release();}
}
export interface WorldRequestRow extends Record<string,unknown> {
 id:string;book_id:string;request_key:string;request_hash:string;input_hash:string;input_payload:WorldConsistencyInput;frozen_plan:WorldFrozenPlan;
 ai_task_id:string;step_id:string;attempt_id:string;report_id:string|null;status:WorldConsistencyReceipt['status'];model_request_state:WorldConsistencyReceipt['modelRequestState'];
 generated_output:WorldConsistencyOutput|null;generated_execution:Record<string,unknown>|null;failure:WorldConsistencyFailure|null;
 lease_expired:boolean|null;lease_token:string|null;attempt_status:string;report_stale_at:Date|string|null;
}
export async function readWorldRequest(client:PoolClient,bookId:string,id?:string,key?:string,locked=false):Promise<WorldRequestRow|null>{
 const query=`SELECT request.*,step.lease_expires_at<=now() lease_expired,step.lease_token,attempt.status attempt_status,report.stale_at report_stale_at FROM new_design.world_consistency_requests request JOIN new_design.ai_task_steps step ON step.id=request.step_id JOIN new_design.ai_task_attempts attempt ON attempt.id=request.attempt_id LEFT JOIN new_design.quality_audit_reports report ON report.id=request.report_id WHERE request.book_id=$1 AND ${id?"request.id=$2":"request.request_key=$2"}`;
 let row=(await client.query<WorldRequestRow>(query,[bookId,id??key])).rows[0]??null;if(row&&locked){
  await client.query("SELECT id FROM new_design.ai_tasks WHERE id=$1 FOR UPDATE",[row.ai_task_id]);
  await client.query("SELECT id FROM new_design.ai_task_steps WHERE id=$1 FOR UPDATE",[row.step_id]);
  await client.query("SELECT id FROM new_design.ai_task_attempts WHERE id=$1 FOR UPDATE",[row.attempt_id]);
  await client.query("SELECT id FROM new_design.world_consistency_requests WHERE id=$1 AND book_id=$2 FOR UPDATE",[row.id,bookId]);row=(await client.query<WorldRequestRow>(query,[bookId,id??key])).rows[0]??null;
 }return row;
}
export function worldReceipt(row:WorldRequestRow):WorldConsistencyReceipt {return{id:String(row.id),bookId:String(row.book_id),requestKey:String(row.request_key),requestHash:String(row.request_hash),input:row.input_payload,inputHash:String(row.input_hash),status:row.report_stale_at?"stale":row.status,modelRequestState:row.model_request_state,reportId:row.report_id??null,modelResultSaved:Boolean(row.generated_output),output:row.generated_output??null,catalog:row.frozen_plan.catalog,canImportSavedResult:row.status==="running"&&Boolean(row.generated_output)&&!row.lease_expired,canReleaseSavedResult:row.status==="running"&&Boolean(row.generated_output),canEndExpiredUnknown:row.status==="running"&&!row.generated_output&&Boolean(row.lease_expired),failure:row.failure??null};}
export async function worldEvent(client:PoolClient,row:{taskId:string;stepId:string;attemptId:string},kind:"task"|"step"|"attempt",from:string|null,to:string,reason:string,revision:number|null=null){await client.query("INSERT INTO new_design.ai_task_state_events(id,task_id,step_id,attempt_id,entity_kind,from_status,to_status,checkpoint_key,reason_code,reason_detail,actor_kind,actor,entity_revision) VALUES($1,$2,$3,$4,$5,$6,$7,'world_consistency',$8,'精确档案检查；局部质量债不停止全书','user','world_consistency',$9)",[randomUUID(),row.taskId,kind==="task"?null:row.stepId,kind==="attempt"?row.attemptId:null,kind,from,to,reason,revision]);}
export async function claimWorldConsistency(bookId:string,input:WorldConsistencyInput):Promise<{claimed:boolean;receipt:WorldConsistencyReceipt;plan:WorldFrozenPlan}>{return worldTransaction(bookId,input.requestKey,async (client,markPreparationAbsent)=>{
 const requestHash=stableHash({bookId,input}),prior=await readWorldRequest(client,bookId,undefined,input.requestKey,true);if(prior){if(prior.request_hash!==requestHash)throw new WorldConsistencyError(bookId,"核对原检查输入","原键已经用于不同来源，请保留原凭证，不替换当前版本。","unknown",409);return{claimed:false,receipt:worldReceipt(prior),plan:prior.frozen_plan};}
 if((await client.query("SELECT id FROM new_design.ai_tasks WHERE book_id=$1 AND source_kind='world_consistency' AND request_idempotency_key=$2 LIMIT 1",[bookId,input.requestKey])).rowCount)throw new WorldConsistencyError(bookId,"核对原运行来源","原任务存在但请求凭证尚不可读，请保留原键，只核对原回执。","unknown",409);markPreparationAbsent();
 const full=await readWorldConsistencyCatalog(client,bookId,undefined,true);if(full.hash!==input.catalogHash)throw new NewDesignError("正式资料、字段、字典或关系已变化，请重新读取来源；本次尚未调用模型。",409);
 const catalog=await readWorldConsistencyCatalog(client,bookId,input,true);let recheck:WorldFrozenPlan["recheck"]=null;
 if(input.recheckIssueId){
  const issue=assertFound((await client.query("SELECT issue.*,version.title,version.description FROM new_design.quality_issues issue JOIN new_design.quality_issue_versions version ON version.id=issue.current_version_id WHERE issue.id=$1 AND issue.book_id=$2 AND version.category_key='world_consistency' FOR UPDATE OF issue",[input.recheckIssueId,bookId])).rows[0],"本书原世界复查问题不存在。");
  if(issue.current_status!=="fixed")throw new NewDesignError("请先正常保存全部修复，并记录正式修复后再复查；未修复不判通过。",409);
  const evidence=(await client.query("SELECT * FROM new_design.quality_issue_evidence WHERE issue_version_id=$1",[issue.current_version_id])).rows;
  if(!evidence.length||evidence.some(entry=>!catalog.subjects.some(s=>s.kind===entry.material_kind&&s.id===entry.material_id&&s.fields.some(f=>f.key===entry.field_key))))throw new NewDesignError("复查未覆盖原问题全部正式证据；请选择原涉及资料和关系，不用部分检查替代复查。",409);
  const source=assertFound((await client.query<WorldRequestRow>("SELECT * FROM new_design.world_consistency_requests WHERE report_id=$1 AND book_id=$2",[issue.report_id,bookId])).rows[0],"原问题的精确世界报告来源不存在，不用其他报告代替。");
  recheck={issueId:String(issue.id),issueVersionId:String(issue.current_version_id),title:String(issue.title),description:String(issue.description),originalCatalog:source.frozen_plan.catalog,originalEvidence:evidence.map(entry=>({kind:entry.material_kind,id:String(entry.material_id),versionId:String(entry.card_version_id??entry.relation_version_id),fieldKey:String(entry.field_key),specVersionId:entry.field_spec_version_id??null,specHash:String(entry.field_spec_hash),valueHash:String(entry.observed_value_hash),note:String(entry.note)}))};
 }
 if((await client.query("SELECT id FROM new_design.world_consistency_requests WHERE book_id=$1 AND status='running' LIMIT 1",[bookId])).rowCount)throw new NewDesignError("本书已有原检查待核对，请先查看原请求；不能并发再次调用。",409);
 const id=randomUUID(),plan=await freezeWorldConsistency(client,bookId,id,catalog,recheck),book=assertFound((await client.query("SELECT space_id FROM new_design.books WHERE id=$1",[bookId])).rows[0],"本书不存在。"),refs={taskId:randomUUID(),stepId:randomUUID(),attemptId:randomUUID()},lease=randomUUID();
 await client.query("INSERT INTO new_design.ai_tasks(id,space_id,book_id,task_key,task_contract_version_id,source_route,source_kind,source_id,request_idempotency_key,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,'world_consistency',$7,$8,$9,'world_consistency')",[refs.taskId,book.space_id,bookId,`world_consistency_${id}`,plan.contractVersionId,`/new-design/books/${bookId}/world?check=${id}`,id,input.requestKey,requestHash]);
 await client.query("INSERT INTO new_design.ai_task_steps(id,task_id,step_key,sort_order,max_attempts) VALUES($1,$2,'world_consistency',0,1)",[refs.stepId,refs.taskId]);
 await client.query("INSERT INTO new_design.ai_task_attempts(id,task_id,step_id,attempt_number,trigger_kind,status,task_contract_version_id,prompt_recipe_version_id,context_manifest_id,model_route_snapshot_id,input_hash,output_schema_version,checkpoint_key,lease_token_digest,started_at) VALUES($1,$2,$3,1,'initial','running',$4,$5,$6,$7,$8,$9,'world_consistency',$10,now())",[refs.attemptId,refs.taskId,refs.stepId,plan.contractVersionId,plan.recipeVersionId,plan.manifestId,plan.snapshotId,plan.inputHash,stableHash(plan.prompt.outputSchema),stableHash(lease)]);
 await client.query("UPDATE new_design.ai_task_steps SET status='running',current_attempt_id=$2,checkpoint_key='world_consistency',lease_owner='world_consistency',lease_token=$3,lease_expires_at=now()+$4*interval '1 millisecond',heartbeat_at=now(),revision=revision+1 WHERE id=$1",[refs.stepId,refs.attemptId,lease,plan.route.policy.timeoutMs+60000]);await client.query("UPDATE new_design.ai_tasks SET status='running',current_step_key='world_consistency',current_checkpoint='world_consistency',revision=revision+1 WHERE id=$1",[refs.taskId]);
 await client.query("INSERT INTO new_design.world_consistency_requests(id,book_id,request_key,request_hash,input_hash,input_payload,frozen_plan,ai_task_id,step_id,attempt_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,$10)",[id,bookId,input.requestKey,requestHash,plan.inputHash,JSON.stringify(input),JSON.stringify(plan),refs.taskId,refs.stepId,refs.attemptId]);for(const kind of ["task","step","attempt"]as const)await worldEvent(client,refs,kind,kind==="attempt"?null:"queued","running","world_check_claimed",kind==="attempt"?null:2);
 return{claimed:true,receipt:worldReceipt(assertFound(await readWorldRequest(client,bookId,id),"原检查领取不存在。")),plan};
 });}
