import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import type { ModelCredentialRef, ModelRouteConfig, ModelRouteFallback, ModelRouteScope, ModelRouteSnapshot, ModelRouteVersion, ResolvedModelRoute, TechnicalFallbackCategory } from "../../../common/contracts";
import { NewDesignError, assertFound } from "../../domain/errors";
import { getNewDesignPool } from "../runtime";
import { asDate, asText, stableHash } from "./integrity";

const TECHNICAL_FAILURES=new Set<TechnicalFallbackCategory>(["timeout","rate_limit","authentication","provider_unavailable","transport","context_limit"]);
type FallbackInput={provider:string;model:string;parameters:Record<string,unknown>;credentialRefId?:string|null;technicalFailureCategories:TechnicalFallbackCategory[];sortOrder:number};
export type RouteVersionInput={source:"manual"|"import"|"system";provider?:string|null;model?:string|null;parameters?:Record<string,unknown>|null;requiredCapabilities?:string[]|null;credentialRefId?:string|null;budgetPolicy?:Record<string,unknown>|null;timeoutMs?:number|null;retryPolicy?:Record<string,unknown>|null;fallbackMode:"inherit"|"replace";fallbacks:FallbackInput[];baseVersionId?:string|null;createdBy?:string};
export type RouteConfigInput={scope:ModelRouteScope;taskGroup?:string|null;taskKey?:string|null;nodeKey?:string|null;bookId?:string|null;overrideKey?:string|null;name:string}&RouteVersionInput;
type InternalFallback=ModelRouteFallback&{credentialRefId:string|null};
type InternalResolved=Omit<ResolvedModelRoute,"fallbacks">&{credentialRefId:string|null;fallbacks:InternalFallback[]};

function publicCredential(row:Record<string,unknown>):ModelCredentialRef{return{id:String(row.id),credentialKey:String(row.credential_key),provider:String(row.provider),status:row.status as ModelCredentialRef["status"],hasLocator:true,createdAt:asDate(row.created_at),updatedAt:asDate(row.updated_at)};}
function publicFallback(row:Record<string,unknown>):ModelRouteFallback{return{provider:String(row.provider),model:String(row.model),parameters:(row.parameters??{}) as Record<string,unknown>,technicalFailureCategories:row.technical_failure_categories as TechnicalFallbackCategory[],hasCredential:Boolean(row.credential_ref_id),sortOrder:Number(row.sort_order)};}
async function mapVersion(client:PoolClient,row:Record<string,unknown>):Promise<ModelRouteVersion>{const fallbacks=(await client.query("SELECT * FROM new_design.model_route_fallbacks WHERE route_version_id=$1 ORDER BY sort_order,id",[row.id])).rows.map(publicFallback);return{id:String(row.id),configId:String(row.config_id),version:Number(row.version),baseVersionId:asText(row.base_version_id),source:row.source as ModelRouteVersion["source"],status:row.status as ModelRouteVersion["status"],provider:asText(row.provider),model:asText(row.model),parameters:row.parameters as Record<string,unknown>|null,requiredCapabilities:row.required_capabilities as string[]|null,hasCredential:Boolean(row.credential_ref_id),budgetPolicy:row.budget_policy as Record<string,unknown>|null,timeoutMs:row.timeout_ms===null?null:Number(row.timeout_ms),retryPolicy:row.retry_policy as Record<string,unknown>|null,fallbackMode:row.fallback_mode as ModelRouteVersion["fallbackMode"],contentHash:String(row.content_hash),createdBy:String(row.created_by),fallbacks,createdAt:asDate(row.created_at)};}

function validateScope(input:RouteConfigInput){const empty=(value:unknown)=>value===undefined||value===null||value==="",has=(...values:unknown[])=>values.some(value=>!empty(value));if(input.scope==="system_default"&&has(input.taskGroup,input.taskKey,input.nodeKey,input.bookId,input.overrideKey))throw new NewDesignError("系统默认路由不能携带范围字段。",422);if(input.scope==="task_group"&&(empty(input.taskGroup)||has(input.taskKey,input.nodeKey,input.bookId,input.overrideKey)))throw new NewDesignError("任务组路由只能指定 taskGroup。",422);if(input.scope==="task"&&(empty(input.taskKey)||has(input.nodeKey,input.bookId,input.overrideKey)))throw new NewDesignError("具体任务路由必须指定 taskKey，且只能附加 taskGroup。",422);if(input.scope==="node"&&(empty(input.nodeKey)||has(input.taskKey,input.bookId,input.overrideKey)))throw new NewDesignError("节点路由必须指定 nodeKey，且只能附加 taskGroup。",422);if(input.scope==="book"&&(empty(input.bookId)||has(input.taskGroup,input.taskKey,input.nodeKey,input.overrideKey)))throw new NewDesignError("书籍路由只能指定 bookId。",422);if(input.scope==="one_time"&&(empty(input.overrideKey)||has(input.taskGroup,input.taskKey,input.nodeKey)))throw new NewDesignError("单次覆盖必须指定 overrideKey，只能附加 bookId。",422);}
async function validateCredential(client:PoolClient,id:string|null|undefined,provider:string|null|undefined){if(!id)return;const row=assertFound((await client.query("SELECT provider,status FROM new_design.model_credential_refs WHERE id=$1",[id])).rows[0],"模型密钥引用不存在。");if(row.status!=="active")throw new NewDesignError("模型密钥引用已停用。",422);if(provider&&String(row.provider)!==provider)throw new NewDesignError("模型密钥引用与供应商不匹配。",422);}
async function validateVersion(client:PoolClient,input:RouteVersionInput,scope:ModelRouteScope){for(const fallback of input.fallbacks){if(!fallback.technicalFailureCategories.length||fallback.technicalFailureCategories.some((item)=>!TECHNICAL_FAILURES.has(item)))throw new NewDesignError("模型回退只允许技术故障类别，不能使用内容质量作为自动回退原因。",422);await validateCredential(client,fallback.credentialRefId,fallback.provider);}await validateCredential(client,input.credentialRefId,input.provider);if(scope==="system_default"&&(!input.provider||!input.model||!input.budgetPolicy||!input.timeoutMs||!input.retryPolicy))throw new NewDesignError("系统默认路由必须完整提供供应商、模型、预算、超时和重试策略。",422);}

async function insertVersion(client:PoolClient,config:Record<string,unknown>,version:number,input:RouteVersionInput,action:"create"|"edit"){await validateVersion(client,input,config.scope as ModelRouteScope);const base=input.baseVersionId??(config.current_version_id?String(config.current_version_id):null);if(base&&!((await client.query("SELECT 1 FROM new_design.model_route_versions WHERE id=$1 AND config_id=$2",[base,config.id])).rowCount))throw new NewDesignError("基础路由版本不存在。",422);const id=randomUUID(),hash=stableHash({provider:input.provider??null,model:input.model??null,parameters:input.parameters??null,requiredCapabilities:input.requiredCapabilities??null,credentialRefId:input.credentialRefId??null,budgetPolicy:input.budgetPolicy??null,timeoutMs:input.timeoutMs??null,retryPolicy:input.retryPolicy??null,fallbackMode:input.fallbackMode,fallbacks:input.fallbacks});const row=(await client.query("INSERT INTO new_design.model_route_versions(id,config_id,version,base_version_id,source,status,provider,model,parameters,required_capabilities,credential_ref_id,budget_policy,timeout_ms,retry_policy,fallback_mode,content_hash,created_by) VALUES($1,$2,$3,$4,$5,'draft',$6,$7,$8::jsonb,$9,$10,$11::jsonb,$12,$13::jsonb,$14,$15,$16) RETURNING *",[id,config.id,version,base,input.source,input.provider??null,input.model??null,input.parameters?JSON.stringify(input.parameters):null,input.requiredCapabilities??null,input.credentialRefId??null,input.budgetPolicy?JSON.stringify(input.budgetPolicy):null,input.timeoutMs??null,input.retryPolicy?JSON.stringify(input.retryPolicy):null,input.fallbackMode,hash,input.createdBy??""])).rows[0];for(const fallback of input.fallbacks)await client.query("INSERT INTO new_design.model_route_fallbacks(id,route_version_id,sort_order,provider,model,parameters,credential_ref_id,technical_failure_categories) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8)",[randomUUID(),id,fallback.sortOrder,fallback.provider,fallback.model,JSON.stringify(fallback.parameters),fallback.credentialRefId??null,fallback.technicalFailureCategories]);await client.query("UPDATE new_design.model_route_configs SET current_version_id=$2,revision=revision+CASE WHEN $3='edit' THEN 1 ELSE 0 END,updated_at=now() WHERE id=$1",[config.id,id,action]);return mapVersion(client,row);}

export async function saveModelCredentialRef(input:{credentialKey:string;provider:string;secretLocator:string;status?:"active"|"disabled"}):Promise<ModelCredentialRef>{const pool=await getNewDesignPool(),id=randomUUID();const row=(await pool.query(`INSERT INTO new_design.model_credential_refs(id,credential_key,provider,secret_locator,status) VALUES($1,$2,$3,$4,$5)
  ON CONFLICT(credential_key) DO UPDATE SET provider=excluded.provider,secret_locator=excluded.secret_locator,status=excluded.status,updated_at=now() RETURNING *`,[id,input.credentialKey,input.provider,input.secretLocator,input.status??"active"])).rows[0];return publicCredential(row);}
export async function getModelCredentialRef(id:string):Promise<ModelCredentialRef>{return publicCredential(assertFound((await(await getNewDesignPool()).query("SELECT id,credential_key,provider,status,created_at,updated_at FROM new_design.model_credential_refs WHERE id=$1",[id])).rows[0],"模型密钥引用不存在。"));}

export async function getModelRouteConfig(id:string):Promise<ModelRouteConfig>{const pool=await getNewDesignPool(),client=await pool.connect();try{const row=assertFound((await client.query("SELECT * FROM new_design.model_route_configs WHERE id=$1",[id])).rows[0],"模型路由配置不存在。"),versionRows=(await client.query("SELECT * FROM new_design.model_route_versions WHERE config_id=$1 ORDER BY version DESC",[id])).rows,versions:ModelRouteVersion[]=[];for(const version of versionRows)versions.push(await mapVersion(client,version));return{id:String(row.id),scope:row.scope,taskGroup:asText(row.task_group),taskKey:asText(row.task_key),nodeKey:asText(row.node_key),bookId:asText(row.book_id),overrideKey:asText(row.override_key),name:String(row.name),status:row.status,currentVersionId:String(row.current_version_id),publishedVersionId:asText(row.published_version_id),revision:Number(row.revision),currentVersion:assertFound(versions.find((item)=>item.id===String(row.current_version_id)),"路由当前版本不存在。"),publishedVersion:row.published_version_id?assertFound(versions.find((item)=>item.id===String(row.published_version_id)),"路由发布版本不存在。"):null,versions,createdAt:asDate(row.created_at),updatedAt:asDate(row.updated_at)};}finally{client.release();}}
export async function createModelRouteConfig(input:RouteConfigInput):Promise<ModelRouteConfig>{validateScope(input);const pool=await getNewDesignPool(),client=await pool.connect(),id=randomUUID();try{await client.query("BEGIN");if(input.bookId)assertFound((await client.query("SELECT id FROM new_design.books WHERE id=$1",[input.bookId])).rows[0],"路由所属书籍不存在。");const row=(await client.query("INSERT INTO new_design.model_route_configs(id,scope,task_group,task_key,node_key,book_id,override_key,name) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[id,input.scope,input.taskGroup??null,input.taskKey??null,input.nodeKey??null,input.bookId??null,input.overrideKey??null,input.name])).rows[0];await insertVersion(client,row,1,input,"create");await client.query("COMMIT");return getModelRouteConfig(id);}catch(error){await client.query("ROLLBACK");if((error as {code?:string}).code==="23505")throw new NewDesignError("该范围存在生效中的模型路由配置。",409);throw error;}finally{client.release();}}
export async function addModelRouteVersion(id:string,input:RouteVersionInput&{expectedRevision:number}):Promise<ModelRouteConfig>{const pool=await getNewDesignPool(),client=await pool.connect();try{await client.query("BEGIN");const config=assertFound((await client.query("SELECT * FROM new_design.model_route_configs WHERE id=$1 FOR UPDATE",[id])).rows[0],"模型路由配置不存在。");if(Number(config.revision)!==input.expectedRevision)throw new NewDesignError("模型路由配置已更新，请刷新后重试。",409);const version=Number((await client.query("SELECT COALESCE(max(version),0)+1 AS version FROM new_design.model_route_versions WHERE config_id=$1",[id])).rows[0].version);await insertVersion(client,config,version,input,"edit");await client.query("COMMIT");return getModelRouteConfig(id);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

export async function publishModelRouteVersion(id:string,input:{versionId:string;expectedRevision:number;idempotencyKey:string;actor?:string}):Promise<ModelRouteConfig>{const pool=await getNewDesignPool(),client=await pool.connect();try{await client.query("BEGIN");const repeated=(await client.query("SELECT entity_id FROM new_design.ai_contract_publications WHERE idempotency_key=$1",[input.idempotencyKey])).rows[0];if(repeated){if(String(repeated.entity_id)!==id)throw new NewDesignError("幂等键已用于其他路由。",409);await client.query("COMMIT");return getModelRouteConfig(id);}const config=assertFound((await client.query("SELECT * FROM new_design.model_route_configs WHERE id=$1 FOR UPDATE",[id])).rows[0],"模型路由配置不存在。");if(Number(config.revision)!==input.expectedRevision)throw new NewDesignError("模型路由配置已更新，请刷新后重试。",409);const target=assertFound((await client.query("SELECT * FROM new_design.model_route_versions WHERE id=$1 AND config_id=$2",[input.versionId,id])).rows[0],"待发布路由版本不存在。");if(target.status==="rejected")throw new NewDesignError("已驳回路由版本不能发布。",409);const fallbackRows=(await client.query("SELECT provider,credential_ref_id,technical_failure_categories FROM new_design.model_route_fallbacks WHERE route_version_id=$1",[input.versionId])).rows;await validateVersion(client,{source:target.source,provider:target.provider,model:target.model,parameters:target.parameters,requiredCapabilities:target.required_capabilities,credentialRefId:target.credential_ref_id,budgetPolicy:target.budget_policy,timeoutMs:target.timeout_ms,retryPolicy:target.retry_policy,fallbackMode:target.fallback_mode,fallbacks:fallbackRows.map((row,index)=>({provider:String(row.provider),model:"validated",parameters:{},credentialRefId:asText(row.credential_ref_id),technicalFailureCategories:row.technical_failure_categories,sortOrder:index}))},config.scope);const from=asText(config.published_version_id),action=from===input.versionId?"republish":from&&Number((await client.query("SELECT version FROM new_design.model_route_versions WHERE id=$1",[from])).rows[0].version)>Number(target.version)?"rollback":"publish",revision=Number(config.revision)+1;if(from&&from!==input.versionId)await client.query("UPDATE new_design.model_route_versions SET status='superseded' WHERE id=$1",[from]);await client.query("UPDATE new_design.model_route_versions SET status='published' WHERE id=$1",[input.versionId]);await client.query("UPDATE new_design.model_route_configs SET published_version_id=$2,revision=$3,updated_at=now() WHERE id=$1",[id,input.versionId,revision]);await client.query("INSERT INTO new_design.ai_contract_publications(id,entity_kind,entity_id,from_version_id,to_version_id,entity_revision,action,actor,idempotency_key) VALUES($1,'model_route',$2,$3,$4,$5,$6,$7,$8)",[randomUUID(),id,from,input.versionId,revision,action,input.actor??"user",input.idempotencyKey]);await client.query("COMMIT");return getModelRouteConfig(id);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

async function loadLayer(client:PoolClient,sql:string,params:unknown[]):Promise<Record<string,unknown>|null>{return(await client.query(`SELECT version.*,config.scope,config.id AS source_config_id FROM new_design.model_route_configs config JOIN new_design.model_route_versions version ON version.id=config.published_version_id WHERE config.status='active' AND ${sql} ORDER BY config.created_at DESC LIMIT 1`,params)).rows[0]??null;}
async function resolveInternal(client:PoolClient,input:{bookId:string;taskContractVersionId:string;nodeKey?:string|null;oneTimeOverrideKey?:string|null}):Promise<InternalResolved>{
  const task=assertFound((await client.query(`SELECT version.*,contract.task_key FROM new_design.task_contract_versions version JOIN new_design.task_contracts contract ON contract.id=version.contract_id WHERE version.id=$1 AND (contract.published_version_id=version.id OR EXISTS(SELECT 1 FROM new_design.ai_contract_publications publication WHERE publication.entity_kind='task_contract' AND publication.to_version_id=version.id))`,[input.taskContractVersionId])).rows[0],"任务合同版本从未发布。");assertFound((await client.query("SELECT id FROM new_design.books WHERE id=$1 AND status='active'",[input.bookId])).rows[0],"书籍不存在或已归档。");const layers:Record<string,unknown>[]=[];const system=await loadLayer(client,"config.scope='system_default'",[]);if(!system)throw new NewDesignError("尚未发布系统默认模型路由。",422);layers.push(system);const group=await loadLayer(client,"config.scope='task_group' AND config.task_group=$1",[task.task_group]);if(group)layers.push(group);const concreteTask=await loadLayer(client,"config.scope='task' AND config.task_key=$1 AND (config.task_group=$2 OR config.task_group IS NULL)",[task.task_key,task.task_group]);if(concreteTask)layers.push(concreteTask);if(input.nodeKey){const node=await loadLayer(client,"config.scope='node' AND config.node_key=$1 AND (config.task_group=$2 OR config.task_group IS NULL)",[input.nodeKey,task.task_group]);if(node)layers.push(node);}const book=await loadLayer(client,"config.scope='book' AND config.book_id=$1",[input.bookId]);if(book)layers.push(book);if(input.oneTimeOverrideKey){const once=await loadLayer(client,"config.scope='one_time' AND config.override_key=$1 AND (config.book_id=$2 OR config.book_id IS NULL)",[input.oneTimeOverrideKey,input.bookId]);if(once)layers.push(once);}
  let provider="",model="",parameters:Record<string,unknown>={},requiredCapabilities=[...(task.required_capabilities as string[])],credentialRefId:string|null=null,budgetPolicy={...(task.budget_policy as Record<string,unknown>)},timeoutMs=Number(task.timeout_ms),retryPolicy={...(task.retry_policy as Record<string,unknown>)},fallbacks:InternalFallback[]=[];const sourceLayers:ResolvedModelRoute["sourceLayers"]=[];
  for(const layer of layers){if(layer.provider)provider=String(layer.provider);if(layer.model)model=String(layer.model);if(layer.parameters)parameters={...parameters,...layer.parameters as Record<string,unknown>};if(layer.required_capabilities)requiredCapabilities=[...new Set([...requiredCapabilities,...layer.required_capabilities as string[]])];if(layer.credential_ref_id)credentialRefId=String(layer.credential_ref_id);if(layer.budget_policy)budgetPolicy={...budgetPolicy,...layer.budget_policy as Record<string,unknown>};if(layer.timeout_ms)timeoutMs=Number(layer.timeout_ms);if(layer.retry_policy)retryPolicy={...retryPolicy,...layer.retry_policy as Record<string,unknown>};const rows=(await client.query("SELECT * FROM new_design.model_route_fallbacks WHERE route_version_id=$1 ORDER BY sort_order,id",[layer.id])).rows.map((row)=>({...publicFallback(row),credentialRefId:asText(row.credential_ref_id)}));if(layer.fallback_mode==="replace")fallbacks=rows;else fallbacks=[...fallbacks,...rows];sourceLayers.push({scope:layer.scope as ModelRouteScope,configId:String(layer.source_config_id),versionId:String(layer.id)});}
  if(!provider||!model||!timeoutMs)throw new NewDesignError("解析后的模型路由不完整。",422);return{provider,model,parameters,requiredCapabilities,credentialRefId,hasCredential:Boolean(credentialRefId),budgetPolicy,timeoutMs,retryPolicy,fallbacks,sourceLayers,policyVersion:String(task.context_policy_version)};
}
function publicResolved(route:InternalResolved):ResolvedModelRoute{const{credentialRefId:_credential,...safe}=route;return{...safe,fallbacks:route.fallbacks.map(({credentialRefId:_fallbackCredential,...fallback})=>fallback)};}
export async function resolveModelRoute(input:{bookId:string;taskContractVersionId:string;nodeKey?:string|null;oneTimeOverrideKey?:string|null}):Promise<ResolvedModelRoute>{const pool=await getNewDesignPool(),client=await pool.connect();try{return publicResolved(await resolveInternal(client,input));}finally{client.release();}}

export async function createModelRouteSnapshot(input:{bookId:string;taskContractVersionId:string;nodeKey?:string|null;oneTimeOverrideKey?:string|null}):Promise<ModelRouteSnapshot>{const pool=await getNewDesignPool(),client=await pool.connect(),id=randomUUID();try{await client.query("BEGIN");const route=await resolveInternal(client,input),hash=stableHash(publicResolved(route));await client.query("INSERT INTO new_design.model_route_snapshots(id,book_id,task_contract_version_id,node_key,provider,model,parameters,required_capabilities,credential_ref_id,budget_policy,timeout_ms,retry_policy,source_layers,policy_version,snapshot_hash) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10::jsonb,$11,$12::jsonb,$13::jsonb,$14,$15)",[id,input.bookId,input.taskContractVersionId,input.nodeKey??null,route.provider,route.model,JSON.stringify(route.parameters),route.requiredCapabilities,route.credentialRefId,JSON.stringify(route.budgetPolicy),route.timeoutMs,JSON.stringify(route.retryPolicy),JSON.stringify(route.sourceLayers),route.policyVersion,hash]);for(const fallback of route.fallbacks)await client.query("INSERT INTO new_design.model_route_snapshot_fallbacks(id,snapshot_id,sort_order,provider,model,parameters,credential_ref_id,technical_failure_categories) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8)",[randomUUID(),id,fallback.sortOrder,fallback.provider,fallback.model,JSON.stringify(fallback.parameters),fallback.credentialRefId,fallback.technicalFailureCategories]);await client.query("COMMIT");return getModelRouteSnapshot(id);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
export async function getModelRouteSnapshot(id:string):Promise<ModelRouteSnapshot>{const pool=await getNewDesignPool(),row=assertFound((await pool.query("SELECT * FROM new_design.model_route_snapshots WHERE id=$1",[id])).rows[0],"模型路由快照不存在。"),fallbacks=(await pool.query("SELECT * FROM new_design.model_route_snapshot_fallbacks WHERE snapshot_id=$1 ORDER BY sort_order,id",[id])).rows.map(publicFallback);if(row.book_id===null||row.task_contract_version_id===null)throw new NewDesignError("此模型快照属于开书前任务，请在新设计模型设置查看其来源。",422);return{id:String(row.id),bookId:String(row.book_id),taskContractVersionId:String(row.task_contract_version_id),nodeKey:asText(row.node_key),provider:String(row.provider),model:String(row.model),parameters:row.parameters as Record<string,unknown>,requiredCapabilities:row.required_capabilities as string[],hasCredential:Boolean(row.credential_ref_id),budgetPolicy:row.budget_policy as Record<string,unknown>,timeoutMs:Number(row.timeout_ms),retryPolicy:row.retry_policy as Record<string,unknown>,fallbacks,sourceLayers:row.source_layers as ResolvedModelRoute["sourceLayers"],policyVersion:String(row.policy_version),snapshotHash:String(row.snapshot_hash),createdAt:asDate(row.created_at)};}
