import {readStoryFormat} from "../../../common/storyFormat";
import {AiExecutionError} from "../../ai/runtime/errors";
import { createHash, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import type { ForeshadowPlanAction, PlanningAdoption, PlanningExecutionMode, PlanningImpact, PlanningLevel, PlanningObject, PlanningReference, PlanningReferenceRole, PlanningTreeNode, PlanningVersion, PlanningVersionAction, PlanningVersionContext, PlanningVersionSource } from "../../../common/contracts";
import { NewDesignError, assertFound } from "../../domain/errors";
import { getNewDesignPool } from "../runtime";

type ReferenceInput={role:PlanningReferenceRole;cardId:string;cardVersionId:string;action?:ForeshadowPlanAction|null;note?:string;sortOrder:number};
type VersionInput={content:Record<string,unknown>;source:PlanningVersionSource;executionMode:PlanningExecutionMode;references:ReferenceInput[];baseVersionId?:string|null;basedOnParentVersionId?:string|null;sourceBodyVersionId?:string|null;createdBy?:string;idempotencyKey:string};
type CreateInput=VersionInput&{bookId:string;level:PlanningLevel;parentObjectId?:string|null;cardId?:string|null;title:string;sortOrder:number};
function planningWriteFailure(error:unknown,rolledBack:boolean,committing:boolean){const result=new AiExecutionError('保存规划候选',error instanceof NewDesignError?error.message:'原规划保存结果待核对，请保留填写与请求。',error instanceof NewDesignError?error.status:503,null,error instanceof NewDesignError?error.issues:undefined);result.recovery.mutationOutcome=rolledBack&&!committing?'not_written':'unknown';return result;}
const asDate=(value:unknown)=>value instanceof Date?value.toISOString():new Date(String(value)).toISOString();
const asText=(value:unknown)=>value===null||value===undefined?null:String(value);
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`;return JSON.stringify(value);}
const contentHash=(value:unknown)=>createHash("sha256").update(stable(value),"utf8").digest("hex");

function mapVersion(row:Record<string,unknown>):PlanningVersion{return{id:String(row.id),objectId:String(row.object_id),bookId:String(row.book_id),version:Number(row.version),baseVersionId:asText(row.base_version_id),basedOnParentVersionId:asText(row.based_on_parent_version_id),source:row.source as PlanningVersionSource,status:row.status as PlanningVersion["status"],executionMode:row.execution_mode as PlanningExecutionMode,content:row.content as Record<string,unknown>,contentHash:String(row.content_hash),sourceBodyVersionId:asText(row.source_body_version_id),references:[],createdBy:String(row.created_by),staleAt:row.stale_at?asDate(row.stale_at):null,staleReason:String(row.stale_reason),createdAt:asDate(row.created_at)};}
function mapReference(row:Record<string,unknown>):PlanningReference{return{id:String(row.id),planningVersionId:String(row.planning_version_id),role:row.reference_role as PlanningReferenceRole,cardId:String(row.card_id),cardVersionId:String(row.card_version_id),cardTypeKey:String(row.type_key),cardTypeName:String(row.type_name),title:String(row.title),action:asText(row.action_key) as ForeshadowPlanAction|null,note:String(row.note),sortOrder:Number(row.sort_order)};}
function mapAdoption(row:Record<string,unknown>):PlanningAdoption{return{id:String(row.id),objectId:String(row.object_id),bookId:String(row.book_id),fromVersionId:asText(row.from_version_id),toVersionId:String(row.to_version_id),action:row.action as PlanningAdoption["action"],objectRevision:Number(row.object_revision),source:row.source as PlanningAdoption["source"],actor:String(row.actor),contentHash:String(row.content_hash),idempotencyKey:String(row.idempotency_key),createdAt:asDate(row.created_at)};}
function mapAction(row:Record<string,unknown>):PlanningVersionAction{return{id:String(row.id),objectId:String(row.object_id),versionId:String(row.version_id),action:row.action as PlanningVersionAction["action"],actor:String(row.actor),note:String(row.note),createdAt:asDate(row.created_at)};}
function mapImpact(row:Record<string,unknown>):PlanningImpact{return{id:String(row.id),bookId:String(row.book_id),adoptionId:String(row.adoption_id),sourceObjectId:String(row.source_object_id),sourceFromVersionId:String(row.source_from_version_id),sourceToVersionId:String(row.source_to_version_id),targetKind:row.target_kind as PlanningImpact["targetKind"],targetId:String(row.target_id),status:row.status as PlanningImpact["status"],reason:String(row.reason),createdAt:asDate(row.created_at),resolvedAt:row.resolved_at?asDate(row.resolved_at):null};}

async function validateParentBasis(client:PoolClient,object:Record<string,unknown>,basisId:string|null|undefined,allowDraftParent=false):Promise<string|null>{
  if(object.level==="story"){if(basisId)throw new NewDesignError("故事总计划不能引用父级规划版本。",422);return null;}
  const parent=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 AND book_id=$2",[object.parent_object_id,object.book_id])).rows[0],"父级规划对象不存在。");
  const requiredParentVersion=allowDraftParent?parent.current_version_id:parent.adopted_version_id;
  if(!requiredParentVersion)throw new NewDesignError("请先明确保存父级规划版本，再创建子级规划。",409);
  if(!basisId)throw new NewDesignError("子级规划必须记录所依据的父级采用版本。",422);
  if(String(requiredParentVersion)!==basisId)throw new NewDesignError("父级依据版本发生变化，请刷新后重新生成或编辑子计划。",409);
  const version=assertFound((await client.query("SELECT stale_at FROM new_design.planning_versions WHERE id=$1 AND object_id=$2",[basisId,parent.id])).rows[0],"父级规划版本不存在。");
  if(version.stale_at)throw new NewDesignError("父级采用版本正在等待复核，不能作为新的规划依据。",409);
  return basisId;
}

async function validateBodySource(client:PoolClient,object:Record<string,unknown>,source:PlanningVersionSource,bodyVersionId:string|null|undefined):Promise<string|null>{
  if(source!=="body_revision"){if(bodyVersionId)throw new NewDesignError("只有正文反向修正规划时才能记录正文版本。",422);return null;}
  if(!bodyVersionId)throw new NewDesignError("正文反向修正规划必须记录当前采用正文版本。",422);
  if(object.level!=="chapter"&&object.level!=="scene")throw new NewDesignError("正文只能反向修正章节或场景计划。",422);
  const chapterObject=object.level==="chapter"?object:assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1",[object.parent_object_id])).rows[0],"场景所属章节计划不存在。");
  const row=await client.query("SELECT document.adopted_version_id FROM new_design.chapter_documents document JOIN new_design.chapter_body_versions version ON version.chapter_document_id=document.id WHERE document.book_id=$1 AND document.chapter_card_id=$2 AND version.id=$3",[object.book_id,chapterObject.card_id,bodyVersionId]);
  if(!row.rowCount||String(row.rows[0].adopted_version_id??"")!==bodyVersionId)throw new NewDesignError("只能依据当前采用的章节正文创建规划修正候选。",409);
  return bodyVersionId;
}

async function insertVersion(client:PoolClient,object:Record<string,unknown>,number:number,input:VersionInput,action:"create"|"edit",allowDraftParent=false):Promise<PlanningVersion>{
  if(input.content.storyFormat!==undefined&&(object.level!=='story'||!readStoryFormat(input.content.storyFormat)))throw new NewDesignError("\u4f5c\u54c1\u5f62\u5f0f\u53ea\u80fd\u4fdd\u5b58\u5728\u6545\u4e8b\u603b\u7eb2\uff0c\u8bf7\u6838\u5bf9\u957f\u77ed\u7bc7\u4e0e\u76ee\u6807\u5b57\u6570\u3002",422);
  if(input.content.storyFormatSourceId!==undefined){
   const source=(await client.query("SELECT source_payload->'storyFormat' format FROM new_design.book_content_sources WHERE id::text=$1 AND book_id=$2 AND confirmation_status='confirmed'",[String(input.content.storyFormatSourceId),object.book_id])).rows[0];
   if(object.level!=='story'||!source||JSON.stringify(readStoryFormat(source.format))!==JSON.stringify(readStoryFormat(input.content.storyFormat))||!readStoryFormat(input.content.storyFormat))throw new NewDesignError("\u5e26\u5165\u7684\u5f00\u4e66\u5f62\u5f0f\u4e0e\u539f\u786e\u8ba4\u6765\u6e90\u4e0d\u4e00\u81f4\uff1b\u4eba\u5de5\u4fee\u6539\u540e\u9700\u4f5c\u4e3a\u65b0\u5019\u9009\u6838\u5bf9\u3002",409);
  }
  const basis=await validateParentBasis(client,object,input.basedOnParentVersionId,allowDraftParent);
  const bodyVersion=await validateBodySource(client,object,input.source,input.sourceBodyVersionId);
  let base:string|null=input.baseVersionId??(object.current_version_id?String(object.current_version_id):null);
  if(base&&!((await client.query("SELECT 1 FROM new_design.planning_versions WHERE id=$1 AND object_id=$2",[base,object.id])).rowCount))throw new NewDesignError("基础规划版本不存在或属于其他规划对象。",422);
  const status=input.source==="ai"||base&&String((await client.query("SELECT status FROM new_design.planning_versions WHERE id=$1",[base])).rows[0]?.status)==="proposed"?"proposed":"draft";
  const duplicateRefs=new Set(input.references.map(item=>`${item.role}:${item.cardId}:${item.action??""}`));if(duplicateRefs.size!==input.references.length)throw new NewDesignError("同一用途不能重复选择相同资料。",422);
  const id=randomUUID(),hash=contentHash({content:input.content,executionMode:input.executionMode,references:input.references.map(item=>({role:item.role,cardId:item.cardId,cardVersionId:item.cardVersionId,action:item.action??null,note:item.note??"",sortOrder:item.sortOrder}))});
  const row=(await client.query("INSERT INTO new_design.planning_versions(id,object_id,book_id,version,base_version_id,based_on_parent_version_id,source,status,execution_mode,content,content_hash,source_body_version_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13) RETURNING *",[id,object.id,object.book_id,number,base,basis,input.source,status,input.executionMode,JSON.stringify(input.content),hash,bodyVersion,input.createdBy??""])).rows[0];
  for(const reference of input.references)await client.query("INSERT INTO new_design.planning_version_references(id,planning_version_id,planning_object_id,book_id,reference_role,card_id,card_version_id,action_key,note,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),id,object.id,object.book_id,reference.role,reference.cardId,reference.cardVersionId,reference.action??null,reference.note??"",reference.sortOrder]);
  if(base&&status==="proposed")await client.query("UPDATE new_design.planning_versions SET status='superseded' WHERE id=$1 AND status='proposed'",[base]);
  await client.query("UPDATE new_design.planning_objects SET current_version_id=$2,revision=CASE WHEN $3='edit' THEN revision+1 ELSE revision END,updated_at=now() WHERE id=$1",[object.id,id,action]);
  await client.query("INSERT INTO new_design.planning_version_actions(id,object_id,version_id,action,actor,note) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),object.id,id,action,input.createdBy??(input.source==="ai"?"ai":"user"),action==="create"?"建立规划初版。":"追加规划修订版本。"]) ;
  return mapVersion(row);
}

export async function getPlanningObject(id:string):Promise<PlanningObject>{
  const pool=await getNewDesignPool(),row=assertFound((await pool.query("SELECT * FROM new_design.planning_objects WHERE id=$1",[id])).rows[0],"规划对象不存在。");
  const [versions,adoptions,actions,references]=await Promise.all([pool.query("SELECT * FROM new_design.planning_versions WHERE object_id=$1 ORDER BY version DESC",[id]),pool.query("SELECT * FROM new_design.planning_adoptions WHERE object_id=$1 ORDER BY created_at DESC,id DESC",[id]),pool.query("SELECT * FROM new_design.planning_version_actions WHERE object_id=$1 ORDER BY created_at,id",[id]),pool.query(`SELECT reference.*,card.title,type.type_key,type.name type_name FROM new_design.planning_version_references reference JOIN new_design.cards card ON card.id=reference.card_id JOIN new_design.card_types type ON type.id=card.card_type_id WHERE reference.planning_object_id=$1 ORDER BY reference.planning_version_id,reference.reference_role,reference.sort_order,reference.id`,[id])]);
  const mappedReferences=references.rows.map(mapReference),mapped=versions.rows.map(item=>({...mapVersion(item),references:mappedReferences.filter(reference=>reference.planningVersionId===String(item.id))})),current=assertFound(mapped.find((item)=>item.id===String(row.current_version_id)),"规划当前版本不存在。"),adopted=row.adopted_version_id?assertFound(mapped.find((item)=>item.id===String(row.adopted_version_id)),"规划采用版本不存在。"):null;
  return{id:String(row.id),bookId:String(row.book_id),level:row.level as PlanningLevel,parentObjectId:asText(row.parent_object_id),cardId:asText(row.card_id),title:String(row.title),sortOrder:Number(row.sort_order),status:row.status as PlanningObject["status"],currentVersionId:current.id,adoptedVersionId:adopted?.id??null,revision:Number(row.revision),currentVersion:current,adoptedVersion:adopted,versions:mapped,adoptions:adoptions.rows.map(mapAdoption),actions:actions.rows.map(mapAction),createdAt:asDate(row.created_at),updatedAt:asDate(row.updated_at)};
}

export async function createPlanningObject(input:CreateInput):Promise<PlanningObject>{
  const pool=await getNewDesignPool(),requestHash=contentHash(input),prior=(await pool.query("SELECT object_id,request_hash FROM new_design.planning_operation_events WHERE book_id=$1 AND idempotency_key=$2",[input.bookId,input.idempotencyKey])).rows[0];if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的规划请求。",409);return getPlanningObject(String(prior.object_id));}const client=await pool.connect(),id=randomUUID();let committing=false;
  try{await client.query("BEGIN");assertFound((await client.query("SELECT id FROM new_design.books WHERE id=$1",[input.bookId])).rows[0],"书籍不存在。");
    const row=(await client.query("INSERT INTO new_design.planning_objects(id,book_id,level,parent_object_id,card_id,title,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[id,input.bookId,input.level,input.parentObjectId??null,input.cardId??null,input.title,input.sortOrder])).rows[0];
    const version=await insertVersion(client,row,1,input,"create");await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,'create',1,$5,$6,$7)",[randomUUID(),input.bookId,id,version.id,requestHash,input.idempotencyKey,input.createdBy??"user"]);committing=true;await client.query("COMMIT");return getPlanningObject(id);
  }catch(error){const rolledBack=await client.query("ROLLBACK").then(()=>true,()=>false);if((error as {code?:string}).code==="23505"){const repeated=(await pool.query("SELECT object_id,request_hash FROM new_design.planning_operation_events WHERE book_id=$1 AND idempotency_key=$2",[input.bookId,input.idempotencyKey])).rows[0];if(repeated&&String(repeated.request_hash)===requestHash)return getPlanningObject(String(repeated.object_id));throw planningWriteFailure(new NewDesignError("同层规划位置、故事总计划或绑定资料已存在。",409),rolledBack,committing);}if((error as {code?:string}).code==="23514")throw planningWriteFailure(new NewDesignError("规划层级或资料引用不符合当前书籍与内容类型。",422),rolledBack,committing);throw planningWriteFailure(error,rolledBack,committing);}finally{client.release();}
}

/** Initial installation uses the same version writer in its caller-owned transaction. */
export async function createPlanningObjectInTransaction(client:PoolClient,input:CreateInput,options:{allowDraftParent?:boolean}={}):Promise<{objectId:string;versionId:string}>{
 const id=randomUUID(),row=(await client.query("INSERT INTO new_design.planning_objects(id,book_id,level,parent_object_id,card_id,title,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[id,input.bookId,input.level,input.parentObjectId??null,input.cardId??null,input.title,input.sortOrder])).rows[0];
 const version=await insertVersion(client,row,1,input,"create",options.allowDraftParent??false);await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,'create',1,$5,$6,$7)",[randomUUID(),input.bookId,id,version.id,contentHash(input),input.idempotencyKey,input.createdBy??"user"]);
 return{objectId:id,versionId:version.id};
}
export async function adoptInitialPlanningVersionInTransaction(client:PoolClient,objectId:string,versionId:string,key:string,actor="user"):Promise<void>{
 const object=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 AND status='active' FOR UPDATE",[objectId])).rows[0],"规划对象不可用。"),version=assertFound((await client.query("SELECT * FROM new_design.planning_versions WHERE id=$1 AND object_id=$2",[versionId,objectId])).rows[0],"规划初版不可用。");
 if(object.adopted_version_id||Number(object.revision)!==1||version.stale_at||!["draft","proposed"].includes(String(version.status)))throw new NewDesignError("只能在安装事务中明确采用未采用的正式规划初版。",409);
 await validateParentBasis(client,object,version.based_on_parent_version_id);
 await client.query("UPDATE new_design.planning_versions SET status='adopted' WHERE id=$1",[versionId]);await client.query("UPDATE new_design.planning_objects SET adopted_version_id=$2,revision=2,updated_at=now() WHERE id=$1",[objectId,versionId]);
 await client.query("INSERT INTO new_design.planning_adoptions(id,object_id,book_id,from_version_id,to_version_id,action,object_revision,source,actor,content_hash,idempotency_key) VALUES($1,$2,$3,NULL,$4,'adopt',2,'user',$5,$6,$7)",[randomUUID(),objectId,object.book_id,versionId,actor,version.content_hash,key]);
}

export async function addPlanningVersion(objectId:string,input:VersionInput&{expectedRevision:number}):Promise<PlanningObject>{
  const pool=await getNewDesignPool(),requestHash=contentHash({objectId,...input}),prior=(await pool.query("SELECT object_id,request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的规划修订。",409);return getPlanningObject(objectId);}const client=await pool.connect();let committing=false;try{await client.query("BEGIN");const object=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 FOR UPDATE",[objectId])).rows[0],"规划对象不存在。"),repeated=(await client.query("SELECT request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(repeated){await client.query("ROLLBACK");if(String(repeated.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的规划修订。",409);return getPlanningObject(objectId);}if(object.status!=="active")throw new NewDesignError("归档的规划不能新增候选。",409);if(Number(object.revision)!==input.expectedRevision)planningConflict(object);const versionNumber=Number((await client.query("SELECT COALESCE(max(version),0)+1 AS version FROM new_design.planning_versions WHERE object_id=$1",[objectId])).rows[0].version),version=await insertVersion(client,object,versionNumber,input,"edit"),resultRevision=Number(object.revision)+1;await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,expected_revision,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,'revise',$5,$6,$7,$8,$9)",[randomUUID(),object.book_id,objectId,version.id,input.expectedRevision,resultRevision,requestHash,input.idempotencyKey,input.createdBy??"user"]);committing=true;await client.query("COMMIT");return getPlanningObject(objectId);}catch(error){const rolledBack=await client.query("ROLLBACK").then(()=>true,()=>false);if((error as {code?:string}).code==="23505")throw planningWriteFailure(new NewDesignError("幂等键已用于同一本书的其他规划请求。",409),rolledBack,committing);throw planningWriteFailure(error,rolledBack,committing);}finally{client.release();}
}

/** Same original writer and validations, with caller-owned transaction and original operation receipt. */
export async function addPlanningVersionInTransaction(client:PoolClient,objectId:string,input:VersionInput&{expectedRevision:number}):Promise<{objectId:string;versionId:string;revision:number}>{
 const requestHash=contentHash({objectId,...input}),object=assertFound((await client.query('SELECT * FROM new_design.planning_objects WHERE id=$1 FOR UPDATE',[objectId])).rows[0],'规划对象不存在。'),prior=(await client.query("SELECT event.request_hash,event.result_revision,version.id FROM new_design.planning_operation_events event JOIN new_design.planning_versions version ON version.id=event.version_id AND version.object_id=event.object_id WHERE event.book_id=$1 AND event.idempotency_key=$2",[object.book_id,input.idempotencyKey])).rows[0];
 if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError('原键已用于不同的规划修订。',409);return{objectId,versionId:String(prior.id),revision:Number(prior.result_revision)};}
 if(object.status!=='active')throw new NewDesignError('归档的规划不能新增候选。',409);if(Number(object.revision)!==input.expectedRevision)planningConflict(object);
 const versionNumber=Number((await client.query('SELECT COALESCE(max(version),0)+1 version FROM new_design.planning_versions WHERE object_id=$1',[objectId])).rows[0].version),version=await insertVersion(client,object,versionNumber,input,'edit'),revision=Number(object.revision)+1;
 await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,expected_revision,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,'revise',$5,$6,$7,$8,$9)",[randomUUID(),object.book_id,objectId,version.id,input.expectedRevision,revision,requestHash,input.idempotencyKey,input.createdBy??'user']);return{objectId,versionId:version.id,revision};
}

export async function rejectPlanningVersion(objectId:string,input:{versionId:string;expectedRevision:number;idempotencyKey:string;actor?:string;note?:string}):Promise<PlanningObject>{
  const pool=await getNewDesignPool(),requestHash=contentHash({objectId,...input}),prior=(await pool.query("SELECT request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的驳回请求。",409);return getPlanningObject(objectId);}const client=await pool.connect();try{await client.query("BEGIN");const object=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 FOR UPDATE",[objectId])).rows[0],"规划对象不存在。"),repeated=(await client.query("SELECT request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(repeated){await client.query("ROLLBACK");if(String(repeated.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的驳回请求。",409);return getPlanningObject(objectId);}if(object.status!=="active")throw new NewDesignError("归档的规划不能处理候选。",409);if(Number(object.revision)!==input.expectedRevision)planningConflict(object);const version=assertFound((await client.query("SELECT * FROM new_design.planning_versions WHERE id=$1 AND object_id=$2",[input.versionId,objectId])).rows[0],"规划版本不存在。");if(!["draft","proposed"].includes(String(version.status)))throw new NewDesignError("只有尚未采用的候选版本可以驳回。",409);const resultRevision=Number(object.revision)+1;await client.query("UPDATE new_design.planning_versions SET status='rejected' WHERE id=$1",[input.versionId]);await client.query("UPDATE new_design.planning_objects SET revision=$2,updated_at=now() WHERE id=$1",[objectId,resultRevision]);await client.query("INSERT INTO new_design.planning_version_actions(id,object_id,version_id,action,actor,note) VALUES($1,$2,$3,'reject',$4,$5)",[randomUUID(),objectId,input.versionId,input.actor??"user",input.note??""]);await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,expected_revision,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,'reject',$5,$6,$7,$8,$9)",[randomUUID(),object.book_id,objectId,input.versionId,input.expectedRevision,resultRevision,requestHash,input.idempotencyKey,input.actor??"user"]);await client.query("COMMIT");return getPlanningObject(objectId);}catch(error){await client.query("ROLLBACK");if((error as {code?:string}).code==="23505")throw new NewDesignError("幂等键已用于同一本书的其他规划请求。",409);throw error;}finally{client.release();}
}

function planningConflict(object:Record<string,unknown>):never{throw new NewDesignError("规划已被其他页面修改，本地填写内容已保留，请对照服务器版本后重试。",409,{serverRevision:String(object.revision),serverVersionId:String(object.current_version_id)});}

async function addImpact(client:PoolClient,args:{bookId:string;adoptionId:string;objectId:string;fromId:string;toId:string;kind:PlanningImpact["targetKind"];targetId:string;reason:string}){await client.query("INSERT INTO new_design.planning_impacts(id,book_id,adoption_id,source_object_id,source_from_version_id,source_to_version_id,target_kind,target_id,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(adoption_id,target_kind,target_id) DO NOTHING",[randomUUID(),args.bookId,args.adoptionId,args.objectId,args.fromId,args.toId,args.kind,args.targetId,args.reason]);}

async function invalidateDownstream(client:PoolClient,object:Record<string,unknown>,fromId:string,toId:string,adoptionId:string){
  const descendants=await client.query(`WITH RECURSIVE affected AS (
    SELECT child.id FROM new_design.planning_objects child JOIN new_design.planning_versions version ON version.object_id=child.id AND version.id IN (child.current_version_id,child.adopted_version_id) WHERE child.parent_object_id=$1 AND version.based_on_parent_version_id=$2
    UNION SELECT child.id FROM new_design.planning_objects child JOIN affected parent ON child.parent_object_id=parent.id
  ) SELECT DISTINCT version.id,version.object_id FROM affected JOIN new_design.planning_objects object ON object.id=affected.id JOIN new_design.planning_versions version ON version.object_id=object.id AND version.id IN (object.current_version_id,object.adopted_version_id)`,[object.id,fromId]);
  for(const row of descendants.rows){const updated=await client.query("UPDATE new_design.planning_versions SET stale_at=COALESCE(stale_at,now()),stale_reason=$2 WHERE id=$1 AND stale_at IS NULL RETURNING id",[row.id,"上游采用了其他规划版本，需要重新核对。"]);if(updated.rowCount)await client.query("INSERT INTO new_design.planning_version_actions(id,object_id,version_id,action,actor,note) VALUES($1,$2,$3,'mark_stale','system',$4)",[randomUUID(),row.object_id,row.id,"上游采用了其他规划版本，需要重新核对。"]);await addImpact(client,{bookId:String(object.book_id),adoptionId,objectId:String(object.id),fromId,toId,kind:"plan_version",targetId:String(row.id),reason:"该子计划基于被替代的上游版本。"});}
  const invalidSourceIds=[fromId,...new Set(descendants.rows.map((row)=>String(row.id)))];
  const timings=await client.query("UPDATE new_design.story_event_timings SET status='stale' WHERE plan_version_id=ANY($1::uuid[]) AND status='active' RETURNING id,proposal_id,proposal_version_id",[invalidSourceIds]);for(const row of timings.rows){if(row.proposal_id){await client.query("UPDATE new_design.story_time_proposals SET status='stale',revision=revision+1,updated_at=now() WHERE id=$1",[row.proposal_id]);await client.query("INSERT INTO new_design.story_time_review_actions(id,proposal_id,proposal_version_id,action,actor,note) VALUES($1,$2,$3,'mark_stale','system',$4)",[randomUUID(),row.proposal_id,row.proposal_version_id,"来源计划采用了其他版本，故事时间等待复核。"]);}await addImpact(client,{bookId:String(object.book_id),adoptionId,objectId:String(object.id),fromId,toId,kind:"story_time",targetId:String(row.id),reason:"故事时间引用了被替代的计划版本。"});}
  await client.query("UPDATE new_design.story_time_proposals proposal SET status='stale',revision=revision+1,updated_at=now() FROM new_design.story_time_proposal_versions version WHERE proposal.current_version_id=version.id AND version.plan_version_id=ANY($1::uuid[]) AND proposal.status='proposed'",[invalidSourceIds]);
  const relations=await client.query("UPDATE new_design.story_event_relations relation SET status='stale' FROM new_design.story_relation_proposal_versions version WHERE relation.proposal_version_id=version.id AND version.plan_version_id=ANY($1::uuid[]) AND relation.status='active' RETURNING relation.id,relation.proposal_id,relation.proposal_version_id",[invalidSourceIds]);for(const row of relations.rows){await client.query("UPDATE new_design.story_relation_proposals SET status='stale',revision=revision+1,updated_at=now() WHERE id=$1",[row.proposal_id]);await client.query("INSERT INTO new_design.story_relation_review_actions(id,proposal_id,proposal_version_id,action,actor,note) VALUES($1,$2,$3,'mark_stale','system',$4)",[randomUUID(),row.proposal_id,row.proposal_version_id,"来源计划采用了其他版本，事件关系等待复核。"]);await addImpact(client,{bookId:String(object.book_id),adoptionId,objectId:String(object.id),fromId,toId,kind:"story_relation",targetId:String(row.id),reason:"事件关系引用了被替代的计划版本。"});}
  await client.query("UPDATE new_design.story_relation_proposals proposal SET status='stale',revision=revision+1,updated_at=now() FROM new_design.story_relation_proposal_versions version WHERE proposal.current_version_id=version.id AND version.plan_version_id=ANY($1::uuid[]) AND proposal.status='proposed'",[invalidSourceIds]);
  if(object.level==="chapter"||object.level==="scene"){const chapterCardId=object.level==="chapter"?object.card_id:(await client.query("SELECT card_id FROM new_design.planning_objects WHERE id=$1",[object.parent_object_id])).rows[0]?.card_id;const bodies=await client.query("SELECT adopted_version_id FROM new_design.chapter_documents WHERE book_id=$1 AND chapter_card_id=$2 AND adopted_version_id IS NOT NULL",[object.book_id,chapterCardId]);for(const row of bodies.rows)await addImpact(client,{bookId:String(object.book_id),adoptionId,objectId:String(object.id),fromId,toId,kind:"chapter_body",targetId:String(row.adopted_version_id),reason:"规划切版不会覆盖正文，该正文需要人工判断是否受影响。"});}
}

export async function adoptPlanningVersion(objectId:string,input:{versionId:string;expectedRevision:number;idempotencyKey:string;source?:"user"|"system"|"import";actor?:string}):Promise<PlanningObject>{
  const pool=await getNewDesignPool(),repeated=await pool.query("SELECT object_id FROM new_design.planning_adoptions WHERE idempotency_key=$1",[input.idempotencyKey]);if(repeated.rows[0]){if(String(repeated.rows[0].object_id)!==objectId)throw new NewDesignError("幂等键已用于其他规划对象。",409);return getPlanningObject(objectId);}const client=await pool.connect();
  try{await client.query("BEGIN");const object=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 FOR UPDATE",[objectId])).rows[0],"规划对象不存在。"),insideRepeat=(await client.query("SELECT object_id FROM new_design.planning_adoptions WHERE idempotency_key=$1",[input.idempotencyKey])).rows[0];if(insideRepeat){await client.query("ROLLBACK");if(String(insideRepeat.object_id)!==objectId)throw new NewDesignError("幂等键已用于其他规划对象。",409);return getPlanningObject(objectId);}if(object.status!=="active")throw new NewDesignError("归档的规划不能采用候选。",409);if(Number(object.revision)!==input.expectedRevision)planningConflict(object);const target=assertFound((await client.query("SELECT * FROM new_design.planning_versions WHERE id=$1 AND object_id=$2",[input.versionId,objectId])).rows[0],"待采用规划版本不存在。");if(target.status==="rejected"||target.stale_at)throw new NewDesignError("已驳回或待复核的规划版本不能直接采用。",409);await validateParentBasis(client,object,asText(target.based_on_parent_version_id));const fromId=asText(object.adopted_version_id),adoptionId=randomUUID(),nextRevision=Number(object.revision)+1;let action:PlanningAdoption["action"]="adopt";if(fromId===input.versionId)action="readopt";else if(fromId){const from=assertFound((await client.query("SELECT version FROM new_design.planning_versions WHERE id=$1",[fromId])).rows[0],"原采用版本不存在。");if(Number(target.version)<Number(from.version))action="rollback";await client.query("UPDATE new_design.planning_versions SET status='superseded' WHERE id=$1",[fromId]);}await client.query("UPDATE new_design.planning_versions SET status='adopted',stale_at=NULL,stale_reason='' WHERE id=$1",[input.versionId]);await client.query("UPDATE new_design.planning_objects SET adopted_version_id=$2,revision=$3,updated_at=now() WHERE id=$1",[objectId,input.versionId,nextRevision]);await client.query("INSERT INTO new_design.planning_adoptions(id,object_id,book_id,from_version_id,to_version_id,action,object_revision,source,actor,content_hash,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[adoptionId,objectId,object.book_id,fromId,input.versionId,action,nextRevision,input.source??"user",input.actor??"user",target.content_hash,input.idempotencyKey]);if(fromId&&fromId!==input.versionId)await invalidateDownstream(client,object,fromId,input.versionId,adoptionId);await client.query("COMMIT");return getPlanningObject(objectId);}catch(error){await client.query("ROLLBACK");if((error as {code?:string}).code==="23505"){const row=await pool.query("SELECT object_id FROM new_design.planning_adoptions WHERE idempotency_key=$1",[input.idempotencyKey]);if(String(row.rows[0]?.object_id)===objectId)return getPlanningObject(objectId);}throw error;}finally{client.release();}
}

export async function setPlanningObjectArchived(objectId:string,input:{expectedRevision:number;idempotencyKey:string;archived:boolean;actor?:string;note?:string}):Promise<PlanningObject>{
  const action=input.archived?"archive":"restore",pool=await getNewDesignPool(),requestHash=contentHash({objectId,...input,action}),prior=(await pool.query("SELECT request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(prior){if(String(prior.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的规划归档请求。",409);return getPlanningObject(objectId);}const client=await pool.connect();try{await client.query("BEGIN");const object=assertFound((await client.query("SELECT * FROM new_design.planning_objects WHERE id=$1 FOR UPDATE",[objectId])).rows[0],"规划对象不存在。"),repeated=(await client.query("SELECT request_hash FROM new_design.planning_operation_events WHERE object_id=$1 AND idempotency_key=$2",[objectId,input.idempotencyKey])).rows[0];if(repeated){await client.query("ROLLBACK");if(String(repeated.request_hash)!==requestHash)throw new NewDesignError("幂等键已用于不同的规划归档请求。",409);return getPlanningObject(objectId);}if(Number(object.revision)!==input.expectedRevision)planningConflict(object);const targetStatus=input.archived?"archived":"active";if(object.status===targetStatus)throw new NewDesignError(input.archived?"规划已归档。":"规划已恢复。",409);if(input.archived&&(await client.query("SELECT 1 FROM new_design.planning_objects WHERE parent_object_id=$1 AND status='active' LIMIT 1",[objectId])).rowCount)throw new NewDesignError("请先归档下级规划，再归档当前规划。",409);if(!input.archived&&object.parent_object_id){const parent=assertFound((await client.query("SELECT status FROM new_design.planning_objects WHERE id=$1",[object.parent_object_id])).rows[0],"上级规划不存在。");if(parent.status!=="active")throw new NewDesignError("请先恢复上级规划。",409);}const resultRevision=Number(object.revision)+1;await client.query("UPDATE new_design.planning_objects SET status=$2,revision=$3,updated_at=now() WHERE id=$1",[objectId,targetStatus,resultRevision]);await client.query("INSERT INTO new_design.planning_version_actions(id,object_id,version_id,action,actor,note) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),objectId,object.current_version_id,action,input.actor??"user",input.note??""]);await client.query("INSERT INTO new_design.planning_operation_events(id,book_id,object_id,version_id,action,expected_revision,result_revision,request_hash,idempotency_key,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),object.book_id,objectId,object.current_version_id,action,input.expectedRevision,resultRevision,requestHash,input.idempotencyKey,input.actor??"user"]);await client.query("COMMIT");return getPlanningObject(objectId);}catch(error){await client.query("ROLLBACK");if((error as {code?:string}).code==="23505")throw new NewDesignError("幂等键已用于同一本书的其他规划请求。",409);throw error;}finally{client.release();}
}

export async function getAdoptedPlanningTree(bookId:string):Promise<PlanningTreeNode|null>{const pool=await getNewDesignPool(),rows=await pool.query("SELECT id,parent_object_id FROM new_design.planning_objects WHERE book_id=$1 AND status='active' AND adopted_version_id IS NOT NULL ORDER BY sort_order,id",[bookId]);if(!rows.rowCount)return null;const objects=await Promise.all(rows.rows.map((row)=>getPlanningObject(String(row.id)))),nodes=new Map(objects.map((object)=>[object.id,{object,children:[]} as PlanningTreeNode]));let root:PlanningTreeNode|null=null;for(const node of nodes.values()){if(!node.object.parentObjectId)root=node;else nodes.get(node.object.parentObjectId)?.children.push(node);}return root;}
export async function getPlanningVersionContext(versionId:string):Promise<PlanningVersionContext>{const pool=await getNewDesignPool(),versionRow=assertFound((await pool.query("SELECT * FROM new_design.planning_versions WHERE id=$1",[versionId])).rows[0],"规划版本不存在。"),object=await getPlanningObject(String(versionRow.object_id)),version=assertFound(object.versions.find(item=>item.id===versionId),"规划版本不存在。"),ancestors:PlanningVersionContext["ancestors"]=[];let basis=version.basedOnParentVersionId;while(basis){const ancestorRow=assertFound((await pool.query("SELECT object_id FROM new_design.planning_versions WHERE id=$1",[basis])).rows[0],"祖先规划版本不存在。"),ancestorObject=await getPlanningObject(String(ancestorRow.object_id)),ancestorVersion=assertFound(ancestorObject.versions.find(item=>item.id===basis),"祖先规划版本不存在。");ancestors.unshift({object:ancestorObject,version:ancestorVersion});basis=ancestorVersion.basedOnParentVersionId;}const childRows=await pool.query("SELECT id,object_id FROM new_design.planning_versions WHERE based_on_parent_version_id=$1 ORDER BY created_at,id",[versionId]),children=[];for(const row of childRows.rows){const childObject=await getPlanningObject(String(row.object_id)),childVersion=assertFound(childObject.versions.find(item=>item.id===String(row.id)),"子规划版本不存在。");children.push({object:childObject,version:childVersion});}return{version,object,ancestors,children};}
export async function listStalePlanningVersions(bookId:string):Promise<PlanningVersion[]>{const pool=await getNewDesignPool(),rows=(await pool.query("SELECT id,object_id FROM new_design.planning_versions WHERE book_id=$1 AND stale_at IS NOT NULL ORDER BY stale_at DESC,id",[bookId])).rows,result:PlanningVersion[]=[];for(const row of rows){const object=await getPlanningObject(String(row.object_id)),version=object.versions.find(item=>item.id===String(row.id));if(version)result.push(version);}return result;}
export async function listPlanningAdoptions(objectId:string):Promise<PlanningAdoption[]>{return(await(await getNewDesignPool()).query("SELECT * FROM new_design.planning_adoptions WHERE object_id=$1 ORDER BY created_at DESC,id DESC",[objectId])).rows.map(mapAdoption);}
export async function listPlanningImpacts(bookId:string,status?:PlanningImpact["status"]):Promise<PlanningImpact[]>{return(await(await getNewDesignPool()).query("SELECT * FROM new_design.planning_impacts WHERE book_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY created_at DESC,id DESC",[bookId,status??null])).rows.map(mapImpact);}
