import {useEffect,useState} from 'react';
import {COMIC_FORMATS,COMIC_STYLES,type ComicCreateInput,type ComicCreateReceipt,type ComicProjectDetail,type ComicProjectSummary,type ComicCapability} from '../../common/comicProjects';
import type {ShelfBook} from '../../common/bookshelf';
import {newDesignApi} from '../api';
import ComicEpisodePlanner from './ComicEpisodePlanner';
import ComicBibleEditor from './ComicBibleEditor';
import './comicProjects.css';

const STEPS=['来源','内容','形态','画风'] as const;
const pendingKey='new-design:comic-create-pending';
type Draft=Pick<ComicCreateInput,'title'|'sourceType'|'comicFormat'|'stylePreset'>&{sourceBookId:string;sourceText:string};
const initial:Draft={title:'',sourceType:'original',sourceBookId:'',sourceText:'',comicFormat:'webtoon',stylePreset:'webtoon_color'};
const sourceLabels={novel_import:'导入小说',original:'原创灵感',text_import:'文本导入'};
const label=(items:readonly {key:string;label:string}[],key:string)=>items.find(item=>item.key===key)?.label??key;

export default function ComicProjectsPage({projectId}:{projectId?:string}){
 const [capability,setCapability]=useState<ComicCapability|null>(null),[items,setItems]=useState<ComicProjectSummary[]>([]),[books,setBooks]=useState<ShelfBook[]>([]),[detail,setDetail]=useState<ComicProjectDetail|null>(null);
 const [draft,setDraft]=useState<Draft>(initial),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(()=>typeof sessionStorage==='undefined'?null:sessionStorage.getItem(pendingKey));
 const [receipt,setReceipt]=useState<ComicCreateReceipt|null>(null);
 useEffect(()=>{let live=true;void newDesignApi.comicProjects.capability().then(value=>{if(!live)return;setCapability(value);if(value.installed){void newDesignApi.comicProjects.list().then(rows=>{if(live)setItems(rows);}).catch(reason=>{if(live)setError(String(reason));});}}).catch(reason=>{if(live)setError(String(reason));});void newDesignApi.getBookshelf().then(value=>{if(live)setBooks(value.books);}).catch(()=>undefined);return()=>{live=false;};},[]);
 useEffect(()=>{if(!projectId||!capability?.installed)return;let live=true;void newDesignApi.comicProjects.detail(projectId).then(value=>{if(live)setDetail(value);}).catch(reason=>{if(live)setError(String(reason));});return()=>{live=false;};},[projectId,capability?.installed]);
 const set=(patch:Partial<Draft>)=>{setDraft(value=>({...value,...patch}));setError('');setNotice('');};
 const canContinue=step===0?Boolean(draft.title.trim()):step===1?draft.sourceType==='novel_import'?Boolean(draft.sourceBookId):Boolean(draft.sourceText.trim()):true;
 async function checkOriginal(){if(!pending)return;setBusy(true);setError('');try{const original=await newDesignApi.comicProjects.original(pending);if(original){setReceipt(original);setNotice('已按原请求找回漫画项目，没有重新创建。');sessionStorage.removeItem(pendingKey);setPending(null);setItems(await newDesignApi.comicProjects.list());}else setNotice('原请求暂未找到记录。可在服务稳定后使用同一请求键重试当前表单；不要另建请求。');}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 async function create(){if(!canContinue||busy||!capability?.operational)return;const key=pending??crypto.randomUUID();if(!pending){try{sessionStorage.setItem(pendingKey,key);setPending(key);}catch{setError('浏览器无法保留原请求凭证，尚未发送创建请求。');return;}}const input:ComicCreateInput={requestKey:key,title:draft.title.trim(),sourceType:draft.sourceType,comicFormat:draft.comicFormat,stylePreset:draft.stylePreset,...(draft.sourceType==='novel_import'?{sourceBookId:draft.sourceBookId}:{sourceText:draft.sourceText.trim()})};setBusy(true);setError('');setNotice('');try{const result=await newDesignApi.comicProjects.create(input);setReceipt(result);setNotice(result.repeated?'已找回原创建结果。':'漫画项目已创建，来源内容已冻结。');sessionStorage.removeItem(pendingKey);setPending(null);setItems(await newDesignApi.comicProjects.list());}catch(reason){setError(`${String(reason)} 请先核对原创建请求；同一表单可沿用原键，不要新建请求。`);}finally{setBusy(false);}}
 async function importText(file:File){if(file.size>2_000_000){setError('来源文件超过 2 MB，请选择较小的文本文件。');return;}try{set({sourceText:await file.text()});}catch{setError('无法读取本地文本文件。');}}
 return <section className="nd-shell nd-comic-workspace"><header className="nd-comic-header"><div><p className="nd-kicker">独立创作系统 · Beta</p><h1>漫画工作台</h1><p>来源与分镜独立保存；小说正文只在明确导入时取已采用版本。</p></div><a className="nd-button nd-button-secondary" href="/new-design/comic">项目列表</a></header>
 {error&&<p role="alert" className="nd-comic-error">{error}</p>}{notice&&<p role="status" className="nd-comic-notice">{notice}</p>}
 {capability&&!capability.operational&&<section className="nd-comic-gate" role="status"><h2>漫画数据层尚未启用</h2><p>{capability.reason}</p><p>手动迁移 109 应在备份和独立恢复验证后启用；当前不会向作者数据库自动写入。</p></section>}
 {projectId?<>{capability?.installed&&detail&&<><article className="nd-comic-detail"><h2>{detail.project.title}</h2><div className="nd-comic-meta"><span>{sourceLabels[detail.project.sourceType]}</span><span>{label(COMIC_FORMATS,detail.project.comicFormat)}</span><span>{label(COMIC_STYLES,detail.project.stylePreset)}</span><span>草稿</span></div><h3>已采用的来源快照</h3><p>冻结于 {new Date(detail.source.createdAt).toLocaleString()}；{detail.source.sourceBookName?`来自《${detail.source.sourceBookName}》`:'独立文本来源'}；后续原作修改不会覆盖此版本。</p>{detail.source.manifest.chapters.length>0&&<p>已采用章节：{detail.source.manifest.chapters.map(chapter=>chapter.title).join('、')}</p>}<pre>{detail.source.content.slice(0,3000)}{detail.source.content.length>3000?'\n…来源较长，可按章节版本追溯。':''}</pre></article><ComicEpisodePlanner projectId={projectId}/><ComicBibleEditor projectId={projectId}/></>}{capability?.installed&&!detail&&!error&&<p>正在读取漫画项目…</p>}</>:<div className="nd-comic-grid"><section className="nd-comic-list"><h2>我的漫画项目</h2>{items.length?items.map(item=><a key={item.id} href={`/new-design/comic/projects/${item.id}`}><strong>{item.title}</strong><small>{sourceLabels[item.sourceType]} · {label(COMIC_FORMATS,item.comicFormat)} · {label(COMIC_STYLES,item.stylePreset)}</small></a>):<p>{capability?.installed?'还没有漫画项目。':'启用后可创建独立漫画项目。'}</p>}</section><section className="nd-comic-create"><h2>新建漫画项目</h2><nav aria-label="创建步骤">{STEPS.map((name,index)=><button key={name} type="button" disabled={busy||index>step} aria-current={step===index?'step':undefined} onClick={()=>setStep(index)}>{index+1}. {name}</button>)}</nav>
 {step===0&&<div className="nd-comic-fields"><label>项目名称<input maxLength={120} value={draft.title} disabled={busy} onChange={event=>set({title:event.target.value})} placeholder="例如：雨夜侦探·漫画版"/></label><fieldset><legend>来源类型</legend>{(['novel_import','original','text_import'] as const).map(type=><label key={type}><input type="radio" name="comic-source" checked={draft.sourceType===type} disabled={busy} onChange={()=>set({sourceType:type,sourceBookId:'',sourceText:''})}/>{sourceLabels[type]}</label>)}</fieldset></div>}
 {step===1&&<div className="nd-comic-fields">{draft.sourceType==='novel_import'?<><label>来源小说<select value={draft.sourceBookId} disabled={busy} onChange={event=>set({sourceBookId:event.target.value})}><option value="">请选择已采用正文的小说</option>{books.map(book=><option key={book.id} value={book.id}>{book.name}（已采用正文约 {book.wordCount} 字）</option>)}</select></label><p>创建时冻结当前已采用章节；没有已采用正文的小说不能导入。</p></>:<><label>{draft.sourceType==='original'?'原创灵感':'来源文本'}<textarea rows={9} maxLength={2_000_000} value={draft.sourceText} disabled={busy} onChange={event=>set({sourceText:event.target.value})} placeholder={draft.sourceType==='original'?'写下故事核心、人物和冲突…':'粘贴原始文本，或选择本地 TXT / Markdown 文件…'}/></label>{draft.sourceType==='text_import'&&<label>选择本地文本文件<input type="file" accept=".txt,.md,text/plain,text/markdown" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void importText(file);}}/></label>}</>}</div>}
 {step===2&&<fieldset className="nd-comic-options"><legend>选择漫画形态</legend>{COMIC_FORMATS.map(item=><label key={item.key}><input type="radio" name="comic-format" value={item.key} checked={draft.comicFormat===item.key} disabled={busy} onChange={()=>set({comicFormat:item.key})}/>{item.label}</label>)}</fieldset>}
 {step===3&&<fieldset className="nd-comic-options"><legend>选择画风</legend>{COMIC_STYLES.map(item=><label key={item.key}><input type="radio" name="comic-style" value={item.key} checked={draft.stylePreset===item.key} disabled={busy} onChange={()=>set({stylePreset:item.key})}/>{item.label}</label>)}</fieldset>}
 <footer><button type="button" className="nd-button nd-button-secondary" disabled={busy||step===0} onClick={()=>setStep(value=>value-1)}>上一步</button>{step<3?<button type="button" className="nd-button nd-button-primary" disabled={busy||!canContinue} onClick={()=>setStep(value=>value+1)}>下一步</button>:<button type="button" className="nd-button nd-button-primary" disabled={busy||!capability?.operational||!canContinue} onClick={()=>void create()}>{busy?'正在创建…':pending?'沿原请求继续创建':'创建漫画项目'}</button>}</footer>{pending&&<aside className="nd-comic-pending" role="status"><p>有待核对的创建请求。原请求键已留在本次浏览器会话；不会自动产生第二次创建。</p><button type="button" className="nd-button" disabled={busy||!capability?.installed} onClick={()=>void checkOriginal()}>只读核对原创建结果</button></aside>}{receipt&&<p role="status"><a href={`/new-design/comic/projects/${receipt.project.id}`}>打开《{receipt.project.title}》</a></p>}</section></div>}
 </section>;
}
