import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {characterAuthorInputSchema,characterAuthorResultSchema,characterAuthorSourceSchema,characterAuthorWorkspaceSchema,type CharacterAuthorInput,type CharacterAuthorResult,type CharacterAuthorWorkspace} from '../../common/characterAuthor';
import {newDesignApi} from '../api';
import {imageInputHash} from '../imageGeneration/recovery';
import type {WorkspaceEditor} from '../storyWorkspace/useGuard';
import './conversation.css';
const frameSchema=z.object({bookId:z.string().uuid(),cardId:z.string().uuid(),cutoffBodyVersionId:z.string().uuid().nullable(),message:z.string().max(8000),source:characterAuthorSourceSchema.nullable(),pending:characterAuthorInputSchema.nullable(),result:characterAuthorResultSchema.nullable(),notWritten:z.boolean(),checkedAbsent:z.boolean()}).strict();
type Frame=z.infer<typeof frameSchema>;
const ANALYSIS_LABELS={situation:'谈话局面',concerns:'关注点',misreadings:'可能误读',pressureReactions:'受压反应',emotions:'情绪与立场',decisionTriggers:'决定触发',beliefs:'相信的内容',inferenceBasis:'推断依据',uncertainties:'不确定点'};
export default function CharacterAuthorPanel({bookId,cardId,title,onState}:{bookId:string;cardId:string;title:string;onState?:(state:WorkspaceEditor)=>void}){
 const panel=useRef<HTMLElement|null>(null),[wide,setWide]=useState(false),[analysisSection,setAnalysisSection]=useState<keyof typeof ANALYSIS_LABELS>('situation');
 useEffect(()=>{const update=()=>setWide(document.fullscreenElement===panel.current);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
 const api=newDesignApi.characterAuthor,key=`new-design:character-author:v1:${bookId}:${cardId}`;
 const empty:Frame={bookId,cardId,cutoffBodyVersionId:null,message:'',source:null,pending:null,result:null,notWritten:false,checkedAbsent:false};
 const initial=()=>{let raw:string|null=null;try{raw=localStorage.getItem(key);if(raw&&raw.length>4000000)throw Error();const frame=raw?frameSchema.parse(JSON.parse(raw)):empty;if(frame.bookId!==bookId||frame.cardId!==cardId||frame.pending&&(frame.pending.bookId!==bookId||frame.pending.cardId!==cardId)||frame.source&&(frame.source.bookId!==bookId||frame.source.cardId!==cardId)||frame.result&&(frame.result.input.bookId!==bookId||frame.result.input.cardId!==cardId))throw Error();return{raw,frame,blocked:false};}catch{return{raw,frame:empty,blocked:true};}};
 const [start]=useState(initial),[frame,setFrame]=useState(start.frame),live=useRef(frame),saved=useRef(start.raw),[blocked,setBlocked]=useState(start.blocked),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[workspace,setWorkspace]=useState<CharacterAuthorWorkspace|null>(null),mounted=useRef(false),flight=useRef(false),callback=useRef(onState);
 callback.current=onState;
 const persist=(next:Frame)=>{try{const value=frameSchema.parse(next),raw=JSON.stringify(value);if(raw.length>4000000||localStorage.getItem(key)!==saved.current)throw Error();localStorage.setItem(key,raw);if(localStorage.getItem(key)!==raw)throw Error();saved.current=raw;live.current=value;setFrame(value);return true;}catch{live.current=next;setFrame(next);setBlocked(true);setMessage('本地原请求或填写未能可靠保存，保留旧记录并停止新提交。');return false;}};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{callback.current?.({dirty:Boolean(frame.message),locked:blocked||busy||Boolean(frame.pending),discard:()=>{if(blocked||flight.current||live.current.pending)return false;return persist({...live.current,message:''});}});},[frame.message,frame.pending,blocked,busy]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(live.current.message||live.current.pending||blocked){event.preventDefault();event.returnValue='';}},storage=(event:StorageEvent)=>{if(event.key===key&&event.newValue!==saved.current){setBlocked(true);setMessage('另一页面已更新此人物原记录，保留本页填写并停止写入，请先核对原结果。');}};window.addEventListener('beforeunload',leave);window.addEventListener('storage',storage);return()=>{window.removeEventListener('beforeunload',leave);window.removeEventListener('storage',storage);};},[blocked,key]);
 async function exclusive(work:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);try{if(!navigator.locks)throw Error('浏览器无法独占原请求，停止写入；可保留填写。');await navigator.locks.request(key,{ifAvailable:true},async lock=>{if(!lock)throw Error('另一页面正在核对此人物原请求。');if(localStorage.getItem(key)!==saved.current){setBlocked(true);throw Error('本地原记录已变化，保留本页输入并停止写入。');}await work();});}catch(error){if(mounted.current)setMessage(error instanceof Error?error.message:'原人物谈话结果尚未确认。');}finally{flight.current=false;if(mounted.current)setBusy(false);}}
 const sourceMatches=async(source:NonNullable<Frame['source']>)=>source.bookId===bookId&&source.cardId===cardId&&source.hash===await imageInputHash({bookId,cardId,cutoffBodyVersionId:source.cutoffBodyVersionId,data:source.data});
 async function read(cutoff=live.current.cutoffBodyVersionId,saveSource=true){const next=characterAuthorWorkspaceSchema.parse(await api.workspace(bookId,cardId,cutoff));if(next.bookId!==bookId||next.cardId!==cardId||next.results.some(item=>item.input.bookId!==bookId||item.input.cardId!==cardId)||next.source&&(!await sourceMatches(next.source)||next.source.cutoffBodyVersionId!==cutoff))throw Error('人物或截至正文来源不一致，保留当前消息。');if(!mounted.current)return;setWorkspace(next);if(saveSource&&!blocked&&!live.current.pending)persist({...live.current,cutoffBodyVersionId:cutoff,source:next.source});}
 useEffect(()=>{void exclusive(()=>read());},[]);
 async function accept(input:CharacterAuthorInput,raw:unknown){const result=characterAuthorResultSchema.parse(raw),old=live.current;if(result.input.bookId!==bookId||result.input.cardId!==cardId||await imageInputHash(input)!==await imageInputHash(result.input)||!await sourceMatches(result.source)||result.source.hash!==input.sourceHash||old.source&&await imageInputHash(old.source)!==await imageInputHash(result.source)||['succeeded','stale'].includes(result.status)&&(!result.output||result.output.bookId!==bookId||result.output.cardId!==cardId||result.output.sourceHash!==input.sourceHash||result.output.sourceVersionIds.some(id=>!result.source.versionIds.includes(id)))||result.status!=='running'&&(result.canCompleteSaved||result.canEndExpired)||result.canCompleteSaved&&result.canEndExpired)throw Error('原人物回执与消息及来源不一致，保留原请求。');if(!mounted.current)return;if(!persist({...old,result,pending:result.status==='running'?input:null,message:result.status==='succeeded'?'':old.message}))return;setMessage(result.summary);if(result.status!=='running')await read(old.cutoffBodyVersionId,false);}
 const send=(kind:CharacterAuthorInput['kind'])=>exclusive(async()=>{const old=live.current;if(blocked||old.pending||!old.source||!workspace?.capability.operational||workspace.resultsTruncated)return;const rounds=workspace.results.filter(item=>item.status==='succeeded'&&item.source.hash===old.source!.hash).reverse();const input=characterAuthorInputSchema.parse({requestKey:crypto.randomUUID(),bookId,cardId,cutoffBodyVersionId:old.cutoffBodyVersionId,sourceHash:old.source.hash,kind,message:kind==='scene_analysis'?old.message.trim()||'请根据本人档案、截至正文及已有作者谈话整理场景分析。':old.message,historyKeys:rounds.map(item=>item.input.requestKey)});if(!persist({...old,pending:input,result:null,notWritten:false,checkedAbsent:false}))return;try{await accept(input,await api.run(input));}catch(error){if((error as {recovery?:{mutationOutcome?:string}})?.recovery?.mutationOutcome==='not_written')persist({...live.current,notWritten:true,checkedAbsent:false});throw error;}});
 const check=()=>exclusive(async()=>{const input=live.current.pending;if(!input)return;const result=await api.byKey(input.requestKey);if(result)await accept(input,result);else{if(!blocked)persist({...live.current,checkedAbsent:true});setMessage('原请求暂未找到；未找到不证明未调用，不换键重新发送。');}});
 const recover=(end=false)=>exclusive(async()=>{const old=live.current;if(blocked||!old.pending||!old.result||end&&!old.result.canEndExpired||!end&&!old.result.canCompleteSaved)return;if(end&&!confirm('明确结束过期未知领取？实际调用与用量仍未知，原记录保留，不会重新调用模型。'))return;await accept(old.pending,await(end?api.endExpired(old.result.id):api.complete(old.result.id)));});
 const locked=busy||blocked||Boolean(frame.pending),results=workspace?.results??[],lastAnalysis=results.find(item=>['succeeded','stale'].includes(item.status)&&item.input.kind==='scene_analysis'&&item.output);
 return <section ref={panel} className={`nd-character-author${wide?' is-wide':''}`} aria-label="人物与作者谈话"><header><button className="nd-button nd-button-secondary" type="button" onClick={()=>{void (async()=>{if(document.fullscreenElement===panel.current)await document.exitFullscreen();else await panel.current?.requestFullscreen();})().catch(error=>setMessage(error instanceof Error?error.message:'工作区未能展开。'));}}>{wide?'收起谈话工作区':'展开宽谈话工作区'}</button><h3>与{title}谈话</h3><p>本人回复及场景分析为 AI 推断候选，不写入正式认知、状态或正文。</p></header><div className="nd-row-actions"><button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void exclusive(()=>read(live.current.cutoffBodyVersionId,!live.current.pending))}>只读读取人物来源与原回合</button></div><label className="nd-control">截至已发生正文<select value={frame.cutoffBodyVersionId??''} disabled={locked} onChange={event=>{const cutoff=event.target.value||null;if(persist({...live.current,cutoffBodyVersionId:cutoff,source:null,result:null}))void exclusive(()=>read(cutoff));}}><option value="">{workspace?.chapters.length?'请明确选择截至章':'尚无采用正文：仅本人档案、当前关系设定及初始设定'}</option>{workspace?.chapters.map(item=><option key={item.bodyVersionId} value={item.bodyVersionId}>{item.title}</option>)}</select></label><p>档案与关系是当前设定，关系端点按原引用版本识别；状态、本人确认认知和已发生内容仅截至所选章。当前设定中的未来安排不视为过去事实。</p>{frame.source&&<details><summary>本次确切来源（只读）</summary><pre>{JSON.stringify(frame.source.data,null,2)}</pre></details>}{workspace&&!workspace.capability.operational&&<p role="status">人物谈话与场景分析尚未启用；资料及历史可只读核对。</p>}{workspace?.resultsTruncated&&<p role="alert">只显示最近200条原回合，不据此拼接截断历史；停止新生成。</p>}
 <div className="nd-character-author-columns"><div><section className="nd-character-author-history" aria-label="已保存作者谈话">{[...results].reverse().map(result=><article key={result.id}><h4>{result.input.kind==='scene_analysis'?'场景分析':'作者谈话'} · {result.status==='stale'?'旧来源候选':result.status==='succeeded'?'已保存候选':result.status==='failed'?'本次失败':result.status==='ended_unknown'?'未知领取已结束':'原请求待核对'}</h4><p>作者：{result.input.message}</p>{result.output?.utterance&&<p>{title}：{result.output.utterance}</p>}<p>{result.summary}</p><details><summary>原版本与请求凭证</summary><code>{result.input.requestKey}</code><p>档案版本 {String(result.source.data.profile.versionId)} · 截至正文 {result.input.cutoffBodyVersionId??'无正文'}</p><p>原来源 {result.source.hash}</p></details></article>)}</section>
 <fieldset disabled={locked||!workspace?.capability.operational||!frame.source||workspace.resultsTruncated}><legend>下一轮作者发言</legend><label className="nd-control">对人物的话或本次分析关注点<textarea rows={4} maxLength={8000} value={frame.message} onChange={event=>persist({...live.current,message:event.target.value})}/></label><div className="nd-row-actions"><button className="nd-button nd-button-primary" type="button" disabled={!frame.message.trim()} onClick={()=>void send('conversation')}>明确发送一轮谈话</button><button className="nd-button nd-button-secondary" type="button" onClick={()=>void send('scene_analysis')}>{lastAnalysis?'更新场景分析':'让 AI 整理谈话场景'}</button></div></fieldset>
 {frame.pending&&<section className="nd-type-recovery" role="alert"><p>原人物谈话请求待核对，消息及冻结来源保留，不能换键重新生成。</p><code>{frame.pending.requestKey}</code><div className="nd-row-actions"><button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void check()}>只读核对原谈话请求</button>{frame.result?.canCompleteSaved&&<button className="nd-button nd-button-secondary" type="button" disabled={busy||blocked} onClick={()=>void recover()}>续存已收到原回复</button>}{frame.result?.canEndExpired&&<button className="nd-button nd-button-secondary" type="button" disabled={busy||blocked} onClick={()=>void recover(true)}>明确结束过期未知领取</button>}{frame.notWritten&&frame.checkedAbsent&&<button className="nd-button nd-button-secondary" type="button" disabled={busy||blocked} onClick={()=>void exclusive(async()=>{const old=live.current;if(!old.pending||!old.notWritten||!old.checkedAbsent||await api.byKey(old.pending.requestKey))throw Error('原请求已出现或未写入条件不完整，请先核对原回执。');if(confirm('本次确认未写入且只读核对未找到，明确释放原领取并保留消息？'))persist({...old,pending:null,result:null,notWritten:false,checkedAbsent:false});})}>明确释放已确认未写入领取</button>}</div></section>}
 </div>{lastAnalysis?.output&&<section aria-label="人物场景分析候选"><h3>人物场景分析 · 推断候选{lastAnalysis.status==='stale'?'（旧来源）':''}</h3><div className="nd-row-actions" role="tablist" aria-label="场景分析分区">{Object.entries(ANALYSIS_LABELS).map(([section,label])=><button className="nd-button nd-button-secondary" key={section} type="button" role="tab" id={`author-analysis-tab-${cardId}-${section}`} aria-selected={analysisSection===section} aria-controls={`author-analysis-panel-${cardId}`} onClick={()=>setAnalysisSection(section as keyof typeof ANALYSIS_LABELS)}>{label}</button>)}</div><article role="tabpanel" id={`author-analysis-panel-${cardId}`} aria-labelledby={`author-analysis-tab-${cardId}-${analysisSection}`}><h4>{ANALYSIS_LABELS[analysisSection]}</h4><ul>{lastAnalysis.output.analysis[analysisSection].map((item,i)=><li key={i}>{item}</li>)}</ul>{!lastAnalysis.output.analysis[analysisSection].length&&<p>本次未确认此项。</p>}</article></section>}</div>{message&&<p role="status">{message}</p>}{blocked&&<p role="alert">本地原凭证未通过核对；停止新写入，当前填写及旧记录保留。</p>}</section>;
}
