import {imagePreparationSelectionSchema} from '../../common/imagePreparation';
import {z} from 'zod';
import {publicCharacterTrialSchema,publicPortraitCommandSchema,publicDialogueOutputSchema,type PublicCharacterTrial,type PublicCharacterTrialInput,type PublicPortraitReceipt,type PublicPortraitCommand} from '../../common/publicCharacters';
import {IMAGE_SIZES} from '../../common/imageGeneration';
const uuid=z.string().uuid(),optionalId=z.union([z.literal(''),uuid]);
export const pendingSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('trials'),inputs:z.array(publicCharacterTrialSchema).min(1).max(4),index:z.number().int().min(0).max(3),dispatched:z.boolean()}).strict().refine(value=>value.index<value.inputs.length&&value.inputs.every(input=>input.resourceId===value.inputs[0].resourceId&&input.resourceVersionId===value.inputs[0].resourceVersionId&&input.sourceHash===value.inputs[0].sourceHash)&&new Set(value.inputs.map(input=>input.requestKey)).size===value.inputs.length),
 z.object({kind:z.literal('portrait'),input:publicPortraitCommandSchema}).strict(),
]);
export const draftSchema=z.object({resourceId:optionalId,versionId:optionalId,message:z.string().max(2000),historyKeys:z.array(uuid).max(31),imagePrompt:z.string().max(4000),preparation:imagePreparationSelectionSchema.optional(),imageDescription:z.string().max(4000),imageTitle:z.string().max(240),connectionVersionId:optionalId,size:z.enum(IMAGE_SIZES),count:z.number().int().min(1).max(4),dirty:z.boolean(),pending:pendingSchema.nullable(),lastResult:z.unknown().nullable()}).strict().superRefine((draft,context)=>{if(Boolean(draft.resourceId)!==Boolean(draft.versionId)||draft.pending?.kind==='trials'&&draft.pending.inputs.some(input=>input.resourceId!==draft.resourceId||input.resourceVersionId!==draft.versionId)||draft.pending?.kind==='portrait'&&draft.pending.input.resourceId!==draft.resourceId)context.addIssue({code:'custom',message:'原请求与来源范围不完整。'});if(draft.lastResult!==null){const value=draft.lastResult as PublicCharacterTrial;if(!value?.input||!validTrial(value.input,draft.lastResult))context.addIssue({code:'custom',message:'原已确认结果不完整。'});}});
export type WorkshopDraft=z.infer<typeof draftSchema>;
export const blankDraft=(resourceId='',versionId=''):WorkshopDraft=>({resourceId,versionId,message:'',historyKeys:[],imagePrompt:'',imageDescription:'',imageTitle:'',connectionVersionId:'',size:'1024x1024',count:1,dirty:false,pending:null,lastResult:null});
export function validTrial(input:PublicCharacterTrialInput,value:unknown):value is PublicCharacterTrial{
 if(!value||typeof value!=='object')return false;const row=value as PublicCharacterTrial,original=publicCharacterTrialSchema.safeParse(input),actual=publicCharacterTrialSchema.safeParse(row.input);
 if(!original.success||!actual.success||JSON.stringify(original.data)!==JSON.stringify(actual.data)||!uuid.safeParse(row.id).success||row.requestKey!==input.requestKey||row.source?.id!==input.resourceId||row.source.versionId!==input.resourceVersionId||row.source.hash!==input.sourceHash||!['running','succeeded','failed','ended_unknown'].includes(row.status)||!['not_sent','sending','sent_unknown','completed'].includes(row.requestState)||typeof row.canCompleteSaved!=='boolean'||typeof row.canEndExpired!=='boolean')return false;
 const source=row.source;
 if(!uuid.safeParse(source.typeVersionId).success||!Number.isSafeInteger(source.revision)||source.revision<1||typeof source.title!=='string'||!source.values||typeof source.values!=='object'||Array.isArray(source.values)||!Array.isArray(source.fields)||source.fields.some(field=>!field||typeof field.key!=='string'||typeof field.name!=='string'||typeof field.type!=='string')||!Array.isArray(source.localFields)||source.localFields.some(local=>!local||!uuid.safeParse(local.definitionId).success||!uuid.safeParse(local.versionId).success||!local.field||typeof local.field.key!=='string'||!Object.hasOwn(local,'value'))||typeof row.summary!=='string'||typeof row.createdAt!=='string'||!Number.isFinite(Date.parse(row.createdAt))||row.canCompleteSaved&&row.canEndExpired||row.status!=='running'&&(row.canCompleteSaved||row.canEndExpired))return false;
 if(row.status==='succeeded'){if(row.requestState!=='completed')return false;if(input.kind==='dialogue'){const output=publicDialogueOutputSchema.safeParse(row.output);if(!output.success||output.data.resourceId!==input.resourceId||output.data.resourceVersionId!==input.resourceVersionId)return false;}else{const image=row.output as import('../../common/publicCharacters').PublicPortraitOutput;if(!image||!uuid.safeParse(image.contentObjectId).success||!/^[a-f0-9]{64}$/.test(image.checksum)||!Number.isSafeInteger(image.byteSize)||image.byteSize<=0||!['image/png','image/jpeg','image/webp'].includes(image.mimeType)||image.title!==input.title||image.description!==input.description)return false;}}
 return true;
}
export function validPortraitReceipt(input:PublicPortraitCommand,value:unknown):value is PublicPortraitReceipt{if(!value||typeof value!=='object')return false;const row=value as PublicPortraitReceipt,original=publicPortraitCommandSchema.safeParse(input),actual=publicPortraitCommandSchema.safeParse(row.input);return original.success&&actual.success&&typeof row.repeated==='boolean'&&uuid.safeParse(row.id).success&&JSON.stringify(original.data)===JSON.stringify(actual.data);}
