import {runInputLabel,runInputRecord,runInputSchemaIssues,validateRunInput,type RunInputSchema} from '../../common/contextRunInput';

function empty(schema:RunInputSchema):unknown {if(schema.const!==undefined)return schema.const;if(schema.type==='object')return {};if(schema.type==='array')return [];if(schema.type==='boolean')return false;if(schema.type==='number'||schema.type==='integer')return 0;if(schema.type==='null')return null;return '';}
function ValueEditor({schema,value,onChange,label,disabled,depth=0}:{schema:RunInputSchema;value:unknown;onChange:(value:unknown)=>void;label:string;disabled:boolean;depth?:number}) {
 if(schema.const!==undefined)return <p>{label}：此发布版本内容已固定，无需填写。<details><summary>高级：查看固定内容</summary><pre>{JSON.stringify(schema.const,null,2)}</pre></details></p>;
 if(Array.isArray(schema.enum))return <label><span>{label}</span><select disabled={disabled} value={schema.enum.findIndex(option=>JSON.stringify(option)===JSON.stringify(value))} onChange={event=>onChange((schema.enum as unknown[])[Number(event.target.value)])}><option value={-1}>请选择</option>{schema.enum.map((option,index)=><option value={index} key={index}>{typeof option==='string'&&/[\u3400-\u9fff]/u.test(option)?option:typeof option==='boolean'?option?'是':'否':typeof option==='number'?String(option):`选项 ${index+1}`}</option>)}</select></label>;
 if(schema.type==='object') {
  const current=runInputRecord(value)?value:{};return <fieldset className="nd-context-author-group"><legend>{label}</legend>{Object.entries(schema.properties as Record<string,RunInputSchema>).map(([key,field],index)=><ValueEditor key={key} schema={field} value={current[key]} disabled={disabled} depth={depth+1} label={`${runInputLabel(field,index)}${Array.isArray(schema.required)&&schema.required.includes(key)?'（必填）':''}`} onChange={next=>onChange({...current,[key]:next})}/>)}</fieldset>;
 }
 if(schema.type==='array') {
  const current=Array.isArray(value)?value:[],field=schema.items as RunInputSchema;return <fieldset className="nd-context-author-group"><legend>{label}</legend>{current.map((item,index)=><div key={index}><ValueEditor schema={field} value={item} disabled={disabled} depth={depth+1} label={`第 ${index+1} 项`} onChange={next=>onChange(current.map((old,position)=>position===index?next:old))}/><button type="button" className="nd-button nd-button-secondary" disabled={disabled} onClick={()=>onChange(current.filter((_,position)=>position!==index))}>移除此项</button></div>)}<button type="button" className="nd-button nd-button-secondary" disabled={disabled||current.length>=Math.min(200,typeof schema.maxItems==='number'?schema.maxItems:200)} onClick={()=>onChange([...current,empty(field)])}>添加一项</button></fieldset>;
 }
 if(schema.type==='boolean')return <label><span>{label}</span><select disabled={disabled} value={typeof value==='boolean'?String(value):''} onChange={event=>onChange(event.target.value==='true')}><option value="">请选择</option><option value="true">是</option><option value="false">否</option></select></label>;
 if(schema.type==='null')return <p>{label}：空值 <button type="button" disabled={disabled} onClick={()=>onChange(null)}>设为空值</button></p>;
 if(schema.type==='number'||schema.type==='integer')return <label><span>{label}</span><input disabled={disabled} type="number" value={typeof value==='number'?value:''} min={typeof schema.minimum==='number'?schema.minimum:undefined} max={typeof schema.maximum==='number'?schema.maximum:undefined} step={schema.type==='integer'?1:'any'} onChange={event=>onChange(event.target.value===''?undefined:Number(event.target.value))}/></label>;
 return <label><span>{label}</span><textarea disabled={disabled} rows={3} value={typeof value==='string'?value:''} onChange={event=>onChange(event.target.value)}/>{typeof schema.description==='string'&&/[\u3400-\u9fff]/u.test(schema.description)&&<small>{schema.description}</small>}</label>;
}
export function RunInputForm({schema,text,onChange,disabled}:{schema:RunInputSchema|null;text:string;onChange:(text:string)=>void;disabled:boolean}) {
 if(!schema)return <p role="alert">尚无已发布输入规格，请选择正式创作任务；原输入保留。</p>;
 let value:unknown;try{value=JSON.parse(text);}catch{return <p role="alert">原输入格式无法读取，内容保留在下方高级输入；请核对，不会当作空表单。</p>;}
 const unsupported=runInputSchemaIssues(schema);if(unsupported.length)return <div role="alert">{unsupported.map((item,index)=><div key={index}><p>{item.label}：{item.message}</p><details><summary>高级：失败字段位置</summary><code>{item.path||'输入根对象'}</code></details></div>)}</div>;
 const issues=validateRunInput(schema,value);return <div><ValueEditor schema={schema} value={value} onChange={next=>onChange(JSON.stringify(next,null,2))} label="本次填写" disabled={disabled}/>{issues.length>0&&<div role="alert">{issues.slice(0,100).map((item,index)=><div key={index}><p>{item.label}：{item.message}</p><details><summary>高级：失败字段位置</summary><code>{item.path||'输入根对象'}</code></details></div>)}{issues.length>100&&<p>另有 {issues.length-100} 项需要核对；原输入完整保留，运行保持阻断，不截断后执行。</p>}</div>}</div>;
}
