import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {WorldLibraryCandidate,WorldLibraryPublish,PublishedWorldPackage,WorldInstallReceipt} from '../../../common/worldPackages';
import {formHash} from '../formAssist';
import {NewDesignError} from '../../domain/errors';

/** Link the original book materials to their new public copies. This is source
 * provenance, not an import or another author save. The complete library command
 * remains the authority for recovery. */
export async function linkPublishedSource(db:PoolClient,bookId:string,input:WorldLibraryPublish,candidate:WorldLibraryCandidate,published:PublishedWorldPackage,created:Map<string,{id:string;versionId:string}>,relationCopies:Map<string,{id:string;versionId:string}>):Promise<WorldInstallReceipt>{
 if((await db.query('SELECT 1 FROM new_design.world_package_installations WHERE book_id=$1 AND root_card_id=$2',[bookId,candidate.input.rootCardId])).rowCount)throw new NewDesignError('当前世界已有公共来源，请从同步管理准备推送，原来源保留。',409);
 const installationId=randomUUID(),inputHash=formHash({scope:bookId,input}),cards:WorldInstallReceipt['cards']=candidate.input.cards.map(item=>{const original=candidate.preview.sourceFrame.cards.find(card=>card.cardId===item.sourceCardId)!,source=created.get(item.sourceCardId)!;return{sourceCardId:source.id,sourceVersionId:source.versionId,targetCardId:original.cardId,targetVersionId:original.versionId,targetTypeVersionId:original.typeVersionId,mapping:item.mapping.map(map=>({sourceKey:map.targetKey,targetKey:map.sourceKey,value:({...original.values,...original.localValues})[map.sourceKey]}))};}),relations:WorldInstallReceipt['relations']=candidate.input.relations.map(item=>{const original=candidate.preview.sourceFrame.relations.find(relation=>relation.relationId===item.sourceRelationId)!,source=relationCopies.get(item.sourceRelationId)!;return{sourceRelationId:source.id,sourceVersionId:source.versionId,targetRelationId:original.relationId,targetVersionId:original.versionId,targetTypeId:String(original.type.id)};});
 const receipt:WorldInstallReceipt={bookId,installationId,origin:'published_source',requestKey:input.requestKey,inputHash,input,packageId:published.id,cards,relations,sourceRoute:`/new-design/books/${bookId}/story-setting?tab=world&selected=${candidate.input.rootCardId}&detail=sync`,repeated:false};
 await db.query("INSERT INTO new_design.world_package_installations(id,book_id,package_id,root_card_id,sync_enabled,origin,request_key,input_hash,input,receipt) VALUES($1,$2,$3,$4,true,'published_source',$5,$6,$7::jsonb,$8::jsonb)",[installationId,bookId,published.id,candidate.input.rootCardId,input.requestKey,inputHash,JSON.stringify(input),JSON.stringify(receipt)]);
 for(const card of cards){await db.query('INSERT INTO new_design.world_package_install_card_refs(installation_id,source_card_id,source_version_id,target_card_id,target_version_id,target_type_version_id,mapping) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[installationId,card.sourceCardId,card.sourceVersionId,card.targetCardId,card.targetVersionId,card.targetTypeVersionId,JSON.stringify(card.mapping)]);await db.query("INSERT INTO new_design.resource_adoptions(id,resource_card_id,resource_version_id,book_id,target_card_id,action,snapshot) VALUES($1,$2,$3,$4,$5,'install_snapshot',$6::jsonb)",[randomUUID(),card.sourceCardId,card.sourceVersionId,bookId,card.targetCardId,JSON.stringify({contract:'published_world_source_v1',installationId,mapping:card.mapping})]);}
 for(const relation of relations)await db.query('INSERT INTO new_design.world_package_install_relation_refs(installation_id,source_relation_id,source_version_id,target_relation_id,target_version_id,target_type_id) VALUES($1,$2,$3,$4,$5,$6)',[installationId,relation.sourceRelationId,relation.sourceVersionId,relation.targetRelationId,relation.targetVersionId,relation.targetTypeId]);
 return receipt;
}
