import {z} from 'zod';
import {characterImportCommitSchema,type CharacterImportCommit,type CharacterImportReceipt} from '../../common/characterImport';
const id=z.union([z.literal(''),z.string().uuid()]),values=z.record(z.string().max(100),z.unknown());
export const importDraftSchema=z.object({format:z.literal(1),bookId:id,resourceId:id,resourceVersionId:id,title:z.string().max(500),mapping:z.record(z.string().max(100),z.object({targetKey:z.string().max(100),value:z.unknown().refine(value=>value!==undefined)}).strict()),additionalValues:values}).strict();
export type ImportDraft=z.infer<typeof importDraftSchema>;
export const blankImportDraft=():ImportDraft=>({format:1,bookId:'',resourceId:'',resourceVersionId:'',title:'',mapping:{},additionalValues:{}});
export function draftOf(bookId:string,input:CharacterImportCommit):ImportDraft{return{format:1,bookId,resourceId:input.resourceId,resourceVersionId:input.resourceVersionId,title:input.title,mapping:Object.fromEntries(input.mapping.map(item=>[item.sourceKey,{targetKey:item.targetKey,value:item.value}])),additionalValues:input.additionalValues};}
function canonical(value:unknown):unknown{return Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])):value;}
export const sameImportValue=(a:unknown,b:unknown)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
export function validImportReceipt(value:unknown,bookId?:string,input?:CharacterImportCommit):value is CharacterImportReceipt{
 try{const result=value as CharacterImportReceipt;return!!result&&z.string().uuid().safeParse(result.bookId).success&&characterImportCommitSchema.safeParse(result.input).success&&(!bookId||result.bookId===bookId)&&(!input||sameImportValue(result.input,input))&&Array.isArray(result.mappedFields)&&result.mappedFields.length===result.input.mapping.length&&result.mappedFields.every((field,index)=>typeof field.sourceLabel==='string'&&typeof field.targetLabel==='string'&&field.sourceKey===result.input.mapping[index]?.sourceKey&&field.targetKey===result.input.mapping[index]?.targetKey)&&result.requestKey===result.input.requestKey&&result.resourceId===result.input.resourceId&&result.resourceVersionId===result.input.resourceVersionId&&result.receipt?.bookId===result.bookId&&result.receipt.requestKey===result.requestKey&&result.receipt.operation==='create'&&z.string().uuid().safeParse(result.receipt.card?.id).success&&z.string().uuid().safeParse(result.receipt.card?.cardTypeId).success&&z.string().uuid().safeParse(result.receipt.cardVersionId).success&&result.sourceRoute===`/new-design/books/${result.bookId}/story-setting?tab=characters&selected=${result.receipt.card.id}&type=${result.receipt.card.cardTypeId}&detail=basic`;}catch{return false;}
}
