import type {PoolClient} from 'pg';
import type {FrozenWorldRelation,PublishedWorldPackage,WorldInstallReceipt,WorldSyncRelation,WorldValue} from '../../../../common/worldPackages';
import {formHash} from '../../formAssist';
import {listRecordCards} from '../../recordCards';
const at=(value:unknown):WorldValue=>value===undefined?{present:false}:{present:true,value};
export function publicRelationValue(relation:FrozenWorldRelation|undefined):WorldValue{return at(relation?{sourceCardId:relation.sourceCardId,targetCardId:relation.targetCardId,properties:relation.properties,status:'active'}:undefined);}
export async function readSyncRelations(db:PoolClient,bookId:string,installation:WorldInstallReceipt,original:PublishedWorldPackage['frame'],upstream:PublishedWorldPackage,cards:WorldInstallReceipt['cards'],lock:boolean):Promise<WorldSyncRelation[]>{
 const commands=(await listRecordCards(db,'world_package_sync_command')).filter(row=>row.installation_id===installation.installationId).sort((left,right)=>Number(right.sequence)-Number(left.sequence)),seen=new Set<string>(),baselines=[];for(const command of commands)for(const baseline of command.relation_baselines??[]){if(!seen.has(String(baseline.source_relation_id))){seen.add(String(baseline.source_relation_id));baselines.push(baseline);}}
 const ids=[...new Set([...installation.relations.map(relation=>relation.sourceRelationId),...baselines.map(row=>String(row.source_relation_id)),...upstream.frame.relations.map(relation=>relation.relationId)])].sort(),result:WorldSyncRelation[]=[];
 for(const id of ids){const mapping=installation.relations.find(relation=>relation.sourceRelationId===id),saved=baselines.find(row=>row.source_relation_id===id),initial=original.relations.find(relation=>relation.relationId===id),next=upstream.frame.relations.find(relation=>relation.relationId===id),targetId=saved?.target_relation_id??mapping?.targetRelationId??null;
  const row=targetId?(await db.query('SELECT relation.*,version.id version_id,version.properties actual_properties,version.status actual_status,to_jsonb(type) type FROM new_design.card_relations relation JOIN new_design.card_relation_versions version ON version.id=relation.current_version_id JOIN new_design.relation_types type ON type.id=relation.relation_type_id JOIN new_design.books book ON book.space_id=relation.space_id WHERE relation.id=$1 AND book.id=$2'+(lock?' FOR SHARE OF relation,type':''),[targetId,bookId])).rows[0]:null;
  const initialLocal=mapping?(await db.query('SELECT version.properties,version.status,source.card_id source_card_id,target.card_id target_card_id FROM new_design.card_relation_versions version JOIN new_design.card_versions source ON source.id=version.source_card_version_id JOIN new_design.card_versions target ON target.id=version.target_card_version_id WHERE version.id=$1 AND version.card_relation_id=$2',[mapping.targetVersionId,mapping.targetRelationId])).rows[0]:null;
  const normalized=(value:{source_card_id:string;target_card_id:string;properties:unknown;status:string}|null):WorldValue=>at(value?{sourceCardId:cards.find(card=>card.targetCardId===value.source_card_id)?.sourceCardId??null,targetCardId:cards.find(card=>card.targetCardId===value.target_card_id)?.sourceCardId??null,properties:value.properties,status:value.status}:undefined);
  const local=normalized(row?{...row,properties:row.actual_properties,status:row.actual_status}:null),base=saved?.public_value??publicRelationValue(initial),localBase=saved?.local_value??normalized(initialLocal),up=publicRelationValue(next),lc=formHash(local)!==formHash(localBase),uc=formHash(up)!==formHash(base),status=!lc&&!uc?'unchanged':formHash(local)===formHash(up)?'converged':!uc?'local_only':!lc?'upstream_only':'conflict';
  result.push({sourceRelationId:id,title:String(next?.type.name??initial?.type.name??row?.type.name??'世界关系'),targetRelationId:targetId,targetVersionId:row?.version_id??null,targetTypeId:String(row?.relation_type_id??next?.type.id??initial?.type.id??''),targetRevision:row?Number(row.revision):null,base,localBase,local,upstream:up,status,original:initial??null,next:next??null});
 }
 return result;
}
