import BookWorkspacePage from "./BookWorkspacePage";
import BooksPage from "./BooksPage";
import ReadingPage from './bookshelf/ReadingPage';
import CreateBookPage from "./CreateBookPage";
import CardTypeCatalogPage from "./CardTypeCatalogPage";
import DictionaryRelationsPage from "./DictionaryRelationsPage";
import FormDesignerPage from "./FormDesignerPage";
import NewDesignLanding from "./NewDesignLanding";
import PromptComponentsPage from "./PromptComponentsPage";
import PromptCompositionPage from "./promptComposition";
import ResourceCenterPage from "./ResourceCenterPage";
import CharacterImportPage from './characterImport';
import ResourceTreesPage from "./ResourceTreesPage";
import ResearchRecordsPage from "./ResearchRecordsPage";
import MarketRadarPage from "./MarketRadarPage";
import BookAnalysisPage from "./BookAnalysisPage";
import ReferencePacksPage from "./ReferencePacksPage";
import StrategyResourcesPage from "./StrategyResourcesPage";
import TemplateGroupsPage from "./TemplateGroupsPage";
import ContextManagementPage from "./ContextManagementPage";
import { BookOverviewPage } from "./planningCenter";
import { ChapterWritingPage } from "./chapterWriting";
import CompletionExportPage from "./completionExport/CompletionExportPage";
import OperationsMaintenancePage from "./operations/OperationsMaintenancePage";
import ModelSettingsPage from "./modelSettings";
import KnowledgeReferencePage from "./knowledgeReference";
import {AuthorTaskCenterPage} from "./authorTasks";
import {newDesignApi} from "./api";
import ProfessionalResourcesPage from "./professionalResources";
import {BookCompositionPage} from "./bookComposition";
import ProductionDirectorPage from "./productionDirector";
import WorldCharacterMaintenancePage from "./worldCharacterMaintenance";
import VisualAssetsPage from "./visualAssets";
import CreativeExtractionPage from "./creativeExtraction";
import {DirectorFollowupPage} from "./directorFollowup";
import CharacterDialoguePage from "./characterDialogue";
import ProfessionalViewsPage from "./professionalViews";
import {BookRouteShell} from "./bookNavigation";
import type {VisualAssetsApi} from "../common/visualAssets";
import "./new-design.css";
import "./legacySurface.css";
import type { BookViewKey } from "../common/contracts";
import {SettingWorkspace,PlanningWorkspace} from './storyWorkspace';
import PlanningCenterPage from './planningCenter/PlanningCenterPage';
import SimpleCreationPage from './simpleCreation';

interface NewDesignPageProps { pathname?:string; }
const visualApi:VisualAssetsApi={workspace:newDesignApi.getVisualWorkspace,upload:newDesignApi.uploadVisualAsset,command:newDesignApi.executeVisualCommand,preview:newDesignApi.previewVisualChange,receipt:newDesignApi.getVisualReceipt,previewByKey:newDesignApi.getVisualPreviewByKey,imageUrl:newDesignApi.visualImageUrl};

export default function NewDesignPage(props:NewDesignPageProps) {
  return <div className="nd-legacy-surface"><NewDesignRoute {...props}/></div>;
}

function NewDesignRoute({pathname}:NewDesignPageProps) {
  const path=(pathname??window.location.pathname).replace(/\/+$/,"")||"/new-design";
  if(path==="/new-design")return <NewDesignLanding/>;
  if(path==="/new-design/books")return <BooksPage/>;
  if(path==="/new-design/books/new")return <CreateBookPage/>;
  const simpleMatch=path.match(/^\/new-design\/books\/([^/]+)\/(simple|short-story)$/);
  if(simpleMatch)return <SimpleCreationPage key={`${simpleMatch[1]}:${simpleMatch[2]}`} bookId={decodeURIComponent(simpleMatch[1])} short={simpleMatch[2]==='short-story'}/>;
  const readingMatch=path.match(/^\/new-design\/books\/([^/]+)\/reading$/);
  if(readingMatch)return <ReadingPage key={readingMatch[1]} bookId={decodeURIComponent(readingMatch[1])}/>;
  if(path==="/new-design/knowledge")return <KnowledgeReferencePage/>;
  if(path==="/new-design/operations/records")return <AuthorTaskCenterPage api={newDesignApi}/>;
  if(path==="/new-design/operations/director")return <DirectorFollowupPage api={newDesignApi.directorFollowup}/>;
  const knowledgeMatch=path.match(/^\/new-design\/books\/([^/]+)\/knowledge$/);
  if(knowledgeMatch)return <KnowledgeReferencePage bookId={decodeURIComponent(knowledgeMatch[1])}/>;
  if(path==="/new-design/resources")return <ResourceCenterPage/>;
  if(path==="/new-design/resources/characters")return <CharacterImportPage/>;
  if(path==="/new-design/resources/extraction"){
    const query=new URLSearchParams(window.location.search),bookId=query.get("bookId"),mode=query.get("mode");
    if(!bookId||query.getAll("bookId").length!==1||! /^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(bookId))return <div className="nd-shell"><p role="alert">请先从我的书籍选择一本书，再打开写法与标题提炼。</p><a href="/new-design/books">选择书籍</a></div>;
    if(query.getAll("mode").length>1||mode!==null&&mode!=="writing_resource"&&mode!=="style_cleaning"&&mode!=="title_groups")return <div className="nd-shell"><p role="alert">专项来源无效，请返回本书重新选择写法或标题操作。</p><a href={`/new-design/books/${bookId}/overview`}>返回本书</a></div>;
    return <CreativeExtractionPage key={bookId} bookId={bookId} api={newDesignApi.creativeExtraction} initialMode={mode??"writing_resource"}/>;
  }
  if(path==="/new-design/resources/professional")return <ProfessionalResourcesPage api={{catalog:newDesignApi.getProfessionalCatalog,command:newDesignApi.executeProfessionalCommand,receipt:newDesignApi.getProfessionalReceipt}} trialApi={{catalog:newDesignApi.getCompositionCatalog,preview:newDesignApi.createCompositionPreview,previewByKey:newDesignApi.getCompositionPreviewByRequest,readPreview:newDesignApi.getCompositionPreview,run:newDesignApi.runCompositionPreview,result:newDesignApi.getCompositionResult}}/>;
  if(path==="/new-design/resources/dictionaries")return <ResourceTreesPage initialMode="dictionary"/>;
  if(path==="/new-design/resources/tags")return <ResourceTreesPage initialMode="tag"/>;
  if(path==="/new-design/resources/strategies")return <StrategyResourcesPage/>;
  if((path==="/new-design/resources/ai/prompt-components"||path==="/new-design/resources/prompts"))return <PromptComponentsPage/>;
  if(path==="/new-design/resources/ai/prompt-composition")return <PromptCompositionPage/>;
  if(path==="/new-design/research"||path==="/new-design/research/records")return <ResearchRecordsPage/>;
  if(path==="/new-design/research/market-radar")return <MarketRadarPage/>;
  if(path==="/new-design/research/book-analysis")return <BookAnalysisPage/>;
  if(path==="/new-design/research/reference-packs")return <ReferencePacksPage/>;
  const overviewMatch=path.match(/^\/new-design\/books\/([^/]+)\/overview$/);
  const compositionMatch=path.match(/^\/new-design\/books\/([^/]+)\/composition$/);
  if(compositionMatch)return <BookCompositionPage key={compositionMatch[1]} bookId={decodeURIComponent(compositionMatch[1])}/>;
  const directorMatch=path.match(/^\/new-design\/books\/([^/]+)\/director$/);
  if(directorMatch)return <ProductionDirectorPage key={directorMatch[1]} bookId={decodeURIComponent(directorMatch[1])}/>;
  const visualMatch=path.match(/^\/new-design\/books\/([^/]+)\/visual-assets$/);
  const dialogueMatch=path.match(/^\/new-design\/books\/([^/]+)\/character-dialogue$/);
  if(dialogueMatch)return <BookRouteShell key={dialogueMatch[1]} bookId={decodeURIComponent(dialogueMatch[1])} active="character-dialogue"><CharacterDialoguePage bookId={decodeURIComponent(dialogueMatch[1])} api={newDesignApi.characterDialogue}/></BookRouteShell>;
  const professionalViewsMatch=path.match(/^\/new-design\/books\/([^/]+)\/professional-views$/);
  if(professionalViewsMatch)return <ProfessionalViewsPage bookId={decodeURIComponent(professionalViewsMatch[1])} api={newDesignApi}/>;
  if(visualMatch)return <BookRouteShell key={visualMatch[1]} bookId={decodeURIComponent(visualMatch[1])} active="visual-assets"><VisualAssetsPage bookId={decodeURIComponent(visualMatch[1])} api={visualApi} imageApi={newDesignApi.imageGeneration}/></BookRouteShell>;
  const professionalMatch=path.match(/^\/new-design\/books\/([^/]+)\/(world|characters)$/);
  if(professionalMatch)return <WorldCharacterMaintenancePage bookId={decodeURIComponent(professionalMatch[1])} mode={professionalMatch[2]==="world"?"world":"character"}/>;
  if(overviewMatch)return <BookOverviewPage bookId={decodeURIComponent(overviewMatch[1])}/>;
  const settingMatch=path.match(/^\/new-design\/books\/([^/]+)\/setting$/);
  if(settingMatch)return <BookWorkspacePage key={settingMatch[1]} bookId={decodeURIComponent(settingMatch[1])} view="forms"/>;
  const storySettingMatch=path.match(/^\/new-design\/books\/([^/]+)\/story-setting$/);
  if(storySettingMatch)return <SettingWorkspace key={storySettingMatch[1]} bookId={decodeURIComponent(storySettingMatch[1])}/>;
  const planningMatch=path.match(/^\/new-design\/books\/([^/]+)\/planning$/);
  if(planningMatch){const stage=new URLSearchParams(location.search).get('stage');return stage==='story_macro'||stage==='outline'||stage==='structured'?<PlanningCenterPage key={`${planningMatch[1]}:${stage}`} bookId={decodeURIComponent(planningMatch[1])} presentation={stage}/>:<PlanningWorkspace key={planningMatch[1]} bookId={decodeURIComponent(planningMatch[1])}/>;}
  const writingMatch=path.match(/^\/new-design\/books\/([^/]+)\/(?:writing|chapters\/([^/]+)\/write)$/);
  if(writingMatch)return <ChapterWritingPage bookId={decodeURIComponent(writingMatch[1])} initialChapterCardId={writingMatch[2]?decodeURIComponent(writingMatch[2]):undefined}/>;
  const completionMatch=path.match(/^\/new-design\/books\/([^/]+)\/completion$/);
  if(completionMatch)return <CompletionExportPage bookId={decodeURIComponent(completionMatch[1])}/>;
  const viewMatch=path.match(/^\/new-design\/books\/([^/]+)\/views\/(chapters|characters|relations|events|clues|props|states|rules|comparison|quality|world|resources)$/);
  if(viewMatch)return <BookWorkspacePage bookId={decodeURIComponent(viewMatch[1])} view="views" viewKey={viewMatch[2] as BookViewKey}/>;
  const bookMatch=path.match(/^\/new-design\/books\/([^/]+)(?:\/(forms|cards|fields))?$/);
  if(bookMatch)return bookMatch[2]?<BookWorkspacePage bookId={decodeURIComponent(bookMatch[1])} view={bookMatch[2] as "forms"|"cards"|"fields"}/>:<BookOverviewPage bookId={decodeURIComponent(bookMatch[1])}/>;
  if(path==="/new-design/structure/card-types")return <CardTypeCatalogPage/>;
  if(path==="/new-design/structure/dictionaries-relations")return <DictionaryRelationsPage/>;
  if(path==="/new-design/structure/forms")return <FormDesignerPage/>;
  if(path==="/new-design/structure/templates")return <TemplateGroupsPage/>;
  if(path==="/new-design/structure/context")return <ContextManagementPage/>;
  if(path==="/new-design/structure/maintenance")return <OperationsMaintenancePage/>;
  if(path==="/new-design/structure/models")return <ModelSettingsPage/>;
  return <div className="nd-shell nd-fatal"><p className="nd-kicker">新设计</p><h1>页面不存在</h1><p>此地址不在当前新设计导航范围内。</p><a className="nd-button nd-button-primary" href="/new-design">返回创作首页</a></div>;
}
