import { useEffect, useState } from "react";
import type { ResearchRecordSummary, ResearchReferencePack } from "../common/contracts";
import { newDesignApi } from "./api";
import ResearchShell from "./ResearchShell";

const typeLabels={market_scan:"榜单扫描",market_analysis:"市场拆解",book_analysis:"作品拆书",diagnosis:"稿件诊断"} as const;

export default function ReferencePacksPage(){
  const [records,setRecords]=useState<ResearchRecordSummary[]>([]),[packs,setPacks]=useState<ResearchReferencePack[]>([]),[selected,setSelected]=useState<ResearchReferencePack|null>(null),[name,setName]=useState(""),[description,setDescription]=useState(""),[note,setNote]=useState(""),[selectedVersions,setSelectedVersions]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=async()=>{const [nextRecords,nextPacks]=await Promise.all([newDesignApi.listResearchRecords(),newDesignApi.listReferencePacks()]);setRecords(nextRecords.filter((item)=>["completed","partial"].includes(item.currentVersion.runStatus)));setPacks(nextPacks);return nextPacks;};
  useEffect(()=>{void load().catch((error)=>setMessage(error instanceof Error?error.message:"研究参考包加载失败。"));},[]);
  const edit=(pack:ResearchReferencePack|null)=>{setSelected(pack);setName(pack?.name??"");setDescription(pack?.description??"");setNote("");setSelectedVersions(pack?.versions[0]?.items.map((item)=>item.researchVersionId)??[]);setMessage("");};
  const toggle=(id:string)=>setSelectedVersions((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
  const publish=async()=>{setBusy(true);setMessage("");try{const pack=await newDesignApi.publishReferencePack({id:selected?.id,name,description,note,revision:selected?.revision,items:selectedVersions.map((researchVersionId)=>({researchVersionId,purpose:"book_creation",weight:1,note:""}))});const next=await load();edit(next.find((item)=>item.id===pack.id)??pack);setMessage(`“${pack.name}”v${pack.currentVersion} 已发布；旧版本保持不变。`);}catch(error){setMessage(error instanceof Error?error.message:"参考包发布失败。");}finally{setBusy(false);}};
  return <ResearchShell active="packs"><main className="nd-pack-workspace"><section className="nd-pack-editor"><div className="nd-section-heading"><div><p className="nd-kicker">版本化研究资产</p><h2>{selected?`编辑 ${selected.name}`:"新建研究参考包"}</h2><p>把精确研究运行版本组合成一个可复用入口；以后重跑不会改变已发布版本。</p></div>{selected&&<button className="nd-button nd-button-secondary" onClick={()=>edit(null)} type="button">新建参考包</button>}</div><div className="nd-form-grid"><label className="nd-control"><span>参考包名称 *</span><input value={name} onChange={(event)=>setName(event.target.value)}/></label><label className="nd-control"><span>版本说明</span><input value={note} placeholder="例如：补充公版仙侠结构研究" onChange={(event)=>setNote(event.target.value)}/></label></div><label className="nd-control"><span>使用说明</span><textarea rows={3} value={description} onChange={(event)=>setDescription(event.target.value)}/></label><div className="nd-pack-records"><div className="nd-section-heading"><div><p className="nd-kicker">精确版本</p><h3>选择研究记录</h3></div><b>{selectedVersions.length}</b></div>{records.map((record)=><label className={selectedVersions.includes(record.currentVersion.id)?"is-selected":""} key={record.id}><input checked={selectedVersions.includes(record.currentVersion.id)} onChange={()=>toggle(record.currentVersion.id)} type="checkbox"/><span><strong>{record.title}</strong><small>{typeLabels[record.type]} · 运行 v{record.currentVersion.version} · {record.currentVersion.completedAt?new Date(record.currentVersion.completedAt).toLocaleDateString():"已完成"}</small></span></label>)}</div><button className="nd-button nd-button-primary" disabled={busy||!name.trim()||!selectedVersions.length} onClick={()=>void publish()} type="button">{busy?"正在发布…":selected?"发布新版本":"发布参考包 v1"}</button>{message&&<p className="nd-message">{message}</p>}</section><aside className="nd-pack-list"><div className="nd-section-heading"><div><p className="nd-kicker">已发布</p><h2>参考包</h2></div><b>{packs.length}</b></div>{packs.map((pack)=><button className={selected?.id===pack.id?"is-selected":""} key={pack.id} onClick={()=>edit(pack)} type="button"><strong>{pack.name}</strong><span>v{pack.currentVersion} · {pack.versions[0]?.items.length??0} 条记录</span><small>{pack.description||"没有说明"}</small></button>)}</aside></main></ResearchShell>;
}
