import {Router} from 'express';
import {z} from 'zod';
import {worldLibraryCommitSchema,worldLibraryInputSchema,worldLibraryPublishSchema} from '../../../common/worldPackages';
import {getWorldLibraryWorkspace,previewWorldLibrary,prepareWorldLibrary,previewWorldLibraryPublish,publishWorldLibrary,readWorldLibraryOriginal,WorldPackageWriteError} from '../../database/worldPackages';
import {AiExecutionError} from '../../ai';
const uuid=z.string().uuid();
function fail(error:unknown,next:(error:unknown)=>void){if(error instanceof WorldPackageWriteError){const problem=new AiExecutionError('核对世界库原保存',error.message,error.status,null,error.issues);problem.recovery.mutationOutcome=error.mutationOutcome;next(problem);}else next(error);}
export function worldLibraryReadRouter(){const router=Router();router.get('/books/:bookId/world-library/workspace',(req,res,next)=>{void Promise.resolve().then(()=>{const query=z.object({rootCardId:uuid}).strict().parse(req.query);return getWorldLibraryWorkspace(uuid.parse(req.params.bookId),query.rootCardId);}).then(data=>res.json({success:true,data})).catch(next);});router.get('/books/:bookId/world-library/candidates/:candidateId/preview',(req,res,next)=>{void Promise.resolve().then(()=>previewWorldLibraryPublish(uuid.parse(req.params.bookId),uuid.parse(req.params.candidateId))).then(data=>res.json({success:true,data})).catch(next);});router.post('/books/:bookId/world-library/original-receipt',(req,res,next)=>{void Promise.resolve().then(()=>readWorldLibraryOriginal(uuid.parse(req.params.bookId),z.union([worldLibraryCommitSchema,worldLibraryPublishSchema]).parse(req.body))).then(data=>res.json({success:true,data})).catch(error=>fail(error,next));});return router;}
export function worldLibraryWriteRouter(){const router=Router();router.post('/books/:bookId/world-library/preview',(req,res,next)=>{void Promise.resolve().then(()=>previewWorldLibrary(uuid.parse(req.params.bookId),worldLibraryInputSchema.parse(req.body))).then(data=>res.json({success:true,data})).catch(next);});router.post('/books/:bookId/world-library/prepare',(req,res,next)=>{void Promise.resolve().then(()=>prepareWorldLibrary(uuid.parse(req.params.bookId),worldLibraryCommitSchema.parse(req.body))).then(data=>res.status(201).json({success:true,data})).catch(error=>fail(error,next));});router.post('/books/:bookId/world-library/publish',(req,res,next)=>{void Promise.resolve().then(()=>publishWorldLibrary(uuid.parse(req.params.bookId),worldLibraryPublishSchema.parse(req.body))).then(data=>res.status(201).json({success:true,data})).catch(error=>fail(error,next));});return router;}
