import { useMemo, useState } from "react";
import type { ChapterAdoptionPreparation, ChapterBodySwitchImpactContract, ChapterBodyVersion, ChapterSettlementCategory, ChapterSettlementDraft, ChapterSettlementItem, ChapterSettlementRisk, ChapterSettlementWorkspace } from "../../common/contracts";
import { newDesignApi } from "../api";

const categoryLabels:Record<ChapterSettlementCategory,string>={fact:"确定事实",knowledge:"角色所知",character_state:"人物状态",relationship:"关系变化",prop:"道具变化",event:"事件结果",foreshadow:"伏笔进度"};
const riskLabels:Record<ChapterSettlementRisk,string>={low:"低风险",medium:"需留意",high:"重要变化",critical:"核心变化"};
const decisionLabels={pending:"待确认",confirm:"纳入本章结果",reject:"不纳入",defer:"稍后处理"} as const;
const blank={category:"character_state" as ChapterSettlementCategory,title:"",subjectId:"",subjectKind:"card" as "card"|"relation",stateKey:"",beforeText:"null",afterText:"",riskLevel:"medium" as ChapterSettlementRisk,evidence:"",reason:""};

function parseValue(value:string):unknown{const trimmed=value.trim();if(!trimmed)return "";try{return JSON.parse(trimmed);}catch{return value;}}
function step(workspace:ChapterSettlementWorkspace|null){if(!workspace)return 1;if(workspace.session.status==="stable")return 4;if(workspace.items.length===0)return 2;return 3;}

export default function AdoptionSettlementPanel({preparation,version,documentRevision,initialWorkspace=null,onClose,onStable}:{preparation:ChapterAdoptionPreparation;version:ChapterBodyVersion;documentRevision:number;initialWorkspace?:ChapterSettlementWorkspace|null;onClose:()=>void;onStable:()=>Promise<void>}){
  const [workspace,setWorkspace]=useState<ChapterSettlementWorkspace|null>(initialWorkspace),[impact,setImpact]=useState<ChapterBodySwitchImpactContract|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[filter,setFilter]=useState<"all"|"pending"|"important">("all"),[form,setForm]=useState(blank),[showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<string|null>(null);
  const currentStep=step(workspace),items=useMemo(()=>workspace?.items.filter(item=>filter==="all"||filter==="pending"?filter==="all"||item.decision==="pending":["high","critical"].includes(item.riskLevel))??[],[workspace,filter]);
  const act=async(run:()=>Promise<ChapterSettlementWorkspace>)=>{setBusy(true);setMessage("");try{setWorkspace(await run());}catch(error){setMessage(error instanceof Error?error.message:"操作没有完成，请稍后重试。");}finally{setBusy(false);}};
  const start=()=>act(()=>newDesignApi.startChapterAdoptionSession(preparation.id,{expectedRevision:documentRevision,idempotencyKey:`settlement:${preparation.id}`,actor:"user"}));
  const extract=async()=>{if(!workspace)return;setBusy(true);setMessage("");try{const request=await newDesignApi.createChapterProposalExtractionRequest(workspace.session.id,{idempotencyKey:`extract:${workspace.session.id}`,createdBy:"user"});setMessage(request.status==="unavailable"?request.errorSummary:"AI 正在整理正文变化，返回后会进入待确认清单。");}catch(error){setMessage(error instanceof Error?error.message:"变化提取请求没有提交。");}finally{setBusy(false);}};
  const decide=(itemId:string,decision:"confirm"|"reject"|"defer",revision:number)=>workspace&&act(()=>newDesignApi.decideChapterSettlementItems(workspace.session.id,{expectedRevision:workspace.session.revision,decisions:[{itemId,decision,expectedRevision:revision}],actor:"user"}));
  const beginEdit=(item:ChapterSettlementItem)=>{setEditingId(item.id);setForm({category:item.category,title:item.title,subjectId:item.subjectId,subjectKind:item.subjectKind,stateKey:item.stateKey,beforeText:JSON.stringify(item.beforeValue),afterText:JSON.stringify(item.afterValue),riskLevel:item.riskLevel,evidence:item.evidence.excerpt,reason:item.decisionNote||item.planExpectation||"依据正文证据修订"});setShowForm(true);};
  const add=async()=>{if(!workspace)return;const startOffset=version.content.indexOf(form.evidence);if(startOffset<0){setMessage("证据原文必须能在候选正文中找到。");return;}const draft:ChapterSettlementDraft={category:form.category,title:form.title,subjectKind:form.subjectKind,subjectId:form.subjectId,subjectCardId:form.subjectKind==="card"?form.subjectId:undefined,stateKey:form.stateKey,beforeValue:parseValue(form.beforeText),afterValue:parseValue(form.afterText),riskLevel:form.riskLevel,evidenceStart:startOffset,evidenceEnd:startOffset+form.evidence.length,evidenceLabel:"正文变化证据",reason:form.reason,valueKind:"text",holderKind:"reader",holderKey:"reader",acquisitionMethod:"manual"},item=workspace.items.find(candidate=>candidate.id===editingId);await act(()=>item?newDesignApi.updateChapterSettlementItem(item.id,{expectedRevision:item.revision,draft,actor:"user",note:"作者修改确认清单"}):newDesignApi.addChapterSettlementItem(workspace.session.id,{...draft,actor:"user"}));setForm(blank);setEditingId(null);setShowForm(false);};
  const settle=async()=>{if(!workspace)return;await act(()=>newDesignApi.settleChapterAdoptionSession(workspace.session.id,{expectedRevision:workspace.session.revision,idempotencyKey:`settle:${workspace.session.id}:${workspace.session.revision}`,actor:"user",note:"章节采用确认"}));};
  const loadImpact=async()=>{if(!workspace)return;setBusy(true);setMessage("");try{setImpact(await newDesignApi.getChapterBodySwitchImpactContract(workspace.session.id));}catch(error){setMessage(error instanceof Error?error.message:"影响范围没有加载完成。");}finally{setBusy(false);}};
  const finish=async()=>{await onStable();onClose();};
  return <div className="nd-settlement-overlay" role="dialog" aria-modal="true" aria-labelledby="settlement-title"><section className="nd-settlement-panel">
    <header><div><p className="nd-kicker">采用确认</p><h2 id="settlement-title">{version.version} 号候选 · 章节结果确认</h2><p>先确认正文，再核对故事中真正发生的变化。下一章只读取稳定结果。</p></div><button type="button" onClick={onClose} aria-label="关闭采用确认">关闭</button></header>
    <ol className="nd-settlement-steps" aria-label="采用确认进度">{["确认正文","整理变化","人工核对","稳定结果"].map((label,index)=><li className={currentStep===index+1?"is-current":currentStep>index+1?"is-complete":""} aria-current={currentStep===index+1?"step":undefined} key={label}><span>{index+1}</span><strong>{label}</strong></li>)}</ol>
    {message?<p className="nd-settlement-message" role="status" aria-live="polite">{message}</p>:null}
    {!workspace?<div className="nd-settlement-body"><section className="nd-settlement-preview"><div><span>{version.content.length} 字</span><span>计划 {version.planningVersionId?.slice(0,8)??"人工稿"}</span><span>来源 {version.createdByKind}</span></div><pre>{version.content}</pre></section><aside><h3>采用后会发生什么</h3><p>这份正文将成为本章基准。人物、关系、道具、事件和伏笔变化仍需逐项确认，正文不会直接改写资料库。</p><button className="nd-button nd-button-primary" type="button" disabled={busy} onClick={start}>确认采用并检查变化</button></aside></div>:workspace.session.status==="impact_review_required"?<div className="nd-settlement-boundary"><strong>需要先看影响范围</strong><p>本章存在稳定结果。切换正文会影响后续章节与资料引用，本阶段只提供新旧正文和依赖清单，不执行重算。</p><button className="nd-button nd-button-primary" type="button" disabled={busy} onClick={()=>void loadImpact()}>{impact?"刷新影响清单":"查看影响清单"}</button>{impact?<div className="nd-settlement-impact-grid"><section><h4>采用正文</h4><pre>{impact.oldBody?.content??"未找到旧正文"}</pre></section><section><h4>候选正文</h4><pre>{impact.newBody.content}</pre></section><section className="is-wide"><h4>下游引用 · {impact.downstreamDependencies.length} 项</h4>{impact.downstreamDependencies.length?<ul>{impact.downstreamDependencies.map(item=><li key={`${item.resourceKind}:${item.stableKey}:${item.currentVersionId}`}><strong>{item.resourceKind}</strong><span>{item.stableKey.slice(0,8)} · 版本 {item.currentVersionId.slice(0,8)}</span></li>)}</ul>:<p>没有登记下游引用。换稿执行仍留在后续阶段。</p>}</section></div>:null}</div>:workspace.session.status==="stable"?<div className="nd-settlement-finished"><span aria-hidden="true">✓</span><h3>本章形成稳定结果</h3><p>采用正文、确认事实、状态变化和章节检查点处于同一结算边界。下一章可以读取这份结果。</p><button className="nd-button nd-button-primary" type="button" onClick={()=>void finish()}>返回章节创作</button></div>:<div className="nd-settlement-review">
      <section className="nd-settlement-source"><header><div><p className="nd-kicker">正文与计划</p><h3>变化依据</h3></div><span>{workspace.expectedChanges.length} 项计划预期</span></header><details><summary>查看采用正文</summary><pre>{workspace.candidate.content}</pre></details>{workspace.expectedChanges.length?<ul>{workspace.expectedChanges.map(item=><li key={item}>{item}</li>)}</ul>:<p>章节计划没有填写预期变化，可依据正文逐项补充。</p>}</section>
      <section className="nd-settlement-items"><header><div><p className="nd-kicker">本章变化</p><h3>{workspace.items.length} 项待核对内容</h3></div><div><button type="button" disabled={busy||!workspace.aiCapability.configured} onClick={()=>void extract()}>AI 整理</button><button type="button" onClick={()=>{setEditingId(null);setForm(blank);setShowForm(value=>!value);}}>手工补充</button></div></header><p className="nd-settlement-capability">{workspace.aiCapability.message}</p><nav aria-label="变化筛选"><button type="button" className={filter==="all"?"is-active":""} onClick={()=>setFilter("all")}>全部</button><button type="button" className={filter==="pending"?"is-active":""} onClick={()=>setFilter("pending")}>待确认 {workspace.counts.pending}</button><button type="button" className={filter==="important"?"is-active":""} onClick={()=>setFilter("important")}>重要变化</button></nav>
      {showForm?<div className="nd-settlement-form"><label>变化类型<select value={form.category} onChange={event=>setForm(value=>({...value,category:event.target.value as ChapterSettlementCategory,subjectId:"",subjectKind:event.target.value==="relationship"?"relation":"card"}))}>{Object.entries(categoryLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>变化对象<select value={form.subjectId} onChange={event=>{const subject=workspace.subjects.find(item=>item.id===event.target.value);setForm(value=>({...value,subjectId:event.target.value,subjectKind:subject?.subjectKind??"card"}));}}><option value="">请选择</option>{workspace.subjects.filter(subject=>form.category==="relationship"?subject.subjectKind==="relation":subject.subjectKind==="card").map(subject=><option value={subject.id} key={`${subject.subjectKind}:${subject.id}`}>{subject.title} · {subject.typeKey}</option>)}</select></label><label>变化标题<input value={form.title} onChange={event=>setForm(value=>({...value,title:event.target.value}))} placeholder="例如：陆沉得知师父隐瞒真相"/></label><label>记录字段<input value={form.stateKey} onChange={event=>setForm(value=>({...value,stateKey:event.target.value}))} placeholder="例如：信任状态、持有状态"/></label><label>变化前<textarea rows={2} value={form.beforeText} onChange={event=>setForm(value=>({...value,beforeText:event.target.value}))} placeholder="可填文字、数字或 JSON"/></label><label>变化后<textarea rows={2} value={form.afterText} onChange={event=>setForm(value=>({...value,afterText:event.target.value}))} placeholder="可填文字、数字或 JSON"/></label><label>风险级别<select value={form.riskLevel} onChange={event=>setForm(value=>({...value,riskLevel:event.target.value as ChapterSettlementRisk}))}>{Object.entries(riskLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="is-wide">正文证据<textarea rows={3} value={form.evidence} onChange={event=>setForm(value=>({...value,evidence:event.target.value}))} placeholder="粘贴候选正文中的原句，系统会记录精确位置"/></label><label className="is-wide">变化原因<textarea rows={2} value={form.reason} onChange={event=>setForm(value=>({...value,reason:event.target.value}))} placeholder="说明这项变化为何成立"/></label><div className="is-wide"><button type="button" onClick={()=>{setShowForm(false);setEditingId(null);setForm(blank);}}>取消</button><button className="nd-button-primary" type="button" disabled={busy||!form.subjectId||!form.title||!form.stateKey||!form.evidence||!form.reason} onClick={()=>void add()}>{editingId?"保存修改":"加入确认清单"}</button></div></div>:null}
      <div className="nd-settlement-item-list">{items.length?items.map(item=><article data-risk={item.riskLevel} key={item.id}><header><div><span>{categoryLabels[item.category]}</span><strong>{item.title}</strong><small>{item.subjectLabel} · {item.stateKey}</small></div><div><span>{riskLabels[item.riskLevel]}</span><span>{decisionLabels[item.decision]}</span></div></header><dl><div><dt>变化前</dt><dd>{JSON.stringify(item.beforeValue)}</dd></div><div><dt>变化后</dt><dd>{JSON.stringify(item.afterValue)}</dd></div></dl><details><summary>查看正文证据与来源</summary><blockquote>{item.evidence.excerpt}</blockquote><small>字符 {item.evidence.startOffset}–{item.evidence.endOffset} · {item.sourceKind==="ai"?`AI 任务 ${item.sourceTaskId?.slice(0,8)}`:"手工补充"}</small></details><footer>{item.decision==="pending"?<button type="button" disabled={busy} onClick={()=>beginEdit(item)}>修改</button>:null}<button type="button" disabled={busy} onClick={()=>void decide(item.id,"reject",item.revision)}>不纳入</button><button type="button" disabled={busy} onClick={()=>void decide(item.id,"defer",item.revision)}>稍后处理</button><button className="nd-button-primary" type="button" disabled={busy} onClick={()=>void decide(item.id,"confirm",item.revision)}>纳入本章结果</button></footer></article>):<div className="nd-empty-state"><strong>确认清单为空</strong><p>可让 AI 整理正文变化，也可以手工补充。正文没有资料变化时可直接形成稳定结果。</p></div>}</div>
      <footer className="nd-settlement-submit"><div><strong>{workspace.counts.confirm} 项纳入 · {workspace.counts.reject} 项不纳入</strong><span>{workspace.counts.pending+workspace.counts.defer?`还有 ${workspace.counts.pending+workspace.counts.defer} 项需要处理`:"可以形成稳定结果"}</span></div><button className="nd-button nd-button-primary" type="button" disabled={busy||workspace.counts.pending>0||workspace.counts.defer>0} onClick={()=>void settle()}>完成结算</button></footer></section></div>}
  </section></div>;
}
