import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { AdoptedChapterPlanContract, BookSummary, ChapterAdoptionPreparation, ChapterBodyVersion, ChapterDocumentDetail, ChapterRevisionStableReadContract, ChapterSettlementWorkspace, ChapterWritingChapter, ChapterWritingOperation, ChapterWritingRequest, ChapterWritingWorkspace, QualityIssue } from "../../common/contracts";
import BookShell from "../BookShell";
import { ApiError, newDesignApi } from "../api";
import AdoptionSettlementPanel,{type RetainedSettlementDraft} from "./AdoptionSettlementPanel";

type Panel="chapters"|"editor"|"context"|"candidates";
const operationLabels:Record<Exclude<ChapterWritingOperation,"manual_draft"|"copy">,string>={continue:"续写",rewrite:"改写",expand:"扩写",shorten:"缩写",dialogue:"对白调整",conflict:"冲突增强",fix:"问题修复",regenerate:"整章重生成"};
const sourceLabels:Record<ChapterBodyVersion["source"],string>={manual:"人工起稿",revision:"人工候选",ai_candidate:"AI 候选",import:"导入"};
const stateLabels:Record<ChapterWritingChapter["state"],string>={needs_plan:"缺少采用计划",ready:"可以起稿",writing:"生成中",review:"待处理问题",adopted:"有采用正文",settlement_pending:"待结算",stable:"稳定章节",settlement_failed:"结算需处理",impact_review_required:"待看改稿影响",revision_running:"换稿处理中",revision_partial_failure:"换稿需恢复",downstream_review:"受前文换稿影响"};
const requestLabels:Record<ChapterWritingRequest["status"],string>={preparing:"准备中",queued:"等待执行",running:"生成中",succeeded:"候选已入库",failed:"执行失败",cancelled:"已取消",unavailable:"执行能力不可用",stale:"来源已变化"};
const countText=(value:string)=>value.replace(/\s/g,"").length;
const requestKey=(prefix:string)=>`${prefix}:${crypto.randomUUID()}`;

export default function ChapterWritingPage({bookId,initialChapterCardId}:{bookId:string;initialChapterCardId?:string}){
  const routeParams=new URLSearchParams(window.location.search),routeChapterId=initialChapterCardId??routeParams.get("chapter")??routeParams.get("chapterDocument")??"",routeSessionId=routeParams.get("session")??"",routeDocumentId=routeParams.get("chapterDocument")??"";
  const [book,setBook]=useState<BookSummary|null>(null),[workspace,setWorkspace]=useState<ChapterWritingWorkspace|null>(null),[selectedId,setSelectedId]=useState(routeChapterId),[document,setDocument]=useState<ChapterDocumentDetail|null>(null),[plan,setPlan]=useState<AdoptedChapterPlanContract|null>(null),[issues,setIssues]=useState<QualityIssue[]>([]),[requests,setRequests]=useState<ChapterWritingRequest[]>([]),[revisionState,setRevisionState]=useState<ChapterRevisionStableReadContract|null>(null);
  const [draft,setDraft]=useState(""),[baseline,setBaseline]=useState(""),[baseVersionId,setBaseVersionId]=useState<string|null>(null),[compareLeft,setCompareLeft]=useState(""),[compareRight,setCompareRight]=useState(""),[panel,setPanel]=useState<Panel>("editor"),[message,setMessage]=useState(""),[conflict,setConflict]=useState(""),[busy,setBusy]=useState(false),[pendingChapter,setPendingChapter]=useState<ChapterWritingChapter|null>(null),[instruction,setInstruction]=useState("");
  const [adoption,setAdoption]=useState<{preparation:ChapterAdoptionPreparation;version:ChapterBodyVersion;documentRevision:number;workspace?:ChapterSettlementWorkspace}|null>(null);
  const [settlementDrafts,setSettlementDrafts]=useState<Record<string,RetainedSettlementDraft>>({}),[sourceFailure,setSourceFailure]=useState("");
  const sourceRead=useRef("");
  const retainSettlementDraft=useCallback((value:RetainedSettlementDraft|null)=>{if(!adoption)return;const key=adoption.preparation.id;setSettlementDrafts(current=>{const next={...current};if(value)next[key]=value;else delete next[key];return next;});},[adoption?.preparation.id]);
  const editorRef=useRef<HTMLTextAreaElement>(null),dirty=draft!==baseline,selected=workspace?.chapters.find(item=>item.chapterCardId===selectedId)??workspace?.chapters[0]??null;

  const loadWorkspace=useCallback(async()=>{const [nextBook,nextWorkspace]=await Promise.all([newDesignApi.getBook(bookId),newDesignApi.getChapterWritingWorkspace(bookId)]);setBook(nextBook);setWorkspace(nextWorkspace);setSelectedId(current=>{const match=current?nextWorkspace.chapters.find(item=>item.chapterCardId===current||item.documentId===current):null;return match?.chapterCardId??nextWorkspace.chapters[0]?.chapterCardId??"";});},[bookId]);
  const loadChapter=useCallback(async(chapter:ChapterWritingChapter|null)=>{setMessage("");setConflict("");if(!chapter){setDocument(null);setPlan(null);setIssues([]);setRequests([]);setRevisionState(null);setDraft("");setBaseline("");return;}const planPromise=chapter.hasAdoptedPlan?newDesignApi.getAdoptedChapterPlan(bookId,chapter.chapterCardId):Promise.resolve(null);if(!chapter.documentId){setDocument(null);setPlan(await planPromise);setIssues([]);setRequests([]);setRevisionState(null);setDraft("");setBaseline("");setBaseVersionId(null);return;}const [nextDocument,nextPlan,nextIssues,nextRequests,nextRevisionState]=await Promise.all([newDesignApi.getChapterDocument(chapter.documentId),planPromise,newDesignApi.listQualityIssues({bookId,chapterDocumentId:chapter.documentId,limit:30}),newDesignApi.listChapterWritingRequests(chapter.documentId),newDesignApi.getChapterRevisionStableReadContract(bookId,chapter.documentId)]);const seed=nextDocument.versions.find(item=>item.id===nextDocument.adoptedVersionId)??nextDocument.versions.find(item=>!item.archivedAt)??null;setDocument(nextDocument);setPlan(nextPlan);setIssues(nextIssues.filter(item=>["open","acknowledged","deferred","fix_proposed"].includes(item.currentStatus)));setRequests(nextRequests);setRevisionState(nextRevisionState);setDraft(seed?.content??"");setBaseline(seed?.content??"");setBaseVersionId(seed?.id??null);setCompareLeft(seed?.id??"");setCompareRight(nextDocument.versions.find(item=>item.id!==seed?.id&&!item.archivedAt)?.id??seed?.id??"");},[bookId]);
  useEffect(()=>{void loadWorkspace().catch(error=>setMessage(error instanceof Error?error.message:"章节工作台加载失败。"));},[loadWorkspace]);
  useEffect(()=>{void loadChapter(selected).catch(error=>setMessage(error instanceof Error?error.message:"章节内容加载失败。"));},[selected?.chapterCardId,loadChapter]);
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty||Object.keys(settlementDrafts).length){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty,settlementDrafts]);
  useEffect(()=>{
    if(!routeSessionId||!document||document.id!==routeDocumentId||sourceRead.current===routeSessionId)return;
    const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    if(!uuid.test(routeSessionId)||!uuid.test(routeDocumentId)){setSourceFailure("结算来源链接无效，请从本章候选点击继续确认。");sourceRead.current=routeSessionId;return;}
    let active=true;sourceRead.current=routeSessionId;
    void (async()=>{try{const next=await newDesignApi.getChapterSettlementEditingWorkspace(routeSessionId);if(next.session.bookId!==bookId||next.session.chapterDocumentId!==document.id)throw new Error("来源结算不属于本书当前章节，请从原章节继续确认。");const prepared=await newDesignApi.getChapterAdoptionPreparation(next.session.preparationId),body=document.versions.find(item=>item.id===next.session.bodyVersionId);if(!body)throw new Error("来源正文版本无法定位，已保存结算保留，请重新读取本章候选。");if(active){setAdoption({preparation:prepared,version:body,documentRevision:document.revision,workspace:next});setSourceFailure("");}}catch(error){if(active)setSourceFailure(error instanceof Error?error.message:"读取来源结算失败，已保存结果保留，可在本页重新核对。");}})();return()=>{active=false;sourceRead.current="";};
  },[bookId,routeSessionId,routeDocumentId,document?.id]);

  const grouped=useMemo(()=>{const groups=new Map<string,ChapterWritingChapter[]>();for(const item of workspace?.chapters??[])groups.set(item.volumeTitle,[...(groups.get(item.volumeTitle)??[]),item]);return [...groups.entries()];},[workspace]);
  const activeVersions=(document?.versions??[]).filter(item=>!item.archivedAt);
  const versionById=(id:string)=>activeVersions.find(item=>item.id===id)??null;

  const chooseChapter=(chapter:ChapterWritingChapter)=>{if(busy||adoption){setMessage("请先完成或保留本章采用确认，再切换章节。");return;}if(chapter.chapterCardId===selected?.chapterCardId)return;if(dirty){setPendingChapter(chapter);return;}setSelectedId(chapter.chapterCardId);setPanel("editor");};
  const save=async(operationKind:"manual_draft"|"copy"="manual_draft",sourceId=baseVersionId)=>{if(!document)return;setBusy(true);setMessage("");setConflict("");try{const next=await newDesignApi.saveChapterCandidate(document.id,{content:draft,operationKind,baseVersionId:sourceId,expectedRevision:document.revision,idempotencyKey:requestKey("candidate"),createdBy:"user"});setDocument(next);const saved=next.versions[0];setBaseline(saved.content);setDraft(saved.content);setBaseVersionId(saved.id);setMessage(`候选版本 ${saved.version} 已保存。`);await loadWorkspace();return true;}catch(error){if(error instanceof ApiError&&error.status===409)setConflict(`${error.message} 服务器修订号：${error.issues.serverRevision??"未知"}`);else setMessage(error instanceof Error?error.message:"候选保存失败。");return false;}finally{setBusy(false);}};
  const resolveSwitch=async(action:"save"|"discard"|"cancel")=>{const target=pendingChapter;if(action==="cancel"){setPendingChapter(null);return;}if(action==="save"&&!(await save()))return;setPendingChapter(null);if(target){setSelectedId(target.chapterCardId);setPanel("editor");}};
  const createDocument=async()=>{if(!selected)return;setBusy(true);try{const created=await newDesignApi.createChapterDocument(bookId,{chapterCardId:selected.chapterCardId,logicalOrder:selected.logicalOrder,title:selected.title});setDocument(created);setDraft("");setBaseline("");setBaseVersionId(null);await loadWorkspace();setMessage("正文档案已建立，可以开始起稿。");}catch(error){setMessage(error instanceof Error?error.message:"正文档案建立失败。");}finally{setBusy(false);}};
  const loadVersion=(version:ChapterBodyVersion)=>{if(dirty){setMessage("请先保存当前内容，再载入其他候选。");return;}setDraft(version.content);setBaseline(version.content);setBaseVersionId(version.id);setPanel("editor");};
  const copyVersion=async(version:ChapterBodyVersion)=>{if(!document||dirty)return;setBusy(true);try{const next=await newDesignApi.saveChapterCandidate(document.id,{content:version.content,operationKind:"copy",baseVersionId:version.id,expectedRevision:document.revision,idempotencyKey:requestKey("copy"),createdBy:"user"});setDocument(next);setDraft(next.versions[0].content);setBaseline(next.versions[0].content);setBaseVersionId(next.versions[0].id);setMessage(`已复制为候选版本 ${next.versions[0].version}。`);await loadWorkspace();}catch(error){setMessage(error instanceof Error?error.message:"复制候选失败。");}finally{setBusy(false);}};
  const askAi=async(operationKind:Exclude<ChapterWritingOperation,"manual_draft"|"copy">)=>{if(!document)return;const textarea=editorRef.current,start=textarea?.selectionStart??null,end=textarea&&textarea.selectionEnd!==textarea.selectionStart?textarea.selectionEnd:null;setBusy(true);setMessage("");try{const request=await newDesignApi.createChapterWritingRequest(document.id,{operationKind,baseBodyVersionId:baseVersionId,selectionStart:end===null?null:start,selectionEnd:end,instruction,expectedRevision:document.revision,idempotencyKey:requestKey("ai"),createdBy:"user"});setRequests(items=>[request,...items]);setMessage(request.status==="unavailable"?request.errorSummary:`${operationLabels[operationKind]}请求已进入队列，结果会保存为候选。`);}catch(error){setMessage(error instanceof Error?error.message:"AI 请求提交失败。");}finally{setBusy(false);}};
  const prepareAdoption=async(version:ChapterBodyVersion)=>{if(!document)return;setBusy(true);try{const prepared=await newDesignApi.prepareChapterAdoption(document.id,{bodyVersionId:version.id,expectedRevision:document.revision,idempotencyKey:requestKey("adopt"),createdBy:"user"});setAdoption({preparation:prepared,version,documentRevision:document.revision});}catch(error){setMessage(error instanceof Error?error.message:"采用确认资料准备失败。");}finally{setBusy(false);}};
  const resumeAdoption=async(sessionId:string)=>{if(!document||busy)return;setBusy(true);try{const next=await newDesignApi.getChapterSettlementEditingWorkspace(sessionId);if(next.session.bookId!==bookId||next.session.chapterDocumentId!==document.id)throw new Error("结算来源不属于本章，请回到原章节核对。");const prepared=await newDesignApi.getChapterAdoptionPreparation(next.session.preparationId),version=document.versions.find(item=>item.id===next.session.bodyVersionId);if(!version)throw new Error("采用正文版本不在当前章节中，已保存结果保留。");setAdoption({preparation:prepared,version,documentRevision:document.revision,workspace:next});setSourceFailure("");}catch(error){setSourceFailure(error instanceof Error?error.message:"采用确认读取失败，已保存结果保留。");}finally{setBusy(false);}};
  const refreshServerVersions=async()=>{if(!document)return;setBusy(true);try{const [nextDocument,nextIssues,nextRequests]=await Promise.all([newDesignApi.getChapterDocument(document.id),newDesignApi.listQualityIssues({bookId,chapterDocumentId:document.id,limit:30}),newDesignApi.listChapterWritingRequests(document.id)]);setDocument(nextDocument);setIssues(nextIssues.filter(item=>["open","acknowledged","deferred","fix_proposed"].includes(item.currentStatus)));setRequests(nextRequests);setConflict("");setMessage("服务器候选和任务状态已刷新，本地稿件保持不变，可比较后另存。");await loadWorkspace();}catch(error){setMessage(error instanceof Error?error.message:"服务器信息刷新失败。");}finally{setBusy(false);}};
  const resolveRevisionImpact=async(flagId:string,revision:number,resolution:"resolved"|"retained")=>{setBusy(true);try{await newDesignApi.resolveChapterRevisionReviewFlag(flagId,{expectedRevision:revision,resolution,note:resolution==="retained"?"作者复核后保留本章正文。":"作者根据前文换稿影响完成本章复核。",actor:"user"});await Promise.all([loadWorkspace(),loadChapter(selected)]);setMessage(resolution==="retained"?"本章正文已标记为复核后保留。":"本章受影响内容已完成复核。");}catch(error){setMessage(error instanceof Error?error.message:"换稿影响处理失败。");}finally{setBusy(false);}};

  if(!book||!workspace)return <div className="nd-loading-screen"><span className="nd-loader"/><p>{message||"正在准备章节工作台…"}</p></div>;
  return <BookShell book={book} active="writing"><main className="nd-writing-page">
    <section className="nd-writing-lead"><div><p className="nd-kicker">章节创作</p><h2>{selected?.title??"等待章节计划"}</h2><p>正文保存为候选，比较满意后再进入采用确认。采用与事实结算由后续确认流程完成。</p></div><div className="nd-writing-save-state"><span className={dirty?"is-dirty":""}>{dirty?"有未保存内容":"稿件已同步"}</span><strong>{countText(draft)} 字</strong></div></section>
    <nav className="nd-writing-mobile-tabs" aria-label="章节创作面板">{(["chapters","editor","context","candidates"] as Panel[]).map(item=><button type="button" className={panel===item?"is-active":""} onClick={()=>setPanel(item)} key={item}>{{chapters:"目录",editor:"正文",context:"资料",candidates:"候选"}[item]}</button>)}</nav>
    {message?<p className="nd-writing-message" role="status" aria-live="polite">{message}</p>:null}{conflict?<div className="nd-writing-conflict" role="alert"><strong>保存冲突</strong><span>{conflict}</span><button type="button" onClick={()=>void refreshServerVersions()}>刷新服务器候选</button></div>:null}
    {sourceFailure&&<div className="nd-writing-conflict" role="alert"><strong>未完成步骤：定位来源结算</strong><span>{sourceFailure}</span><span>已保存的正文与结算保留，读取不会自动采用或结算。</span><button type="button" disabled={busy||!routeSessionId} onClick={()=>void resumeAdoption(routeSessionId)}>只读重新定位结算</button></div>}
    {revisionState?.currentImpacts.length?<section className="nd-writing-revision-notice" aria-labelledby="revision-impact-title"><div><p className="nd-kicker">前文换稿影响</p><h3 id="revision-impact-title">本章正文需要作者复核</h3><p>{revisionState.currentImpacts[0].reason}</p><small>{revisionState.currentImpacts[0].manualProtected?"包含明确保留的人工纠正，系统不会自动覆盖。":"正文保持原样，只提示可能受影响的位置。"}</small></div><div><button type="button" disabled={busy} onClick={()=>void resolveRevisionImpact(revisionState.currentImpacts[0].id,revisionState.currentImpacts[0].revision,"retained")}>复核后保留正文</button><button className="nd-button nd-button-primary" type="button" disabled={busy} onClick={()=>void resolveRevisionImpact(revisionState.currentImpacts[0].id,revisionState.currentImpacts[0].revision,"resolved")}>已完成调整</button></div></section>:null}
    <div className={`nd-writing-layout panel-${panel}`}>
      <aside className="nd-writing-chapters"><header><div><p className="nd-kicker">卷章目录</p><h3>{workspace.chapters.length} 章</h3></div><span>真实进度</span></header>{grouped.length?<div className="nd-chapter-tree" role="tree">{grouped.map(([volume,chapters])=><section key={volume}><h4>{volume}</h4>{chapters.map(chapter=><button type="button" role="treeitem" aria-level={2} aria-current={chapter.chapterCardId===selected?.chapterCardId?"page":undefined} className={chapter.chapterCardId===selected?.chapterCardId?"is-selected":""} onClick={()=>chooseChapter(chapter)} key={chapter.chapterCardId}><span>{String(chapter.logicalOrder).padStart(2,"0")}</span><div><strong>{chapter.title}</strong><small>{stateLabels[chapter.state]} · {chapter.candidateCount} 个候选{chapter.pendingRequestCount?` · ${chapter.pendingRequestCount} 个任务`:""}</small></div>{chapter.openIssueCount?<em>{chapter.openIssueCount}</em>:null}</button>)}</section>)}</div>:<div className="nd-empty-state"><strong>暂无章节计划</strong><p>先在故事规划中建立章节并采用计划。</p><a href={`/new-design/books/${bookId}/planning`}>前往故事规划</a></div>}</aside>
      <section className="nd-writing-editor"><header><div><p className="nd-kicker">正文编辑器</p><h3>{document?`候选基于修订 ${document.revision}`:"等待建立正文档案"}</h3></div><div><button type="button" onClick={()=>void save()} disabled={busy||!document||!draft.trim()}>保存新候选</button></div></header>{!selected?<div className="nd-empty-state"><strong>选择章节开始写作</strong></div>:!selected.hasAdoptedPlan?<div className="nd-empty-state"><strong>本章缺少采用计划</strong><p>章节创作只读取明确采用的计划版本。</p><a href={`/new-design/books/${bookId}/planning#plan-${selected.planningObjectId}`}>完成章节计划</a></div>:!document?<div className="nd-empty-state"><strong>为本章建立正文档案</strong><p>正文档案会承载人工稿和 AI 候选的不可变版本。</p><button className="nd-button nd-button-primary" type="button" disabled={busy} onClick={()=>void createDocument()}>开始起稿</button></div>:<><label htmlFor="chapter-body-editor">章节正文（纯文本／Markdown）</label><textarea ref={editorRef} id="chapter-body-editor" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="从本章目标、人物行动和冲突变化开始写…" spellCheck/><div className="nd-writing-editor-meta"><span>来源版本：{baseVersionId?`#${versionById(baseVersionId)?.version??"-"}`:"新稿"}</span><span>{countText(draft)} 字</span><span>{dirty?"等待保存":"可继续编辑"}</span></div><section className="nd-ai-writing-tools"><div><p className="nd-kicker">AI 协作</p><small>{workspace.aiCapability.message}</small></div><label>补充要求<input value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="可选：语气、节奏或必须保留的内容"/></label><div>{Object.entries(operationLabels).map(([key,label])=><button type="button" disabled={busy||!workspace.aiCapability.configured||(key!=="regenerate"&&!baseVersionId)} onClick={()=>void askAi(key as Exclude<ChapterWritingOperation,"manual_draft"|"copy">)} key={key}>{label}</button>)}</div><small>选中文字后提交会记录选区来源；首版结果仍以整章候选返回，不会局部覆盖正文。</small></section></>}</section>
      <aside className="nd-writing-context"><section><header><div><p className="nd-kicker">采用计划</p><h3>{plan?`版本 ${plan.planningVersionNumber}`:"暂无可用计划"}</h3></div>{plan?<a href={`/new-design/books/${bookId}/planning#plan-${plan.planningObjectId}`}>编辑规划</a>:null}</header>{plan?<><p>{String(plan.content.goal??plan.content.summary??"本章计划未填写目标说明。")}</p><dl><div><dt>执行方式</dt><dd>{{manual:"人工",ai_assisted:"AI 辅助",automatic:"自动"}[plan.executionMode]}</dd></div><div><dt>资料引用</dt><dd>{plan.references.length} 项</dd></div><div><dt>规划来源</dt><dd>{plan.planningContentHash.slice(0,10)}</dd></div></dl></>:<p>采用章节计划后，工作台才会开放写作。</p>}</section><section><header><div><p className="nd-kicker">本章资料</p><h3>计划引用</h3></div></header>{plan?.references.length?<ul>{plan.references.map(ref=><li key={ref.id}><strong>{ref.title}</strong><span>{ref.cardTypeName}{ref.action?` · ${ref.action}`:""}</span><small>{ref.note||"由采用计划选入本章。"}</small></li>)}</ul>:<p>计划没有引用人物、地点、事件或伏笔资料。</p>}</section><section><header><div><p className="nd-kicker">质量与连续性</p><h3>{issues.length} 项待处理</h3></div></header>{issues.length?<ul>{issues.map(issue=><li key={issue.id}><strong>{issue.currentVersion.title}</strong><span>{issue.currentVersion.severity} · {issue.currentStatus}</span><small>{issue.currentVersion.suggestedAction||issue.currentVersion.description}</small></li>)}</ul>:<p>没有与本章关联的待处理问题。</p>}</section></aside>
      <section className="nd-writing-candidates"><header><div><p className="nd-kicker">候选与比较</p><h3>{activeVersions.length} 个可用版本</h3></div><div className="nd-writing-candidate-actions"><span>整章比较</span><button type="button" disabled={busy||!document} onClick={()=>void refreshServerVersions()}>刷新</button></div></header>{document&&activeVersions.length?<><div className="nd-candidate-list">{activeVersions.map(version=><article className={version.isAdopted?"is-adopted":""} key={version.id}><div><strong>版本 {version.version}</strong><span>{version.isAdopted?"采用正文":sourceLabels[version.source]}</span></div><p>{version.content.slice(0,120)}{version.content.length>120?"…":""}</p><small>{countText(version.content)} 字 · {new Date(version.createdAt).toLocaleString()} · {version.createdBy||version.createdByKind}</small><small>计划 {version.planningVersionId?.slice(0,8)??"未记录"} · 上下文 {version.contextManifestId?.slice(0,8)??"人工稿"}{version.aiTaskId?` · 任务 ${version.aiTaskId.slice(0,8)}`:""}</small><div><button type="button" disabled={dirty} title={dirty?"请先保存当前内容":undefined} onClick={()=>loadVersion(version)}>载入编辑</button><button type="button" disabled={busy||dirty} title={dirty?"请先保存当前内容":undefined} onClick={()=>void copyVersion(version)}>复制为人工候选</button>{selected?.settlementSessionId&&selected.settlementBodyVersionId===version.id&&selected.state!=="stable"?<button type="button" disabled={busy} onClick={()=>void resumeAdoption(selected.settlementSessionId!)}>继续确认</button>:!version.isAdopted&&version.planningVersionId===plan?.planningVersionId?<button type="button" disabled={busy} onClick={()=>void prepareAdoption(version)}>进入采用确认</button>:null}</div></article>)}</div><div className="nd-version-compare"><label>左侧<select value={compareLeft} onChange={event=>setCompareLeft(event.target.value)}>{activeVersions.map(item=><option value={item.id} key={item.id}>版本 {item.version} · {sourceLabels[item.source]}</option>)}</select></label><label>右侧<select value={compareRight} onChange={event=>setCompareRight(event.target.value)}>{activeVersions.map(item=><option value={item.id} key={item.id}>版本 {item.version} · {sourceLabels[item.source]}</option>)}</select></label><div><pre>{versionById(compareLeft)?.content??""}</pre><pre>{versionById(compareRight)?.content??""}</pre></div></div></>:<div className="nd-empty-state"><strong>暂无正文候选</strong><p>人工保存或 AI 返回后，候选会出现在这里。</p></div>}{requests.length?<div className="nd-writing-requests"><h4>生成任务</h4>{requests.map(request=><article key={request.id}><span>{operationLabels[request.operationKind]}</span><strong>{requestLabels[request.status]}</strong><small>{new Date(request.createdAt).toLocaleString()}{request.errorSummary?` · ${request.errorSummary}`:""}</small></article>)}</div>:null}</section>
    </div>
    {pendingChapter?<div className="nd-writing-dialog" role="dialog" aria-modal="true" aria-labelledby="unsaved-title"><div><p className="nd-kicker">未保存内容</p><h3 id="unsaved-title">切换章节前处理本地稿件</h3><p>保存会创建新的候选版本；放弃只清除本地未保存修改。</p><div><button type="button" onClick={()=>void resolveSwitch("cancel")}>取消</button><button type="button" onClick={()=>void resolveSwitch("discard")}>放弃修改</button><button className="nd-button-primary" type="button" disabled={busy||!draft.trim()} onClick={()=>void resolveSwitch("save")}>保存并切换</button></div></div></div>:null}
    {adoption?<AdoptionSettlementPanel key={adoption.preparation.id} preparation={adoption.preparation} version={adoption.version} documentRevision={adoption.documentRevision} initialWorkspace={adoption.workspace} retainedDraft={settlementDrafts[adoption.preparation.id]} onDraftChange={retainSettlementDraft} onClose={()=>{setAdoption(null);void loadWorkspace().catch(error=>setMessage(`采用确认已关闭，已保存结果与本地草稿保留；章节进度读取失败：${error instanceof Error?error.message:"请重新读取"}`));}} onStable={async()=>{await loadWorkspace();if(document){const next=await newDesignApi.getChapterDocument(document.id);setDocument(next);}setMessage("本章结算完成，下一章可读取稳定结果。本地正文填写保持不变。");}}/>:null}
  </main></BookShell>;
}
