import {z} from 'zod';
const uuid=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/),text=z.string().trim().min(1).max(8000),items=z.array(text).max(20);
export const characterAuthorInputSchema=z.object({requestKey:uuid,bookId:uuid,cardId:uuid,cutoffBodyVersionId:uuid.nullable(),sourceHash:hash,kind:z.enum(['conversation','scene_analysis']),message:text,historyKeys:z.array(uuid).max(100)}).strict();
export type CharacterAuthorInput=z.infer<typeof characterAuthorInputSchema>;
export const characterAuthorInfluenceDraftSchema=z.object({summary:z.string().trim().min(1).max(260),behaviorGuidance:z.string().trim().min(1).max(260),emotionalGuidance:z.string().trim().max(220),relationTension:z.string().trim().max(220),evidence:z.array(z.string().trim().min(1).max(220)).min(1).max(3),confidence:z.number().min(0).max(1)}).strict();
export const characterAuthorOutputSchema=z.object({bookId:uuid,cardId:uuid,sourceHash:hash,utterance:z.string().max(16000),analysis:z.object({situation:items,concerns:items,misreadings:items,pressureReactions:items,emotions:items,decisionTriggers:items,beliefs:items,inferenceBasis:items,uncertainties:items}).strict(),sourceVersionIds:z.array(uuid).max(300),influenceDraft:characterAuthorInfluenceDraftSchema.nullable().optional()}).strict();
export type CharacterAuthorOutput=z.infer<typeof characterAuthorOutputSchema>;
export interface CharacterAuthorSource{bookId:string;cardId:string;cutoffBodyVersionId:string|null;data:{book:Record<string,unknown>;profile:Record<string,unknown>;relations:Array<Record<string,unknown>>;chapters:Array<Record<string,unknown>>;states:Array<Record<string,unknown>>;knowledge:Array<Record<string,unknown>>};hash:string;versionIds:string[];}
export interface CharacterAuthorResult{id:string;input:CharacterAuthorInput;source:CharacterAuthorSource;status:'running'|'succeeded'|'stale'|'failed'|'ended_unknown';output:CharacterAuthorOutput|null;canCompleteSaved:boolean;canEndExpired:boolean;summary:string;}
export interface CharacterAuthorWorkspace{bookId:string;cardId:string;chapters:Array<{bodyVersionId:string;title:string;order:number}>;source:CharacterAuthorSource|null;results:CharacterAuthorResult[];resultsTruncated:boolean;capability:{installed:boolean;operational:boolean};}
export interface CharacterAuthorPromptInput{contract:'character_author_v1';input:CharacterAuthorInput;source:CharacterAuthorSource;history:Array<{requestKey:string;kind:CharacterAuthorInput['kind'];message:string;output:CharacterAuthorOutput}>;}
export const characterAuthorSourceSchema=z.object({bookId:uuid,cardId:uuid,cutoffBodyVersionId:uuid.nullable(),hash,versionIds:z.array(uuid),data:z.object({book:z.record(z.string(),z.unknown()),profile:z.record(z.string(),z.unknown()),relations:z.array(z.record(z.string(),z.unknown())),chapters:z.array(z.record(z.string(),z.unknown())),states:z.array(z.record(z.string(),z.unknown())),knowledge:z.array(z.record(z.string(),z.unknown()))}).strict()}).strict();
export const characterAuthorResultSchema=z.object({id:uuid,input:characterAuthorInputSchema,source:characterAuthorSourceSchema,status:z.enum(['running','succeeded','stale','failed','ended_unknown']),output:characterAuthorOutputSchema.nullable(),canCompleteSaved:z.boolean(),canEndExpired:z.boolean(),summary:z.string()}).strict();
export const characterAuthorWorkspaceSchema=z.object({bookId:uuid,cardId:uuid,chapters:z.array(z.object({bodyVersionId:uuid,title:z.string(),order:z.number()})),source:characterAuthorSourceSchema.nullable(),results:z.array(characterAuthorResultSchema),resultsTruncated:z.boolean(),capability:z.object({installed:z.boolean(),operational:z.boolean()}).strict()}).strict();
const influenceStatus=z.enum(['draft','active','expired','superseded','dismissed']);
export const characterAuthorInfluenceSchema=z.object({id:uuid,bookId:uuid,cardId:uuid,sourceHash:hash,draft:characterAuthorInfluenceDraftSchema,targetStart:z.number().int().positive(),targetEnd:z.number().int().positive(),status:influenceStatus,effectiveStatus:influenceStatus,revision:z.number().int().positive(),guidanceCardId:uuid.nullable(),guidanceVersionId:uuid.nullable(),referencedRequestIds:z.array(uuid).max(100),referencesTruncated:z.boolean(),reason:z.string()}).strict();
export type CharacterAuthorInfluence=z.infer<typeof characterAuthorInfluenceSchema>;
export const characterAuthorInfluenceCommandSchema=z.object({requestKey:uuid,bookId:uuid,cardId:uuid,candidateId:uuid,sourceHash:hash,expectedRevision:z.number().int().positive(),action:z.enum(['activate','dismiss','revoke']),targetStart:z.number().int().min(1).max(2147483645),targetEnd:z.number().int().min(1).max(2147483647)}).strict().refine(input=>input.targetEnd>=input.targetStart&&input.targetEnd-input.targetStart<=2,'创作倾向最多覆盖连续三章。');
export type CharacterAuthorInfluenceCommand=z.infer<typeof characterAuthorInfluenceCommandSchema>;
export const characterAuthorInfluenceReceiptSchema=z.object({requestKey:uuid,inputHash:hash,candidate:characterAuthorInfluenceSchema}).strict();
export const characterAuthorInfluenceWorkspaceSchema=z.object({bookId:uuid,cardId:uuid,capability:z.object({installed:z.boolean(),operational:z.boolean()}).strict(),candidates:z.array(characterAuthorInfluenceSchema).max(201),truncated:z.boolean(),nextChapterOrder:z.number().int().positive()}).strict();
