import type {ProfessionalObject} from '../../common/worldCharacterMaintenance';
import {useId,useRef} from 'react';
export interface GraphPoint {id:string;x:number;y:number;}
export interface GraphEdge {id:string;sourceId:string;targetId:string;label:string;directed:boolean;available:boolean;}
export default function GraphCanvas({objects,points,edges,selected,onSelect,onEdge,zoom=1,onMove}:{objects:Pick<ProfessionalObject,"id"|"title"|"typeLabel">[];points:GraphPoint[];edges:GraphEdge[];selected:string;onSelect:(id:string)=>void;onEdge:(id:string)=>void;zoom?:number;onMove?:(point:GraphPoint)=>void}){
 const arrowId=useId().replaceAll(':',''),svg=useRef<SVGSVGElement|null>(null),drag=useRef<{id:string;pointerId:number;clientX:number;clientY:number;point:GraphPoint;moved:boolean}|null>(null),suppressClick=useRef<string|null>(null);
 const pointById=new Map(points.map(point=>[point.id,point]));
 const width=Math.max(1000,...points.map(point=>point.x+180)),height=Math.max(360,...points.map(point=>point.y+80));
 return <div className="nd-pro-graph-scroll"><svg ref={svg} className="nd-pro-graph" viewBox={`0 0 ${width} ${height}`} style={{width:width*zoom,height:height*zoom}} role="group" aria-label="专业资料节点图；可选择人物和关系；支持拖动的节点仅调整本次视图">
  <defs><marker id={arrowId} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 z"/></marker></defs>
  {edges.map(edge=>{const a=pointById.get(edge.sourceId),b=pointById.get(edge.targetId);if(!a||!b)return null;return <g key={edge.id} className={edge.available?'':'is-unavailable'}><line x1={a.x+80} y1={a.y+22} x2={b.x+80} y2={b.y+22} markerEnd={edge.directed?`url(#${arrowId})`:undefined}/><foreignObject x={(a.x+b.x)/2+15} y={(a.y+b.y)/2+5} width="130" height="44"><button type="button" className="nd-pro-edge" onClick={()=>onEdge(edge.id)} title={edge.label}>{edge.label}</button></foreignObject></g>;})}
  {points.map(point=>{const object=objects.find(object=>object.id===point.id);if(!object)return null;return <foreignObject x={point.x} y={point.y} width="160" height="60" key={point.id}><button type="button" className={`nd-pro-node ${selected===point.id?'is-selected':''}`} style={onMove?{touchAction:'none',cursor:'grab'}:undefined} onPointerDown={event=>{suppressClick.current=null;if(!onMove||event.button!==0)return;drag.current={id:point.id,pointerId:event.pointerId,clientX:event.clientX,clientY:event.clientY,point,moved:false};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{const current=drag.current;if(!onMove||!current||current.id!==point.id||current.pointerId!==event.pointerId)return;const dx=event.clientX-current.clientX,dy=event.clientY-current.clientY;if(!current.moved&&Math.hypot(dx,dy)<4)return;current.moved=true;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const inverse=matrix.inverse(),start=new DOMPoint(current.clientX,current.clientY).matrixTransform(inverse),end=new DOMPoint(event.clientX,event.clientY).matrixTransform(inverse);onMove({id:point.id,x:Math.max(0,Math.min(20000,current.point.x+end.x-start.x)),y:Math.max(0,Math.min(20000,current.point.y+end.y-start.y))});}} onPointerUp={event=>{const current=drag.current;if(current?.pointerId!==event.pointerId)return;if(current.moved)suppressClick.current=point.id;drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onClick={()=>{if(suppressClick.current===point.id){suppressClick.current=null;return;}onSelect(point.id);}} aria-pressed={selected===point.id} title={`${object.title} · ${object.typeLabel}`}><span>{object.title}</span><small>{object.typeLabel}</small></button></foreignObject>;})}
 </svg></div>;
}
