import {readCardWorkflowCapability,recordWorkflowAction} from '../cardWorkflow';
import {createRecordCard,requireRecordCard,replaceRecordCard} from '../recordCards';
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {FieldDefinition} from '../../../common/contracts';
import {publicTitleInputSchema,publicTitleSourceSchema,publicTitleOutputSchema,publicTitleChoiceSchema,publicTitleChoiceReceiptSchema,publicTitleResultSchema,publicTitleLibrarySchema,PUBLIC_TITLE_ROUTE,type PublicTitleInput} from '../../../common/publicTitles';
import {getNewDesignPool} from '../runtime';
import {stableHash} from '../aiContracts';
import {createCardInTransaction,archiveCardInTransaction} from '../store';
import {NewDesignError,assertFound} from '../../domain/errors';
import {freezePublicTitle} from './freeze';
import {readPublicTitleReply,type PublicTitleReplyReferences} from '../../ai/imageGeneration/receipts';
type Plan=Awaited<ReturnType<typeof freezePublicTitle>>;
type Row={id:string;request_key:string;request_hash:string;source_id:string;source_version_id:string;source_hash:string;input_payload:PublicTitleInput;source_snapshot:Plan['promptInput']['source'];frozen_plan:Plan;step_id:string;attempt_id:string;status:'running'|'succeeded'|'failed'|'ended_unknown';reply:{output:unknown;execution:Record<string,unknown>}|null;output:unknown;summary:string;expired:boolean};
const SPACE='60000000-0000-4000-8000-000000000001';
export class PublicTitleError extends NewDesignError{readonly recovery;constructor(message:string,status=503,outcome:'not_written'|'unknown'='unknown'){super(message,status);this.recovery={summary:message,mutationOutcome:outcome,sourceRoute:PUBLIC_TITLE_ROUTE,actionLabel:'返回开书前标题工坊',savedResult:'原简述、参考固定版本、标题候选和原请求保留；只读核对不会重新调用模型。'};}}
export async function titleTransaction<T>(key:string|undefined,work:(client:PoolClient,absent:()=>void)=>Promise<T>){const client=await(await getNewDesignPool()).connect();let committing=false,isAbsent=false;try{await client.query('BEGIN');if(key)await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`public-title:${key}`]);const result=await work(client,()=>{isAbsent=true;});committing=true;await client.query('COMMIT');return result;}catch(error){const rolledBack=await client.query('ROLLBACK').then(()=>true,()=>false);throw new PublicTitleError(error instanceof NewDesignError?error.message:'公共标题原操作未确认，请保留原键只读核对。',error instanceof NewDesignError?error.status:503,isAbsent&&!committing&&rolledBack?'not_written':'unknown');}finally{client.release();}}
export async function titleCapability(client:PoolClient){return readCardWorkflowCapability(client,"public_title_factory_v1",["public_title_factory_trial"]);}
async function read(client:PoolClient,id:string,byKey=false,lock=false):Promise<Row|null>{if(!(await titleCapability(client)).installed)return null;const row=(await client.query<Row>(`SELECT trial.*,step.lease_expires_at<=now() expired FROM (SELECT fields.* FROM new_design.cards record JOIN new_design.card_types record_type ON record_type.id=record.card_type_id AND record_type.type_key='public_title_factory_trial' JOIN new_design.card_versions record_version ON record_version.id=record.current_version_id AND record_version.card_id=record.id CROSS JOIN LATERAL jsonb_to_record(record_version.values) AS fields(id uuid,request_key uuid,request_hash char(64),intent_hash char(64),source_id uuid,source_version_id uuid,source_hash char(64),input_payload jsonb,source_snapshot jsonb,frozen_plan jsonb,step_id uuid,attempt_id uuid,status text,reply jsonb,output jsonb,summary text,created_at timestamptz) WHERE record.status='active') trial JOIN new_design.ai_task_steps step ON step.id=trial.step_id WHERE trial.${byKey?'request_key':'id'}=$1`,[id])).rows[0]??null;if(row&&lock){for(const[table,id]of [['ai_tasks',row.id],['ai_task_steps',row.step_id],['ai_task_attempts',row.attempt_id]])await client.query(`SELECT id FROM new_design.${table} WHERE id=$1 FOR UPDATE`,[id]);await requireRecordCard(client,row.id,'public_title_factory_trial','原公共标题请求不存在。',{lock:true});return read(client,row.id);}return row;}
export const publicTitleRefs=(row:Row):PublicTitleReplyReferences=>({scopeKind:'public_title_factory',resourceId:row.source_id,resourceVersionId:row.source_version_id,requestId:row.id,attemptId:row.attempt_id,inputHash:row.frozen_plan.inputHash});
async function saved(row:Row){const reply=row.reply??await readPublicTitleReply(publicTitleRefs(row));if(reply&&(reply.execution.routeSnapshotId!==row.frozen_plan.snapshotId||reply.execution.routeSnapshotHash!==row.frozen_plan.snapshotHash))throw new PublicTitleError('原公共标题回复的冻结路线不一致，未用另一回复替代。',409);return reply;}
async function present(row:Row){const retained=row.status==='running'?await saved(row):null;return publicTitleResultSchema.parse({id:row.id,input:row.input_payload,source:row.source_snapshot,status:row.status,output:row.output,summary:row.summary,canCompleteSaved:row.status==='running'&&Boolean(retained),canEndExpired:row.status==='running'&&row.expired===true&&!retained});}
export const readPublicTitleByKey=(key:string)=>titleTransaction(undefined,async client=>{const row=await read(client,key,true);return row?present(row):null;});
export async function getPublicTitleWorkspace(before?:string){return titleTransaction(undefined,async client=>{const capability=await titleCapability(client),rows=capability.installed?(await client.query<Row>("SELECT trial.*,step.lease_expires_at<=now() expired FROM (SELECT fields.* FROM new_design.cards record JOIN new_design.card_types record_type ON record_type.id=record.card_type_id AND record_type.type_key='public_title_factory_trial' JOIN new_design.card_versions record_version ON record_version.id=record.current_version_id AND record_version.card_id=record.id CROSS JOIN LATERAL jsonb_to_record(record_version.values) AS fields(id uuid,request_key uuid,request_hash char(64),intent_hash char(64),source_id uuid,source_version_id uuid,source_hash char(64),input_payload jsonb,source_snapshot jsonb,frozen_plan jsonb,step_id uuid,attempt_id uuid,status text,reply jsonb,output jsonb,summary text,created_at timestamptz) WHERE record.status='active') trial JOIN new_design.ai_task_steps step ON step.id=trial.step_id WHERE ($1::uuid IS NULL OR (trial.created_at,trial.id)<(SELECT created_at,id FROM (SELECT fields.* FROM new_design.cards record JOIN new_design.card_types record_type ON record_type.id=record.card_type_id AND record_type.type_key='public_title_factory_trial' JOIN new_design.card_versions record_version ON record_version.id=record.current_version_id AND record_version.card_id=record.id CROSS JOIN LATERAL jsonb_to_record(record_version.values) AS fields(id uuid,request_key uuid,request_hash char(64),intent_hash char(64),source_id uuid,source_version_id uuid,source_hash char(64),input_payload jsonb,source_snapshot jsonb,frozen_plan jsonb,step_id uuid,attempt_id uuid,status text,reply jsonb,output jsonb,summary text,created_at timestamptz) WHERE record.status='active') public_title_factory_trial_record WHERE id=$1)) ORDER BY trial.created_at DESC,trial.id DESC LIMIT 51",[before??null])).rows:[];return{capability,results:await Promise.all(rows.slice(0,50).map(present)),truncated:rows.length>50,nextCursor:rows.length>50?rows[49].id:null};});}

async function resourceType(client:PoolClient,key:'public_title_brief'|'public_title_resource'){
 await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`public-title-type:${key}`]);
 const brief=key==='public_title_brief',definitions:Array<[string,FieldDefinition['type']]>=brief?[['content_kind','short_text'],['mode','short_text'],['brief','long_text'],['reference','long_text'],['instruction','long_text'],['group_count','number'],['candidates_per_group','number']]:[['content_kind','short_text'],['name','short_text'],['source_id','short_text'],['source_version_id','short_text'],['source_hash','short_text'],['source_trial_id','short_text'],['reason','long_text'],['risks','long_text']];
 const fields:FieldDefinition[]=definitions.map(([key,type],order)=>({key,name:({content_kind:'资料性质',mode:'标题来源方式',brief:'故事简述',reference:'参考原文',instruction:'标题要求',group_count:'分组数',candidates_per_group:'每组数量',name:'标题',source_id:'原来源资料',source_version_id:'原来源版本',source_hash:'原来源校验',source_trial_id:'原生成请求',reason:'适用理由',risks:'标题风险'} as Record<string,string>)[key],type,description:'固定原来源，候选不具有书名采用权。',required:!['brief','reference','risks'].includes(key),defaultValue:null,options:[],group:brief?'标题原来源':'标题库',order,aiSuggestible:false,stateSettlement:'none'}));
 const existing=(await client.query('SELECT id,status,current_version_id,source_card_type_id,semantic_capabilities FROM new_design.card_types WHERE space_id=$1 AND type_key=$2',[SPACE,key])).rows[0];if(existing){const version=(await client.query('SELECT fields FROM new_design.card_type_versions WHERE id=$1 AND card_type_id=$2',[existing.current_version_id,existing.id])).rows[0];if(existing.status!=='published'||existing.source_card_type_id!==null||stableHash(existing.semantic_capabilities)!==stableHash([])||!version||stableHash(version.fields)!==stableHash(fields))throw new PublicTitleError('公共标题的正式资料规格缺失或变化，未覆盖同名类型。',409);return existing.id as string;}
 const id=randomUUID(),versionId=randomUUID();await client.query("INSERT INTO new_design.card_types(id,space_id,type_key,name,description,status,draft_fields,is_system,sort_order,semantic_capabilities) VALUES($1,$2,$3,$4,'独立公共标题资料，无书籍或人物替身','published',$5::jsonb,false,991,'[]'::jsonb)",[id,SPACE,key,brief?'标题简述与参考原件':'中文标题库',JSON.stringify(fields)]);await client.query('INSERT INTO new_design.card_type_versions(id,card_type_id,version,fields) VALUES($1,$2,1,$3::jsonb)',[versionId,id,JSON.stringify(fields)]);await client.query('UPDATE new_design.card_types SET current_version_id=$2 WHERE id=$1',[id,versionId]);return id;
}
export async function claimPublicTitle(raw:unknown){const input=publicTitleInputSchema.parse(raw);return titleTransaction(input.requestKey,async(client,absent)=>{
 const prior=await read(client,input.requestKey,true);if(prior){if(prior.request_hash!==stableHash(input))throw new PublicTitleError('原公共标题请求键不可改变完整输入。',409);return{claimed:false as const,result:await present(prior)};}absent();if(!(await titleCapability(client)).operational)throw new PublicTitleError('开书前标题工坊尚未启用，原简述与参考保留。',503);
 const {requestKey,...intent}=input,intentHash=stableHash(intent);await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`public-title-intent:${intentHash}`]);if((await client.query("SELECT id FROM (SELECT fields.* FROM new_design.cards record JOIN new_design.card_types record_type ON record_type.id=record.card_type_id AND record_type.type_key='public_title_factory_trial' JOIN new_design.card_versions record_version ON record_version.id=record.current_version_id AND record_version.card_id=record.id CROSS JOIN LATERAL jsonb_to_record(record_version.values) AS fields(id uuid,request_key uuid,request_hash char(64),intent_hash char(64),source_id uuid,source_version_id uuid,source_hash char(64),input_payload jsonb,source_snapshot jsonb,frozen_plan jsonb,step_id uuid,attempt_id uuid,status text,reply jsonb,output jsonb,summary text,created_at timestamptz) WHERE record.status='active') public_title_factory_trial_record WHERE intent_hash=$1 AND status='running' LIMIT 1",[intentHash])).rowCount)throw new PublicTitleError('相同原标题来源有在途请求，请先只读核对原结果。',409);
 const typeId=await resourceType(client,'public_title_brief'),values={content_kind:'public_title_brief' as const,mode:input.mode,brief:input.brief,reference:input.reference,instruction:input.instruction,group_count:input.groupCount,candidates_per_group:input.candidatesPerGroup},card=await createCardInTransaction(client,{spaceId:SPACE,cardTypeId:typeId,title:input.mode==='brief'?'标题故事简述原件':'标题参考改写原件',values}),versionId=(await client.query('SELECT current_version_id FROM new_design.cards WHERE id=$1',[card.id])).rows[0].current_version_id,source=publicTitleSourceSchema.parse({id:card.id,versionId,values:card.values,hash:stableHash({id:card.id,versionId,values:card.values})});
 const id=randomUUID(),stepId=randomUUID(),attemptId=randomUUID(),lease=randomUUID(),plan=await freezePublicTitle(client,id,input,source);
 await client.query("INSERT INTO new_design.ai_tasks(id,space_id,book_id,task_key,task_contract_version_id,source_route,source_kind,source_id,request_idempotency_key,request_hash,status,current_step_key,created_by) VALUES($1,$2,NULL,$3,$4,$5,'public_title_factory',$1,$6,$7,'running','public_title_factory','public_title_factory')",[id,SPACE,`public_title_${id}`,plan.contractVersionId,PUBLIC_TITLE_ROUTE,input.requestKey,stableHash(input)]);
 await client.query("INSERT INTO new_design.ai_task_steps(id,task_id,step_key,sort_order,status,max_attempts,lease_owner,lease_token,lease_expires_at,heartbeat_at) VALUES($1,$2,'public_title_factory',0,'running',1,'public_title_factory',$3,now()+($4::int*interval '1 millisecond'),now())",[stepId,id,lease,plan.timeoutMs+60000]);
 await client.query("INSERT INTO new_design.ai_task_attempts(id,task_id,step_id,attempt_number,trigger_kind,status,task_contract_version_id,prompt_recipe_version_id,context_manifest_id,model_route_snapshot_id,input_hash,output_schema_version,lease_token_digest,started_at) VALUES($1,$2,$3,1,'initial','running',$4,$5,$6,$7,$8,$9,$10,now())",[attemptId,id,stepId,plan.contractVersionId,plan.recipeVersionId,plan.manifestId,plan.snapshotId,plan.inputHash,plan.outputSchemaVersion,stableHash(lease)]);
 await client.query('UPDATE new_design.ai_task_steps SET current_attempt_id=$2,revision=revision+1 WHERE id=$1',[stepId,attemptId]);for(const kind of ['task','step','attempt'])await client.query("INSERT INTO new_design.ai_task_events(id,task_id,step_id,attempt_id,entity_kind,from_status,to_status,reason_code,reason_detail,actor_kind,actor) VALUES($1,$2,$3,$4,$5,NULL,'running','public_title_claimed','开书前公共标题原来源已领取','worker','public_title_factory')",[randomUUID(),id,kind==='task'?null:stepId,kind==='attempt'?attemptId:null,kind]);
 await (async()=>{const values={id:id,request_key:input.requestKey,request_hash:stableHash(input),intent_hash:intentHash,source_id:source.id,source_version_id:source.versionId,source_hash:source.hash,input_payload:(input),source_snapshot:(source),frozen_plan:(plan),step_id:stepId,attempt_id:attemptId,status:"running",reply:null,output:null,summary:"",created_at:new Date().toISOString()};const row=await createRecordCard(client,{id:String(values.id),spaceId:SPACE,typeKey:"public_title_factory_trial",title:"public_title_factory_trial",values});return{rows:[row],rowCount:1};})();return{claimed:true as const,result:await present(assertFound(await read(client,id),'原公共标题请求未读取。')),plan,attemptId};
 });}

async function finish(client:PoolClient,row:Row,status:'succeeded'|'failed'|'ended_unknown',output:unknown,execution:Record<string,unknown>|null,summary:string){
 const number=(value:unknown)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?value:null,terminal=status==='ended_unknown'?'cancelled':status,attemptStatus=status==='ended_unknown'?'discarded':status;
 await client.query('INSERT INTO new_design.ai_attempt_usage(id,task_id,step_id,attempt_id,provider,model,input_tokens,output_tokens,duration_ms,fallback_count,budget_decision) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,0,$10)',[randomUUID(),row.id,row.step_id,row.attempt_id,row.frozen_plan.route.primary.provider,row.frozen_plan.route.primary.model,number(execution?.inputTokens),number(execution?.outputTokens),number(execution?.durationMs),number(execution?.inputTokens)!==null&&number(execution?.outputTokens)!==null?'within_budget':'unknown']);
 for(const[table,id,state]of [['ai_task_attempts',row.attempt_id,attemptStatus],['ai_task_steps',row.step_id,terminal],['ai_tasks',row.id,terminal]]){const result=await client.query(`UPDATE new_design.${table} SET status=$2 ${table==='ai_task_attempts'?",ended_at=now(),error_summary=$3,error_category=CASE WHEN $2='failed' THEN 'unknown' ELSE NULL END,retry_eligibility=CASE WHEN $2='failed' THEN 'none' ELSE NULL END":',revision=revision+1,completed_at=now(),updated_at=now()'+(table==='ai_task_steps'?',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL':'')} WHERE id=$1 AND status='running'`,table==='ai_task_attempts'?[id,state,summary]:[id,state]);if(result.rowCount!==1)throw new PublicTitleError('原公共标题领取已变化，结果保留。',409);}
 for(const kind of ['task','step','attempt'])await client.query("INSERT INTO new_design.ai_task_events(id,task_id,step_id,attempt_id,entity_kind,from_status,to_status,reason_code,reason_detail,actor_kind,actor) VALUES($1,$2,$3,$4,$5,'running',$6,'public_title_result',$7,'worker','public_title_factory')",[randomUUID(),row.id,kind==='task'?null:row.step_id,kind==='attempt'?row.attempt_id:null,kind,kind==='attempt'?attemptStatus:terminal,summary]);
 await (async()=>{const current=await requireRecordCard(client,row.id,"public_title_factory_trial","原请求不存在。",{lock:true});const savedRow=await replaceRecordCard(client,{id:current.recordCardId,spaceId:current.recordSpaceId,typeKey:"public_title_factory_trial",values:{...current,revision:Number(current.revision)+1,updated_at:new Date().toISOString(),status:status,output:output===null?null:(output),summary:summary}});return{rows:[savedRow],rowCount:1};})();
}
export const completePublicTitle=(id:string)=>titleTransaction(undefined,async client=>{const row=assertFound(await read(client,id,false,true),'原公共标题请求不存在。');if(row.status!=='running')return present(row);const reply=await saved(row);if(!reply)throw new PublicTitleError('尚无已收到的原标题回复，只读核对不会重新调用模型。',409);const {preparePrompt}=await import('../../ai/prompts'),output=publicTitleOutputSchema.parse(preparePrompt('public_title_factory',row.frozen_plan.promptInput).parseOutput(reply.output));if(!row.reply)await (async()=>{const current=await requireRecordCard(client,id,"public_title_factory_trial","原请求不存在。",{lock:true});const savedRow=await replaceRecordCard(client,{id:current.recordCardId,spaceId:current.recordSpaceId,typeKey:"public_title_factory_trial",values:{...current,revision:Number(current.revision)+1,updated_at:new Date().toISOString(),reply:({...reply,output})}});return{rows:[savedRow],rowCount:1};})();await finish(client,row,'succeeded',output,reply.execution,'分组标题候选已保存；未改书名，未写入标题库。');return present(assertFound(await read(client,id),'原公共标题结果未读取。'));});
export const failPublicTitle=(id:string,execution:Record<string,unknown>|null,known:boolean)=>titleTransaction(undefined,async client=>{const row=assertFound(await read(client,id,false,true),'原公共标题请求不存在。');if(row.status==='running'&&known)await finish(client,row,'failed',null,execution,'本次未形成可用分组标题，原来源和请求保留。');return present(assertFound(await read(client,id),'原公共标题结果未读取。'));});
export const endExpiredPublicTitle=(id:string)=>titleTransaction(undefined,async client=>{const row=assertFound(await read(client,id,false,true),'原公共标题请求不存在。');if(row.status!=='running')return present(row);if(!row.expired||await saved(row))throw new PublicTitleError('原领取尚未过期或已有原回复，不能结束后重调模型。',409);await finish(client,row,'ended_unknown',null,null,'未知公共标题领取已明确结束；真实调用和用量仍未知。');return present(assertFound(await read(client,id),'原公共标题结果未读取。'));});
export const readPublicTitleChoice=(key:string)=>titleTransaction(undefined,async client=>{if(!(await titleCapability(client)).installed)return null;const row=(await client.query('SELECT receipt FROM (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key=\'public_title.choice\') public_title_factory_choice_record WHERE request_key=$1',[key])).rows[0];return row?publicTitleChoiceReceiptSchema.parse(row.receipt):null;});
export const choosePublicTitle=(raw:unknown)=>{const input=publicTitleChoiceSchema.parse(raw),hash=stableHash(input);return titleTransaction(`choice:${input.requestKey}`,async(client,absent)=>{if(!(await titleCapability(client)).installed){absent();throw new PublicTitleError('公共标题尚未安装，原选择保留。',503);}const prior=(await client.query('SELECT input_hash,receipt FROM (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key=\'public_title.choice\') public_title_factory_choice_record WHERE request_key=$1',[input.requestKey])).rows[0];if(prior){if(prior.input_hash!==hash)throw new PublicTitleError('原标题选择键不能改动完整输入。',409);return publicTitleChoiceReceiptSchema.parse(prior.receipt);}absent();if(!(await titleCapability(client)).operational)throw new PublicTitleError('原标题保存或采用尚未启用。',503);const row=assertFound(await read(client,input.trialId,false,true),'原标题生成请求不存在。');if(row.status!=='succeeded'||row.source_version_id!==input.sourceVersionId||row.source_hash!==input.sourceHash)throw new PublicTitleError('原标题候选的确切来源未确认，未用相似标题代替。',409);const output=publicTitleOutputSchema.parse(row.output),candidate=assertFound(output.groups[input.groupIndex]?.titles[input.titleIndex],'原分组标题未找到。');let resourceId:string|null=null,versionId:string|null=null,bookRevision:number|null=null;
 if(input.action==='save_library'){const card=await createCardInTransaction(client,{spaceId:SPACE,cardTypeId:await resourceType(client,'public_title_resource'),title:candidate.title,values:{content_kind:'public_title_candidate',name:candidate.title,source_id:row.source_id,source_version_id:row.source_version_id,source_hash:row.source_hash,source_trial_id:row.id,reason:candidate.reason,risks:JSON.stringify(candidate.risks)}});resourceId=card.id;versionId=(await client.query('SELECT current_version_id FROM new_design.cards WHERE id=$1',[card.id])).rows[0].current_version_id;}
 else if(input.action==='archive_library'){const card=assertFound((await client.query("SELECT card.id FROM new_design.cards card JOIN new_design.card_types type ON type.id=card.card_type_id JOIN (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key='public_title.choice') choice ON choice.receipt->>'resourceId'=card.id::text AND choice.input_payload->>'action'='save_library' WHERE card.id=$1 AND card.space_id=$2 AND card.status='active' AND type.type_key='public_title_resource' AND choice.trial_id=$3 AND choice.input_payload->>'groupIndex'=$4 AND choice.input_payload->>'titleIndex'=$5 FOR UPDATE OF card",[input.resourceId,SPACE,row.id,String(input.groupIndex),String(input.titleIndex)])).rows[0],'Original selected library resource unavailable.');await archiveCardInTransaction(client,card.id,input.expectedRevision);resourceId=card.id;versionId=(await client.query('SELECT current_version_id FROM new_design.cards WHERE id=$1',[card.id])).rows[0].current_version_id;}
 else{const book=assertFound((await client.query("SELECT id,revision FROM new_design.books WHERE id=$1 AND status='active' FOR UPDATE",[input.bookId])).rows[0],'明确选择的本书不存在或已归档。');if(Number(book.revision)!==input.expectedBookRevision)throw new PublicTitleError('本书名称或修订已变化，原选择保留。',409);bookRevision=Number((await client.query('UPDATE new_design.books SET name=$2,revision=revision+1,updated_at=now() WHERE id=$1 RETURNING revision',[input.bookId,candidate.title])).rows[0].revision);}
 const receipt=publicTitleChoiceReceiptSchema.parse({requestKey:input.requestKey,inputHash:hash,command:input,title:candidate.title,resourceId,versionId,bookRevision});await recordWorkflowAction(client,{cardId:row.id,actionKey:"public_title.choice",requestKey:"public-title:choice:"+input.requestKey,inputHash:hash,payload:{request_key:input.requestKey,input_hash:hash,trial_id:row.id,input_payload:input},receipt});return receipt;
 });};

export const getPublicTitleLibrary=(before?:string)=>titleTransaction(undefined,async client=>{
 if(!(await titleCapability(client)).installed)return{items:[],truncated:false,nextCursor:null};
 const rows=(await client.query("SELECT card.id,card.current_version_id,card.revision,card.title,card.status,choice.input_payload FROM (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key='public_title.choice') choice JOIN new_design.cards card ON card.id=(choice.receipt->>'resourceId')::uuid JOIN new_design.card_types type ON type.id=card.card_type_id WHERE choice.input_payload->>'action'='save_library' AND type.type_key='public_title_resource' AND card.space_id=$1 AND ($2::uuid IS NULL OR (choice.created_at,card.id)<(SELECT saved.created_at,c.id FROM (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key='public_title.choice') saved JOIN new_design.cards c ON c.id=(saved.receipt->>'resourceId')::uuid WHERE saved.input_payload->>'action'='save_library' AND c.id=$2)) ORDER BY choice.created_at DESC,card.id DESC LIMIT 51",[SPACE,before??null])).rows;
 const items=await Promise.all(rows.slice(0,50).map(async row=>{const original=publicTitleChoiceSchema.parse(row.input_payload),used=(await client.query("SELECT book.id book_id,book.name,choice.request_key FROM (SELECT action.id,action.created_at,action.receipt,data.* FROM new_design.card_version_actions action CROSS JOIN LATERAL jsonb_to_record(action.payload) AS data(request_key uuid,input_hash text,trial_id uuid,input_payload jsonb) WHERE action.action_key='public_title.choice') choice JOIN new_design.books book ON book.id=(choice.input_payload->>'bookId')::uuid WHERE choice.input_payload->>'action'='adopt_book_title' AND choice.trial_id=$1 AND choice.input_payload->>'groupIndex'=$2 AND choice.input_payload->>'titleIndex'=$3 ORDER BY choice.created_at DESC LIMIT 101",[original.trialId,String(original.groupIndex),String(original.titleIndex)])).rows;return{id:row.id,versionId:row.current_version_id,revision:Number(row.revision),title:row.title,status:row.status,originalChoice:original,usedBy:used.slice(0,100).map(item=>({bookId:item.book_id,bookName:item.name,requestKey:item.request_key})),usageTruncated:used.length>100};}));
 return publicTitleLibrarySchema.parse({items,truncated:rows.length>50,nextCursor:rows.length>50?rows[49].id:null});
});
