import { useEffect, useMemo, useRef, useState } from "react";
import type { AssociationCandidate, AssociationItem, AssociationMountVersion, AssociationSlotSpec, AssociationWorkspace, BookSummary, CardGroupFormSummary, CardGroupFormVersion, CardSummary, CardTypeSummary, CardTypeVersion, FieldDefinition } from "../../common/contracts";
import { ApiError, newDesignApi } from "../api";
import DynamicForm from "../DynamicForm";
import AddInformationDialog from "./AddInformationDialog";
import { defaultValues, resolveBusinessForm } from "./model";

interface Props{book:BookSummary;primary:CardSummary;cardTypes:CardTypeSummary[];forms:CardGroupFormSummary[];formVersions:Map<string,CardGroupFormVersion[]>;hasUnsavedChanges:boolean;onSourcesChanged:()=>Promise<void>}
type SourceEditor={item:AssociationItem;type:CardTypeSummary;version:CardTypeVersion;title:string;values:Record<string,unknown>};
type CreateEditor={type:CardTypeSummary;version:CardTypeVersion;title:string;values:Record<string,unknown>};

function fieldsOf(item:AssociationItem):FieldDefinition[]{return item.localFields.filter((field)=>field.status==="active").map((field)=>field.currentVersion.field);}
function summaryText(candidate:AssociationCandidate){try{const values=JSON.parse(candidate.summary) as Record<string,unknown>;return Object.values(values).filter((value)=>typeof value==="string"&&value.trim()).slice(0,2).join(" · ")||"暂无摘要";}catch{return candidate.summary||"暂无摘要";}}

export default function AssociationPanel({book,primary,cardTypes,forms,formVersions,hasUnsavedChanges,onSourcesChanged}:Props){
  const [workspace,setWorkspace]=useState<AssociationWorkspace|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [searched,setSearched]=useState(false);
  const [drafts,setDrafts]=useState<Record<string,Record<string,unknown>>>({});const [picker,setPicker]=useState<AssociationSlotSpec|null>(null);const [query,setQuery]=useState("");const [candidates,setCandidates]=useState<AssociationCandidate[]>([]);const [hasMore,setHasMore]=useState(false);const [offset,setOffset]=useState(0);
  const [sourceEditor,setSourceEditor]=useState<SourceEditor|null>(null);const [createEditor,setCreateEditor]=useState<CreateEditor|null>(null);const [localFieldTarget,setLocalFieldTarget]=useState<AssociationItem|null>(null);const [history,setHistory]=useState<{item:AssociationItem;versions:AssociationMountVersion[]}|null>(null);
  const dialogHeading=useRef<HTMLHeadingElement>(null);
  const typeByKey=useMemo(()=>new Map(cardTypes.map((type)=>[type.key,type])),[cardTypes]);
  const load=async()=>{const next=await newDesignApi.getAssociationWorkspace(book.id,primary.id);setWorkspace(next);setDrafts((current)=>Object.fromEntries(next.items.map((item)=>[item.id,current[item.id]??item.localValues])));return next;};
  useEffect(()=>{setWorkspace(null);setError("");void load().catch((reason)=>setError(reason instanceof Error?reason.message:"关联资料暂时无法读取。"));},[book.id,primary.id]);
  useEffect(()=>{if(picker||sourceEditor||createEditor||history)dialogHeading.current?.focus();},[picker,sourceEditor,createEditor,history]);
  const act=async(action:()=>Promise<AssociationWorkspace>,message:string)=>{setBusy(true);setError("");setNotice("");try{const next=await action();setWorkspace(next);setDrafts((current)=>Object.fromEntries(next.items.map((item)=>[item.id,current[item.id]??item.localValues])));setNotice(message);return true;}catch(reason){setError(reason instanceof Error?reason.message:"操作没有完成，当前填写仍保留。 ");return false;}finally{setBusy(false);}};
  const search=async(nextOffset=0,append=false)=>{if(!picker)return;setBusy(true);setError("");try{const result=await newDesignApi.searchAssociationCandidates(book.id,primary.id,{slotKey:picker.key,query,offset:nextOffset,limit:12});setCandidates((current)=>append?[...current,...result.items]:result.items);setHasMore(result.hasMore);setOffset(nextOffset);setSearched(true);}catch(reason){setError(reason instanceof Error?reason.message:"暂时无法搜索本书资料。");}finally{setBusy(false);}};
  const openPicker=(slot:AssociationSlotSpec)=>{setPicker(slot);setQuery("");setCandidates([]);setOffset(0);setHasMore(false);setSearched(false);setCreateEditor(null);};
  const addExisting=async(candidate:AssociationCandidate)=>{if(!workspace||!picker)return;if(await act(()=>newDesignApi.addExistingAssociation(book.id,primary.id,{slotKey:picker.key,cardId:candidate.id,expectedInstanceRevision:workspace.instanceRevision,idempotencyKey:crypto.randomUUID()}),`已加入“${candidate.title}”。`))setPicker(null);};
  const beginCreate=async(typeKey:string)=>{const type=typeByKey.get(typeKey);if(!type)return;setBusy(true);try{const versions=await newDesignApi.listCardTypeVersions(type.id);const version=versions.find((item)=>item.id===type.currentVersionId)??versions[0];if(!version)throw new Error("这个内容类型还没有已发布规格。");const resolution=resolveBusinessForm(type,version.fields,forms,formVersions);setCreateEditor({type,version,title:"",values:defaultValues(resolution.fields)});}catch(reason){setError(reason instanceof Error?reason.message:"无法打开新建表单。");}finally{setBusy(false);}};
  const createAndAdd=async()=>{if(!workspace||!picker||!createEditor)return;const resolution=resolveBusinessForm(createEditor.type,createEditor.version.fields,forms,formVersions);const formVersionId=resolution.formId?forms.find((form)=>form.id===resolution.formId)?.currentVersionId??null:null;const saved=await act(()=>newDesignApi.createAndAddAssociation(book.id,primary.id,{slotKey:picker.key,cardTypeId:createEditor.type.id,title:createEditor.title,values:createEditor.values,expectedInstanceRevision:workspace.instanceRevision,formVersionId,formResolutionKind:resolution.source,idempotencyKey:crypto.randomUUID()}),`已新建并加入“${createEditor.title}”。`);if(saved){setCreateEditor(null);setPicker(null);await onSourcesChanged();}};
  const remove=async(item:AssociationItem)=>{if(!window.confirm(`移除与“${item.source.title}”的关联？来源资料不会删除；当前表单中的局部信息会离开页面，但历史版本仍保留。`))return;await act(()=>newDesignApi.removeAssociation(book.id,item.id,{expectedRevision:item.revision,idempotencyKey:crypto.randomUUID()}),`已移除与“${item.source.title}”的关联，来源资料和历史均已保留。`);};
  const reorder=async(slotKey:string,item:AssociationItem,direction:-1|1)=>{if(!workspace)return;const list=workspace.items.filter((entry)=>entry.slotKey===slotKey).sort((a,b)=>a.sortOrder-b.sortOrder);const index=list.findIndex((entry)=>entry.id===item.id),target=index+direction;if(index<0||target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];await act(()=>newDesignApi.reorderAssociations(book.id,primary.id,{items:list.map((entry)=>({mountId:entry.id,expectedRevision:entry.revision})),idempotencyKey:crypto.randomUUID()}),"关联顺序已保存。");};
  const saveLocal=async(item:AssociationItem)=>{if(!workspace)return;await act(()=>newDesignApi.saveAssociationLocalValues(book.id,item.id,{expectedRevision:item.revision,values:drafts[item.id]??{},idempotencyKey:crypto.randomUUID()}),`“${item.source.title}”的关联信息已保存。`);};
  const openSource=async(item:AssociationItem)=>{if(item.sourceArchived)return;setBusy(true);setError("");try{const type=cardTypes.find((entry)=>entry.id===item.source.cardTypeId);if(!type)throw new Error("来源资料的内容类型已不可用。");const versions=await newDesignApi.listCardTypeVersions(type.id);const version=versions.find((entry)=>entry.id===item.source.typeVersionId)??versions[0];if(!version)throw new Error("来源资料的填写规格已不可用。");setSourceEditor({item,type,version,title:item.source.title,values:item.source.values});}catch(reason){setError(reason instanceof Error?reason.message:"无法打开来源资料。");}finally{setBusy(false);}};
  const saveSource=async()=>{if(!sourceEditor)return;setBusy(true);setError("");try{const resolution=resolveBusinessForm(sourceEditor.type,sourceEditor.version.fields,forms,formVersions);const formVersionId=resolution.formId?forms.find((form)=>form.id===resolution.formId)?.currentVersionId??null:null;await newDesignApi.updateCard({...sourceEditor.item.source,title:sourceEditor.title,values:sourceEditor.values,formVersionId,formResolutionKind:resolution.source});await load();await onSourcesChanged();setSourceEditor(null);setNotice("来源资料已保存；引用位置已标记为使用了更新版本。");}catch(reason){if(reason instanceof ApiError&&reason.status===409){try{const latest=await newDesignApi.getCard(sourceEditor.item.source.id);setSourceEditor({...sourceEditor,item:{...sourceEditor.item,source:latest}});setError(`来源资料已更新到修订 ${latest.revision}；你的标题和填写仍保留，请比较后再次保存。`);}catch{setError("来源资料已被更新；你的填写仍保留，但最新修订暂时无法读取。");}}else setError(reason instanceof Error?reason.message:"来源资料保存失败，填写内容仍保留。");}finally{setBusy(false);}};
  const openHistory=async(item:AssociationItem)=>{setBusy(true);try{setHistory({item,versions:await newDesignApi.listAssociationHistory(book.id,item.id)});}catch(reason){setError(reason instanceof Error?reason.message:"关联记录暂时无法读取。");}finally{setBusy(false);}};
  if(!workspace&&!error)return <section className="nd-association-panel" aria-live="polite"><p>正在整理关联资料…</p></section>;
  return <section className="nd-association-panel" aria-labelledby="nd-association-title">
    <div className="nd-association-heading"><div><h3 id="nd-association-title">关联资料</h3><p>在表单里引用本书已有资料，或直接新建后加入。来源资料始终独立保存。</p></div><span>{workspace?.items.length??0} 条</span></div>
    {workspace?.slots.length===0?<div className="nd-empty nd-empty-compact">当前已发布填写规格没有配置关联资料。</div>:workspace?.slots.map((slot)=>{const items=workspace.items.filter((item)=>item.slotKey===slot.key).sort((a,b)=>a.sortOrder-b.sortOrder);return <section className="nd-association-slot" key={slot.key} aria-labelledby={`slot-${slot.key}`}>
      <div><span><strong id={`slot-${slot.key}`}>{slot.name}</strong><small>{slot.sectionName}{slot.relationName?` · ${slot.relationName}${slot.relationDirection==="directed"?"（有方向）":"（双向）"}`:""} · 已加入 {items.length}/{slot.max}</small></span><button className="nd-button nd-button-secondary" type="button" disabled={busy||items.length>=slot.max} onClick={()=>openPicker(slot)}>＋ 添加关联资料</button></div>
      {items.length===0?<p>还没有关联资料。可按标题或类型从本书中查找。</p>:items.map((item,index)=>{const localFields=fieldsOf(item);return <article className="nd-association-item" key={item.id}>
        <header><span><strong>{item.source.title}</strong><small>{item.source.cardTypeName} · 修订 {item.source.revision} · 被引用 {item.referenceCount} 次</small></span><span className="nd-association-badges">{item.sourceUpdated&&<i>来源有更新</i>}{item.sourceArchived&&<i className="is-muted">来源已归档 · 只读</i>}</span></header>
        <p>{item.sourceUpdated?`当前关联仍引用修订 ${item.attachedSourceRevision}，可查看来源后决定是否调整。`:"当前引用与来源资料一致。"}</p>
        {localFields.length>0&&<DynamicForm
          fields={localFields}
          values={drafts[item.id]??item.localValues}
          scopeLabelByKey={Object.fromEntries(localFields.map((field)=>[field.key,"仅此关联"]))}
          onChange={(values)=>setDrafts((current)=>({...current,[item.id]:values}))}
        />}
        <footer><span><button className="nd-text-button" type="button" disabled={busy||item.sourceArchived} onClick={()=>void openSource(item)}>{item.sourceArchived?"来源已归档":"查看／编辑来源"}</button>{item.sourceUpdated&&!item.sourceArchived&&<button className="nd-text-button" type="button" disabled={busy} onClick={()=>void act(()=>newDesignApi.refreshAssociationSource(book.id,item.id,{expectedRevision:item.revision,idempotencyKey:crypto.randomUUID()}),`已采用“${item.source.title}”的最新来源版本。`)}>采用最新来源</button>}<button className="nd-text-button" type="button" onClick={()=>void openHistory(item)}>查看关联记录</button><button className="nd-text-button" type="button" onClick={()=>setLocalFieldTarget(item)}>＋ 添加此关联的信息</button></span><span><button className="nd-text-button" type="button" aria-label={`上移 ${item.source.title}`} disabled={busy||index===0} onClick={()=>void reorder(slot.key,item,-1)}>上移</button><button className="nd-text-button" type="button" aria-label={`下移 ${item.source.title}`} disabled={busy||index===items.length-1} onClick={()=>void reorder(slot.key,item,1)}>下移</button><button className="nd-text-button is-danger" type="button" disabled={busy} onClick={()=>void remove(item)}>移除关联</button>{localFields.length>0&&<button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void saveLocal(item)}>保存关联信息</button>}</span></footer>
      </article>;})}
    </section>;})}
    <div aria-live="polite">{error&&<p className="nd-message is-error">{error}{error.includes("刷新")&&" 当前填写没有被清空，可读取最新数据后再次提交。"}</p>}{error.includes("刷新")&&<button className="nd-text-button" type="button" disabled={busy} onClick={()=>void load().then(()=>{setError("");setNotice("已读取最新关联状态，尚未保存的局部信息仍保留。");})}>读取最新关联状态</button>}{notice&&<p className="nd-message is-success">{notice}</p>}</div>

    {picker&&<div className="nd-dialog-backdrop" role="presentation" onMouseDown={()=>setPicker(null)}><section className="nd-association-dialog" role="dialog" aria-modal="true" aria-labelledby="nd-picker-title" onKeyDown={(event)=>{if(event.key==="Escape")setPicker(null);}} onMouseDown={(event)=>event.stopPropagation()}><div className="nd-section-heading"><div><p className="nd-kicker">{picker.name}</p><h2 id="nd-picker-title" ref={dialogHeading} tabIndex={-1}>添加关联资料</h2></div><button className="nd-dialog-close" type="button" aria-label="关闭关联资料选择" onClick={()=>setPicker(null)}>×</button></div>{createEditor?(()=>{const resolution=resolveBusinessForm(createEditor.type,createEditor.version.fields,forms,formVersions);return <div className="nd-association-create"><button className="nd-text-button" type="button" onClick={()=>setCreateEditor(null)}>← 返回本书资料</button><label className="nd-control"><span>资料标题 <b aria-label="必填">*</b></span><input autoFocus value={createEditor.title} onChange={(event)=>setCreateEditor({...createEditor,title:event.target.value})}/></label><DynamicForm fields={resolution.fields} values={createEditor.values} onChange={(values)=>setCreateEditor({...createEditor,values})}/><div className="nd-editor-actions"><button className="nd-button nd-button-secondary" type="button" onClick={()=>setCreateEditor(null)}>取消</button><button className="nd-button nd-button-primary" type="button" disabled={busy||!createEditor.title.trim()} onClick={()=>void createAndAdd()}>新建并加入</button></div></div>;})():<><form className="nd-association-search" onSubmit={(event)=>{event.preventDefault();void search();}}><label className="nd-control"><span>搜索本书资料</span><input autoFocus value={query} placeholder="输入标题或内容类型" onChange={(event)=>setQuery(event.target.value)}/></label><button className="nd-button nd-button-secondary" type="submit" disabled={busy}>搜索</button></form><div className="nd-association-create-row"><span>没有合适的资料？</span>{picker.allowedTypeKeys.filter((key)=>typeByKey.has(key)).map((key)=><button className="nd-text-button" type="button" key={key} onClick={()=>void beginCreate(key)}>新建{typeByKey.get(key)?.name}</button>)}</div><div className="nd-association-results">{candidates.length===0?<p>{searched?`没有找到“${query||"全部"}”对应的可用资料。可以换一个标题或类型词，也可以直接新建。`:"输入关键词查找；搜索结果只包含本书内、类型相符、尚未选中的有效资料。"}</p>:candidates.map((candidate)=><article key={candidate.id}><span><strong>{candidate.title}</strong><small>{candidate.typeName} · 修订 {candidate.revision} · 被引用 {candidate.referenceCount} 次</small><p>{summaryText(candidate)}</p></span><button className="nd-button nd-button-secondary" type="button" disabled={busy} onClick={()=>void addExisting(candidate)}>加入</button></article>)}</div>{hasMore&&<button className="nd-text-button" type="button" disabled={busy} onClick={()=>void search(offset+12,true)}>加载更多</button>}</>}</section></div>}
    {sourceEditor&&(()=>{const resolution=resolveBusinessForm(sourceEditor.type,sourceEditor.version.fields,forms,formVersions);return <div className="nd-dialog-backdrop" role="presentation" onMouseDown={()=>setSourceEditor(null)}><section className="nd-association-dialog" role="dialog" aria-modal="true" aria-labelledby="nd-source-title" onMouseDown={(event)=>event.stopPropagation()}><div className="nd-section-heading"><div><p className="nd-kicker">来源资料</p><h2 id="nd-source-title" ref={dialogHeading} tabIndex={-1}>查看／编辑 {sourceEditor.item.source.title}</h2><p>{hasUnsavedChanges?"当前主表单尚有未保存内容；关闭此窗口后仍会保留。":"此处保存只修改来源资料，不改写当前主表单。"}</p></div><button className="nd-dialog-close" type="button" aria-label="关闭来源资料" onClick={()=>setSourceEditor(null)}>×</button></div><label className="nd-control"><span>资料标题 <b aria-label="必填">*</b></span><input value={sourceEditor.title} onChange={(event)=>setSourceEditor({...sourceEditor,title:event.target.value})}/></label><DynamicForm fields={resolution.fields} values={sourceEditor.values} onChange={(values)=>setSourceEditor({...sourceEditor,values})}/>{error&&<p className="nd-message is-error" aria-live="assertive">{error}</p>}<div className="nd-editor-actions"><button className="nd-button nd-button-secondary" type="button" onClick={()=>setSourceEditor(null)}>取消</button><button className="nd-button nd-button-primary" type="button" disabled={busy||!sourceEditor.title.trim()} onClick={()=>void saveSource()}>保存来源资料</button></div></section></div>;})()}
    {localFieldTarget&&<AddInformationDialog bookId={book.id} cardType={cardTypes.find((type)=>type.id===primary.cardTypeId)??cardTypes[0]} card={null} association={localFieldTarget} onClose={()=>setLocalFieldTarget(null)} onCreated={async()=>{await load();setNotice("这项信息已加入当前关联，不会写回来源资料。");}}/>}
    {history&&<div className="nd-dialog-backdrop" role="presentation" onMouseDown={()=>setHistory(null)}><section className="nd-association-dialog" role="dialog" aria-modal="true" aria-labelledby="nd-association-history-title" onMouseDown={(event)=>event.stopPropagation()}><div className="nd-section-heading"><div><p className="nd-kicker">只读记录</p><h2 id="nd-association-history-title" ref={dialogHeading} tabIndex={-1}>{history.item.source.title} · 关联历史</h2></div><button className="nd-dialog-close" type="button" aria-label="关闭关联历史" onClick={()=>setHistory(null)}>×</button></div><div className="nd-history-list">{history.versions.map((version)=><article key={version.id}><div><strong>关联修订 {version.revision}</strong><span>{version.status==="active"?"使用中":"已移除"} · 来源修订 {version.sourceRevision}</span></div><time>{new Date(version.createdAt).toLocaleString("zh-CN")}</time></article>)}</div></section></div>}
  </section>;
}
